{
  "hash": "e92a676ccbe3c20b45e3bcbf0e00936c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 52 篇 · 结构方程模型：从环境因子到微生物再到表型\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**用预先声明的分段结构方程模型（piecewise SEM）检验“气候 → 土壤化学 → 微生物多样性 → 土壤有机碳”路径与数据是否相容，并用 PLS-PM 做估计器敏感性分析。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`，以及逐样本实测的 `environment.tsv`；后者必须包含环境因子和表型，不能由 OTU 表虚构。  \n> **预计资源：**真实示例为 13,628 个 OTU、90 个样本、4 个实测环境变量和 1 个实测表型；普通笔记本约 3–8 分钟，内存低于 1 GB。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n环境微生物组论文常见一张由方框和箭头组成的路径图：环境因子指向菌群，菌群再指向生态功能或宿主表型，箭头旁标标准化系数和 P 值。它试图同时回答：\n\n- 哪些直接路径与数据一致？\n- 环境与表型的关联是否可能经过微生物指标传递？\n- 预设图遗漏的独立关系是否足以拒绝整个结构？\n\n本例使用中国湿地土壤公开 16S 数据。原研究覆盖内陆、沿海和青藏高原湿地，并测量 pH、电导率、温度、降水和总有机碳（TOC）；`microeco` 以标准 OTU、分类、样本和环境表分发其中的示例。[数据研究（An et al., 2019）](https://doi.org/10.1016/j.geoderma.2018.09.035)与[`microeco` 软件论文](https://doi.org/10.1093/femsec/fiaa255)提供出处。\n\n这里重绘自己的路径图，不复制论文原图。分析前把结构写成：气候可直接影响土壤化学、Shannon 和 TOC；土壤化学可影响 Shannon 与 TOC；Shannon 可影响 TOC；湿地组别进入所有分量模型作为调整变量。\n\n::: {.callout-important title=\"SEM 的合格结论是“相容”，不是“证实因果”\"}\n全局拟合未拒绝一个图，只说明该图蕴含的条件独立关系没有与当前数据明显冲突。反向箭头、共同原因、测量误差或另一张竞争图也可能得到相似拟合；横断面 SEM 不会自动创造时间顺序。\n:::\n\n## 理论：SEM 把什么放进同一张图 {#sec-theory}\n\n传统单个回归只估计一个结局。分段 SEM 把多个回归连接起来，例如：\n\n\\[\n\\begin{aligned}\n\\mathrm{pH} &\\leftarrow \\mathrm{Temperature}+\\mathrm{Precipitation}+\\mathrm{Group},\\\\\n\\log(\\mathrm{EC}) &\\leftarrow \\mathrm{Temperature}+\\mathrm{Precipitation}+\\mathrm{Group},\\\\\n\\mathrm{Shannon} &\\leftarrow \\mathrm{pH}+\\log(\\mathrm{EC})+\\mathrm{Climate}+\\mathrm{Group},\\\\\n\\log(\\mathrm{TOC}) &\\leftarrow \\mathrm{Shannon}+\\mathrm{pH}+\\log(\\mathrm{EC})+\\mathrm{Climate}+\\mathrm{Group}.\n\\end{aligned}\n\\]\n\n`piecewiseSEM` 对每个响应拟合独立模型，再用 directed separation（定向分离）检查图所蕴含的缺失路径。Fisher's C 的小 P 值表示至少有应独立的变量仍存在条件关联，因而拒绝当前图；大 P 值不代表图唯一或为真。\n\n<details>\n<summary><strong>深入：piecewise SEM、协方差型 SEM 与 PLS-PM 怎么选</strong></summary>\n\n**piecewise SEM** 允许每个分量使用线性模型、广义模型或混合模型，适合生态学中的层级设计和中等样本量。它的全局检验围绕图的条件独立声明。\n\n**协方差型 SEM**（如 `lavaan`）直接拟合整体协方差结构，适合有明确潜变量测量模型且样本量足够的场景。微生物组常见的稀疏成分数据和小样本会使模型不稳定；不能用拟合指标掩盖不收敛或不识别。\n\n**PLS-PM** 偏向预测和方差解释，对分布要求较弱，也可构建多指标 block；但传统全局拟合指标不能替代因果结构检验。本例只把它用作“换一种估计器，关键路径是否同方向且区间排除零”的敏感性分析。\n\n</details>\n\n### 三条建模底线\n\n1. **箭头在看数据前由理论、时间顺序和设计确定。** 不从相关矩阵自动搜索一张最好看的网络。\n2. **调整变量不能被误叫作可干预暴露。** 本例 `Group` 控制宏观湿地差异，但不能解释成随机处理。\n3. **一个 alpha 指标不是“微生物组潜变量”。** Shannon 只描述多样性；若科学问题是特定功能或组成轴，应预先定义更合适且可验证的指标。\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、获取真实数据和定义作图函数</strong></summary>\n\n首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"piecewiseSEM\", \"plspm\", \"ggplot2\", \"patchwork\", \"scales\",\n  \"digest\", \"svglite\", \"ragg\"\n))\n```\n:::\n\n\n数据固定使用 `microeco 2.0.0` 源码包中的真实表。下面下载、核对 SHA-256，并导出三件套和环境表。\n\n\n::: {.cell}\n\n```{.r .cell-code}\narchive <- \"data/raw/microeco_2.0.0.tar.gz\"\nurl <- paste0(\n  \"https://cran.r-project.org/src/contrib/Archive/microeco/\",\n  \"microeco_2.0.0.tar.gz\"\n)\nexpected <- paste0(\n  \"454a3b71ceeea86bdd54f475a12b5bac\",\n  \"9c3b124f663b8dc6e560827fca89ebfd\"\n)\ndir.create(\"data/raw\", recursive = TRUE, showWarnings = FALSE)\ndir.create(\"data/small\", recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(archive)) download.file(url, archive, mode = \"wb\")\nstopifnot(identical(\n  digest::digest(archive, algo = \"sha256\", file = TRUE), expected\n))\n\nfiles <- c(\n  \"microeco/data/otu_table_16S.RData\",\n  \"microeco/data/taxonomy_table_16S.RData\",\n  \"microeco/data/sample_info_16S.RData\",\n  \"microeco/data/env_data_16S.RData\"\n)\ntmp <- tempfile(\"microeco-\")\ndir.create(tmp)\nutils::untar(archive, files = files, exdir = tmp)\ne <- new.env(parent = emptyenv())\nfor (f in files) load(file.path(tmp, f), envir = e)\nwrite_piece <- function(x, id, path) {\n  out <- data.frame(setNames(list(rownames(x)), id), x, check.names = FALSE)\n  write.table(out, path, sep = \"\\t\", quote = FALSE, row.names = FALSE, na = \"\")\n}\nwrite_piece(e$otu_table_16S, \"FeatureID\", \"data/small/otutab.tsv\")\nwrite_piece(e$taxonomy_table_16S, \"FeatureID\", \"data/small/taxonomy.tsv\")\nwrite_piece(e$sample_info_16S, \"SampleID\", \"data/small/metadata.tsv\")\nwrite_piece(e$env_data_16S, \"SampleID\", \"data/small/environment.tsv\")\nunlink(tmp, recursive = TRUE)\n```\n:::\n\n\n出版级作图函数直接内联：\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.libPaths(c(\".r-lib\", .libPaths()))\nlibrary(piecewiseSEM)\nlibrary(plspm)\nlibrary(ggplot2)\nlibrary(patchwork)\n\nset.seed(20260752)\nfont_pub <- \"DejaVu Sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(colour = \"#E6E6E6\", linewidth = 0.25),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      legend.position = \"top\", legend.key = ggplot2::element_blank()\n    )\n}\nsave_pub <- function(plot, file_base, width = 180, height = 120,\n                     units = \"mm\", dpi = 600) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(paste0(file_base, \".pdf\"), plot, width = width,\n                  height = height, units = units,\n                  device = grDevices::cairo_pdf, family = font_pub, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".svg\"), plot, width = width,\n                  height = height, units = units, device = svglite::svglite,\n                  bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".png\"), plot, width = width,\n                  height = height, units = units, dpi = dpi,\n                  device = ragg::agg_png, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".tiff\"), plot, width = width,\n                  height = height, units = units, dpi = dpi,\n                  device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\")\n  invisible(plot)\n}\n```\n:::\n\n\n整套项目可使用内容相同的 `R/theme_pub.R`；单独复制文章时保留上面的函数。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取三件套与实测环境/表型表\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- as.matrix(read.delim(\n  \"data/small/otutab.tsv\", row.names = 1, check.names = FALSE\n))\ntaxonomy <- read.delim(\n  \"data/small/taxonomy.tsv\", row.names = 1, check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/metadata.tsv\", row.names = 1, check.names = FALSE\n)\nenvironment <- read.delim(\n  \"data/small/environment.tsv\", row.names = 1, check.names = FALSE\n)\nstorage.mode(otutab) <- \"numeric\"\nsample_ids <- intersect(\n  colnames(otutab), intersect(rownames(metadata), rownames(environment))\n)\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  length(sample_ids) == 90,\n  all(colSums(otutab[, sample_ids, drop = FALSE]) > 0)\n)\notutab <- otutab[, sample_ids, drop = FALSE]\nmetadata <- metadata[sample_ids, , drop = FALSE]\nenvironment <- environment[sample_ids, , drop = FALSE]\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(taxonomy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\nOTU_706  k__Bacteria                     p__Actinobacteria\n                         Class               Order               Family\nOTU_4272            c__Bacilli       o__Bacillales                  f__\nOTU_236                    c__                 o__                  f__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__\nOTU_32                     c__                 o__                  f__\nOTU_706      c__Actinobacteria       o__Frankiales   f__Nakamurellaceae\n                  Genus Species\nOTU_4272            g__     s__\nOTU_236             g__     s__\nOTU_399             g__     s__\nOTU_1556            g__     s__\nOTU_32              g__     s__\nOTU_706  g__Nakamurella     s__\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(environment[, c(\"pH\", \"Conductivity\", \"TOC\", \"Temperature\", \"Precipitation\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     pH Conductivity   TOC Temperature Precipitation\nS1 5.10        108.7 10.02        -4.2           445\nS2 6.53         31.2  6.94        -4.3           449\nS3 5.13         68.2  8.38        -4.3           449\nS4 5.81         64.4  8.17        -4.3           449\nS5 5.50         33.5  8.41        -4.3           449\nS6 5.37         33.3  8.13        -4.3           449\n```\n\n\n:::\n:::\n\n\n`environment.tsv` 原有 200 行，只有与三件套共同的 90 个样本进入 SEM。任何合并后的静默丢样都应打印并解释。\n\n### 2. 构建预先声明的分析表\n\n对偏斜的电导率和 TOC 做 `log1p`，再把连续变量标准化，使不同量纲的路径系数可比较。`Group` 用原始研究的三个英文代码 `CW/IW/TW`，并进入每个分量模型。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelative <- sweep(otutab, 2, colSums(otutab), \"/\")\nshannon <- -colSums(ifelse(relative > 0, relative * log(relative), 0))\nz <- function(x) as.numeric(scale(x))\n\nsem_data <- data.frame(\n  SampleID = sample_ids,\n  Group = factor(metadata$Group, levels = c(\"CW\", \"IW\", \"TW\")),\n  Shannon = shannon[sample_ids],\n  TOC = environment$TOC,\n  pH = environment$pH,\n  Conductivity = environment$Conductivity,\n  Temperature = environment$Temperature,\n  Precipitation = environment$Precipitation,\n  ShannonZ = z(shannon[sample_ids]),\n  TOCZ = z(log1p(environment$TOC)),\n  pHZ = z(environment$pH),\n  LogECZ = z(log1p(environment$Conductivity)),\n  TempZ = z(environment$Temperature),\n  PrecipZ = z(environment$Precipitation)\n)\nsummary(sem_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   SampleID         Group      Shannon           TOC               pH        \n Length:90          CW:30   Min.   :4.930   Min.   : 0.270   Min.   : 5.000  \n Class :character   IW:30   1st Qu.:6.335   1st Qu.: 1.633   1st Qu.: 7.147  \n Mode  :character   TW:30   Median :6.665   Median : 3.510   Median : 8.015  \n                            Mean   :6.567   Mean   : 7.587   Mean   : 7.785  \n                            3rd Qu.:6.873   3rd Qu.: 8.160   3rd Qu.: 8.695  \n                            Max.   :7.310   Max.   :67.530   Max.   :10.620  \n  Conductivity       Temperature     Precipitation       ShannonZ      \n Min.   :   13.10   Min.   :-4.300   Min.   :  39.0   Min.   :-3.5995  \n 1st Qu.:   88.28   1st Qu.: 0.700   1st Qu.: 401.0   1st Qu.:-0.5105  \n Median :  227.50   Median : 4.000   Median : 550.0   Median : 0.2163  \n Mean   : 1013.42   Mean   : 6.984   Mean   : 660.9   Mean   : 0.0000  \n 3rd Qu.: 1629.50   3rd Qu.:12.200   3rd Qu.: 668.0   3rd Qu.: 0.6733  \n Max.   :10800.00   Max.   :24.400   Max.   :1837.0   Max.   : 1.6343  \n      TOCZ              pHZ              LogECZ            TempZ        \n Min.   :-1.5815   Min.   :-2.1025   Min.   :-1.9056   Min.   :-1.2012  \n 1st Qu.:-0.7632   1st Qu.:-0.4813   1st Qu.:-0.7654   1st Qu.:-0.6690  \n Median :-0.1585   Median : 0.1735   Median :-0.1843   Median :-0.3177  \n Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000  \n 3rd Qu.: 0.6376   3rd Qu.: 0.6869   3rd Qu.: 1.0298   3rd Qu.: 0.5552  \n Max.   : 2.8978   Max.   : 2.1400   Max.   : 2.1985   Max.   : 1.8539  \n    PrecipZ       \n Min.   :-1.3665  \n 1st Qu.:-0.5710  \n Median :-0.2436  \n Mean   : 0.0000  \n 3rd Qu.: 0.0157  \n Max.   : 2.5845  \n```\n\n\n:::\n:::\n\n\n### 3. 拟合完整的分段 SEM\n\n公式就是 DAG 的可执行版本。每条没写入公式的路径都隐含一个条件独立声明，因此不能拟合后再偷偷补箭头而不把它标为探索性分析。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmain_models <- list(\n  acidity = lm(pHZ ~ TempZ + PrecipZ + Group, data = sem_data),\n  salinity = lm(LogECZ ~ TempZ + PrecipZ + Group, data = sem_data),\n  microbiome = lm(\n    ShannonZ ~ pHZ + LogECZ + TempZ + PrecipZ + Group,\n    data = sem_data\n  ),\n  carbon = lm(\n    TOCZ ~ ShannonZ + pHZ + LogECZ + TempZ + PrecipZ + Group,\n    data = sem_data\n  )\n)\nsem_main <- piecewiseSEM::psem(\n  main_models$acidity,\n  main_models$salinity,\n  main_models$microbiome,\n  main_models$carbon,\n  data = sem_data\n)\n\npiecewiseSEM::fisherC(sem_main)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fisher.C df P.Value\n1    4.514  2   0.105\n```\n\n\n:::\n\n```{.r .cell-code}\npiecewiseSEM::dSep(sem_main)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Independ.Claim Test.Type DF Crit.Value   P.Value \n1 LogECZ ~ pHZ + ...      coef 84   1.640417 0.1046582 \n```\n\n\n:::\n\n```{.r .cell-code}\npiecewiseSEM::coefs(sem_main)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Response  Predictor Estimate Std.Error DF Crit.Value P.Value Std.Estimate\n1       pHZ      TempZ   1.1626    0.2426 85     4.7913  0.0000            -\n2       pHZ    PrecipZ  -1.1352    0.1705 85    -6.6580  0.0000            -\n3       pHZ      Group        -         -  2     2.1115  0.1274            -\n4       pHZ Group = CW  -0.3428    0.2675 85    -1.2815  0.2035            -\n5       pHZ Group = IW   0.0469    0.2109 85     0.2223  0.8246            -\n6       pHZ Group = TW    0.296    0.1652 85     1.7914  0.0768            -\n7    LogECZ      TempZ   0.7486    0.1906 85     3.9283  0.0002            -\n8    LogECZ    PrecipZ  -0.4941    0.1339 85    -3.6896  0.0004            -\n9    LogECZ      Group        -         -  2     5.3339  0.0066            -\n10   LogECZ Group = IW  -0.4963    0.1656 85    -2.9964  0.0036            -\n11   LogECZ Group = TW  -0.0833    0.1298 85    -0.6422  0.5225            -\n12   LogECZ Group = CW   0.5796    0.2101 85     2.7586  0.0071            -\n13 ShannonZ        pHZ   0.2967    0.1268 83     2.3404  0.0217            -\n14 ShannonZ     LogECZ  -0.4908    0.1614 83    -3.0409  0.0032            -\n15 ShannonZ      TempZ   0.3057    0.3286 83     0.9305  0.3548            -\n16 ShannonZ    PrecipZ   0.5275     0.248 83     2.1270  0.0364            -\n17 ShannonZ      Group        -         -  2     2.1793  0.1196            -\n18 ShannonZ Group = CW  -0.6408    0.3268 83    -1.9607  0.0533            -\n19 ShannonZ Group = TW    0.284    0.1947 83     1.4591  0.1483            -\n20 ShannonZ Group = IW   0.3567    0.2559 83     1.3940  0.1670            -\n21     TOCZ   ShannonZ  -0.0123    0.0718 82    -0.1710  0.8647            -\n22     TOCZ        pHZ  -0.6891    0.0856 82    -8.0465  0.0000            -\n23     TOCZ     LogECZ   0.4871    0.1113 82     4.3751  0.0000            -\n24     TOCZ      TempZ  -1.0433    0.2161 82    -4.8280  0.0000            -\n25     TOCZ    PrecipZ   0.6498    0.1666 82     3.8998  0.0002            -\n26     TOCZ      Group        -         -  2    11.5455  0.0000            -\n27     TOCZ Group = CW  -0.2661    0.2187 82    -1.2169  0.2271            -\n28     TOCZ Group = IW   -0.221    0.1694 82    -1.3051  0.1955            -\n29     TOCZ Group = TW   0.4872     0.129 82     3.7772  0.0003            -\n      \n1  ***\n2  ***\n3     \n4     \n5     \n6     \n7  ***\n8  ***\n9   **\n10  **\n11    \n12  **\n13   *\n14  **\n15    \n16   *\n17    \n18    \n19    \n20    \n21    \n22 ***\n23 ***\n24 ***\n25 ***\n26 ***\n27    \n28    \n29 ***\n```\n\n\n:::\n:::\n\n\n完整图的 Fisher's C = 4.514，df = 2，P = 0.105：当前数据没有拒绝图蕴含的条件独立结构。关键的 `Shannon → log TOC` 标准化系数为 −0.012（95% CI −0.155 至 0.131，P = 0.865），没有支持微生物多样性与 TOC 的直接路径。\n\n### 4. 提取标准化路径并重绘 DAG\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_paths <- function(model, response, model_name) {\n  x <- summary(model)$coefficients\n  x <- x[!grepl(\"^\\\\(Intercept\\\\)$|^Group\", rownames(x)), , drop = FALSE]\n  critical <- qt(0.975, df = df.residual(model))\n  data.frame(\n    Model = model_name, Response = response, Predictor = rownames(x),\n    Estimate = x[, \"Estimate\"],\n    Lower = x[, \"Estimate\"] - critical * x[, \"Std. Error\"],\n    Upper = x[, \"Estimate\"] + critical * x[, \"Std. Error\"],\n    PValue = x[, \"Pr(>|t|)\"], row.names = NULL\n  )\n}\nmain_paths <- do.call(rbind, list(\n  extract_paths(main_models$acidity, \"pH\", \"Full direct-path DAG\"),\n  extract_paths(main_models$salinity, \"log Conductivity\", \"Full direct-path DAG\"),\n  extract_paths(main_models$microbiome, \"Shannon\", \"Full direct-path DAG\"),\n  extract_paths(main_models$carbon, \"log TOC\", \"Full direct-path DAG\")\n))\nmicrobe_carbon <- main_paths[\n  main_paths$Response == \"log TOC\" & main_paths$Predictor == \"ShannonZ\", ]\n\nnodes <- data.frame(\n  X = c(0, 1.4, 2.8, 4.2), Y = 1.15,\n  Label = c(\n    \"Climate\\nTemperature + precipitation\",\n    \"Soil chemistry\\npH + conductivity\",\n    \"Microbiome\\nShannon diversity\",\n    \"Phenotype\\nSoil organic carbon\"\n  )\n)\nedges <- data.frame(\n  X = c(0.38, 0.35, 1.78, 1.75, 3.18),\n  XEnd = c(1.02, 2.42, 2.42, 3.82, 3.82),\n  Y = c(1.15, 1.28, 1.15, 1.02, 1.15),\n  YEnd = c(1.15, 1.28, 1.15, 1.02, 1.15),\n  Type = c(\"Direct\", \"Direct\", \"Direct\", \"Direct\", \"Focal\")\n)\np_dag <- ggplot() +\n  geom_segment(\n    data = edges, aes(X, Y, xend = XEnd, yend = YEnd, colour = Type),\n    linewidth = 1,\n    arrow = grid::arrow(length = grid::unit(2.4, \"mm\"), type = \"closed\")\n  ) +\n  geom_label(\n    data = nodes, aes(X, Y, label = Label), size = 3.3,\n    lineheight = 1.05, label.size = 0.35, fill = \"white\"\n  ) +\n  annotate(\n    \"label\", x = 3.45, y = 1.52,\n    label = sprintf(\"Shannon -> carbon\\nbeta = %.3f, P = %.3f\",\n                    microbe_carbon$Estimate, microbe_carbon$PValue),\n    size = 3.2, fill = \"#F7F7F7\", label.size = 0.3\n  ) +\n  annotate(\n    \"text\", x = 2.1, y = 0.68,\n    label = \"Wetland group adjusted in every component model\",\n    colour = \"#666666\", size = 3.1\n  ) +\n  scale_colour_manual(values = c(\n    Direct = pal_pub[[\"grey\"]], Focal = pal_pub[[\"vermillion\"]]\n  )) +\n  coord_cartesian(xlim = c(-0.55, 4.75), ylim = c(0.55, 1.75), clip = \"off\") +\n  labs(\n    title = \"A pre-specified path model separates direct and mediated routes\",\n    subtitle = \"A compatible graph is not proof that any arrow is causal\",\n    colour = \"Path role\"\n  ) +\n  theme_void(base_family = font_pub) +\n  theme(\n    legend.position = \"top\", plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(colour = \"#555555\", size = 10),\n    plot.margin = margin(10, 15, 10, 15)\n  )\np_dag\n```\n\n::: {.cell-output-display}\n![](52-structural-equation-model_files/figure-html/unnamed-chunk-7-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_dag, \"figures/52-structural-equation-model/52-1-prespecified-dag\",\n         height = 100)\n```\n:::\n\n\n### 5. 画完整路径系数\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_paths <- main_paths\nplot_paths$Response <- factor(\n  plot_paths$Response,\n  levels = c(\"pH\", \"log Conductivity\", \"Shannon\", \"log TOC\")\n)\nplot_paths$PredictorLabel <- factor(\n  plot_paths$Predictor,\n  levels = rev(c(\"TempZ\", \"PrecipZ\", \"pHZ\", \"LogECZ\", \"ShannonZ\")),\n  labels = rev(c(\"Temperature\", \"Precipitation\", \"pH\", \"log Conductivity\", \"Shannon\"))\n)\np_paths <- ggplot(plot_paths, aes(Estimate, PredictorLabel, colour = PValue < 0.05)) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_errorbarh(aes(xmin = Lower, xmax = Upper), height = 0) +\n  geom_point(size = 2) +\n  facet_wrap(~ Response, scales = \"free_y\", ncol = 2) +\n  scale_colour_manual(\n    values = c(`FALSE` = pal_pub[[\"grey\"]], `TRUE` = pal_pub[[\"blue\"]]),\n    labels = c(`FALSE` = \"No\", `TRUE` = \"Yes\")\n  ) +\n  labs(\n    title = \"Standardised component-model paths\",\n    subtitle = \"Intervals are 95% confidence intervals; habitat group coefficients are omitted\",\n    x = \"Standardised coefficient\", y = \"Predictor\", colour = \"P < 0.05\"\n  ) + theme_pub(9)\np_paths\n```\n\n::: {.cell-output-display}\n![](52-structural-equation-model_files/figure-html/unnamed-chunk-8-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_paths, \"figures/52-structural-equation-model/52-2-path-coefficients\",\n         height = 135)\n```\n:::\n\n\n## 审计与升级 {#sec-audit}\n\n### 用竞争图检验“完全中介”的强假设\n\n一个常见但过强的写法是删掉气候到 Shannon 和 TOC 的直接路径，暗示所有作用只能经过 pH/电导率。把这个“中介限定图”明确拟合，而不是从不显著路径倒推出完全中介：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreduced_models <- list(\n  acidity = main_models$acidity,\n  salinity = main_models$salinity,\n  microbiome = lm(ShannonZ ~ pHZ + LogECZ + Group, data = sem_data),\n  carbon = lm(TOCZ ~ ShannonZ + pHZ + LogECZ + Group, data = sem_data)\n)\nsem_reduced <- piecewiseSEM::psem(\n  reduced_models$acidity, reduced_models$salinity,\n  reduced_models$microbiome, reduced_models$carbon,\n  data = sem_data\n)\n\nfit_row <- function(model, label) {\n  f <- piecewiseSEM::fisherC(model)\n  a <- AIC(model)\n  data.frame(\n    Model = label, FisherC = f$Fisher.C, DF = f$df, PValue = f$P.Value,\n    AIC = a$AIC, Parameters = a$K, Samples = a$n\n  )\n}\nsem_fit <- rbind(\n  fit_row(sem_main, \"Full direct-path DAG\"),\n  fit_row(sem_reduced, \"Mediation-only DAG\")\n)\nsem_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Model FisherC DF PValue     AIC Parameters Samples\n1 Full direct-path DAG   4.514  2  0.105 794.226         29      90\n2   Mediation-only DAG  51.796 10  0.000 828.137         25      90\n```\n\n\n:::\n:::\n\n\n中介限定图 Fisher's C = 51.796，df = 10，P < 0.001，被数据明确拒绝。这个结果不是说完整图“被证明”，而是说明删掉气候直接路径后留下了明显未解释关系。\n\n### PLS-PM 作为估计器敏感性分析\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninner <- matrix(\n  0, 5, 5,\n  dimnames = list(\n    c(\"Climate\", \"Acidity\", \"Salinity\", \"Microbiome\", \"Carbon\"),\n    c(\"Climate\", \"Acidity\", \"Salinity\", \"Microbiome\", \"Carbon\")\n  )\n)\ninner[\"Acidity\", \"Climate\"] <- 1\ninner[\"Salinity\", \"Climate\"] <- 1\ninner[\"Microbiome\", c(\"Acidity\", \"Salinity\")] <- 1\ninner[\"Carbon\", c(\"Acidity\", \"Salinity\", \"Microbiome\")] <- 1\nblocks <- list(c(\"TempZ\", \"PrecipZ\"), \"pHZ\", \"LogECZ\", \"ShannonZ\", \"TOCZ\")\n\nset.seed(20260752)\npls_fit <- plspm::plspm(\n  sem_data, inner, blocks,\n  modes = rep(\"A\", 5), scaled = FALSE,\n  boot.val = TRUE, br = 2000\n)\npls_paths <- data.frame(\n  Path = rownames(pls_fit$boot$paths),\n  Estimate = pls_fit$boot$paths[, \"Original\"],\n  Lower = pls_fit$boot$paths[, \"perc.025\"],\n  Upper = pls_fit$boot$paths[, \"perc.975\"],\n  row.names = NULL\n)\npls_fit$gof\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4597259\n```\n\n\n:::\n\n```{.r .cell-code}\npls_paths\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Path    Estimate       Lower      Upper\n1     Climate -> Acidity -0.18581622 -0.38520556  0.1212176\n2    Climate -> Salinity  0.60109277  0.44995841  0.7502763\n3  Acidity -> Microbiome  0.10097202 -0.08322429  0.2921690\n4      Acidity -> Carbon -0.64088475 -0.74396618 -0.5014294\n5 Salinity -> Microbiome -0.30598136 -0.46594354 -0.1311716\n6     Salinity -> Carbon -0.03340378 -0.20625616  0.1615331\n7   Microbiome -> Carbon -0.07065033 -0.25286504  0.1426278\n```\n\n\n:::\n:::\n\n\nPLS-PM 的 GOF 为 0.460，但它不能把箭头升级为因果。更值得看的是路径区间：`Microbiome → Carbon` 估计 −0.071，95% bootstrap 区间 −0.253 至 0.143，仍跨过零，与分段 SEM 的空结果一致。\n\n### 残差与全局结构一起看\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsem_data$PredictedTOCZ <- predict(main_models$carbon)\nsem_data$ResidualTOCZ <- residuals(main_models$carbon)\ngroup_colours <- c(\n  CW = pal_pub[[\"blue\"]], IW = pal_pub[[\"orange\"]], TW = pal_pub[[\"green\"]]\n)\np_diag_a <- ggplot(sem_data, aes(PredictedTOCZ, TOCZ, colour = Group)) +\n  geom_abline(slope = 1, intercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_point(size = 1.8, alpha = 0.8) +\n  scale_colour_manual(values = group_colours) +\n  labs(\n    title = \"A. Observed versus predicted\",\n    x = \"Predicted log TOC (z-score)\", y = \"Observed log TOC (z-score)\",\n    colour = \"Wetland group\"\n  ) + coord_equal() + theme_pub(9)\np_diag_b <- ggplot(sem_data, aes(PredictedTOCZ, ResidualTOCZ, colour = Group)) +\n  geom_hline(yintercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_point(size = 1.8, alpha = 0.8) +\n  geom_smooth(\n    inherit.aes = FALSE,\n    aes(x = PredictedTOCZ, y = ResidualTOCZ),\n    method = \"loess\", se = FALSE, colour = \"#202020\", linewidth = 0.7\n  ) +\n  scale_colour_manual(values = group_colours) +\n  labs(\n    title = \"B. Residual structure\",\n    x = \"Predicted log TOC (z-score)\", y = \"Residual\",\n    colour = \"Wetland group\"\n  ) + theme_pub(9)\np_diagnostics <- p_diag_a + p_diag_b + patchwork::plot_layout(guides = \"collect\") &\n  theme(legend.position = \"top\")\np_diagnostics\n```\n\n::: {.cell-output-display}\n![](52-structural-equation-model_files/figure-html/unnamed-chunk-11-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_diagnostics,\n         \"figures/52-structural-equation-model/52-3-model-diagnostics\",\n         height = 110)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsem_fit$Compatible <- sem_fit$PValue >= 0.05\np_fit <- ggplot(sem_fit, aes(PValue, Model, colour = Compatible)) +\n  geom_vline(xintercept = 0.05, linetype = 2, colour = pal_pub[[\"vermillion\"]]) +\n  geom_segment(aes(x = 0, xend = PValue, yend = Model), linewidth = 0.8) +\n  geom_point(size = 2.8) +\n  scale_x_continuous(limits = c(0, max(0.12, sem_fit$PValue * 1.15))) +\n  scale_colour_manual(\n    values = c(`FALSE` = pal_pub[[\"vermillion\"]], `TRUE` = pal_pub[[\"green\"]]),\n    labels = c(`FALSE` = \"Rejected\", `TRUE` = \"Compatible\")\n  ) +\n  labs(\n    title = \"A. Directed-separation test\", subtitle = \"P < 0.05 rejects the graph\",\n    x = \"Fisher's C P value\", y = NULL, colour = \"Compatible\"\n  ) + theme_pub(9)\npls_paths$PathLabel <- gsub(\" -> \", \"  ->  \", pls_paths$Path, fixed = TRUE)\np_pls <- ggplot(pls_paths, aes(Estimate, reorder(PathLabel, Estimate))) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_errorbarh(aes(xmin = Lower, xmax = Upper), height = 0,\n                 colour = pal_pub[[\"grey\"]]) +\n  geom_point(size = 2, colour = pal_pub[[\"purple\"]]) +\n  labs(\n    title = \"B. PLS-PM estimator audit\",\n    subtitle = \"Percentile intervals from 2,000 sample-level bootstrap draws\",\n    x = \"PLS path coefficient (95% interval)\", y = NULL\n  ) + theme_pub(9)\np_audit <- p_fit + p_pls + patchwork::plot_layout(widths = c(0.8, 1.35))\np_audit\n```\n\n::: {.cell-output-display}\n![](52-structural-equation-model_files/figure-html/unnamed-chunk-12-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_audit, \"figures/52-structural-equation-model/52-4-model-audit\",\n         height = 120)\n```\n:::\n\n\n### 今天还应补哪些验证\n\n- 用采样时间、空间层级或研究中心构建混合分量模型，避免伪重复；\n- 对竞争 DAG 做预先定义的比较，而不是用显著性逐条删边；\n- 对环境变量的测量误差、非线性、交互和共线性做诊断；\n- 若以特定菌或功能作为中介，先解决成分性、零值、多重检验和测量可靠性；\n- 对关键箭头寻找时间滞后、干预或外部数据证据，形成独立于同一横断面协方差的验证。\n\n::: {.callout-caution title=\"常见坑：一张漂亮路径图可能隐藏什么\"}\n- 箭头方向来自作图者，不来自横断面数据；  \n- “路径不显著”不等于该路径不存在，“全局 P > 0.05”也不等于模型正确；  \n- 拟合后按 P 值删边会造成选择偏倚，使最终系数和拟合指标过于乐观；  \n- 把多个菌先按结果筛选，再塞进同一个 SEM，会把特征选择的不确定性完全丢掉；  \n- `Group`、批次和空间位置若同时代表多种差异，调整它们不能恢复一个不存在的随机实验。\n:::\n\n## 出版级美化 {#sec-publication}\n\n路径图应把“科学结构”和“统计结果”分开：节点写变量含义，箭头颜色只区分焦点路径与其余直接路径；完整数值放系数森林图。每个箭头都塞系数、P 值和星号会让读者看不到结构，也容易只注意显著路径。\n\n推荐正文组合为：预设 DAG + 全部标准化系数；补充材料放 directed-separation 表、竞争图比较、残差诊断和 PLS-PM bootstrap。`save_pub()` 输出 PDF/SVG 与 600 ppi PNG/TIFF，所有图内文字为英文。\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> We evaluated a pre-specified causal graph using piecewise structural equation modelling. Measured temperature and precipitation were modelled as upstream climatic predictors; soil pH and log-transformed conductivity represented soil chemistry; Shannon diversity represented the microbial community; and log-transformed total organic carbon was the measured phenotype. Continuous variables were standardised before analysis, and wetland group was included as an adjustment factor in every component model. Global graph compatibility was assessed using tests of directed separation and Fisher's C. Standardised component-model coefficients with 95% confidence intervals were reported. A more restrictive mediation-only graph was evaluated as a falsification model. Partial least-squares path modelling with 2,000 fixed-seed bootstrap resamples was used as an estimator-family sensitivity analysis. Graph compatibility was not interpreted as proof of causality.\n\n请把变量的实测方法、取样时间、预设图依据、变换、层级结构、缺失处理、bootstrap 次数和软件版本替换为真实信息。若 DAG 在看结果后修改，应把修改过程与最终模型标为探索性。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n除三件套外，必须准备一张以 `SampleID` 为行名的实测表：\n\n| 必需信息 | 本例列名 | 你的数据 |\n|---|---|---|\n| 上游环境/暴露 | `Temperature`, `Precipitation` | 饮食、药物、污染物或环境梯度 |\n| 中间环境变量 | `pH`, `Conductivity` | 代谢物、炎症或局部理化指标 |\n| 微生物指标 | 从 `otutab` 算 `Shannon` | 预先定义的多样性、组成轴或功能 |\n| 表型/结局 | `TOC` | 临床或生态结局 |\n| 调整变量 | `Group` | 年龄、中心、空间区组等 |\n\n先在纸上画 DAG，再把每个入箭头集合翻译成一个分量公式。变量缺失、时间顺序不明确或测量并非逐样本对应时，不要靠代码补齐；应重新界定问题或补数据。\n\n## 参考 {#sec-references}\n\n- An J, et al. A large-scale survey of soil bacterial communities across Chinese wetlands. *Geoderma*. 2019;337:841–850. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n- Liu C, et al. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97:fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n- Lefcheck JS. piecewiseSEM: Piecewise structural equation modelling in R for ecology, evolution, and systematics. *Methods in Ecology and Evolution*. 2016;7:573–579. [doi:10.1111/2041-210X.12512](https://doi.org/10.1111/2041-210X.12512)\n- Sanchez G. *PLS Path Modeling with R*. Trowchez Editions; 2013.\n- Shipley B. The AIC model selection method applied to path analytic models compared using a d-separation test. *Ecology*. 2013;94:560–564. [doi:10.1890/12-0976.1](https://doi.org/10.1890/12-0976.1)\n",
    "supporting": [
      "52-structural-equation-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}