{
  "hash": "973526921eb62023c5a72c9593095636",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 06 篇 · 认识你的数据：测序原理 + FASTQ / 文件格式拆解\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**从一组真实的 multiplexed paired-end FASTQ 出发，读懂 read header、碱基序列、Phred 质量、R1/R2/index 的对应关系，并建立从原始 reads 到 `otutab` / `taxonomy` / `metadata` 三件套的文件地图。  \n> **输入文件：**`forward.fastq.gz`、`reverse.fastq.gz`、`barcodes.fastq.gz`、`metadata.tsv`。  \n> **预计资源：**本篇随附 2,000 组真实同步 reads，普通笔记本约 20–40 秒、内存低于 300 MB；官方 1% 完整数据为 135,487 组 reads。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n论文通常不会把 FASTQ 四行结构当作结果图，但一篇可信的 16S 论文至少需要让读者从 Methods 或流程图中回答五个问题：\n\n1. 测的是哪个扩增子区域，使用 single-end 还是 paired-end；\n2. R1、R2 与 index read 如何产生，是否已经 demultiplex；\n3. 原始 reads 的长度、质量编码与文件完整性是否正确；\n4. primer、adapter 和低质量尾端在什么位置处理；\n5. 原始 FASTQ 最终如何变成 feature table、代表序列、taxonomy 和 metadata。\n\n本篇使用 QIIME 2 官方 Atacama soils paired-end 教程数据。原研究沿智利 Atacama Desert 的 Baquedano 与 Yungay 两条 transect 采集土壤，研究干旱增强对微生物群落的影响。官方 1% 数据包含 135,487 个同步的 forward、reverse 与 barcode record；这里从首尾完整覆盖的 1% 文件中等间距、保序抽取 2,000 组，既保留真实 read header 和质量分布，也让文章可以快速重复执行。\n\n::: {layout-ncol=2}\n![扩增子、双端 reads、index 与 overlap 的关系。](../figures/06-read-architecture.png){#fig-read-architecture}\n\n![一个真实 FASTQ record 的四行结构。](../figures/06-fastq-anatomy.png){#fig-fastq-anatomy}\n:::\n\n::: {layout-ncol=2}\n![2,000 组真实 Atacama reads 的逐 cycle Phred 质量。](../figures/06-quality-profile.png){#fig-quality-profile}\n\n![从 multiplexed FASTQ 到标准三件套的文件流。](../figures/06-file-contract.png){#fig-file-contract}\n:::\n\n::: {.callout-important title=\"先确认交付类型，再写导入命令\"}\n`R1/R2` 两个文件不一定代表“两个样本”，也不一定已经按样本拆分。本篇数据采用 EMP multiplexed 格式：所有样本共用一份 `forward.fastq.gz`、一份 `reverse.fastq.gz` 和一份 `barcodes.fastq.gz`，三个文件依靠 **record 顺序**保持对应。若测序公司交付的是每个样本一对 FASTQ，则它们已经 demultiplex，导入方式完全不同。\n:::\n\n### 数据出处与固定校验值\n\n| 文件 | 官方 2024.5 URL | SHA-256 |\n|---|---|---|\n| Forward 1% | `.../atacama-soils/1p/forward.fastq.gz` | `392f178b...88c2702` |\n| Reverse 1% | `.../atacama-soils/1p/reverse.fastq.gz` | `54073703...86cfae` |\n| Barcode 1% | `.../atacama-soils/1p/barcodes.fastq.gz` | `c07f517e...ff3c0f` |\n| Metadata | `.../atacama-soils/sample_metadata.tsv` | `7cff810a...c5b3bd` |\n\n完整 URL、完整校验值、2,000-record 摘录的生成规则和摘录文件校验值均保存在 `data/small/fastq/source_summary.json`。本篇的图是根据真实 reads 重新计算的原创图，不复制论文图版。\n\n## 理论：从荧光信号到四行文本 {#sec-theory}\n\n### 1. paired-end 测序得到的是两个方向的观测\n\nIllumina sequencing by synthesis（边合成边测序）每个 cycle 延伸一个碱基并记录荧光信号。single-end 只从文库分子的一端读取；paired-end 先完成 Read 1，再经过 index read 和模板重建，从另一端得到 Read 2。一个文库分子因此对应：\n\n- 一条 R1；\n- 一条 R2；\n- 一个或两个 index read，取决于建库方案。\n\n“2 × 150 bp”表示每个分子得到 151 bp 左右的两个方向观测，不表示一个样本只有 300 bp 数据，也不表示 R1 与 R2 可以直接首尾拼接。扩增子分析还要先去除 primer，再把 R2 reverse-complement 后寻找足够的 overlap。\n\n设去 primer 与截断后的有效长度为 \\(L_F\\) 和 \\(L_R\\)，扩增子长度为 \\(L_A\\)，理论 overlap 为：\n\n$$\nL_{\\mathrm{overlap}} = L_F + L_R - L_A\n$$\n\n若 overlap 太短、两端在重叠区冲突太多，paired reads 就不能可靠合并。不能只看“尾端质量差不差”，还要同时保住扩增子几何关系。\n\n### 2. FASTQ 的一个 record 固定为四行\n\n```text\n@read_identifier optional_description\nACGT...                         # sequence\n+\n?IIG...                         # ASCII-encoded quality\n```\n\n四行分别是：\n\n1. `@` 开头的 read identifier；\n2. 碱基序列；\n3. `+` 开头的分隔行；\n4. 与序列等长的质量字符串。\n\n最基本的合法性条件是：\n\n$$\nn_{\\mathrm{lines}} \\bmod 4 = 0\n$$\n\n并且每条 read 都满足：\n\n$$\n\\operatorname{length}(\\mathrm{sequence})\n=\n\\operatorname{length}(\\mathrm{quality})\n$$\n\n`.fastq.gz` 只是使用 gzip 压缩的 FASTQ。检查时应流式解压，不能把压缩文件的字节数当作 read 数。\n\n### 3. Phred 质量是错误概率的对数尺度\n\nPhred score \\(Q\\) 与碱基判错概率 \\(P_e\\) 的关系为：\n\n$$\nQ = -10\\log_{10}(P_e), \\qquad\nP_e = 10^{-Q/10}\n$$\n\n| Phred | 估计错误概率 | 直观解释 |\n|---:|---:|---|\n| Q20 | 1% | 约每 100 个 base 错 1 个 |\n| Q30 | 0.1% | 约每 1,000 个 base 错 1 个 |\n| Q40 | 0.01% | 约每 10,000 个 base 错 1 个 |\n\n现代 Illumina FASTQ 通常使用 Phred+33：质量字符的 ASCII 整数减 33 得到 \\(Q\\)。例如 `?` 的 ASCII 值是 63，因此表示 Q30；`I` 的 ASCII 值是 73，因此表示 Q40。质量字符不是“越像乱码越差”，必须先解码。\n\n<details>\n<summary><strong>深入：为什么不能只报告平均 Q30</strong></summary>\n\n平均 Q30 会把 cycle、方向和 read 之间的异质性压成一个数字。扩增子去噪真正需要的是：\n\n- 每个 cycle 的质量分布；\n- forward 与 reverse 分开观察；\n- 碱基 `N` 的位置；\n- read 长度是否一致；\n- 保留足够 overlap 后的可截断区间。\n\n如果 R2 从 cycle 120 后快速下降，整文件平均 Q30 仍可能很好看；但把 `trunc-len-r` 设在 150 可能造成错误率升高或合并失败。质量图用于提出截断候选值，最终参数还要用 DADA2 retention、merged reads 和 non-chimeric reads 验收。\n\n</details>\n\n### 4. multiplexed 与 demultiplexed 是两种文件合同\n\n**Multiplexed EMP paired-end：**\n\n```text\nforward.fastq.gz\nreverse.fastq.gz\nbarcodes.fastq.gz\nsample_metadata.tsv  # sample ID ↔ barcode\n```\n\n三个 FASTQ 的第 \\(i\\) 个 record 必须属于同一文库分子。任何单独排序、过滤或截取都会破坏对应。\n\n**Demultiplexed paired-end：**\n\n```text\nSampleA_R1.fastq.gz\nSampleA_R2.fastq.gz\nSampleB_R1.fastq.gz\nSampleB_R2.fastq.gz\nmanifest.tsv\n```\n\n每个样本各有一对 FASTQ，manifest 明确 `sample-id`、绝对路径和方向。此时通常不再需要 barcode FASTQ，但必须检查 manifest 与文件名、方向、样本数是否一致。\n\n### 5. 常见文件不是彼此替代品\n\n| 文件/对象 | 保存什么 | 是否含质量 | 典型阶段 |\n|---|---|---:|---|\n| FASTQ / FASTQ.GZ | reads + per-base quality | 是 | 原始测序、去噪前 |\n| FASTA | 序列 | 否 | 代表序列、参考序列 |\n| TSV/CSV manifest | sample 与文件路径 | 否 | 导入 demultiplexed FASTQ |\n| QZA | QIIME 2 数据 + provenance | 视类型而定 | QIIME 2 中间/结果对象 |\n| QZV | 可视化结果 + provenance | 不适用 | QIIME 2 报告 |\n| BIOM | feature count table | 否 | ASV/OTU 计数 |\n| `otutab.tsv` | feature × sample 计数 | 否 | R 下游标准输入 |\n| `taxonomy.tsv` | feature × taxonomic ranks | 否 | R 下游标准输入 |\n| `metadata.tsv` | sample × covariates | 否 | 全流程设计信息 |\n\n原始 FASTQ 阶段还没有 `otutab` 和 `taxonomy`。它们必须通过 demultiplex、primer trimming、denoising、chimera removal 与 taxonomic classification 产生；metadata 则应从实验设计开始就存在，并贯穿所有步骤。\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、下载真实数据和定义作图函数</strong></summary>\n\n本篇使用 R 4.4.1、`ggplot2 3.5.2`、`dplyr 1.1.4`、`tidyr 1.3.1`、`jsonlite 1.8.8` 与 `digest 0.6.36`。首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"ggplot2\", \"dplyr\", \"tidyr\", \"scales\",\n  \"jsonlite\", \"digest\", \"knitr\"\n))\n```\n:::\n\n\n仓库已经提供 2,000 组同步的真实摘录。若要改用 QIIME 2 官方 1% 完整文件，可下载到新目录：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nmkdir -p data/atacama-1p\n\ncurl -fL \\\n  -o data/atacama-1p/forward.fastq.gz \\\n  https://data.qiime2.org/2024.5/tutorials/atacama-soils/1p/forward.fastq.gz\n\ncurl -fL \\\n  -o data/atacama-1p/reverse.fastq.gz \\\n  https://data.qiime2.org/2024.5/tutorials/atacama-soils/1p/reverse.fastq.gz\n\ncurl -fL \\\n  -o data/atacama-1p/barcodes.fastq.gz \\\n  https://data.qiime2.org/2024.5/tutorials/atacama-soils/1p/barcodes.fastq.gz\n\ncurl -fL \\\n  -o data/atacama-1p/metadata.tsv \\\n  https://data.qiime2.org/2024.5/tutorials/atacama-soils/sample_metadata.tsv\n```\n:::\n\n\n先检查压缩流和官方校验值：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\ngzip -t data/atacama-1p/forward.fastq.gz\ngzip -t data/atacama-1p/reverse.fastq.gz\ngzip -t data/atacama-1p/barcodes.fastq.gz\n\nsha256sum data/atacama-1p/*\n```\n:::\n\n\n出版级函数直接定义在文章内：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\n\nstopifnot(\n  identical(\n    as.character(utils::packageVersion(\"ggplot2\")),\n    \"3.5.2\"\n  ),\n  identical(\n    as.character(utils::packageVersion(\"dplyr\")),\n    \"1.1.4\"\n  ),\n  identical(\n    as.character(utils::packageVersion(\"tidyr\")),\n    \"1.3.1\"\n  ),\n  identical(\n    as.character(utils::packageVersion(\"jsonlite\")),\n    \"1.8.8\"\n  ),\n  identical(\n    as.character(utils::packageVersion(\"digest\")),\n    \"0.6.36\"\n  )\n)\n\nset.seed(20260719)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(\n        color = \"black\",\n        linewidth = 0.3\n      ),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 120,\n  height = 95,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(\n    dirname(file_base),\n    recursive = TRUE,\n    showWarnings = FALSE\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n}\n```\n:::\n\n\n整仓库运行时可使用内容相同的 `R/theme_pub.R`；独立运行以上代码块即可获得全部函数。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 选择输入并核对 SHA-256\n\n默认读取随文章提供的真实摘录。若改用官方完整 1% 文件，只需把 `fastq_dir` 改为 `data/atacama-1p`。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfastq_dir <- \"data/small/fastq\"\n\nfastq_paths <- c(\n  Forward = file.path(fastq_dir, \"forward.fastq.gz\"),\n  Reverse = file.path(fastq_dir, \"reverse.fastq.gz\"),\n  Barcode = file.path(fastq_dir, \"barcodes.fastq.gz\"),\n  Metadata = file.path(fastq_dir, \"metadata.tsv\")\n)\n\nstopifnot(all(file.exists(fastq_paths)))\n\nknown_sha256 <- data.frame(\n  File = names(fastq_paths),\n  ExcerptSHA256 = c(\n    \"e6fabdbd31db519c719447f1caf2d1cd334c6ab932353e534ea2433ead88d254\",\n    \"d2fa5841d150fead5a73067a267ec531221de11c512a38ec32ada03f1621bf65\",\n    \"9cce1bb9a57975d14b54a5cf07c89b2b7c2095da4a8f0d1bd2720f1349e74057\",\n    \"8d5342f0a80abf4197088bb1ce92f4903c1bd1212f6a9182e0e1c87ebc322bcb\"\n  ),\n  Full1PercentSHA256 = c(\n    \"392f178b5f15967fafb9332c0493a8b6ecbf4a7857538023813a630c488c2702\",\n    \"5407370313a3974e5b70878153841a61df408e49ced133b3ace44b2db286cfae\",\n    \"c07f517e920d9e3924ce1e87102f057232b57041947523b90d560f68a0ff3c0f\",\n    \"7cff810ad86a621ebc78a16b690255d839ea58e2622ad45a11a838d0f8c5b3bd\"\n  ),\n  stringsAsFactors = FALSE\n)\n\nobserved_sha256 <- vapply(\n  fastq_paths,\n  digest::digest,\n  FUN.VALUE = character(1),\n  algo = \"sha256\",\n  serialize = FALSE,\n  file = TRUE\n)\n\nknown_sha256$ObservedSHA256 <- unname(observed_sha256)\nknown_sha256$SourceSet <- ifelse(\n  known_sha256$ObservedSHA256 == known_sha256$ExcerptSHA256,\n  \"Bundled 2,000-record excerpt\",\n  ifelse(\n    known_sha256$ObservedSHA256 ==\n      known_sha256$Full1PercentSHA256,\n    \"Official 1% source\",\n    \"Unknown\"\n  )\n)\n\nstopifnot(!any(known_sha256$SourceSet == \"Unknown\"))\n\nknitr::kable(\n  known_sha256[, c(\"File\", \"SourceSet\", \"ObservedSHA256\")],\n  caption = \"Input identity audit\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Input identity audit\n\n|File     |SourceSet                    |ObservedSHA256                                                   |\n|:--------|:----------------------------|:----------------------------------------------------------------|\n|Forward  |Bundled 2,000-record excerpt |e6fabdbd31db519c719447f1caf2d1cd334c6ab932353e534ea2433ead88d254 |\n|Reverse  |Bundled 2,000-record excerpt |d2fa5841d150fead5a73067a267ec531221de11c512a38ec32ada03f1621bf65 |\n|Barcode  |Bundled 2,000-record excerpt |9cce1bb9a57975d14b54a5cf07c89b2b7c2095da4a8f0d1bd2720f1349e74057 |\n|Metadata |Bundled 2,000-record excerpt |8d5342f0a80abf4197088bb1ce92f4903c1bd1212f6a9182e0e1c87ebc322bcb |\n\n\n:::\n:::\n\n\n这一关拦住的不是“下载失败”而是更危险的静默替换：同名文件被覆盖、下载不完整、上游版本变更或团队成员传错数据，都可能让后续分析在不报错的情况下变成另一批数据。\n\n### 2. 不依赖专用包读取并验证 FASTQ\n\n下面的函数只使用 base R，完整检查四行结构、header、separator 与 sequence/quality 等长条件。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_fastq <- function(path) {\n  connection <- gzfile(path, open = \"rt\")\n  on.exit(close(connection), add = TRUE)\n  lines <- readLines(\n    connection,\n    warn = FALSE,\n    encoding = \"bytes\"\n  )\n\n  if (length(lines) %% 4 != 0) {\n    stop(\n      basename(path),\n      \" does not contain a multiple of four lines\"\n    )\n  }\n\n  records <- matrix(\n    lines,\n    ncol = 4,\n    byrow = TRUE,\n    dimnames = list(\n      NULL,\n      c(\"Header\", \"Sequence\", \"Separator\", \"Quality\")\n    )\n  )\n  records <- as.data.frame(\n    records,\n    stringsAsFactors = FALSE\n  )\n\n  if (!all(startsWith(records$Header, \"@\"))) {\n    stop(basename(path), \" contains an invalid header\")\n  }\n  if (!all(startsWith(records$Separator, \"+\"))) {\n    stop(basename(path), \" contains an invalid separator\")\n  }\n  if (!all(\n    nchar(records$Sequence, type = \"bytes\") ==\n      nchar(records$Quality, type = \"bytes\")\n  )) {\n    stop(\n      basename(path),\n      \" contains unequal sequence and quality lengths\"\n    )\n  }\n\n  records$ReadID <- sub(\n    \"^@([^ ]+).*$\",\n    \"\\\\1\",\n    records$Header\n  )\n  records$Mate <- sub(\n    \"^@[^ ]+ ([12]):.*$\",\n    \"\\\\1\",\n    records$Header\n  )\n  records\n}\n\nforward <- read_fastq(fastq_paths[[\"Forward\"]])\nreverse <- read_fastq(fastq_paths[[\"Reverse\"]])\nbarcodes <- read_fastq(fastq_paths[[\"Barcode\"]])\n\nstopifnot(\n  nrow(forward) == nrow(reverse),\n  nrow(forward) == nrow(barcodes),\n  identical(forward$ReadID, reverse$ReadID),\n  identical(forward$ReadID, barcodes$ReadID),\n  all(forward$Mate == \"1\"),\n  all(reverse$Mate == \"2\")\n)\n```\n:::\n\n\n当前输入包含 2,000 组完全同步的 records。下面不是虚构例子，而是文件中的第一条真实 forward read：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrecord_example <- data.frame(\n  Line = 1:4,\n  Field = c(\n    \"Header\", \"Sequence\",\n    \"Separator\", \"Quality\"\n  ),\n  Value = unname(unlist(\n    forward[1, c(\n      \"Header\", \"Sequence\",\n      \"Separator\", \"Quality\"\n    )]\n  )),\n  stringsAsFactors = FALSE\n)\n\nrecord_example$Length <- nchar(\n  record_example$Value,\n  type = \"bytes\"\n)\n\nknitr::kable(\n  transform(\n    record_example,\n    Value = ifelse(\n      nchar(Value) > 72,\n      paste0(substr(Value, 1, 69), \"...\"),\n      ifelse(\n        startsWith(Value, \"@\"),\n        paste0(\"\\\\\", Value),\n        Value\n      )\n    )\n  ),\n  caption = \"First real FASTQ record\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: First real FASTQ record\n\n| Line|Field     |Value                                                                    | Length|\n|----:|:---------|:------------------------------------------------------------------------|------:|\n|    1|Header    |\\@M00176:65:000000000-A41FR:1:1101:14282:1412 1:N:0:0                    |     52|\n|    2|Sequence  |NACGTAGGGTGCAAGCGTTAATCGGAATTACNGGNNNTAAAGCGTGCNNAGGCNNNNNNNNNNNANNNN... |    151|\n|    3|Separator |+                                                                        |      1|\n|    4|Quality   |#>>>AAF@ACAA4BGCEEECGGHGGEFCFBG#BA###BABAEFGEEE##BBAA###########B####... |    151|\n\n\n:::\n:::\n\n\n### 3. 读 metadata，确认 barcode 与实验设计\n\nQIIME 2 metadata 的第二行是类型声明 `#q2:types`，不是一个样本。读取时保留表头、跳过这一行：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_q2_metadata <- function(path) {\n  lines <- readLines(path, warn = FALSE)\n  stopifnot(\n    length(lines) >= 3,\n    startsWith(lines[2], \"#q2:types\")\n  )\n  connection <- textConnection(\n    c(lines[1], lines[-c(1, 2)])\n  )\n  on.exit(close(connection), add = TRUE)\n  read.delim(\n    connection,\n    check.names = FALSE,\n    stringsAsFactors = FALSE,\n    quote = \"\"\n  )\n}\n\nmetadata <- read_q2_metadata(\n  fastq_paths[[\"Metadata\"]]\n)\n\nmetadata_summary <- metadata |>\n  count(\n    Transect = .data[[\"transect-name\"]],\n    name = \"Samples\"\n  ) |>\n  arrange(Transect)\n\nstopifnot(\n  nrow(metadata) == 75,\n  n_distinct(metadata[[\"sample-id\"]]) == 75,\n  n_distinct(metadata[[\"barcode-sequence\"]]) == 75,\n  all(nchar(metadata[[\"barcode-sequence\"]]) == 12)\n)\n\nknitr::kable(\n  head(metadata, 5),\n  caption = \"First five Atacama metadata rows\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: First five Atacama metadata rows\n\n|sample-id   |barcode-sequence | elevation| extract-concen| amplicon-concentration|extract-group-no |transect-name |site-name | depth|   ph| toc|    ec| average-soil-relative-humidity| relative-humidity-soil-high| relative-humidity-soil-low| percent-relative-humidity-soil-100| average-soil-temperature| temperature-soil-high| temperature-soil-low|vegetation | percentcover|\n|:-----------|:----------------|---------:|--------------:|----------------------:|:----------------|:-------------|:---------|-----:|----:|---:|-----:|------------------------------:|---------------------------:|--------------------------:|----------------------------------:|------------------------:|---------------------:|--------------------:|:----------|------------:|\n|BAQ1370.1.2 |GCCCAAGTTCAC     |      1370|          0.019|                   0.95|B                |Baquedano     |BAQ1370   |     2| 7.98| 525| 6.080|                          16.17|                       23.97|                      11.42|                                  0|                    22.61|                 35.21|                12.46|no         |            0|\n|BAQ1370.3   |GCGCCGAATCTT     |      1370|          0.124|                  17.46|E                |Baquedano     |BAQ1370   |     2|   NA| 771| 6.080|                          16.17|                       23.97|                      11.42|                                  0|                    22.61|                 35.21|                12.46|no         |            0|\n|BAQ1370.1.3 |ATAAAGAGGAGG     |      1370|          1.200|                   0.96|J                |Baquedano     |BAQ1370   |     3| 8.13|  NA|    NA|                          16.17|                       23.97|                      11.42|                                  0|                    22.61|                 35.21|                12.46|no         |            0|\n|BAQ1552.1.1 |ATCCCAGCATGC     |      1552|          0.722|                  18.83|J                |Baquedano     |BAQ1552   |     1| 7.87|  NA|    NA|                          15.75|                       35.36|                      11.10|                                  0|                    22.63|                 30.65|                10.96|no         |            0|\n|BAQ1552.2   |GCTTCCAGACAA     |      1552|          0.017|                   2.00|B                |Baquedano     |BAQ1552   |     2|   NA| 223| 1.839|                          15.75|                       35.36|                      11.10|                                  0|                    22.63|                 30.65|                10.96|no         |            0|\n\n\n:::\n\n```{.r .cell-code}\nknitr::kable(\n  metadata_summary,\n  caption = \"Samples by transect\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Samples by transect\n\n|Transect  | Samples|\n|:---------|-------:|\n|Baquedano |      32|\n|Yungay    |      43|\n\n\n:::\n:::\n\n\nmetadata 共 75 个样本：Baquedano 32 个、Yungay 43 个。barcode 是 12 nt，并且在 metadata 内唯一。注意本数据的 barcode reads 与 metadata 中的 barcode 方向相反，因此 QIIME 2 demultiplex 时需要 `--p-rev-comp-mapping-barcodes`；这个选项来自实际建库方向，不能对所有项目机械照抄。\n\n### 4. 解码 Phred，按 cycle 审计 R1 与 R2\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecode_phred33 <- function(quality_string) {\n  utf8ToInt(quality_string) - 33L\n}\n\nquality_matrix <- function(records) {\n  lengths <- nchar(\n    records$Quality,\n    type = \"bytes\"\n  )\n  if (length(unique(lengths)) != 1) {\n    stop(\"variable read lengths require padding before matrix conversion\")\n  }\n  do.call(\n    rbind,\n    lapply(records$Quality, decode_phred33)\n  )\n}\n\nsummarize_cycles <- function(records, read_name) {\n  quality <- quality_matrix(records)\n  tibble(\n    Read = read_name,\n    Cycle = seq_len(ncol(quality)),\n    Q10 = apply(\n      quality,\n      2,\n      stats::quantile,\n      probs = 0.10,\n      names = FALSE,\n      type = 8\n    ),\n    MedianQ = apply(\n      quality,\n      2,\n      stats::median\n    ),\n    Q90 = apply(\n      quality,\n      2,\n      stats::quantile,\n      probs = 0.90,\n      names = FALSE,\n      type = 8\n    ),\n    Q30Fraction = colMeans(quality >= 30)\n  )\n}\n\nsummarize_file <- function(records, read_name) {\n  quality <- quality_matrix(records)\n  sequence_length <- nchar(\n    records$Sequence,\n    type = \"bytes\"\n  )\n  tibble(\n    Read = read_name,\n    Records = nrow(records),\n    MinLength = min(sequence_length),\n    MedianLength = stats::median(sequence_length),\n    MaxLength = max(sequence_length),\n    MedianReadMeanPhred = stats::median(\n      rowMeans(quality)\n    ),\n    Q30BaseFraction = mean(quality >= 30),\n    NBaseFraction = NA_real_\n  )\n}\n\ncycle_summary <- bind_rows(\n  summarize_cycles(forward, \"Forward\"),\n  summarize_cycles(reverse, \"Reverse\")\n)\n\nfile_summary <- bind_rows(\n  summarize_file(forward, \"Forward\"),\n  summarize_file(reverse, \"Reverse\"),\n  summarize_file(barcodes, \"Barcode\")\n)\n\n# NBaseFraction 用明确的逐字符计数重算，避免零匹配的特殊值。\ncount_n <- function(records) {\n  n_bases <- sum(\n    vapply(\n      strsplit(records$Sequence, \"\", fixed = TRUE),\n      function(x) sum(x == \"N\"),\n      integer(1)\n    )\n  )\n  n_bases / sum(\n    nchar(records$Sequence, type = \"bytes\")\n  )\n}\n\nfile_summary$NBaseFraction <- c(\n  count_n(forward),\n  count_n(reverse),\n  count_n(barcodes)\n)\n\nknitr::kable(\n  transform(\n    file_summary,\n    MedianReadMeanPhred = round(\n      MedianReadMeanPhred,\n      2\n    ),\n    Q30BaseFraction = scales::percent(\n      Q30BaseFraction,\n      accuracy = 0.1\n    ),\n    NBaseFraction = scales::percent(\n      NBaseFraction,\n      accuracy = 0.01\n    )\n  ),\n  caption = \"Read-level FASTQ audit\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Read-level FASTQ audit\n\n|Read    | Records| MinLength| MedianLength| MaxLength| MedianReadMeanPhred|Q30BaseFraction |NBaseFraction |\n|:-------|-------:|---------:|------------:|---------:|-------------------:|:---------------|:-------------|\n|Forward |    2000|       151|          151|       151|               36.09|89.3%           |0.19%         |\n|Reverse |    2000|       151|          151|       151|               32.34|73.9%           |0.24%         |\n|Barcode |    2000|        12|           12|        12|               33.83|73.2%           |0.31%         |\n\n\n:::\n:::\n\n\n在 2,000-record 摘录中，forward 与 reverse 都是 151 nt。forward 的 median read-mean Phred 为 36.09，Q30 base 占 89.3%；reverse 分别为 32.34 和 73.9%。因此 R2 的整体质量低于 R1，但截断位置仍应根据逐 cycle 分布和后续 merge retention 联合决定。\n\n### 5. 导出可审计结果表\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\n  \"results/06-fastq\",\n  recursive = TRUE,\n  showWarnings = FALSE\n)\n\nfile_audit <- file_summary |>\n  left_join(\n    known_sha256[, c(\n      \"File\", \"ObservedSHA256\",\n      \"SourceSet\"\n    )],\n    by = c(\"Read\" = \"File\")\n  )\n\nutils::write.table(\n  file_audit,\n  \"results/06-fastq/fastq-file-audit.tsv\",\n  sep = \"\\t\",\n  quote = FALSE,\n  row.names = FALSE\n)\nutils::write.table(\n  cycle_summary,\n  \"results/06-fastq/quality-by-cycle.tsv\",\n  sep = \"\\t\",\n  quote = FALSE,\n  row.names = FALSE\n)\nutils::write.table(\n  record_example,\n  \"results/06-fastq/fastq-record-example.tsv\",\n  sep = \"\\t\",\n  quote = FALSE,\n  row.names = FALSE\n)\nutils::write.table(\n  metadata_summary,\n  \"results/06-fastq/metadata-summary.tsv\",\n  sep = \"\\t\",\n  quote = FALSE,\n  row.names = FALSE\n)\n```\n:::\n\n\n`fastq-file-audit.tsv` 保存文件级 read 数、长度、Phred、Q30、N 比例与 SHA-256；`quality-by-cycle.tsv` 是截断参数决策的机器可读证据；另外两张表分别保留真实四行 record 和 metadata 分组规模。\n\n## 出版级美化 {#sec-polish}\n\n### 图 1：read architecture 只画能由实验流程支持的关系\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_architecture <- ggplot() +\n  annotate(\n    \"rect\",\n    xmin = 0, xmax = 12,\n    ymin = 0.92, ymax = 1.18,\n    fill = pal_pub[5]\n  ) +\n  annotate(\n    \"rect\",\n    xmin = 12, xmax = 88,\n    ymin = 0.92, ymax = 1.18,\n    fill = \"#E6E6E6\"\n  ) +\n  annotate(\n    \"rect\",\n    xmin = 88, xmax = 100,\n    ymin = 0.92, ymax = 1.18,\n    fill = pal_pub[4]\n  ) +\n  annotate(\n    \"segment\",\n    x = 2, xend = 63,\n    y = 0.68, yend = 0.68,\n    linewidth = 1.2,\n    color = pal_pub[1],\n    arrow = grid::arrow(\n      length = grid::unit(2.5, \"mm\"),\n      type = \"closed\"\n    )\n  ) +\n  annotate(\n    \"segment\",\n    x = 98, xend = 37,\n    y = 0.40, yend = 0.40,\n    linewidth = 1.2,\n    color = pal_pub[2],\n    arrow = grid::arrow(\n      length = grid::unit(2.5, \"mm\"),\n      type = \"closed\"\n    )\n  ) +\n  annotate(\n    \"rect\",\n    xmin = 37, xmax = 63,\n    ymin = 0.28, ymax = 0.80,\n    fill = scales::alpha(pal_pub[3], 0.16),\n    color = pal_pub[3],\n    linewidth = 0.5\n  ) +\n  annotate(\n    \"text\",\n    x = 6, y = 1.30,\n    label = \"515F primer\",\n    size = 3.2\n  ) +\n  annotate(\n    \"text\",\n    x = 50, y = 1.30,\n    label = \"16S V4 insert\",\n    size = 3.2\n  ) +\n  annotate(\n    \"text\",\n    x = 94, y = 1.30,\n    label = \"806R primer\",\n    size = 3.2\n  ) +\n  annotate(\n    \"text\",\n    x = 18, y = 0.76,\n    label = \"Read 1\",\n    color = pal_pub[1],\n    fontface = \"bold\",\n    size = 3.2\n  ) +\n  annotate(\n    \"text\",\n    x = 82, y = 0.48,\n    label = \"Read 2\",\n    color = pal_pub[2],\n    fontface = \"bold\",\n    size = 3.2\n  ) +\n  annotate(\n    \"text\",\n    x = 50, y = 0.18,\n    label = \"Required overlap\",\n    color = pal_pub[3],\n    size = 3\n  ) +\n  annotate(\n    \"rect\",\n    xmin = 31, xmax = 69,\n    ymin = -0.12, ymax = 0.03,\n    fill = \"#F7F7F7\",\n    color = \"#666666\",\n    linewidth = 0.4\n  ) +\n  annotate(\n    \"text\",\n    x = 50, y = -0.045,\n    label = \"Index read assigns the molecule to a sample\",\n    size = 2.8\n  ) +\n  coord_cartesian(\n    xlim = c(-2, 102),\n    ylim = c(-0.18, 1.45),\n    clip = \"off\"\n  ) +\n  labs(\n    title = \"Paired-end amplicon architecture\",\n    subtitle = \"Primer removal and overlap are linked decisions\"\n  ) +\n  theme_void(base_size = 11, base_family = \"sans\") +\n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      hjust = 0\n    ),\n    plot.subtitle = element_text(\n      color = \"#4D4D4D\",\n      margin = margin(b = 7)\n    ),\n    plot.margin = margin(8, 10, 6, 10)\n  )\n\nsave_pub(\n  p_architecture,\n  \"figures/06-read-architecture\",\n  width = 155,\n  height = 88\n)\n\np_architecture\n```\n\n::: {.cell-output-display}\n![](06-data-and-fastq_files/figure-html/unnamed-chunk-11-1.png)\n:::\n:::\n\n\n这张图不声称所有项目都使用 515F/806R，也不把示意长度伪装成测量值。换引物区域时需要重画 primer、insert 和 overlap 的关系，并把实际 primer sequence 写进 Methods。\n\n### 图 2：FASTQ anatomy 使用真实 record，但避免长字符串挤压\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanatomy <- record_example |>\n  mutate(\n    Display = case_when(\n      Field == \"Header\" ~ substr(Value, 1, 53),\n      Field == \"Sequence\" ~ paste0(\n        substr(Value, 1, 48),\n        \"…  [151 nt]\"\n      ),\n      Field == \"Quality\" ~ paste0(\n        substr(Value, 1, 48),\n        \"…  [151 chars]\"\n      ),\n      TRUE ~ Value\n    ),\n    Meaning = c(\n      \"Read identifier\",\n      \"Nucleotide sequence\",\n      \"Record separator\",\n      \"Phred+33 quality\"\n    ),\n    PlotRow = rev(Line)\n  )\n\np_anatomy <- ggplot(anatomy) +\n  geom_tile(\n    aes(\n      x = 0,\n      y = PlotRow,\n      fill = Field\n    ),\n    width = 0.48,\n    height = 0.76,\n    color = \"white\",\n    linewidth = 0.5\n  ) +\n  geom_text(\n    aes(\n      x = 0,\n      y = PlotRow,\n      label = paste0(\"Line \", Line)\n    ),\n    color = \"white\",\n    fontface = \"bold\",\n    size = 3.1\n  ) +\n  geom_text(\n    aes(\n      x = 0.38,\n      y = PlotRow,\n      label = Display\n    ),\n    family = \"mono\",\n    hjust = 0,\n    size = 2.75,\n    color = \"#222222\"\n  ) +\n  geom_text(\n    aes(\n      x = 4.20,\n      y = PlotRow,\n      label = Meaning\n    ),\n    hjust = 0,\n    size = 2.9,\n    color = \"#4D4D4D\"\n  ) +\n  scale_fill_manual(\n    values = setNames(\n      pal_pub[c(1, 3, 8, 2)],\n      c(\n        \"Header\", \"Sequence\",\n        \"Separator\", \"Quality\"\n      )\n    ),\n    guide = \"none\"\n  ) +\n  coord_cartesian(\n    xlim = c(-0.28, 5.55),\n    ylim = c(0.45, 4.55),\n    clip = \"off\"\n  ) +\n  labs(\n    title = \"One FASTQ record has exactly four lines\",\n    subtitle = \"Real Atacama forward read; long sequence and quality strings are abbreviated\"\n  ) +\n  theme_void(base_size = 11, base_family = \"sans\") +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(\n      color = \"#4D4D4D\",\n      margin = margin(b = 8)\n    ),\n    plot.margin = margin(7, 8, 7, 8)\n  )\n\nsave_pub(\n  p_anatomy,\n  \"figures/06-fastq-anatomy\",\n  width = 180,\n  height = 90\n)\n\np_anatomy\n```\n\n::: {.cell-output-display}\n![](06-data-and-fastq_files/figure-html/unnamed-chunk-12-1.png)\n:::\n:::\n\n\n### 图 3：逐 cycle 质量图显示分布，不只画均值\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_quality <- ggplot(\n  cycle_summary,\n  aes(\n    x = Cycle,\n    y = MedianQ,\n    color = Read,\n    fill = Read\n  )\n) +\n  geom_ribbon(\n    aes(\n      ymin = Q10,\n      ymax = Q90\n    ),\n    alpha = 0.16,\n    color = NA\n  ) +\n  geom_line(linewidth = 0.8) +\n  geom_hline(\n    yintercept = 30,\n    linetype = 2,\n    linewidth = 0.45,\n    color = \"#444444\"\n  ) +\n  annotate(\n    \"text\",\n    x = 149,\n    y = 30.8,\n    label = \"Q30\",\n    hjust = 1,\n    vjust = 0,\n    size = 3,\n    color = \"#444444\"\n  ) +\n  scale_color_manual(\n    values = c(\n      Forward = pal_pub[1],\n      Reverse = pal_pub[2]\n    )\n  ) +\n  scale_fill_manual(\n    values = c(\n      Forward = pal_pub[1],\n      Reverse = pal_pub[2]\n    )\n  ) +\n  scale_x_continuous(\n    breaks = c(1, 25, 50, 75, 100, 125, 151),\n    expand = expansion(mult = c(0.01, 0.02))\n  ) +\n  scale_y_continuous(\n    limits = c(0, 42),\n    breaks = seq(0, 40, 10),\n    expand = expansion(mult = c(0, 0.02))\n  ) +\n  labs(\n    x = \"Sequencing cycle\",\n    y = \"Phred quality\",\n    color = NULL,\n    fill = NULL,\n    title = \"Read 2 quality declines near the tail\",\n    subtitle = \"Median and 10th–90th percentiles; n = 2,000 real read pairs\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    legend.position = \"bottom\",\n    legend.direction = \"horizontal\",\n    plot.title = element_text(face = \"bold\")\n  )\n\nsave_pub(\n  p_quality,\n  \"figures/06-quality-profile\",\n  width = 135,\n  height = 95\n)\n\np_quality\n```\n\n::: {.cell-output-display}\n![](06-data-and-fastq_files/figure-html/unnamed-chunk-13-1.png)\n:::\n:::\n\n\n### 图 4：把 FASTQ 与三件套放在同一条 provenance 链上\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflow <- tibble(\n  Step = 1:4,\n  Stage = factor(\n    c(\n      \"Raw\", \"Demultiplexed\",\n      \"Denoised\", \"Analysis-ready\"\n    ),\n    levels = c(\n      \"Raw\", \"Demultiplexed\",\n      \"Denoised\", \"Analysis-ready\"\n    )\n  ),\n  Label = c(\n    \"Multiplexed\\nFASTQ triplet\",\n    \"Per-sample\\nR1 + R2\",\n    \"ASV table +\\nsequences\",\n    \"otutab +\\ntaxonomy +\\nmetadata\"\n  ),\n  Detail = c(\n    \"Forward, reverse, barcode\\nshare record order\",\n    \"Manifest maps files\\nto sample IDs\",\n    \"Trim, denoise, merge,\\nremove chimeras\",\n    \"Stable input contract\\nfor R analysis\"\n  )\n)\n\np_contract <- ggplot(flow) +\n  geom_segment(\n    data = tibble(\n      x = 1:3 + 0.42,\n      xend = 2:4 - 0.42,\n      y = 1,\n      yend = 1\n    ),\n    aes(\n      x = x,\n      xend = xend,\n      y = y,\n      yend = yend\n    ),\n    linewidth = 0.7,\n    color = \"#666666\",\n    arrow = grid::arrow(\n      type = \"closed\",\n      length = grid::unit(2.2, \"mm\")\n    )\n  ) +\n  geom_rect(\n    aes(\n      xmin = Step - 0.40,\n      xmax = Step + 0.40,\n      ymin = 0.82,\n      ymax = 1.18,\n      fill = Stage\n    ),\n    color = \"white\",\n    linewidth = 0.7\n  ) +\n  geom_text(\n    aes(\n      x = Step,\n      y = 1,\n      label = Label\n    ),\n    color = \"white\",\n    fontface = \"bold\",\n    lineheight = 0.95,\n    size = 2.8\n  ) +\n  geom_text(\n    aes(\n      x = Step,\n      y = 0.58,\n      label = Detail\n    ),\n    size = 2.6,\n    color = \"#4D4D4D\",\n    lineheight = 0.95\n  ) +\n  scale_fill_manual(\n    values = setNames(\n      pal_pub[c(2, 5, 3, 1)],\n      levels(flow$Stage)\n    ),\n    guide = \"none\"\n  ) +\n  coord_cartesian(\n    xlim = c(0.48, 4.52),\n    ylim = c(0.34, 1.30),\n    clip = \"off\"\n  ) +\n  labs(\n    title = \"From raw reads to the standard triad\",\n    subtitle = \"Metadata anchors sample identity across every transition\"\n  ) +\n  theme_void(base_size = 11, base_family = \"sans\") +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(\n      color = \"#4D4D4D\",\n      margin = margin(b = 9)\n    ),\n    plot.margin = margin(8, 10, 5, 10)\n  )\n\nsave_pub(\n  p_contract,\n  \"figures/06-file-contract\",\n  width = 180,\n  height = 92\n)\n\np_contract\n```\n\n::: {.cell-output-display}\n![](06-data-and-fastq_files/figure-html/unnamed-chunk-14-1.png)\n:::\n:::\n\n\n::: {.callout-note title=\"这四张图各自回答什么\"}\n- `read architecture` 回答 primer、R1/R2 与 overlap 的几何关系；\n- `FASTQ anatomy` 回答文件内部每一行是什么；\n- `quality profile` 回答两个方向哪些 cycle 可能限制截断；\n- `file contract` 回答 FASTQ、QIIME 2 artifact 与 R 三件套如何衔接。\n:::\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿与复现中最常见的 FASTQ 问题\"}\n1. **把 read 与 read pair 混为一谈。**100 万 pairs 是 200 万 reads，但仍只代表 100 万个文库分子。\n2. **把 R1/R2 当成两个样本。**它们是同一批分子的两个方向，样本身份由 demultiplex 或 manifest 决定。\n3. **对 EMP 三个文件分别排序或过滤。**record 顺序一旦错位，barcode 会分配给错误分子。\n4. **只用 `文件行数 ÷ 4`。**这只能给 record 数，不能证明 header、separator、等长和 R1/R2 ID 都正确。\n5. **直接对 `.gz` 用普通 `wc -l`。**应先 `gzip -t`，再用 `zcat file.fastq.gz | wc -l` 或流式解析器。\n6. **默认所有质量编码都是 Phred+33。**现代 Illumina 通常如此，但历史 Solexa/Illumina 文件可能不同；公共旧数据应查 archive metadata。\n7. **只报平均 Q30。**去噪参数依赖 per-cycle、per-direction 质量和 overlap，不能被一个全局均值替代。\n8. **把 adapter 与 locus-specific primer 混为一谈。**adapter contamination 和 PCR primer 都可能要去除，但序列、位置和工具参数不同。\n9. **根据文件名猜方向。**`_1/_2`、`R1/R2` 是常见命名，不是可靠 provenance；应核对 sample sheet、header、manifest 和交付说明。\n10. **认为文件能解压就完整。**gzip CRC 通过后仍需 SHA-256 或 archive checksum，以确认拿到的是预期版本。\n11. **忽略 metadata 类型行。**QIIME 2 的 `#q2:types` 不是样本；把它读成样本会造成样本数和 barcode 审计错误。\n12. **先截短再问能否合并。**truncation 同时改变错误率和 overlap；必须用 merged/non-chimeric retention 反向验收。\n:::\n\n::: {.callout-warning title=\"FASTQ 质量好不等于生物学设计好\"}\n高 Q30、无损 gzip、完全配对只能证明测序文件在技术上可读，不能补救病例/对照混杂、样本量不足、阴性对照缺失或 metadata 错误。文件 QC 与研究设计 QC 是两条都必须通过的证据链。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n以下模板把可替换字段保留在方括号中：\n\n> Amplicons targeting the [16S region] were sequenced on an Illumina [instrument] using a [2 × N]-bp paired-end configuration with [single/dual] indexing. Raw FASTQ files were verified by gzip integrity testing and SHA-256 checksums. FASTQ records were audited for four-line structure, equal sequence and quality-string lengths, synchronized forward/reverse read identifiers, and Phred+33 encoding. Per-cycle quality distributions were inspected separately for forward and reverse reads. Primer trimming and truncation parameters were selected jointly to remove primer sequences and low-quality tails while retaining at least [N] nt of expected overlap. Demultiplexing was performed using [barcode/manifest method], and sample identifiers were matched against the prespecified metadata table before denoising.\n\n本篇真实数据的文件审计可写为：\n\n> The QIIME 2 Atacama soils 1% paired-end data set comprised 135,487 synchronized forward, reverse, and 12-nt barcode records. File identities were fixed by SHA-256 checksums. A deterministic, order-preserving excerpt of 2,000 evenly spaced record triplets was used to render the tutorial diagnostics. Both sequence reads were 151 nt; per-cycle Phred distributions and the proportion of bases at Q30 or higher were evaluated separately by read direction. The excerpt was used only for file-format demonstration, whereas denoising parameters should be validated on the complete study data.\n\nMethods 中不要只写“quality control was performed”。至少给出 read 类型、长度、质量编码、primer、截断/去引物规则、最低 overlap、demultiplex 方式和完整数据上的 retention。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. 先判定是哪种交付\n\n| 你收到的文件 | 交付类型 | 下一步 |\n|---|---|---|\n| 全项目只有 forward/reverse/barcodes 三个 FASTQ | EMP multiplexed | 用 barcode metadata demultiplex |\n| 每样本一对 R1/R2 FASTQ | Demultiplexed paired-end | 建 manifest 后导入 |\n| 每样本一个 FASTQ | Demultiplexed single-end | 建 single-end manifest |\n| BCL + sample sheet | 未完成 base calling/demultiplex | 先运行厂商转换流程或要求测序方交付 FASTQ |\n\n### 2. 只改路径即可复用本篇审计\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfastq_dir <- \"your_project/data/raw\"\nfastq_paths <- c(\n  Forward = file.path(fastq_dir, \"your_R1.fastq.gz\"),\n  Reverse = file.path(fastq_dir, \"your_R2.fastq.gz\"),\n  Barcode = file.path(fastq_dir, \"your_index.fastq.gz\"),\n  Metadata = \"your_project/data/metadata.tsv\"\n)\n\nforward <- read_fastq(fastq_paths[[\"Forward\"]])\nreverse <- read_fastq(fastq_paths[[\"Reverse\"]])\n\nstopifnot(\n  nrow(forward) == nrow(reverse),\n  identical(forward$ReadID, reverse$ReadID)\n)\n\ncycle_summary <- bind_rows(\n  summarize_cycles(forward, \"Forward\"),\n  summarize_cycles(reverse, \"Reverse\")\n)\n```\n:::\n\n\n若已 demultiplex，没有独立 barcode FASTQ，则删除 barcode 相关代码，改为检查：\n\n- manifest 中每个 sample 是否恰好有一个 forward 和一个 reverse；\n- 文件路径是否存在且为绝对路径；\n- metadata sample ID 是否与 manifest 一致；\n- 每个样本内部 R1/R2 record 数和 read ID 是否一一对应。\n\n### 3. 原始 reads 之后仍要回到标准三件套\n\n完成 demultiplex、primer trimming、DADA2/其他 ASV inference 与 taxonomy classification 后，导出：\n\n```text\notutab.tsv      # rows = ASVs, columns = samples\ntaxonomy.tsv    # rows = the same ASVs, columns = taxonomic ranks\nmetadata.tsv    # rows = the same samples, columns = study variables\n```\n\n在进入 R 下游前做最后一次 ID 合同检查：\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  setequal(colnames(otutab), rownames(metadata))\n)\nmetadata <- metadata[colnames(otutab), , drop = FALSE]\n```\n:::\n\n\nFASTQ 是测序证据的起点，三件套是统计分析的入口；二者之间必须由可追踪的参数、日志和 artifact provenance 连接起来。\n\n## 参考 {#sec-references}\n\n1. Neilson JW, Califf K, Cardona C, et al. Significant impacts of increasing aridity on the arid soil microbiome. *mSystems*. 2017;2(3):e00195-16. [doi:10.1128/mSystems.00195-16](https://doi.org/10.1128/mSystems.00195-16)\n2. QIIME 2. “Atacama soil microbiome” tutorial, archived 2024.10 documentation. [docs.qiime2.org/2024.10/tutorials/atacama-soils/](https://docs.qiime2.org/2024.10/tutorials/atacama-soils/)\n3. Cock PJA, Fields CJ, Goto N, Heuer ML, Rice PM. The Sanger FASTQ file format for sequences with quality scores, and the Solexa/Illumina FASTQ variants. *Nucleic Acids Research*. 2010;38(6):1767–1771. [doi:10.1093/nar/gkp1137](https://doi.org/10.1093/nar/gkp1137)\n4. Ewing B, Green P. Base-calling of automated sequencer traces using phred. II. Error probabilities. *Genome Research*. 1998;8(3):186–194. [doi:10.1101/gr.8.3.186](https://doi.org/10.1101/gr.8.3.186)\n5. Bolyen E, Rideout JR, Dillon MR, et al. Reproducible, interactive, scalable and extensible microbiome data science using QIIME 2. *Nature Biotechnology*. 2019;37:852–857. [doi:10.1038/s41587-019-0209-9](https://doi.org/10.1038/s41587-019-0209-9)\n6. Callahan BJ, McMurdie PJ, Rosen MJ, Han AW, Johnson AJA, Holmes SP. DADA2: high-resolution sample inference from Illumina amplicon data. *Nature Methods*. 2016;13:581–583. [doi:10.1038/nmeth.3869](https://doi.org/10.1038/nmeth.3869)\n7. Illumina. What is a Single Read, Paired End reads, and read requirements for sequencing? Illumina Knowledge Article 9547.\n",
    "supporting": [
      "06-data-and-fastq_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}