{
  "hash": "09123a54c7b317b18f457532f4ed0b81",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"开篇：这套教程你将复现哪些顶刊图（图集预览 + 学习地图）\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **学习目标：**从一张“证据地图”理解 16S 研究从实验设计到因果判断的完整路径，并用真实湿地数据复现两类常见论文主图。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`；环境约束分析额外使用 `environment.tsv`。  \n> **预计资源：**90 个样本、13,628 个 OTU；普通笔记本约 2–5 分钟，内存低于 1 GB。\n\n## 先看终点：一篇完整的 16S 研究需要哪些证据？ {#sec-target}\n\n一项完整的 16S 研究通常不是“做一张菌群柱状图”，而是一条逐层收紧的证据链：\n\n1. 先证明样本、对照和批次设计能够支持目标比较；\n2. 再从原始 reads 得到可追溯的 ASV/OTU 表、分类表和系统发育树；\n3. 描述群落多样性与组成；\n4. 检验分组、环境或临床变量与群落的关联；\n5. 在独立数据中验证预测能力；\n6. 最后区分相关、时间顺序、机制和干预证据。\n\n下面两张图来自同一套公开中国湿地 16S 数据，展示两种核心读图方式。\n\n::: {layout-ncol=2}\n![非约束排序：Bray–Curtis PCoA 展示样本整体群落结构，并同时报告 PERMANOVA 与组内离散度检验。](figures/01-preview-pcoa.png){#fig-gallery-pcoa}\n\n![约束排序：CAP 展示预先指定环境变量所解释的群落变异，并报告调整后解释率、置换检验和变量方向。](figures/01-preview-cap.png){#fig-gallery-cap}\n:::\n\n图 @fig-gallery-pcoa 回答“样本间整体组成是否不同”；图 @fig-gallery-cap 回答“预先指定的环境梯度与群落差异关联到什么程度”。二者都不能单独证明环境因子造成了群落变化。\n\n本例数据来自中国内陆、沿海和青藏高原湿地调查，`microeco` 将标准化后的 OTU、taxonomy、样本信息和环境变量作为真实示例数据分发。[原始研究](https://doi.org/10.1016/j.geoderma.2018.09.035)与[`microeco` 软件论文](https://doi.org/10.1093/femsec/fiaa255)提供数据和软件出处。\n\n::: {.callout-important title=\"一张漂亮图对应一个明确问题\"}\n组成图描述“有什么”，多样性图概括“群落有多复杂或彼此多不同”，差异分析定位“哪些类群与条件相关”，预测模型回答“能否在新样本上预测”，因果结论则需要时间顺序、干预或机制证据。图形越复杂，不代表证据等级越高。\n:::\n\n## 理论：从测序表到生物学证据 {#sec-theory}\n\n### 1. 16S 测到的是标记基因，不是完整功能\n\n16S rRNA 扩增子测序对特定可变区进行 PCR 扩增。它适合比较细菌和古菌群落组成，但通常不能稳定解析菌株、毒力基因、耐药基因或真实代谢活性。功能预测只能描述基于参考基因组的推断，不能替代宏基因组、转录组、代谢组或培养实验。\n\n### 2. 测序深度不是微生物绝对数量\n\n每个样本的 reads 总数由取样、DNA 提取、PCR、建库和测序共同决定。常规 16S 表更接近“组成比例”，某一类群相对丰度升高，可能来自它本身增加，也可能来自其他类群减少。[Gloor 等](https://doi.org/10.3389/fmicb.2017.02224)系统说明了微生物组数据的成分性；涉及绝对负荷时，需要 spike-in、流式细胞计数、总菌 qPCR/ddPCR 或其他外部定量参照。\n\n### 3. 同一问题需要相互补充的分析\n\n| 科学问题 | 主要结果 | 必须同时检查 |\n|---|---|---|\n| 单个样本内部有多丰富？ | Observed features、Shannon、Faith's PD | 测序深度、稀释覆盖、树质量 |\n| 不同样本整体是否不同？ | Bray–Curtis/Jaccard/UniFrac、PCoA/NMDS | PERMANOVA、dispersion、置换设计 |\n| 哪些类群发生变化？ | ANCOM-BC、ALDEx2、MaAsLin2、DESeq2 等 | 成分性、协变量、FDR、方法敏感性 |\n| 环境变量解释多少差异？ | CAP/db-RDA、variation partitioning | 调整后 \\(R^2\\)、VIF、边际检验 |\n| 能否预测疾病或表型？ | ROC/AUC、校准、特征重要性 | 嵌套交叉验证、外部验证、数据泄漏 |\n| 能否说“微生物导致结局”？ | 纵向、中介、MR、干预、机制实验 | 时间顺序、混杂、多效性、可重复性 |\n\n[Nearing 等](https://doi.org/10.1038/s41467-022-28034-z)在 38 个数据集上比较差异丰度方法，显示不同方法可能返回显著不同的结果集。因此，方法选择必须由数据结构和估计目标决定，而不是由“哪种方法显著菌更多”决定。\n\n<details>\n<summary><strong>深入：八个阶段分别交付什么</strong></summary>\n\n1. **Study design（03–06）：**明确实验单位、主要终点、混杂因素、阴性/阳性对照、批次和采样时点。\n2. **Computing setup（07–09）：**固定 QIIME 2、R、数据库和包版本，留下可重跑环境。\n3. **ASV generation（10–16）：**从 FASTQ 经导入、去引物、DADA2、taxonomy 和建树，得到带 provenance 的特征表。\n4. **Diversity and ordination（17–25）：**从标准三件套构建分析对象，报告 α/β 多样性、排序和环境约束。\n5. **Taxa and covariates（26–34）：**描述组成、核心菌群和差异类群，并处理成分性、协变量与绝对定量边界。\n6. **Networks and ecology（35–40）：**评估关联网络稳健性、群落构建过程、中性模型和距离衰减。\n7. **Prediction and integration（41–50）：**功能预测、随机森林、跨队列验证、多组学、多界和来源追踪。\n8. **Causal evidence（51–55）：**纵向、SEM、中介、MR 与证据阶梯；明确哪些结论仍只是关联。\n\n</details>\n\n::: {.callout-note title=\"推荐的最短可信主线\"}\n如果目标是完成一篇规范的基础 16S 论文，最低限度应覆盖实验设计与对照、可追溯上游、数据质控、α/β 多样性、组成、至少一种适合数据结构的差异分析、协变量处理、效应量与不确定性。网络、机器学习和因果分析只有在科学问题与样本量真正支持时才加入。\n:::\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、下载真实数据和定义作图函数</strong></summary>\n\n首次运行安装以下 R 包：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"vegan\", \"ggplot2\", \"ggrepel\", \"scales\", \"digest\"\n))\n```\n:::\n\n\n示例固定使用 `microeco 2.0.0` 源码包中的真实数据。以下代码下载归档、校验 SHA-256，并导出标准三件套和环境变量表。\n\n\n::: {.cell}\n\n```{.r .cell-code}\narchive <- \"data/raw/microeco_2.0.0.tar.gz\"\nsource_url <- paste0(\n  \"https://cran.r-project.org/src/contrib/Archive/\",\n  \"microeco/microeco_2.0.0.tar.gz\"\n)\nexpected_sha256 <- paste0(\n  \"454a3b71ceeea86bdd54f475a12b5bac\",\n  \"9c3b124f663b8dc6e560827fca89ebfd\"\n)\n\ndir.create(\"data/raw\", recursive = TRUE, showWarnings = FALSE)\ndir.create(\"data/small\", recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(archive)) {\n  download.file(source_url, archive, mode = \"wb\")\n}\nobserved_sha256 <- digest::digest(\n  file = archive,\n  algo = \"sha256\",\n  serialize = FALSE\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\nrequired <- c(\n  \"microeco/data/otu_table_16S.RData\",\n  \"microeco/data/taxonomy_table_16S.RData\",\n  \"microeco/data/sample_info_16S.RData\",\n  \"microeco/data/env_data_16S.RData\"\n)\nextract_dir <- tempfile(\"microeco-data-\")\ndir.create(extract_dir)\nutils::untar(archive, files = required, exdir = extract_dir)\n\ndata_env <- new.env(parent = emptyenv())\nfor (relative_path in required) {\n  load(file.path(extract_dir, relative_path), envir = data_env)\n}\n\nwrite_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name),\n    x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out,\n    path,\n    sep = \"\\t\",\n    quote = FALSE,\n    row.names = FALSE,\n    na = \"\"\n  )\n}\n\nwrite_tsv(data_env$otu_table_16S, \"FeatureID\", \"data/small/otutab.tsv\")\nwrite_tsv(\n  data_env$taxonomy_table_16S,\n  \"FeatureID\",\n  \"data/small/taxonomy.tsv\"\n)\nwrite_tsv(\n  data_env$sample_info_16S,\n  \"SampleID\",\n  \"data/small/metadata.tsv\"\n)\nwrite_tsv(\n  data_env$env_data_16S,\n  \"SampleID\",\n  \"data/small/environment.tsv\"\n)\nunlink(extract_dir, recursive = TRUE)\n```\n:::\n\n\n每篇需要的出版级函数在文章内直接定义：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vegan)\nlibrary(ggplot2)\nlibrary(ggrepel)\n\nset.seed(20260718)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(color = \"black\", linewidth = 0.3),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 120,\n  height = 95,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n整仓库运行时可使用内容相同的 `R/theme_pub.R`；独立阅读时运行以上代码即可获得全部函数。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取并核对四张表\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"data/small/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"data/small/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nenvironment <- read.delim(\n  \"data/small/environment.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(colnames(otutab) %in% rownames(environment)),\n  all(otutab >= 0),\n  all(colSums(otutab) > 0)\n)\n\nenvironment <- environment[colnames(otutab), , drop = FALSE]\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n```\n\n\n:::\n\n```{.r .cell-code}\notutab[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxonomy[1:5, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\n                         Class               Order               Family Genus\nOTU_4272            c__Bacilli       o__Bacillales                  f__   g__\nOTU_236                    c__                 o__                  f__   g__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae   g__\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__   g__\nOTU_32                     c__                 o__                  f__   g__\n         Species\nOTU_4272     s__\nOTU_236      s__\nOTU_399      s__\nOTU_1556     s__\nOTU_32       s__\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(environment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Latitude Longitude Altitude Temperature Precipitation   TOC      NH4  NO3\nS1 52.96482  122.5635      432        -4.2           445 10.02 18.95966 1.93\nS2 52.94877  122.6109      445        -4.3           449  6.94 21.05730 1.46\nS3 52.94932  122.6099      430        -4.3           449  8.38 14.31937 2.38\nS4 52.94900  122.6104      430        -4.3           449  8.17 20.89645 1.38\nS5 52.95292  122.6057      429        -4.3           449  8.41  9.65465 0.77\nS6 52.95300  122.6123      429        -4.3           449  8.13 15.94577 1.31\n     pH Conductivity   TN\nS1 5.10        108.7 0.28\nS2 6.53         31.2 0.22\nS3 5.13         68.2 0.26\nS4 5.81         64.4 0.25\nS5 5.50         33.5 0.24\nS6 5.37         33.3 0.26\n```\n\n\n:::\n:::\n\n\n三张核心表的方向必须是：\n\n- `otutab`：特征 × 样本；\n- `taxonomy`：特征 × 分类层级，行名与 `otutab` 一致；\n- `metadata`：样本 × 变量，行名与 `otutab` 列名一致。\n\n### 2. 构建共同的群落矩阵\n\n保留至少在 5% 样本中检出的特征，然后按样本转换为相对丰度。这个转换用于本篇的 Bray–Curtis 展示，不应机械套用到所有分析；例如 DESeq2 和 ANCOM-BC 需要各自规定的输入。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin_prevalence <- 0.05\nmin_samples <- ceiling(min_prevalence * ncol(otutab))\nkeep_feature <- rowSums(otutab > 0) >= min_samples\n\ncomm <- t(otutab[keep_feature, , drop = FALSE])\ncomm_rel <- sweep(comm, 1, rowSums(comm), \"/\")\nmetadata <- metadata[rownames(comm_rel), , drop = FALSE]\nenvironment <- environment[rownames(comm_rel), , drop = FALSE]\n\nstopifnot(\n  all(abs(rowSums(comm_rel) - 1) < 1e-10),\n  identical(rownames(comm_rel), rownames(metadata)),\n  identical(rownames(comm_rel), rownames(environment))\n)\n\nc(\n  samples = nrow(comm_rel),\n  retained_features = ncol(comm_rel),\n  original_features = nrow(otutab)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          samples retained_features original_features \n               90             11113             13628 \n```\n\n\n:::\n:::\n\n\n### 3. 非约束排序：PCoA + PERMANOVA + dispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_bray <- vegan::vegdist(comm_rel, method = \"bray\")\n\npcoa_fit <- stats::cmdscale(\n  dist_bray,\n  k = 2,\n  eig = TRUE,\n  add = TRUE\n)\npositive_eigenvalues <- pcoa_fit$eig[pcoa_fit$eig > 0]\npcoa_variance <- 100 * pcoa_fit$eig[1:2] /\n  sum(positive_eigenvalues)\n\npcoa_df <- as.data.frame(pcoa_fit$points)\ncolnames(pcoa_df) <- c(\"PCoA1\", \"PCoA2\")\npcoa_df$SampleID <- rownames(pcoa_df)\npcoa_df$Salinity <- factor(\n  metadata[pcoa_df$SampleID, \"Saline\"],\n  levels = c(\"Non-saline soil\", \"Saline soil\")\n)\n\nset.seed(20260718)\npermanova <- vegan::adonis2(\n  dist_bray ~ Salinity,\n  data = pcoa_df,\n  permutations = 999\n)\n\ndispersion_model <- vegan::betadisper(\n  dist_bray,\n  group = pcoa_df$Salinity,\n  type = \"median\",\n  bias.adjust = TRUE\n)\nset.seed(20260718)\ndispersion_test <- vegan::permutest(\n  dispersion_model,\n  permutations = 999\n)\n\npermanova_r2 <- unname(permanova$R2[1])\npermanova_p <- unname(permanova$`Pr(>F)`[1])\ndispersion_p <- unname(dispersion_test$tab$`Pr(>F)`[1])\n\npermanova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nvegan::adonis2(formula = dist_bray ~ Salinity, data = pcoa_df, permutations = 999)\n         Df SumOfSqs      R2      F Pr(>F)    \nSalinity  1   3.2599 0.11106 10.994  0.001 ***\nResidual 88  26.0925 0.88894                  \nTotal    89  29.3524 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ndispersion_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n          Df  Sum Sq   Mean Sq      F N.Perm Pr(>F)\nGroups     1 0.00468 0.0046803 1.5095    999  0.216\nResiduals 88 0.27284 0.0031005                     \n```\n\n\n:::\n:::\n\n\n本例的 PERMANOVA 检验组间群落位置差异，`betadisper` 则检查显著结果是否可能由某组更分散造成。二者必须按研究设计使用相同且合理的置换限制。\n\n### 4. 约束排序：环境 CAP\n\n预先选择 pH、总有机碳、铵态氮、硝态氮和电导率，并做 Z-score 标准化。地理组只用于给点着色，不进入当前环境模型。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_labels <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan Plateau\"\n)\nmetadata$Group <- factor(\n  unname(group_labels[metadata$Group]),\n  levels = unname(group_labels)\n)\n\npredictors <- c(\n  \"pH\", \"TOC\", \"NH4\", \"NO3\", \"Conductivity\"\n)\nstopifnot(all(predictors %in% colnames(environment)))\n\ncomplete_samples <- complete.cases(\n  environment[, predictors, drop = FALSE]\n)\ncomm_env <- comm_rel[complete_samples, , drop = FALSE]\nmetadata_env <- metadata[complete_samples, , drop = FALSE]\nenvironment_env <- environment[\n  complete_samples,\n  predictors,\n  drop = FALSE\n]\nmodel_data <- as.data.frame(scale(environment_env))\n\ncap_env <- vegan::capscale(\n  comm_env ~ pH + TOC + NH4 + NO3 + Conductivity,\n  data = model_data,\n  distance = \"bray\",\n  add = \"lingoes\"\n)\n\ncap_env_r2 <- vegan::RsquareAdj(cap_env)\ncap_env_vif <- vegan::vif.cca(cap_env)\n\nset.seed(20260718)\ncap_env_overall <- anova(\n  cap_env,\n  permutations = 999\n)\nset.seed(20260718)\ncap_env_margin <- anova(\n  cap_env,\n  by = \"margin\",\n  permutations = 999\n)\n\ncap_env_p <- unname(cap_env_overall$`Pr(>F)`[1])\ncap_env_r2_raw <- unname(cap_env_r2$r.squared)\ncap_env_r2_adjusted <- unname(cap_env_r2$adj.r.squared)\n\ncap_env_r2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$r.squared\n[1] 0.2286814\n\n$adj.r.squared\n[1] 0.1827695\n```\n\n\n:::\n\n```{.r .cell-code}\ncap_env_vif\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          pH          TOC          NH4          NO3 Conductivity \n    1.456621     1.626594     1.053479     1.246362     1.043803 \n```\n\n\n:::\n\n```{.r .cell-code}\ncap_env_overall\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: vegan::capscale(formula = comm_env ~ pH + TOC + NH4 + NO3 + Conductivity, data = model_data, distance = \"bray\", add = \"lingoes\")\n         Df SumOfSqs      F Pr(>F)    \nModel     5   6.7123 4.9809  0.001 ***\nResidual 84  22.6401                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncap_env_margin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nMarginal effects of terms\nPermutation: free\nNumber of permutations: 999\n\nModel: vegan::capscale(formula = comm_env ~ pH + TOC + NH4 + NO3 + Conductivity, data = model_data, distance = \"bray\", add = \"lingoes\")\n             Df SumOfSqs      F Pr(>F)    \npH            1   1.8475 6.8547  0.001 ***\nTOC           1   0.7888 2.9267  0.001 ***\nNH4           1   0.6795 2.5210  0.002 ** \nNO3           1   0.3684 1.3667  0.093 .  \nConductivity  1   2.3043 8.5495  0.001 ***\nResidual     84  22.6401                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n提取当前模型的样本坐标、变量箭头和轴解释比例：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_eigenvalues <- cap_env$CCA$eig\ncap_axis_percent <- 100 * cap_eigenvalues[1:2] /\n  sum(cap_eigenvalues)\n\ncap_sites <- as.data.frame(\n  vegan::scores(\n    cap_env,\n    display = \"sites\",\n    choices = 1:2,\n    scaling = 2\n  )\n)\ncap_sites$SampleID <- rownames(cap_sites)\ncap_sites$Group <- metadata_env[\n  cap_sites$SampleID,\n  \"Group\"\n]\n\ncap_arrows <- as.data.frame(\n  vegan::scores(\n    cap_env,\n    display = \"bp\",\n    choices = 1:2,\n    scaling = 2\n  )\n)\ncap_arrows$Variable <- rownames(cap_arrows)\n\narrow_multiplier <- min(\n  diff(range(cap_sites$CAP1)) * 0.35 /\n    max(abs(cap_arrows$CAP1)),\n  diff(range(cap_sites$CAP2)) * 0.35 /\n    max(abs(cap_arrows$CAP2))\n)\ncap_arrows$CAP1 <- cap_arrows$CAP1 * arrow_multiplier\ncap_arrows$CAP2 <- cap_arrows$CAP2 * arrow_multiplier\n\nhead(cap_sites)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        CAP1       CAP2 SampleID          Group\nS1 -1.306507 -0.4718530       S1 Inland wetland\nS2 -1.413450 -0.7413386       S2 Inland wetland\nS3 -1.455895 -0.8905344       S3 Inland wetland\nS4 -1.567960 -1.0303186       S4 Inland wetland\nS5 -1.523055 -0.9751641       S5 Inland wetland\nS6 -1.662818 -1.0937208       S6 Inland wetland\n```\n\n\n:::\n\n```{.r .cell-code}\ncap_arrows\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    CAP1        CAP2     Variable\npH            0.62908411  0.91049570           pH\nTOC          -0.65228224 -0.36588590          TOC\nNH4          -0.03593229  0.11372774          NH4\nNO3          -0.38804971 -0.08116419          NO3\nConductivity  0.88250723 -0.59897850 Conductivity\n```\n\n\n:::\n:::\n\n\n## 出版级美化 {#sec-polish}\n\n### 1. 非约束排序预览图\n\n所有统计数字从当前运行对象自动生成，避免图注与代码版本脱节。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_p <- function(p) {\n  if (is.na(p)) {\n    return(\"= NA\")\n  }\n  if (p < 0.001) {\n    return(\"< 0.001\")\n  }\n  sprintf(\"= %.3f\", p)\n}\n\np_preview_pcoa <- ggplot(\n  pcoa_df,\n  aes(PCoA1, PCoA2, color = Salinity)\n) +\n  stat_ellipse(\n    type = \"t\",\n    level = 0.95,\n    linewidth = 0.75,\n    show.legend = FALSE\n  ) +\n  geom_point(size = 2.7, alpha = 0.88) +\n  scale_color_pub(name = \"Soil salinity\") +\n  labs(\n    title = \"Community-level separation\",\n    subtitle = paste0(\n      \"PERMANOVA R² = \", sprintf(\"%.3f\", permanova_r2),\n      \", P \", format_p(permanova_p),\n      \"\\nDispersion P \", format_p(dispersion_p)\n    ),\n    x = sprintf(\"PCoA 1 (%.1f%%)\", pcoa_variance[1]),\n    y = sprintf(\"PCoA 2 (%.1f%%)\", pcoa_variance[2])\n  ) +\n  coord_equal() +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 11),\n    plot.subtitle = element_text(size = 8.8, lineheight = 1.05),\n    legend.position = \"bottom\"\n  ) +\n  guides(color = guide_legend(nrow = 1, byrow = TRUE))\n\np_preview_pcoa\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_preview_pcoa,\n  \"figures/01-preview-pcoa\",\n  width = 125,\n  height = 100\n)\n```\n:::\n\n\n### 2. 环境约束排序预览图\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_preview_cap <- ggplot(\n  cap_sites,\n  aes(CAP1, CAP2, color = Group)\n) +\n  stat_ellipse(\n    type = \"t\",\n    level = 0.95,\n    linewidth = 0.7,\n    show.legend = FALSE\n  ) +\n  geom_point(size = 2.5, alpha = 0.86) +\n  geom_segment(\n    data = cap_arrows,\n    aes(x = 0, y = 0, xend = CAP1, yend = CAP2),\n    inherit.aes = FALSE,\n    color = \"grey20\",\n    linewidth = 0.55,\n    arrow = grid::arrow(\n      length = grid::unit(2.2, \"mm\"),\n      type = \"closed\"\n    )\n  ) +\n  ggrepel::geom_text_repel(\n    data = cap_arrows,\n    aes(x = CAP1, y = CAP2, label = Variable),\n    inherit.aes = FALSE,\n    color = \"grey10\",\n    size = 3.0,\n    fontface = \"bold\",\n    seed = 20260718,\n    box.padding = 0.35,\n    point.padding = 0.2,\n    min.segment.length = 0,\n    segment.color = \"grey60\"\n  ) +\n  scale_color_pub(name = \"Wetland group\") +\n  labs(\n    title = \"Environmental constraints\",\n    subtitle = paste0(\n      \"R² = \", sprintf(\"%.3f\", cap_env_r2_raw),\n      \" · adjusted R² = \",\n      sprintf(\"%.3f\", cap_env_r2_adjusted),\n      \" · permutation P \", format_p(cap_env_p)\n    ),\n    x = sprintf(\n      \"CAP1 (%.1f%% constrained)\",\n      cap_axis_percent[1]\n    ),\n    y = sprintf(\n      \"CAP2 (%.1f%% constrained)\",\n      cap_axis_percent[2]\n    )\n  ) +\n  coord_equal(clip = \"off\") +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 9),\n    legend.position = \"bottom\"\n  ) +\n  guides(color = guide_legend(nrow = 1, byrow = TRUE))\n\np_preview_cap\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_preview_cap,\n  \"figures/01-preview-cap\",\n  width = 150,\n  height = 110\n)\n```\n:::\n\n\n### 3. 55 篇学习路线图\n\n路线图只表达分析顺序和证据层级，不暗示所有研究都必须使用全部方法。图内文字使用英文，便于直接用于英文汇报。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_nodes <- data.frame(\n  id = 1:8,\n  x = c(1, 3, 5, 7, 7, 5, 3, 1),\n  y = c(2.4, 2.4, 2.4, 2.4, 0, 0, 0, 0),\n  chapters = c(\n    \"Ch. 03–06\", \"Ch. 07–09\", \"Ch. 10–16\", \"Ch. 17–25\",\n    \"Ch. 26–34\", \"Ch. 35–40\", \"Ch. 41–50\", \"Ch. 51–55\"\n  ),\n  stage = c(\n    \"Study\\ndesign\",\n    \"Computing\\nsetup\",\n    \"ASV\\ngeneration\",\n    \"Diversity &\\nordination\",\n    \"Taxa &\\ncovariates\",\n    \"Networks &\\necology\",\n    \"Prediction &\\nintegration\",\n    \"Causal\\nevidence\"\n  ),\n  output = c(\n    \"estimand +\\ncontrols\",\n    \"reproducible\\nruntime\",\n    \"counts + taxonomy\\n+ tree\",\n    \"alpha / beta\\nPCoA / CAP\",\n    \"composition +\\nDA models\",\n    \"associations +\\nassembly\",\n    \"validated models\\n+ multi-omics\",\n    \"time → intervention\\n→ mechanism\"\n  ),\n  fill = c(\n    \"#1B4965\", \"#245F73\", \"#2C7DA0\", \"#3A8D9F\",\n    \"#2A9D8F\", \"#6A4C93\", \"#B64A28\", \"#7A1F3D\"\n  )\n)\n\nmap_edges <- data.frame(\n  x = c(1.85, 3.85, 5.85, 7, 6.15, 4.15, 2.15),\n  y = c(2.4, 2.4, 2.4, 1.72, 0, 0, 0),\n  xend = c(2.15, 4.15, 6.15, 7, 5.85, 3.85, 1.85),\n  yend = c(2.4, 2.4, 2.4, 0.68, 0, 0, 0)\n)\n\np_learning_map <- ggplot() +\n  geom_segment(\n    data = map_edges,\n    aes(x, y, xend = xend, yend = yend),\n    linewidth = 0.8,\n    color = \"grey55\",\n    arrow = grid::arrow(\n      length = grid::unit(2.4, \"mm\"),\n      type = \"closed\"\n    )\n  ) +\n  geom_tile(\n    data = map_nodes,\n    aes(x, y, fill = fill),\n    width = 1.78,\n    height = 1.35,\n    color = \"white\",\n    linewidth = 0.9\n  ) +\n  geom_text(\n    data = map_nodes,\n    aes(x, y = y + 0.48, label = chapters),\n    color = \"white\",\n    size = 2.7,\n    fontface = \"bold\"\n  ) +\n  geom_text(\n    data = map_nodes,\n    aes(x, y = y + 0.08, label = stage),\n    color = \"white\",\n    size = 2.85,\n    fontface = \"bold\",\n    lineheight = 0.88\n  ) +\n  geom_text(\n    data = map_nodes,\n    aes(x, y = y - 0.43, label = output),\n    color = \"white\",\n    size = 2.05,\n    lineheight = 0.9\n  ) +\n  annotate(\n    \"text\",\n    x = 4,\n    y = -1.02,\n    label = \"Association ≠ prediction ≠ causation\",\n    color = \"#7A1F3D\",\n    fontface = \"bold\",\n    size = 3.8\n  ) +\n  scale_fill_identity() +\n  coord_cartesian(\n    xlim = c(0, 8),\n    ylim = c(-1.25, 3.25),\n    clip = \"off\"\n  ) +\n  labs(\n    title = \"A reproducible 16S evidence workflow\",\n    subtitle = \"Each transition adds assumptions, validation requirements and limits\"\n  ) +\n  theme_void(base_family = \"sans\") +\n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 14,\n      hjust = 0.5\n    ),\n    plot.subtitle = element_text(\n      size = 10,\n      color = \"grey35\",\n      hjust = 0.5,\n      margin = margin(b = 10)\n    ),\n    plot.margin = margin(8, 8, 8, 8)\n  )\n\np_learning_map\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_learning_map,\n  \"figures/01-learning-map\",\n  width = 180,\n  height = 110\n)\n```\n:::\n\n\n三个图均导出为 PDF、PNG 和 300 dpi LZW-TIFF。PDF 用于论文排版，PNG 用于网页和公众号，TIFF 用于要求位图投稿的期刊。\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"从开题到投稿最容易埋下的八个问题\"}\n1. **先看数据再定义主要假设。** 在大量分组、距离和方法中挑显著结果，会放大研究者自由度；主要终点和协变量应尽量预先确定。\n2. **把 reads 当绝对菌量。** 相对丰度变化不能直接说明某个菌真实增殖或减少。\n3. **只按表格位置合并。** OTU、taxonomy、metadata 和树必须按 ID 显式核对；顺序碰巧一致不是证据。\n4. **把技术重复当独立样本。** 实验单位决定有效样本量；同一个体、笼位、地块或采样点内的重复需要配对、区组或混合模型。\n5. **按显著菌数量选择方法。** 差异方法的输入、零值、离散度和成分性假设不同，应报告选择依据并做敏感性分析。\n6. **把分类准确率当可转化价值。** 没有嵌套交叉验证、独立队列、校准与决策价值评估，高 AUC 可能只是数据泄漏或批次识别。\n7. **跨研究直接合并不同扩增区。** 引物区、提取方法、平台、数据库和生物信息流程会产生结构性批次差异。\n8. **从相关图跳到因果语言。** 共现边、CAP 箭头、中介路径和 MR 结果都有各自假设，不能替代培养、干预、无菌动物或分子机制证据。\n:::\n\n::: {.callout-warning title=\"“顶刊图”不是越复杂越好\"}\n审稿人首先检查实验单位、对照、批次、协变量、效应量、验证队列和结论边界。一个设计正确、统计完整的 PCoA 往往比堆叠十种未经验证的高级方法更有说服力。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n下面是一段覆盖基础 16S 统计主线的英文模板。正式使用时必须替换扩增区、平台、数据库版本、过滤阈值、协变量和置换结构。\n\n> Amplicon count, taxonomic annotation and sample-metadata tables were matched by feature and sample identifiers before analysis. The dataset contained 13,628 features across 90 samples. Features detected in at least 5% of samples were retained, yielding 11,113 features. Bray–Curtis dissimilarities were calculated from sample-wise relative-abundance profiles and visualized by principal coordinates analysis with a Lingoes correction. Group differences were evaluated by PERMANOVA with 999 permutations (\\(R^2\\) = 0.111, P = 0.001), and homogeneity of multivariate dispersion was assessed separately (P = 0.216). Associations with five prespecified, standardized environmental variables were evaluated by distance-based redundancy analysis; model fit was summarized by raw and adjusted \\(R^2\\) (0.229 and 0.183, respectively) and tested using 999 permutations (P = 0.001). All random procedures used a fixed seed, and all reported values were generated directly from the executed analysis objects.\n\n如果存在重复测量、配对、笼位、地块或中心效应，必须补充真实的受限置换或混合模型结构；不能保留模板中的自由置换表述。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n先准备三个必需文件：\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"your_project/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"your_project/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"your_project/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\ngroup_col <- \"Treatment\"\nmetadata$AnalysisGroup <- factor(metadata[[group_col]])\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata))\n)\n```\n:::\n\n\n然后按科学问题补充相应数据：\n\n| 目标分析 | 三件套之外还需要 |\n|---|---|\n| UniFrac、Faith's PD、βNTI | tip ID 与特征 ID 一致的系统发育树 |\n| CAP、variation partitioning、SEM | 实测环境因子、宿主表型或临床变量 |\n| 绝对定量 | spike-in、流式计数、总菌 qPCR/ddPCR 或其他外部负荷 |\n| 纵向分析 | 个体 ID、准确时间、干预/暴露与重复测量信息 |\n| 生存分析 | 随访时间、事件状态、删失和临床协变量 |\n| 多组学 | 同一样本或可明确配对的代谢组、转录组等矩阵 |\n| 孟德尔随机化 | 暴露与结局 GWAS 汇总统计、等位基因和 LD 信息 |\n\n开始计算前，用一句话写清楚：\n\n> 在什么总体中，以什么为实验单位，比较什么暴露或处理，对什么结局估计哪一种效应？\n\n如果这句话写不清，优先修正研究问题和设计，而不是继续增加分析方法。\n\n## 参考 {#sec-references}\n\n- Knight R, Vrbanac A, Taylor BC, et al. Best practices for analysing microbiomes. *Nature Reviews Microbiology*. 2018;16:410–422. [doi:10.1038/s41579-018-0029-9](https://doi.org/10.1038/s41579-018-0029-9)\n- Bolyen E, Rideout JR, Dillon MR, et al. Reproducible, interactive, scalable and extensible microbiome data science using QIIME 2. *Nature Biotechnology*. 2019;37:852–857. [doi:10.1038/s41587-019-0209-9](https://doi.org/10.1038/s41587-019-0209-9)\n- Callahan BJ, McMurdie PJ, Rosen MJ, et al. DADA2: High-resolution sample inference from Illumina amplicon data. *Nature Methods*. 2016;13:581–583. [doi:10.1038/nmeth.3869](https://doi.org/10.1038/nmeth.3869)\n- Gloor GB, Macklaim JM, Pawlowsky-Glahn V, Egozcue JJ. Microbiome datasets are compositional: and this is not optional. *Frontiers in Microbiology*. 2017;8:2224. [doi:10.3389/fmicb.2017.02224](https://doi.org/10.3389/fmicb.2017.02224)\n- Nearing JT, Douglas GM, Hayes MG, et al. Microbiome differential abundance methods produce different results across 38 datasets. *Nature Communications*. 2022;13:342. [doi:10.1038/s41467-022-28034-z](https://doi.org/10.1038/s41467-022-28034-z)\n- Anderson MJ. A new method for non-parametric multivariate analysis of variance. *Austral Ecology*. 2001;26:32–46. [doi:10.1111/j.1442-9993.2001.01070.pp.x](https://doi.org/10.1111/j.1442-9993.2001.01070.pp.x)\n- Anderson MJ, Willis TJ. Canonical analysis of principal coordinates: a useful method of constrained ordination for ecology. *Ecology*. 2003;84:511–525. [doi:10.1890/0012-9658(2003)084%5B0511:CAOPCA%5D2.0.CO;2](https://doi.org/10.1890/0012-9658%282003%29084%5B0511%3ACAOPCA%5D2.0.CO%3B2)\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}