{
  "hash": "790c3891a2d5668ae954b6f0d9206b79",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"WGCNA 用于微生物组：模块、性状关联与候选 hub\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**把真实 16S 属级 counts 转成 CLR abundance profile，完成 soft-threshold、signed WGCNA、dynamic tree cut、module eigengene–trait correlation、BH 校正、hub candidate 与 pseudocount sensitivity。  \n> **输入文件：**`data/small/otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`；额外读取同源 `environment.tsv` 作为 module–trait 分析。  \n> **预计资源：**90 个样本、422 个预先过滤的命名属；WGCNA 1.74、4 线程通常 1–3 分钟、峰值内存约 2 GB；四张图导出为 PDF/SVG/600 ppi PNG/LZW-TIFF。\n\n## WGCNA 模块是共变模式，不是生态功能单元 {#sec-target}\n\n[Langfelder & Horvath (2008)](https://doi.org/10.1186/1471-2105-9-559)系统化了 weighted correlation network analysis：用 soft threshold 把 correlation 转为 adjacency，经 topological overlap 聚类得到模块，再以 module eigengene 关联外部性状。以下结果依次检查 soft threshold、module dendrogram、module–trait association 和候选 hub 的稳定性。\n\n::: {.callout-important title=\"先给结论\"}\nWGCNA 可以把共同变化的 taxa 压缩成模块，但微生物 abundance 是组成数据，模块也容易重现分组、地理与批次结构。本页先做 prevalence/abundance filter，再用 CLR 与 signed bicor；module–trait p-value 在统一检验族内 BH 校正。Hub 只表示“在当前模块里与 eigengene 高度一致且连接较强”，不能直接写成功能核心菌或 keystone。\n:::\n\n本页仍使用 CW、IW、TW 各 30 个真实样本。已知 genus reads 只占全部 reads 的一部分，因此 WGCNA 的 estimand 明确限定为“可命名且通过过滤的属级子群”，不会把模块结果外推到整张 ASV 表。\n\n## WGCNA 是软阈值模块模型，不是另一种差异分析 {#sec-theory}\n\n### 1. 从 correlation 到 signed adjacency\n\n对 taxon $i,j$ 的 robust correlation $r_{ij}$，signed network 使用\n\n$$\na_{ij}=\\left(\\frac{1+r_{ij}}{2}\\right)^\\beta,\n$$\n\n其中 $\\beta$ 是 soft-threshold power。负相关被压向 0，强正相关保留较大权重；与 hard threshold 相比，不必把 `r=0.59` 与 `r=0.60` 切成无边/有边。\n\n### 2. Soft-threshold 不是追逐最高 $R^2$\n\n`pickSoftThreshold()` 给 scale-free topology fit 与 mean connectivity。只追求高 $R^2$ 会选择过大的 power，把网络压得几乎没有连接。本页预先规定：选择第一个 `signed R² >= 0.80` 且 `mean connectivity >= 5` 的 power；若没有同时满足者，才在 connectivity 合格的候选中选择最高 $R^2$，并显式报告失败。\n\n### 3. TOM 与 dynamic tree cut 找共同变化模块\n\nTopological overlap matrix（TOM）不仅看两个 taxa 是否直接相关，还看它们是否共享邻居。`blockwiseModules()` 在 `1-TOM` 层次树上 dynamic cut，并合并 eigengene correlation 高的模块。灰色（grey）节点表示没有进入任何稳定模块，不应硬塞进最近模块。\n\n### 4. Module eigengene 把数百个 taxa 压成一个轴\n\nModule eigengene 是模块 abundance profile 的第一主成分。它与 CW/IW/TW one-vs-rest 指示变量及预设环境因子做 correlation；所有 module × trait tests 组成一个 BH family。强 correlation 仍可能来自 group–environment 共线性，不能解释为该环境变量驱动模块。\n\n### 5. Hub 至少要同时满足 membership 与 connectivity\n\n本页候选 hub 需同时满足：模块 membership `|kME| >= 0.80`，且 within-module connectivity 位于本模块前 10%。这比只按 degree 排名更清楚，但仍是数据驱动候选。功能验证、跨队列 preservation 和去除候选 taxon 后的模块稳定性才是升级证据。\n\n<details>\n<summary><strong>深入：为什么 RNA-seq 的 WGCNA 代码不能原样搬到 16S 百分比</strong></summary>\n\n百分比总和固定会制造负依赖，零值又使 log transform 不可直接计算。本页用固定 0.5 replacement 做 CLR，并用 1.0 replacement 重跑全部模块作为 sensitivity。CLR correlation 仍依赖 zero replacement、filter 和 reference frame，因此 module assignment sensitivity 必须进入结果，而不是只在 Methods 里写一句“数据已标准化”。\n\n</details>\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装锁定依赖并定义出版级作图函数</strong></summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"ggdendro\", \"ggplot2\", \"ggrepel\", \"patchwork\", \"ragg\", \"readr\",\n  \"scales\", \"svglite\", \"systemfonts\", \"WGCNA\"\n))\n```\n:::\n\n\n本页实跑 `WGCNA` 1.74。旧版 1.72-5 与当前 `xfun` 可出现 namespace 冲突，因此应使用本页锁定的依赖版本，不要混用系统旧包。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(WGCNA)\n\nset.seed(20260737)\nfont_pub <- \"DejaVu Sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(colour = \"#1A1A1A\", linewidth = 0.3),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(), legend.position = \"top\"\n    )\n}\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot, width = width, height = height,\n    units = units, device = grDevices::cairo_pdf,\n    family = base_family, bg = \"white\"\n  )\n  if (write_svg) ggplot2::ggsave(\n    paste0(file_base, \".svg\"), plot, width = width, height = height,\n    units = units, device = svglite::svglite, bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_png, bg = \"white\"\n  )\n  if (write_tiff) ggplot2::ggsave(\n    paste0(file_base, \".tiff\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_tiff,\n    compression = \"lzw\", bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 从三件套生成 90 × 422 的命名属 CLR 矩阵\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path, show_col_types = FALSE, progress = FALSE,\n    name_repair = \"minimal\", na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\notutab_raw <- read_keyed_tsv(\"data/small/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"data/small/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"data/small/metadata.tsv\")\nenvironment <- read_keyed_tsv(\"data/small/environment.tsv\")\notutab <- as.matrix(data.frame(\n  lapply(otutab_raw, as.integer), check.names = FALSE\n))\nrownames(otutab) <- rownames(otutab_raw)\nmetadata$Group <- factor(metadata$Group, levels = c(\"CW\", \"IW\", \"TW\"))\nenvironment <- environment[rownames(metadata), , drop = FALSE]\n\nrank_names <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"\n)\nclean_taxon <- function(x) {\n  x <- sub(\"^[A-Za-z]__\", \"\", trimws(as.character(x)))\n  x[\n    is.na(x) | x == \"\" |\n      grepl(\n        \"unclassified|unknown|unassigned|uncultured|metagenome\",\n        x, ignore.case = TRUE\n      )\n  ] <- NA_character_\n  x\n}\ntaxonomy_clean <- as.data.frame(\n  lapply(taxonomy[rownames(otutab), rank_names], clean_taxon),\n  check.names = FALSE\n)\nknown_genus <- !is.na(taxonomy_clean$Genus)\nlineage_key <- apply(\n  taxonomy_clean[known_genus, rank_names[1:6], drop = FALSE], 1L,\n  function(x) paste(ifelse(is.na(x), \"?\", x), collapse = \";\")\n)\ngenus_counts <- rowsum(\n  otutab[known_genus, , drop = FALSE], lineage_key, reorder = FALSE\n)\nlineage_matrix <- do.call(\n  rbind, strsplit(rownames(genus_counts), \";\", fixed = TRUE)\n)\ncolnames(lineage_matrix) <- rank_names[1:6]\nfeature_ids <- make.unique(paste0(\"Genus:\", lineage_matrix[, \"Genus\"]))\nrownames(genus_counts) <- feature_ids\n\neligible <- rowMeans(genus_counts > 0) >= 0.20 & rowSums(genus_counts) >= 100\ncounts <- genus_counts[eligible, rownames(metadata), drop = FALSE]\nmake_clr <- function(pseudocount) {\n  log_values <- log2(t(counts) + pseudocount)\n  log_values - rowMeans(log_values)\n}\ndat_expr <- make_clr(0.5)\nquality <- WGCNA::goodSamplesGenes(dat_expr, verbose = 0)\n\nstopifnot(\n  nrow(otutab) == 13628L,\n  ncol(otutab) == 90L,\n  sum(otutab) == 1619670L,\n  nrow(dat_expr) == 90L,\n  ncol(dat_expr) == 422L,\n  quality$allOK,\n  identical(rownames(dat_expr), rownames(metadata)),\n  all(is.finite(dat_expr))\n)\n\ndata.frame(\n  Samples = nrow(dat_expr),\n  NamedGenera = ncol(dat_expr),\n  RetainedAllReadFraction = sum(counts) / sum(otutab),\n  FailedSamples = sum(!quality$goodSamples),\n  FailedGenera = sum(!quality$goodGenes)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Samples NamedGenera RetainedAllReadFraction FailedSamples FailedGenera\n1      90         422               0.3613347             0            0\n```\n\n\n:::\n:::\n\n\n### 2. 用双门槛选择 soft-threshold power\n\n\n::: {.cell}\n\n```{.r .cell-code}\npowers <- c(1:12, 14, 16, 18, 20)\nsoft_threshold <- WGCNA::pickSoftThreshold(\n  dat_expr,\n  powerVector = powers,\n  networkType = \"signed\",\n  corFnc = \"bicor\",\n  corOptions = list(use = \"p\", maxPOutliers = 0.10),\n  verbose = 0\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Power SFT.R.sq slope truncated.R.sq mean.k. median.k. max.k.\n1      1   0.2320 14.30         0.7980 212.000  212.0000 222.00\n2      2   0.0501 -3.55         0.7750 113.000  113.0000 129.00\n3      3   0.1540 -3.02         0.8280  63.400   62.7000  80.80\n4      4   0.2950 -2.40         0.8920  37.200   36.4000  53.50\n5      5   0.4930 -1.77         0.9170  22.800   21.8000  37.00\n6      6   0.7380 -1.66         0.8660  14.500   13.5000  27.50\n7      7   0.8770 -1.87         0.9190   9.560    8.5500  22.50\n8      8   0.8480 -1.94         0.8390   6.520    5.5700  19.30\n9      9   0.7370 -2.04         0.6760   4.590    3.6600  17.10\n10    10   0.1760 -3.16        -0.0526   3.330    2.4400  15.50\n11    11   0.1700 -3.75        -0.0165   2.480    1.6500  14.20\n12    12   0.1820 -3.62        -0.0130   1.900    1.1200  13.30\n13    14   0.1260 -2.64         0.0325   1.200    0.5500  11.90\n14    16   0.0678 -1.74         0.1310   0.826    0.2730  11.00\n15    18   0.0857 -1.36         0.0857   0.610    0.1430  10.30\n16    20   0.0577 -1.59         0.1650   0.477    0.0776   9.67\n```\n\n\n:::\n\n```{.r .cell-code}\npower_table <- soft_threshold$fitIndices\neligible_power <- with(\n  power_table,\n  Power[SFT.R.sq >= 0.80 & mean.k. >= 5]\n)\nif (length(eligible_power)) {\n  selected_power <- min(eligible_power)\n  power_gate <- \"PASS\"\n} else {\n  connectivity_ok <- power_table$mean.k. >= 5\n  stopifnot(any(connectivity_ok))\n  selected_power <- power_table$Power[\n    which.max(ifelse(connectivity_ok, power_table$SFT.R.sq, -Inf))\n  ]\n  power_gate <- \"FALLBACK\"\n}\nselected_power_row <- power_table[power_table$Power == selected_power, ]\n\ndata.frame(\n  SelectedPower = selected_power,\n  SignedR2 = selected_power_row$SFT.R.sq,\n  MeanConnectivity = selected_power_row$mean.k.,\n  Gate = power_gate\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SelectedPower  SignedR2 MeanConnectivity Gate\n1             7 0.8765043         9.562958 PASS\n```\n\n\n:::\n:::\n\n\n### 3. 构建 signed TOM、识别并合并模块\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260737)\nwgcna_fit <- WGCNA::blockwiseModules(\n  dat_expr,\n  power = selected_power,\n  networkType = \"signed\",\n  TOMType = \"signed\",\n  corType = \"bicor\",\n  maxPOutliers = 0.10,\n  deepSplit = 2,\n  minModuleSize = 20,\n  mergeCutHeight = 0.25,\n  pamRespectsDendro = FALSE,\n  numericLabels = TRUE,\n  randomSeed = 20260737L,\n  nThreads = 4,\n  verbose = 0\n)\nmodule_colours <- WGCNA::labels2colors(wgcna_fit$colors)\nmodule_eigengenes <- WGCNA::orderMEs(WGCNA::moduleEigengenes(\n  dat_expr,\n  colors = module_colours,\n  excludeGrey = TRUE\n)$eigengenes)\nmodule_sizes <- as.data.frame(table(module_colours), stringsAsFactors = FALSE)\nnames(module_sizes) <- c(\"Module\", \"Genera\")\n\nstopifnot(\n  length(module_colours) == ncol(dat_expr),\n  ncol(module_eigengenes) >= 2L,\n  all(rownames(module_eigengenes) == rownames(dat_expr)),\n  sum(module_sizes$Genera) == ncol(dat_expr)\n)\nmodule_sizes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Module Genera\n1      blue     72\n2     brown     57\n3      grey    115\n4 turquoise    127\n5    yellow     51\n```\n\n\n:::\n:::\n\n\n### 4. Module eigengene–trait correlation 与统一 BH\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrait_data <- data.frame(\n  CW = as.integer(metadata$Group == \"CW\"),\n  IW = as.integer(metadata$Group == \"IW\"),\n  TW = as.integer(metadata$Group == \"TW\"),\n  pH = as.numeric(environment$pH),\n  TOC = as.numeric(environment$TOC),\n  Conductivity = as.numeric(environment$Conductivity),\n  Temperature = as.numeric(environment$Temperature),\n  Precipitation = as.numeric(environment$Precipitation),\n  row.names = rownames(metadata),\n  check.names = FALSE\n)\nmodule_trait_r <- WGCNA::bicor(\n  module_eigengenes,\n  trait_data,\n  use = \"pairwise.complete.obs\",\n  maxPOutliers = 0.10,\n  robustY = FALSE\n)\nmodule_trait_p <- WGCNA::corPvalueStudent(\n  module_trait_r, nSamples = nrow(dat_expr)\n)\nmodule_trait_q <- matrix(\n  stats::p.adjust(module_trait_p, method = \"BH\"),\n  nrow = nrow(module_trait_p),\n  dimnames = dimnames(module_trait_p)\n)\nmodule_trait_ledger <- expand.grid(\n  Module = rownames(module_trait_r),\n  Trait = colnames(module_trait_r),\n  stringsAsFactors = FALSE\n)\nmodule_trait_ledger$Correlation <- as.vector(module_trait_r)\nmodule_trait_ledger$PValue <- as.vector(module_trait_p)\nmodule_trait_ledger$QValue <- as.vector(module_trait_q)\nmodule_trait_ledger$Significant <- module_trait_ledger$QValue < 0.05\n\ndata.frame(\n  Modules = nrow(module_trait_r),\n  Traits = ncol(module_trait_r),\n  Tests = length(module_trait_p),\n  BHSignificant = sum(module_trait_q < 0.05)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Modules Traits Tests BHSignificant\n1       4      8    32            23\n```\n\n\n:::\n:::\n\n\n### 5. 候选 hub 与 pseudocount sensitivity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadjacency_matrix <- WGCNA::adjacency(\n  dat_expr,\n  power = selected_power,\n  type = \"signed\",\n  corFnc = \"bicor\",\n  corOptions = list(use = \"p\", maxPOutliers = 0.10)\n)\nmodule_membership <- WGCNA::signedKME(\n  dat_expr,\n  module_eigengenes,\n  corFnc = \"bicor\",\n  corOptions = 'use=\"p\", maxPOutliers=0.1'\n)\nhub_ledger <- data.frame(\n  FeatureID = colnames(dat_expr),\n  DisplayTaxon = sub(\"Genus:\", \"\", colnames(dat_expr), fixed = TRUE),\n  Module = module_colours,\n  stringsAsFactors = FALSE\n)\nhub_ledger$WithinConnectivity <- vapply(\n  seq_len(ncol(dat_expr)),\n  function(index) {\n    sum(adjacency_matrix[index, module_colours == module_colours[[index]]]) - 1\n  },\n  numeric(1)\n)\nmembership_columns <- match(\n  paste0(\"kME\", hub_ledger$Module), colnames(module_membership)\n)\nhub_ledger$KME <- as.numeric(module_membership[cbind(\n  seq_len(nrow(hub_ledger)), membership_columns\n)])\nhub_ledger$CandidateHub <- with(\n  hub_ledger,\n  Module != \"grey\" & abs(KME) >= 0.80 &\n    ave(\n      WithinConnectivity, Module,\n      FUN = function(x) x >= stats::quantile(x, 0.90)\n    )\n)\n\nset.seed(20260737)\nwgcna_pseudocount_one <- WGCNA::blockwiseModules(\n  make_clr(1.0),\n  power = selected_power,\n  networkType = \"signed\",\n  TOMType = \"signed\",\n  corType = \"bicor\",\n  maxPOutliers = 0.10,\n  deepSplit = 2,\n  minModuleSize = 20,\n  mergeCutHeight = 0.25,\n  pamRespectsDendro = FALSE,\n  numericLabels = TRUE,\n  randomSeed = 20260737L,\n  nThreads = 4,\n  verbose = 0\n)\nmodule_colours_pc_one <- WGCNA::labels2colors(\n  wgcna_pseudocount_one$colors\n)\nadjusted_rand <- function(a, b) {\n  contingency <- table(a, b)\n  choose_two <- function(x) x * (x - 1) / 2\n  n <- sum(contingency)\n  index <- sum(choose_two(contingency))\n  row_index <- sum(choose_two(rowSums(contingency)))\n  column_index <- sum(choose_two(colSums(contingency)))\n  expected <- row_index * column_index / choose_two(n)\n  (index - expected) / (0.5 * (row_index + column_index) - expected)\n}\npseudocount_ari <- adjusted_rand(\n  module_colours, module_colours_pc_one\n)\npair_coclustering_agreement <- mean(\n  outer(module_colours, module_colours, \"==\") ==\n    outer(module_colours_pc_one, module_colours_pc_one, \"==\")\n)\n\ndata.frame(\n  CandidateHubs = sum(hub_ledger$CandidateHub),\n  Pseudocount05Modules = length(setdiff(unique(module_colours), \"grey\")),\n  Pseudocount10Modules = length(setdiff(unique(module_colours_pc_one), \"grey\")),\n  AdjustedRand = pseudocount_ari,\n  PairCoclusteringAgreement = pair_coclustering_agreement\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  CandidateHubs Pseudocount05Modules Pseudocount10Modules AdjustedRand\n1            19                    4                    5    0.7149369\n  PairCoclusteringAgreement\n1                 0.9050111\n```\n\n\n:::\n:::\n\n\n## 模块、性状和 hub 的结论边界 {#sec-audit}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwgcna_audit <- data.frame(\n  Dimension = c(\n    \"Composition\", \"Taxonomic coverage\", \"Soft power\", \"Grey module\",\n    \"Trait family\", \"Confounding\", \"Hub\", \"Sensitivity\"\n  ),\n  FragilePractice = c(\n    \"WGCNA on percentages\",\n    \"Pretend genus table covers all reads\",\n    \"Pick highest scale-free R2\",\n    \"Force every taxon into a module\",\n    \"Report nominal p-values\",\n    \"Read module-trait r as mechanism\",\n    \"Rank degree only\",\n    \"Show one zero replacement\"\n  ),\n  UpgradedContract = c(\n    \"Pre-filtered CLR with declared replacement\",\n    \"Report all-read denominator coverage\",\n    \"R2 plus connectivity gate\",\n    \"Retain and report grey fraction\",\n    \"One BH family across module × trait\",\n    \"Design and collinearity boundary\",\n    \"|kME| plus within-module connectivity\",\n    \"Refit modules and report ARI\"\n  ),\n  stringsAsFactors = FALSE\n)\nknitr::kable(wgcna_audit, caption = \"Microbiome WGCNA audit contract\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Microbiome WGCNA audit contract\n\n|Dimension          |FragilePractice                      |UpgradedContract                                |\n|:------------------|:------------------------------------|:-----------------------------------------------|\n|Composition        |WGCNA on percentages                 |Pre-filtered CLR with declared replacement      |\n|Taxonomic coverage |Pretend genus table covers all reads |Report all-read denominator coverage            |\n|Soft power         |Pick highest scale-free R2           |R2 plus connectivity gate                       |\n|Grey module        |Force every taxon into a module      |Retain and report grey fraction                 |\n|Trait family       |Report nominal p-values              |One BH family across module × trait             |\n|Confounding        |Read module-trait r as mechanism     |Design and collinearity boundary                |\n|Hub                |Rank degree only                     |&#124;kME&#124; plus within-module connectivity |\n|Sensitivity        |Show one zero replacement            |Refit modules and report ARI                    |\n\n\n:::\n:::\n\n\n当前主模型选择 power 7（signed $R^2$ = 0.877，mean connectivity = 9.56），得到 4 个非 grey 模块，115/422 个属未分配。23/32 个预设 module–trait tests 在 BH 后达到 0.05；这些强信号大多同时追踪 wetland group 与相关环境梯度，不能拆成独立机制。\n\n0.5 与 1.0 replacement 的 module assignment adjusted Rand index 为 0.715，说明总体结构较接近但并非完全不变。候选 hub 共 19 个，正文与图中坚持使用 candidate，而不改写为已验证 keystone。\n\n## 出版级美化 {#sec-publication}\n\n### 图 1：soft-threshold 双门槛\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_panel <- ggplot(\n  power_table,\n  aes(x = Power, y = SFT.R.sq)\n) +\n  geom_hline(yintercept = 0.80, linetype = 2, colour = pal_pub[[\"grey\"]]) +\n  geom_line(colour = pal_pub[[\"blue\"]], linewidth = 0.7) +\n  geom_point(\n    aes(fill = Power == selected_power),\n    shape = 21, size = 2.8, colour = \"white\", stroke = 0.35\n  ) +\n  scale_fill_manual(values = c(\"FALSE\" = pal_pub[[\"grey\"]], \"TRUE\" = pal_pub[[\"vermillion\"]]), guide = \"none\") +\n  labs(\n    title = \"A. Scale-free topology fit\",\n    x = \"Soft-threshold power\", y = \"Signed scale-free R²\"\n  ) +\n  theme_pub(base_size = 8.2)\n\nconnectivity_panel <- ggplot(\n  power_table,\n  aes(x = Power, y = mean.k.)\n) +\n  geom_hline(yintercept = 5, linetype = 2, colour = pal_pub[[\"grey\"]]) +\n  geom_line(colour = pal_pub[[\"orange\"]], linewidth = 0.7) +\n  geom_point(\n    aes(fill = Power == selected_power),\n    shape = 21, size = 2.8, colour = \"white\", stroke = 0.35\n  ) +\n  scale_fill_manual(values = c(\"FALSE\" = pal_pub[[\"grey\"]], \"TRUE\" = pal_pub[[\"vermillion\"]]), guide = \"none\") +\n  scale_y_log10() +\n  labs(\n    title = \"B. Mean connectivity\",\n    x = \"Soft-threshold power\", y = \"Mean connectivity (log scale)\"\n  ) +\n  theme_pub(base_size = 8.2)\n\nsoft_threshold_plot <- patchwork::wrap_plots(\n  r2_panel, connectivity_panel, nrow = 1L\n) +\n  patchwork::plot_annotation(\n    title = sprintf(\"Power %d is the first value passing both gates\", selected_power),\n    subtitle = \"Selection requires signed R² >= 0.80 and mean connectivity >= 5\",\n    caption = \"A high R² alone is not sufficient when the resulting network is nearly disconnected.\"\n  )\nsave_pub(\n  soft_threshold_plot, \"figures/37-soft-threshold\",\n  width = 180, height = 122\n)\nsoft_threshold_plot\n```\n\n::: {.cell-output-display}\n![](37-microbial-wgcna_files/figure-html/fig-soft-threshold-1.png){#fig-soft-threshold}\n:::\n:::\n\n\n### 图 2：TOM dendrogram 与 module strip\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_tree <- wgcna_fit$dendrograms[[1L]]\nblock_genes <- wgcna_fit$blockGenes[[1L]]\ndendrogram_data <- ggdendro::dendro_data(\n  stats::as.dendrogram(gene_tree), type = \"rectangle\"\n)\nordered_gene_index <- block_genes[gene_tree$order]\nordered_modules <- module_colours[ordered_gene_index]\nmodule_strip <- data.frame(\n  X = seq_along(ordered_modules),\n  Y = -0.035 * max(dendrogram_data$segments$y),\n  Module = ordered_modules,\n  stringsAsFactors = FALSE\n)\ndendrogram_plot <- ggplot() +\n  geom_segment(\n    data = dendrogram_data$segments,\n    aes(x = x, y = y, xend = xend, yend = yend),\n    colour = \"#4D4D4D\", linewidth = 0.25\n  ) +\n  geom_tile(\n    data = module_strip,\n    aes(x = X, y = Y, fill = Module),\n    width = 1.05, height = 0.045 * max(dendrogram_data$segments$y)\n  ) +\n  scale_fill_identity() +\n  coord_cartesian(clip = \"off\") +\n  labs(\n    title = \"Dynamic tree cut separates four non-grey modules\",\n    subtitle = sprintf(\n      \"%d genera remain grey; merge cut height = 0.25\",\n      sum(module_colours == \"grey\")\n    ),\n    x = \"Genera ordered by signed TOM dissimilarity\",\n    y = \"Clustering height\",\n    caption = \"Module colours are arbitrary identifiers, not biological annotations.\"\n  ) +\n  theme_pub(base_size = 8.5) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank(),\n    legend.position = \"none\",\n    plot.margin = margin(6, 6, 12, 6)\n  )\nsave_pub(\n  dendrogram_plot, \"figures/37-module-dendrogram\",\n  width = 180, height = 132\n)\ndendrogram_plot\n```\n\n::: {.cell-output-display}\n![](37-microbial-wgcna_files/figure-html/fig-module-dendrogram-1.png){#fig-module-dendrogram}\n:::\n:::\n\n\n### 图 3：Module–trait heatmap 同时显示 r 与 BH q\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodule_trait_ledger$ModuleLabel <- sub(\"^ME\", \"\", module_trait_ledger$Module)\nmodule_trait_ledger$Label <- sprintf(\n  \"%.2f\\nq=%s\",\n  module_trait_ledger$Correlation,\n  ifelse(\n    module_trait_ledger$QValue < 0.001,\n    \"<.001\", sprintf(\"%.3f\", module_trait_ledger$QValue)\n  )\n)\nmodule_trait_ledger$TextColour <- ifelse(\n  abs(module_trait_ledger$Correlation) >= 0.55, \"white\", \"black\"\n)\nmodule_trait_plot <- ggplot(\n  module_trait_ledger,\n  aes(x = Trait, y = ModuleLabel, fill = Correlation)\n) +\n  geom_tile(colour = \"white\", linewidth = 0.55) +\n  geom_text(\n    aes(label = Label, colour = TextColour),\n    family = font_pub, size = 2.55, lineheight = 0.88\n  ) +\n  scale_colour_identity() +\n  scale_fill_gradient2(\n    low = pal_pub[[\"blue\"]], mid = \"white\", high = pal_pub[[\"vermillion\"]],\n    midpoint = 0, limits = c(-1, 1)\n  ) +\n  labs(\n    title = \"Module eigengenes mostly track the wetland gradient\",\n    subtitle = sprintf(\n      \"%d of %d module-trait tests have BH q < 0.05\",\n      sum(module_trait_q < 0.05), length(module_trait_q)\n    ),\n    x = NULL, y = \"Module eigengene\", fill = \"Bicor r\",\n    caption = \"CW/IW/TW are one-vs-rest indicators; environmental correlations remain confounded with group and geography.\"\n  ) +\n  theme_pub(base_size = 8.2) +\n  theme(\n    axis.text.x = element_text(angle = 35, hjust = 1),\n    legend.position = \"bottom\"\n  )\nsave_pub(\n  module_trait_plot, \"figures/37-module-trait\",\n  width = 180, height = 138\n)\nmodule_trait_plot\n```\n\n::: {.cell-output-display}\n![](37-microbial-wgcna_files/figure-html/fig-module-trait-1.png){#fig-module-trait}\n:::\n:::\n\n\n### 图 4：candidate hub 与 module sensitivity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_hubs <- hub_ledger[hub_ledger$Module != \"grey\", ]\nlabel_hubs <- head(\n  plot_hubs[\n    order(!plot_hubs$CandidateHub, -abs(plot_hubs$KME), -plot_hubs$WithinConnectivity),\n  ],\n  14L\n)\nhub_plot <- ggplot(\n  plot_hubs,\n  aes(\n    x = abs(KME), y = WithinConnectivity,\n    fill = Module, shape = CandidateHub\n  )\n) +\n  geom_vline(xintercept = 0.80, linetype = 2, colour = \"#555555\") +\n  geom_point(\n    size = 3, alpha = 0.82, colour = \"white\", stroke = 0.4\n  ) +\n  ggrepel::geom_text_repel(\n    data = label_hubs,\n    aes(label = DisplayTaxon),\n    family = font_pub, size = 2.45, min.segment.length = 0,\n    max.overlaps = Inf, show.legend = FALSE\n  ) +\n  scale_fill_identity() +\n  scale_shape_manual(values = c(\"FALSE\" = 21, \"TRUE\" = 24)) +\n  labs(\n    title = \"Hub status requires membership, connectivity and sensitivity\",\n    subtitle = sprintf(\n      \"%d candidates; pseudocount 0.5 vs 1.0 module ARI = %.3f\",\n      sum(hub_ledger$CandidateHub), pseudocount_ari\n    ),\n    x = \"Absolute module membership (|kME|)\",\n    y = \"Within-module connectivity\",\n    shape = \"Candidate hub\",\n    caption = \"Triangles pass |kME| >= 0.80 and the within-module top-decile rule; labels are candidates, not validated keystones.\"\n  ) +\n  theme_pub(base_size = 8.3) +\n  theme(legend.position = \"bottom\")\nsave_pub(\n  hub_plot, \"figures/37-hub-sensitivity\",\n  width = 180, height = 138\n)\nhub_plot\n```\n\n::: {.cell-output-display}\n![](37-microbial-wgcna_files/figure-html/fig-hub-sensitivity-1.png){#fig-hub-sensitivity}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-caution title=\"常见坑：审稿人会追问的八件事\"}\n\n1. **直接输入 relative abundance**：closure 会把模块结构带偏；至少使用明确的 log-ratio 方案并做 sensitivity。  \n2. **样本太少、taxa 太多**：模块会被单个异常样本主导；先检查 `goodSamplesGenes()` 和 sample tree。  \n3. **只看 scale-free R²**：同时报告 mean connectivity 与 power 选择规则。  \n4. **删除 grey taxa 不报告**：灰色比例是模块可分性的证据。  \n5. **每个热图格单独看 p<0.05**：统一调整 module × trait 检验族。  \n6. **binary trait 直接 robust bicor**：本页对 trait 端设 `robustY=FALSE`，避免二元变量的 robust treatment 失真。  \n7. **把 module–trait correlation 写成驱动机制**：先审计 group、空间、批次和环境共线性。  \n8. **把 hub 写成功能核心菌**：需跨队列 module preservation 与实验验证。\n\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> Genus-level counts were aggregated by complete lineage and filtered independently of traits (prevalence ≥20% and total abundance ≥100 reads), retaining 422 named genera across 90 samples. Counts were transformed using a 0.5-count replacement followed by sample-wise centred log-ratio transformation. A signed WGCNA network was constructed with biweight midcorrelation (`maxPOutliers=0.10`). The soft-threshold power was selected as the first value satisfying signed scale-free topology R² ≥0.80 and mean connectivity ≥5 (power 7). Modules were detected from signed topological overlap using dynamic tree cutting (`deepSplit=2`, minimum module size 20) and merged at eigengene dissimilarity 0.25. Module eigengenes were correlated with three one-vs-rest wetland indicators and five prespecified environmental traits; all 32 tests were adjusted together using Benjamini–Hochberg. Candidate hubs required |kME| ≥0.80 and within-module connectivity in the module-specific upper decile. The full network was refitted with a 1.0-count replacement, and assignment sensitivity was summarized by adjusted Rand index. Random seeds were fixed at 20260737.\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read_keyed_tsv(\"your_data/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"your_data/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"your_data/metadata.tsv\")\nenvironment <- read_keyed_tsv(\"your_data/environment.tsv\")\n\n# 必改：分组列和预设连续性状；先按 SampleID 对齐。\nmetadata$Group <- factor(metadata$YourGroupColumn)\ntrait_columns <- c(\"YourTrait1\", \"YourTrait2\")\n\n# 必须在看模块前固定：\nprevalence_cutoff <- 0.20\ntotal_read_cutoff <- 100L\npseudocount <- 0.5\nmin_module_size <- 20L\n```\n:::\n\n\n若数据有 treatment、site、subject、time 或 batch，应先确认这些因素可识别；必要时在变换后做设计合适的 residualization，并把原始与调整后的 module preservation 一起报告。若 genus 注释覆盖低，可在 Family 或 ASV 层运行，但不同 rank 是不同 feature universe，不能直接比较 module 名称。\n\n## 参考 {#sec-references}\n\n- Langfelder P, Horvath S. WGCNA: an R package for weighted correlation network analysis. *BMC Bioinformatics*. 2008;9:559. <https://doi.org/10.1186/1471-2105-9-559>\n- Zhang B, Horvath S. A general framework for weighted gene co-expression network analysis. *Statistical Applications in Genetics and Molecular Biology*. 2005;4:Article17. <https://doi.org/10.2202/1544-6115.1128>\n- Gloor GB, Macklaim JM, Pawlowsky-Glahn V, Egozcue JJ. Microbiome datasets are compositional: and this is not optional. *Frontiers in Microbiology*. 2017;8:2224. <https://doi.org/10.3389/fmicb.2017.02224>\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. <https://doi.org/10.1016/j.geoderma.2018.09.035>\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97:fiaa255. <https://doi.org/10.1093/femsec/fiaa255>\n- WGCNA 1.74 CRAN documentation. <https://cran.r-project.org/package=WGCNA>\n",
    "supporting": [
      "37-microbial-wgcna_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}