{
  "hash": "5a989adfe883f6b2568365ea29f9889a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"污染与对照：blank、kitome、低生物量、decontam\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**用阴性对照和 DNA 浓度识别 16S 数据中的污染 ASV，量化每个样本的污染 reads 比例，并导出保留完整审计轨迹的过滤后三件套。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`；metadata 额外包含 `IsNegative`、`quant_reading` 和 `PlateNumber`。  \n> **预计资源：**1,951 个 ASV、569 个样本（含 30 个阴性对照）；普通笔记本约 1–3 分钟，内存低于 1 GB。\n\n## 低生物量研究为什么必须先证明信号不是污染？ {#sec-target}\n\n低生物量研究中，污染不是一句“设置了 blank”就结束。论文至少应给出三类可审查证据：\n\n1. 生物样本与阴性对照的 reads 分布；\n2. 候选污染物在阴性对照和生物样本中的 prevalence（检出率）；\n3. 每个生物样本中候选污染 reads 的比例，以及它与 DNA 浓度/生物量的关系。\n\n本篇使用 `decontam` 官方示例 `MUClite.rds`。这是一个真实的 16S V4 数据对象，包含 1,951 个 DADA2 ASV、539 个口腔生物样本和分布在 6 块板上的 30 个阴性对照。从该对象导出三件套后，重新计算三类污染证据：\n\n::: {layout-ncol=2}\n![生物样本与阴性对照的测序深度分布。](../figures/04-control-library-size.png){#fig-control-library}\n\n![每个 ASV 在阴性对照和生物样本中的检出率，以及 combined classifier 的判定。](../figures/04-contaminant-prevalence.png){#fig-contaminant-prevalence}\n:::\n\n![每个样本的候选污染 reads 比例随 DNA 浓度的变化。](../figures/04-contaminant-burden.png){#fig-contaminant-burden}\n\n::: {.callout-important title=\"阴性对照必须测序，也必须暂时保留\"}\n阴性对照 reads 少是预期现象，不是“没测好”。如果在 ASV 推断后立刻按低 reads 删除所有 blank，就失去了 prevalence 方法最关键的参照。应先让对照经历与真实样本相同的采集、提取、PCR、建库、测序和序列处理，再做污染判定。\n:::\n\n## 污染为什么在低生物量样本中被放大 {#sec-theory}\n\n### 1. 观测到的 DNA 由样本信号与外源信号共同组成\n\n可以把某个样本的观测 DNA 简化为：\n\n$$\n\\text{Observed DNA}\n=\n\\text{Biological DNA}\n+\n\\text{Reagent/laboratory DNA}\n+\n\\text{Cross-sample DNA}\n$$\n\n试剂或实验室带入的污染 DNA 质量可能不大，却常具有近似固定的绝对量。当真实样本的微生物 DNA 很少时，相同污染量会占据更高的相对比例。因此：\n\n- 阴性对照可能获得可观的微生物 reads；\n- 低 DNA 浓度样本更容易被 reagent/kit background 主导；\n- 相同 kit lot 在高生物量粪便中几乎不可见，在胎盘、血液、肺、皮肤拭子或洁净环境样本中却可能决定结果。\n\n[Salter 等](https://doi.org/10.1186/s12915-014-0087-z)系统展示了试剂与实验室污染对低生物量微生物组的影响；[Eisenhofer 等](https://doi.org/10.1016/j.tim.2018.11.003)进一步总结了从实验设计到报告的控制原则。\n\n### 2. blank 不是一种，而是一条污染定位链\n\n| 对照 | 从哪一步开始 | 主要帮助定位 |\n|---|---|---|\n| Field blank | 采样现场 | 采样器具、空气、运输和保存 |\n| Collection blank | 采样操作 | 拭子、缓冲液和采样步骤 |\n| Extraction blank | DNA 提取 | kit/reagent、工作台和提取批次 |\n| PCR no-template control | PCR | PCR 试剂和扩增环境 |\n| Mock community / positive control | 已知组成 | 提取偏倚、扩增偏倚、串样与流程失败 |\n\n阴性对照回答“没有加入生物样本时出现了什么”，阳性对照回答“已知输入经过流程后变成什么”。两者不能互相替代。若研究跨多个 kit lot、提取板或测序批次，每个关键批次都要有相应对照；把所有 blank 集中在最后一块板上，无法识别批次特异污染。\n\n### 3. kitome 不是可直接套用的黑名单\n\n“kitome”泛指试剂盒和实验室背景中反复出现的微生物 DNA，但它不是固定的物种名单。同一个属：\n\n- 在某个项目中可能是试剂污染；\n- 在另一种真实生态位中可能是优势成员；\n- 还可能同时包含真实信号和污染信号。\n\n按属名删除 `Ralstonia`、`Pseudomonas` 或 `Sphingomonas` 等“常见污染菌”会制造不可追踪的主观偏差。判定应结合本实验的阴性对照、浓度、批次、序列分辨率和丰度模式，而不是仅看 taxonomy。\n\n### 4. `decontam` 的两个基本证据\n\n**Frequency method（频率法）**\n\n若污染 DNA 的绝对量近似固定，其相对丰度会随样本总 DNA 浓度升高而下降。该方法需要每个样本在等摩尔混样前的定量值，且浓度必须为正数。\n\n**Prevalence method（检出率法）**\n\n若一个 ASV 在阴性对照中比在真实样本中更常检出，它更符合污染物模式。该方法需要经过完整流程并测序的阴性对照。\n\n**Combined method（联合方法）**\n\n`decontam` 可用 Fisher 方法合并 frequency 与 prevalence 证据。本例以 `method = \"combined\"`、`threshold = 0.10` 为主分析，同时报告 frequency、prevalence 和按板分层的敏感性结果。\n\n::: {.callout-note title=\"threshold 不是通用 FDR 阈值\"}\n`decontam` 的 `threshold` 是分类器用于拒绝“非污染物”假设的内部概率阈值。`0.10` 是软件默认值，不等于 10% FDR，也不是所有研究的最优阈值。应结合控制设计、诊断图和敏感性分析预先确定并完整报告。\n:::\n\n<details>\n<summary><strong>深入：哪些污染 decontam 不一定能抓到</strong></summary>\n\n`decontam` 识别的是符合浓度或阴性对照模式的 feature。以下问题可能需要额外证据：\n\n- 高丰度样本向相邻孔、索引或低生物量样本的 cross-talk；\n- 所有阴性对照都在不同批次导致的不可识别批次混杂；\n- 污染物同时也是目标生态位真实成员；\n- 只有一个阴性对照，prevalence 几乎无法稳定估计；\n- 某些污染只发生在采样前，而现有对照从提取步骤才开始；\n- 样本已经被污染 reads 主导，仅删除若干 ASV 后仍不可解释。\n\n因此还应检查板位、索引组合、批次、阴性/阳性对照、实验日志和样本总负荷。污染控制是证据整合，不是单一函数调用。\n\n</details>\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、导出真实数据和定义作图函数</strong></summary>\n\n本项目使用 R 4.4.1、Bioconductor 3.19 和 `decontam 1.24.0`。首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"BiocManager\", \"ggplot2\", \"scales\", \"digest\"\n))\nBiocManager::install(version = \"3.19\", ask = FALSE)\nBiocManager::install(\n  c(\"decontam\", \"phyloseq\"),\n  ask = FALSE,\n  update = FALSE\n)\n```\n:::\n\n\n`MUClite.rds` 随 `decontam` 分发。下面代码核对固定对象的 SHA-256，并导出标准三件套：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(phyloseq)\n\nmuc_path <- system.file(\n  \"extdata\",\n  \"MUClite.rds\",\n  package = \"decontam\"\n)\nstopifnot(nzchar(muc_path), file.exists(muc_path))\n\nexpected_sha256 <- paste0(\n  \"801456d5780d5f51308d04c23f447710\",\n  \"2cc5fbe9543ffa62fad2240a99c43d62\"\n)\nobserved_sha256 <- digest::digest(\n  file = muc_path,\n  algo = \"sha256\",\n  serialize = FALSE\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\nps <- readRDS(muc_path)\notutab <- as(phyloseq::otu_table(ps), \"matrix\")\nif (!phyloseq::taxa_are_rows(ps)) {\n  otutab <- t(otutab)\n}\ntaxonomy <- as(phyloseq::tax_table(ps), \"matrix\")\nmetadata <- as.data.frame(phyloseq::sample_data(ps))\nmetadata$IsNegative <- (\n  metadata$Sample_or_Control == \"Control Sample\"\n)\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata))\n)\n\nwrite_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name),\n    x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out,\n    path,\n    sep = \"\\t\",\n    quote = FALSE,\n    row.names = FALSE,\n    na = \"\"\n  )\n}\n\ndir.create(\n  \"data/small/decontam\",\n  recursive = TRUE,\n  showWarnings = FALSE\n)\nwrite_tsv(\n  otutab,\n  \"FeatureID\",\n  \"data/small/decontam/otutab.tsv\"\n)\nwrite_tsv(\n  taxonomy,\n  \"FeatureID\",\n  \"data/small/decontam/taxonomy.tsv\"\n)\nwrite_tsv(\n  metadata,\n  \"SampleID\",\n  \"data/small/decontam/metadata.tsv\"\n)\n```\n:::\n\n\n出版级函数直接定义在文章内：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(decontam)\nlibrary(ggplot2)\n\nstopifnot(\n  identical(\n    as.character(utils::packageVersion(\"decontam\")),\n    \"1.24.0\"\n  )\n)\n\nset.seed(20260718)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(color = \"black\", linewidth = 0.3),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 120,\n  height = 95,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 从三件套读取并核对阴性对照\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"data/small/decontam/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"data/small/decontam/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/decontam/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\nmetadata$IsNegative <- as.logical(metadata$IsNegative)\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(otutab >= 0),\n  all(otutab == floor(otutab)),\n  all(colSums(otutab) > 0),\n  all(c(\n    \"IsNegative\",\n    \"quant_reading\",\n    \"PlateNumber\",\n    \"Sample_or_Control\"\n  ) %in% colnames(metadata)),\n  all(is.finite(metadata$quant_reading)),\n  all(metadata$quant_reading > 0)\n)\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1951  569\n```\n\n\n:::\n\n```{.r .cell-code}\notutab[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     P1101C01701R00 P1101C01702R00 P1101C01703R00 P1101C08701R00 P1101C08702R00\nSeq1           3502          12040           9877           4035          12491\nSeq2           8391            152           2401           5706           1444\nSeq3              0              0              0              0              0\nSeq4            193           7924           4333            257           4384\nSeq5           2838              0              0           3161            294\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxonomy[1:5, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Kingdom         Phylum               Class           Order\nSeq1 Bacteria     Firmicutes             Bacilli Lactobacillales\nSeq2 Bacteria Proteobacteria Gammaproteobacteria  Pasteurellales\nSeq3 Bacteria        unknown             unknown         unknown\nSeq4 Bacteria Proteobacteria Gammaproteobacteria  Pasteurellales\nSeq5 Bacteria Proteobacteria  Betaproteobacteria    Neisseriales\n               Family         Genus\nSeq1 Streptococcaceae Streptococcus\nSeq2  Pasteurellaceae   Haemophilus\nSeq3          unknown       unknown\nSeq4  Pasteurellaceae   Haemophilus\nSeq5    Neisseriaceae     Neisseria\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   X.SampleID PlateNumber Subject     Habitat quant_reading\nP1101C01701R00 P1101C01701R00           3    1101      Tongue          2829\nP1101C01702R00 P1101C01702R00           3    1101 Cheek_Right          5808\nP1101C01703R00 P1101C01703R00           3    1101  Cheek_Left          5052\nP1101C08701R00 P1101C08701R00           3    1101      Tongue          1227\nP1101C08702R00 P1101C08702R00           3    1101 Cheek_Right          3872\nP1101C08703R00 P1101C08703R00           3    1101  Cheek_Left          5872\n               Sample_or_Control IsNegative\nP1101C01701R00       True Sample      FALSE\nP1101C01702R00       True Sample      FALSE\nP1101C01703R00       True Sample      FALSE\nP1101C08701R00       True Sample      FALSE\nP1101C08702R00       True Sample      FALSE\nP1101C08703R00       True Sample      FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\ncontrol_by_plate <- with(\n  metadata,\n  table(PlateNumber, IsNegative)\n)\ncontrol_by_plate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           IsNegative\nPlateNumber FALSE TRUE\n          1    91    5\n          2    90    5\n          3    89    5\n          4    90    5\n          5    89    5\n          6    90    5\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(all(control_by_plate[, \"TRUE\"] == 5))\n```\n:::\n\n\n共有 1,951 个 ASV、569 个测序样本，其中 30 个为阴性对照；每块板均有 5 个对照。这里的独立生物单位不是 539：口腔样本来自重复受试者/部位，污染识别使用样本级浓度和对照，但后续生物学推断仍必须按原研究的重复测量结构建模。\n\n### 2. 先看测序深度，不删除低 reads 对照\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_qc <- data.frame(\n  SampleID = rownames(metadata),\n  SampleClass = factor(\n    ifelse(\n      metadata$IsNegative,\n      \"Negative control\",\n      \"Biological sample\"\n    ),\n    levels = c(\"Biological sample\", \"Negative control\")\n  ),\n  Plate = factor(metadata$PlateNumber),\n  DNAConcentration = metadata$quant_reading,\n  LibrarySize = colSums(otutab),\n  stringsAsFactors = FALSE\n)\n\nlibrary_summary <- do.call(\n  rbind,\n  lapply(\n    split(sample_qc$LibrarySize, sample_qc$SampleClass),\n    function(x) {\n      data.frame(\n        N = length(x),\n        Minimum = min(x),\n        Median = stats::median(x),\n        Maximum = max(x)\n      )\n    }\n  )\n)\nlibrary_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    N Minimum  Median Maximum\nBiological sample 539     554 23956.0   39483\nNegative control   30     192   720.5    8365\n```\n\n\n:::\n:::\n\n\n生物样本的 median library size 为 23,956 reads；阴性对照为 720.5 reads。对照 reads 较少，但并非全部为 0，这正是后续 prevalence 证据的来源。\n\n### 3. 分别运行 frequency、prevalence 与 combined\n\n`decontam` 的矩阵输入是“样本 × feature”，因此需要转置标准三件套中的 `otutab`。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseqtab <- t(otutab)\nis_negative <- metadata[rownames(seqtab), \"IsNegative\"]\ndna_concentration <- metadata[\n  rownames(seqtab),\n  \"quant_reading\"\n]\n\nstopifnot(\n  identical(rownames(seqtab), rownames(metadata)),\n  identical(colnames(seqtab), rownames(taxonomy))\n)\n\ncontam_frequency <- decontam::isContaminant(\n  seqtab,\n  method = \"frequency\",\n  conc = dna_concentration,\n  threshold = 0.10\n)\n\ncontam_prevalence <- decontam::isContaminant(\n  seqtab,\n  method = \"prevalence\",\n  neg = is_negative,\n  threshold = 0.10\n)\n\ncontam_combined <- decontam::isContaminant(\n  seqtab,\n  method = \"combined\",\n  conc = dna_concentration,\n  neg = is_negative,\n  threshold = 0.10\n)\n\nclassification_summary <- data.frame(\n  Method = c(\"Frequency\", \"Prevalence\", \"Combined\"),\n  Threshold = 0.10,\n  ContaminantASVs = c(\n    sum(contam_frequency$contaminant),\n    sum(contam_prevalence$contaminant),\n    sum(contam_combined$contaminant)\n  )\n)\nclassification_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Method Threshold ContaminantASVs\n1  Frequency       0.1              58\n2 Prevalence       0.1             124\n3   Combined       0.1              56\n```\n\n\n:::\n\n```{.r .cell-code}\nmethod_overlap <- table(\n  Frequency = contam_frequency$contaminant,\n  Prevalence = contam_prevalence$contaminant\n)\nmethod_overlap\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Prevalence\nFrequency FALSE TRUE\n    FALSE  1812   81\n    TRUE     15   43\n```\n\n\n:::\n:::\n\n\n在默认 `threshold = 0.10` 下，frequency 法标记 58 个 ASV，prevalence 法标记 124 个，combined 法标记 56 个。两种基本证据不会完全重合：某些高 prevalence 污染物在真实样本和对照中都很常见，单独用 prevalence 可能漏掉；某些低丰度 feature 又主要依赖对照证据。\n\n### 4. 按实验板做敏感性分析\n\n本数据每块板都有 5 个阴性对照，可以检查板特异判定：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontam_batch <- decontam::isContaminant(\n  seqtab,\n  method = \"combined\",\n  conc = dna_concentration,\n  neg = is_negative,\n  batch = factor(metadata[rownames(seqtab), \"PlateNumber\"]),\n  batch.combine = \"minimum\",\n  threshold = 0.10\n)\n\nbatch_comparison <- data.frame(\n  GlobalCombined = contam_combined$contaminant,\n  BatchCombined = contam_batch$contaminant\n)\n\ntable(batch_comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              BatchCombined\nGlobalCombined FALSE TRUE\n         FALSE  1889    6\n         TRUE     15   41\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(\n  Global = sum(batch_comparison$GlobalCombined),\n  BatchAware = sum(batch_comparison$BatchCombined),\n  Shared = sum(\n    batch_comparison$GlobalCombined &\n      batch_comparison$BatchCombined\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Global BatchAware Shared\n1     56         47     41\n```\n\n\n:::\n:::\n\n\n全局 combined 标记 56 个 ASV；按板分析标记 47 个，两者共有 41 个。这里把全局 combined 作为可复现主分析，把按板结果作为敏感性检查；真实研究应根据 kit lot、提取板和对照布局在分析方案中预先确定主模型。\n\n### 5. 生成 feature 级和样本级审计表\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnegative_prevalence <- colMeans(\n  seqtab[is_negative, , drop = FALSE] > 0\n)\nbiological_prevalence <- colMeans(\n  seqtab[!is_negative, , drop = FALSE] > 0\n)\ntotal_feature_reads <- colSums(seqtab)\n\ncontaminant_audit <- data.frame(\n  FeatureID = rownames(contam_combined),\n  taxonomy[rownames(contam_combined), , drop = FALSE],\n  NegativePrevalence = negative_prevalence,\n  BiologicalPrevalence = biological_prevalence,\n  TotalReads = total_feature_reads,\n  FrequencyP = contam_combined$p.freq,\n  PrevalenceP = contam_combined$p.prev,\n  CombinedP = contam_combined$p,\n  GlobalContaminant = contam_combined$contaminant,\n  BatchContaminant = contam_batch$contaminant,\n  check.names = FALSE\n)\n\ncontaminant_ids <- contaminant_audit$FeatureID[\n  contaminant_audit$GlobalContaminant\n]\nlibrary_size <- colSums(otutab)\ncontaminant_reads <- colSums(\n  otutab[contaminant_ids, , drop = FALSE]\n)\n\nsample_burden <- data.frame(\n  SampleID = colnames(otutab),\n  SampleClass = sample_qc$SampleClass,\n  Plate = sample_qc$Plate,\n  DNAConcentration = sample_qc$DNAConcentration,\n  LibrarySize = library_size,\n  ContaminantReads = contaminant_reads,\n  ContaminantFraction = contaminant_reads / library_size,\n  stringsAsFactors = FALSE\n)\n\nburden_summary <- do.call(\n  rbind,\n  lapply(\n    split(\n      sample_burden$ContaminantFraction,\n      sample_burden$SampleClass\n    ),\n    function(x) {\n      data.frame(\n        Minimum = min(x),\n        Median = stats::median(x),\n        Mean = mean(x),\n        Maximum = max(x)\n      )\n    }\n  )\n)\nburden_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Minimum       Median       Mean   Maximum\nBiological sample 0.00000000 0.0001888752 0.01093441 0.9096968\nNegative control  0.06610879 0.8696184865 0.81311348 0.9406807\n```\n\n\n:::\n\n```{.r .cell-code}\nburden_correlation <- stats::cor.test(\n  sample_burden$ContaminantFraction[\n    sample_burden$SampleClass == \"Biological sample\"\n  ],\n  sample_burden$DNAConcentration[\n    sample_burden$SampleClass == \"Biological sample\"\n  ],\n  method = \"spearman\",\n  exact = FALSE\n)\nburden_correlation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  sample_burden$ContaminantFraction[sample_burden$SampleClass == \"Biological sample\"] and sample_burden$DNAConcentration[sample_burden$SampleClass == \"Biological sample\"]\nS = 45698282, p-value < 2.2e-16\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.7510007 \n```\n\n\n:::\n:::\n\n\ncombined 候选污染 ASV 在阴性对照中占 reads 的 median 为 87.0%，在生物样本中为 0.019%。生物样本内，污染 reads 比例与 DNA 浓度呈负相关（Spearman $\\rho=-0.751$，$P<2.2\\times10^{-16}$）。这是低生物量样本更容易受固定背景 DNA 影响的真实数据表现，不是给所有项目套用的污染比例。\n\n### 6. 导出过滤后的三件套，但保留原始对照\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiological_ids <- rownames(metadata)[!metadata$IsNegative]\nkept_features <- setdiff(rownames(otutab), contaminant_ids)\n\notutab_filtered <- otutab[\n  kept_features,\n  biological_ids,\n  drop = FALSE\n]\ntaxonomy_filtered <- taxonomy[\n  kept_features,\n  ,\n  drop = FALSE\n]\nmetadata_filtered <- metadata[\n  biological_ids,\n  ,\n  drop = FALSE\n]\n\nstopifnot(\n  identical(\n    rownames(otutab_filtered),\n    rownames(taxonomy_filtered)\n  ),\n  identical(\n    colnames(otutab_filtered),\n    rownames(metadata_filtered)\n  ),\n  all(colSums(otutab_filtered) > 0)\n)\n\nbiological_reads_before <- sum(\n  otutab[, biological_ids, drop = FALSE]\n)\nbiological_reads_after <- sum(otutab_filtered)\nbiological_reads_removed <- (\n  1 - biological_reads_after / biological_reads_before\n)\n\nfilter_summary <- data.frame(\n  InputFeatures = nrow(otutab),\n  RemovedFeatures = length(contaminant_ids),\n  OutputFeatures = nrow(otutab_filtered),\n  BiologicalSamples = ncol(otutab_filtered),\n  BiologicalReadsRemoved = biological_reads_removed\n)\nfilter_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  InputFeatures RemovedFeatures OutputFeatures BiologicalSamples\n1          1951              56           1895               539\n  BiologicalReadsRemoved\n1            0.007303255\n```\n\n\n:::\n:::\n\n\n本例删除 56 / 1951 个 ASV，保留 1895 个 ASV 和 539 个生物样本；这些 ASV 占全部生物样本 reads 的 0.73%。少量总体 reads 不代表不重要：污染可能集中在少数低 DNA 样本中，最高样本的候选污染比例达到 91.0%。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_result_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name),\n    x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out,\n    path,\n    sep = \"\\t\",\n    quote = FALSE,\n    row.names = FALSE,\n    na = \"\"\n  )\n}\n\nresult_dir <- \"results/04-contamination\"\ndir.create(result_dir, recursive = TRUE, showWarnings = FALSE)\n\nutils::write.table(\n  contaminant_audit,\n  file.path(result_dir, \"contaminant-classification.tsv\"),\n  sep = \"\\t\",\n  quote = FALSE,\n  row.names = FALSE,\n  na = \"\"\n)\nutils::write.table(\n  sample_burden,\n  file.path(result_dir, \"sample-contamination-burden.tsv\"),\n  sep = \"\\t\",\n  quote = FALSE,\n  row.names = FALSE,\n  na = \"\"\n)\nwrite_result_tsv(\n  otutab_filtered,\n  \"FeatureID\",\n  file.path(result_dir, \"otutab.filtered.tsv\")\n)\nwrite_result_tsv(\n  taxonomy_filtered,\n  \"FeatureID\",\n  file.path(result_dir, \"taxonomy.filtered.tsv\")\n)\nwrite_result_tsv(\n  metadata_filtered,\n  \"SampleID\",\n  file.path(result_dir, \"metadata.filtered.tsv\")\n)\n```\n:::\n\n\n原始 `data/small/decontam/` 三件套始终保留，过滤结果和判定表另写到 `results/04-contamination/`。这样可以回溯阈值、恢复被删 feature，并比较不同污染策略。\n\n## 出版级美化 {#sec-polish}\n\n### 1. 阴性对照与生物样本的 library size\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_colors <- c(\n  \"Biological sample\" = \"#0072B2\",\n  \"Negative control\" = \"#D55E00\"\n)\n\np_control_library <- ggplot(\n  sample_qc,\n  aes(SampleClass, LibrarySize, fill = SampleClass)\n) +\n  geom_violin(\n    width = 0.72,\n    trim = FALSE,\n    alpha = 0.25,\n    color = NA\n  ) +\n  geom_boxplot(\n    width = 0.24,\n    outlier.shape = NA,\n    alpha = 0.75,\n    linewidth = 0.45\n  ) +\n  geom_point(\n    position = position_jitter(\n      width = 0.12,\n      height = 0,\n      seed = 20260718\n    ),\n    shape = 21,\n    size = 1.35,\n    stroke = 0.2,\n    alpha = 0.48\n  ) +\n  scale_fill_manual(\n    values = sample_colors,\n    guide = \"none\"\n  ) +\n  scale_y_log10(\n    breaks = c(100, 300, 1000, 3000, 10000, 30000),\n    labels = scales::label_number(big.mark = \",\")\n  ) +\n  labs(\n    title = \"Negative controls carry fewer reads but remain informative\",\n    subtitle = paste0(\n      sum(!metadata$IsNegative),\n      \" biological samples · \",\n      sum(metadata$IsNegative),\n      \" controls · \",\n      length(unique(metadata$PlateNumber)),\n      \" plates\"\n    ),\n    x = NULL,\n    y = \"Library size (reads; log scale)\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(color = \"grey35\", size = 9.5),\n    axis.title.y = element_text(face = \"bold\"),\n    axis.text.x = element_text(face = \"bold\")\n  )\n\np_control_library\n```\n\n::: {.cell-output-display}\n![](04-contamination-controls_files/figure-html/unnamed-chunk-11-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_control_library,\n  \"figures/04-control-library-size\",\n  width = 162,\n  height = 112\n)\n```\n:::\n\n\n### 2. 阴性对照与生物样本中的 prevalence\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprevalence_plot_df <- data.frame(\n  FeatureID = contaminant_audit$FeatureID,\n  NegativePrevalence = contaminant_audit$NegativePrevalence,\n  BiologicalPrevalence = contaminant_audit$BiologicalPrevalence,\n  TotalReads = contaminant_audit$TotalReads,\n  Classification = factor(\n    ifelse(\n      contaminant_audit$GlobalContaminant,\n      \"Likely contaminant\",\n      \"Not classified\"\n    ),\n    levels = c(\"Not classified\", \"Likely contaminant\")\n  )\n)\n\nclassification_colors <- c(\n  \"Not classified\" = \"#B8B8B8\",\n  \"Likely contaminant\" = \"#D55E00\"\n)\n\nlabel_features <- intersect(\n  c(\"Seq30\", \"Seq175\", \"Seq3\"),\n  prevalence_plot_df$FeatureID\n)\n\np_contaminant_prevalence <- ggplot(\n  prevalence_plot_df,\n  aes(\n    NegativePrevalence,\n    BiologicalPrevalence,\n    color = Classification,\n    size = TotalReads\n  )\n) +\n  geom_abline(\n    slope = 1,\n    intercept = 0,\n    linetype = \"dashed\",\n    color = \"grey45\",\n    linewidth = 0.55\n  ) +\n  geom_point(alpha = 0.62) +\n  geom_text(\n    data = subset(\n      prevalence_plot_df,\n      FeatureID %in% label_features\n    ),\n    aes(label = FeatureID),\n    size = 3.0,\n    color = \"grey10\",\n    nudge_y = 0.035,\n    show.legend = FALSE\n  ) +\n  scale_color_manual(\n    values = classification_colors,\n    name = \"Combined classifier\"\n  ) +\n  scale_size_continuous(\n    trans = \"log10\",\n    range = c(0.8, 4.4),\n    breaks = c(10, 1000, 100000, 1000000),\n    labels = scales::label_number(big.mark = \",\"),\n    name = \"Total reads\"\n  ) +\n  scale_x_continuous(\n    limits = c(0, 1),\n    breaks = seq(0, 1, 0.25),\n    labels = scales::percent_format(accuracy = 1),\n    expand = expansion(mult = c(0, 0.02))\n  ) +\n  scale_y_continuous(\n    limits = c(0, 1),\n    breaks = seq(0, 1, 0.25),\n    labels = scales::percent_format(accuracy = 1),\n    expand = expansion(mult = c(0, 0.02))\n  ) +\n  coord_equal(clip = \"off\") +\n  labs(\n    title = \"Negative controls reveal a distinct contaminant branch\",\n    subtitle = paste0(\n      sum(contam_combined$contaminant),\n      \" of \",\n      nrow(contam_combined),\n      \" ASVs classified by combined evidence at threshold = 0.10\"\n    ),\n    x = \"Prevalence in negative controls\",\n    y = \"Prevalence in biological samples\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(color = \"grey35\", size = 9.2),\n    axis.title = element_text(face = \"bold\"),\n    legend.position = \"right\",\n    legend.title = element_text(face = \"bold\"),\n    plot.margin = margin(8, 10, 8, 8)\n  )\n\np_contaminant_prevalence\n```\n\n::: {.cell-output-display}\n![](04-contamination-controls_files/figure-html/unnamed-chunk-12-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_contaminant_prevalence,\n  \"figures/04-contaminant-prevalence\",\n  width = 178,\n  height = 126\n)\n```\n:::\n\n\n虚线是两类样本 prevalence 相等的位置；右下方向表示 feature 在阴性对照中相对更常检出。combined 方法还加入浓度证据，因此并非虚线下方的每个点都被判定，也可能识别出 prevalence 差异不大的强 frequency 候选。\n\n### 3. 污染 burden 与 DNA 浓度\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrho_label <- sprintf(\n  \"Biological samples: Spearman rho = %.2f\",\n  unname(burden_correlation$estimate)\n)\n\np_contaminant_burden <- ggplot(\n  sample_burden,\n  aes(\n    DNAConcentration,\n    ContaminantFraction,\n    color = SampleClass\n  )\n) +\n  geom_point(\n    alpha = 0.62,\n    size = 1.8\n  ) +\n  scale_color_manual(\n    values = sample_colors,\n    name = \"Sample class\"\n  ) +\n  scale_x_log10(\n    labels = scales::label_number(big.mark = \",\")\n  ) +\n  scale_y_continuous(\n    trans = scales::pseudo_log_trans(\n      base = 10,\n      sigma = 0.0001\n    ),\n    breaks = c(0, 0.0001, 0.001, 0.01, 0.1, 1),\n    labels = scales::percent_format(accuracy = 0.01),\n    limits = c(0, 1)\n  ) +\n  annotate(\n    \"label\",\n    x = Inf,\n    y = Inf,\n    label = rho_label,\n    hjust = 1.04,\n    vjust = 1.25,\n    size = 3.1,\n    label.size = 0.25,\n    fill = scales::alpha(\"white\", 0.85),\n    color = \"grey15\"\n  ) +\n  labs(\n    title = \"Contaminant burden rises as DNA concentration falls\",\n    subtitle = paste0(\n      \"Burden is the read fraction assigned to \",\n      sum(contam_combined$contaminant),\n      \" globally classified ASVs\"\n    ),\n    x = \"DNA concentration (PicoGreen intensity; log scale)\",\n    y = \"Candidate contaminant read fraction\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(color = \"grey35\", size = 9.2),\n    axis.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\")\n  ) +\n  guides(color = guide_legend(nrow = 1, byrow = TRUE))\n\np_contaminant_burden\n```\n\n::: {.cell-output-display}\n![](04-contamination-controls_files/figure-html/unnamed-chunk-13-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_contaminant_burden,\n  \"figures/04-contaminant-burden\",\n  width = 174,\n  height = 116\n)\n```\n:::\n\n\n三张图均导出为 PDF、PNG 和 300 dpi LZW-TIFF，图内文字全部使用英文。\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最容易指出的十个污染控制问题\"}\n1. **只写“设置空白对照”，不说明从哪一步开始。** Field blank、extraction blank 和 PCR NTC 监测的环节不同。\n2. **阴性对照只做 PCR、不测序。** 没有 feature table 就无法与真实样本比较 prevalence。\n3. **在污染识别前按低 reads 删除所有 blank。** 这会直接丢失最有价值的控制证据。\n4. **所有 blank 都集中在一个批次。** 不能用它们代表其他 kit lot、提取板或测序批次。\n5. **用“常见污染菌名单”按 taxonomy 删除。** 同一分类群可能是真实成员；应在 ASV/feature 层结合本实验证据。\n6. **把 `threshold = 0.10` 写成 10% FDR。** 它是分类阈值，不是常规多重检验校正后的 FDR。\n7. **只删除污染 ASV，不检查样本 burden。** 某些样本可能已被污染主导，删除后仍不适合进入下游分析。\n8. **把阴性对照当作健康/环境零组参与多样性检验。** 它们是过程控制，不是生物学对照组。\n9. **忽略 plate、kit lot 和 index cross-talk。** `decontam` 不能替代板位图、实验日志和阳性对照。\n10. **只报告删了多少 feature。** 还应报告每类对照数、阈值、批次策略、reads 损失、样本排除和敏感性分析。\n:::\n\n::: {.callout-warning title=\"没有阴性对照，也没有浓度怎么办\"}\n两类核心证据都缺失时，不能事后从 taxonomy 可靠重建污染来源。可以做丰度—批次—板位敏感性检查、与同批公共背景比较并弱化结论，但这不能等价替代真实 blank。下一轮实验应把阴性对照和 DNA 定量作为设计必需项。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n可直接修改的英文模板：\n\n> **Contamination control and feature filtering.** Field/collection blanks, extraction blanks, PCR no-template controls, and mock-community controls were processed alongside biological samples as applicable. Each extraction batch and library-preparation plate contained [number] negative controls. DNA was quantified using [assay] before equimolar pooling. Negative controls were retained through denoising and contaminant inference. Candidate contaminant ASVs were identified with `decontam` version [version] using the [frequency/prevalence/combined] method at a classification threshold of [threshold]; analyses were [pooled across batches/performed within batch using batch variable]. We inspected feature prevalence in negative versus biological samples and quantified the fraction of contaminant-assigned reads per sample. ASVs classified as contaminants were removed from biological samples, while the original feature table, controls, classifier scores, and removal log were retained. Samples were excluded when [prespecified rule and rationale]. Negative controls were not included in downstream biological diversity or differential-abundance analyses.\n\n本例的可复现实写：\n\n> **Worked contamination analysis.** The dataset contained 1,951 ASVs from 539 biological oral samples and 30 negative controls distributed evenly across six plates. DNA concentration was represented by PicoGreen fluorescence (`quant_reading`). Contaminants were identified with `decontam` 1.24.0 using combined frequency and prevalence evidence and a classification threshold of 0.10. The global combined analysis classified 56 ASVs; a plate-aware sensitivity analysis classified 47, with 41 ASVs shared. Removing globally classified ASVs eliminated 0.73% of reads across biological samples. The median candidate-contaminant read fraction was 0.019% in biological samples and 87.0% in negative controls. Original controls and complete feature- and sample-level audit tables were retained.\n\nResults 中不要只写“污染已去除”，应同时给：\n\n- 阴性/阳性对照种类、数量和批次分布；\n- 主要 classifier、版本、阈值和 batch 策略；\n- 候选污染 feature 数及方法间重合；\n- 生物样本总体 reads 损失和逐样本 burden 分布；\n- 被排除样本及预先规定的理由；\n- 改变阈值或 batch 策略后主要结论是否稳定。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. metadata 必需列\n\n三件套路径仍只需替换为你的文件，但 metadata 至少应增加：\n\n| 列名 | 类型 | 含义 |\n|---|---|---|\n| `IsNegative` | logical | 阴性对照为 `TRUE` |\n| `ControlType` | factor | Field/collection/extraction/PCR control |\n| `DNAConcentration` | numeric | 等摩尔混样前的 DNA 定量，必须 $>0$ |\n| `ExtractionBatch` | factor | 提取板或 kit lot |\n| `PCRPlate` | factor | PCR/建库板 |\n| `SequencingRun` | factor | 测序批次 |\n| `PlateRow`, `PlateColumn` | factor/integer | 排查邻孔串样 |\n| `SubjectID`/`SiteID` | factor | 真正的独立生物单位 |\n\n对照也必须拥有唯一 `SampleID`，并成为 `otutab` 的列。不要用空字符串、`NA` 或特殊行名把它们藏在主表之外。\n\n### 2. 三件套通用代码\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"your_data/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"your_data/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"your_data/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  is.logical(metadata$IsNegative),\n  all(metadata$DNAConcentration > 0)\n)\n\n# 每个批次是否同时有生物样本和阴性对照？\ndesign_table <- with(\n  metadata,\n  table(ExtractionBatch, IsNegative)\n)\nprint(design_table)\nstopifnot(all(design_table[, \"TRUE\"] > 0))\n\nseqtab <- t(otutab)\ncontam <- decontam::isContaminant(\n  seqtab,\n  method = \"combined\",\n  conc = metadata$DNAConcentration,\n  neg = metadata$IsNegative,\n  batch = metadata$ExtractionBatch,\n  batch.combine = \"minimum\",\n  threshold = 0.10\n)\n\ncontaminant_ids <- rownames(contam)[contam$contaminant]\nbiological_ids <- rownames(metadata)[!metadata$IsNegative]\n\notutab_clean <- otutab[\n  setdiff(rownames(otutab), contaminant_ids),\n  biological_ids,\n  drop = FALSE\n]\ntaxonomy_clean <- taxonomy[\n  rownames(otutab_clean),\n  ,\n  drop = FALSE\n]\nmetadata_clean <- metadata[\n  colnames(otutab_clean),\n  ,\n  drop = FALSE\n]\n```\n:::\n\n\n若只有阴性对照而没有可靠浓度，使用 `method = \"prevalence\"`；若只有浓度而没有阴性对照，使用 `method = \"frequency\"`。不要为满足 combined 方法而伪造浓度或对照标签。\n\n### 3. 样本排除要预先规定\n\n对每个生物样本计算：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncandidate_fraction <- colSums(\n  otutab[contaminant_ids, , drop = FALSE]\n) / colSums(otutab)\n\nsample_audit <- data.frame(\n  SampleID = colnames(otutab),\n  IsNegative = metadata$IsNegative,\n  DNAConcentration = metadata$DNAConcentration,\n  LibrarySize = colSums(otutab),\n  CandidateContaminantFraction = candidate_fraction\n)\n```\n:::\n\n\n没有一个适用于所有生态位的固定排除比例。可结合以下证据预先制定规则：\n\n- 候选污染 reads 比例；\n- DNA 浓度/绝对微生物负荷；\n- library size 与阳性对照表现；\n- 样本是否处于异常板位或失败批次；\n- 删除污染 ASV 后是否仍有足够信息；\n- 改变阈值后主要结论是否稳定。\n\n主分析与敏感性分析都应保存 feature 清单、样本清单、阈值和理由，避免看完结果后才决定删哪些样本。\n\n## 参考 {#sec-references}\n\n1. Davis NM, Proctor DM, Holmes SP, Relman DA, Callahan BJ. Simple statistical identification and removal of contaminant sequences in marker-gene and metagenomics data. *Microbiome*. 2018;6:226. [doi:10.1186/s40168-018-0605-2](https://doi.org/10.1186/s40168-018-0605-2)\n2. Salter SJ, Cox MJ, Turek EM, et al. Reagent and laboratory contamination can critically impact sequence-based microbiome analyses. *BMC Biology*. 2014;12:87. [doi:10.1186/s12915-014-0087-z](https://doi.org/10.1186/s12915-014-0087-z)\n3. Eisenhofer R, Minich JJ, Marotz C, Cooper A, Knight R, Weyrich LS. Contamination in low microbial biomass microbiome studies: issues and recommendations. *Trends in Microbiology*. 2019;27(2):105–117. [doi:10.1016/j.tim.2018.11.003](https://doi.org/10.1016/j.tim.2018.11.003)\n4. Karstens L, Asquith M, Davin S, et al. Controlling for contaminants in low-biomass 16S rRNA gene sequencing experiments. *mSystems*. 2019;4(4):e00290-19. [doi:10.1128/mSystems.00290-19](https://doi.org/10.1128/mSystems.00290-19)\n5. Minich JJ, Zhu Q, Janssen S, et al. KatharoSeq enables high-throughput microbiome analysis from low-biomass samples. *mSystems*. 2018;3(3):e00218-17. [doi:10.1128/mSystems.00218-17](https://doi.org/10.1128/mSystems.00218-17)\n",
    "supporting": [
      "04-contamination-controls_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}