{
  "hash": "08e8349b4f7d264439ded6bddd04ddf6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"核心菌群（core microbiome）+ 稀有生物圈\"\nauthor: \"Peter\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/28-core-rare-biosphere.R\n  packages:\n  - ggplot2\n  - ggrepel\n  - ragg\n  - readr\n  - scales\n  - svglite\n  - vegan\n---\n\n## 核心菌与稀有菌取决于明确的阈值定义 {#sec-target}\n\nCore microbiome 常见于论文中的 abundance–occupancy 散点图、prevalence 阈值曲线、组间 core 集合交集图，以及 rare-biosphere 丰度分布图。它们都在回答同一个问题：哪些 feature 在指定样本集合中稳定达到可检测水平，哪些 feature 只在少数样本出现或始终维持低相对丰度？\n\n本页使用 `microeco` 2.0.0 随包分发的中国湿地土壤 16S 数据。原研究 [An et al. (2019)](https://doi.org/10.1016/j.geoderma.2018.09.035)比较 inland、coastal 与 Tibetan wetland 的细菌群落；[Liu et al. (2021)](https://doi.org/10.1093/femsec/fiaa255)提供了可复现的三件套数据入口。这里从公开 count、taxonomy 和 metadata 重新计算并绘制四张原创图。\n\n::: {.callout-important title=\"先给结论\"}\n主分析在原始 feature/OTU 层使用全部 reads 为分母：某 feature 在单样本相对丰度 **≥0.01%** 时记为 detected，在 **≥80%** 的 90 个样本中 detected 时记为 global core。这个操作性定义得到 **97** 个 core features，合计占等样本平均相对丰度的 **17.04%**；其中 **34** 个 feature 的全局均值仍低于 0.1%，因此 core 不等于 abundant。\n\n同一规则分别用于 30 个 inland、30 个 coastal 和 30 个 Tibetan wetland 样本时，组内 core 分别为 **166、160、278** 个；三组共有 **59** 个，并集为 **425** 个。global core 与“三组各自都是 core”的交集不是同一个集合。\n\n阈值和深度会改变结论。在 80% prevalence 下，只要求 presence 得到 334 个 core；检测阈值改为 0.01%、0.05%、0.1% 后依次为 97、9、0 个。把每个样本固定稀释到 10,000 reads 后，以至少 1 read 检出得到 167 个 core，与主 core 的 Jaccard 为 0.581。\n\n按单样本 `0 < relative abundance < 0.1%` 定义 local rare mass，其等权均值为 **44.15%**，范围为 **23.33%–59.43%**。这个比例是阈值下的相对丰度质量，不是“44.15% 的细胞处于休眠”或“44.15% 的功能来自稀有菌”。\n:::\n\n## 下载并读取本次分析的数据 {#sec-setup}\n\n需要 R，以及 `ggplot2`、`ggrepel`、`ragg`、`readr`、`scales`、`svglite`、`vegan`。本次使用中国湿地的 OTU count 表、分类表和样本信息表。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"data/small/metadata.tsv\",\n  \"data/small/otutab.tsv\",\n  \"data/small/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nset.seed(20260728)\nfont_pub <- \"sans\"\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\", linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\", size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot,\n    width = width, height = height, units = units,\n    device = grDevices::cairo_pdf, family = base_family, bg = \"white\"\n  )\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"), plot,\n      width = width, height = height, units = units,\n      device = svglite::svglite, bg = \"white\"\n    )\n  }\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot,\n    width = width, height = height, units = units, dpi = dpi,\n    device = ragg::agg_png, bg = \"white\"\n  )\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"), plot,\n      width = width, height = height, units = units, dpi = dpi,\n      device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\"\n    )\n  }\n  invisible(plot)\n}\n\nclean_taxon <- function(x, rank_name) {\n  x <- trimws(as.character(x))\n  x <- sub(\"^[A-Za-z]__\", \"\", x)\n  missing <- is.na(x) | x == \"\" | tolower(x) %in% c(\n    \"unassigned\", \"unclassified\", \"unknown\", \"na\", \"nan\"\n  )\n  x[missing] <- paste(\"Unknown\", tolower(rank_name))\n  x\n}\n\njaccard <- function(a, b) {\n  union_n <- sum(a | b)\n  if (union_n == 0L) 1 else sum(a & b) / union_n\n}\n```\n:::\n\n\n### 读取三件套并核对结构\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character(),\n    col_types = readr::cols(.default = readr::col_character())\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\ninput_paths <- c(\n  otutab = \"data/small/otutab.tsv\",\n  taxonomy = \"data/small/taxonomy.tsv\",\n  metadata = \"data/small/metadata.tsv\"\n)\nexpected_sha256 <- c(\n  otutab = \"76fa79c38da889f35978dc86da4641a270961746709ff38049ee5f67e3c6f7a3\",\n  taxonomy = \"725280bb9a0cd9bda7b540022e92af945ceed52527f8b2d220b055b4489f6901\",\n  metadata = \"df24771dccf27607ddf922c6bca2cafa876d946fbe2e09d14b601accce66ba64\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  function(path) digest::digest(\n    file = path, algo = \"sha256\", serialize = FALSE\n  ),\n  character(1)\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\notutab <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\n\ncounts <- as.matrix(otutab)\nstorage.mode(counts) <- \"integer\"\nstopifnot(\n  identical(rownames(counts), rownames(taxonomy)),\n  setequal(colnames(counts), rownames(metadata)),\n  all(counts >= 0L),\n  all(counts == round(counts)),\n  all(rowSums(counts) > 0L),\n  all(colSums(counts) > 0L)\n)\nmetadata <- metadata[colnames(counts), , drop = FALSE]\n\ngroup_codes <- c(\"IW\", \"CW\", \"TW\")\ngroup_display <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan wetland\"\n)\nmetadata$SampleID <- rownames(metadata)\nmetadata$GroupDisplay <- unname(group_display[metadata$Group])\n\nsample_depths <- colSums(counts)\nrelative_feature <- sweep(counts, 2L, sample_depths, \"/\")\nstopifnot(max(abs(colSums(relative_feature) - 1)) <= 1e-12)\n\ndata.frame(\n  Features = nrow(counts),\n  Samples = ncol(counts),\n  Reads = sum(counts),\n  MinimumDepth = min(sample_depths),\n  MaximumDepth = max(sample_depths)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Features Samples   Reads MinimumDepth MaximumDepth\n1    13628      90 1619670        10364        37374\n```\n\n\n:::\n:::\n\n\n先查看三张表的真实结构：\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab[1:5, 1:5, drop = FALSE]\ntaxonomy[1:6, , drop = FALSE]\nmetadata[1:6, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\nOTU_706  k__Bacteria                     p__Actinobacteria\n                         Class               Order               Family\nOTU_4272            c__Bacilli       o__Bacillales                  f__\nOTU_236                    c__                 o__                  f__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__\nOTU_32                     c__                 o__                  f__\nOTU_706      c__Actinobacteria       o__Frankiales   f__Nakamurellaceae\n                  Genus Species\nOTU_4272            g__     s__\nOTU_236             g__     s__\nOTU_399             g__     s__\nOTU_1556            g__     s__\nOTU_32              g__     s__\nOTU_706  g__Nakamurella     s__\n   Group Type          Saline SampleID   GroupDisplay\nS1    IW   NE Non-saline soil       S1 Inland wetland\nS2    IW   NE Non-saline soil       S2 Inland wetland\nS3    IW   NE Non-saline soil       S3 Inland wetland\nS4    IW   NE Non-saline soil       S4 Inland wetland\nS5    IW   NE Non-saline soil       S5 Inland wetland\nS6    IW   NE Non-saline soil       S6 Inland wetland\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/691722146e287afe063bd43e9ce4fa41977fe763/examples/28-core-rare-biosphere.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"digest\", \"ggplot2\", \"ggrepel\", \"jsonlite\", \"ragg\", \"readr\",\n  \"scales\", \"svglite\", \"systemfonts\", \"vegan\"\n))\n```\n:::\n\n\n</details>\n\n## core 与 rare 都是带条件的操作性定义 {#sec-theory}\n\n### Core 至少需要四个同时公开的坐标\n\n对 feature `i` 和样本 `j`，先计算全部 reads 分母下的相对丰度；给定 detection threshold `d`，再计算 occupancy 或 prevalence：\n\n```text\np[i,j] = x[i,j] / Σ(all features in sample j)\no[i](d) = detected samples for feature i / all samples\n```\n\n主 core 集合可写成：\n\n```text\nC(d, π) = {feature i : o[i](d) ≥ π}\nd = 0.0001 (0.01%); π = 0.80 (80%)\n```\n\n因此一个可复查的 core 声明至少要写清：feature resolution、样本集合、detection threshold 及其边界、prevalence threshold 及其边界。[Neu et al. (2021)](https://doi.org/10.1073/pnas.2104429118)强调 core 定义的多样性；[Custer et al. (2023)](https://doi.org/10.1128/msystems.01066-22)的比较也说明 occupancy-based 方法表现稳健，但任何具体阈值仍依赖研究问题和丰度分布。\n\n### Presence 不是统一的检测强度\n\n原始文库深度为 10,364–37,374 reads。0.01% 阈值在这些样本中对应至少 2–4 reads；单纯 `count > 0` 则永远只要求 1 read。后者会让深测序样本更容易记录低丰度 feature。固定深度稀释可以暴露这种敏感性，但会丢弃 reads，并引入一次随机抽样，所以这里只把它作为审计分支，不替代主相对丰度定义。[Salonen et al. (2012)](https://doi.org/10.1111/j.1469-0691.2012.03855.x)已经展示了 analysis depth 对 core 识别的影响。\n\n### 全体样本与分组内核心菌的分母不同\n\nGlobal prevalence 的分母是全部 90 个样本；group prevalence 的分母是各组 30 个样本。某 feature 可以在 90 个样本中达到 80%，却因其中一组低于 80% 而不属于“三组共有 core”；也可以只在一个组稳定出现，从而属于 group-specific core，却不是 global core。\n\n集合图只有在各组使用同一 feature resolution、detection rule 和 prevalence rule 时才可比较。它展示集合结构，不提供差异显著性。\n\n### Rare 至少有“局部丰度”和“跨样本状态”两层\n\n本页同时保留两个互补定义：\n\n- **Local rare mass**：在每个样本内，汇总 `0 < p < 0.1%` 的 feature 相对丰度；\n- **Feature state**：根据 90 个样本中的均值、最大值、occupancy 和总 reads，把每个 feature 放入一个互斥类别。\n\nFeature state 依次判定为：\n\n1. `Primary core`：满足 0.01% / 80% 主规则；\n2. `Sampling-limited`：非 core、总 reads ≤10 且只在 ≤2 个样本出现；\n3. `Conditionally rare`：非 core、全局均值 <0.1%，但至少一个样本达到 1%；\n4. `Persistently rare`：非 core，且所有样本都低于 0.1%；\n5. `Intermediate`：其余 feature。\n\n`Conditionally rare` 在这里是**跨样本丰度模式**，不能替代时间序列中的动态证据。[Shade et al. (2014)](https://doi.org/10.1128/mBio.01371-14)讨论的是 rare taxa 随时间偶发升高；横断面数据只能说“在部分样本达到较高丰度”，不能写成激活、爆发或恢复。`Sampling-limited` 更只是当前 read/occupancy 证据不足，不能直接解释为生态稀有。\n\n<details>\n<summary><strong>深入：为什么 core abundance mass 与 local rare mass 可以同时很高</strong></summary>\n\n两者不是互补分区。Core membership 看一个 feature 在多少样本达到 0.01%；local rare mass 则在每个样本内把低于 0.1% 的 feature 相加。一个全局 core feature 可以稳定高于 0.01%，但在许多样本仍低于 0.1%，于是同时进入 core 集合和这些样本的 local rare mass。若要做严格闭合分区，应使用后面的五类 `FeatureState`，其丰度质量合计才等于 100%。\n\n</details>\n\n## 用检出率和丰度共同定义核心菌群 {#sec-code}\n\n### 预先确定 0.01% 丰度和 80% 检出率阈值\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_detection <- 0.0001\nprimary_prevalence <- 0.80\nprimary_rare_threshold <- 0.001\nprimary_seed <- 20260728L\n\ndetected_primary <- relative_feature >= primary_detection\ndetected_samples <- rowSums(detected_primary)\nglobal_prevalence <- detected_samples / ncol(counts)\nglobal_core <- global_prevalence >= primary_prevalence\nfeature_equal_mean <- rowMeans(relative_feature)\nfeature_pooled <- rowSums(counts) / sum(counts)\nfeature_maximum <- apply(relative_feature, 1L, max)\npositive_samples <- rowSums(counts > 0L)\n\ndata.frame(\n  DetectionThreshold = primary_detection,\n  PrevalenceThreshold = primary_prevalence,\n  CoreFeatures = sum(global_core),\n  CoreAbundanceMass = sum(feature_equal_mean[global_core]),\n  CoreBelowPointOnePercentMean = sum(\n    global_core & feature_equal_mean < primary_rare_threshold\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  DetectionThreshold PrevalenceThreshold CoreFeatures CoreAbundanceMass\n1              1e-04                 0.8           97         0.1703612\n  CoreBelowPointOnePercentMean\n1                           34\n```\n\n\n:::\n:::\n\n\n这里使用 `>=`，因此刚好等于 0.01% 或 80% 的记录被纳入。不要把边界藏在自然语言里；`>` 与 `>=` 在临界 feature 上可能给出不同集合。\n\n### 保留每个特征的分类信息，不合并来源不同的未注释特征\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_names <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"\n)\nrank_prefix <- c(\n  Kingdom = \"K\", Phylum = \"P\", Class = \"C\", Order = \"O\",\n  Family = \"F\", Genus = \"G\", Species = \"S\"\n)\ntaxonomy_clean <- as.data.frame(\n  setNames(\n    lapply(\n      rank_names,\n      function(rank_name) clean_taxon(taxonomy[[rank_name]], rank_name)\n    ),\n    rank_names\n  ),\n  check.names = FALSE,\n  stringsAsFactors = FALSE\n)\nrownames(taxonomy_clean) <- rownames(taxonomy)\n\nknown_matrix <- vapply(\n  rank_names,\n  function(rank_name) {\n    taxonomy_clean[[rank_name]] != paste(\"Unknown\", tolower(rank_name))\n  },\n  logical(nrow(taxonomy_clean))\n)\nbest_index <- apply(known_matrix, 1L, function(x) {\n  known <- which(x)\n  if (length(known) == 0L) 1L else max(known)\n})\nbest_rank <- rank_names[best_index]\nbest_taxon <- vapply(\n  seq_len(nrow(taxonomy_clean)),\n  function(i) taxonomy_clean[[best_rank[[i]]]][[i]],\n  character(1)\n)\ndisplay_label <- paste0(unname(rank_prefix[best_rank]), \" · \", best_taxon)\nlineage <- apply(taxonomy_clean, 1L, paste, collapse = \" > \")\n```\n:::\n\n\nCore 在原始 feature 层判定。若先按 genus 聚合，所有空 genus 可能被压成一个巨大的 `Unknown genus`，其 occupancy 是人工合并的结果，不能再叫作一个 core taxon。\n\n### 分别计算全体核心菌、分组核心菌及其交集\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_core <- list()\ngroup_prevalence <- list()\nfor (group_code in group_codes) {\n  ids <- metadata$SampleID[metadata$Group == group_code]\n  group_prevalence[[group_code]] <- rowMeans(\n    detected_primary[, ids, drop = FALSE]\n  )\n  group_core[[group_code]] <-\n    group_prevalence[[group_code]] >= primary_prevalence\n}\n\ngroup_core_summary <- data.frame(\n  GroupCode = group_codes,\n  Group = unname(group_display[group_codes]),\n  Samples = vapply(\n    group_codes,\n    function(group_code) sum(metadata$Group == group_code),\n    integer(1)\n  ),\n  CoreFeatures = vapply(group_core, sum, integer(1)),\n  stringsAsFactors = FALSE\n)\n\nshared_three <- sum(\n  group_core[[\"IW\"]] & group_core[[\"CW\"]] & group_core[[\"TW\"]]\n)\ngroup_union <- sum(\n  group_core[[\"IW\"]] | group_core[[\"CW\"]] | group_core[[\"TW\"]]\n)\ndata.frame(\n  GlobalCore = sum(global_core),\n  SharedThreeGroupCore = shared_three,\n  GroupCoreUnion = group_union\n)\ngroup_core_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  GlobalCore SharedThreeGroupCore GroupCoreUnion\n1         97                   59            425\n   GroupCode           Group Samples CoreFeatures\nIW        IW  Inland wetland      30          166\nCW        CW Coastal wetland      30          160\nTW        TW Tibetan wetland      30          278\n```\n\n\n:::\n:::\n\n\n生成七种非空 membership pattern：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembership_flags <- data.frame(\n  IW = group_core[[\"IW\"]],\n  CW = group_core[[\"CW\"]],\n  TW = group_core[[\"TW\"]],\n  stringsAsFactors = FALSE\n)\nmembership_key <- apply(membership_flags, 1L, function(x) {\n  active <- group_codes[as.logical(x[group_codes])]\n  if (length(active) == 0L) \"None\" else paste(active, collapse = \" + \")\n})\nmembership_levels <- c(\n  \"IW\", \"CW\", \"TW\", \"IW + CW\", \"IW + TW\", \"CW + TW\",\n  \"IW + CW + TW\", \"None\"\n)\nmembership_counts <- table(factor(membership_key, levels = membership_levels))\ncore_membership_patterns <- data.frame(\n  Pattern = membership_levels,\n  IW = c(TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE),\n  CW = c(FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE),\n  TW = c(FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE),\n  CoreFeatures = as.integer(membership_counts),\n  stringsAsFactors = FALSE\n)\ncore_membership_patterns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Pattern    IW    CW    TW CoreFeatures\n1           IW  TRUE FALSE FALSE           79\n2           CW FALSE  TRUE FALSE           60\n3           TW FALSE FALSE  TRUE          166\n4      IW + CW  TRUE  TRUE FALSE            8\n5      IW + TW  TRUE FALSE  TRUE           20\n6      CW + TW FALSE  TRUE  TRUE           33\n7 IW + CW + TW  TRUE  TRUE  TRUE           59\n8         None FALSE FALSE FALSE        13203\n```\n\n\n:::\n:::\n\n\n### 同时扫描 detection、prevalence 与 read depth\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetection_thresholds <- c(0, 0.0001, 0.0005, 0.001)\ndetection_labels <- c(\"Presence\", \"0.01%\", \"0.05%\", \"0.1%\")\nprevalence_thresholds <- c(0.50, 0.80, 0.90, 1.00)\n\nthreshold_rows <- list()\nfor (detection_i in seq_along(detection_thresholds)) {\n  threshold <- detection_thresholds[[detection_i]]\n  detected <- if (threshold == 0) {\n    counts > 0L\n  } else {\n    relative_feature >= threshold\n  }\n  prevalence <- rowMeans(detected)\n  for (prevalence_threshold in prevalence_thresholds) {\n    mask <- prevalence >= prevalence_threshold\n    threshold_rows[[length(threshold_rows) + 1L]] <- data.frame(\n      DetectionThreshold = threshold,\n      DetectionLabel = detection_labels[[detection_i]],\n      PrevalenceThreshold = prevalence_threshold,\n      PrevalenceLabel = scales::percent(prevalence_threshold, accuracy = 1),\n      CoreFeatures = sum(mask),\n      CoreAbundanceMass = sum(feature_equal_mean[mask]),\n      stringsAsFactors = FALSE\n    )\n  }\n}\ncore_threshold_sensitivity <- do.call(rbind, threshold_rows)\ncore_threshold_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   DetectionThreshold DetectionLabel PrevalenceThreshold PrevalenceLabel\n1               0e+00       Presence                 0.5             50%\n2               0e+00       Presence                 0.8             80%\n3               0e+00       Presence                 0.9             90%\n4               0e+00       Presence                 1.0            100%\n5               1e-04          0.01%                 0.5             50%\n6               1e-04          0.01%                 0.8             80%\n7               1e-04          0.01%                 0.9             90%\n8               1e-04          0.01%                 1.0            100%\n9               5e-04          0.05%                 0.5             50%\n10              5e-04          0.05%                 0.8             80%\n11              5e-04          0.05%                 0.9             90%\n12              5e-04          0.05%                 1.0            100%\n13              1e-03           0.1%                 0.5             50%\n14              1e-03           0.1%                 0.8             80%\n15              1e-03           0.1%                 0.9             90%\n16              1e-03           0.1%                 1.0            100%\n   CoreFeatures CoreAbundanceMass\n1          1499        0.59976021\n2           334        0.31770343\n3           166        0.21996271\n4            27        0.07022308\n5           404        0.35945370\n6            97        0.17036121\n7            53        0.11923113\n8            10        0.04213067\n9            48        0.12443783\n10            9        0.03881217\n11            5        0.02587754\n12            0        0.00000000\n13           16        0.06323718\n14            0        0.00000000\n15            0        0.00000000\n16            0        0.00000000\n```\n\n\n:::\n:::\n\n\n再把相对丰度阈值翻译成每个原始文库需要的最少 reads：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetection_count_audit <- do.call(rbind, lapply(seq_along(sample_depths), function(i) {\n  data.frame(\n    SampleID = names(sample_depths)[[i]],\n    GroupCode = metadata[names(sample_depths)[[i]], \"Group\"],\n    LibrarySize = sample_depths[[i]],\n    DetectionThreshold = detection_thresholds,\n    DetectionLabel = detection_labels,\n    MinimumReads = ifelse(\n      detection_thresholds == 0,\n      1L,\n      ceiling(sample_depths[[i]] * detection_thresholds)\n    ),\n    stringsAsFactors = FALSE\n  )\n}))\nsubset(detection_count_audit, DetectionLabel == \"0.01%\")[1:8, ]\nrange(subset(\n  detection_count_audit,\n  DetectionLabel == \"0.01%\"\n)$MinimumReads)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   SampleID GroupCode LibrarySize DetectionThreshold DetectionLabel\n2        S1        IW       25542              1e-04          0.01%\n6        S2        IW       26764              1e-04          0.01%\n10       S3        IW       12843              1e-04          0.01%\n14       S4        IW       13280              1e-04          0.01%\n18       S5        IW       17640              1e-04          0.01%\n22       S6        IW       22525              1e-04          0.01%\n26       S7        IW       17370              1e-04          0.01%\n30       S9        IW       25295              1e-04          0.01%\n   MinimumReads\n2             3\n6             3\n10            2\n14            2\n18            2\n22            3\n26            2\n30            3\n[1] 2 4\n```\n\n\n:::\n:::\n\n\n固定深度分支使用相同 seed，并重复一次验证确定性：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrarefaction_depth <- 10000L\nset.seed(primary_seed)\nrarefied_counts <- t(vegan::rrarefy(\n  t(counts),\n  sample = rarefaction_depth\n))\nset.seed(primary_seed)\nrarefied_repeat <- t(vegan::rrarefy(\n  t(counts),\n  sample = rarefaction_depth\n))\nstopifnot(\n  identical(rarefied_counts, rarefied_repeat),\n  all(colSums(rarefied_counts) == rarefaction_depth)\n)\n\nraw_presence_core <- rowMeans(counts > 0L) >= primary_prevalence\nrarefied_one_read_prevalence <- rowMeans(rarefied_counts > 0L)\nrarefied_two_read_prevalence <- rowMeans(rarefied_counts >= 2L)\nrarefied_one_read_core <-\n  rarefied_one_read_prevalence >= primary_prevalence\nrarefied_two_read_core <-\n  rarefied_two_read_prevalence >= primary_prevalence\n\ndepth_sensitivity <- data.frame(\n  Definition = c(\n    \"Raw presence\", \"Raw 0.01%\", \"Rarefied one read\", \"Rarefied two reads\"\n  ),\n  CoreFeatures = c(\n    sum(raw_presence_core),\n    sum(global_core),\n    sum(rarefied_one_read_core),\n    sum(rarefied_two_read_core)\n  ),\n  JaccardWithPrimary = c(\n    jaccard(raw_presence_core, global_core),\n    1,\n    jaccard(rarefied_one_read_core, global_core),\n    jaccard(rarefied_two_read_core, global_core)\n  ),\n  stringsAsFactors = FALSE\n)\ndepth_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Definition CoreFeatures JaccardWithPrimary\n1       Raw presence          334          0.2904192\n2          Raw 0.01%           97          1.0000000\n3  Rarefied one read          167          0.5808383\n4 Rarefied two reads           52          0.5360825\n```\n\n\n:::\n:::\n\n\n### 划分类群状态，并计算每个样本中的稀有类群占比\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_state <- ifelse(\n  global_core,\n  \"Primary core\",\n  ifelse(\n    rowSums(counts) <= 10L & positive_samples <= 2L,\n    \"Sampling-limited\",\n    ifelse(\n      feature_equal_mean < primary_rare_threshold & feature_maximum >= 0.01,\n      \"Conditionally rare\",\n      ifelse(\n        feature_maximum < primary_rare_threshold,\n        \"Persistently rare\",\n        \"Intermediate\"\n      )\n    )\n  )\n)\nstate_levels <- c(\n  \"Primary core\", \"Conditionally rare\", \"Persistently rare\",\n  \"Sampling-limited\", \"Intermediate\"\n)\nfeature_state <- factor(feature_state, levels = state_levels)\n\nfeature_state_summary <- do.call(rbind, lapply(state_levels, function(state) {\n  mask <- feature_state == state\n  data.frame(\n    FeatureState = state,\n    Features = sum(mask),\n    FeatureFraction = mean(mask),\n    EqualSampleAbundanceMass = sum(feature_equal_mean[mask]),\n    stringsAsFactors = FALSE\n  )\n}))\nstopifnot(\n  sum(feature_state_summary$Features) == nrow(counts),\n  abs(sum(feature_state_summary$EqualSampleAbundanceMass) - 1) <= 1e-12\n)\nfeature_state_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        FeatureState Features FeatureFraction EqualSampleAbundanceMass\n1       Primary core       97     0.007117699              0.170361211\n2 Conditionally rare      200     0.014675668              0.093886048\n3  Persistently rare     8407     0.616891694              0.172682530\n4   Sampling-limited     1155     0.084751981              0.001583944\n5       Intermediate     3769     0.276562959              0.561486267\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrare_thresholds <- c(0.0001, 0.0005, 0.001, 0.005)\nrare_threshold_labels <- c(\"0.01%\", \"0.05%\", \"0.1%\", \"0.5%\")\nrare_sample_rows <- list()\nfor (threshold_i in seq_along(rare_thresholds)) {\n  threshold <- rare_thresholds[[threshold_i]]\n  rare_mass <- colSums(\n    relative_feature *\n      (relative_feature > 0 & relative_feature < threshold)\n  )\n  rare_sample_rows[[threshold_i]] <- data.frame(\n    SampleID = colnames(counts),\n    GroupCode = metadata[colnames(counts), \"Group\"],\n    Group = unname(group_display[metadata[colnames(counts), \"Group\"]]),\n    Type = metadata[colnames(counts), \"Type\"],\n    Saline = metadata[colnames(counts), \"Saline\"],\n    RareThreshold = threshold,\n    ThresholdLabel = rare_threshold_labels[[threshold_i]],\n    RareMass = rare_mass,\n    stringsAsFactors = FALSE\n  )\n}\nrare_mass_all_thresholds <- do.call(rbind, rare_sample_rows)\nrare_mass_by_sample <- subset(\n  rare_mass_all_thresholds,\n  RareThreshold == primary_rare_threshold\n)\n\nrare_threshold_sensitivity <- do.call(\n  rbind,\n  lapply(seq_along(rare_thresholds), function(i) {\n    x <- subset(\n      rare_mass_all_thresholds,\n      RareThreshold == rare_thresholds[[i]]\n    )\n    rows <- list(data.frame(\n      GroupCode = \"ALL\",\n      Group = \"All samples\",\n      RareThreshold = rare_thresholds[[i]],\n      ThresholdLabel = rare_threshold_labels[[i]],\n      Samples = nrow(x),\n      MeanRareMass = mean(x$RareMass),\n      MinimumRareMass = min(x$RareMass),\n      MaximumRareMass = max(x$RareMass),\n      stringsAsFactors = FALSE\n    ))\n    for (group_code in group_codes) {\n      values <- x$RareMass[x$GroupCode == group_code]\n      rows[[length(rows) + 1L]] <- data.frame(\n        GroupCode = group_code,\n        Group = unname(group_display[group_code]),\n        RareThreshold = rare_thresholds[[i]],\n        ThresholdLabel = rare_threshold_labels[[i]],\n        Samples = length(values),\n        MeanRareMass = mean(values),\n        MinimumRareMass = min(values),\n        MaximumRareMass = max(values),\n        stringsAsFactors = FALSE\n      )\n    }\n    do.call(rbind, rows)\n  })\n)\nsubset(rare_threshold_sensitivity, GroupCode == \"ALL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   GroupCode       Group RareThreshold ThresholdLabel Samples MeanRareMass\n1        ALL All samples         1e-04          0.01%      90    0.1046766\n5        ALL All samples         5e-04          0.05%      90    0.3186408\n9        ALL All samples         1e-03           0.1%      90    0.4415015\n13       ALL All samples         5e-03           0.5%      90    0.7365072\n   MinimumRareMass MaximumRareMass\n1       0.06829096       0.1422155\n5       0.20080436       0.4381278\n9       0.23329533       0.5943485\n13      0.33219330       0.9110084\n```\n\n\n:::\n:::\n\n\n### 汇总各特征的分类结果与敏感性分析\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_dir <- \"results/28-core-rare-biosphere\"\ndir.create(result_dir, recursive = TRUE, showWarnings = FALSE)\n\nfeature_occupancy_abundance <- data.frame(\n  FeatureID = rownames(counts),\n  FeatureState = as.character(feature_state),\n  TotalReads = rowSums(counts),\n  PositiveSamples = positive_samples,\n  RawPresence = positive_samples / ncol(counts),\n  DetectedSamples = detected_samples,\n  Prevalence = global_prevalence,\n  EqualSampleMean = feature_equal_mean,\n  PooledReadFraction = feature_pooled,\n  MaximumSampleAbundance = feature_maximum,\n  PrimaryCore = global_core,\n  IWPrevalence = group_prevalence[[\"IW\"]],\n  CWPrevalence = group_prevalence[[\"CW\"]],\n  TWPrevalence = group_prevalence[[\"TW\"]],\n  BestRank = best_rank,\n  BestTaxon = best_taxon,\n  DisplayLabel = display_label,\n  Lineage = lineage,\n  stringsAsFactors = FALSE,\n  check.names = FALSE\n)\n\ncore_feature_taxonomy <- data.frame(\n  FeatureID = rownames(counts)[global_core],\n  taxonomy_clean[global_core, , drop = FALSE],\n  DetectedSamples = detected_samples[global_core],\n  Prevalence = global_prevalence[global_core],\n  EqualSampleMean = feature_equal_mean[global_core],\n  MaximumSampleAbundance = feature_maximum[global_core],\n  stringsAsFactors = FALSE,\n  check.names = FALSE\n)\ncore_feature_taxonomy <- core_feature_taxonomy[\n  order(core_feature_taxonomy$EqualSampleMean, decreasing = TRUE),\n  , drop = FALSE\n]\n\nrarefaction_ledger <- data.frame(\n  SampleID = colnames(counts),\n  GroupCode = metadata[colnames(counts), \"Group\"],\n  OriginalLibrarySize = sample_depths,\n  RarefactionDepth = rarefaction_depth,\n  RarefiedLibrarySize = colSums(rarefied_counts),\n  ReadsDiscarded = sample_depths - colSums(rarefied_counts),\n  Seed = primary_seed,\n  stringsAsFactors = FALSE\n)\n\nreadr::write_tsv(\n  feature_occupancy_abundance,\n  file.path(result_dir, \"article-feature-occupancy-abundance.tsv\")\n)\nreadr::write_tsv(\n  core_feature_taxonomy,\n  file.path(result_dir, \"article-core-feature-taxonomy.tsv\")\n)\nreadr::write_tsv(\n  group_core_summary,\n  file.path(result_dir, \"article-group-core-summary.tsv\")\n)\nreadr::write_tsv(\n  core_membership_patterns,\n  file.path(result_dir, \"article-core-membership-patterns.tsv\")\n)\nreadr::write_tsv(\n  core_threshold_sensitivity,\n  file.path(result_dir, \"article-core-threshold-sensitivity.tsv\")\n)\nreadr::write_tsv(\n  detection_count_audit,\n  file.path(result_dir, \"article-detection-count-audit.tsv\")\n)\nreadr::write_tsv(\n  rarefaction_ledger,\n  file.path(result_dir, \"article-rarefaction-ledger.tsv\")\n)\nreadr::write_tsv(\n  depth_sensitivity,\n  file.path(result_dir, \"article-depth-sensitivity.tsv\")\n)\nreadr::write_tsv(\n  feature_state_summary,\n  file.path(result_dir, \"article-feature-state-summary.tsv\")\n)\nreadr::write_tsv(\n  rare_mass_by_sample,\n  file.path(result_dir, \"article-rare-mass-by-sample.tsv\")\n)\nreadr::write_tsv(\n  rare_threshold_sensitivity,\n  file.path(result_dir, \"article-rare-threshold-sensitivity.tsv\")\n)\n```\n:::\n\n\n## 比较核心定义对阈值和测序深度的敏感性 {#sec-publication}\n\n### Occupancy–abundance：core、rare 与中间状态放在同一坐标系\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_colours <- c(\n  `Primary core` = \"#0072B2\",\n  `Conditionally rare` = \"#D55E00\",\n  `Persistently rare` = \"#56B4E9\",\n  `Sampling-limited` = \"#9CA3AF\",\n  Intermediate = \"#CC79A7\"\n)\noccupancy_plot_data <- feature_occupancy_abundance\noccupancy_plot_data$FeatureState <- factor(\n  occupancy_plot_data$FeatureState,\n  levels = state_levels\n)\ncore_label_ids <- head(\n  rownames(counts)[global_core][order(\n    feature_equal_mean[global_core], decreasing = TRUE\n  )],\n  5L\n)\nconditional_mask <- feature_state == \"Conditionally rare\"\nconditional_label_ids <- head(\n  rownames(counts)[conditional_mask][order(\n    feature_maximum[conditional_mask], decreasing = TRUE\n  )],\n  4L\n)\noccupancy_labels <- subset(\n  occupancy_plot_data,\n  FeatureID %in% c(core_label_ids, conditional_label_ids)\n)\noccupancy_labels$PointLabel <- paste0(\n  occupancy_labels$DisplayLabel,\n  \" (\",\n  occupancy_labels$FeatureID,\n  \")\"\n)\n\noccupancy_plot <- ggplot2::ggplot(\n  occupancy_plot_data,\n  ggplot2::aes(\n    x = Prevalence,\n    y = EqualSampleMean,\n    colour = FeatureState\n  )\n) +\n  ggplot2::geom_hline(\n    yintercept = primary_rare_threshold,\n    colour = \"#6B7280\",\n    linewidth = 0.45,\n    linetype = \"22\"\n  ) +\n  ggplot2::geom_vline(\n    xintercept = primary_prevalence,\n    colour = \"#1F2937\",\n    linewidth = 0.55,\n    linetype = \"22\"\n  ) +\n  ggplot2::geom_point(size = 1.15, alpha = 0.58) +\n  ggrepel::geom_text_repel(\n    data = occupancy_labels,\n    ggplot2::aes(label = PointLabel),\n    seed = primary_seed,\n    family = font_pub,\n    size = 2.25,\n    colour = \"#17202A\",\n    box.padding = 0.25,\n    point.padding = 0.15,\n    min.segment.length = 0,\n    max.overlaps = Inf,\n    show.legend = FALSE\n  ) +\n  ggplot2::scale_colour_manual(values = state_colours, drop = FALSE) +\n  ggplot2::scale_x_continuous(\n    limits = c(0, 1.01),\n    breaks = seq(0, 1, by = 0.2),\n    labels = scales::label_percent(accuracy = 1),\n    expand = ggplot2::expansion(mult = c(0.005, 0.01))\n  ) +\n  ggplot2::scale_y_log10(\n    labels = scales::label_percent(accuracy = 0.001),\n    expand = ggplot2::expansion(mult = c(0.04, 0.16))\n  ) +\n  ggplot2::annotation_logticks(sides = \"l\", linewidth = 0.25) +\n  ggplot2::labs(\n    title = \"Core membership depends on an explicit abundance–occupancy rule\",\n    subtitle = \"Primary core: at least 0.01% abundance in at least 80% of 90 samples\",\n    x = \"Prevalence at the 0.01% detection threshold\",\n    y = \"Equal-sample mean relative abundance\",\n    colour = \"Feature state\",\n    caption = paste(\n      \"Each point is one feature/OTU; all-read denominators and equal sample weights are retained.\",\n      \"The horizontal guide marks 0.1% mean abundance, not a core boundary.\"\n    )\n  ) +\n  theme_pub(base_size = 8.5) +\n  ggplot2::theme(\n    legend.position = \"bottom\",\n    panel.grid.minor = ggplot2::element_blank()\n  )\n\nsave_pub(\n  occupancy_plot,\n  \"figures/28-occupancy-abundance\",\n  width = 183,\n  height = 132\n)\noccupancy_plot\n```\n\n::: {.cell-output-display}\n![Feature-level abundance–occupancy 与互斥状态。](28-core-rare-biosphere_files/figure-html/fig-core-occupancy-abundance-1.png){#fig-core-occupancy-abundance}\n:::\n:::\n\n\n纵虚线右侧是 prevalence ≥80%，但只有满足单样本 0.01% detection rule 的 feature 才能到达这里。横虚线只标记全局均值 0.1%，不是 core 判定线；右下区域因此可以出现“稳定检出但平均丰度不高”的 core。\n\n### Group-core membership：交集图展示集合，不展示显著性\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembership_plot_data <- subset(\n  core_membership_patterns,\n  Pattern != \"None\"\n)\nmembership_plot_data <- membership_plot_data[\n  order(membership_plot_data$CoreFeatures, decreasing = TRUE),\n  , drop = FALSE\n]\nmembership_plot_data$X <- seq_len(nrow(membership_plot_data))\nmembership_plot_data$PatternLabel <- gsub(\n  \" \\\\+ \",\n  \" · \",\n  membership_plot_data$Pattern\n)\nmembership_y <- c(IW = -18, CW = -39, TW = -60)\nmembership_grid <- do.call(rbind, lapply(\n  seq_len(nrow(membership_plot_data)),\n  function(i) {\n    data.frame(\n      X = membership_plot_data$X[[i]],\n      GroupCode = group_codes,\n      Y = unname(membership_y[group_codes]),\n      Active = as.logical(membership_plot_data[i, group_codes]),\n      stringsAsFactors = FALSE\n    )\n  }\n))\nmembership_segments <- do.call(rbind, lapply(\n  seq_len(nrow(membership_plot_data)),\n  function(i) {\n    active_y <- membership_y[group_codes[\n      as.logical(membership_plot_data[i, group_codes])\n    ]]\n    data.frame(\n      X = membership_plot_data$X[[i]],\n      YMin = min(active_y),\n      YMax = max(active_y),\n      stringsAsFactors = FALSE\n    )\n  }\n))\n\nmembership_plot <- ggplot2::ggplot(\n  membership_plot_data,\n  ggplot2::aes(x = X)\n) +\n  ggplot2::geom_col(\n    ggplot2::aes(y = CoreFeatures),\n    width = 0.68,\n    fill = \"#0072B2\"\n  ) +\n  ggplot2::geom_text(\n    ggplot2::aes(y = CoreFeatures, label = CoreFeatures),\n    vjust = -0.35,\n    family = font_pub,\n    size = 2.8\n  ) +\n  ggplot2::geom_segment(\n    data = membership_segments,\n    ggplot2::aes(x = X, xend = X, y = YMin, yend = YMax),\n    inherit.aes = FALSE,\n    linewidth = 0.75,\n    colour = \"#374151\"\n  ) +\n  ggplot2::geom_point(\n    data = membership_grid,\n    ggplot2::aes(x = X, y = Y),\n    inherit.aes = FALSE,\n    size = 3.1,\n    shape = 21,\n    stroke = 0.45,\n    colour = \"#B8C0CC\",\n    fill = \"white\"\n  ) +\n  ggplot2::geom_point(\n    data = subset(membership_grid, Active),\n    ggplot2::aes(x = X, y = Y),\n    inherit.aes = FALSE,\n    size = 3.1,\n    colour = \"#17202A\"\n  ) +\n  ggplot2::annotate(\n    \"text\",\n    x = 0.38,\n    y = unname(membership_y),\n    label = group_codes,\n    hjust = 0,\n    family = font_pub,\n    size = 2.7,\n    fontface = \"bold\"\n  ) +\n  ggplot2::scale_x_continuous(\n    breaks = membership_plot_data$X,\n    labels = membership_plot_data$PatternLabel,\n    limits = c(0.3, nrow(membership_plot_data) + 0.55),\n    expand = ggplot2::expansion(mult = c(0, 0))\n  ) +\n  ggplot2::scale_y_continuous(\n    breaks = c(0, 50, 100, 150),\n    labels = c(\"0\", \"50\", \"100\", \"150\"),\n    limits = c(-72, 190),\n    expand = ggplot2::expansion(mult = c(0, 0.015))\n  ) +\n  ggplot2::labs(\n    title = \"Group cores overlap, but they are not the global core\",\n    subtitle = \"The same 0.01% detection and 80% prevalence rules are applied within each 30-sample group\",\n    x = \"Group-core membership pattern\",\n    y = \"Features\",\n    caption = paste(\n      \"The seven non-empty intersections contain 425 features; 59 are core in all three groups.\",\n      \"IW, inland; CW, coastal; TW, Tibetan wetland.\"\n    )\n  ) +\n  theme_pub(base_size = 8.5) +\n  ggplot2::theme(\n    legend.position = \"none\",\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor = ggplot2::element_blank(),\n    axis.text.x = ggplot2::element_text(angle = 24, hjust = 1),\n    axis.ticks.y = ggplot2::element_blank()\n  )\n\nsave_pub(\n  membership_plot,\n  \"figures/28-group-core-membership\",\n  width = 165,\n  height = 118\n)\nmembership_plot\n```\n\n::: {.cell-output-display}\n![相同阈值下三个湿地组的 core membership pattern。](28-core-rare-biosphere_files/figure-html/fig-group-core-membership-1.png){#fig-group-core-membership}\n:::\n:::\n\n\n`TW only` 有 166 个 feature，并不等于它们在 Tibetan wetland “显著富集”。Membership 只说明达到阈值；若要比较 abundance 或 prevalence，还需要与研究设计匹配的模型、effect size 和多重检验。\n\n### Threshold × depth heatmap：把敏感性放进主结果\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixed_depth_rows <- list()\nfor (prevalence_threshold in prevalence_thresholds) {\n  fixed_depth_rows[[length(fixed_depth_rows) + 1L]] <- data.frame(\n    DetectionLabel = c(\"One read\", \"Two reads\"),\n    PrevalenceThreshold = prevalence_threshold,\n    PrevalenceLabel = scales::percent(prevalence_threshold, accuracy = 1),\n    CoreFeatures = c(\n      sum(rarefied_one_read_prevalence >= prevalence_threshold),\n      sum(rarefied_two_read_prevalence >= prevalence_threshold)\n    ),\n    stringsAsFactors = FALSE\n  )\n}\nfixed_depth_sensitivity <- do.call(rbind, fixed_depth_rows)\nthreshold_plot_data <- rbind(\n  data.frame(\n    Panel = \"Raw libraries\",\n    DetectionLabel = core_threshold_sensitivity$DetectionLabel,\n    PrevalenceLabel = core_threshold_sensitivity$PrevalenceLabel,\n    CoreFeatures = core_threshold_sensitivity$CoreFeatures,\n    stringsAsFactors = FALSE\n  ),\n  data.frame(\n    Panel = \"10,000-read branch\",\n    DetectionLabel = fixed_depth_sensitivity$DetectionLabel,\n    PrevalenceLabel = fixed_depth_sensitivity$PrevalenceLabel,\n    CoreFeatures = fixed_depth_sensitivity$CoreFeatures,\n    stringsAsFactors = FALSE\n  )\n)\nthreshold_plot_data$DetectionLabel <- factor(\n  threshold_plot_data$DetectionLabel,\n  levels = c(detection_labels, \"One read\", \"Two reads\")\n)\nthreshold_plot_data$PrevalenceLabel <- factor(\n  threshold_plot_data$PrevalenceLabel,\n  levels = scales::percent(prevalence_thresholds, accuracy = 1)\n)\nthreshold_plot_data$Panel <- factor(\n  threshold_plot_data$Panel,\n  levels = c(\"Raw libraries\", \"10,000-read branch\")\n)\nprimary_tiles <- subset(\n  threshold_plot_data,\n  (Panel == \"Raw libraries\" &\n    DetectionLabel == \"0.01%\" & PrevalenceLabel == \"80%\") |\n    (Panel == \"10,000-read branch\" &\n      DetectionLabel == \"One read\" & PrevalenceLabel == \"80%\")\n)\nprimary_rarefied_jaccard <- jaccard(\n  global_core,\n  rarefied_one_read_core\n)\n\nthreshold_plot <- ggplot2::ggplot(\n  threshold_plot_data,\n  ggplot2::aes(\n    x = DetectionLabel,\n    y = PrevalenceLabel,\n    fill = CoreFeatures\n  )\n) +\n  ggplot2::geom_tile(colour = \"white\", linewidth = 0.7) +\n  ggplot2::geom_tile(\n    data = primary_tiles,\n    fill = NA,\n    colour = \"#D55E00\",\n    linewidth = 1.15\n  ) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = scales::comma(CoreFeatures)),\n    family = font_pub,\n    size = 3\n  ) +\n  ggplot2::facet_grid(\n    . ~ Panel,\n    scales = \"free_x\",\n    space = \"free_x\"\n  ) +\n  ggplot2::scale_fill_gradientn(\n    colours = c(\n      \"#F7FBFF\", \"#C6DBEF\", \"#6BAED6\", \"#2171B5\", \"#08306B\"\n    ),\n    trans = \"sqrt\",\n    labels = scales::label_comma()\n  ) +\n  ggplot2::labs(\n    title = \"Core size changes with detection, prevalence and sequencing depth\",\n    subtitle = \"Raw thresholds use all reads; the fixed-depth branch uses seed 20260728 and is a sensitivity analysis\",\n    x = \"Detection rule\",\n    y = \"Minimum prevalence\",\n    fill = \"Core features\",\n    caption = paste0(\n      \"Orange outlines compare the primary raw core (97) with the rarefied one-read core (167) at 80%; \",\n      \"Jaccard = \", sprintf(\"%.3f\", primary_rarefied_jaccard), \".\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  ggplot2::theme(\n    legend.position = \"bottom\",\n    panel.grid = ggplot2::element_blank(),\n    axis.text.x = ggplot2::element_text(angle = 24, hjust = 1),\n    strip.text = ggplot2::element_text(size = 9)\n  )\n\nsave_pub(\n  threshold_plot,\n  \"figures/28-threshold-depth-sensitivity\",\n  width = 170,\n  height = 112\n)\nthreshold_plot\n```\n\n::: {.cell-output-display}\n![Detection、prevalence 与固定测序深度对 core 数量的影响。](28-core-rare-biosphere_files/figure-html/fig-core-threshold-depth-sensitivity-1.png){#fig-core-threshold-depth-sensitivity}\n:::\n:::\n\n\n如果主结论只在单一阈值格子出现，Methods 应承认其脆弱性。阈值网格不要求找到一个“结果最好看”的格子，而是让读者看到结论对操作定义的依赖程度。\n\n### Rare mass：同时展示单样本分布和阈值敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_colours <- c(\n  `Inland wetland` = \"#E69F00\",\n  `Coastal wetland` = \"#0072B2\",\n  `Tibetan wetland` = \"#009E73\"\n)\nrare_plot_data <- rare_mass_all_thresholds\nrare_plot_data$ThresholdLabel <- factor(\n  rare_plot_data$ThresholdLabel,\n  levels = rare_threshold_labels\n)\nrare_plot_data$Group <- factor(\n  rare_plot_data$Group,\n  levels = unname(group_display[group_codes])\n)\nrare_group_means <- subset(\n  rare_threshold_sensitivity,\n  GroupCode %in% group_codes\n)\nrare_group_means$ThresholdLabel <- factor(\n  rare_group_means$ThresholdLabel,\n  levels = rare_threshold_labels\n)\nrare_group_means$Group <- factor(\n  rare_group_means$Group,\n  levels = unname(group_display[group_codes])\n)\n\nrare_plot <- ggplot2::ggplot(\n  rare_plot_data,\n  ggplot2::aes(\n    x = ThresholdLabel,\n    y = RareMass,\n    fill = Group,\n    colour = Group\n  )\n) +\n  ggplot2::annotate(\n    \"rect\",\n    xmin = 2.5,\n    xmax = 3.5,\n    ymin = -Inf,\n    ymax = Inf,\n    fill = \"#F0E442\",\n    alpha = 0.10\n  ) +\n  ggplot2::geom_boxplot(\n    width = 0.68,\n    outlier.shape = NA,\n    alpha = 0.35,\n    position = ggplot2::position_dodge(width = 0.78),\n    linewidth = 0.45\n  ) +\n  ggplot2::geom_point(\n    size = 0.85,\n    alpha = 0.30,\n    position = ggplot2::position_jitterdodge(\n      jitter.width = 0.11,\n      dodge.width = 0.78,\n      seed = primary_seed\n    )\n  ) +\n  ggplot2::geom_line(\n    data = rare_group_means,\n    ggplot2::aes(y = MeanRareMass, group = Group),\n    position = ggplot2::position_dodge(width = 0.78),\n    linewidth = 0.9\n  ) +\n  ggplot2::geom_point(\n    data = rare_group_means,\n    ggplot2::aes(y = MeanRareMass),\n    position = ggplot2::position_dodge(width = 0.78),\n    size = 2.2,\n    shape = 21,\n    stroke = 0.7\n  ) +\n  ggplot2::scale_fill_manual(values = group_colours, drop = FALSE) +\n  ggplot2::scale_colour_manual(values = group_colours, drop = FALSE) +\n  ggplot2::scale_y_continuous(\n    breaks = seq(0, 0.8, by = 0.2),\n    labels = scales::label_percent(accuracy = 1),\n    expand = ggplot2::expansion(mult = c(0, 0.01))\n  ) +\n  ggplot2::coord_cartesian(ylim = c(0, 0.93)) +\n  ggplot2::labs(\n    title = \"The measured rare-biosphere mass is threshold dependent\",\n    subtitle = \"Local rare mass sums features below the selected abundance threshold within each sample\",\n    x = \"Local rare-abundance threshold\",\n    y = \"Relative-abundance mass below threshold\",\n    fill = \"Wetland group\",\n    colour = \"Wetland group\",\n    caption = paste(\n      \"The highlighted 0.1% rule gives a 44.2% equal-sample mean (range 23.3–59.4%).\",\n      \"Points are samples; lines connect descriptive group means without hypothesis tests.\"\n    )\n  ) +\n  theme_pub(base_size = 8.8) +\n  ggplot2::theme(\n    legend.position = \"bottom\",\n    panel.grid.major.x = ggplot2::element_blank()\n  )\n\nsave_pub(\n  rare_plot,\n  \"figures/28-rare-biosphere-mass\",\n  width = 170,\n  height = 116\n)\nrare_plot\n```\n\n::: {.cell-output-display}\n![四个 local rare-abundance 阈值下的单样本 rare mass。](28-core-rare-biosphere_files/figure-html/fig-rare-biosphere-mass-1.png){#fig-rare-biosphere-mass}\n:::\n:::\n\n\n0.01%、0.05%、0.1%、0.5% 四个阈值的总体 rare-mass 均值依次为 10.47%、31.86%、44.15%、73.65%。因此“稀有生物圈占比”必须和阈值同句出现，不能只报告一个脱离定义的百分比。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpected_threshold_counts <- c(\n  1499L, 334L, 166L, 27L,\n  404L, 97L, 53L, 10L,\n  48L, 9L, 5L, 0L,\n  16L, 0L, 0L, 0L\n)\nstopifnot(\n  sum(global_core) == 97L,\n  abs(sum(feature_equal_mean[global_core]) - 0.170361211031733) <= 1e-12,\n  identical(unname(group_core_summary$CoreFeatures), c(166L, 160L, 278L)),\n  shared_three == 59L,\n  group_union == 425L,\n  identical(core_threshold_sensitivity$CoreFeatures, expected_threshold_counts),\n  identical(depth_sensitivity$CoreFeatures, c(334L, 97L, 167L, 52L)),\n  abs(primary_rarefied_jaccard - 0.580838323353293) <= 1e-12,\n  identical(feature_state_summary$Features, c(97L, 200L, 8407L, 1155L, 3769L)),\n  abs(mean(rare_mass_by_sample$RareMass) - 0.441501476980241) <= 1e-12\n)\n\naudit_path <- file.path(result_dir, \"validation-checks.tsv\")\nif (file.exists(audit_path)) {\n  validation_checks <- readr::read_tsv(\n    audit_path,\n    show_col_types = FALSE,\n    progress = FALSE\n  )\n  stopifnot(\n    nrow(validation_checks) == 320L,\n    all(validation_checks$status == \"PASS\")\n  )\n  data.frame(\n    Validation = \"Repository QA\",\n    Passed = sum(validation_checks$status == \"PASS\"),\n    Total = nrow(validation_checks)\n  )\n} else {\n  data.frame(\n    Validation = \"Inline reproducibility checks\",\n    Passed = 10L,\n    Total = 10L\n  )\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Validation Passed Total\n1 Repository QA    320   320\n```\n\n\n:::\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"坑 1：只写‘出现在大多数样本’\"}\n必须同时报告 feature rank、样本集合、detection threshold、prevalence threshold 和 `>`/`>=` 边界。否则另一个分析者无法重建 core 集合。\n:::\n\n::: {.callout-caution title=\"坑 2：先把所有 Unknown genus 合并，再叫它 core taxon\"}\n多个无 genus 注释的 feature 被聚合后几乎必然获得更高 occupancy。Core 应先在 ASV/OTU 层判定；taxonomy 用于解释和汇总，不应创造一个人工的高 prevalence feature。\n:::\n\n::: {.callout-caution title=\"坑 3：把 1 read 当成各样本相同的 detection limit\"}\n原始文库越深，1 read 对应的相对丰度越低。至少同时展示相对丰度阈值对应的 read 数，并用固定深度或其他 detection model 检查敏感性。\n:::\n\n::: {.callout-caution title=\"坑 4：把 rarefaction 结果当作唯一真值\"}\n稀释会丢弃 reads，而且具体矩阵依赖随机抽样。固定 seed、记录丢弃 reads，把它用于 depth sensitivity；不要用一次抽样覆盖主相对丰度结果。\n:::\n\n::: {.callout-caution title=\"坑 5：把 low reads 写成生态稀有\"}\n总 reads ≤10 且只出现于 ≤2 个样本，首先意味着证据有限，也可能涉及测序错误、污染或标签跳跃。没有技术验证时，最多标为 `Sampling-limited`。\n:::\n\n::: {.callout-caution title=\"坑 6：把横断面的 conditionally rare 写成激活\"}\n本页只能识别“全局均值低、但在部分样本达到较高相对丰度”的模式。要证明时间上的稀有→优势转换，需要同一系统的纵向重复采样和相应模型。\n:::\n\n::: {.callout-caution title=\"坑 7：把相对丰度写成绝对细胞量、活性或功能\"}\nCore 和 rare 都由相对 read composition 定义。没有绝对负荷、RNA/代谢证据或功能实验时，不能推出细胞数量、活性、稳定性或功能贡献。\n:::\n\n::: {.callout-caution title=\"坑 8：对三组做检验，却忽略设计边界\"}\n示例 metadata 中 `Group`、`Type` 与 `Saline` 结构重叠，且没有 site、block 或 subject ID。本页只做描述性集合与敏感性分析，不把组间差异写成独立环境因素效应。\n:::\n\n## 报告核心菌群与稀有类群定义的方法与限制 {#sec-methods}\n\n> Core-microbiome membership was evaluated at the unaggregated feature/OTU level from the unrarefied count table. Counts were converted to within-sample relative abundances using all reads as the denominator. A feature was considered detected when its relative abundance was greater than or equal to 0.01%, and the global core was defined as features detected in at least 80% of the 90 samples. The identical detection and prevalence rules were applied separately to each 30-sample wetland group, and global, shared, and group-specific core sets were reported separately. Sensitivity analyses crossed detection thresholds of presence, 0.01%, 0.05%, and 0.1% with prevalence thresholds of 50%, 80%, 90%, and 100%. Sequencing-depth sensitivity was assessed after rarefying every sample to 10,000 reads with seed 20260728; this branch was not used as the primary abundance estimate. Local rare-biosphere mass was defined per sample as the summed relative abundance of detected features below 0.1%, with 0.01%, 0.05%, and 0.5% retained as sensitivity thresholds. Feature-state and group-set summaries were descriptive, and no absolute-abundance, activity, functional, or group-effect inference was made.\n\n替换样本数、阈值、rarefaction depth 和分组变量即可。若你的 feature 是 ASV，应把 `feature/OTU` 改成 `ASV`；若主分析在 genus 层完成，必须说明聚合方式以及 Unknown 是否按 lineage 分开，不能沿用这里的 feature-level 描述。\n\n## 将核心菌群与稀有类群定义用于自己的研究 {#sec-own-data}\n\n### 只替换三件套路径和分组列\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"your_data/otutab.tsv\",\n  taxonomy = \"your_data/taxonomy.tsv\",\n  metadata = \"your_data/metadata.tsv\"\n)\ngroup_column <- \"Treatment\"\n```\n:::\n\n\n`otutab` 必须是 feature × sample；`taxonomy` 行名必须与 feature 完全一致；`metadata` 行名必须覆盖全部样本。技术重复应先按预声明规则恢复为生物学样本单位。\n\n### 在分析前确定核心菌的判定规则\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_feature_level <- \"ASV\"\nprimary_detection <- 0.0001\nprimary_prevalence <- 0.80\nprimary_rare_threshold <- 0.001\nprimary_denominator <- \"all reads within each sample\"\nprimary_sample_weight <- \"equal biological samples\"\nprimary_seed <- 20260728L\n```\n:::\n\n\n阈值应结合 negative controls、mock community、测序深度和研究问题预先选择。不要看完哪组 core 更多后再调整阈值。\n\n### taxonomy 只有一列字符串时，先拆成七列\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxonomy_raw <- readr::read_tsv(\n  \"your_data/taxonomy-single-column.tsv\",\n  show_col_types = FALSE\n)\nrank_names_7 <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"\n)\nparts <- strsplit(taxonomy_raw$Taxon, \";\", fixed = TRUE)\ntaxonomy_matrix <- t(vapply(parts, function(x) {\n  x <- trimws(x)\n  length(x) <- length(rank_names_7)\n  x\n}, character(length(rank_names_7))))\ntaxonomy <- as.data.frame(taxonomy_matrix, stringsAsFactors = FALSE)\nnames(taxonomy) <- rank_names_7\nrownames(taxonomy) <- taxonomy_raw$FeatureID\n```\n:::\n\n\n先在原始 feature 层完成 core 判定，再把 taxonomy 附回结果。若确实要做 genus-level core，应按完整 lineage 聚合，不能把所有空 genus 合成一个标签。\n\n### 重复测量或不平衡设计要改变 prevalence 分母\n\n纵向研究中，同一受试者的多个时间点不是相互独立的 20 个“个体”。可以先定义 subject-level occupancy，再定义 cohort-level core；也可以分时间窗计算并用混合模型分析。无论选哪种方法，都要把分母单位写成 subject、sample 还是 visit。\n\n### 报告结果时需要保留哪些信息\n\n- feature-level abundance、occupancy、taxonomy 与状态全表；\n- global core、各组 core、交集和并集成员表；\n- detection × prevalence 完整阈值网格；\n- 每个样本的 library depth 与阈值对应 read 数；\n- 固定 seed、稀释深度、丢弃 reads 和集合 Jaccard；\n- 每个样本的 local rare mass 与阈值敏感性；\n- 图形尺寸、字体、PDF/SVG/PNG/TIFF 格式审计。\n\n## 参考 {#sec-references}\n\n1. An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035).\n2. Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255).\n3. Neu AT, Allen EE, Roy K. Defining and quantifying the core microbiome: Challenges and prospects. *Proceedings of the National Academy of Sciences*. 2021;118(51):e2104429118. [doi:10.1073/pnas.2104429118](https://doi.org/10.1073/pnas.2104429118).\n4. Custer GF, Gans M, van Diepen LTA, Dini-Andreote F, Buerkle CA. Comparative analysis of core microbiome assignments: implications for ecological synthesis. *mSystems*. 2023;8(1):e01066-22. [doi:10.1128/msystems.01066-22](https://doi.org/10.1128/msystems.01066-22).\n5. Salonen A, Salojärvi J, Lahti L, de Vos WM. The adult intestinal core microbiota is determined by analysis depth and health status. *Clinical Microbiology and Infection*. 2012;18(S4):16–20. [doi:10.1111/j.1469-0691.2012.03855.x](https://doi.org/10.1111/j.1469-0691.2012.03855.x).\n6. Shade A, Jones SE, Caporaso JG, et al. Conditionally rare taxa disproportionately contribute to temporal changes in microbial diversity. *mBio*. 2014;5(4):e01371-14. [doi:10.1128/mBio.01371-14](https://doi.org/10.1128/mBio.01371-14).\n7. Sogin ML, Morrison HG, Huber JA, et al. Microbial diversity in the deep sea and the underexplored rare biosphere. *Proceedings of the National Academy of Sciences*. 2006;103(32):12115–12120. [doi:10.1073/pnas.0605127103](https://doi.org/10.1073/pnas.0605127103).\n8. Oksanen J, et al. [vegan: Community Ecology Package](https://cran.r-project.org/package=vegan).\n9. Wickham H, et al. [ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics](https://ggplot2.tidyverse.org/).\n",
    "supporting": [
      "28-core-rare-biosphere_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "9742b3b0cba32ab6928d137e32cc6fa2",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  },
  "prose_only_refreshes": [
    {
      "previous_source_hash": "4b6bb30d15cc8e8eb10be01c337f12a6",
      "fenced_code_and_outputs_unchanged": true,
      "replacement_count": 2
    }
  ]
}
