{
  "hash": "d9c7eb6c1743d73f3d4b184e10c1801f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"16S 能回答什么、回答不了什么（vs 宏基因组 / 其他组学）\"\nauthor: \"Peter\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/02-scope-and-limits.R\n  packages:\n  - ggplot2\n  - scales\n---\n\n## 先确定分辨率：16S 能测到什么？ {#sec-target}\n\n在论文中，测序方法决定了后续结论能走多远。16S rRNA 扩增子测序最适合回答：\n\n- 样本中细菌/古菌群落的相对组成如何变化；\n- α 多样性和 β 多样性是否随分组、时间或环境梯度改变；\n- 哪些 ASV/OTU 或较高分类层级与表型相关；\n- 群落差异是否与预先指定的环境或临床变量相关。\n\n它通常不能独立回答：\n\n- 某个微生物的绝对细胞数是否增加；\n- 某个菌是否存活、正在转录或正在产生某种代谢物；\n- 某个 16S 序列是否属于特定致病菌株；\n- 样本中实际携带哪些耐药、毒力或代谢基因；\n- 微生物变化是否造成了宿主结局。\n\n本篇从真实湿地 taxonomy 表生成两张目标图：\n\n\n图 @fig-taxonomy-resolution 检查当前数据能被注释到多深；图 @fig-assay-scope 用来判断研究问题是否需要增加其他测量技术。\n\n::: {.callout-important title=\"先写问题，再选技术\"}\n如果主要终点是“菌株传播”“耐药基因”“实际代谢活动”或“绝对微生物负荷”，仅做 16S 会让研究从采样开始就缺失关键测量。后期增加更复杂的统计模型，无法补回实验阶段没有测到的信息。\n:::\n\n## 下载并读取本次分析的数据 {#sec-setup}\n\n需要 R，以及 `ggplot2`、`scales`。本次使用中国湿地的 OTU count 表、分类表和样本信息表。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"data/small/metadata.tsv\",\n  \"data/small/otutab.tsv\",\n  \"data/small/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nset.seed(20260718)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(color = \"black\", linewidth = 0.3),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 120,\n  height = 95,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n### 从三件套读取并核对 ID\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"data/small/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"data/small/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(otutab >= 0),\n  all(colSums(otutab) > 0)\n)\n\ndim(otutab)\notutab[1:5, 1:5]\ntaxonomy[1:5, , drop = FALSE]\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\n                         Class               Order               Family Genus\nOTU_4272            c__Bacilli       o__Bacillales                  f__   g__\nOTU_236                    c__                 o__                  f__   g__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae   g__\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__   g__\nOTU_32                     c__                 o__                  f__   g__\n         Species\nOTU_4272     s__\nOTU_236      s__\nOTU_399      s__\nOTU_1556     s__\nOTU_32       s__\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/6c3ebab44401839f38b8d9356cb2f338ecfc9a3f/examples/02-scope-and-limits.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"ggplot2\", \"scales\", \"digest\"))\n```\n:::\n\n\n</details>\n\n## 16S 实际测到了什么 {#sec-theory}\n\n### 从生物样本到 reads，中间有多层选择\n\n16S 结果不是样本中微生物的无偏普查。观测链条依次包含：\n\n1. 样本采集与保存；\n2. 细胞裂解与 DNA 提取；\n3. 引物与目标可变区；\n4. PCR 扩增；\n5. 建库与测序；\n6. 质量过滤、去嵌合体与 ASV/OTU 推断；\n7. 参考数据库与分类器。\n\n任一环节都可能使不同类群的检出概率不同。16S rRNA 基因在不同基因组中的拷贝数也不同，同一基因组内的多个拷贝还可能存在序列差异。因此，ASV 数不等于物种数，reads 比例也不等于细胞比例。[Větrovský 与 Baldrian](https://doi.org/10.1371/journal.pone.0057923)讨论了 16S 基因拷贝和基因组内变异对群落分析的影响。\n\n### 短扩增区通常不能稳定解析菌株\n\n常规 Illumina 16S 只覆盖一个或数个可变区。不同物种可能在目标区域拥有相同序列，同一物种的不同菌株也可能共享完全相同的 16S 序列。[Johnson 等](https://doi.org/10.1038/s41467-019-13036-1)表明，短读长可变区的物种/菌株分辨率低于全长 16S；全长 16S 能改善部分分类群的物种分辨率，但仍不能把“全长序列不同”普遍等同于“菌株不同”。\n\n因此：\n\n- 属水平标签通常比种水平更稳妥，但仍依赖参考库、目标区域和分类阈值；\n- 一个 ASV 可以对应多个物种；\n- 同一个物种也可能产生多个 ASV；\n- “检出某属”不能自动推出“检出该属中的致病种或致病株”。\n\n### DNA 潜力、转录活动和代谢产物是不同层次\n\nshotgun 宏基因组直接测量样本 DNA 片段，可以分析基因家族、通路潜力，并在覆盖度足够时进行物种或菌株分析，但仍主要反映“基因存在的潜力”。宏转录组测量 RNA，更接近表达活动；代谢组测量小分子，是宿主、微生物、饮食和环境共同作用后的结果。[Quince 等](https://doi.org/10.1038/nbt.3935)综述了 shotgun 从采样到分析的能力与限制。\n\nPICRUSt2 等工具可根据 16S 序列在参考系统发育中的位置预测基因家族与通路。[PICRUSt2 原始论文](https://doi.org/10.1038/s41587-020-0548-6)明确将其定位为 metagenome function prediction。预测结果不是实测基因，更不是表达量或代谢通量；参考基因组稀疏的环境样本尤其需要谨慎。\n\n### 分类变化不等于功能变化，功能相似也不等于机制相同\n\n不同分类群可能携带相似功能，同一分类群内部也可能存在显著功能差异。[Louca 等](https://doi.org/10.1038/s41559-018-0519-1)总结了微生物系统中的功能冗余。因此：\n\n- 分类组成显著变化时，功能潜力未必同步变化；\n- 预测通路显著变化时，不能证明该通路正在表达；\n- 代谢物变化时，不能仅凭相关性把来源归给某个菌；\n- 要建立机制，需要时间顺序、干预、培养或多组学证据。\n\n<details>\n<summary><strong>深入：五类技术怎么选</strong></summary>\n\n| 技术 | 主要测量 | 优势 | 关键限制 |\n|---|---|---|---|\n| 16S/ITS/18S 扩增子 | 标记基因片段 | 成本低、适合大队列、群落比较成熟 | PCR/引物偏倚、相对组成、功能和菌株有限 |\n| Shotgun 宏基因组 | 群落总 DNA | 物种/菌株和基因潜力更强，可覆盖病毒与真菌 | 成本与计算量高，宿主 DNA、低丰度覆盖不足 |\n| 宏转录组 | 群落 RNA | 更接近正在表达的功能 | RNA 易降解、rRNA 占比高、仍受组成和注释影响 |\n| 代谢组 | 小分子 | 接近实际化学表型 | 来源不唯一、注释率有限、宿主与饮食混杂 |\n| qPCR/ddPCR/流式/spike-in | 靶标或总负荷 | 提供绝对数量参照 | 通常只覆盖预先选择的靶标或总量 |\n\n多组学不是“同一样本多测几张表”就自动得到机制。真正的整合需要匹配的样本/时间、明确的主要假设、独立验证和与每种测量误差相符的统计模型。iHMP 展示了纵向、多组学和宿主信息联合设计的范式，而不是简单把多个矩阵拼接。[iHMP 项目论文](https://doi.org/10.1038/s41586-019-1238-8)\n\n</details>\n\n## 检查分类标签，确定16S的解释范围 {#sec-code}\n\n### 统一 taxonomy 空值规则\n\n示例表使用 `k__`、`p__`、`g__` 等前缀，未注释条目可能是空字符串或 `Unassigned`。先去掉层级前缀，再统一判定空值。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_order <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\",\n  \"Family\", \"Genus\", \"Species\"\n)\nstopifnot(all(rank_order %in% colnames(taxonomy)))\n\nclean_taxon <- function(x) {\n  x <- trimws(as.character(x))\n  x <- sub(\"^[A-Za-z]__\", \"\", x)\n  x\n}\n\nis_assigned <- function(x) {\n  !is.na(x) &\n    nzchar(x) &\n    !grepl(\n      \"^(unassigned|unclassified|uncultured|unknown|norank|NA)$\",\n      x,\n      ignore.case = TRUE\n    )\n}\n\ntaxonomy_clean <- taxonomy\ntaxonomy_clean[rank_order] <- lapply(\n  taxonomy_clean[rank_order],\n  clean_taxon\n)\n```\n:::\n\n\n### 计算每个分类层级的注释覆盖\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_summary <- do.call(\n  rbind,\n  lapply(rank_order, function(rank_name) {\n    values <- taxonomy_clean[[rank_name]]\n    assigned <- is_assigned(values)\n    data.frame(\n      Rank = rank_name,\n      AssignedFeatures = sum(assigned),\n      TotalFeatures = length(values),\n      AssignedPercent = 100 * mean(assigned),\n      DistinctLabels = length(unique(values[assigned])),\n      stringsAsFactors = FALSE\n    )\n  })\n)\n\nrank_summary$Rank <- factor(\n  rank_summary$Rank,\n  levels = rev(rank_order)\n)\n\nrank_summary\nstopifnot(\n  all(rank_summary$AssignedFeatures <= rank_summary$TotalFeatures),\n  all(diff(rank_summary$AssignedPercent) <= 1e-10)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Rank AssignedFeatures TotalFeatures AssignedPercent DistinctLabels\n1 Kingdom            13330         13628      97.8133255              2\n2  Phylum            13319         13628      97.7326093             55\n3   Class            12378         13628      90.8277077            127\n4   Order            10878         13628      79.8209569            216\n5  Family             8285         13628      60.7939536            393\n6   Genus             4176         13628      30.6427942            771\n7 Species               50         13628       0.3668917             42\n```\n\n\n:::\n:::\n\n\n本数据共有 13,628 个特征。属水平有明确非空标签的特征为 4,176 个（30.6%），种水平为 50 个（0.4%）。\n\n这些数字表示“分类器返回了非空标签”，不等于标签一定正确。分类准确度还取决于扩增区、序列质量、参考库覆盖、训练方式和置信阈值。\n\n### 建立测量范围矩阵\n\n以下矩阵是实验设计决策工具。`Direct` 表示该技术直接测量该层信息，`Partial / inferred` 表示覆盖有限或需要模型推断，`Not measured` 表示该技术本身没有测量该信息。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquestions <- c(\n  \"Community\\nstructure\",\n  \"Species /\\nstrain\",\n  \"Gene\\npotential\",\n  \"Gene\\nactivity\",\n  \"Metabolites\",\n  \"Absolute\\nload\"\n)\n\nscope_row <- function(assay, status, label) {\n  stopifnot(\n    length(status) == length(questions),\n    length(label) == length(questions)\n  )\n  data.frame(\n    Assay = assay,\n    Question = questions,\n    Status = status,\n    Label = label,\n    stringsAsFactors = FALSE\n  )\n}\n\nscope_matrix <- do.call(\n  rbind,\n  list(\n    scope_row(\n      \"16S amplicon\",\n      c(\n        \"Direct\", \"Partial / inferred\", \"Partial / inferred\",\n        \"Not measured\", \"Not measured\", \"Not measured\"\n      ),\n      c(\"Direct\", \"Limited\", \"Predicted\", \"No\", \"No\", \"No\")\n    ),\n    scope_row(\n      \"Shotgun metagenome\",\n      c(\n        \"Direct\", \"Direct\", \"Direct\",\n        \"Not measured\", \"Not measured\", \"Partial / inferred\"\n      ),\n      c(\"Direct\", \"Strong\", \"Direct\", \"No\", \"No\", \"Relative\")\n    ),\n    scope_row(\n      \"Metatranscriptome\",\n      c(\n        \"Partial / inferred\", \"Partial / inferred\", \"Partial / inferred\",\n        \"Direct\", \"Not measured\", \"Partial / inferred\"\n      ),\n      c(\"Biased\", \"Partial\", \"Expressed\", \"Direct\", \"No\", \"Relative\")\n    ),\n    scope_row(\n      \"Metabolome\",\n      c(\n        \"Not measured\", \"Not measured\", \"Not measured\",\n        \"Partial / inferred\", \"Direct\", \"Partial / inferred\"\n      ),\n      c(\"No\", \"No\", \"No\", \"Downstream\", \"Direct\", \"Relative\")\n    ),\n    scope_row(\n      \"Absolute reference\\n(qPCR / flow / spike-in)\",\n      c(\n        \"Partial / inferred\", \"Partial / inferred\", \"Not measured\",\n        \"Not measured\", \"Not measured\", \"Direct\"\n      ),\n      c(\"Targeted\", \"Targeted\", \"No\", \"No\", \"No\", \"Direct\")\n    )\n  )\n)\n\nscope_matrix$Question <- factor(\n  scope_matrix$Question,\n  levels = questions\n)\nscope_matrix$Assay <- factor(\n  scope_matrix$Assay,\n  levels = rev(unique(scope_matrix$Assay))\n)\nscope_matrix$Status <- factor(\n  scope_matrix$Status,\n  levels = c(\"Direct\", \"Partial / inferred\", \"Not measured\")\n)\n\nscope_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                          Assay             Question\n1                                  16S amplicon Community\\nstructure\n2                                  16S amplicon    Species /\\nstrain\n3                                  16S amplicon      Gene\\npotential\n4                                  16S amplicon       Gene\\nactivity\n5                                  16S amplicon          Metabolites\n6                                  16S amplicon       Absolute\\nload\n7                            Shotgun metagenome Community\\nstructure\n8                            Shotgun metagenome    Species /\\nstrain\n9                            Shotgun metagenome      Gene\\npotential\n10                           Shotgun metagenome       Gene\\nactivity\n11                           Shotgun metagenome          Metabolites\n12                           Shotgun metagenome       Absolute\\nload\n13                            Metatranscriptome Community\\nstructure\n14                            Metatranscriptome    Species /\\nstrain\n15                            Metatranscriptome      Gene\\npotential\n16                            Metatranscriptome       Gene\\nactivity\n17                            Metatranscriptome          Metabolites\n18                            Metatranscriptome       Absolute\\nload\n19                                   Metabolome Community\\nstructure\n20                                   Metabolome    Species /\\nstrain\n21                                   Metabolome      Gene\\npotential\n22                                   Metabolome       Gene\\nactivity\n23                                   Metabolome          Metabolites\n24                                   Metabolome       Absolute\\nload\n25 Absolute reference\\n(qPCR / flow / spike-in) Community\\nstructure\n26 Absolute reference\\n(qPCR / flow / spike-in)    Species /\\nstrain\n27 Absolute reference\\n(qPCR / flow / spike-in)      Gene\\npotential\n28 Absolute reference\\n(qPCR / flow / spike-in)       Gene\\nactivity\n29 Absolute reference\\n(qPCR / flow / spike-in)          Metabolites\n30 Absolute reference\\n(qPCR / flow / spike-in)       Absolute\\nload\n               Status      Label\n1              Direct     Direct\n2  Partial / inferred    Limited\n3  Partial / inferred  Predicted\n4        Not measured         No\n5        Not measured         No\n6        Not measured         No\n7              Direct     Direct\n8              Direct     Strong\n9              Direct     Direct\n10       Not measured         No\n11       Not measured         No\n12 Partial / inferred   Relative\n13 Partial / inferred     Biased\n14 Partial / inferred    Partial\n15 Partial / inferred  Expressed\n16             Direct     Direct\n17       Not measured         No\n18 Partial / inferred   Relative\n19       Not measured         No\n20       Not measured         No\n21       Not measured         No\n22 Partial / inferred Downstream\n23             Direct     Direct\n24 Partial / inferred   Relative\n25 Partial / inferred   Targeted\n26 Partial / inferred   Targeted\n27       Not measured         No\n28       Not measured         No\n29       Not measured         No\n30             Direct     Direct\n```\n\n\n:::\n:::\n\n\n## 注释覆盖率与测量范围怎样呈现在图中 {#sec-polish}\n\n### 真实 taxonomy 解析深度\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_palette <- c(\n  Kingdom = \"#1B4965\",\n  Phylum = \"#245F73\",\n  Class = \"#2C7DA0\",\n  Order = \"#3A8D9F\",\n  Family = \"#2A9D8F\",\n  Genus = \"#B56576\",\n  Species = \"#7A1F3D\"\n)\n\nrank_summary$Label <- sprintf(\n  \"%.1f%% · n=%s · %s labels\",\n  rank_summary$AssignedPercent,\n  format(rank_summary$AssignedFeatures, big.mark = \",\"),\n  format(rank_summary$DistinctLabels, big.mark = \",\")\n)\n\np_taxonomy_resolution <- ggplot(\n  rank_summary,\n  aes(Rank, AssignedPercent, fill = Rank)\n) +\n  geom_col(width = 0.72) +\n  geom_text(\n    data = subset(rank_summary, AssignedPercent >= 50),\n    aes(y = AssignedPercent - 2, label = Label),\n    hjust = 1,\n    size = 3.0,\n    color = \"white\"\n  ) +\n  geom_text(\n    data = subset(rank_summary, AssignedPercent < 50),\n    aes(y = AssignedPercent + 2, label = Label),\n    hjust = 0,\n    size = 3.0,\n    color = \"grey15\"\n  ) +\n  scale_fill_manual(values = rank_palette, guide = \"none\") +\n  scale_y_continuous(\n    limits = c(0, 112),\n    breaks = c(0, 25, 50, 75, 100),\n    labels = function(x) paste0(x, \"%\"),\n    expand = expansion(mult = c(0, 0))\n  ) +\n  coord_flip(clip = \"off\") +\n  labs(\n    title = \"Taxonomic annotation depth in a real 16S dataset\",\n    subtitle = paste0(\n      format(nrow(taxonomy), big.mark = \",\"),\n      \" features · empty and placeholder labels excluded\"\n    ),\n    x = NULL,\n    y = \"Features with a non-empty taxonomic label\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(color = \"grey35\", size = 9.5),\n    axis.text.y = element_text(face = \"bold\"),\n    plot.margin = margin(8, 12, 8, 8)\n  )\n\np_taxonomy_resolution\n```\n\n```{.r .cell-code}\nsave_pub(\n  p_taxonomy_resolution,\n  \"figures/02-taxonomy-resolution\",\n  width = 165,\n  height = 105\n)\n```\n:::\n\n\n![真实 16S 数据在不同分类层级的非空注释比例。](../figures/02-taxonomy-resolution.png){#fig-taxonomy-resolution}\n\n### 技术选择范围图\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscope_colors <- c(\n  \"Direct\" = \"#009E73\",\n  \"Partial / inferred\" = \"#E69F00\",\n  \"Not measured\" = \"#D9D9D9\"\n)\n\np_assay_scope <- ggplot(\n  scope_matrix,\n  aes(Question, Assay, fill = Status)\n) +\n  geom_tile(color = \"white\", linewidth = 1.1) +\n  geom_text(\n    aes(label = Label),\n    size = 3.0,\n    color = \"grey10\",\n    lineheight = 0.9\n  ) +\n  scale_fill_manual(\n    values = scope_colors,\n    drop = FALSE,\n    name = \"Measurement\"\n  ) +\n  labs(\n    title = \"What each microbiome assay can measure\",\n    subtitle = \"Direct measurement does not imply freedom from bias or confounding\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal(base_size = 11, base_family = \"sans\") +\n  theme(\n    panel.grid = element_blank(),\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(color = \"grey35\", size = 9.5),\n    axis.text.x = element_text(\n      color = \"black\",\n      face = \"bold\",\n      lineheight = 0.9\n    ),\n    axis.text.y = element_text(\n      color = \"black\",\n      face = \"bold\",\n      lineheight = 0.9\n    ),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\")\n  ) +\n  guides(fill = guide_legend(nrow = 1, byrow = TRUE))\n\np_assay_scope\n```\n\n```{.r .cell-code}\nsave_pub(\n  p_assay_scope,\n  \"figures/02-assay-scope-map\",\n  width = 180,\n  height = 105\n)\n```\n:::\n\n\n![不同测量技术对六类科学问题的直接、部分或不可测范围。](../figures/02-assay-scope-map.png){#fig-assay-scope}\n\n两张图均导出为 PDF、PNG 和 300 dpi LZW-TIFF。图内标签全部使用英文；正文保留中文解释。\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最容易指出的八种越界解释\"}\n1. **把 ASV 数写成物种数。** 一个基因组可能贡献多个 16S 拷贝或 ASV，多个物种也可能共享目标序列。\n2. **taxonomy 有种名就按种解释。** 非空标签不等于有足够分辨率；必须结合扩增区、分类置信度和参考序列唯一性。\n3. **把相对丰度写成绝对增殖。** 没有外部负荷参照时，只能解释组成变化。\n4. **用 DNA 判断活菌或活性。** DNA 可来自休眠、死亡或胞外残留；RNA、培养和代谢测量回答不同问题。\n5. **把 PICRUSt2 通路写成实测功能。** 应始终使用 predicted/inferred functional potential，并报告参考距离或预测质量。\n6. **认为 shotgun 自动解决所有问题。** shotgun 仍有提取偏倚、宿主污染、深度不足、数据库缺口和组成性。\n7. **把代谢物来源唯一归因于某个菌。** 同一代谢物可由宿主、饮食或多个微生物产生，也可能被其他成员消耗。\n8. **用横断面多组学相关宣称机制。** 同时测量不提供时间顺序；机制需要纵向、扰动和实验验证。\n:::\n\n::: {.callout-warning title=\"本例 0.4% 的 species 标签不是普遍定律\"}\n当前比例由这套湿地数据、目标扩增区、`microeco 2.0.0` 分发的 taxonomy 和当时采用的参考数据库共同决定。其他数据可能更高或更低。真正可迁移的做法是对自己的 taxonomy 表运行同样的覆盖审计，并把结果写进报告。\n:::\n\n## 报告16S测量边界的方法与限制 {#sec-methods}\n\n适用于论文中说明测量边界的英文模板：\n\n> Bacterial and archaeal community structure was profiled by 16S rRNA gene amplicon sequencing. Amplicon count, taxonomic annotation and sample-metadata tables were matched by feature and sample identifiers before analysis. Taxonomic labels were considered assigned only when they were non-empty and did not contain placeholder terms such as “unassigned” or “unclassified”. Among 13,628 features, 30.6% and 0.4% received non-placeholder genus- and species-level labels, respectively. Analyses were therefore interpreted primarily at the ASV/OTU and higher taxonomic levels. Amplicon read counts were treated as compositional measurements and were not interpreted as absolute microbial loads. Predicted functional profiles, where used, were described as inferred genomic potential rather than directly measured genes, transcripts or metabolic activity.\n\n真实论文还必须写明扩增区、引物序列、平台、读长、DADA2/OTU 参数、数据库名称与版本、分类器和置信阈值。\n\n## 将16S测量边界用于自己的研究 {#sec-own-data}\n\n替换三件套路径后，直接运行本篇的 taxonomy 清理与 `rank_summary` 代码：\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"your_project/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"your_project/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"your_project/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata))\n)\n```\n:::\n\n\n根据主要问题选择技术：\n\n- **群落组成、大队列分层、基础生态比较：**16S 通常足够；\n- **物种/菌株、耐药基因、毒力基因、代谢基因：**优先 shotgun，必要时培养分离和 isolate WGS；\n- **正在表达什么：**宏转录组/宏蛋白组；\n- **实际化学产物：**代谢组，并结合标准品和来源验证；\n- **绝对数量：**qPCR/ddPCR、流式、spike-in 或定量宏基因组；\n- **传播证据：**菌株级 SNV/单倍型和时间、接触信息，属水平相似远远不够；\n- **机制或因果：**纵向、扰动、培养、动物或临床干预与多层验证。\n\n若预算有限，可以先用 16S 覆盖大队列，再对预先定义的代表性样本做 shotgun 或多组学；子集选择规则必须在看主要结果前确定，避免只挑“最显著”的样本。\n\n## 参考 {#sec-references}\n\n- Knight R, Vrbanac A, Taylor BC, et al. Best practices for analysing microbiomes. *Nature Reviews Microbiology*. 2018;16:410–422. [doi:10.1038/s41579-018-0029-9](https://doi.org/10.1038/s41579-018-0029-9)\n- Johnson JS, Spakowicz DJ, Hong B-Y, et al. Evaluation of 16S rRNA gene sequencing for species and strain-level microbiome analysis. *Nature Communications*. 2019;10:5029. [doi:10.1038/s41467-019-13036-1](https://doi.org/10.1038/s41467-019-13036-1)\n- Větrovský T, Baldrian P. The variability of the 16S rRNA gene in bacterial genomes and its consequences for bacterial community analyses. *PLOS ONE*. 2013;8:e57923. [doi:10.1371/journal.pone.0057923](https://doi.org/10.1371/journal.pone.0057923)\n- Quince C, Walker AW, Simpson JT, Loman NJ, Segata N. Shotgun metagenomics, from sampling to analysis. *Nature Biotechnology*. 2017;35:833–844. [doi:10.1038/nbt.3935](https://doi.org/10.1038/nbt.3935)\n- Douglas GM, Maffei VJ, Zaneveld JR, et al. PICRUSt2 for prediction of metagenome functions. *Nature Biotechnology*. 2020;38:685–688. [doi:10.1038/s41587-020-0548-6](https://doi.org/10.1038/s41587-020-0548-6)\n- Louca S, Polz MF, Mazel F, et al. Function and functional redundancy in microbial systems. *Nature Ecology & Evolution*. 2018;2:936–943. [doi:10.1038/s41559-018-0519-1](https://doi.org/10.1038/s41559-018-0519-1)\n- The Integrative HMP Research Network Consortium. The Integrative Human Microbiome Project. *Nature*. 2019;569:641–648. [doi:10.1038/s41586-019-1238-8](https://doi.org/10.1038/s41586-019-1238-8)\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n",
    "supporting": [
      "02-scope-and-limits_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "3f3db0a9637155d9c2b0cbd570d88643",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  }
}
