{
  "hash": "73565dfd90a533696189390247d0fbd6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"约束排序：CAP/db-RDA/RDA/CCA（复现）\"\nauthor: \"Peter\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/24-ordination-constrained-cap.R\n  packages:\n  - ggplot2\n  - ggrepel\n  - scales\n  - vegan\n---\n\n## 约束排序回答环境解释了多少群落差异 {#sec-target}\n\n环境微生物组论文经常出现一张带箭头的二维排序图：\n\n- 每个点是一个样本；\n- 点的颜色表示地点、处理或表型；\n- `pH`、`Conductivity`、`TOC` 等箭头表示环境梯度；\n- 图注报告约束模型的 \\(R^2\\)、调整后 \\(R^2\\) 和置换检验 P 值。\n\n这类图回答的不是“样本自然会沿哪两个方向变化”，而是：\n\n> 预先指定的环境变量能解释多少群落组成差异？这种关联是否强于随机置换下的结果？\n\n本例继续使用中国湿地土壤 16S 数据。[原始研究](https://doi.org/10.1016/j.geoderma.2018.09.035)报告 pH 与电导率是影响湿地土壤细菌群落的重要环境因子；[`microeco`](https://doi.org/10.1093/femsec/fiaa255)公开分发了 OTU、分类、样本和环境因子表。下面从这些表拟合一个五变量 CAP 模型。\n\n::: {.callout-important title=\"约束排序不是把差异“逼出来”\"}\nCAP 是有监督模型：坐标轴专门呈现可由给定变量解释的变异。因此分离更明显是模型定义的结果，不是独立证据。证据来自预先设定的假设、调整后 \\(R^2\\)、置换检验、共线性检查和与研究设计一致的置换方案。\n:::\n\n## 下载并读取本次分析的数据 {#sec-setup}\n\n需要 R，以及 `ggplot2`、`ggrepel`、`scales`、`vegan`。本次使用中国湿地的 OTU count 表、分类表和样本信息表，以及本次分析使用的实测环境变量或系统发育信息。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"data/small/environment.tsv\",\n  \"data/small/metadata.tsv\",\n  \"data/small/otutab.tsv\",\n  \"data/small/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vegan)\nlibrary(ggplot2)\n\nset.seed(20260718)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(color = \"black\", linewidth = 0.3),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 125,\n  height = 100,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n### 读取四张表并按 ID 对齐\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"data/small/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"data/small/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nenvironment <- read.delim(\n  \"data/small/environment.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(colnames(otutab) %in% rownames(environment)),\n  all(otutab >= 0),\n  all(colSums(otutab) > 0)\n)\n\nenvironment <- environment[colnames(otutab), , drop = FALSE]\n\ndim(otutab)\notutab[1:5, 1:5]\ntaxonomy[1:5, , drop = FALSE]\nhead(metadata)\nhead(environment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\n                         Class               Order               Family Genus\nOTU_4272            c__Bacilli       o__Bacillales                  f__   g__\nOTU_236                    c__                 o__                  f__   g__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae   g__\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__   g__\nOTU_32                     c__                 o__                  f__   g__\n         Species\nOTU_4272     s__\nOTU_236      s__\nOTU_399      s__\nOTU_1556     s__\nOTU_32       s__\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n   Latitude Longitude Altitude Temperature Precipitation   TOC      NH4  NO3\nS1 52.96482  122.5635      432        -4.2           445 10.02 18.95966 1.93\nS2 52.94877  122.6109      445        -4.3           449  6.94 21.05730 1.46\nS3 52.94932  122.6099      430        -4.3           449  8.38 14.31937 2.38\nS4 52.94900  122.6104      430        -4.3           449  8.17 20.89645 1.38\nS5 52.95292  122.6057      429        -4.3           449  8.41  9.65465 0.77\nS6 52.95300  122.6123      429        -4.3           449  8.13 15.94577 1.31\n     pH Conductivity   TN\nS1 5.10        108.7 0.28\nS2 6.53         31.2 0.22\nS3 5.13         68.2 0.26\nS4 5.81         64.4 0.25\nS5 5.50         33.5 0.24\nS6 5.37         33.3 0.26\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/691722146e287afe063bd43e9ce4fa41977fe763/examples/24-ordination-constrained-cap.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"vegan\", \"ggplot2\", \"ggrepel\", \"scales\", \"digest\"))\n```\n:::\n\n\n</details>\n\n## CAP 到底约束了什么 {#sec-theory}\n\n群落总变异可分为两部分：\n\n\\[\n\\text{Total variation}\n=\n\\text{Constrained variation}\n+\n\\text{Residual variation}\n\\]\n\n约束部分是当前预测变量能够解释的群落变异，残差部分是模型没有解释的变异。原始 \\(R^2\\) 随变量数量增加而单调上升，因此多变量模型应同时报告调整后 \\(R^2\\)。\n\n### RDA、CCA 与 CAP/db-RDA 的选择\n\n- **RDA（redundancy analysis）**：本质上是多响应线性回归后做 PCA，适合 Hellinger 或 CLR 等近欧氏表示。\n- **CCA（canonical correspondence analysis）**：基于卡方距离和单峰响应假设，常用于沿长环境梯度的经典群落生态数据。\n- **db-RDA（distance-based RDA）/ CAP**：先用距离表示群落差异，再用预测变量约束排序，可结合 Bray–Curtis 等非欧氏距离。\n\n`vegan::capscale()` 和 `vegan::dbrda()` 都可拟合基于距离的约束模型。这里用 `capscale(..., distance = \"bray\", add = \"lingoes\")`，显式处理 Bray–Curtis 可能产生的负特征值。\n\n<details>\n<summary><strong>深入：箭头、样本点和分组颜色分别代表什么</strong></summary>\n\n连续变量的箭头方向表示该变量增加的方向，箭头长度反映它与当前二维排序空间的关联强度。两个箭头夹角较小通常表示正相关，方向相反通常表示负相关，接近直角表示当前二维投影中的相关较弱。\n\n这些解释有三项限制：\n\n1. 箭头是多维模型在二维平面的投影，短箭头可能只是信息落在更高轴；\n2. 箭头表示关联，不证明因果；\n3. 图上用颜色标出的 `Group` 可以只用于展示。若 `Group` 没进入公式，它不是该模型的约束变量。\n\n因子变量进入公式后通常显示为水平质心；连续变量显示为 biplot arrows。不要把两者都解释成连续梯度。\n\n</details>\n\n::: {.callout-note title=\"为什么同时做顺序检验和边际检验\"}\n`anova(model, by = \"terms\")` 按公式顺序逐项加入变量，结果依赖变量排列；`by = \"margin\"` 检验每个变量在控制其余变量后的边际贡献。本例两者都运行：前者复现预先指定的建模顺序，后者用于判断独立贡献。\n:::\n\n## 检验预先指定变量与群落结构的关系 {#sec-code}\n\n### 构建用于 Bray–Curtis 的群落矩阵\n\n与非约束排序一致，保留至少在 5% 样本中检出的特征，并转换为样本内相对丰度。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin_prevalence <- 0.05\nmin_samples <- ceiling(min_prevalence * ncol(otutab))\nkeep_feature <- rowSums(otutab > 0) >= min_samples\n\ncomm <- t(otutab[keep_feature, , drop = FALSE])\ncomm_rel <- sweep(comm, 1, rowSums(comm), \"/\")\nmetadata <- metadata[rownames(comm_rel), , drop = FALSE]\nenvironment <- environment[rownames(comm_rel), , drop = FALSE]\n\ngroup_labels <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan Plateau\"\n)\nmetadata$Group <- factor(\n  unname(group_labels[metadata$Group]),\n  levels = unname(group_labels)\n)\n\nstopifnot(\n  all(abs(rowSums(comm_rel) - 1) < 1e-10),\n  identical(rownames(comm_rel), rownames(metadata)),\n  identical(rownames(comm_rel), rownames(environment)),\n  !anyNA(metadata$Group)\n)\n\nc(\n  samples = nrow(comm_rel),\n  retained_features = ncol(comm_rel),\n  original_features = nrow(otutab)\n)\ntable(metadata$Group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          samples retained_features original_features \n               90             11113             13628 \n\n Inland wetland Coastal wetland Tibetan Plateau \n             30              30              30 \n```\n\n\n:::\n:::\n\n\n### 先看一个单因子 CAP 模型\n\n这个模型把湿地地理组作为约束变量。图上分开是预期结果，模型显著性仍由置换检验决定。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_group <- vegan::capscale(\n  comm_rel ~ Group,\n  data = metadata,\n  distance = \"bray\",\n  add = \"lingoes\"\n)\n\nset.seed(20260718)\ncap_group_test <- anova(\n  cap_group,\n  permutations = 999\n)\ncap_group_r2 <- vegan::RsquareAdj(cap_group)\n\ncap_group_test\ncap_group_r2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: vegan::capscale(formula = comm_rel ~ Group, data = metadata, distance = \"bray\", add = \"lingoes\")\n         Df SumOfSqs      F Pr(>F)    \nModel     2   6.3195 11.935  0.001 ***\nResidual 87  23.0329                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n$r.squared\n[1] 0.2152982\n\n$adj.r.squared\n[1] 0.1972591\n```\n\n\n:::\n:::\n\n\n### 预先确定环境变量并处理缺失值\n\n本例选择 `pH`、`TOC`、`NH4`、`NO3` 和 `Conductivity`。其中 pH 与电导率来自原研究的主要环境结论，其余三项代表碳、铵态氮和硝态氮。变量在建模前做 Z-score 标准化，使量纲可比。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictors <- c(\n  \"pH\",\n  \"TOC\",\n  \"NH4\",\n  \"NO3\",\n  \"Conductivity\"\n)\nstopifnot(all(predictors %in% colnames(environment)))\n\ncomplete_samples <- complete.cases(environment[, predictors, drop = FALSE])\ncomm_env <- comm_rel[complete_samples, , drop = FALSE]\nmetadata_env <- metadata[complete_samples, , drop = FALSE]\nenvironment_env <- environment[\n  complete_samples,\n  predictors,\n  drop = FALSE\n]\n\nmodel_data <- as.data.frame(scale(environment_env))\nstopifnot(\n  identical(rownames(comm_env), rownames(model_data)),\n  all(vapply(model_data, is.numeric, logical(1)))\n)\n\nsummary(model_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       pH               TOC               NH4               NO3         \n Min.   :-2.1025   Min.   :-0.5705   Min.   :-1.0391   Min.   :-0.7371  \n 1st Qu.:-0.4813   1st Qu.:-0.4643   1st Qu.:-0.6486   1st Qu.:-0.7371  \n Median : 0.1735   Median :-0.3179   Median :-0.2648   Median :-0.3944  \n Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000  \n 3rd Qu.: 0.6869   3rd Qu.: 0.0447   3rd Qu.: 0.2454   3rd Qu.: 0.1988  \n Max.   : 2.1400   Max.   : 4.6740   Max.   : 5.7514   Max.   : 4.6714  \n  Conductivity    \n Min.   :-0.5997  \n 1st Qu.:-0.5547  \n Median :-0.4712  \n Mean   : 0.0000  \n 3rd Qu.: 0.3694  \n Max.   : 5.8675  \n```\n\n\n:::\n:::\n\n\n### 拟合环境 CAP，并检查 \\(R^2\\) 与共线性\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_env <- vegan::capscale(\n  comm_env ~ pH + TOC + NH4 + NO3 + Conductivity,\n  data = model_data,\n  distance = \"bray\",\n  add = \"lingoes\"\n)\n\ncap_env_r2 <- vegan::RsquareAdj(cap_env)\ncap_env_vif <- vegan::vif.cca(cap_env)\n\ncap_env_r2\ncap_env_vif\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$r.squared\n[1] 0.2286814\n\n$adj.r.squared\n[1] 0.1827695\n\n          pH          TOC          NH4          NO3 Conductivity \n    1.456621     1.626594     1.053479     1.246362     1.043803 \n```\n\n\n:::\n:::\n\n\n本例所有 VIF 均低于 2，没有明显多重共线性。VIF 很高时，应依据科学问题删除或合并变量，不能为了获得更漂亮的箭头保留冗余预测因子。\n\n### 整体、逐项、边际和逐轴置换检验\n\n每次随机置换前都固定种子。`by = \"terms\"` 是顺序检验，`by = \"margin\"` 是控制其他变量后的边际检验。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260718)\ncap_env_overall <- anova(\n  cap_env,\n  permutations = 999\n)\n\nset.seed(20260718)\ncap_env_terms <- anova(\n  cap_env,\n  by = \"terms\",\n  permutations = 999\n)\n\nset.seed(20260718)\ncap_env_margin <- anova(\n  cap_env,\n  by = \"margin\",\n  permutations = 999\n)\n\nset.seed(20260718)\ncap_env_axes <- anova(\n  cap_env,\n  by = \"axis\",\n  permutations = 999\n)\n\ncap_env_overall\ncap_env_terms\ncap_env_margin\ncap_env_axes\n\ncap_env_p <- unname(cap_env_overall$`Pr(>F)`[1])\ncap_env_r2_raw <- unname(cap_env_r2$r.squared)\ncap_env_r2_adjusted <- unname(cap_env_r2$adj.r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: vegan::capscale(formula = comm_env ~ pH + TOC + NH4 + NO3 + Conductivity, data = model_data, distance = \"bray\", add = \"lingoes\")\n         Df SumOfSqs      F Pr(>F)    \nModel     5   6.7123 4.9809  0.001 ***\nResidual 84  22.6401                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nPermutation test for capscale under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nModel: vegan::capscale(formula = comm_env ~ pH + TOC + NH4 + NO3 + Conductivity, data = model_data, distance = \"bray\", add = \"lingoes\")\n             Df SumOfSqs      F Pr(>F)    \npH            1   2.4049 8.9226  0.001 ***\nTOC           1   0.9247 3.4308  0.001 ***\nNH4           1   0.6554 2.4316  0.002 ** \nNO3           1   0.4231 1.5699  0.036 *  \nConductivity  1   2.3043 8.5495  0.001 ***\nResidual     84  22.6401                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nPermutation test for capscale under reduced model\nMarginal effects of terms\nPermutation: free\nNumber of permutations: 999\n\nModel: vegan::capscale(formula = comm_env ~ pH + TOC + NH4 + NO3 + Conductivity, data = model_data, distance = \"bray\", add = \"lingoes\")\n             Df SumOfSqs      F Pr(>F)    \npH            1   1.8475 6.8547  0.001 ***\nTOC           1   0.7888 2.9267  0.001 ***\nNH4           1   0.6795 2.5210  0.002 ** \nNO3           1   0.3684 1.3667  0.093 .  \nConductivity  1   2.3043 8.5495  0.001 ***\nResidual     84  22.6401                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nPermutation test for capscale under reduced model\nForward tests for axes\nPermutation: free\nNumber of permutations: 999\n\nModel: vegan::capscale(formula = comm_env ~ pH + TOC + NH4 + NO3 + Conductivity, data = model_data, distance = \"bray\", add = \"lingoes\")\n         Df SumOfSqs       F Pr(>F)    \nCAP1      1   2.7263 10.1151  0.001 ***\nCAP2      1   2.3811  8.8344  0.001 ***\nCAP3      1   0.6804  2.5243  0.003 ** \nCAP4      1   0.5877  2.1804  0.007 ** \nCAP5      1   0.3370  1.2503  0.125    \nResidual 84  22.6401                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n注意 `NO3` 在顺序检验与边际检验中的结论可能不同：前者会把先进入模型的变量解释后的剩余变异依次分配，后者检验控制全部其他变量后的贡献。这正是不能只贴一张箭头图的原因。\n\n### 提取当前环境模型的坐标和轴标签\n\n轴百分比按“受约束变异内部的占比”计算，并在标签中明确写出 `constrained`。调整后 \\(R^2\\) 则衡量全部五个变量对总群落变异的解释比例。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenv_eigenvalues_mod2 <- cap_env$CCA$eig\nenv_axis_percent_mod2 <- 100 *\n  env_eigenvalues_mod2[1:2] /\n  sum(env_eigenvalues_mod2)\n\nlab1_mod2 <- sprintf(\n  \"CAP1 (%.1f%% constrained)\",\n  env_axis_percent_mod2[1]\n)\nlab2_mod2 <- sprintf(\n  \"CAP2 (%.1f%% constrained)\",\n  env_axis_percent_mod2[2]\n)\n\nsite_scores_mod2 <- as.data.frame(\n  vegan::scores(\n    cap_env,\n    display = \"sites\",\n    choices = 1:2,\n    scaling = 2\n  )\n)\nsite_scores_mod2$SampleID <- rownames(site_scores_mod2)\nsite_scores_mod2$Group <- metadata_env[\n  site_scores_mod2$SampleID,\n  \"Group\"\n]\n\narrow_scores_mod2 <- as.data.frame(\n  vegan::scores(\n    cap_env,\n    display = \"bp\",\n    choices = 1:2,\n    scaling = 2\n  )\n)\narrow_scores_mod2$Variable <- rownames(arrow_scores_mod2)\n\narrow_multiplier_mod2 <- min(\n  diff(range(site_scores_mod2$CAP1)) * 0.35 /\n    max(abs(arrow_scores_mod2$CAP1)),\n  diff(range(site_scores_mod2$CAP2)) * 0.35 /\n    max(abs(arrow_scores_mod2$CAP2))\n)\narrow_scores_mod2$CAP1 <- arrow_scores_mod2$CAP1 *\n  arrow_multiplier_mod2\narrow_scores_mod2$CAP2 <- arrow_scores_mod2$CAP2 *\n  arrow_multiplier_mod2\n\nhead(site_scores_mod2)\narrow_scores_mod2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        CAP1       CAP2 SampleID          Group\nS1 -1.306507 -0.4718530       S1 Inland wetland\nS2 -1.413450 -0.7413386       S2 Inland wetland\nS3 -1.455895 -0.8905344       S3 Inland wetland\nS4 -1.567960 -1.0303186       S4 Inland wetland\nS5 -1.523055 -0.9751641       S5 Inland wetland\nS6 -1.662818 -1.0937208       S6 Inland wetland\n                    CAP1        CAP2     Variable\npH            0.62908411  0.91049570           pH\nTOC          -0.65228224 -0.36588590          TOC\nNH4          -0.03593229  0.11372774          NH4\nNO3          -0.38804971 -0.08116419          NO3\nConductivity  0.88250723 -0.59897850 Conductivity\n```\n\n\n:::\n:::\n\n\n每个模型都必须重新提取 eigenvalues 和 labels。不能把单因子模型的 `CAP1` 百分比复制到环境模型。\n\n## 正确解释约束轴和环境箭头 {#sec-polish}\n\n箭头缩放只改变绘图长度，不进入模型计算。环境变量是约束项，地理组仅用于给样本点着色。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_p <- function(p) {\n  if (is.na(p)) {\n    return(\"= NA\")\n  }\n  if (p < 0.001) {\n    return(\"< 0.001\")\n  }\n  sprintf(\"= %.3f\", p)\n}\n\np_cap_environment <- ggplot(\n  site_scores_mod2,\n  aes(CAP1, CAP2, color = Group)\n) +\n  stat_ellipse(\n    type = \"t\",\n    level = 0.95,\n    linewidth = 0.7,\n    show.legend = FALSE\n  ) +\n  geom_point(size = 2.5, alpha = 0.86) +\n  geom_segment(\n    data = arrow_scores_mod2,\n    aes(x = 0, y = 0, xend = CAP1, yend = CAP2),\n    inherit.aes = FALSE,\n    color = \"grey20\",\n    linewidth = 0.55,\n    arrow = grid::arrow(\n      length = grid::unit(2.2, \"mm\"),\n      type = \"closed\"\n    )\n  ) +\n  ggrepel::geom_text_repel(\n    data = arrow_scores_mod2,\n    aes(x = CAP1, y = CAP2, label = Variable),\n    inherit.aes = FALSE,\n    color = \"grey10\",\n    size = 3.0,\n    fontface = \"bold\",\n    seed = 20260718,\n    box.padding = 0.35,\n    point.padding = 0.2,\n    min.segment.length = 0,\n    segment.color = \"grey60\"\n  ) +\n  scale_color_pub(name = \"Wetland group\") +\n  labs(\n    title = \"Environmental CAP\",\n    subtitle = paste0(\n      \"R² = \", sprintf(\"%.3f\", cap_env_r2_raw),\n      \" · adjusted R² = \", sprintf(\"%.3f\", cap_env_r2_adjusted),\n      \" · permutation P \", format_p(cap_env_p)\n    ),\n    x = lab1_mod2,\n    y = lab2_mod2\n  ) +\n  coord_equal(clip = \"off\") +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 11),\n    plot.subtitle = element_text(size = 9.2),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\", size = 9),\n    legend.text = element_text(size = 8.3)\n  ) +\n  guides(color = guide_legend(nrow = 1, byrow = TRUE))\n\np_cap_environment\n```\n\n::: {.cell-output-display}\n![](24-ordination-constrained-cap_files/figure-html/reader-step-10-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_cap_environment,\n  \"figures/24-cap-environment\",\n  width = 150,\n  height = 110\n)\n```\n:::\n\n\n导出后得到：\n\n- `figures/24-cap-environment.pdf`：矢量主图；\n- `figures/24-cap-environment.png`：300 dpi 网页与公众号图；\n- `figures/24-cap-environment.tiff`：300 dpi、LZW 压缩期刊图。\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"约束排序最常见的七个误区\"}\n1. **看到 CAP 分开就宣称存在差异。** 轴本来就是按预测变量优化的；必须报告置换检验和调整后 \\(R^2\\)。\n2. **变量越多越好。** 原始 \\(R^2\\) 会随变量增加而上升。变量应由研究假设预先确定，并检查 VIF 和调整后 \\(R^2\\)。\n3. **把 `by = \"terms\"` 当成独立效应。** 它依赖公式顺序；独立贡献应结合 `by = \"margin\"`，大量探索性检验还需控制多重比较。\n4. **不标准化不同量纲的环境变量。** pH、mg/kg 与 µS/cm 的数值尺度不同；连续预测变量应先 Z-score，除非模型有明确的原尺度解释需求。\n5. **忽略区组和重复测量。** `Condition(Batch)` 用于从模型中控制协变量，受限置换用于保证样本交换性；两者解决不同问题，不能互相替代。\n6. **把箭头解释为因果。** 箭头只表示当前模型与二维投影中的关联方向和强度。\n7. **复用别的模型轴标签。** 每次重拟合后都要从当前模型重新提取 eigenvalues、scores、\\(R^2\\) 和 P 值。\n:::\n\n::: {.callout-warning title=\"环境变量和地理分组可能混杂\"}\n本数据来自不同地理湿地，环境梯度与地理组可能相关。主模型描述的是环境因子与群落结构的总体关联，不证明环境因子的独立因果效应。若目标是估计“控制地理组后的环境关联”，可拟合 `... + Condition(Group)` 的 partial CAP，并使用与采样层级一致的置换设计。\n:::\n\n## 报告约束排序与置换检验的方法与限制 {#sec-methods}\n\n可直接替换变量名、阈值和置换限制：\n\n> Distance-based redundancy analysis (db-RDA; CAP) was performed using Bray–Curtis dissimilarities calculated from sample-wise relative abundances. Features detected in at least 5% of samples were retained, yielding 11,113 features across 90 complete samples. The prespecified environmental predictors (pH, TOC, NH4, NO3, Conductivity) were Z-score standardized before model fitting. A Lingoes correction was applied to the Bray–Curtis dissimilarities. Model significance was assessed with 999 permutations (P = 0.001), and the model explained \\(R^2\\) = 0.229 of the total variation (adjusted \\(R^2\\) = 0.183). Sequential, marginal, and axis-wise permutation tests were performed, and variance inflation factors were all below 1.63. Wetland group was used only for point color in the environmental CAP figure.\n\n若样本属于同一受试者、站点或区组，应把最后的置换描述改成实际限制，例如“permutations were restricted within site”。\n\n## 将约束排序与置换检验用于自己的研究 {#sec-own-data}\n\n### 四张表的最低要求\n\n- `otutab`：特征 × 样本的非负计数表；\n- `taxonomy`：特征 × 分类层级，行名与 `otutab` 完全相同；\n- `metadata`：样本 × 分组/协变量，行名与 `otutab` 列名一致；\n- `environment`：样本 × 连续环境或临床变量，行名能与样本 ID 对齐。\n\n替换路径和公式：\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"your_project/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"your_project/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"your_project/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nenvironment <- read.delim(\n  \"your_project/environment.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\npredictors <- c(\"pH\", \"Moisture\", \"OrganicCarbon\")\ngroup_col <- \"Treatment\"\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(colnames(otutab) %in% rownames(environment)),\n  all(predictors %in% colnames(environment))\n)\n```\n:::\n\n\n然后把主模型公式替换为：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_your_data <- vegan::capscale(\n  comm_rel ~ pH + Moisture + OrganicCarbon,\n  data = model_data,\n  distance = \"bray\",\n  add = \"lingoes\"\n)\n```\n:::\n\n\n正式建模前还要决定：\n\n1. 环境变量是否由先验假设确定，而不是根据同一张图反复筛选；\n2. 缺失样本如何处理，最终模型样本数是多少；\n3. 是否存在批次、地点、家庭、受试者或时间序列结构；\n4. 需要把哪些变量放入 `Condition()`，置换应限制在哪个层级；\n5. Bray–Curtis、Aitchison 或 UniFrac 哪个距离与科学问题一致；\n6. 模型结果在不同 prevalence 阈值和变量集合下是否稳定。\n\n## 参考 {#sec-references}\n\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n- Anderson MJ, Willis TJ. Canonical analysis of principal coordinates: a useful method of constrained ordination for ecology. *Ecology*. 2003;84:511–525. [doi:10.1890/0012-9658(2003)084[0511:CAOPCA]2.0.CO;2](https://doi.org/10.1890/0012-9658(2003)084%5B0511:CAOPCA%5D2.0.CO;2)\n- Legendre P, Anderson MJ. Distance-based redundancy analysis: testing multispecies responses in multifactorial ecological experiments. *Ecological Monographs*. 1999;69:1–24.\n- Peres-Neto PR, Legendre P, Dray S, Borcard D. Variation partitioning of species data matrices: estimation and comparison of fractions. *Ecology*. 2006;87:2614–2625.\n- Oksanen J, Simpson GL, Blanchet FG, et al. `vegan`: Community Ecology Package. [CRAN package page](https://CRAN.R-project.org/package=vegan)\n",
    "supporting": [
      "24-ordination-constrained-cap_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "895c139796c2d0d10d4bc68cc00c5af6",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  }
}
