{
  "hash": "0ed84df2e6356f7579d9380fea443a08",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"出版级作图地基：ggplot2 主题、色盲友好配色、字体、PDF/SVG 矢量 + TIFF/PNG 300–600 ppi 导出\"\ndraft: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nauthor: \"Peter\"\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/18-publication-graphics.R\n  packages:\n  - colorspace\n  - ggplot2\n  - jsonlite\n  - ragg\n  - readr\n  - scales\n  - svglite\n  - systemfonts\n---\n\n## 发表级图形首先要可读、可辨和可复现 {#sec-paper-figure}\n\n一张图在 RStudio 绘图窗里看起来清楚，不等于投稿文件合格。真正要交付的是一组可复核的文件合同：最终物理尺寸、字体、颜色编码、矢量或位图格式、实际像素数，以及打开导出文件后的回验结果。\n\n本页用 An 等公开湿地研究随 `microeco 2.0.0` 分发的真实 16S 数据重绘四张图。数据包含 13,628 个 OTU、90 个样本和 1,619,670 条 reads；三组各 30 个样本。以下比较聚焦图形的可读性与导出质量，不用于检验湿地组的生物学差异。\n\n\n::: {.callout-important title=\"先记住三个结论\"}\n\n1. **先定最终宽高，再谈字号和 ppi。** 在大画布上做完再缩小，常把 10 pt 字缩成不可读的小字。\n2. **PDF/SVG 是矢量格式，不存在“300 dpi 矢量图”。** ppi 只约束 PNG/TIFF 这类像素网格；图中若嵌入照片，照片本身仍有分辨率。\n3. **颜色不能是唯一编码。** 重要分组同时使用 shape、linetype、direct label 或 panel，色觉模拟只是检查，不是可访问性的全部证明。\n\n:::\n\n本次文件级验收为 **171 / 171 PASS**：4 张图各生成 PDF、SVG、PNG 和 LZW-TIFF，共 8 个矢量文件、8 个 600 ppi 位图文件；4 个 PDF 均嵌入字体，4 个 SVG 均保留文本节点，16 个主文件均通过最终尺寸检查。\n\n## 下载并读取本次分析的数据 {#sec-preparation}\n\n需要 R，以及 `colorspace`、`ggplot2`、`jsonlite`、`ragg`、`readr`、`scales`、`svglite`、`systemfonts`。本次使用中国湿地的 OTU count 表、分类表和样本信息表。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"scripts/validate_publication_graphics.R\",\n  \"data/small/metadata.tsv\",\n  \"data/small/otutab.tsv\",\n  \"data/small/source_summary.json\",\n  \"data/small/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260721)\n\nrequired_packages <- c(\n  \"colorspace\", \"digest\", \"dplyr\", \"ggplot2\", \"jsonlite\", \"ragg\",\n  \"readr\", \"scales\", \"svglite\", \"systemfonts\", \"tibble\", \"tidyr\"\n)\nmissing_packages <- required_packages[\n  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)\n]\nstopifnot(length(missing_packages) == 0L)\n\nfont_pub <- \"DejaVu Sans\"\nfont_info <- systemfonts::font_info(font_pub)\nstopifnot(\n  nrow(font_info) >= 1L,\n  identical(font_info$family[[1L]], font_pub),\n  file.exists(font_info$path[[1L]]),\n  isTRUE(font_info$scalable[[1L]])\n)\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\", linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\", size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(\n        colour = \"#666666\", hjust = 0\n      ),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 89,\n  height = 70,\n  units = \"mm\",\n  dpi = 600,\n  write_svg = TRUE,\n  write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot,\n    width = width, height = height, units = units,\n    device = grDevices::cairo_pdf,\n    family = base_family,\n    bg = \"white\"\n  )\n\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"), plot,\n      width = width, height = height, units = units,\n      device = svglite::svglite,\n      bg = \"white\"\n    )\n  }\n\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot,\n    width = width, height = height, units = units,\n    dpi = dpi,\n    device = ragg::agg_png,\n    bg = \"white\"\n  )\n\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"), plot,\n      width = width, height = height, units = units,\n      dpi = dpi,\n      device = ragg::agg_tiff,\n      compression = \"lzw\",\n      bg = \"white\"\n    )\n  }\n\n  invisible(plot)\n}\n```\n:::\n\n\n### 从三件套读入真实数据并先验收\n\n本页在普通 Linux 工作站上约需 30 秒，峰值内存低于 1 GB。四个输入文件都先核对 SHA-256，再检查矩阵方向、非负整数 counts 和 ID 集合。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"data/small/otutab.tsv\",\n  taxonomy = \"data/small/taxonomy.tsv\",\n  metadata = \"data/small/metadata.tsv\",\n  source_summary = \"data/small/source_summary.json\"\n)\nexpected_sha256 <- c(\n  otutab = \"76fa79c38da889f35978dc86da4641a270961746709ff38049ee5f67e3c6f7a3\",\n  taxonomy = \"725280bb9a0cd9bda7b540022e92af945ceed52527f8b2d220b055b4489f6901\",\n  metadata = \"df24771dccf27607ddf922c6bca2cafa876d946fbe2e09d14b601accce66ba64\",\n  source_summary = \"acc15b18d3f85d6d35770d0db7580d91d0a55a838862876536500a8d7c75711b\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  digest::digest,\n  character(1),\n  algo = \"sha256\",\n  serialize = FALSE,\n  file = TRUE\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\notutab <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\n\notu_matrix <- as.matrix(otutab)\nstorage.mode(otu_matrix) <- \"numeric\"\n\nstopifnot(\n  identical(rownames(otu_matrix), rownames(taxonomy)),\n  identical(colnames(otu_matrix), rownames(metadata)),\n  all(is.finite(otu_matrix)),\n  all(otu_matrix >= 0),\n  all(otu_matrix == round(otu_matrix)),\n  all(c(\"Group\", \"Type\", \"Saline\") %in% colnames(metadata)),\n  nrow(otu_matrix) == 13628L,\n  ncol(otu_matrix) == 90L,\n  sum(otu_matrix) == 1619670\n)\n\ndim(otu_matrix)\notu_matrix[1:5, 1:5]\ntaxonomy[1:5, , drop = FALSE]\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\n                         Class               Order               Family Genus\nOTU_4272            c__Bacilli       o__Bacillales                  f__   g__\nOTU_236                    c__                 o__                  f__   g__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae   g__\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__   g__\nOTU_32                     c__                 o__                  f__   g__\n         Species\nOTU_4272     s__\nOTU_236      s__\nOTU_399      s__\nOTU_1556     s__\nOTU_32       s__\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/691722146e287afe063bd43e9ce4fa41977fe763/examples/18-publication-graphics.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"colorspace\", \"digest\", \"dplyr\", \"ggplot2\", \"jsonlite\",\n  \"ragg\", \"readr\", \"scales\", \"svglite\", \"systemfonts\",\n  \"tibble\", \"tidyr\"\n))\n```\n:::\n\n\n</details>\n\n## 先定最终尺寸，再决定格式 {#sec-theory}\n\n### 矢量和位图解决的是两类问题\n\n矢量图记录几何对象：线段、曲线、点、文字和填充。放大时由查看器重新计算，因此适合大多数 `ggplot2` 统计图。\n\n位图记录规则像素网格，适合显微照片、遥感图、密集热图或期刊明确要求 TIFF/PNG 的情形。位图清晰度由两个量共同决定：\n\n\\[\nN_{px}=\\frac{L_{mm}}{25.4}\\times \\mathrm{ppi}\n\\]\n\n其中，$L_{mm}$ 是最终物理长度，$N_{px}$ 是该方向的像素数。例如 89 mm 宽的图：\n\n| Target ppi | Expected width | Expected height at 70 mm | Pixel count |\n|---:|---:|---:|---:|\n| 72 | 252 px | 198 px | 0.05 MP |\n| 300 | 1,051 px | 826 px | 0.87 MP |\n| 600 | 2,102 px | 1,653 px | 3.47 MP |\n\n不同软件可能因取整相差 1 pixel，应根据实际文件核对，而不是只看保存命令。\n\n### `dpi` 与 `ppi` 不应混为一谈\n\n- **ppi（pixels per inch）**描述数字图像每英寸包含多少像素；本页位图验收的对象就是 ppi。\n- **dpi（dots per inch）**原本描述打印设备每英寸落多少墨点。\n- R 的 `ggsave(dpi = ...)` 参数沿用了常见软件命名；对 PNG/TIFF 导出来说，它控制物理尺寸到像素尺寸的换算，因此本文按输出 ppi 解读。\n\n期刊指南经常把数字图的要求也写成 dpi。投稿时照目标期刊的原词填写，但在自己的审计表里应同时保存毫米尺寸和实际 pixels，避免只剩一个模糊的“300 dpi”。\n\n### 字号只能在最终尺寸下判断\n\n字体大小以 point 为单位，1 point = 1/72 inch。若图先按 180 mm 宽绘制，再缩到 90 mm，所有 10 pt 文字都会视觉上变成约 5 pt。正确顺序是：\n\n```text\njournal column width\n        ↓\nfinal width × height\n        ↓\nfont size / line width / point size\n        ↓\nlegend and panel layout\n        ↓\nexport and reopen\n```\n\n字体名称也不是装饰信息。系统若找不到指定字体，会替换成另一个字体，造成字宽变化、换行漂移或 PDF 字体未嵌入。本页明确解析 `DejaVu Sans`，记录字体文件 SHA-256，并检查 PDF 嵌入和 SVG 字体声明。换用 Arial、Helvetica 或期刊指定字体时，同样要先验证系统真正解析到了哪一个文件。\n\n### 色盲友好不等于“换一套调色板”\n\n颜色选择至少要同时回答四个问题：\n\n- 色相在常见色觉缺陷模拟下是否仍可区分；\n- 点或线是否还有 shape、linetype、边框或文字标签作为第二通道；\n- 浅色对象在白底上是否仍可见；\n- 灰度打印、投影和缩小后是否仍能读懂。\n\n本例的三组颜色是蓝、vermillion 和 bluish green。deutan/protan 模拟后部分颜色明显靠近，但 circle、square、triangle 仍保留组别。模拟结果不能代表每位读者的实际视觉体验，因此关键结论还应允许从标签、形状或分面中恢复。\n\n### 按目标期刊的当前要求设置图形尺寸与格式\n\nNature 当前图形指南偏好让线条和文字保持矢量，并接受 PDF/SVG；其示例版面给出约 89 mm 单栏和约 183 mm 双栏。PLOS 的具体期刊指南则要求按最终尺寸准备文件，并列出 TIFF/EPS、300–600 dpi、LZW 等要求。两者已经说明：**不同期刊、不同图型、不同投稿阶段可能要求不同格式。**\n\n因此本页把 89 mm 和 183 mm 当作可执行示例，不把它们写成所有期刊的统一标准。投稿前应重新读取目标期刊的最新 figure guide，并把宽高、颜色空间、格式、字体和分辨率更新到导出函数参数中。\n\n<details>\n<summary><strong>深入：为什么“把 72 ppi 图片改成 600 ppi”通常没有修复任何细节</strong></summary>\n\n若原始图只有 252 × 198 pixels，把元数据改成 600 ppi 会让它在版面上的标称尺寸变小；把它插值到 2,102 × 1,653 pixels，则只是根据邻近像素猜出新像素。两种操作都不会恢复原来没有记录的线条、字形或照片细节。\n\n统计图应回到产生它的代码和数据重新导出。照片或扫描图应回到原始采集文件；若原始采集本身分辨率不足，应如实说明，而不是用插值掩盖。\n\n</details>\n\n## 固定颜色、字体与物理尺寸 {#sec-code}\n\n### 建立英文标签、颜色和形状的双重编码\n\nmetadata 中的 `IW/CW/TW` 先映射成英文组名。每组获得一个颜色和一个形状；颜色模拟只改变填充色，不改变 shape。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_labels <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan Plateau\"\n)\ngroup_palette <- c(\n  \"Inland wetland\" = \"#0072B2\",\n  \"Coastal wetland\" = \"#D55E00\",\n  \"Tibetan Plateau\" = \"#009E73\"\n)\ngroup_shapes <- c(\n  \"Inland wetland\" = 21,\n  \"Coastal wetland\" = 22,\n  \"Tibetan Plateau\" = 24\n)\n\nsample_plot_data <- data.frame(\n  SampleID = colnames(otu_matrix),\n  LibrarySize = as.numeric(colSums(otu_matrix)),\n  ObservedFeatures = as.numeric(colSums(otu_matrix > 0)),\n  Group = metadata[colnames(otu_matrix), \"Group\"],\n  GroupLabel = unname(\n    group_labels[metadata[colnames(otu_matrix), \"Group\"]]\n  ),\n  Salinity = metadata[colnames(otu_matrix), \"Saline\"],\n  stringsAsFactors = FALSE\n)\nsample_plot_data$GroupLabel <- factor(\n  sample_plot_data$GroupLabel,\n  levels = names(group_palette)\n)\n\npalette_views <- list(\n  Standard = unname(group_palette),\n  \"Deuteranopia simulation\" = colorspace::deutan(\n    unname(group_palette), severity = 1\n  ),\n  \"Protanopia simulation\" = colorspace::protan(\n    unname(group_palette), severity = 1\n  )\n)\n\npalette_audit <- do.call(\n  rbind,\n  lapply(names(palette_views), function(view) {\n    data.frame(\n      View = view,\n      Group = names(group_palette),\n      Hex = unname(palette_views[[view]]),\n      Shape = unname(group_shapes[names(group_palette)]),\n      ContrastWhite = as.numeric(\n        colorspace::contrast_ratio(palette_views[[view]], \"#FFFFFF\")\n      ),\n      ContrastBlack = as.numeric(\n        colorspace::contrast_ratio(palette_views[[view]], \"#000000\")\n      )\n    )\n  })\n)\n\nencoding_plot_data <- do.call(\n  rbind,\n  lapply(names(palette_views), function(view) {\n    out <- sample_plot_data\n    out$Vision <- view\n    view_palette <- stats::setNames(\n      palette_views[[view]],\n      names(group_palette)\n    )\n    out$DisplayColor <- unname(\n      view_palette[as.character(out$GroupLabel)]\n    )\n    out\n  })\n)\nencoding_plot_data$Vision <- factor(\n  encoding_plot_data$Vision,\n  levels = names(palette_views)\n)\n\npalette_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     View           Group     Hex Shape ContrastWhite\n1                Standard  Inland wetland #0072B2    21      5.185446\n2                Standard Coastal wetland #D55E00    22      3.867184\n3                Standard Tibetan Plateau #009E73    24      3.421140\n4 Deuteranopia simulation  Inland wetland #3B67B1    21      5.583732\n5 Deuteranopia simulation Coastal wetland #9E8C00    22      3.384338\n6 Deuteranopia simulation Tibetan Plateau #8A8676    24      3.650717\n7   Protanopia simulation  Inland wetland #5375B5    21      4.585598\n8   Protanopia simulation Coastal wetland #817100    22      4.888864\n9   Protanopia simulation Tibetan Plateau #9A9271    24      3.123137\n  ContrastBlack\n1      4.049796\n2      5.430308\n3      6.138305\n4      3.760925\n5      6.205054\n6      5.752295\n7      4.579555\n8      4.295476\n9      6.724010\n```\n\n\n:::\n:::\n\n\n### 画颜色视觉与冗余编码审计图\n\n点使用可填充 shape 21/22/24，黑色边框让浅色填充在白底上仍有边界。图例中的英文名可以直接进入英文论文。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nencoding_plot <- ggplot2::ggplot(\n  encoding_plot_data,\n  ggplot2::aes(x = ObservedFeatures, y = LibrarySize)\n) +\n  ggplot2::geom_point(\n    ggplot2::aes(fill = DisplayColor, shape = GroupLabel),\n    colour = \"#1A1A1A\",\n    stroke = 0.35,\n    size = 2.2,\n    alpha = 0.85\n  ) +\n  ggplot2::facet_wrap(~Vision, nrow = 1L) +\n  ggplot2::scale_fill_identity(\n    name = \"Wetland group\",\n    breaks = unname(group_palette),\n    labels = names(group_palette),\n    guide = \"legend\"\n  ) +\n  ggplot2::scale_shape_manual(\n    name = \"Wetland group\",\n    values = group_shapes\n  ) +\n  ggplot2::scale_x_continuous(labels = scales::label_comma()) +\n  ggplot2::scale_y_continuous(labels = scales::label_comma()) +\n  ggplot2::labs(\n    title = \"Colour is not the only group cue\",\n    subtitle = paste(\n      \"The same 90 samples retain distinct shapes under\",\n      \"two colour-vision simulations\"\n    ),\n    x = \"Observed features\",\n    y = \"Library size (reads)\"\n  ) +\n  theme_pub(base_size = 9.5) +\n  ggplot2::theme(\n    legend.position = \"bottom\",\n    legend.box = \"horizontal\",\n    panel.spacing.x = grid::unit(3, \"mm\")\n  )\n\nsave_pub(\n  encoding_plot,\n  \"figures/18-encoding-redundancy-audit\",\n  width = 183,\n  height = 95,\n  dpi = 600\n)\n```\n:::\n\n\n![同一批真实样本在标准颜色、deutan 和 protan 模拟下的显示。颜色同时配合形状，避免把分组信息只压在色相上。](../figures/18-encoding-redundancy-audit.png){#fig-encoding-redundancy}\n\n### 在 89 mm 最终宽度下完成单栏图\n\n先把 taxonomy 的 `p__` 前缀清理掉，再按每个样本计算相对丰度。图中展示总 reads 排名前五的 phyla，其余合并为 `Other`；三根柱是组内 30 个样本相对丰度的均值。这张图只用于排版示范，不把组间视觉差异当作推断结果。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphylum <- sub(\n  \"^p__\",\n  \"\",\n  as.character(taxonomy[rownames(otu_matrix), \"Phylum\"])\n)\nphylum[is.na(phylum) | !nzchar(phylum)] <- \"Unassigned\"\n\nphylum_totals <- sort(\n  rowsum(rowSums(otu_matrix), phylum)[, 1L],\n  decreasing = TRUE\n)\ntop_phyla <- names(phylum_totals)[seq_len(5L)]\nphylum_class <- ifelse(phylum %in% top_phyla, phylum, \"Other\")\nphylum_counts <- rowsum(\n  otu_matrix,\n  group = phylum_class,\n  reorder = FALSE\n)\nphylum_relative <- sweep(\n  phylum_counts,\n  2L,\n  colSums(phylum_counts),\n  \"/\"\n)\n\nphylum_composition <- do.call(\n  rbind,\n  lapply(names(group_labels), function(group_code) {\n    selected <- rownames(metadata)[metadata$Group == group_code]\n    data.frame(\n      Group = unname(group_labels[[group_code]]),\n      Phylum = rownames(phylum_relative),\n      MeanRelativeAbundance = rowMeans(\n        phylum_relative[, selected, drop = FALSE]\n      ),\n      SampleN = length(selected),\n      stringsAsFactors = FALSE\n    )\n  })\n)\n\nphylum_order <- c(top_phyla, \"Other\")\nphylum_composition$Group <- factor(\n  phylum_composition$Group,\n  levels = names(group_palette)\n)\nphylum_composition$Phylum <- factor(\n  phylum_composition$Phylum,\n  levels = phylum_order\n)\nstopifnot(\n  all(\n    abs(\n      tapply(\n        phylum_composition$MeanRelativeAbundance,\n        phylum_composition$Group,\n        sum\n      ) - 1\n    ) < 1e-12\n  )\n)\n\nphylum_composition\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Group         Phylum MeanRelativeAbundance SampleN\nOther            Inland wetland          Other            0.22925113      30\nChloroflexi      Inland wetland    Chloroflexi            0.17560180      30\nProteobacteria   Inland wetland Proteobacteria            0.23380808      30\nAcidobacteria    Inland wetland  Acidobacteria            0.19261967      30\nActinobacteria   Inland wetland Actinobacteria            0.10352536      30\nBacteroidetes    Inland wetland  Bacteroidetes            0.06519396      30\nOther1          Coastal wetland          Other            0.23662190      30\nChloroflexi1    Coastal wetland    Chloroflexi            0.12366948      30\nProteobacteria1 Coastal wetland Proteobacteria            0.37269759      30\nAcidobacteria1  Coastal wetland  Acidobacteria            0.07105327      30\nActinobacteria1 Coastal wetland Actinobacteria            0.09523486      30\nBacteroidetes1  Coastal wetland  Bacteroidetes            0.10072289      30\nOther2          Tibetan Plateau          Other            0.20811096      30\nChloroflexi2    Tibetan Plateau    Chloroflexi            0.11545141      30\nProteobacteria2 Tibetan Plateau Proteobacteria            0.31489623      30\nAcidobacteria2  Tibetan Plateau  Acidobacteria            0.07645415      30\nActinobacteria2 Tibetan Plateau Actinobacteria            0.10152668      30\nBacteroidetes2  Tibetan Plateau  Bacteroidetes            0.18356057      30\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomposition_palette <- stats::setNames(\n  c(\n    pal_pub[[\"blue\"]],\n    pal_pub[[\"orange\"]],\n    pal_pub[[\"green\"]],\n    pal_pub[[\"vermillion\"]],\n    pal_pub[[\"purple\"]],\n    pal_pub[[\"grey\"]]\n  ),\n  phylum_order\n)\n\ncomposition_plot <- ggplot2::ggplot(\n  phylum_composition,\n  ggplot2::aes(\n    x = Group,\n    y = MeanRelativeAbundance,\n    fill = Phylum\n  )\n) +\n  ggplot2::geom_col(\n    width = 0.72,\n    colour = \"white\",\n    linewidth = 0.25\n  ) +\n  ggplot2::scale_fill_manual(\n    values = composition_palette,\n    breaks = phylum_order,\n    drop = FALSE\n  ) +\n  ggplot2::scale_y_continuous(\n    labels = scales::label_percent(accuracy = 1),\n    expand = ggplot2::expansion(mult = c(0, 0.02))\n  ) +\n  ggplot2::labs(\n    title = \"Community composition at final size\",\n    subtitle = \"Mean relative abundance; n = 30 per group\",\n    x = NULL,\n    y = \"Mean relative abundance\",\n    fill = NULL\n  ) +\n  theme_pub(base_size = 8.5) +\n  ggplot2::theme(\n    axis.text.x = ggplot2::element_text(angle = 25, hjust = 1),\n    legend.position = \"bottom\",\n    legend.text = ggplot2::element_text(size = 8),\n    legend.key.height = grid::unit(3.3, \"mm\"),\n    panel.grid.major.x = ggplot2::element_blank()\n  ) +\n  ggplot2::guides(\n    fill = ggplot2::guide_legend(ncol = 2, byrow = TRUE)\n  )\n\nsave_pub(\n  composition_plot,\n  \"figures/18-final-size-community-summary\",\n  width = 89,\n  height = 105,\n  dpi = 600\n)\n```\n:::\n\n\n![按 89 mm 单栏宽度直接排版的门水平组成图。图例、轴标签和字号均在最终尺寸下判断。](../figures/18-final-size-community-summary.png){#fig-final-size-composition}\n\n### 把格式选择和像素预算画成可复核证据\n\n格式决策图本身也使用 `ggplot2` 绘制，因此可以和统计图共享字体、线宽和导出函数。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecision_boxes <- data.frame(\n  xmin = c(1.35, 0.15, 2.55, 0.15, 2.55, 0.65),\n  xmax = c(2.65, 1.45, 3.85, 1.45, 3.85, 3.35),\n  ymin = c(3.85, 2.25, 2.25, 0.65, 0.65, -0.35),\n  ymax = c(4.65, 3.15, 3.15, 1.55, 1.55, 0.25),\n  fill = c(\n    \"#E8F1F8\", \"#EAF5F1\", \"#FFF3E6\",\n    \"#DDECF6\", \"#FCE6DD\", \"#F2F2F2\"\n  ),\n  label = c(\n    \"Finished ggplot\\nat final dimensions\",\n    \"Lines, points,\\nand text\",\n    \"Pixel-based image\\nor journal request\",\n    \"PDF / SVG\\nvector geometry\",\n    \"TIFF / PNG\\nexplicit ppi\",\n    \"Open the exported file; audit width, height, fonts, and labels\"\n  ),\n  stringsAsFactors = FALSE\n)\ndecision_arrows <- data.frame(\n  x = c(1.75, 2.25, 0.8, 3.2, 0.8, 3.2),\n  xend = c(0.8, 3.2, 0.8, 3.2, 1.55, 2.45),\n  y = c(3.85, 3.85, 2.25, 2.25, 0.65, 0.65),\n  yend = c(3.15, 3.15, 1.55, 1.55, 0.25, 0.25)\n)\n\ndecision_plot <- ggplot2::ggplot() +\n  ggplot2::geom_segment(\n    data = decision_arrows,\n    ggplot2::aes(x = x, y = y, xend = xend, yend = yend),\n    linewidth = 0.55,\n    colour = \"#4D4D4D\",\n    arrow = grid::arrow(\n      length = grid::unit(2.1, \"mm\"),\n      type = \"closed\"\n    )\n  ) +\n  ggplot2::geom_rect(\n    data = decision_boxes,\n    ggplot2::aes(\n      xmin = xmin,\n      xmax = xmax,\n      ymin = ymin,\n      ymax = ymax,\n      fill = fill\n    ),\n    colour = \"#4D4D4D\",\n    linewidth = 0.45\n  ) +\n  ggplot2::geom_text(\n    data = decision_boxes,\n    ggplot2::aes(\n      x = (xmin + xmax) / 2,\n      y = (ymin + ymax) / 2,\n      label = label\n    ),\n    family = font_pub,\n    colour = \"#1A1A1A\",\n    lineheight = 0.98,\n    size = c(3.2, 3, 3, 3.2, 3.2, 2.8),\n    fontface = c(\"bold\", \"plain\", \"plain\", \"bold\", \"bold\", \"plain\")\n  ) +\n  ggplot2::scale_fill_identity() +\n  ggplot2::coord_cartesian(\n    xlim = c(0, 4),\n    ylim = c(-0.45, 4.8),\n    clip = \"off\"\n  ) +\n  ggplot2::labs(\n    title = \"Choose the file format from the graphic content\",\n    subtitle = paste(\n      \"Physical dimensions come first; ppi is a raster-only\",\n      \"sampling contract\"\n    )\n  ) +\n  theme_pub(base_size = 10) +\n  ggplot2::theme(\n    panel.grid.major = ggplot2::element_blank(),\n    panel.grid.minor = ggplot2::element_blank(),\n    panel.border = ggplot2::element_blank(),\n    axis.text = ggplot2::element_blank(),\n    axis.title = ggplot2::element_blank(),\n    axis.ticks = ggplot2::element_blank(),\n    legend.position = \"none\",\n    plot.margin = ggplot2::margin(5, 7, 5, 7)\n  )\n\nsave_pub(\n  decision_plot,\n  \"figures/18-export-decision-map\",\n  width = 183,\n  height = 90,\n  dpi = 600\n)\n```\n:::\n\n\n![从图形内容选择输出格式：线、点和文字优先保留矢量；像素图或期刊指定格式再使用有明确 ppi 的位图。](../figures/18-export-decision-map.png){#fig-export-decision}\n\n同一张 probe 图固定为 89 × 70 mm，只改变 ppi。`floor()` 对应本次 ragg 设备实际采用的像素取整方式；正式回验仍以生成文件为准。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprobe_plot <- ggplot2::ggplot(\n  sample_plot_data,\n  ggplot2::aes(x = ObservedFeatures, y = LibrarySize)\n) +\n  ggplot2::geom_point(\n    ggplot2::aes(fill = GroupLabel, shape = GroupLabel),\n    colour = \"#1A1A1A\",\n    stroke = 0.3,\n    size = 1.7,\n    alpha = 0.85\n  ) +\n  ggplot2::scale_fill_manual(values = group_palette) +\n  ggplot2::scale_shape_manual(values = group_shapes) +\n  ggplot2::scale_x_continuous(labels = scales::label_comma()) +\n  ggplot2::scale_y_continuous(labels = scales::label_comma()) +\n  ggplot2::labs(\n    title = \"Resolution probe\",\n    x = \"Observed features\",\n    y = \"Library size (reads)\"\n  ) +\n  theme_pub(base_size = 8) +\n  ggplot2::theme(legend.position = \"none\")\n\nprobe_ppi <- c(72L, 300L, 600L)\nprobe_paths <- file.path(\n  \"results/18-publication-graphics\",\n  paste0(\"resolution-probe-\", probe_ppi, \"ppi.png\")\n)\ndir.create(\n  \"results/18-publication-graphics\",\n  recursive = TRUE,\n  showWarnings = FALSE\n)\n\nfor (i in seq_along(probe_ppi)) {\n  ggplot2::ggsave(\n    probe_paths[[i]],\n    plot = probe_plot,\n    width = 89,\n    height = 70,\n    units = \"mm\",\n    dpi = probe_ppi[[i]],\n    device = ragg::agg_png,\n    bg = \"white\"\n  )\n}\n\nresolution_plot_data <- data.frame(\n  target_ppi = probe_ppi,\n  pixel_width = floor(89 / 25.4 * probe_ppi),\n  pixel_height = floor(70 / 25.4 * probe_ppi)\n)\nresolution_plot_data$megapixels <- with(\n  resolution_plot_data,\n  pixel_width * pixel_height / 1e6\n)\nresolution_plot_data$PPI <- factor(\n  paste0(resolution_plot_data$target_ppi, \" ppi\"),\n  levels = paste0(probe_ppi, \" ppi\")\n)\nresolution_plot_data$PixelLabel <- paste0(\n  scales::comma(resolution_plot_data$pixel_width),\n  \" x \",\n  scales::comma(resolution_plot_data$pixel_height),\n  \" px\\n\",\n  sprintf(\"%.2f MP\", resolution_plot_data$megapixels)\n)\n\nresolution_plot <- ggplot2::ggplot(\n  resolution_plot_data,\n  ggplot2::aes(x = PPI, y = target_ppi, fill = PPI)\n) +\n  ggplot2::geom_col(\n    width = 0.62,\n    colour = \"#1A1A1A\",\n    linewidth = 0.35\n  ) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = PixelLabel),\n    vjust = -0.35,\n    family = font_pub,\n    size = 3.2,\n    lineheight = 0.95\n  ) +\n  ggplot2::scale_fill_manual(\n    values = c(\n      pal_pub[[\"sky\"]],\n      pal_pub[[\"blue\"]],\n      pal_pub[[\"vermillion\"]]\n    )\n  ) +\n  ggplot2::scale_y_continuous(\n    limits = c(0, 700),\n    breaks = c(0, 72, 300, 600),\n    expand = ggplot2::expansion(mult = c(0, 0))\n  ) +\n  ggplot2::labs(\n    title = \"Physical size stays fixed; pixel budget does not\",\n    subtitle = \"The same plot was exported at 89 x 70 mm\",\n    x = NULL,\n    y = \"Pixels per inch (ppi)\",\n    caption = paste(\n      \"Increasing metadata cannot restore detail that was absent\",\n      \"from a low-resolution source.\"\n    )\n  ) +\n  theme_pub(base_size = 10) +\n  ggplot2::theme(\n    legend.position = \"none\",\n    panel.grid.major.x = ggplot2::element_blank()\n  )\n\nsave_pub(\n  resolution_plot,\n  \"figures/18-raster-resolution-audit\",\n  width = 183,\n  height = 92,\n  dpi = 600\n)\n```\n:::\n\n\n![同一张 89 × 70 mm 图在 72、300 和 600 ppi 下的实际像素预算。物理尺寸不变，像素数并不相同。](../figures/18-raster-resolution-audit.png){#fig-resolution-audit}\n\n### 不只保存：逐个打开并检查导出文件\n\n### 测量导出文件的尺寸与字体\n\n直接打开导出的文件，检查真实尺寸、字体嵌入与位图分辨率。还需要命令行工具 pdfinfo、pdffonts 和 ImageMagick identify。\n\n在 Ubuntu 中可安装 `poppler-utils`、`imagemagick` 和 `fonts-dejavu-core`。这些工具用于读取文件本身的尺寸和字体信息。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_analysis <- function(command, args) {\n  output <- system2(command, args, stdout = TRUE, stderr = TRUE)\n  status <- attr(output, \"status\")\n  if (!is.null(status) && status != 0L) stop(paste(tail(output, 20), collapse = \"\\n\"))\n  invisible(output)\n}\nrun_analysis(file.path(R.home(\"bin\"), \"Rscript\"), c(\"--vanilla\", \"scripts/validate_publication_graphics.R\", \"--project-root\", \".\", \"--input-dir\", \"data/small\", \"--output-dir\", \"results/18-publication-graphics\", \"--figure-dir\", \"figures\"))\n```\n:::\n\n\n完整计算脚本：[validate_publication_graphics.R](https://github.com/petemeng/microbiome-best-practices/blob/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/scripts/validate_publication_graphics.R)。\n\n也可以在终端单独检查导出的文件：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nRscript --vanilla scripts/validate_publication_graphics.R \\\n  --project-root . \\\n  --input-dir data/small \\\n  --output-dir results/18-publication-graphics \\\n  --figure-dir figures\n```\n:::\n\n\n下面读取验证器生成的机器可读表。`actual_width_mm` 和 `actual_height_mm` 是导出文件的实际尺寸，不是命令中计划写入的数字。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_audit <- readr::read_tsv(\n  \"results/18-publication-graphics/format-audit.tsv\",\n  show_col_types = FALSE\n)\nvalidation_summary <- jsonlite::read_json(\n  \"results/18-publication-graphics/publication-graphics-summary.json\",\n  simplifyVector = TRUE\n)\n\nstopifnot(\n  nrow(format_audit) == 16L,\n  all(format_audit$dimension_status == \"PASS\")\n)\n\nformat_audit[, c(\n  \"figure\",\n  \"extension\",\n  \"bytes\",\n  \"actual_width_mm\",\n  \"actual_height_mm\",\n  \"pixel_width\",\n  \"pixel_height\",\n  \"effective_ppi_x\",\n  \"compression\",\n  \"font_status\",\n  \"dimension_status\"\n)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 11\n   figure          extension  bytes actual_width_mm actual_height_mm pixel_width\n   <chr>           <chr>      <dbl>           <dbl>            <dbl>       <dbl>\n 1 18-encoding-re… pdf        26188           183.              94.9          NA\n 2 18-encoding-re… svg        58231           183.              95.0          NA\n 3 18-encoding-re… png       567793           183               95          4322\n 4 18-encoding-re… tiff      938172           183               95          4322\n 5 18-final-size-… pdf        23618            88.9            105.           NA\n 6 18-final-size-… svg        10157            89.0            105.           NA\n 7 18-final-size-… png       171825            89              105          2102\n 8 18-final-size-… tiff      233752            89              105          2102\n 9 18-export-deci… pdf        24334           183.              90.0          NA\n10 18-export-deci… svg         6425           183.              90.0          NA\n11 18-export-deci… png       196473           183               90          4322\n12 18-export-deci… tiff      301922           183               90          4322\n13 18-raster-reso… pdf        21131           183.              91.7          NA\n14 18-raster-reso… svg         6435           183.              92.0          NA\n15 18-raster-reso… png       182861           183               92          4322\n16 18-raster-reso… tiff      286506           183               92          4322\n# ℹ 5 more variables: pixel_height <dbl>, effective_ppi_x <dbl>,\n#   compression <chr>, font_status <chr>, dimension_status <chr>\n```\n\n\n:::\n:::\n\n\nPDF 经 Cairo 导出时 page box 以 point 记录，毫米换算可能因整数 point 取整出现小于 0.4 mm 的差异；SVG 和位图尺寸则几乎精确命中。这里把这个设备行为写入容差，而不是把计划值冒充实测值。\n\n## 检查屏幕预览与投稿文件的差别 {#sec-publication}\n\n### 把尺寸作为函数参数，而不是最后手动缩放\n\n常见的两类调用可以直接固定：\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Single-column example\nsave_pub(\n  plot_single,\n  \"figures/figure-single\",\n  width = 89,\n  height = 75,\n  dpi = 600\n)\n\n# Two-column example\nsave_pub(\n  plot_double,\n  \"figures/figure-double\",\n  width = 183,\n  height = 105,\n  dpi = 600\n)\n```\n:::\n\n\n先用目标宽度检查文字、点、线、legend 和 panel 数量。若单栏塞不下，不要继续缩字；应减少面板、直接标注、拆分补充图，或改用双栏宽度。\n\n### 用“视觉层级”代替装饰堆叠\n\n一个稳定的层级通常是：\n\n- 主标题最强，subtitle 次之，caption 最弱；\n- 数据对象比网格线更醒目；\n- 主要比较用饱和色，背景和辅助参考线用中性灰；\n- 同一种语义在所有 panel 中保持同一颜色、shape 和顺序；\n- 不靠阴影、3D、渐变或粗边框制造“高级感”。\n\n本页主题保留浅色 major grid，去掉 minor grid。若图是组成柱图，x 方向网格没有帮助，就局部关闭；若图是坐标散点，浅网格可帮助估读数值。主题函数提供基线，具体图仍应按信息结构做小范围覆盖。\n\n### 图例应服务查找，不应消耗半张图\n\n优先级通常是：\n\n1. 直接在对象附近标注；\n2. 合并相同语义的 color/shape 图例；\n3. 固定类别顺序并控制 `ncol`；\n4. 类别过多时改为分面、热图或补充表，而不是无限扩展颜色。\n\n组成图只显示 top taxa 时，必须在图注或 Methods 中写明 top 的选择规则和 `Other` 的定义，不能让读者误以为未显示类群不存在。\n\n### 最终提交前做人工加机器双检查\n\n| Audit | Machine check | Human check |\n|---|---|---|\n| Dimensions | PDF/SVG page size; raster pixels | Fits journal column without manual scaling |\n| Typography | Font resolved/embedded; SVG text present | Labels readable at 100% final size |\n| Colour | Hex values; CVD simulations | Groups remain interpretable without hue alone |\n| Raster | Pixel dimensions; effective ppi; compression | No jagged lines, blur, halo or interpolation artifacts |\n| Content | Expected files and English labels | No clipping, overlap, duplicated legends or stale annotations |\n\n机器检查能证明文件属性，不能判断故事是否清楚；人工检查能发现布局问题，却容易漏掉错误尺寸和未嵌入字体。两者不能互相替代。\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿与制图阶段最常见的失败模式\"}\n\n- **给 PDF 写“600 dpi”。** PDF/SVG 的线和文字是矢量；只对其中嵌入的 raster layer 单独讨论 ppi。\n- **用 `ggsave()` 默认尺寸交稿。** 默认值可能来自当前设备，与期刊栏宽无关；每次显式写 `width`、`height` 和 `units`。\n- **在 180 mm 画布上调好 8 pt 字，再缩到 90 mm。** 最终字号随整体缩放减半，应直接在 90 mm 上排版。\n- **只用红绿区分组。** 即使颜色通过某个模拟，也应增加 shape、linetype、label 或 facet。\n- **黄色点直接放白底。** 浅色面积或点需要深色边框；彩色文字还要单独检查对比度。\n- **指定字体名却不检查解析结果。** 同名字体可能缺失或被替换；记录 `systemfonts::font_info()` 的 family、path 和文件哈希。\n- **SVG 有图形却没有可编辑文字。** 某些设备把字形转换成 path；需要文本可编辑时，用 `svglite` 并检查 `<text>` 节点。\n- **把低分辨率图重新采样后称为 600 ppi 原图。** 应从数据和绘图代码重新导出，照片则回到原始采集文件。\n- **所有图一律 600 ppi。** 先看目标期刊和图型；过高分辨率会增加文件体积和处理时间，并不改善矢量对象。\n- **只看 R 绘图窗，不打开提交文件。** PDF 字体替换、SVG 换行、TIFF 颜色和裁切问题只会在实际文件中暴露。\n\n:::\n\n## 报告图形尺寸、字体与导出格式的方法与限制 {#sec-methods}\n\n下面的英文模板可以直接替换方括号内容。只有实际执行过的尺寸、设备和检查才能保留。\n\n> **Figure generation and export.** Statistical graphics were generated in R [version] with ggplot2 [version] using a predefined publication theme. Figure text was set in [font family], whose resolved system font was recorded before rendering. Categorical groups were encoded redundantly by colour and [shape/linetype/direct labels], and the selected palette was inspected under protan and deutan colour-vision simulations with colorspace [version]. Figures were composed at their intended final widths ([single-column width] mm or [double-column width] mm) rather than resized after export. Line art and text were exported as PDF and SVG; raster deliverables were exported with ragg as PNG and LZW-compressed TIFF at [300/600] ppi. Exported files were reopened and audited for physical dimensions, raster pixel dimensions, font embedding or declaration, text retention, compression, clipping, and label readability. All labels within figures were in English.\n\n若期刊只收 TIFF，应删除“PDF and SVG were submitted”，改写为“PDF/SVG files were retained as editable masters, and the submitted TIFF files…”。若实际没有做色觉模拟或字体嵌入检查，也不能把相应句子留在 Methods 中。\n\n## 将图形尺寸、字体与导出格式用于自己的研究 {#sec-own-data}\n\n### 只改三件套路径和分组列\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read_keyed_tsv(\"your_project/data/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"your_project/data/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"your_project/data/metadata.tsv\")\n\ngroup_column <- \"Treatment\"\ngroup_levels <- c(\"Control\", \"Disease\", \"Therapy\")\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  group_column %in% colnames(metadata),\n  setequal(unique(metadata[[group_column]]), group_levels)\n)\n```\n:::\n\n\n若 `otutab` 是 samples × features，应先根据 taxonomy feature IDs 判断方向并转置；不要凭行数和列数猜。\n\n### 根据真实类别数设计编码\n\n三到五组可以使用离散颜色加 shape。类别更多时，不要自动循环八种颜色；先判断是否能用分面、排序、聚合或直接标签减少同时编码的类别数。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_palette <- c(\n  Control = \"#0072B2\",\n  Disease = \"#D55E00\",\n  Therapy = \"#009E73\"\n)\ngroup_shapes <- c(Control = 21, Disease = 22, Therapy = 24)\n\ncolorspace::deutan(group_palette, severity = 1)\ncolorspace::protan(group_palette, severity = 1)\n```\n:::\n\n\n### 把目标期刊规范写成参数表\n\n\n::: {.cell}\n\n```{.r .cell-code}\njournal_spec <- data.frame(\n  layout = c(\"single\", \"double\"),\n  width_mm = c(89, 183),\n  height_mm = c(80, 110),\n  raster_ppi = c(600, 600)\n)\n```\n:::\n\n\n这里的数字必须替换成目标期刊当前指南。还要确认允许的格式、RGB/CMYK、最大文件大小、字体范围、线宽和是否允许透明背景。\n\n### 额外数据要求\n\n本分析只需要三件套。若图中还包含显微照片、地图、凝胶图或其他像素源文件，还需要保存：\n\n- 未经截图或社交软件压缩的原始图；\n- 原始 pixels、采集尺寸和颜色空间；\n- 裁剪、亮度/对比度调整和拼版记录；\n- 每个 panel 的来源与允许的处理边界。\n\n统计图的 600 ppi 导出不能替代这些原始影像合同。\n\n## 参考 {#sec-references}\n\n1. An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n2. Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n3. Wickham H, Navarro D, Pedersen TL. *ggplot2: Elegant Graphics for Data Analysis*. 3rd ed. [ggplot2 book](https://ggplot2-book.org/)\n4. ggplot2 developers. Save a ggplot or other grid object with sensible defaults. [`ggsave()` documentation](https://ggplot2.tidyverse.org/reference/ggsave.html)\n5. Pedersen TL, Shemanarev M. ragg: high-quality raster graphics devices. [`agg_tiff()` documentation](https://ragg.r-lib.org/reference/agg_tiff.html)\n6. Wickham H, Henry L, Pedersen TL, et al. svglite: an SVG graphics device. [svglite documentation](https://svglite.r-lib.org/)\n7. Pedersen TL. systemfonts: system native font finding. [systemfonts documentation](https://systemfonts.r-lib.org/reference/index.html)\n8. Zeileis A, Fisher JC, Hornik K, et al. colorspace: A Toolbox for Manipulating and Assessing Colors and Palettes. *Journal of Statistical Software*. 2020;96(1):1–49. [doi:10.18637/jss.v096.i01](https://doi.org/10.18637/jss.v096.i01)\n9. Machado GM, Oliveira MM, Fernandes LAF. A physiologically-based model for simulation of color vision deficiency. *IEEE Transactions on Visualization and Computer Graphics*. 2009;15(6):1291–1298. [doi:10.1109/TVCG.2009.113](https://doi.org/10.1109/TVCG.2009.113)\n10. Nature Portfolio. [Preparing figures—specifications](https://research-figure-guide.nature.com/figures/preparing-figures-our-specifications/) and [building/exporting figure panels](https://research-figure-guide.nature.com/figures/building-and-exporting-figure-panels/)\n11. PLOS. [Figure guidelines](https://journals.plos.org/plosmedicine/s/figures)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "20bd3f4f31abcab7f921b83bc06f5947",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  },
  "prose_only_refreshes": [
    {
      "previous_source_hash": "bb19ae7b0f2db547e5c4d9749b62019c",
      "fenced_code_and_outputs_unchanged": true,
      "replacement_count": 1
    }
  ]
}
