{
  "hash": "5fff0ab6c040a56fab745057b1984ec4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 54 篇 · 孟德尔随机化：工具变量、水平多效性与敏感性分析\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**用 two-sample Mendelian randomization（MR）评估遗传预测的 `Bifidobacterium` 菌属丰度与炎症性肠病（IBD）风险，并系统审计工具强度、等位基因对齐、水平多效性、方向性和共定位。  \n> **额外数据：**MR 不能从 `otutab/taxonomy/metadata` 直接计算；必须另有暴露 GWAS 与结局 GWAS 的逐 SNP 汇总统计，至少包括 effect/other allele、beta、SE、P 值，最好还有 effect-allele frequency 与完整位点统计。  \n> **预计资源：**教学子集为 6 个候选 SNP、5 个对齐后工具；2,000 次 MR-PRESSO 模拟约 1–3 分钟，内存低于 1 GB。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n微生物组 MR 论文通常包含：SNP 暴露效应–结局效应散点图、多个 MR 估计器的森林图、leave-one-out 图，以及异质性/多效性诊断。它们试图回答：\n\n> 携带使某个微生物性状长期偏高的遗传变异者，结局风险是否也沿一致方向改变？这种关系能否用水平多效性、反向因果或共享关联位点解释？\n\n本例的暴露来自 MiBioGen 联盟 24 个队列的菌群 GWAS，选取 `genus.Bifidobacterium.id.436`；结局来自 de Lange 等人的 IBD GWAS（GCST004131，25,042 病例、34,915 对照）。[MiBioGen 论文](https://doi.org/10.1038/s41588-020-00763-1)、[IBD GWAS 论文](https://doi.org/10.1038/ng.3760)、[MiBioGen 官方汇总文件](https://molgenis26.gcc.rug.nl/downloads/MiBioGen/MBG.allHits.p1e4.txt)和[NHGRI-EBI GWAS Catalog](https://www.ebi.ac.uk/gwas/)提供来源。\n\n为了让单篇可运行，这里冻结 MiBioGen P < 5×10^-6、且在结局 API 中可取到的 6 个跨染色体候选位点。**一条染色体取一个 SNP 只能保证它们不在同一染色体，并不替代与暴露祖源匹配的 LD clumping。** 因此这是用于演示全流程的审计型分析，不是可直接投稿的最终工具集。\n\n::: {.callout-important title=\"MR 不是“有遗传数据就自动因果”\"}\nMR 的因果解释依赖三个不可由一次回归完全验证的假设：工具与暴露相关；工具不受暴露–结局混杂影响；工具只经暴露影响结局。菌群 GWAS 的弱工具、祖源差异、菌定义不一致、水平多效性和宿主位点共享尤其容易破坏这些条件。\n:::\n\n## 理论：三项工具变量假设 {#sec-theory}\n\n对工具 SNP (G_j)、微生物暴露 (X) 和结局 (Y)，Wald ratio 为：\n\n\\[\n\\hat\\beta_{MR,j}=\\frac{\\hat\\beta_{Y G,j}}{\\hat\\beta_{X G,j}}.\n\\]\n\nIVW（inverse-variance weighted）将多个 ratio 按精度合并。它依赖：\n\n1. **Relevance（相关性）**：(G\\) 能预测 (X\\)。常用近似 (F=(\\beta_X/SE_X)^2\\)，但 F > 10 只是经验筛查，不是强工具保证。\n2. **Independence（独立性）**：(G\\) 与 (X-Y\\) 混杂因素独立；人群分层、家系结构和择偶可破坏它。\n3. **Exclusion restriction（排除限制）**：(G\\) 不经 (X\\) 之外的路径影响 (Y\\)。这正是水平多效性的核心风险。\n\n<details>\n<summary><strong>深入：不同敏感性估计器保护什么</strong></summary>\n\n- **IVW**：在所有工具有效，或无方向性多效性时效率高；异质性提示 ratio 不一致。\n- **MR-Egger**：截距检验平均方向性多效性，斜率在 InSIDE 假设下可较稳健，但工具少时功效极低且易受弱工具影响。\n- **Weighted median**：当至少一半权重来自有效工具时可一致。\n- **Mode estimators**：假设最大的一簇相似 ratio 来自有效工具，通常区间较宽。\n- **MR-PRESSO**：寻找异常多效性工具并比较校正前后结果；没有检测到 outlier 不等于没有多效性。\n\n所有方法都可能在共同假设同时失败时一致地给出错误答案。敏感性分析的价值是压力测试，不是“多数投票即真”。\n\n</details>\n\n### 微生物 MR 的专属审计\n\n- 暴露 GWAS 中的“属”可能由不同 16S 区域、分类库、相对丰度变换和 cohort-specific prevalence 定义；\n- 暴露 beta 的一单位到底代表标准化丰度、presence/absence 还是秩正态值，决定效应量如何解释；\n- 两个 GWAS 的祖源、样本重叠和协变量策略影响偏倚；\n- 同一宿主位点同时关联菌和 IBD，不代表由菌介导；需要 locus colocalisation 区分共享因果变异与 LD 中的两个信号。\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、下载公开汇总统计和定义作图函数</strong></summary>\n\n首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"remotes\", \"jsonlite\", \"digest\", \"ggplot2\", \"ggrepel\", \"patchwork\",\n  \"scales\", \"svglite\", \"ragg\"\n))\nremotes::install_github(\"MRCIEU/TwoSampleMR@v0.6.6\")\nremotes::install_github(\"rondolab/MR-PRESSO\")\n```\n:::\n\n\n下面从 MiBioGen 官方文件筛选预先指定的候选 SNP，并从 GWAS Catalog summary-statistics API 取得 GCST004131 的对齐记录。原始 API JSON 应保留，以便将来审计接口内容变化。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmibiogen_path <- \"data/raw/MBG.allHits.p1e4.txt\"\nmibiogen_url <- \"https://molgenis26.gcc.rug.nl/downloads/MiBioGen/MBG.allHits.p1e4.txt\"\nexpected_sha <- \"37001a83d060596fe0b97b63d6a397f01f43a29add2925d406916b7a50b5883e\"\nraw_api <- \"data/raw/mr-mibiogen\"\nout_dir <- \"data/small/mr-mibiogen\"\ndir.create(dirname(mibiogen_path), recursive = TRUE, showWarnings = FALSE)\ndir.create(raw_api, recursive = TRUE, showWarnings = FALSE)\ndir.create(out_dir, recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(mibiogen_path)) download.file(mibiogen_url, mibiogen_path, mode = \"wb\")\nstopifnot(identical(\n  digest::digest(mibiogen_path, algo = \"sha256\", file = TRUE), expected_sha\n))\n\nexposure_id <- \"genus.Bifidobacterium.id.436\"\noutcome_id <- \"GCST004131\"\nrsids <- c(\"rs182549\", \"rs73797465\", \"rs857444\", \"rs10841473\", \"rs7322849\", \"rs75344046\")\nmbg <- read.delim(mibiogen_path, check.names = FALSE)\nx <- mbg[mbg$bac == exposure_id & mbg$rsID %in% rsids, ]\nx <- x[match(rsids, x$rsID), ]\nstopifnot(nrow(x) == 6, all(x$P.weightedSumZ < 5e-6), !anyDuplicated(x$chr))\nexposure <- data.frame(\n  SNP = x$rsID, exposure = \"Bifidobacterium genus abundance\",\n  id.exposure = exposure_id,\n  chr.exposure = x$chr, pos.exposure = x$bp,\n  effect_allele.exposure = toupper(x$eff.allele),\n  other_allele.exposure = toupper(x$ref.allele),\n  beta.exposure = x$beta, se.exposure = x$SE,\n  pval.exposure = x$P.weightedSumZ, eaf.exposure = NA_real_,\n  samplesize.exposure = x$N, ncohorts.exposure = x$Ncohorts,\n  check.names = FALSE\n)\nexposure$FStatistic <- (exposure$beta.exposure / exposure$se.exposure)^2\n\npriority <- c(`10` = 1, `5` = 2, `12` = 3, `11` = 4, `6` = 5, `13` = 6)\nget_outcome <- function(rsid) {\n  url <- paste0(\n    \"https://www.ebi.ac.uk/gwas/summary-statistics/api/associations/\",\n    rsid, \"?study_accession=\", outcome_id, \"&reveal=all\"\n  )\n  cache <- file.path(raw_api, paste0(outcome_id, \"-\", rsid, \".json\"))\n  if (!file.exists(cache)) download.file(url, cache, mode = \"wb\",\n                                        headers = \"User-Agent: microbiome-best-practices/1.0\")\n  payload <- jsonlite::read_json(cache, simplifyVector = FALSE)\n  rows <- payload[[\"_embedded\"]][[\"associations\"]]\n  usable <- Filter(function(z) {\n    identical(z$study_accession, outcome_id) &&\n      !is.null(z$hm_effect_allele) && !is.null(z$hm_other_allele) &&\n      !is.null(z$hm_beta) && !is.null(z$standard_error)\n  }, rows)\n  rank <- vapply(usable, function(z) priority[as.character(z$hm_code)], numeric(1))\n  z <- usable[[which.min(rank)]]\n  data.frame(\n    SNP = rsid, outcome = \"Inflammatory bowel disease\", id.outcome = outcome_id,\n    chr.outcome = z$chromosome, pos.outcome = z$base_pair_location,\n    effect_allele.outcome = toupper(z$hm_effect_allele),\n    other_allele.outcome = toupper(z$hm_other_allele),\n    beta.outcome = z$hm_beta, se.outcome = z$standard_error,\n    pval.outcome = z$p_value, samplesize.outcome = 59957,\n    ncase.outcome = 25042, ncontrol.outcome = 34915,\n    eaf.outcome = NA_real_, check.names = FALSE\n  )\n}\noutcome <- do.call(rbind, lapply(rsids, get_outcome))\nwrite.table(exposure, file.path(out_dir, \"exposure.tsv\"), sep = \"\\t\",\n            quote = FALSE, row.names = FALSE, na = \"\")\nwrite.table(outcome, file.path(out_dir, \"outcome.tsv\"), sep = \"\\t\",\n            quote = FALSE, row.names = FALSE, na = \"\")\n```\n:::\n\n\n出版级作图函数直接内联：\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.libPaths(c(\".r-lib\", .libPaths()))\nlibrary(TwoSampleMR)\nlibrary(MRPRESSO)\nlibrary(ggplot2)\nlibrary(ggrepel)\nlibrary(patchwork)\n\nset.seed(20260754)\nfont_pub <- \"DejaVu Sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(colour = \"#E6E6E6\", linewidth = 0.25),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      legend.position = \"top\", legend.key = ggplot2::element_blank()\n    )\n}\nsave_pub <- function(plot, file_base, width = 180, height = 115,\n                     units = \"mm\", dpi = 600) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(paste0(file_base, \".pdf\"), plot, width = width,\n                  height = height, units = units,\n                  device = grDevices::cairo_pdf, family = font_pub, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".svg\"), plot, width = width,\n                  height = height, units = units, device = svglite::svglite,\n                  bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".png\"), plot, width = width,\n                  height = height, units = units, dpi = dpi,\n                  device = ragg::agg_png, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".tiff\"), plot, width = width,\n                  height = height, units = units, dpi = dpi,\n                  device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\")\n  invisible(plot)\n}\n```\n:::\n\n\n整套项目可使用内容相同的 `R/theme_pub.R`；单篇复制时保留以上函数。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取并审计暴露/结局汇总统计\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase <- \"data/small/mr-mibiogen\"\nexposure <- read.delim(\n  file.path(base, \"exposure.tsv\"), check.names = FALSE, stringsAsFactors = FALSE\n)\noutcome <- read.delim(\n  file.path(base, \"outcome.tsv\"), check.names = FALSE, stringsAsFactors = FALSE\n)\nstopifnot(\n  nrow(exposure) == 6,\n  identical(exposure$SNP, outcome$SNP),\n  length(unique(exposure$chr.exposure)) == nrow(exposure),\n  all(exposure$FStatistic > 10)\n)\nexposure\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SNP                        exposure                  id.exposure\n1   rs182549 Bifidobacterium genus abundance genus.Bifidobacterium.id.436\n2 rs73797465 Bifidobacterium genus abundance genus.Bifidobacterium.id.436\n3   rs857444 Bifidobacterium genus abundance genus.Bifidobacterium.id.436\n4 rs10841473 Bifidobacterium genus abundance genus.Bifidobacterium.id.436\n5  rs7322849 Bifidobacterium genus abundance genus.Bifidobacterium.id.436\n6 rs75344046 Bifidobacterium genus abundance genus.Bifidobacterium.id.436\n  chr.exposure pos.exposure effect_allele.exposure other_allele.exposure\n1            2    136616754                      C                     T\n2            5    142793467                      T                     G\n3            6     14617591                      C                     T\n4           12     20378911                      G                     C\n5           13    112859829                      T                     C\n6           21     31861790                      C                     T\n  beta.exposure se.exposure pval.exposure eaf.exposure samplesize.exposure\n1    0.11970350  0.01272937  1.278216e-20           NA               14778\n2   -0.09535663  0.02092365  4.381619e-06           NA               14666\n3    0.05582344  0.01212192  3.570966e-06           NA               14777\n4   -0.06242065  0.01294385  1.645220e-06           NA               14777\n5    0.11242845  0.02018126  1.083679e-08           NA               14778\n6    0.23235409  0.05059787  4.863541e-06           NA                3856\n  ncohorts.exposure FStatistic\n1                24   88.42999\n2                23   20.76954\n3                24   21.20753\n4                24   23.25572\n5                24   31.03529\n6                 6   21.08804\n```\n\n\n:::\n\n```{.r .cell-code}\noutcome\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SNP                    outcome id.outcome chr.outcome pos.outcome\n1   rs182549 Inflammatory bowel disease GCST004131           2   135859184\n2 rs73797465 Inflammatory bowel disease GCST004131           5   143413902\n3   rs857444 Inflammatory bowel disease GCST004131           6    14617360\n4 rs10841473 Inflammatory bowel disease GCST004131          12    20225977\n5  rs7322849 Inflammatory bowel disease GCST004131          13   112205515\n6 rs75344046 Inflammatory bowel disease GCST004131          21    30489472\n  effect_allele.outcome other_allele.outcome beta.outcome se.outcome\n1                     T                    C      -0.0135     0.0148\n2                     T                    G       0.0201     0.0265\n3                     C                    T      -0.0177     0.0131\n4                     G                    C      -0.0074     0.0144\n5                     T                    C       0.0410     0.0247\n6                     C                    T      -0.0423     0.0326\n  pval.outcome samplesize.outcome ncase.outcome ncontrol.outcome eaf.outcome\n1      0.36080              59957         25042            34915          NA\n2      0.44890              59957         25042            34915          NA\n3      0.17700              59957         25042            34915          NA\n4      0.60560              59957         25042            34915          NA\n5      0.09639              59957         25042            34915          NA\n6      0.19440              59957         25042            34915          NA\n```\n\n\n:::\n:::\n\n\n候选工具的最小近似 F = 20.77，但最弱位点仍只达到暴露 GWAS 的 suggestive threshold，而非传统 genome-wide significance。菌群性状遗传解释度较低时，F 筛查不能替代弱工具稳健分析。\n\n### 2. 等位基因 harmonisation\n\n同一个 SNP 在两份 GWAS 中可能以相反 effect allele 报告。`harmonise_data(action = 2)` 对齐方向，并在缺少 allele frequency 时删除不能可靠判向的 palindromic SNP。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nharmonised <- TwoSampleMR::harmonise_data(exposure, outcome, action = 2)\nharmonisation_ledger <- harmonised[, c(\n  \"SNP\", \"effect_allele.exposure\", \"other_allele.exposure\",\n  \"effect_allele.outcome\", \"other_allele.outcome\",\n  \"beta.exposure\", \"beta.outcome\", \"palindromic\", \"ambiguous\",\n  \"mr_keep\", \"remove\", \"action\"\n)]\nharmonisation_ledger\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SNP effect_allele.exposure other_allele.exposure effect_allele.outcome\n1 rs10841473                      G                     C                     G\n2   rs182549                      C                     T                     C\n3  rs7322849                      T                     C                     T\n4 rs73797465                      T                     G                     T\n5 rs75344046                      C                     T                     C\n6   rs857444                      C                     T                     C\n  other_allele.outcome beta.exposure beta.outcome palindromic ambiguous mr_keep\n1                    C   -0.06242065      -0.0074        TRUE      TRUE   FALSE\n2                    T    0.11970350       0.0135       FALSE     FALSE    TRUE\n3                    C    0.11242845       0.0410       FALSE     FALSE    TRUE\n4                    G   -0.09535663       0.0201       FALSE     FALSE    TRUE\n5                    T    0.23235409      -0.0423       FALSE     FALSE    TRUE\n6                    T    0.05582344      -0.0177       FALSE     FALSE    TRUE\n  remove action\n1  FALSE      2\n2  FALSE      2\n3  FALSE      2\n4  FALSE      2\n5  FALSE      2\n6  FALSE      2\n```\n\n\n:::\n\n```{.r .cell-code}\nanalysis_data <- harmonised[harmonised$mr_keep, , drop = FALSE]\nstopifnot(nrow(analysis_data) == 5)\n```\n:::\n\n\n`rs10841473` 是 C/G palindromic SNP，且两份紧凑表没有 effect-allele frequency，无法判断 strand，因而删除。不能为了增加工具数而强行保留。\n\n### 3. 主估计与稳健估计器\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmethods <- c(\n  \"mr_ivw\", \"mr_egger_regression\", \"mr_weighted_median\",\n  \"mr_simple_mode\", \"mr_weighted_mode\"\n)\nset.seed(20260754)\nmr_results <- TwoSampleMR::mr(analysis_data, method_list = methods)\nmr_results$Lower <- mr_results$b - qnorm(0.975) * mr_results$se\nmr_results$Upper <- mr_results$b + qnorm(0.975) * mr_results$se\nmr_results$OR <- exp(mr_results$b)\nmr_results$ORLower <- exp(mr_results$Lower)\nmr_results$ORUpper <- exp(mr_results$Upper)\nmr_results[, c(\"method\", \"nsnp\", \"b\", \"se\", \"pval\", \"Lower\", \"Upper\", \"OR\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     method nsnp           b        se      pval      Lower\n1 Inverse variance weighted    5 -0.01667419 0.1065087 0.8755976 -0.2254274\n2                  MR Egger    5  0.04637394 0.2890186 0.8827197 -0.5200922\n3           Weighted median    5 -0.03834782 0.1011232 0.7045254 -0.2365457\n4               Simple mode    5 -0.22709201 0.1923468 0.3031557 -0.6040848\n5             Weighted mode    5 -0.18694887 0.1343972 0.2365998 -0.4503626\n       Upper        OR\n1 0.19207898 0.9834641\n2 0.61284007 1.0474660\n3 0.15985003 0.9623781\n4 0.14990075 0.7968475\n5 0.07646485 0.8294861\n```\n\n\n:::\n:::\n\n\nIVW 估计为 −0.0167（SE = 0.1065，P = 0.876），对应 OR = 0.984（95% CI 0.798–1.212）。MR-Egger、weighted median 和两种 mode 的区间也均包含零。这里的“每单位更高 abundance”沿用 MiBioGen 暴露标度，不能写成“每增加 1% 相对丰度”。\n\n### 4. 散点图：每个 SNP 的方向与方法斜率\n\n\n::: {.cell}\n\n```{.r .cell-code}\nivw <- mr_results[mr_results$method == \"Inverse variance weighted\", ]\negger <- mr_results[mr_results$method == \"MR Egger\", ]\nmedian <- mr_results[mr_results$method == \"Weighted median\", ]\negger_intercept <- TwoSampleMR::mr_pleiotropy_test(analysis_data)\nline_data <- data.frame(\n  Method = c(\"IVW\", \"MR Egger\", \"Weighted median\"),\n  Intercept = c(0, egger_intercept$egger_intercept, 0),\n  Slope = c(ivw$b, egger$b, median$b)\n)\nmethod_colours <- c(\n  IVW = pal_pub[[\"blue\"]],\n  `MR Egger` = pal_pub[[\"vermillion\"]],\n  `Weighted median` = pal_pub[[\"green\"]]\n)\np_scatter <- ggplot(\n  analysis_data, aes(beta.exposure, beta.outcome, label = SNP)\n) +\n  geom_errorbar(\n    aes(ymin = beta.outcome - 1.96 * se.outcome,\n        ymax = beta.outcome + 1.96 * se.outcome),\n    width = 0, colour = \"#888888\"\n  ) +\n  geom_errorbarh(\n    aes(xmin = beta.exposure - 1.96 * se.exposure,\n        xmax = beta.exposure + 1.96 * se.exposure),\n    height = 0, colour = \"#888888\"\n  ) +\n  geom_point(size = 2.3, colour = \"#202020\") +\n  ggrepel::geom_text_repel(\n    seed = 20260754, size = 2.8, max.overlaps = Inf,\n    min.segment.length = 0, box.padding = 0.35, point.padding = 0.25\n  ) +\n  geom_abline(\n    data = line_data,\n    aes(intercept = Intercept, slope = Slope, colour = Method), linewidth = 0.9\n  ) +\n  scale_colour_manual(values = method_colours) +\n  coord_cartesian(xlim = range(analysis_data$beta.exposure) * 1.15) +\n  labs(\n    title = \"Harmonised SNP effects do not share a stable causal slope\",\n    subtitle = \"Five non-ambiguous instruments; error bars are 95% confidence intervals\",\n    x = \"SNP effect on Bifidobacterium abundance\",\n    y = \"SNP effect on log-odds of IBD\", colour = \"MR method\"\n  ) + theme_pub(10)\np_scatter\n```\n\n::: {.cell-output-display}\n![](54-mendelian-randomization_files/figure-html/unnamed-chunk-7-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_scatter, \"figures/54-mendelian-randomization/54-1-harmonised-scatter\",\n         height = 120)\n```\n:::\n\n\n### 5. 森林图：不要只报告 IVW\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmr_results$method <- factor(\n  mr_results$method,\n  levels = rev(c(\n    \"Inverse variance weighted\", \"MR Egger\", \"Weighted median\",\n    \"Simple mode\", \"Weighted mode\"\n  ))\n)\np_methods <- ggplot(mr_results, aes(b, method)) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_errorbarh(aes(xmin = Lower, xmax = Upper), height = 0,\n                 colour = pal_pub[[\"grey\"]]) +\n  geom_point(aes(colour = method == \"Inverse variance weighted\"), size = 2.5) +\n  scale_colour_manual(values = c(\n    `FALSE` = pal_pub[[\"grey\"]], `TRUE` = pal_pub[[\"blue\"]]\n  )) +\n  labs(\n    title = \"Sensitivity estimators all include the null\",\n    subtitle = \"Effects are log-odds of IBD per unit higher genetically predicted abundance\",\n    x = \"MR estimate (95% confidence interval)\", y = NULL\n  ) + theme_pub(10) + theme(legend.position = \"none\")\np_methods\n```\n\n::: {.cell-output-display}\n![](54-mendelian-randomization_files/figure-html/unnamed-chunk-8-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_methods, \"figures/54-mendelian-randomization/54-2-method-forest\",\n         height = 110)\n```\n:::\n\n\n## 审计与升级 {#sec-audit}\n\n### 异质性、Egger 截距与 MR-PRESSO\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheterogeneity <- TwoSampleMR::mr_heterogeneity(analysis_data)\negger_intercept <- TwoSampleMR::mr_pleiotropy_test(analysis_data)\nheterogeneity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   id.exposure id.outcome                    outcome\n1 genus.Bifidobacterium.id.436 GCST004131 Inflammatory bowel disease\n2 genus.Bifidobacterium.id.436 GCST004131 Inflammatory bowel disease\n                         exposure                    method        Q Q_df\n1 Bifidobacterium genus abundance                  MR Egger 7.480877    3\n2 Bifidobacterium genus abundance Inverse variance weighted 7.625177    4\n      Q_pval\n1 0.05805185\n2 0.10631453\n```\n\n\n:::\n\n```{.r .cell-code}\negger_intercept\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   id.exposure id.outcome                    outcome\n1 genus.Bifidobacterium.id.436 GCST004131 Inflammatory bowel disease\n                         exposure egger_intercept         se      pval\n1 Bifidobacterium genus abundance    -0.007511445 0.03122526 0.8254008\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(20260754)\npresso <- MRPRESSO::mr_presso(\n  BetaOutcome = \"beta.outcome\", BetaExposure = \"beta.exposure\",\n  SdOutcome = \"se.outcome\", SdExposure = \"se.exposure\",\n  OUTLIERtest = TRUE, DISTORTIONtest = TRUE,\n  data = analysis_data, NbDistribution = 2000, SignifThreshold = 0.05\n)\npresso[[\"Main MR results\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Exposure       MR Analysis Causal Estimate        Sd     T-stat\n1 beta.exposure               Raw     -0.01667419 0.1065087 -0.1565524\n2 beta.exposure Outlier-corrected              NA        NA         NA\n    P-value\n1 0.8831814\n2        NA\n```\n\n\n:::\n\n```{.r .cell-code}\npresso[[\"MR-PRESSO results\"]][[\"Global Test\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$RSSobs\n[1] 12.34602\n\n$Pvalue\n[1] 0.183\n```\n\n\n:::\n:::\n\n\nIVW Cochran's Q P = 0.106，Egger intercept = −0.0075（P = 0.825），MR-PRESSO global P = 0.183，未检测到 outlier。只有 5 个工具时这些检验功效很低，因此结果应写作“未发现多效性信号”，而不是“证明不存在多效性”。\n\n### Leave-one-out 只能发现单点主导\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleave_one_out <- TwoSampleMR::mr_leaveoneout(analysis_data)\nleave_one_out$Lower <- leave_one_out$b - qnorm(0.975) * leave_one_out$se\nleave_one_out$Upper <- leave_one_out$b + qnorm(0.975) * leave_one_out$se\nleave_one_out$Label <- ifelse(\n  leave_one_out$SNP == \"All\", \"All instruments\", paste(\"Remove\", leave_one_out$SNP)\n)\nleave_one_out$Label <- factor(leave_one_out$Label, levels = rev(leave_one_out$Label))\np_loo <- ggplot(leave_one_out, aes(b, Label)) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_errorbarh(aes(xmin = Lower, xmax = Upper), height = 0,\n                 colour = pal_pub[[\"grey\"]]) +\n  geom_point(aes(colour = SNP == \"All\"), size = 2.3) +\n  scale_colour_manual(values = c(\n    `FALSE` = pal_pub[[\"orange\"]], `TRUE` = pal_pub[[\"blue\"]]\n  )) +\n  labs(\n    title = \"Leave-one-out estimates remain imprecise\",\n    subtitle = \"A stable sign alone would not overcome weak instrument design or pleiotropy\",\n    x = \"IVW estimate after exclusion (95% confidence interval)\", y = NULL\n  ) + theme_pub(10) + theme(legend.position = \"none\")\np_loo\n```\n\n::: {.cell-output-display}\n![](54-mendelian-randomization_files/figure-html/unnamed-chunk-10-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_loo, \"figures/54-mendelian-randomization/54-3-leave-one-out\",\n         height = 110)\n```\n:::\n\n\n### 把无法完成的诊断也写进结果\n\n\n::: {.cell}\n\n```{.r .cell-code}\npresso_global_p <- presso[[\"MR-PRESSO results\"]][[\"Global Test\"]]$Pvalue\nassumption_audit <- data.frame(\n  Assumption = c(\n    \"Instrument strength\", \"LD independence\", \"Allele harmonisation\",\n    \"Directional pleiotropy\", \"Outlier pleiotropy\", \"Steiger directionality\",\n    \"Population overlap\", \"Locus colocalisation\"\n  ),\n  Status = c(\n    \"Supported\", \"Partial\", \"Partial\", \"Low power\",\n    \"No signal\", \"Unavailable\", \"Unresolved\", \"Unavailable\"\n  ),\n  Evidence = c(\n    sprintf(\"Minimum F = %.1f\", min(exposure$FStatistic)),\n    \"One SNP per chromosome;\\nno ancestry-matched clumping\",\n    sprintf(\"%d of %d SNPs retained\", nrow(analysis_data), nrow(harmonised)),\n    sprintf(\"Egger intercept P = %.3f\", egger_intercept$pval),\n    sprintf(\"MR-PRESSO global P = %.3f\", presso_global_p),\n    \"Effect-allele frequencies absent\",\n    \"Cohort overlap unresolved\\nfrom compact files\",\n    \"Top-hit file lacks full\\nlocus statistics\"\n  )\n)\n\nstrength <- merge(\n  exposure[, c(\"SNP\", \"FStatistic\")],\n  harmonisation_ledger[, c(\"SNP\", \"mr_keep\")],\n  by = \"SNP\", all.x = TRUE, sort = FALSE\n)\nstrength$Status <- ifelse(strength$mr_keep, \"Retained\", \"Dropped: palindromic\")\np_strength <- ggplot(strength, aes(FStatistic, reorder(SNP, FStatistic), colour = Status)) +\n  geom_vline(xintercept = 10, linetype = 2, colour = pal_pub[[\"vermillion\"]]) +\n  geom_segment(aes(x = 0, xend = FStatistic, yend = reorder(SNP, FStatistic)),\n               linewidth = 0.7) +\n  geom_point(size = 2.4) +\n  scale_colour_manual(values = c(\n    Retained = pal_pub[[\"blue\"]],\n    `Dropped: palindromic` = pal_pub[[\"orange\"]]\n  )) +\n  labs(\n    title = \"A. Candidate instruments\", subtitle = \"The dashed line marks F = 10\",\n    x = \"Approximate F statistic\", y = NULL, colour = \"Harmonisation\"\n  ) + theme_pub(9)\n\nassumption_audit$Assumption <- factor(\n  assumption_audit$Assumption, levels = rev(assumption_audit$Assumption)\n)\nstatus_colours <- c(\n  Supported = pal_pub[[\"green\"]], Partial = pal_pub[[\"orange\"]],\n  `No signal` = pal_pub[[\"sky\"]], `Low power` = pal_pub[[\"purple\"]],\n  Unavailable = pal_pub[[\"vermillion\"]], Unresolved = pal_pub[[\"grey\"]]\n)\np_assumptions <- ggplot(assumption_audit, aes(1, Assumption, fill = Status)) +\n  geom_tile(width = 0.28, height = 0.7, colour = \"white\") +\n  geom_text(aes(x = 1.2, label = Evidence), hjust = 0, size = 2.35,\n            lineheight = 0.9, colour = \"#252525\") +\n  scale_fill_manual(values = status_colours) +\n  coord_cartesian(xlim = c(0.82, 2.55), clip = \"off\") +\n  labs(title = \"B. Assumption audit\", x = NULL, y = NULL, fill = \"Status\") +\n  theme_pub(8) +\n  theme(\n    axis.text.x = element_blank(), axis.ticks.x = element_blank(),\n    panel.grid = element_blank(), plot.margin = margin(5, 85, 5, 5)\n  )\np_audit <- p_strength + p_assumptions +\n  patchwork::plot_layout(widths = c(0.85, 1.5), guides = \"collect\") &\n  theme(legend.position = \"bottom\")\np_audit\n```\n\n::: {.cell-output-display}\n![](54-mendelian-randomization_files/figure-html/unnamed-chunk-11-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_audit, \"figures/54-mendelian-randomization/54-4-assumption-audit\",\n         height = 130)\n```\n:::\n\n\n本教学子集没有 effect-allele frequency，不能可靠计算 exposure/outcome explained variance，因此不伪造 Steiger directionality；暴露仅有 top-hit 记录，也无法做位点共定位。样本重叠不能从紧凑文件排除。把这些标成 unavailable/unresolved 比输出一个看似齐全的绿色勾选表更重要。\n\n### 今天可投稿分析还要升级什么\n\n- 用与暴露 GWAS 祖源匹配的 reference panel 做 LD clumping，并报告阈值、窗口和 panel；\n- 获取完整暴露与结局 summary statistics，做 Steiger、双向 MR 和关键位点 colocalisation；\n- 报告暴露 GWAS 的统一分类/变换、工具解释度、conditional F 和样本重叠；\n- 检查 SNP 与 BMI、饮食、药物、免疫表型等潜在多效性通路；\n- 在独立 GWAS、不同 16S 区域或 shotgun taxonomic definition 中复现；\n- 若暴露是多个相关菌，考虑 multivariable MR，但先证明工具对各暴露有足够条件强度。\n\n::: {.callout-caution title=\"常见坑：MR 最危险的“全绿结果”\"}\n- 用 P < 1×10^-5 的弱工具，却只写所有 F > 10；  \n- 把“一染色体一个 SNP”写成已完成 LD clumping；  \n- palindromic SNP 无 EAF 仍强行对齐；  \n- Egger/PRESSO P > 0.05 就宣称不存在水平多效性；  \n- 两份 GWAS 中同名菌属的测量定义不同，却按同一 exposure 解释；  \n- 没做 colocalisation，就把共享区域写成“菌介导宿主遗传效应”；  \n- 空结果写成“证明该菌对疾病无因果作用”。宽区间通常只表示数据还不能排除有意义的正负效应。\n:::\n\n## 出版级美化 {#sec-publication}\n\nMR 主图建议用“散点 + 方法森林图”，把 leave-one-out 与 assumption audit 放补充材料。森林图必须有零参考线、方法名、SNP 数和 95% CI；二元结局可补充 OR，但不要把暴露标度误写成百分比。\n\n图注应同时说明：候选/保留 SNP 数、harmonisation action、工具选择与 clumping、效应单位、样本量以及哪些诊断不可得。`save_pub()` 已输出 PDF/SVG 和 600 ppi PNG/TIFF，图中文字全部为英文。\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> We performed two-sample Mendelian randomisation using summary associations for MiBioGen genus-level *Bifidobacterium* abundance and inflammatory bowel disease (GCST004131; 25,042 cases and 34,915 controls). Candidate instruments were selected at P < 5×10^-6. For this compact teaching analysis, one outcome-available variant per chromosome was retained before harmonisation; this cross-chromosome rule was not considered a substitute for ancestry-matched LD clumping. Effect alleles were harmonised using `TwoSampleMR` with action 2, and one palindromic variant without allele-frequency information was excluded. The inverse-variance weighted estimator was primary; MR-Egger, weighted-median, simple-mode and weighted-mode estimators were sensitivity analyses. Heterogeneity, the MR-Egger intercept, leave-one-out estimates and MR-PRESSO with 2,000 fixed-seed simulations were evaluated. Steiger directionality and locus colocalisation were not estimable because effect-allele frequencies and full locus-level exposure statistics, respectively, were unavailable. Results were therefore treated as a limited teaching analysis rather than definitive causal evidence.\n\n正式论文必须把上述“cross-chromosome rule”替换为真正执行的 clumping 参数，并补充 population、exposure scale、software version、sample overlap、Steiger、bidirectional MR、colocalisation 和数据 accession。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n你的 16S 三件套只能定义表型和发现问题，不能充当 MR 暴露 GWAS。还需两张独立汇总统计表：\n\n| 字段 | 暴露表 | 结局表 |\n|---|---|---|\n| 变异 ID | `SNP` | `SNP` |\n| 等位基因 | `effect_allele.exposure`, `other_allele.exposure` | 对应 `.outcome` 字段 |\n| 效应与标准误 | `beta.exposure`, `se.exposure` | `beta.outcome`, `se.outcome` |\n| P 值 | `pval.exposure` | `pval.outcome` |\n| 推荐补充 | EAF、N、祖源、坐标/build | EAF、病例/对照 N、祖源、坐标/build |\n\n先统一 genome build 与 variant ID，再做 ancestry-matched clumping，最后 harmonise。若菌属 GWAS 与你的 16S 研究在分类层级、扩增区域和变换上不一致，只能把 MR 当作外部三角验证，不能声称它直接验证了你队列中的具体 ASV。\n\n## 参考 {#sec-references}\n\n- Kurilshikov A, et al. Large-scale association analyses identify host factors influencing human gut microbiome composition. *Nature Genetics*. 2021;53:156–165. [doi:10.1038/s41588-020-00763-1](https://doi.org/10.1038/s41588-020-00763-1)\n- de Lange KM, et al. Genome-wide association study implicates immune activation of multiple integrin genes in inflammatory bowel disease. *Nature Genetics*. 2017;49:256–261. [doi:10.1038/ng.3760](https://doi.org/10.1038/ng.3760)\n- Hemani G, et al. The MR-Base platform supports systematic causal inference across the human phenome. *eLife*. 2018;7:e34408. [doi:10.7554/eLife.34408](https://doi.org/10.7554/eLife.34408)\n- Bowden J, Davey Smith G, Burgess S. Mendelian randomization with invalid instruments: effect estimation and bias detection through Egger regression. *International Journal of Epidemiology*. 2015;44:512–525. [doi:10.1093/ije/dyv080](https://doi.org/10.1093/ije/dyv080)\n- Verbanck M, et al. Detection of widespread horizontal pleiotropy in causal relationships inferred from Mendelian randomization. *Nature Genetics*. 2018;50:693–698. [doi:10.1038/s41588-018-0099-7](https://doi.org/10.1038/s41588-018-0099-7)\n- Burgess S, Thompson SG. *Mendelian Randomization: Methods for Using Genetic Variants in Causal Estimation*. Chapman & Hall/CRC; 2015.\n",
    "supporting": [
      "54-mendelian-randomization_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}