{
  "hash": "59a08fbe85b361016fbcfdd4a6c51425",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"生态位宽度、物种丰度分布与距离衰减\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**在同一真实 16S 数据集上分别估计 standardized Levins sample-use breadth、逐样本 rank-abundance distribution（RAD）模型与 Bray–Curtis geographic distance-decay，并把三类描述量的解释边界分开。  \n> **输入文件：**通用三件套 `data/small/otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`；距离衰减额外读取同一数据源的 `environment.tsv` 中 `Latitude`/`Longitude`。  \n> **预计资源：**13,628 个 OTU、90 个样本；90 × 5 个 RAD fits、999 次分层 Mantel permutation，通常 2–5 分钟、峰值内存低于 2 GB；四张图导出为 PDF/SVG/600 ppi PNG/LZW-TIFF。\n\n## 生态位、丰度分布与距离衰减回答不同尺度问题 {#sec-target}\n\n[Martiny et al. (2011)](https://doi.org/10.1073/pnas.1016308108)展示了 bacterial beta-diversity 的空间尺度依赖；[Hanson et al. (2012)](https://doi.org/10.1038/nrmicro2795)系统梳理了 selection、dispersal、drift 与 diversification 如何共同塑造微生物生物地理格局。以下分析在公开湿地 16S 数据上对照 breadth–occupancy、rank-abundance fit、within-region distance-decay 和 effect size。\n\n::: {.callout-important title=\"先给结论\"}\nLevins breadth、RAD 和 distance-decay 是三个不同层次的 pattern：taxon 在样本间分布得多均匀、单个样本内丰度怎样排序、不同地点的群落相似性怎样随距离变化。它们可以提出 generalist/specialist、dominance 与 dispersal/selection 假设，但任一张图都不能单独识别生态过程。\n:::\n\n本页使用 `microeco` 2.0.0 的真实中国湿地数据。CW、IW、TW 各 30 个样本，但三组覆盖的地理距离和环境范围不同；因此 distance-decay 以 **within-region** slope 为主，pooled 结果只作审计，避免把 region composition difference 当成连续空间衰减。\n\n## 三种宏生态图不能互相代替 {#sec-theory}\n\n### 1. standardized Levins breadth 是 sample-use evenness\n\n对 taxon $j$，令 $p_{ij}$ 为它在样本 $i$ 的相对丰度占该 taxon 在所有样本总相对丰度的比例。Levins breadth 为\n\n$$\nB_j = \\frac{1}{\\sum_i p_{ij}^2},\n$$\n\n并标准化为\n\n$$\nB_j^{\\ast}=\\frac{B_j-1}{S-1},\n$$\n\n其中 $S$ 是样本数。$B_j^{\\ast}$ 越接近 1，表示该 taxon 的相对丰度在样本间越均匀；越接近 0，表示集中于少数样本。\n\n这里称它为 **sample-use breadth**，不直接称“生理生态位宽度”。只有把 occurrence 与实测环境梯度、资源利用或实验 tolerances 连接起来，才能升级为 environmental niche inference。\n\n### 2. RAD 比较的是同一样本内的 abundance hierarchy\n\n每个样本把非零 OTU abundance 从高到低排序。本页用 `vegan::radfit()` 比较五个候选模型：broken-stick/null、preemption、lognormal、Zipf 与 Zipf–Mandelbrot。AIC 最小者只是这个候选集内的相对最佳近似；不同模型胜出不等于唯一生态机制成立。\n\n逐样本拟合保留 biological replicate。把 90 个样本先合并为一个 rank-abundance curve 会丢失 replicate variation，并把不同 library sizes 与 habitats 混在一起。\n\n### 3. distance-decay 要先定义空间尺度\n\nBray–Curtis similarity $S_{ij}=1-D_{ij}$ 与 Haversine geographic distance $G_{ij}$ 的 log–log 回归为\n\n$$\n\\log_{10}(S_{ij})=\\alpha+\\beta\\log_{10}(G_{ij}+1),\n$$\n\n负的 $\\beta$ 表示距离越远，群落越不相似。pairwise points 并不独立，因为同一样本参与多条 pair；因此 slope 用作 effect-size description，关联检验另用 sample-label permutation 的 Mantel statistic，并明确其限制。\n\n### 4. pooled slope 容易被 region separation 劫持\n\n如果 between-region pairs 同时具有更大距离和更低相似性，pooled regression 即使很陡，也不能说明每个 region 内都存在同样衰减。本页主图分面展示 CW、IW、TW 内部 pairs；pooled Mantel permutation 限制在 region blocks 内，并与三组独立结果一起报告。\n\n<details>\n<summary><strong>深入：为什么 breadth 与 occupancy 天然相关</strong></summary>\n\n一个只出现在少量样本的 taxon 不可能拥有很高的 sample-use evenness，因此 Levins breadth 与 occupancy 的正相关有数学约束。breadth–occupancy scatter 的价值在于识别“相同 occupancy 下异常集中或异常均匀”的 taxa，而不是把高相关本身当作 generalist–specialist 生态机制证据。\n\n</details>\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖并定义出版级作图函数</strong></summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"ggplot2\", \"ggrepel\", \"patchwork\", \"permute\", \"ragg\", \"readr\",\n  \"scales\", \"svglite\", \"systemfonts\", \"vegan\"\n))\n```\n:::\n\n\n整仓库使用者可改用 `source(\"R/theme_pub.R\")`；单篇复现直接运行下面定义：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(vegan)\n\nset.seed(20260740)\nfont_pub <- \"DejaVu Sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(colour = \"#1A1A1A\", linewidth = 0.3),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(), legend.position = \"top\"\n    )\n}\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot, width = width, height = height,\n    units = units, device = grDevices::cairo_pdf,\n    family = base_family, bg = \"white\"\n  )\n  if (write_svg) ggplot2::ggsave(\n    paste0(file_base, \".svg\"), plot, width = width, height = height,\n    units = units, device = svglite::svglite, bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_png, bg = \"white\"\n  )\n  if (write_tiff) ggplot2::ggsave(\n    paste0(file_base, \".tiff\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_tiff,\n    compression = \"lzw\", bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 从三件套读取，再对齐经纬度\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path, show_col_types = FALSE, progress = FALSE,\n    name_repair = \"minimal\", na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\notutab_raw <- read_keyed_tsv(\"data/small/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"data/small/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"data/small/metadata.tsv\")\nenvironment <- read_keyed_tsv(\"data/small/environment.tsv\")\notutab <- as.matrix(data.frame(\n  lapply(otutab_raw, as.integer), check.names = FALSE\n))\nrownames(otutab) <- rownames(otutab_raw)\nmetadata$Group <- factor(metadata$Group, levels = c(\"CW\", \"IW\", \"TW\"))\notutab <- otutab[, rownames(metadata), drop = FALSE]\nenvironment <- environment[rownames(metadata), , drop = FALSE]\n\nclean_taxon <- function(x) {\n  x <- sub(\"^[A-Za-z]__\", \"\", trimws(as.character(x)))\n  x[\n    is.na(x) | x == \"\" |\n      grepl(\"unclassified|unknown|unassigned|uncultured|metagenome\", x,\n            ignore.case = TRUE)\n  ] <- NA_character_\n  x\n}\nrank_names <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"\n)\ntaxonomy_clean <- as.data.frame(\n  lapply(taxonomy[rownames(otutab), rank_names], clean_taxon),\n  check.names = FALSE\n)\nrownames(taxonomy_clean) <- rownames(otutab)\ndisplay_taxon <- apply(\n  taxonomy_clean[, rev(rank_names), drop = FALSE], 1L,\n  function(x) {\n    value <- x[!is.na(x)][1L]\n    if (length(value)) value else \"Unclassified OTU\"\n  }\n)\nnames(display_taxon) <- rownames(taxonomy_clean)\n\nstopifnot(\n  nrow(otutab) == 13628L,\n  ncol(otutab) == 90L,\n  sum(otutab) == 1619670L,\n  identical(colnames(otutab), rownames(metadata)),\n  identical(rownames(environment), rownames(metadata)),\n  all(stats::complete.cases(environment[, c(\"Latitude\", \"Longitude\")]))\n)\n\nhead(otutab[, 1:5])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\nOTU_706   0  1  0  1   0\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(taxonomy[, rank_names])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\nOTU_706  k__Bacteria                     p__Actinobacteria\n                         Class               Order               Family\nOTU_4272            c__Bacilli       o__Bacillales                  f__\nOTU_236                    c__                 o__                  f__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__\nOTU_32                     c__                 o__                  f__\nOTU_706      c__Actinobacteria       o__Frankiales   f__Nakamurellaceae\n                  Genus Species\nOTU_4272            g__     s__\nOTU_236             g__     s__\nOTU_399             g__     s__\nOTU_1556            g__     s__\nOTU_32              g__     s__\nOTU_706  g__Nakamurella     s__\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(environment[, c(\"Latitude\", \"Longitude\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Latitude Longitude\nS1 52.96482  122.5635\nS2 52.94877  122.6109\nS3 52.94932  122.6099\nS4 52.94900  122.6104\nS5 52.95292  122.6057\nS6 52.95300  122.6123\n```\n\n\n:::\n:::\n\n\n### 2. standardized Levins sample-use breadth\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelative <- sweep(otutab, 2L, colSums(otutab), \"/\")\nprevalence <- rowMeans(otutab > 0)\ntotal_reads <- rowSums(otutab)\nbreadth_keep <- prevalence >= 0.05 & total_reads >= 100L\nbreadth_relative <- relative[breadth_keep, , drop = FALSE]\n\nsample_share <- sweep(\n  breadth_relative, 1L, rowSums(breadth_relative), \"/\"\n)\nlevins_b <- 1 / rowSums(sample_share^2)\nstandardized_b <- (levins_b - 1) / (ncol(otutab) - 1)\nbreadth_quantiles <- stats::quantile(\n  standardized_b, c(0.10, 0.90), names = FALSE\n)\nbreadth_ledger <- data.frame(\n  FeatureID = names(standardized_b),\n  DisplayTaxon = display_taxon[names(standardized_b)],\n  Prevalence = prevalence[names(standardized_b)],\n  TotalReads = total_reads[names(standardized_b)],\n  LevinsB = unname(levins_b),\n  StandardizedBreadth = unname(standardized_b),\n  BreadthClass = ifelse(\n    standardized_b <= breadth_quantiles[[1L]], \"Narrow decile\",\n    ifelse(\n      standardized_b >= breadth_quantiles[[2L]],\n      \"Broad decile\", \"Intermediate\"\n    )\n  ),\n  stringsAsFactors = FALSE\n)\nbreadth_occupancy_rho <- stats::cor(\n  breadth_ledger$StandardizedBreadth,\n  breadth_ledger$Prevalence,\n  method = \"spearman\"\n)\n\nstopifnot(\n  nrow(breadth_ledger) == 3208L,\n  all(breadth_ledger$StandardizedBreadth >= 0 &\n        breadth_ledger$StandardizedBreadth <= 1)\n)\nsummary(breadth_ledger$StandardizedBreadth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.0005788 0.0678290 0.1238397 0.1457250 0.1993611 0.5906111 \n```\n\n\n:::\n:::\n\n\n### 3. 每个样本独立拟合五类 RAD 模型\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrad_models <- c(\"Null\", \"Preemption\", \"Lognormal\", \"Zipf\", \"Mandelbrot\")\nrad_aic <- matrix(\n  NA_real_, nrow = ncol(otutab), ncol = length(rad_models),\n  dimnames = list(colnames(otutab), rad_models)\n)\nrad_warning_ledger <- data.frame(\n  SampleID = character(), Message = character(), stringsAsFactors = FALSE\n)\n\nfor (sample_id in colnames(otutab)) {\n  abundance <- otutab[, sample_id]\n  abundance <- abundance[abundance > 0]\n  fit <- withCallingHandlers(\n    vegan::radfit(abundance),\n    warning = function(warning_condition) {\n      warning_message <- conditionMessage(warning_condition)\n      warning_message <- if (\n        grepl(\"did not converge|算法没有聚合\", warning_message)\n      ) {\n        \"GLM did not converge\"\n      } else {\n        warning_message\n      }\n      rad_warning_ledger <<- rbind(\n        rad_warning_ledger,\n        data.frame(\n          SampleID = sample_id,\n          Message = warning_message,\n          stringsAsFactors = FALSE\n        )\n      )\n      invokeRestart(\"muffleWarning\")\n    }\n  )\n  rad_aic[sample_id, ] <- vapply(\n    fit$models, stats::AIC, numeric(1)\n  )[rad_models]\n}\nrad_winner <- rad_models[max.col(-rad_aic, ties.method = \"first\")]\nrad_delta_aic <- sweep(rad_aic, 1L, apply(rad_aic, 1L, min), \"-\")\nrad_aic_ledger <- data.frame(\n  SampleID = rep(rownames(rad_aic), times = ncol(rad_aic)),\n  Group = rep(as.character(metadata[rownames(rad_aic), \"Group\"]),\n              times = ncol(rad_aic)),\n  Model = rep(colnames(rad_aic), each = nrow(rad_aic)),\n  AIC = as.vector(rad_aic),\n  DeltaAIC = as.vector(rad_delta_aic),\n  stringsAsFactors = FALSE\n)\nrad_model_summary <- data.frame(\n  Model = rad_models,\n  WinningSamples = as.integer(table(factor(rad_winner, levels = rad_models))),\n  MedianDeltaAIC = apply(rad_delta_aic, 2L, stats::median),\n  stringsAsFactors = FALSE\n)\n\nsample_richness <- colSums(otutab > 0)\nrad_warning_samples <- unique(rad_warning_ledger$SampleID)\nrepresentative_candidates <- setdiff(\n  names(sample_richness), rad_warning_samples\n)\nrepresentative_sample <- representative_candidates[\n  which.min(abs(\n    sample_richness[representative_candidates] -\n      stats::median(sample_richness[representative_candidates])\n  ))\n]\nrepresentative_abundance <- otutab[, representative_sample]\nrepresentative_abundance <- representative_abundance[\n  representative_abundance > 0\n]\nrepresentative_fit <- suppressWarnings(\n  vegan::radfit(representative_abundance)\n)\nrepresentative_rad <- do.call(rbind, lapply(rad_models, function(model) {\n  data.frame(\n    Rank = seq_along(representative_fit$models[[model]]$fitted.values),\n    Abundance = as.numeric(\n      representative_fit$models[[model]]$fitted.values\n    ),\n    Model = model,\n    stringsAsFactors = FALSE\n  )\n}))\nrepresentative_observed <- data.frame(\n  Rank = seq_along(representative_fit$y),\n  Abundance = as.numeric(representative_fit$y)\n)\n\nstopifnot(\n  nrow(rad_aic_ledger) == 450L,\n  sum(rad_model_summary$WinningSamples) == 90L,\n  all(is.finite(rad_aic_ledger$AIC)),\n  representative_sample %in% rownames(metadata)\n)\nrad_model_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Model WinningSamples MedianDeltaAIC\nNull             Null              0     13316.2624\nPreemption Preemption              0     13396.3649\nLognormal   Lognormal              0      1427.4889\nZipf             Zipf             15       792.5678\nMandelbrot Mandelbrot             75         0.0000\n```\n\n\n:::\n\n```{.r .cell-code}\nrad_warning_ledger\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SampleID              Message\n1      S22 GLM did not converge\n2     S165 GLM did not converge\n3     S167 GLM did not converge\n```\n\n\n:::\n:::\n\n\n### 4. Haversine distance、within-region slope 与 Mantel audit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhaversine_km <- function(lat1, lon1, lat2, lon2) {\n  earth_radius <- 6371.0088\n  phi1 <- lat1 * pi / 180\n  phi2 <- lat2 * pi / 180\n  delta_phi <- (lat2 - lat1) * pi / 180\n  delta_lambda <- (lon2 - lon1) * pi / 180\n  a <- sin(delta_phi / 2)^2 +\n    cos(phi1) * cos(phi2) * sin(delta_lambda / 2)^2\n  2 * earth_radius * asin(pmin(1, sqrt(a)))\n}\nsample_ids <- rownames(metadata)\nsample_index <- seq_along(sample_ids)\ngeographic_matrix <- outer(\n  sample_index, sample_index,\n  Vectorize(function(i, j) {\n    haversine_km(\n      environment$Latitude[[i]], environment$Longitude[[i]],\n      environment$Latitude[[j]], environment$Longitude[[j]]\n    )\n  })\n)\ndimnames(geographic_matrix) <- list(sample_ids, sample_ids)\nbray_matrix <- as.matrix(vegan::vegdist(t(relative), method = \"bray\"))\n\npair_index <- which(upper.tri(bray_matrix), arr.ind = TRUE)\ndistance_pairs <- data.frame(\n  Sample1 = sample_ids[pair_index[, \"row\"]],\n  Sample2 = sample_ids[pair_index[, \"col\"]],\n  Group1 = as.character(metadata$Group[pair_index[, \"row\"]]),\n  Group2 = as.character(metadata$Group[pair_index[, \"col\"]]),\n  DistanceKm = geographic_matrix[pair_index],\n  BrayCurtis = bray_matrix[pair_index],\n  stringsAsFactors = FALSE\n)\ndistance_pairs$Similarity <- pmax(1 - distance_pairs$BrayCurtis, 1e-6)\ndistance_pairs$Scope <- ifelse(\n  distance_pairs$Group1 == distance_pairs$Group2,\n  distance_pairs$Group1, \"Between regions\"\n)\ndistance_pairs$LogDistance <- log10(distance_pairs$DistanceKm + 1)\ndistance_pairs$LogSimilarity <- log10(distance_pairs$Similarity)\nwithin_pairs <- distance_pairs[\n  distance_pairs$Scope %in% levels(metadata$Group), , drop = FALSE\n]\n\nfit_distance_slope <- function(data, region) {\n  fit <- stats::lm(LogSimilarity ~ LogDistance, data = data)\n  interval <- stats::confint(fit, \"LogDistance\", level = 0.95)\n  data.frame(\n    Region = region,\n    Pairs = nrow(data),\n    MinDistanceKm = min(data$DistanceKm),\n    MaxDistanceKm = max(data$DistanceKm),\n    Slope = unname(stats::coef(fit)[[\"LogDistance\"]]),\n    Lower = unname(interval[[1L]]),\n    Upper = unname(interval[[2L]]),\n    RSquared = summary(fit)$r.squared,\n    stringsAsFactors = FALSE\n  )\n}\ndistance_slope_ledger <- rbind(\n  fit_distance_slope(distance_pairs, \"Pooled\"),\n  do.call(rbind, lapply(levels(metadata$Group), function(group_name) {\n    fit_distance_slope(\n      within_pairs[within_pairs$Scope == group_name, , drop = FALSE],\n      group_name\n    )\n  }))\n)\n\nset.seed(20260740)\nblocked_permutations <- permute::shuffleSet(\n  nrow(metadata), nset = 999L,\n  control = permute::how(blocks = metadata$Group)\n)\npooled_mantel <- vegan::mantel(\n  stats::as.dist(bray_matrix), stats::as.dist(geographic_matrix),\n  method = \"spearman\", permutations = blocked_permutations\n)\nmantel_ledger <- data.frame(\n  Region = \"Pooled; permutations within region\",\n  Samples = nrow(metadata),\n  MantelRho = unname(pooled_mantel$statistic),\n  PermutationP = pooled_mantel$signif,\n  stringsAsFactors = FALSE\n)\nfor (group_index in seq_along(levels(metadata$Group))) {\n  group_name <- levels(metadata$Group)[[group_index]]\n  rows <- metadata$Group == group_name\n  set.seed(20260740L + group_index)\n  fit <- vegan::mantel(\n    stats::as.dist(bray_matrix[rows, rows]),\n    stats::as.dist(geographic_matrix[rows, rows]),\n    method = \"spearman\", permutations = 999L\n  )\n  mantel_ledger <- rbind(\n    mantel_ledger,\n    data.frame(\n      Region = group_name,\n      Samples = sum(rows),\n      MantelRho = unname(fit$statistic),\n      PermutationP = fit$signif,\n      stringsAsFactors = FALSE\n    )\n  )\n}\n\nstopifnot(\n  nrow(distance_pairs) == choose(90L, 2L),\n  nrow(within_pairs) == 3L * choose(30L, 2L),\n  max(distance_pairs$DistanceKm) > 4000,\n  all(distance_slope_ledger$Slope < 0),\n  all(mantel_ledger$PermutationP >= 1 / 1000 &\n        mantel_ledger$PermutationP <= 1)\n)\ndistance_slope_ledger\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Region Pairs MinDistanceKm MaxDistanceKm       Slope       Lower       Upper\n1 Pooled  4005    0.00000000      4030.928 -0.17966159 -0.18652999 -0.17279319\n2     CW   435    0.00000000      2590.647 -0.13561249 -0.14905760 -0.12216737\n3     IW   435    0.01433949      1248.224 -0.14192181 -0.15603654 -0.12780708\n4     TW   435    0.01259622      1052.052 -0.05368038 -0.07014131 -0.03721944\n    RSquared\n1 0.39650367\n2 0.47578989\n3 0.47422973\n4 0.08665552\n```\n\n\n:::\n\n```{.r .cell-code}\nmantel_ledger\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              Region Samples  MantelRho PermutationP\n1 Pooled; permutations within region      90 0.58463928        0.001\n2                                 CW      30 0.61719236        0.001\n3                                 IW      30 0.41363945        0.001\n4                                 TW      30 0.03971385        0.287\n```\n\n\n:::\n:::\n\n\n## 三类生态模式如何相互验证？ {#sec-audit}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nniche_distance_audit <- data.frame(\n  Dimension = c(\n    \"Breadth estimand\", \"Breadth filter\", \"RAD replicate\", \"RAD choice\",\n    \"Geographic distance\", \"Pair dependence\", \"Spatial scale\", \"Process claim\"\n  ),\n  FragilePractice = c(\n    \"Call sample evenness a physiological niche\",\n    \"Let singletons define specialists\",\n    \"Pool samples into one curve\",\n    \"Select a model without diagnostics\",\n    \"Use Euclidean degrees as kilometres\",\n    \"Run ordinary p-values on all pairs\",\n    \"Mix within- and between-region pairs\",\n    \"Equate decay with dispersal limitation\"\n  ),\n  UpgradedContract = c(\n    \"Use sample-use breadth and state its limit\",\n    \"Prespecify prevalence and abundance gates\",\n    \"Fit each sample and retain winner variation\",\n    \"Report AIC ledger and convergence warnings\",\n    \"Use Haversine great-circle distance\",\n    \"Use slopes descriptively and permute labels\",\n    \"Lead with stratified curves and pooled audit\",\n    \"Require environment and process-aware evidence\"\n  ),\n  stringsAsFactors = FALSE\n)\nknitr::kable(\n  niche_distance_audit,\n  caption = \"Audit contract for macroecological pattern claims\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Audit contract for macroecological pattern claims\n\n|Dimension           |FragilePractice                            |UpgradedContract                               |\n|:-------------------|:------------------------------------------|:----------------------------------------------|\n|Breadth estimand    |Call sample evenness a physiological niche |Use sample-use breadth and state its limit     |\n|Breadth filter      |Let singletons define specialists          |Prespecify prevalence and abundance gates      |\n|RAD replicate       |Pool samples into one curve                |Fit each sample and retain winner variation    |\n|RAD choice          |Select a model without diagnostics         |Report AIC ledger and convergence warnings     |\n|Geographic distance |Use Euclidean degrees as kilometres        |Use Haversine great-circle distance            |\n|Pair dependence     |Run ordinary p-values on all pairs         |Use slopes descriptively and permute labels    |\n|Spatial scale       |Mix within- and between-region pairs       |Lead with stratified curves and pooled audit   |\n|Process claim       |Equate decay with dispersal limitation     |Require environment and process-aware evidence |\n\n\n:::\n:::\n\n\n过滤后保留 3208 个 OTU；standardized breadth 中位数为 0.124，与 occupancy 的 Spearman $\\rho=$ 0.636。这个相关的一部分来自数学约束，不能单独支持 generalist–specialist 机制。\n\nRAD 候选集中，Mandelbrot 在 75/90 个样本中 AIC 最低；拟合捕获并保留了 3 条 warning。warning 是诊断信息，不能因最终有一条曲线就删除。\n\nwithin-region log–log slopes 分别为 CW -0.136、IW -0.142、TW -0.054。三组 slope 都为负，但 effect size 和 Mantel evidence 不一致，说明 pooled distance-decay 不能替代分层检查。\n\n## 出版级美化 {#sec-publication}\n\n### 图 1：sample-use breadth 与 occupancy\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbreadth_colours <- c(\n  \"Narrow decile\" = pal_pub[[\"blue\"]],\n  \"Intermediate\" = pal_pub[[\"grey\"]],\n  \"Broad decile\" = pal_pub[[\"vermillion\"]]\n)\nnarrow_label_pool <- head(\n  breadth_ledger[order(breadth_ledger$StandardizedBreadth), ], 40L\n)\nnarrow_label_pool <- narrow_label_pool[\n  !duplicated(narrow_label_pool$DisplayTaxon),\n]\nnarrow_labels <- head(\n  narrow_label_pool[order(nchar(narrow_label_pool$DisplayTaxon)), ], 3L\n)\nbroad_labels <- head(\n  breadth_ledger[order(-breadth_ledger$StandardizedBreadth), ], 6L\n)\nlabel_breadth <- rbind(narrow_labels, broad_labels)\nbreadth_plot <- ggplot(\n  breadth_ledger,\n  aes(x = Prevalence, y = StandardizedBreadth, colour = BreadthClass)\n) +\n  geom_point(size = 1.1, alpha = 0.48) +\n  ggrepel::geom_text_repel(\n    data = label_breadth,\n    aes(label = DisplayTaxon),\n    family = font_pub, size = 2.35, max.overlaps = Inf,\n    min.segment.length = 0, show.legend = FALSE\n  ) +\n  scale_colour_manual(values = breadth_colours) +\n  scale_x_continuous(\n    labels = scales::label_percent(), limits = c(0.04, 1.03),\n    expand = expansion(mult = c(0.01, 0.01))\n  ) +\n  scale_y_continuous(\n    limits = c(0, max(breadth_ledger$StandardizedBreadth) * 1.08),\n    expand = expansion(mult = c(0.01, 0.02))\n  ) +\n  labs(\n    title = \"Sample-use breadth is constrained by occupancy\",\n    subtitle = sprintf(\n      \"%d OTUs; Spearman rho = %.3f\",\n      nrow(breadth_ledger), breadth_occupancy_rho\n    ),\n    x = \"Sample occupancy\", y = \"Standardized Levins breadth\",\n    colour = \"Breadth class\",\n    caption = \"Deciles are descriptive within this filtered feature universe; breadth is not a physiological tolerance measurement.\"\n  ) +\n  theme_pub(base_size = 8.4) +\n  theme(legend.position = \"bottom\")\nsave_pub(\n  breadth_plot, \"figures/40-niche-breadth\", width = 180, height = 140\n)\nbreadth_plot\n```\n\n::: {.cell-output-display}\n![](40-niche-distance-decay_files/figure-html/fig-niche-breadth-1.png){#fig-niche-breadth}\n:::\n:::\n\n\n### 图 2：representative RAD 与 90 个样本的 model winners\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrad_colours <- c(\n  \"Null\" = pal_pub[[\"grey\"]], \"Preemption\" = pal_pub[[\"orange\"]],\n  \"Lognormal\" = pal_pub[[\"green\"]], \"Zipf\" = pal_pub[[\"blue\"]],\n  \"Mandelbrot\" = pal_pub[[\"vermillion\"]]\n)\nrad_curve_panel <- ggplot() +\n  geom_point(\n    data = representative_observed,\n    aes(x = Rank, y = Abundance), size = 0.75, alpha = 0.45\n  ) +\n  geom_line(\n    data = representative_rad,\n    aes(x = Rank, y = Abundance, colour = Model), linewidth = 0.65\n  ) +\n  scale_x_log10() +\n  scale_y_log10() +\n  scale_colour_manual(values = rad_colours) +\n  labs(\n    title = \"A. Representative rank-abundance fit\",\n    subtitle = sprintf(\n      \"%s (%s); richness = %d\",\n      representative_sample, metadata[representative_sample, \"Group\"],\n      sample_richness[[representative_sample]]\n    ),\n    x = \"Abundance rank\", y = \"Read count\", colour = \"RAD model\"\n  ) +\n  theme_pub(base_size = 7.8) +\n  theme(legend.position = \"bottom\")\nrad_winner_panel <- ggplot(\n  rad_model_summary,\n  aes(x = reorder(Model, WinningSamples), y = WinningSamples, fill = Model)\n) +\n  geom_col(width = 0.68, colour = \"white\", linewidth = 0.3) +\n  geom_text(\n    aes(label = WinningSamples), hjust = -0.15,\n    family = font_pub, size = 2.7\n  ) +\n  coord_flip(clip = \"off\") +\n  scale_fill_manual(values = rad_colours) +\n  scale_y_continuous(\n    limits = c(0, max(rad_model_summary$WinningSamples) * 1.14),\n    expand = c(0, 0)\n  ) +\n  labs(\n    title = \"B. Best AIC model across samples\",\n    subtitle = sprintf(\"%d captured fitting warnings\", nrow(rad_warning_ledger)),\n    x = NULL, y = \"Samples\"\n  ) +\n  theme_pub(base_size = 7.8) +\n  theme(legend.position = \"none\")\nrad_plot <- patchwork::wrap_plots(\n  rad_curve_panel, rad_winner_panel, nrow = 1L, widths = c(1.25, 0.75)\n) +\n  patchwork::plot_annotation(\n    title = \"RAD models summarize dominance, not unique mechanisms\",\n    caption = \"Model winners are relative to the five-model candidate set; each biological sample was fitted independently.\"\n  )\nsave_pub(\n  rad_plot, \"figures/40-rank-abundance-models\",\n  width = 180, height = 132\n)\nrad_plot\n```\n\n::: {.cell-output-display}\n![](40-niche-distance-decay_files/figure-html/fig-rank-abundance-models-1.png){#fig-rank-abundance-models}\n:::\n:::\n\n\n### 图 3：within-region geographic distance-decay\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregion_colours <- c(\n  \"CW\" = pal_pub[[\"blue\"]],\n  \"IW\" = pal_pub[[\"orange\"]],\n  \"TW\" = pal_pub[[\"green\"]]\n)\nwithin_pairs$Scope <- factor(\n  within_pairs$Scope, levels = c(\"CW\", \"IW\", \"TW\")\n)\ndistance_decay_plot <- ggplot(\n  within_pairs,\n  aes(x = LogDistance, y = LogSimilarity, colour = Scope)\n) +\n  geom_point(size = 0.9, alpha = 0.32) +\n  geom_smooth(method = \"lm\", se = TRUE, linewidth = 0.8) +\n  facet_wrap(~Scope, scales = \"free_x\") +\n  scale_colour_manual(values = region_colours) +\n  labs(\n    title = \"Distance-decay differs across wetland regions\",\n    subtitle = \"Bray-Curtis similarity regressed on Haversine distance within each region\",\n    x = \"log10(Geographic distance [km] + 1)\",\n    y = \"log10(Bray-Curtis similarity)\", colour = \"Region\",\n    caption = \"Pairwise points are not independent; slopes are effect-size descriptions and permutation evidence is reported separately.\"\n  ) +\n  theme_pub(base_size = 8.2) +\n  theme(legend.position = \"none\")\nsave_pub(\n  distance_decay_plot, \"figures/40-distance-decay\",\n  width = 180, height = 137\n)\ndistance_decay_plot\n```\n\n::: {.cell-output-display}\n![](40-niche-distance-decay_files/figure-html/fig-distance-decay-1.png){#fig-distance-decay}\n:::\n:::\n\n\n### 图 4：slope 与 permutation evidence 并列审计\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_slopes <- distance_slope_ledger[\n  distance_slope_ledger$Region != \"Pooled\",\n]\nslope_panel <- ggplot(\n  plot_slopes,\n  aes(x = Slope, y = Region, colour = Region)\n) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#555555\") +\n  geom_errorbarh(\n    aes(xmin = Lower, xmax = Upper), height = 0.15, linewidth = 0.75\n  ) +\n  geom_point(size = 3) +\n  scale_colour_manual(values = region_colours) +\n  labs(\n    title = \"A. Within-region decay slope\",\n    subtitle = \"Estimate and ordinary-regression 95% CI\",\n    x = \"Log-log slope\", y = NULL\n  ) +\n  theme_pub(base_size = 8.0) +\n  theme(legend.position = \"none\")\nplot_mantel <- mantel_ledger[mantel_ledger$Region %in% c(\"CW\", \"IW\", \"TW\"), ]\nmantel_panel <- ggplot(\n  plot_mantel,\n  aes(x = MantelRho, y = Region, colour = Region)\n) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#555555\") +\n  geom_point(size = 3) +\n  geom_text(\n    aes(label = sprintf(\"p = %.3f\", PermutationP)),\n    nudge_x = 0.055, hjust = 0, family = font_pub, size = 2.5\n  ) +\n  scale_colour_manual(values = region_colours) +\n  scale_x_continuous(\n    limits = c(min(0, min(plot_mantel$MantelRho) - 0.05),\n               max(plot_mantel$MantelRho) + 0.18)\n  ) +\n  labs(\n    title = \"B. Mantel rank association\",\n    subtitle = \"999 sample-label permutations per region\",\n    x = \"Spearman Mantel rho\", y = NULL\n  ) +\n  theme_pub(base_size = 8.0) +\n  theme(legend.position = \"none\")\ndistance_audit_plot <- patchwork::wrap_plots(\n  slope_panel, mantel_panel, nrow = 1L\n) +\n  patchwork::plot_annotation(\n    title = \"Effect size and permutation evidence answer different questions\",\n    caption = \"Slope CIs ignore pair dependence; Mantel does not separate environment from dispersal.\",\n    theme = theme(\n      plot.caption = element_text(\n        family = font_pub, colour = \"#666666\", hjust = 0,\n        margin = margin(t = 5, r = 4, b = 2, l = 8)\n      )\n    )\n  )\nsave_pub(\n  distance_audit_plot, \"figures/40-distance-decay-audit\",\n  width = 180, height = 125\n)\ndistance_audit_plot\n```\n\n::: {.cell-output-display}\n![](40-niche-distance-decay_files/figure-html/fig-distance-decay-audit-1.png){#fig-distance-decay-audit}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-caution title=\"常见坑：审稿人会追问的十件事\"}\n\n1. **把 sample-use breadth 写成生理 tolerance**：没有环境梯度或实验测量时不能这样升级。  \n2. **让 singleton 定义 specialist**：先固定最低 prevalence/abundance，并报告过滤影响。  \n3. **忽略 breadth–occupancy 数学耦合**：相关不自动等于生态机制。  \n4. **合并样本后只拟合一条 RAD**：必须保留 sample-level replicate variation。  \n5. **只报 AIC winner**：同时保留候选集、$\\Delta$AIC 和 convergence warnings。  \n6. **经纬度直接用 Euclidean distance**：跨数百公里时应用 great-circle distance。  \n7. **把 4,005 个 pairs 当独立观测**：普通回归 p-value 和 CI 会过度乐观。  \n8. **混合 within/between-region pairs**：先分层画图，再审计 pooled result。  \n9. **Mantel 显著就写 dispersal limitation**：环境空间自相关可产生同一 pattern。  \n10. **忽略可比空间范围**：不同 region 的 slope 比较还需匹配 distance support。\n\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> The OTU table, taxonomy and metadata were read independently and aligned by sample identifier; latitude and longitude were obtained from the environment table distributed with the same dataset. Sample-use breadth was calculated for OTUs with prevalence ≥5% and total abundance ≥100 reads (3,208 OTUs). Relative abundances across the 90 samples were converted to taxon-specific sample shares, and Levins' index was standardized to [0,1]. Narrow and broad labels denoted the lower and upper within-dataset deciles and were treated descriptively. Rank-abundance distributions were fitted separately in all 90 samples using broken-stick/null, preemption, lognormal, Zipf and Zipf–Mandelbrot models in `vegan`; AIC, $\\Delta$AIC, the best candidate and all fitting warnings were retained. Geographic distances were computed using the Haversine formula, community dissimilarity using Bray–Curtis, and within-region distance-decay as $\\log_{10}(1-D_{BC})$ versus $\\log_{10}(G+1)$. Slopes were reported as descriptive effect sizes because pairs share samples. Spearman Mantel associations used 999 sample-label permutations within each region; the pooled audit restricted permutations within region blocks. Random seeds were fixed at 20260740–20260743.\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read_keyed_tsv(\"your_data/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"your_data/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"your_data/metadata.tsv\")\nenvironment <- read_keyed_tsv(\"your_data/environment.tsv\")\n\n# 必改：经纬度列与主分层列。\nlatitude <- environment$YourLatitudeColumn\nlongitude <- environment$YourLongitudeColumn\nmetadata$Group <- factor(metadata$YourRegionColumn)\n\n# 必须在看结果前固定：\nprevalence_cutoff <- 0.05\ntotal_read_cutoff <- 100L\n```\n:::\n\n\n若没有经纬度，可以计算预先定义的 environmental distance，但不能继续把横轴写成 geographic distance。若是时间序列或 repeated measures，应在 subject/site 内定义 pairs 或用 mixed/spatial model；若不同区域的 distance range 几乎不重叠，不宜直接比较 slope 大小。\n\n## 参考 {#sec-references}\n\n- Levins R. *Evolution in Changing Environments: Some Theoretical Explorations*. Princeton University Press; 1968.\n- Wilson JB. Methods for fitting dominance/diversity curves. *Journal of Vegetation Science*. 1991;2:35–46. <https://doi.org/10.2307/3235896>\n- Martiny JBH, Eisen JA, Penn K, Allison SD, Horner-Devine MC. Drivers of bacterial beta-diversity depend on spatial scale. *Proceedings of the National Academy of Sciences*. 2011;108:7850–7854. <https://doi.org/10.1073/pnas.1016308108>\n- Hanson CA, Fuhrman JA, Horner-Devine MC, Martiny JBH. Beyond biogeographic patterns: processes shaping the microbial landscape. *Nature Reviews Microbiology*. 2012;10:497–506. <https://doi.org/10.1038/nrmicro2795>\n- Nekola JC, White PS. The distance decay of similarity in biogeography and ecology. *Journal of Biogeography*. 1999;26:867–878. <https://doi.org/10.1046/j.1365-2699.1999.00305.x>\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. <https://doi.org/10.1016/j.geoderma.2018.09.035>\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97:fiaa255. <https://doi.org/10.1093/femsec/fiaa255>\n",
    "supporting": [
      "40-niche-distance-decay_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}
