{
  "hash": "c4ee96875dd1b59fefed8d82b3fdb788",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"βNTI + RCbray：确定性与随机过程的条件性证据\"\nauthor: \"Peter\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/38-community-assembly-bnti.R\n  packages:\n  - ape\n  - ggplot2\n  - iCAMP\n  - knitr\n  - patchwork\n  - ragg\n  - scales\n  - svglite\n---\n\n## βNTI 与 RCbray 提供的是条件性组装证据 {#sec-target}\n\n[Stegen et al. (2013)](https://doi.org/10.1038/ismej.2013.93)把 β-nearest taxon index（βNTI）与 abundance-based Raup–Crick（RCbray）串联，用 pairwise phylogenetic 与 taxonomic turnover 条件性区分 selection、dispersal 和 undominated processes。[Ning et al. (2020)](https://doi.org/10.1038/s41467-020-18560-z)进一步发展了可扩展的定量框架。下面用公开湿地数据检查 βNTI–RCbray process map、分组 process fractions、系统发育信号和过滤结果。\n\n::: {.callout-important title=\"先给结论\"}\nβNTI/RCbray 不是从一张 OTU 表直接“测出生态过程”。只有系统树与 feature 精确对齐、局部 phylogenetic signal 得到支持、null model 与 regional pool 合理、随机化充分且过滤敏感性可接受时，process fractions 才能作为条件性证据。它们不是 dispersal rate、selection strength 或因果比例的直接测量。\n:::\n\n本页使用 `microeco` 2.0.0 随数据分发的真实 14,096-tip rooted 16S tree。树覆盖全部 13,628 个 count-table OTU，另有 468 个未进入 count table 的 tips；代码先按当前 feature universe 裁剪，不让 `ape` 或 iCAMP 静默重排。\n\n## 下载并读取本次分析的数据 {#sec-setup}\n\n需要 R，以及 `ape`、`ggplot2`、`iCAMP`、`knitr`、`patchwork`、`ragg`、`scales`、`svglite`。本次使用中国湿地的 OTU count 表、分类表和样本信息表，以及本次分析使用的实测环境变量或系统发育信息。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"data/small/environment.tsv\",\n  \"data/small/metadata.tsv\",\n  \"data/small/otutab.tsv\",\n  \"data/small/rooted-tree.nwk.gz\",\n  \"data/small/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(ape)\nlibrary(iCAMP)\n\nset.seed(20260738)\nfont_pub <- \"sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(colour = \"#1A1A1A\", linewidth = 0.3),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(), legend.position = \"top\"\n    )\n}\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot, width = width, height = height,\n    units = units, device = grDevices::cairo_pdf,\n    family = base_family, bg = \"white\"\n  )\n  if (write_svg) ggplot2::ggsave(\n    paste0(file_base, \".svg\"), plot, width = width, height = height,\n    units = units, device = svglite::svglite, bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_png, bg = \"white\"\n  )\n  if (write_tiff) ggplot2::ggsave(\n    paste0(file_base, \".tiff\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_tiff,\n    compression = \"lzw\", bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n### 读取三件套、环境表与真实有根树\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path, show_col_types = FALSE, progress = FALSE,\n    name_repair = \"minimal\", na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\notutab_raw <- read_keyed_tsv(\"data/small/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"data/small/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"data/small/metadata.tsv\")\nenvironment <- read_keyed_tsv(\"data/small/environment.tsv\")\notutab <- as.matrix(data.frame(\n  lapply(otutab_raw, as.integer), check.names = FALSE\n))\nrownames(otutab) <- rownames(otutab_raw)\nmetadata$Group <- factor(metadata$Group, levels = c(\"CW\", \"IW\", \"TW\"))\notutab <- otutab[, rownames(metadata), drop = FALSE]\nenvironment <- environment[rownames(metadata), , drop = FALSE]\nfull_tree <- ape::read.tree(gzfile(\"data/small/rooted-tree.nwk.gz\"))\n\ntree_tip_contract <- data.frame(\n  TreeTips = ape::Ntip(full_tree),\n  CountFeatures = nrow(otutab),\n  CountFeaturesMissingFromTree = sum(!rownames(otutab) %in% full_tree$tip.label),\n  TreeTipsOutsideCountTable = sum(!full_tree$tip.label %in% rownames(otutab)),\n  Rooted = ape::is.rooted(full_tree),\n  NonPositiveBranches = sum(\n    !is.finite(full_tree$edge.length) | full_tree$edge.length <= 0\n  )\n)\nstopifnot(\n  nrow(otutab) == 13628L,\n  ncol(otutab) == 90L,\n  sum(otutab) == 1619670L,\n  nrow(taxonomy) == nrow(otutab),\n  tree_tip_contract$TreeTips == 14096L,\n  tree_tip_contract$CountFeaturesMissingFromTree == 0L,\n  tree_tip_contract$TreeTipsOutsideCountTable == 468L,\n  tree_tip_contract$Rooted\n)\ntree_tip_contract\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  TreeTips CountFeatures CountFeaturesMissingFromTree TreeTipsOutsideCountTable\n1    14096         13628                            0                       468\n  Rooted NonPositiveBranches\n1   TRUE                   1\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/691722146e287afe063bd43e9ce4fa41977fe763/examples/38-community-assembly-bnti.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"ape\", \"ggplot2\", \"iCAMP\", \"patchwork\", \"ragg\", \"readr\",\n  \"scales\", \"svglite\", \"systemfonts\"\n))\n```\n:::\n\n\n</details>\n\n## 先用 βNTI 判断 selection，再用 RCbray 分流 {#sec-theory}\n\n### βMNTD 与 βNTI\n\nAbundance-weighted β mean nearest taxon distance（βMNTD）计算两个样本间每个 taxon 到另一群落最近亲缘 taxon 的距离。Taxon labels 在固定树上随机化后，βNTI 是 observed βMNTD 相对 null mean 的标准化偏离：\n\n$$\n\\beta NTI = \\frac{\\beta MNTD_{obs}-\\mu(\\beta MNTD_{null})}\n{\\sigma(\\beta MNTD_{null})}.\n$$\n\n`βNTI > +1.96` 表示 turnover 高于 null，常标为 heterogeneous selection；`βNTI < -1.96` 表示 turnover 低于 null，常标为 homogeneous selection。\n\n### 只有 |βNTI| 不超过 1.96 才进入 RCbray\n\n当 phylogenetic turnover 没有越过 selection gate，再用 abundance-based RCbray：\n\n- `RCbray > +0.95`：dispersal limitation；\n- `RCbray < -0.95`：homogenizing dispersal；\n- `|RCbray| <= 0.95`：undominated，可能混合 weak selection、weak dispersal、drift 与 diversification。\n\n这是一套 operational classification；“undominated”不等于只有 drift，“dispersal limitation”也不是实测迁移率。\n\n### 为什么必须先查 phylogenetic signal\n\nβNTI 用近缘关系代理 niche similarity。若近缘 taxa 在所研究环境尺度上没有相似 niche，phylogenetic turnover 不能可靠映射到 selection。本页为 retained OTUs 计算 pH、conductivity、TOC 的 abundance-weighted niche optima，在最近 10% phylogenetic distances 内检验“系统距离越大，niche difference 是否越大”，并用 499 次 taxon-label permutation 与三项 BH 控制。\n\n### 区域类群库与特征过滤会改变零模型的参照\n\n本页主分析预先保留 prevalence ≥10%、total reads ≥500 的 dominant OTUs；这样把运行规模固定为 585 taxa，但只覆盖部分 reads。严格阈值 `total reads ≥1000` 另行重跑 199 次 null sensitivity。二者估计的是不同 dominant-community universes，不能把 filter-dependent fractions 写成全群落定律。\n\n### Parallel null model 也要有确定性随机数流\n\n`iCAMP 1.5.12` 的公开函数没有 `seed` 参数，并在内部新建 PSOCK cluster。仅在主进程 `set.seed()` 不能保证 worker streams 相同。本页复制函数到当前会话并在内部 `parLapply()` 前插入 `clusterSetRNGStream()`；不修改安装包 namespace，两次运行可逐值复现。\n\n<details>\n<summary><strong>深入：为什么 process fractions 不能当成样本级独立比例</strong></summary>\n\n90 个样本产生 4,005 个 pair，但同一样本参与 89 个 pair，因此 pairwise labels 不是 4,005 个独立观测。堆叠比例是描述性汇总；若要比较组间 fractions，应在 site/subject 层 bootstrap 或采用维护 pair dependence 的层级模型，而不是对 pair labels 做普通卡方检验。\n\n</details>\n\n## 在系统发育假设下计算βNTI与RCbray {#sec-code}\n\n### 确定优势 OTU 集合，并保留对应的树枝\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_keep <- rowMeans(otutab > 0) >= 0.10 & rowSums(otutab) >= 500\nprimary_counts <- otutab[primary_keep, , drop = FALSE]\ncommunity <- t(primary_counts)\npruned_tree <- ape::keep.tip(full_tree, colnames(community))\nphylogenetic_distance <- ape::cophenetic.phylo(pruned_tree)\nphylogenetic_distance <- phylogenetic_distance[\n  colnames(community), colnames(community), drop = FALSE\n]\nsample_retention <- data.frame(\n  SampleID = colnames(otutab),\n  Group = metadata[colnames(otutab), \"Group\"],\n  RetainedFraction = colSums(primary_counts) / colSums(otutab),\n  stringsAsFactors = FALSE\n)\n\nstopifnot(\n  ncol(community) == 585L,\n  ape::Ntip(pruned_tree) == ncol(community),\n  setequal(pruned_tree$tip.label, colnames(community)),\n  identical(rownames(phylogenetic_distance), colnames(community)),\n  all(is.finite(phylogenetic_distance)),\n  all(phylogenetic_distance >= 0)\n)\n\ndata.frame(\n  RetainedOTUs = ncol(community),\n  RetainedReadFraction = sum(primary_counts) / sum(otutab),\n  MinimumSampleRetention = min(sample_retention$RetainedFraction),\n  MaximumSampleRetention = max(sample_retention$RetainedFraction),\n  PrunedTreeTips = ape::Ntip(pruned_tree)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  RetainedOTUs RetainedReadFraction MinimumSampleRetention\n1          585            0.4741738              0.2696026\n  MaximumSampleRetention PrunedTreeTips\n1              0.7720565            585\n```\n\n\n:::\n:::\n\n\n### 先检验最近 10% 系统距离的 niche signal\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelative_abundance <- sweep(otutab, 2L, colSums(otutab), \"/\")\nretained_relative <- relative_abundance[primary_keep, , drop = FALSE]\ntaxon_site_weights <- sweep(\n  retained_relative, 1L, rowSums(retained_relative), \"/\"\n)\ndistance_index <- which(upper.tri(phylogenetic_distance), arr.ind = TRUE)\npair_distance <- phylogenetic_distance[distance_index]\nshort_range <- pair_distance <= stats::quantile(pair_distance, 0.10)\nshort_index <- distance_index[short_range, , drop = FALSE]\nshort_distance <- pair_distance[short_range]\nsignal_traits <- c(\"pH\", \"Conductivity\", \"TOC\")\n\nset.seed(20260738)\nsignal_results <- lapply(seq_along(signal_traits), function(trait_index) {\n  trait <- signal_traits[[trait_index]]\n  niche_optimum <- as.vector(\n    taxon_site_weights %*% as.numeric(environment[[trait]])\n  )\n  niche_difference <- abs(\n    niche_optimum[short_index[, \"row\"]] -\n      niche_optimum[short_index[, \"col\"]]\n  )\n  observed <- stats::cor(\n    short_distance, niche_difference, method = \"spearman\"\n  )\n  set.seed(20260738L + trait_index)\n  null_rho <- replicate(499L, {\n    permuted <- sample(niche_optimum)\n    stats::cor(\n      short_distance,\n      abs(\n        permuted[short_index[, \"row\"]] -\n          permuted[short_index[, \"col\"]]\n      ),\n      method = \"spearman\"\n    )\n  })\n  data.frame(\n    Trait = trait,\n    ObservedRho = observed,\n    NullLower = stats::quantile(null_rho, 0.025),\n    NullMedian = stats::median(null_rho),\n    NullUpper = stats::quantile(null_rho, 0.975),\n    PValue = (1 + sum(null_rho >= observed)) / 500,\n    ShortRangePairs = length(short_distance),\n    stringsAsFactors = FALSE\n  )\n})\nsignal_results <- do.call(rbind, signal_results)\nsignal_results$QValue <- stats::p.adjust(signal_results$PValue, method = \"BH\")\nsignal_results$Supported <- signal_results$ObservedRho > 0 &\n  signal_results$QValue < 0.05\nphylogenetic_signal_gate <- if (\n  sum(signal_results$Supported) >= 2L\n) \"CONDITIONAL PASS\" else \"FAIL\"\nsignal_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Trait ObservedRho   NullLower    NullMedian  NullUpper PValue\n2.5%            pH  0.04269054 -0.04440469 -0.0007388548 0.04262020  0.028\n2.5%1 Conductivity  0.17225367 -0.03947050 -0.0001770700 0.04528549  0.002\n2.5%2          TOC  0.03006616 -0.04415424  0.0013572020 0.05092055  0.102\n      ShortRangePairs QValue Supported\n2.5%            17083  0.042      TRUE\n2.5%1           17083  0.006      TRUE\n2.5%2           17083  0.102     FALSE\n```\n\n\n:::\n:::\n\n\n### 为 iCAMP 的并行计算固定随机数流\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseed_icamp_function <- function(fun, target, seed) {\n  function_text <- paste(deparse(fun), collapse = \"\\n\")\n  replacement <- paste0(\n    \"parallel::clusterSetRNGStream(c1, iseed = \",\n    as.integer(seed), \"L)\\n    \", target\n  )\n  stopifnot(grepl(target, function_text, fixed = TRUE))\n  function_text <- sub(\n    target, replacement, function_text, fixed = TRUE\n  )\n  seeded_function <- eval(\n    parse(text = function_text), envir = environment(fun)\n  )\n  environment(seeded_function) <- environment(fun)\n  seeded_function\n}\nseeded_bnti <- seed_icamp_function(\n  iCAMP::bNTI.cm,\n  \"bMNTD.rand <- parallel::parLapply\",\n  20260738L\n)\nseeded_rcbray <- seed_icamp_function(\n  iCAMP::RC.cm,\n  \"BC.rd <- parallel::parLapply\",\n  20261738L\n)\nn_workers <- max(\n  1L,\n  min(8L, parallel::detectCores(logical = FALSE))\n)\n\n# Small double-run probe: same seed and worker count must be byte-identical.\nprobe_community <- community[, head(colnames(community), 40L), drop = FALSE]\nprobe_distance <- phylogenetic_distance[\n  colnames(probe_community), colnames(probe_community), drop = FALSE\n]\nprobe_one <- seeded_bnti(\n  comm = probe_community,\n  dis = probe_distance,\n  nworker = n_workers,\n  weighted = TRUE,\n  rand = 9L,\n  output.bMNTD = FALSE,\n  sig.index = \"SES\"\n)$index\nprobe_two <- seeded_bnti(\n  comm = probe_community,\n  dis = probe_distance,\n  nworker = n_workers,\n  weighted = TRUE,\n  rand = 9L,\n  output.bMNTD = FALSE,\n  sig.index = \"SES\"\n)$index\nstopifnot(identical(probe_one, probe_two))\n```\n:::\n\n\n### 正式运行 999 次 βNTI 与 RCbray null models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_randomizations <- 999L\nbnti_fit <- seeded_bnti(\n  comm = community,\n  dis = phylogenetic_distance,\n  nworker = n_workers,\n  weighted = TRUE,\n  rand = primary_randomizations,\n  output.bMNTD = TRUE,\n  sig.index = \"SES\"\n)\nrcbray_fit <- seeded_rcbray(\n  comm = community,\n  nworker = n_workers,\n  weighted = TRUE,\n  rand = primary_randomizations,\n  sig.index = \"RC\",\n  output.bray = TRUE,\n  silent = TRUE\n)\nbnti_matrix <- bnti_fit$index\nrcbray_matrix <- rcbray_fit$index\n\npair_index <- which(lower.tri(bnti_matrix), arr.ind = TRUE)\nassembly_pairs <- data.frame(\n  Sample1 = rownames(bnti_matrix)[pair_index[, \"row\"]],\n  Sample2 = colnames(bnti_matrix)[pair_index[, \"col\"]],\n  BetaNTI = bnti_matrix[pair_index],\n  RCbray = rcbray_matrix[pair_index],\n  BrayCurtis = rcbray_fit$BC.obs[pair_index],\n  stringsAsFactors = FALSE\n)\nassembly_pairs$Group1 <- metadata[assembly_pairs$Sample1, \"Group\"]\nassembly_pairs$Group2 <- metadata[assembly_pairs$Sample2, \"Group\"]\nassembly_pairs$PairScope <- ifelse(\n  assembly_pairs$Group1 == assembly_pairs$Group2,\n  paste(\"Within\", assembly_pairs$Group1),\n  \"Between groups\"\n)\nclassify_process <- function(beta_nti, rcbray) {\n  ifelse(\n    beta_nti > 1.96, \"Heterogeneous selection\",\n    ifelse(\n      beta_nti < -1.96, \"Homogeneous selection\",\n      ifelse(\n        rcbray > 0.95, \"Dispersal limitation\",\n        ifelse(\n          rcbray < -0.95, \"Homogenizing dispersal\", \"Undominated\"\n        )\n      )\n    )\n  )\n}\nassembly_pairs$Process <- classify_process(\n  assembly_pairs$BetaNTI, assembly_pairs$RCbray\n)\nprocess_levels <- c(\n  \"Heterogeneous selection\", \"Homogeneous selection\",\n  \"Dispersal limitation\", \"Homogenizing dispersal\", \"Undominated\"\n)\nassembly_pairs$Process <- factor(\n  assembly_pairs$Process, levels = process_levels\n)\nassembly_pairs$PairScope <- factor(\n  assembly_pairs$PairScope,\n  levels = c(\"Within CW\", \"Within IW\", \"Within TW\", \"Between groups\")\n)\nprocess_fraction <- as.data.frame(\n  prop.table(table(assembly_pairs$PairScope, assembly_pairs$Process), 1L),\n  stringsAsFactors = FALSE\n)\nnames(process_fraction) <- c(\"PairScope\", \"Process\", \"Fraction\")\n\nstopifnot(\n  nrow(assembly_pairs) == choose(90L, 2L),\n  all(is.finite(assembly_pairs$BetaNTI)),\n  all(assembly_pairs$RCbray >= -1 & assembly_pairs$RCbray <= 1),\n  abs(sum(prop.table(table(assembly_pairs$Process))) - 1) < 1e-12\n)\nas.data.frame(prop.table(table(assembly_pairs$Process)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Var1        Freq\n1 Heterogeneous selection 0.168039950\n2   Homogeneous selection 0.000000000\n3    Dispersal limitation 0.820973783\n4  Homogenizing dispersal 0.006491885\n5             Undominated 0.004494382\n```\n\n\n:::\n:::\n\n\n### 用更严格 feature filter 重跑敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrict_keep <- rowMeans(otutab > 0) >= 0.10 & rowSums(otutab) >= 1000\nstrict_community <- t(otutab[strict_keep, , drop = FALSE])\nstrict_tree <- ape::keep.tip(full_tree, colnames(strict_community))\nstrict_distance <- ape::cophenetic.phylo(strict_tree)\nstrict_distance <- strict_distance[\n  colnames(strict_community), colnames(strict_community), drop = FALSE\n]\nseeded_bnti_strict <- seed_icamp_function(\n  iCAMP::bNTI.cm,\n  \"bMNTD.rand <- parallel::parLapply\",\n  202607381L\n)\nseeded_rcbray_strict <- seed_icamp_function(\n  iCAMP::RC.cm,\n  \"BC.rd <- parallel::parLapply\",\n  202617381L\n)\nstrict_randomizations <- 199L\nstrict_bnti <- seeded_bnti_strict(\n  comm = strict_community,\n  dis = strict_distance,\n  nworker = n_workers,\n  weighted = TRUE,\n  rand = strict_randomizations,\n  output.bMNTD = FALSE,\n  sig.index = \"SES\"\n)$index\nstrict_rcbray <- seeded_rcbray_strict(\n  comm = strict_community,\n  nworker = n_workers,\n  weighted = TRUE,\n  rand = strict_randomizations,\n  sig.index = \"RC\",\n  silent = TRUE\n)$index\nstrict_process <- classify_process(\n  strict_bnti[pair_index], strict_rcbray[pair_index]\n)\nfilter_process_agreement <- mean(\n  strict_process == as.character(assembly_pairs$Process)\n)\nfilter_sensitivity <- rbind(\n  data.frame(\n    Filter = \"Total reads >= 500\",\n    OTUs = sum(primary_keep),\n    ReadFraction = sum(otutab[primary_keep, ]) / sum(otutab),\n    Randomizations = primary_randomizations,\n    Process = levels(assembly_pairs$Process),\n    Fraction = as.numeric(prop.table(table(assembly_pairs$Process))),\n    stringsAsFactors = FALSE\n  ),\n  data.frame(\n    Filter = \"Total reads >= 1000\",\n    OTUs = sum(strict_keep),\n    ReadFraction = sum(otutab[strict_keep, ]) / sum(otutab),\n    Randomizations = strict_randomizations,\n    Process = process_levels,\n    Fraction = as.numeric(prop.table(table(factor(\n      strict_process, levels = process_levels\n    )))),\n    stringsAsFactors = FALSE\n  )\n)\n\ndata.frame(\n  PrimaryOTUs = sum(primary_keep),\n  StrictOTUs = sum(strict_keep),\n  PrimaryReadFraction = sum(otutab[primary_keep, ]) / sum(otutab),\n  StrictReadFraction = sum(otutab[strict_keep, ]) / sum(otutab),\n  PairwiseProcessAgreement = filter_process_agreement\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PrimaryOTUs StrictOTUs PrimaryReadFraction StrictReadFraction\n1         585        220           0.4741738           0.319738\n  PairwiseProcessAgreement\n1                0.8142322\n```\n\n\n:::\n:::\n\n\n## 阈值、树和 null model 怎样改变组装比例？ {#sec-audit}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbnti_audit <- data.frame(\n  Dimension = c(\n    \"Tree\", \"Phylogenetic signal\", \"Regional pool\", \"Feature filter\",\n    \"Randomization\", \"Sequential gate\", \"Pair dependence\", \"Claim\"\n  ),\n  FragilePractice = c(\n    \"Taxonomy tree or unmatched tips\",\n    \"Assume close relatives share niches\",\n    \"Mix unrelated habitats without definition\",\n    \"Hide retained read fraction\",\n    \"Parallel workers without seeded streams\",\n    \"Use RCbray even when |bNTI| > 1.96\",\n    \"Treat all sample pairs as independent\",\n    \"Call fractions measured mechanisms\"\n  ),\n  UpgradedContract = c(\n    \"Rooted branch-length tree plus exact tip audit\",\n    \"Short-range niche-signal gate\",\n    \"Declare metacommunity and pair scope\",\n    \"Primary plus strict filter ledger\",\n    \"999 nulls with deterministic cluster RNG\",\n    \"Selection gate before RCbray\",\n    \"Descriptive fractions or sample-level resampling\",\n    \"Conditional process evidence\"\n  ),\n  stringsAsFactors = FALSE\n)\nknitr::kable(bnti_audit, caption = \"βNTI/RCbray interpretation audit\")\n```\n\n::: {.cell-output-display}\n\n\nTable: βNTI/RCbray interpretation audit\n\n|Dimension           |FragilePractice                              |UpgradedContract                                 |\n|:-------------------|:--------------------------------------------|:------------------------------------------------|\n|Tree                |Taxonomy tree or unmatched tips              |Rooted branch-length tree plus exact tip audit   |\n|Phylogenetic signal |Assume close relatives share niches          |Short-range niche-signal gate                    |\n|Regional pool       |Mix unrelated habitats without definition    |Declare metacommunity and pair scope             |\n|Feature filter      |Hide retained read fraction                  |Primary plus strict filter ledger                |\n|Randomization       |Parallel workers without seeded streams      |999 nulls with deterministic cluster RNG         |\n|Sequential gate     |Use RCbray even when &#124;bNTI&#124; > 1.96 |Selection gate before RCbray                     |\n|Pair dependence     |Treat all sample pairs as independent        |Descriptive fractions or sample-level resampling |\n|Claim               |Call fractions measured mechanisms           |Conditional process evidence                     |\n\n\n:::\n:::\n\n\n主模型保留 585 个 OTU 和 47.4% reads。最近 10% 系统距离的三个预设 niche-signal tests 中，2 个在 BH 后为正且显著，解释门禁为 **CONDITIONAL PASS**。因此 process labels 可以作为 dominant-community、当前 regional pool 和当前环境尺度下的条件性结果，但不升级为因果过程比例。\n\n严格过滤仅保留 220 个 OTU、32.0% reads；与主模型的 pairwise process agreement 为 81.4%。若关键结论随 filter 明显变化，投稿时应扩大计算资源、降低过滤并报告完整 sensitivity grid。\n\n## 解释组装比例前先检查null model {#sec-publication}\n\n### 图 1：检查树上的特征覆盖了多少读数\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntree_counts <- data.frame(\n  Stage = factor(\n    c(\"Source tree\", \"Count table\", \"Primary universe\"),\n    levels = c(\"Source tree\", \"Count table\", \"Primary universe\")\n  ),\n  Tips = c(ape::Ntip(full_tree), nrow(otutab), sum(primary_keep))\n)\ntree_panel <- ggplot(tree_counts, aes(x = Stage, y = Tips, fill = Stage)) +\n  geom_col(width = 0.65, show.legend = FALSE) +\n  geom_text(\n    aes(label = scales::comma(Tips)),\n    vjust = -0.35, family = font_pub, size = 2.8\n  ) +\n  scale_fill_manual(values = unname(pal_pub[c(\"grey\", \"blue\", \"orange\")])) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.14))) +\n  labs(\n    title = \"A. Tree tips are explicitly reconciled\",\n    x = NULL, y = \"Tips / features\"\n  ) +\n  theme_pub(base_size = 8.0) +\n  theme(axis.text.x = element_text(angle = 24, hjust = 1))\n\nretention_panel <- ggplot(\n  sample_retention,\n  aes(x = Group, y = RetainedFraction, fill = Group)\n) +\n  geom_violin(trim = FALSE, alpha = 0.40, colour = NA) +\n  geom_boxplot(width = 0.18, outlier.shape = NA, colour = \"#333333\") +\n  geom_jitter(\n    width = 0.10, shape = 21, size = 1.5,\n    colour = \"white\", stroke = 0.25, alpha = 0.75\n  ) +\n  scale_fill_manual(values = c(\n    CW = pal_pub[[\"blue\"]], IW = pal_pub[[\"orange\"]], TW = pal_pub[[\"green\"]]\n  )) +\n  scale_y_continuous(labels = scales::label_percent()) +\n  labs(\n    title = \"B. Dominant-OTU read retention\",\n    subtitle = sprintf(\"Pooled coverage = %.1f%%\", 100 * sum(primary_counts) / sum(otutab)),\n    x = \"Wetland group\", y = \"Retained sample reads\"\n  ) +\n  theme_pub(base_size = 8.0) +\n  theme(legend.position = \"none\")\n\ntree_filter_plot <- patchwork::wrap_plots(\n  tree_panel, retention_panel, nrow = 1L\n) +\n  patchwork::plot_annotation(\n    title = \"Phylogenetic inference begins with a feature-universe audit\",\n    caption = \"The primary result describes 585 dominant OTUs, not the full rare biosphere.\"\n  )\nsave_pub(tree_filter_plot, \"figures/38-tree-filter\", width = 180, height = 122)\ntree_filter_plot\n```\n\n::: {.cell-output-display}\n![](38-community-assembly-bnti_files/figure-html/fig-tree-filter-1.png){#fig-tree-filter}\n:::\n:::\n\n\n### 图 2：按 βNTI 和 RCbray 依次判断群落构建过程\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprocess_colours <- c(\n  \"Heterogeneous selection\" = pal_pub[[\"vermillion\"]],\n  \"Homogeneous selection\" = pal_pub[[\"blue\"]],\n  \"Dispersal limitation\" = pal_pub[[\"orange\"]],\n  \"Homogenizing dispersal\" = pal_pub[[\"green\"]],\n  \"Undominated\" = pal_pub[[\"grey\"]]\n)\nbnti_rc_plot <- ggplot(\n  assembly_pairs,\n  aes(x = BetaNTI, y = RCbray, colour = Process)\n) +\n  geom_hline(yintercept = c(-0.95, 0.95), linetype = 2, colour = \"#777777\") +\n  geom_vline(xintercept = c(-1.96, 1.96), linetype = 2, colour = \"#777777\") +\n  geom_point(size = 1.25, alpha = 0.42) +\n  scale_colour_manual(values = process_colours, drop = FALSE) +\n  coord_cartesian(ylim = c(-1, 1)) +\n  labs(\n    title = \"Selection is evaluated before RCbray\",\n    subtitle = sprintf(\n      \"%s; %d pairwise comparisons; %d null randomizations\",\n      phylogenetic_signal_gate, nrow(assembly_pairs), primary_randomizations\n    ),\n    x = expression(beta * \"NTI\"), y = expression(\"RC\"[Bray]),\n    colour = \"Process\",\n    caption = \"RCbray labels apply only to pairs with |βNTI| <= 1.96; points are not independent observations.\"\n  ) +\n  theme_pub(base_size = 8.5) +\n  theme(legend.position = \"bottom\", legend.box = \"vertical\") +\n  guides(colour = guide_legend(nrow = 2, byrow = TRUE, title.position = \"top\"))\nsave_pub(bnti_rc_plot, \"figures/38-bnti-rcbray\", width = 180, height = 148)\nbnti_rc_plot\n```\n\n::: {.cell-output-display}\n![](38-community-assembly-bnti_files/figure-html/fig-bnti-rcbray-1.png){#fig-bnti-rcbray}\n:::\n:::\n\n\n### 图 3：比较不同样本配对范围内的过程占比\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprocess_fraction$Process <- factor(\n  process_fraction$Process, levels = rev(process_levels)\n)\nprocess_fraction_plot <- ggplot(\n  process_fraction,\n  aes(x = PairScope, y = Fraction, fill = Process)\n) +\n  geom_col(width = 0.72, colour = \"white\", linewidth = 0.25) +\n  scale_fill_manual(values = process_colours, drop = FALSE) +\n  scale_y_continuous(labels = scales::label_percent(), expand = c(0, 0)) +\n  labs(\n    title = \"Dispersal limitation dominates this filtered pairwise ledger\",\n    subtitle = \"Fractions summarize dependent sample pairs and are not tested with an ordinary contingency table\",\n    x = NULL, y = \"Pairwise process fraction\", fill = \"Process\",\n    caption = \"Between-group and within-group results share the same dominant-OTU regional pool.\"\n  ) +\n  theme_pub(base_size = 8.3) +\n  theme(\n    axis.text.x = element_text(angle = 22, hjust = 1),\n    legend.position = \"bottom\", legend.box = \"vertical\"\n  ) +\n  guides(fill = guide_legend(nrow = 2, byrow = TRUE, title.position = \"top\"))\nsave_pub(\n  process_fraction_plot, \"figures/38-process-fractions\",\n  width = 180, height = 132\n)\nprocess_fraction_plot\n```\n\n::: {.cell-output-display}\n![](38-community-assembly-bnti_files/figure-html/fig-process-fractions-1.png){#fig-process-fractions}\n:::\n:::\n\n\n### 图 4：phylogenetic-signal 与 filter sensitivity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignal_results$Trait <- factor(\n  signal_results$Trait, levels = rev(signal_traits)\n)\nsignal_panel <- ggplot(\n  signal_results,\n  aes(x = ObservedRho, y = Trait, colour = Supported)\n) +\n  geom_errorbarh(\n    aes(xmin = NullLower, xmax = NullUpper),\n    height = 0.18, colour = pal_pub[[\"grey\"]]\n  ) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_point(size = 3) +\n  geom_text(\n    aes(\n      label = sprintf(\"q=%.3f\", QValue),\n      hjust = ifelse(ObservedRho > 0.12, 1.1, -0.1)\n    ),\n    nudge_y = 0.23, family = font_pub, size = 2.5,\n    show.legend = FALSE\n  ) +\n  scale_colour_manual(values = c(\n    \"FALSE\" = pal_pub[[\"grey\"]], \"TRUE\" = pal_pub[[\"vermillion\"]]\n  )) +\n  labs(\n    title = \"A. Short-range niche signal gate\",\n    subtitle = \"Observed rho with 95% label-permutation interval\",\n    x = \"Phylogenetic distance vs niche difference rho\", y = NULL,\n    colour = \"BH supported\"\n  ) +\n  theme_pub(base_size = 8.0) +\n  theme(legend.position = \"bottom\") +\n  coord_cartesian(xlim = c(-0.06, 0.185), clip = \"off\")\n\nfilter_sensitivity$Filter <- factor(\n  filter_sensitivity$Filter,\n  levels = c(\"Total reads >= 500\", \"Total reads >= 1000\")\n)\nfilter_panel <- ggplot(\n  filter_sensitivity,\n  aes(x = Filter, y = Fraction, fill = Process)\n) +\n  geom_col(width = 0.68, colour = \"white\", linewidth = 0.25) +\n  scale_fill_manual(values = process_colours, drop = FALSE) +\n  scale_y_continuous(labels = scales::label_percent(), expand = c(0, 0)) +\n  labs(\n    title = \"B. Feature-filter sensitivity\",\n    subtitle = sprintf(\"Pairwise label agreement = %.1f%%\", 100 * filter_process_agreement),\n    x = NULL, y = \"Overall process fraction\", fill = \"Process\"\n  ) +\n  theme_pub(base_size = 8.0) +\n  theme(\n    axis.text.x = element_text(angle = 20, hjust = 1),\n    legend.position = \"none\"\n  )\n\nsignal_filter_plot <- patchwork::wrap_plots(\n  signal_panel, filter_panel, nrow = 1L, widths = c(1.05, 0.95)\n) +\n  patchwork::plot_annotation(\n    title = \"Assembly-process labels need assumption and preprocessing gates\",\n    caption = \"The primary analysis covers 47.4% of reads; rare-biosphere processes are outside its estimand.\"\n  )\nsave_pub(\n  signal_filter_plot, \"figures/38-phylogenetic-signal\",\n  width = 180, height = 127\n)\nsignal_filter_plot\n```\n\n::: {.cell-output-display}\n![](38-community-assembly-bnti_files/figure-html/fig-phylogenetic-signal-1.png){#fig-phylogenetic-signal}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_dir <- \"results/38-community-assembly-bnti\"\ndir.create(result_dir, recursive = TRUE, showWarnings = FALSE)\nutils::write.table(\n  tree_tip_contract,\n  file.path(result_dir, \"tree-tip-contract.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\nutils::write.table(\n  signal_results,\n  file.path(result_dir, \"phylogenetic-signal.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\nutils::write.table(\n  assembly_pairs,\n  file.path(result_dir, \"pairwise-process-ledger.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\nutils::write.table(\n  filter_sensitivity,\n  file.path(result_dir, \"filter-sensitivity.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\n\nexpected_bases <- c(\n  \"figures/38-tree-filter\",\n  \"figures/38-bnti-rcbray\",\n  \"figures/38-process-fractions\",\n  \"figures/38-phylogenetic-signal\"\n)\nexpected_files <- as.vector(outer(\n  expected_bases, c(\".pdf\", \".svg\", \".png\", \".tiff\"), paste0\n))\nstopifnot(\n  all(file.exists(expected_files)),\n  as.character(utils::packageVersion(\"iCAMP\")) == \"1.5.12\",\n  primary_randomizations == 999L,\n  strict_randomizations == 199L,\n  nrow(assembly_pairs) == 4005L,\n  sum(primary_keep) == 585L,\n  sum(strict_keep) == 220L,\n  identical(probe_one, probe_two),\n  phylogenetic_signal_gate == \"CONDITIONAL PASS\"\n)\n```\n:::\n\n\n::: {.callout-caution title=\"常见坑：审稿人会追问的九件事\"}\n\n1. **用 taxonomy 层级拼一棵树**：βNTI 需要有枝长的系统树，不是分类字符串。  \n2. **tip names 静默丢失**：先报告 missing/extra tips，再显式裁树。  \n3. **不检查 phylogenetic signal**：没有近缘 niche conservatism 时，selection 映射缺少关键前提。  \n4. **把少量 null runs 当正式结果**：主分析至少 999 次，并报告随机数算法与 seed。  \n5. **并行只写 `set.seed()`**：worker stream 也必须被显式固定。  \n6. **所有 pair 都同时读 βNTI 和 RCbray**：RCbray 只分流未越过 selection gate 的 pairs。  \n7. **隐藏 dominant-taxa filter**：报告 taxa 数、总 reads coverage 和逐样本 coverage。  \n8. **把 4,005 pairs 当独立样本做普通检验**：同一样本重复参与多对比较。  \n9. **把 process label 写成因果比例**：它是 null-model-dependent、pool-dependent 的 operational evidence。\n\n:::\n\n## 报告群落构建模型与条件假设的方法与限制 {#sec-methods}\n\n> The OTU table, taxonomy and metadata were read independently and aligned to the rooted branch-length phylogeny distributed with the same `microeco 2.0.0` dataset. The source tree contained 14,096 tips, included all 13,628 count-table OTUs and had 468 extra tips, which were explicitly pruned. The primary dominant-OTU universe required prevalence ≥10% and total abundance ≥500 reads, retaining 585 OTUs and 47.4% of all reads. Before process attribution, short-range phylogenetic signal was evaluated for abundance-weighted pH, conductivity and TOC optima among the closest 10% of phylogenetic distances using 499 taxon-label permutations and Benjamini–Hochberg adjustment. Abundance-weighted βNTI and RCbray were then estimated with 999 null randomizations using `iCAMP 1.5.12`; deterministic L'Ecuyer worker streams were injected with `clusterSetRNGStream` before each internal parallel loop. Pairs with βNTI >1.96 or <−1.96 were assigned to heterogeneous or homogeneous selection, respectively. Remaining pairs were assigned to dispersal limitation (RCbray >0.95), homogenizing dispersal (RCbray <−0.95), or undominated processes. A stricter ≥1,000-read universe was refitted with 199 null randomizations as a preprocessing sensitivity analysis. Random seeds were fixed at 20260738 and documented in the result ledger.\n\n## 将群落构建模型与条件假设用于自己的研究 {#sec-own-data}\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read_keyed_tsv(\"your_data/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"your_data/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"your_data/metadata.tsv\")\nenvironment <- read_keyed_tsv(\"your_data/environment.tsv\")\nfull_tree <- ape::read.tree(\"your_data/rooted-tree.nwk\")\n\n# 必须先通过：\nstopifnot(all(rownames(otutab) %in% full_tree$tip.label))\nstopifnot(ape::is.rooted(full_tree))\n\n# 必须预先定义 regional pool、过滤与环境信号变量：\nprevalence_cutoff <- 0.10\ntotal_read_cutoff <- 500L\nsignal_traits <- c(\"pH\", \"Conductivity\", \"TOC\")\n```\n:::\n\n\n如果 feature 是 ASV，优先使用同一区域 sequence alignment 建树或 reference placement；不要把 SILVA taxonomy 层级当作 phylogenetic distance。若研究有多个分离的 region、season 或 host compartment，应分别定义合理 metacommunity pool，并把 pool definition sensitivity 纳入补充材料。\n\n## 参考 {#sec-references}\n\n- Stegen JC, Lin X, Fredrickson JK, et al. Quantifying community assembly processes and identifying features that impose them. *ISME Journal*. 2013;7:2069–2079. <https://doi.org/10.1038/ismej.2013.93>\n- Stegen JC, Lin X, Fredrickson JK, Konopka AE. Estimating and mapping ecological processes influencing microbial community assembly. *Frontiers in Microbiology*. 2015;6:370. <https://doi.org/10.3389/fmicb.2015.00370>\n- Ning D, Yuan M, Wu L, et al. A quantitative framework reveals ecological drivers of grassland microbial community assembly in response to warming. *Nature Communications*. 2020;11:4717. <https://doi.org/10.1038/s41467-020-18560-z>\n- Wang J, Shen J, Wu Y, et al. Phylogenetic beta diversity in bacterial assemblages across ecosystems: deterministic versus stochastic processes. *ISME Journal*. 2013;7:1310–1321. <https://doi.org/10.1038/ismej.2013.30>\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. <https://doi.org/10.1016/j.geoderma.2018.09.035>\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97:fiaa255. <https://doi.org/10.1093/femsec/fiaa255>\n",
    "supporting": [
      "38-community-assembly-bnti_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "686de5a072f2682585934f3ca23dcef3",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  }
}
