{
  "hash": "73272791d1ccce3571e913df2e73490c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"中性群落模型：Sloan 拟合、迁入率与偏离类群\"\nauthor: \"Peter\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/39-neutral-community-model.R\n  packages:\n  - ggplot2\n  - ggrepel\n  - knitr\n  - patchwork\n  - ragg\n  - scales\n  - svglite\n  - vegan\n---\n\n## 中性模型的偏离不等于确定性机制 {#sec-target}\n\n[Sloan et al. (2006)](https://doi.org/10.1111/j.1462-2920.2005.00956.x)给出了微生物 neutral community model；[Burns et al. (2016)](https://doi.org/10.1038/ismej.2015.142)用 abundance–occupancy 曲线比较斑马鱼不同发育阶段的中性拟合。\n\n::: {.callout-important title=\"先给结论\"}\nNCM 检验的是一个明确的观测模式：在给定 metacommunity pool、局部群落大小和 detection rule 后，taxon 的平均相对丰度能否解释它出现于多少样本。较高 $R^2$ 表示该低维 stochastic model 能复现 occupancy pattern；它**不等于**选择不存在，也不意味着落在 envelope 内的每个 OTU 都是生态学上“中性”的。\n:::\n\n本页使用 `microeco` 2.0.0 随包分发的真实中国湿地 OTU 表：CW、IW、TW 各 30 个样本，共 1,619,670 reads。主模型把全部 90 个样本定义为一个 regional pool；组内模型改变了 pool 和平均 library size，因此只作为分层描述，不把三个 $m$ 当作无偏处理效应比较。\n\n## 下载并读取本次分析的数据 {#sec-setup}\n\n需要 R，以及 `ggplot2`、`ggrepel`、`knitr`、`patchwork`、`ragg`、`scales`、`svglite`、`vegan`。本次使用中国湿地的 OTU count 表、分类表和样本信息表。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"data/small/metadata.tsv\",\n  \"data/small/otutab.tsv\",\n  \"data/small/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(vegan)\n\nset.seed(20260739)\nfont_pub <- \"sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(colour = \"#1A1A1A\", linewidth = 0.3),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(), legend.position = \"top\"\n    )\n}\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot, width = width, height = height,\n    units = units, device = grDevices::cairo_pdf,\n    family = base_family, bg = \"white\"\n  )\n  if (write_svg) ggplot2::ggsave(\n    paste0(file_base, \".svg\"), plot, width = width, height = height,\n    units = units, device = svglite::svglite, bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_png, bg = \"white\"\n  )\n  if (write_tiff) ggplot2::ggsave(\n    paste0(file_base, \".tiff\"), plot, width = width, height = height,\n    units = units, dpi = dpi, device = ragg::agg_tiff,\n    compression = \"lzw\", bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n### 从三件套读取并锁定 sample order\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path, show_col_types = FALSE, progress = FALSE,\n    name_repair = \"minimal\", na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\notutab_raw <- read_keyed_tsv(\"data/small/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"data/small/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"data/small/metadata.tsv\")\notutab <- as.matrix(data.frame(\n  lapply(otutab_raw, as.integer), check.names = FALSE\n))\nrownames(otutab) <- rownames(otutab_raw)\nmetadata$Group <- factor(metadata$Group, levels = c(\"CW\", \"IW\", \"TW\"))\notutab <- otutab[, rownames(metadata), drop = FALSE]\n\nclean_taxon <- function(x) {\n  x <- sub(\"^[A-Za-z]__\", \"\", trimws(as.character(x)))\n  x[\n    is.na(x) | x == \"\" |\n      grepl(\"unclassified|unknown|unassigned|uncultured|metagenome\", x,\n            ignore.case = TRUE)\n  ] <- NA_character_\n  x\n}\nrank_names <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"\n)\ntaxonomy_clean <- as.data.frame(\n  lapply(taxonomy[rownames(otutab), rank_names], clean_taxon),\n  check.names = FALSE\n)\nrownames(taxonomy_clean) <- rownames(otutab)\ndisplay_taxon <- apply(\n  taxonomy_clean[, rev(rank_names), drop = FALSE], 1L,\n  function(x) {\n    value <- x[!is.na(x)][1L]\n    if (length(value)) value else \"Unclassified OTU\"\n  }\n)\nnames(display_taxon) <- rownames(taxonomy_clean)\n\nstopifnot(\n  nrow(otutab) == 13628L,\n  ncol(otutab) == 90L,\n  sum(otutab) == 1619670L,\n  identical(colnames(otutab), rownames(metadata)),\n  all(colSums(otutab) >= 10000L)\n)\n\nhead(otutab[, 1:5])\nhead(taxonomy[, rank_names])\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\nOTU_706   0  1  0  1   0\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\nOTU_706  k__Bacteria                     p__Actinobacteria\n                         Class               Order               Family\nOTU_4272            c__Bacilli       o__Bacillales                  f__\nOTU_236                    c__                 o__                  f__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__\nOTU_32                     c__                 o__                  f__\nOTU_706      c__Actinobacteria       o__Frankiales   f__Nakamurellaceae\n                  Genus Species\nOTU_4272            g__     s__\nOTU_236             g__     s__\nOTU_399             g__     s__\nOTU_1556            g__     s__\nOTU_32              g__     s__\nOTU_706  g__Nakamurella     s__\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/691722146e287afe063bd43e9ce4fa41977fe763/examples/39-neutral-community-model.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"ggplot2\", \"ggrepel\", \"patchwork\", \"ragg\", \"readr\", \"scales\",\n  \"svglite\", \"systemfonts\", \"vegan\"\n))\n```\n:::\n\n\n</details>\n\n## 曲线、参数和偏离各自回答什么 {#sec-theory}\n\n### abundance–occupancy 是模型的观测接口\n\n对 taxon $i$，先计算其在 metacommunity 中的平均相对丰度 $p_i$ 与在局部样本中的 occupancy $f_i$。给定平均局部群落大小 $N$、migration parameter $m$ 和 detection threshold $d$，本页使用 beta distribution 的连续近似：\n\n$$\n\\hat f_i = 1 - F_{\\mathrm{Beta}}\\left(d;\\,Nm p_i,\\,Nm(1-p_i)\\right).\n$$\n\n主分析把 $d$ 设为 $1/N$，即平均 library 中约 1 read 的相对丰度。$m$ 通过最小化 observed occupancy 与 predicted occupancy 的平方误差估计；$Nm$ 常被解释为 immigration 与 local community size 的组合强度。\n\n### 预测区间用于比较模型与观测，不能定义类群的生态属性\n\n本页用 $n$ 个样本下的 exact binomial 2.5%–97.5% quantiles 构造 predicted occupancy envelope：\n\n- **Above neutral**：observed occupancy 高于上界，可能包含广泛选择、持续输入、聚合误差或 detection bias；\n- **Below neutral**：低于下界，可能包含环境过滤、dispersal barrier、竞争、批次或技术 dropout；\n- **Neutral envelope**：当前数据分辨率下没有偏离该模型的证据。\n\n第三类不能改写成“证明中性”。模型有误、区间较宽或统计功效不足时，taxon 同样可能落入 envelope。\n\n### $R^2$ 是 pattern fit，不是过程占比\n\n这里报告\n\n$$\nR^2 = 1 - \\frac{\\sum_i(f_i-\\hat f_i)^2}\n{\\sum_i(f_i-\\bar f)^2}.\n$$\n\n它描述 abundance–occupancy curve 的拟合度，不是“中性过程解释了多少群落构建”。同一份数据中的 compositional sampling、heterogeneous selection 与 dispersal limitation 可以共同产生良好拟合。\n\n### 区域类群库与检出规则会影响模型估计\n\n把三个湿地合并或拆开、用 presence (>0) 或固定 relative-abundance threshold、是否 rarefy，都会改变 occupancy 和 $N$。因此模型必须连同 pool、detection、depth handling 和 taxonomic resolution 报告；不能只给一个 $m$ 与 $R^2$。\n\n<details>\n<summary><strong>深入：为什么不用显著性检验替代 envelope</strong></summary>\n\n13,628 个 OTU 的 occupancy 不是彼此独立的：每个样本的测序深度有限，OTU 相对丰度具有 closure，多数稀有 OTU 共享 detection constraint。逐 OTU 套普通回归 p-value 会制造一个并不存在的独立检验族。本页保留模型预测区间用于诊断，并把 sample bootstrap 用在总体参数 $m$ 的不确定性上。\n\n</details>\n\n## 拟合出现频率与平均丰度的关系 {#sec-code}\n\n### 拟合 Sloan NCM 并构造 predictive envelope\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ncm <- function(counts, detection = NULL) {\n  stopifnot(all(counts >= 0), all(colSums(counts) > 0))\n  relative <- sweep(counts, 2L, colSums(counts), \"/\")\n  mean_abundance <- rowMeans(relative)\n  mean_library <- mean(colSums(counts))\n  if (is.null(detection)) detection <- 1 / mean_library\n  occupancy <- rowMeans(relative >= detection)\n  estimable <- mean_abundance > 0 & mean_abundance < 1\n\n  objective <- function(log10_m) {\n    migration <- 10^log10_m\n    predicted <- stats::pbeta(\n      detection,\n      mean_library * migration * mean_abundance[estimable],\n      mean_library * migration * (1 - mean_abundance[estimable]),\n      lower.tail = FALSE\n    )\n    sum((occupancy[estimable] - predicted)^2)\n  }\n  optimum <- stats::optimize(objective, interval = c(-8, 0))\n  migration <- 10^optimum$minimum\n  predicted <- rep(NA_real_, length(mean_abundance))\n  predicted[estimable] <- stats::pbeta(\n    detection,\n    mean_library * migration * mean_abundance[estimable],\n    mean_library * migration * (1 - mean_abundance[estimable]),\n    lower.tail = FALSE\n  )\n  predicted[mean_abundance <= 0] <- 0\n  predicted[mean_abundance >= 1] <- 1\n  sample_n <- ncol(counts)\n  lower <- stats::qbinom(0.025, sample_n, predicted) / sample_n\n  upper <- stats::qbinom(0.975, sample_n, predicted) / sample_n\n  classification <- ifelse(\n    occupancy > upper, \"Above neutral\",\n    ifelse(occupancy < lower, \"Below neutral\", \"Neutral envelope\")\n  )\n  r_squared <- 1 -\n    sum((occupancy[estimable] - predicted[estimable])^2) /\n    sum((occupancy[estimable] - mean(occupancy[estimable]))^2)\n\n  data.frame(\n    FeatureID = rownames(counts),\n    MeanAbundance = mean_abundance,\n    Occupancy = occupancy,\n    Predicted = predicted,\n    Lower = lower,\n    Upper = upper,\n    Classification = classification,\n    Migration = migration,\n    MeanLibrary = mean_library,\n    Detection = detection,\n    RSquared = r_squared,\n    stringsAsFactors = FALSE\n  )\n}\n\npooled_fit <- fit_ncm(otutab)\npooled_fit$DisplayTaxon <- display_taxon[pooled_fit$FeatureID]\npooled_fit$StandardizedDeviation <- with(\n  pooled_fit,\n  (Occupancy - Predicted) /\n    pmax(sqrt(Predicted * (1 - Predicted) / ncol(otutab)), 1 / ncol(otutab))\n)\nprimary_summary <- unique(pooled_fit[\n  , c(\"Migration\", \"MeanLibrary\", \"Detection\", \"RSquared\")\n])\nclassification_summary <- as.data.frame(\n  table(pooled_fit$Classification), stringsAsFactors = FALSE\n)\nnames(classification_summary) <- c(\"Classification\", \"OTUs\")\n\nstopifnot(\n  nrow(primary_summary) == 1L,\n  primary_summary$Migration > 0,\n  primary_summary$Migration < 1,\n  is.finite(primary_summary$RSquared)\n)\nprimary_summary\nclassification_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Migration MeanLibrary    Detection  RSquared\nOTU_4272 0.1029033    17996.33 5.556687e-05 0.7115455\n    Classification OTUs\n1    Above neutral 4531\n2    Below neutral 1086\n3 Neutral envelope 8011\n```\n\n\n:::\n:::\n\n\n### 对迁入参数 $m$ 进行样本重采样，并分别拟合三类湿地\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_migration <- function(counts, replicates, seed) {\n  set.seed(seed)\n  replicate(replicates, {\n    columns <- sample(seq_len(ncol(counts)), replace = TRUE)\n    unique(fit_ncm(counts[, columns, drop = FALSE])$Migration)\n  })\n}\nsummarise_pool <- function(counts, pool, seed) {\n  fit <- fit_ncm(counts)\n  migration_boot <- bootstrap_migration(\n    counts, replicates = 200L, seed = seed\n  )\n  data.frame(\n    Pool = pool,\n    Samples = ncol(counts),\n    Migration = unique(fit$Migration),\n    Lower = unname(stats::quantile(migration_boot, 0.025)),\n    Upper = unname(stats::quantile(migration_boot, 0.975)),\n    RSquared = unique(fit$RSquared),\n    Detection = unique(fit$Detection),\n    stringsAsFactors = FALSE\n  )\n}\n\npool_ledger <- rbind(\n  summarise_pool(otutab, \"All wetlands\", 20260739L),\n  summarise_pool(\n    otutab[, metadata$Group == \"CW\", drop = FALSE], \"CW\", 20260740L\n  ),\n  summarise_pool(\n    otutab[, metadata$Group == \"IW\", drop = FALSE], \"IW\", 20260741L\n  ),\n  summarise_pool(\n    otutab[, metadata$Group == \"TW\", drop = FALSE], \"TW\", 20260742L\n  )\n)\npool_ledger\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Pool Samples Migration     Lower     Upper  RSquared    Detection\n1 All wetlands      90 0.1029033 0.0916165 0.1210316 0.7115455 5.556687e-05\n2           CW      30 0.2084566 0.1555683 0.2904382 0.6621776 6.124611e-05\n3           IW      30 0.1275119 0.1081285 0.1948382 0.6728028 5.031151e-05\n4           TW      30 0.2398610 0.1866172 0.3178601 0.7666314 5.622631e-05\n```\n\n\n:::\n:::\n\n\n### detection 与测序深度敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixed_detection_fit <- fit_ncm(otutab, detection = 1e-4)\nset.seed(20260739)\nrarefied_otutab <- t(vegan::rrarefy(t(otutab), sample = 10000L))\nrarefied_fit <- fit_ncm(rarefied_otutab)\n\nclassification_sensitivity <- rbind(\n  transform(\n    as.data.frame(table(pooled_fit$Classification), stringsAsFactors = FALSE),\n    Model = \"Primary: 1 / mean depth\"\n  ),\n  transform(\n    as.data.frame(\n      table(fixed_detection_fit$Classification), stringsAsFactors = FALSE\n    ),\n    Model = \"Fixed relative threshold\"\n  ),\n  transform(\n    as.data.frame(table(rarefied_fit$Classification), stringsAsFactors = FALSE),\n    Model = \"Rarefied to 10k reads\"\n  )\n)\nnames(classification_sensitivity)[1:2] <- c(\"Classification\", \"OTUs\")\nclassification_sensitivity$Fraction <- ave(\n  classification_sensitivity$OTUs,\n  classification_sensitivity$Model,\n  FUN = function(x) x / sum(x)\n)\n\nclassification_agreement <- data.frame(\n  Comparison = c(\n    \"Primary vs fixed threshold\", \"Primary vs rarefied\"\n  ),\n  Agreement = c(\n    mean(pooled_fit$Classification == fixed_detection_fit$Classification),\n    mean(pooled_fit$Classification == rarefied_fit$Classification)\n  ),\n  stringsAsFactors = FALSE\n)\n\ndetection_grid <- 10^seq(-5, -3, length.out = 17L)\ndetection_sensitivity <- do.call(rbind, lapply(detection_grid, function(value) {\n  fit <- fit_ncm(otutab, detection = value)\n  data.frame(\n    Detection = value,\n    Migration = unique(fit$Migration),\n    RSquared = unique(fit$RSquared),\n    NeutralFraction = mean(fit$Classification == \"Neutral envelope\"),\n    stringsAsFactors = FALSE\n  )\n}))\n\nstopifnot(\n  all(colSums(rarefied_otutab) == 10000L),\n  nrow(classification_sensitivity) == 9L,\n  nrow(detection_sensitivity) == 17L,\n  all(classification_agreement$Agreement >= 0 &\n        classification_agreement$Agreement <= 1)\n)\nclassification_agreement\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Comparison Agreement\n1 Primary vs fixed threshold 0.6865277\n2        Primary vs rarefied 0.8426768\n```\n\n\n:::\n:::\n\n\n## 迁入率与偏离类群的解释边界 {#sec-audit}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneutral_model_audit <- data.frame(\n  Dimension = c(\n    \"Regional pool\", \"Detection\", \"Sequencing depth\", \"Model fit\",\n    \"Envelope\", \"Taxonomic rank\", \"Group contrast\"\n  ),\n  FragilePractice = c(\n    \"Pool all habitats without justification\",\n    \"Define presence differently across analyses\",\n    \"Ignore library-size-driven occupancy\",\n    \"Translate R-squared into neutral-process percentage\",\n    \"Call every in-envelope taxon neutral\",\n    \"Compare ASV and genus parameters directly\",\n    \"Treat group-specific m as a randomized effect\"\n  ),\n  UpgradedContract = c(\n    \"State source pool and refit plausible strata\",\n    \"Prespecify threshold and show sensitivity\",\n    \"Report N and a depth-handling sensitivity\",\n    \"Use R-squared only as abundance-occupancy fit\",\n    \"Use predictive labels as diagnostic evidence\",\n    \"Keep one feature universe per comparison\",\n    \"Report pool, depth and confounding boundaries\"\n  ),\n  stringsAsFactors = FALSE\n)\nknitr::kable(\n  neutral_model_audit,\n  caption = \"Audit contract for neutral community-model claims\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Audit contract for neutral community-model claims\n\n|Dimension        |FragilePractice                                     |UpgradedContract                              |\n|:----------------|:---------------------------------------------------|:---------------------------------------------|\n|Regional pool    |Pool all habitats without justification             |State source pool and refit plausible strata  |\n|Detection        |Define presence differently across analyses         |Prespecify threshold and show sensitivity     |\n|Sequencing depth |Ignore library-size-driven occupancy                |Report N and a depth-handling sensitivity     |\n|Model fit        |Translate R-squared into neutral-process percentage |Use R-squared only as abundance-occupancy fit |\n|Envelope         |Call every in-envelope taxon neutral                |Use predictive labels as diagnostic evidence  |\n|Taxonomic rank   |Compare ASV and genus parameters directly           |Keep one feature universe per comparison      |\n|Group contrast   |Treat group-specific m as a randomized effect       |Report pool, depth and confounding boundaries |\n\n\n:::\n:::\n\n\n主模型估计 $m=$ 0.103，abundance–occupancy $R^2=$ 0.712；13,628 个 OTU 中有 8011 个落入 95% predictive envelope。把 detection 改为 $10^{-4}$ 后，分类一致率为 68.7%；把所有样本确定性抽平到 10,000 reads 后，一致率为 84.3%。因此“哪些 OTU 偏离”必须和 detection/depth contract 一起解释。\n\n三个湿地的 group-specific $m$ 不能直接归因为 habitat effect：拆分后 local sample number、metacommunity composition、mean depth 与 spatial extent 同时改变。可靠比较应在匹配设计中 bootstrap pool definition，并把环境协变量与批次纳入独立分析。\n\n## 区分模型参数、拟合不足与偏离类群 {#sec-publication}\n\n### 图 1：丰度与检出率的关系及 95% 预测区间\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_colours <- c(\n  \"Above neutral\" = pal_pub[[\"vermillion\"]],\n  \"Neutral envelope\" = pal_pub[[\"grey\"]],\n  \"Below neutral\" = pal_pub[[\"blue\"]]\n)\ncurve_data <- pooled_fit[order(pooled_fit$MeanAbundance), ]\nlabel_data <- pooled_fit[\n  order(-abs(pooled_fit$StandardizedDeviation)),\n]\nlabel_data <- label_data[!duplicated(label_data$DisplayTaxon), ]\nlabel_data <- head(label_data, 8L)\nneutral_curve_plot <- ggplot() +\n  geom_ribbon(\n    data = curve_data,\n    aes(x = MeanAbundance, ymin = Lower, ymax = Upper),\n    fill = \"#BFC5CC\", alpha = 0.45\n  ) +\n  geom_line(\n    data = curve_data,\n    aes(x = MeanAbundance, y = Predicted),\n    colour = \"#202020\", linewidth = 0.65\n  ) +\n  geom_point(\n    data = pooled_fit,\n    aes(x = MeanAbundance, y = Occupancy, colour = Classification),\n    size = 0.8, alpha = 0.42\n  ) +\n  ggrepel::geom_text_repel(\n    data = label_data,\n    aes(x = MeanAbundance, y = Occupancy, label = DisplayTaxon),\n    family = font_pub, size = 2.35, max.overlaps = Inf,\n    min.segment.length = 0, box.padding = 0.45, point.padding = 0.15,\n    force = 1.5, max.time = 2, show.legend = FALSE\n  ) +\n  scale_x_log10(labels = scales::label_scientific()) +\n  scale_y_continuous(limits = c(0, 1), labels = scales::label_percent()) +\n  scale_colour_manual(values = class_colours) +\n  labs(\n    title = \"Neutral model reproduces the pooled abundance-occupancy pattern\",\n    subtitle = sprintf(\n      \"m = %.3f; R² = %.3f; N = %.0f reads\",\n      primary_summary$Migration, primary_summary$RSquared,\n      primary_summary$MeanLibrary\n    ),\n    x = \"Mean relative abundance in the metacommunity\",\n    y = \"Sample occupancy\", colour = \"Predictive class\",\n    caption = \"Ribbon: exact-binomial 95% predictive envelope; labels mark the largest standardized deviations.\"\n  ) +\n  theme_pub(base_size = 8.4) +\n  theme(legend.position = \"bottom\")\nsave_pub(\n  neutral_curve_plot, \"figures/39-neutral-abundance-occupancy\",\n  width = 180, height = 143\n)\nneutral_curve_plot\n```\n\n::: {.cell-output-display}\n![](39-neutral-community-model_files/figure-html/fig-neutral-abundance-occupancy-1.png){#fig-neutral-abundance-occupancy}\n:::\n:::\n\n\n### 图 2：pool-specific immigration estimates\n\n\n::: {.cell}\n\n```{.r .cell-code}\npool_ledger$Pool <- factor(\n  pool_ledger$Pool, levels = rev(c(\"All wetlands\", \"CW\", \"IW\", \"TW\"))\n)\npool_plot <- ggplot(\n  pool_ledger,\n  aes(x = Migration, y = Pool, colour = Pool)\n) +\n  geom_errorbarh(\n    aes(xmin = Lower, xmax = Upper), height = 0.15, linewidth = 0.7\n  ) +\n  geom_point(aes(size = RSquared), shape = 16) +\n  scale_x_log10() +\n  scale_colour_manual(values = c(\n    \"All wetlands\" = pal_pub[[\"grey\"]], \"CW\" = pal_pub[[\"blue\"]],\n    \"IW\" = pal_pub[[\"orange\"]], \"TW\" = pal_pub[[\"green\"]]\n  )) +\n  scale_size_continuous(range = c(3.2, 6.2)) +\n  labs(\n    title = \"Immigration estimates depend on the defined regional pool\",\n    subtitle = \"Points: fitted m; bars: 95% sample-bootstrap interval (200 replicates)\",\n    x = \"Migration parameter m (log scale)\", y = NULL,\n    colour = \"Regional pool\", size = \"Model R²\",\n    caption = \"Group-specific fits also change sample number, mean depth, composition and spatial extent.\"\n  ) +\n  theme_pub(base_size = 8.6) +\n  theme(legend.position = \"bottom\")\nsave_pub(\n  pool_plot, \"figures/39-neutral-pool-migration\",\n  width = 180, height = 122\n)\npool_plot\n```\n\n::: {.cell-output-display}\n![](39-neutral-community-model_files/figure-html/fig-neutral-pool-migration-1.png){#fig-neutral-pool-migration}\n:::\n:::\n\n\n### 图 3：OTU classification 的预处理敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassification_sensitivity$Model <- factor(\n  classification_sensitivity$Model,\n  levels = c(\n    \"Primary: 1 / mean depth\", \"Fixed relative threshold\",\n    \"Rarefied to 10k reads\"\n  )\n)\nclassification_sensitivity$Classification <- factor(\n  classification_sensitivity$Classification,\n  levels = c(\"Below neutral\", \"Neutral envelope\", \"Above neutral\")\n)\nclass_sensitivity_plot <- ggplot(\n  classification_sensitivity,\n  aes(x = Model, y = Fraction, fill = Classification)\n) +\n  geom_col(width = 0.68, colour = \"white\", linewidth = 0.3) +\n  scale_fill_manual(values = class_colours, drop = FALSE) +\n  scale_y_continuous(labels = scales::label_percent(), expand = c(0, 0)) +\n  labs(\n    title = \"Predictive labels move when observation rules change\",\n    subtitle = sprintf(\n      \"Agreement with primary labels: fixed threshold %.1f%%; rarefied %.1f%%\",\n      100 * classification_agreement$Agreement[1],\n      100 * classification_agreement$Agreement[2]\n    ),\n    x = NULL, y = \"Fraction of OTUs\", fill = \"Predictive class\",\n    caption = \"Rarefaction is used only as a sensitivity analysis, with seed 20260739.\"\n  ) +\n  theme_pub(base_size = 8.5) +\n  theme(\n    axis.text.x = element_text(angle = 18, hjust = 1),\n    legend.position = \"bottom\"\n  )\nsave_pub(\n  class_sensitivity_plot, \"figures/39-neutral-classification-sensitivity\",\n  width = 180, height = 122\n)\nclass_sensitivity_plot\n```\n\n::: {.cell-output-display}\n![](39-neutral-community-model_files/figure-html/fig-neutral-classification-sensitivity-1.png){#fig-neutral-classification-sensitivity}\n:::\n:::\n\n\n### 图 4：检查检出阈值改变后模型是否稳定\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_panel <- ggplot(\n  detection_sensitivity, aes(x = Detection, y = Migration)\n) +\n  geom_vline(\n    xintercept = primary_summary$Detection,\n    linetype = 2, colour = pal_pub[[\"grey\"]]\n  ) +\n  geom_line(colour = pal_pub[[\"blue\"]], linewidth = 0.8) +\n  geom_point(colour = pal_pub[[\"blue\"]], size = 1.9) +\n  scale_x_log10(labels = scales::label_scientific()) +\n  scale_y_log10() +\n  labs(\n    title = \"A. Migration estimate\", x = \"Detection threshold\",\n    y = \"Migration parameter m\"\n  ) +\n  theme_pub(base_size = 8.0)\nr2_panel <- ggplot(\n  detection_sensitivity, aes(x = Detection, y = RSquared)\n) +\n  geom_vline(\n    xintercept = primary_summary$Detection,\n    linetype = 2, colour = pal_pub[[\"grey\"]]\n  ) +\n  geom_line(colour = pal_pub[[\"vermillion\"]], linewidth = 0.8) +\n  geom_point(colour = pal_pub[[\"vermillion\"]], size = 1.9) +\n  scale_x_log10(labels = scales::label_scientific()) +\n  labs(\n    title = \"B. Abundance-occupancy fit\", x = \"Detection threshold\",\n    y = \"Model R²\"\n  ) +\n  theme_pub(base_size = 8.0)\ndetection_plot <- patchwork::wrap_plots(m_panel, r2_panel, nrow = 1L) +\n  patchwork::plot_annotation(\n    title = \"Observation limits are part of the neutral-model estimand\",\n    caption = \"Dashed lines mark the primary threshold (1 / mean library size).\"\n  )\nsave_pub(\n  detection_plot, \"figures/39-neutral-detection-sensitivity\",\n  width = 180, height = 122\n)\ndetection_plot\n```\n\n::: {.cell-output-display}\n![](39-neutral-community-model_files/figure-html/fig-neutral-detection-sensitivity-1.png){#fig-neutral-detection-sensitivity}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_dir <- \"results/39-neutral-community-model\"\ndir.create(result_dir, recursive = TRUE, showWarnings = FALSE)\nutils::write.table(\n  pooled_fit,\n  file.path(result_dir, \"otu-neutral-ledger.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\nutils::write.table(\n  pool_ledger,\n  file.path(result_dir, \"pool-migration-ledger.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\nutils::write.table(\n  classification_sensitivity,\n  file.path(result_dir, \"classification-sensitivity.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\nutils::write.table(\n  detection_sensitivity,\n  file.path(result_dir, \"detection-sensitivity.tsv\"),\n  sep = \"\\t\", quote = FALSE, row.names = FALSE\n)\n\nexpected_bases <- c(\n  \"figures/39-neutral-abundance-occupancy\",\n  \"figures/39-neutral-pool-migration\",\n  \"figures/39-neutral-classification-sensitivity\",\n  \"figures/39-neutral-detection-sensitivity\"\n)\nexpected_files <- as.vector(outer(\n  expected_bases, c(\".pdf\", \".svg\", \".png\", \".tiff\"), paste0\n))\nstopifnot(\n  all(file.exists(expected_files)),\n  nrow(pooled_fit) == 13628L,\n  nrow(pool_ledger) == 4L,\n  all(pool_ledger$Migration > 0 & pool_ledger$Migration < 1),\n  unique(pooled_fit$RSquared) > 0.50,\n  all(colSums(rarefied_otutab) == 10000L),\n  setequal(\n    unique(pooled_fit$Classification),\n    c(\"Above neutral\", \"Below neutral\", \"Neutral envelope\")\n  )\n)\n```\n:::\n\n\n::: {.callout-caution title=\"常见坑：审稿人会追问的九件事\"}\n\n1. **不定义 metacommunity pool**：合并不同 habitat 会把 selection gradient 混进 pooled occupancy。  \n2. **把 $m$ 解释为真实迁移率**：它是模型尺度上的 migration parameter，并与 $N$、pool 和 detection 相连。  \n3. **把 $R^2$ 写成中性过程比例**：它只是 abundance–occupancy pattern fit。  \n4. **把 envelope 内 OTU 宣布为中性**：正确表述是“未检测到偏离”。  \n5. **忽略 library size**：低深度样本更难检出稀有 OTU。  \n6. **先过滤偏离模型的稀有类群**：feature filtering 会改变待解释的 rare biosphere。  \n7. **只报一条漂亮曲线**：至少给 detection/depth sensitivity 与 parameter uncertainty。  \n8. **跨 rank 比较 $m$**：aggregation 会同时改变 abundance 与 occupancy。  \n9. **用 observational group difference 写因果**：pool composition、空间范围与环境共线性必须单独处理。\n\n:::\n\n## 报告中性群落模型的方法与限制 {#sec-methods}\n\n> The OTU table, taxonomy and metadata were read independently and aligned by sample identifier. The metacommunity comprised 13,628 OTUs in 90 wetland samples (1,619,670 reads; 30 samples each from CW, IW and TW). For each OTU, mean metacommunity relative abundance and occupancy above a prespecified detection limit of one read per mean library ($d=1/N$) were calculated. The Sloan neutral community model was fitted by minimizing squared error between observed occupancy and the beta-distribution prediction over $10^{-8}\\le m\\le1$. Exact-binomial 95% predictive limits classified OTUs as above, below or within the neutral envelope. Parameter uncertainty was estimated using 200 sample-bootstrap replicates for the pooled dataset and each wetland-specific pool. Sensitivity analyses used a fixed relative-abundance threshold of $10^{-4}$, deterministic rarefaction to 10,000 reads per sample, and 17 detection limits from $10^{-5}$ to $10^{-3}$. Random seeds were fixed at 20260739–20260742. $R^2$ was interpreted as abundance–occupancy fit rather than a fraction of neutral assembly.\n\n## 将中性群落模型用于自己的研究 {#sec-own-data}\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read_keyed_tsv(\"your_data/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"your_data/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"your_data/metadata.tsv\")\n\n# 必改：在拟合前写清 regional pool 与 detection rule。\npool_samples <- rownames(metadata)[metadata$YourPoolColumn == \"TargetPool\"]\ncounts <- as.matrix(otutab[, pool_samples, drop = FALSE])\nfit <- fit_ncm(counts, detection = 1 / mean(colSums(counts)))\n```\n:::\n\n\n若研究问题是“recipient community 从哪个 source 输入”，source pool 应来自设计和生物学，而不是为了提高 $R^2$ 后验挑选。若是 repeated measures、不同 body sites 或多个地理区域，分别拟合只是第一步；pool-level inference 还需要 subject/site-aware resampling 与明确的比较 estimand。\n\n## 参考 {#sec-references}\n\n- Sloan WT, Lunn M, Woodcock S, et al. Quantifying the roles of immigration and chance in shaping prokaryote community structure. *Environmental Microbiology*. 2006;8:732–740. <https://doi.org/10.1111/j.1462-2920.2005.00956.x>\n- Burns AR, Stephens WZ, Stagaman K, et al. Contribution of neutral processes to the assembly of gut microbial communities in the zebrafish over host development. *ISME Journal*. 2016;10:655–664. <https://doi.org/10.1038/ismej.2015.142>\n- Sloan WT, Woodcock S, Lunn M, et al. Modeling taxa-abundance distributions in microbial communities using environmental sequence data. *Microbial Ecology*. 2007;53:443–455. <https://doi.org/10.1007/s00248-006-9141-x>\n- Gloor GB, Macklaim JM, Pawlowsky-Glahn V, Egozcue JJ. Microbiome datasets are compositional: and this is not optional. *Frontiers in Microbiology*. 2017;8:2224. <https://doi.org/10.3389/fmicb.2017.02224>\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. <https://doi.org/10.1016/j.geoderma.2018.09.035>\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97:fiaa255. <https://doi.org/10.1093/femsec/fiaa255>\n",
    "supporting": [
      "39-neutral-community-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "c6bf76df84912d0c60d32a9c57361259",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  }
}
