{
  "hash": "454ea6fd28c968457839f3892dec971a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MMvec/MOFA（菌×代谢物）\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**在同一套配对 IBD 数据上比较四种常被混写成“整合”的 estimands：逐对 Spearman、CCA、MMvec conditional co-occurrence 与 MOFA latent factors；用 holdout error、variance explained、group association 和跨方法 overlap 做审计。  \n> **输入文件：**通用三件套 `data/small/paired-ibd-multiomics/{otutab,taxonomy,metadata}.tsv`，另加 `metabolites.tsv` 与 `metabolite-annotation.tsv`。  \n> **预计资源：**220 个样本；100 个 microbial features、120 个 metabolites。CPU 上 MMvec/MOFA 通常数分钟、峰值内存约 3 GB；四张图导出为 PDF/SVG/600 ppi PNG/LZW-TIFF。\n\n## 联合潜变量模型比较的是共享结构 {#sec-target}\n\n[Morton et al. (2019)](https://doi.org/10.1038/s41592-019-0616-3)用 MMvec 展示 microbe–metabolite conditional probabilities 与 embeddings；[Argelaguet et al. (2020)](https://doi.org/10.1186/s13059-020-02015-1)用 MOFA+ 展示多视图 factors、variance explained 和 loadings。本页不转载原图，而是在 [Franzosa et al. (2019)](https://doi.org/10.1038/s41564-018-0306-4) 数据上重绘 CCA audit、MMvec training trace/ranking 与 MOFA factor summary。\n\n::: {.callout-important title=\"先给结论\"}\nnaive CCA 的前三个 canonical correlations 都超过 0.999，但这里 $p=220$ features、$n=220$ samples，几乎完美的 training correlation 是高维过拟合警报。原生 MMvec 在固定的 153/67 train/holdout split 上运行 100 个 epochs，最低 holdout MAE 为 1844.29，且出现在最后一轮；这提示结果尚未形成内部最优点，不能冒充 early stopping。原生 MOFA2 最终保留 4 个 factors，解释 microbiome 34.8%、metabolome 32.6% 的总 variance，其中 3 个 factors 与 diagnosis group 通过 FDR。Spearman 与 MMvec top-50 pairs 的精确重叠为 0，说明它们不是同一个问题的可互换答案。\n:::\n\n## 四种“整合”方法分别估计什么 {#sec-theory}\n\n### 1. Spearman 是逐对单调 association\n\n它回答“两个 feature 的 ranks 是否共同变化”。优点是透明，缺点是 100 × 120 立即产生 12,000 次检验，而且没有利用跨 feature structure。本文统一 BH correction，并把它当 baseline，而不是 gold standard。\n\n### 2. CCA 最大化两个线性组合的相关\n\nCCA 寻找 $u=Xa$、$v=Yb$ 最大化 $\\mathrm{cor}(u,v)$。当 features 接近或超过 samples 时，模型有足够自由度把 training data 几乎完全对齐；没有 shrinkage、cross-validation 或 test projection 的高 correlation 不应作为主要发现。\n\n### 3. MMvec 建模 conditional log probability\n\nMMvec 学习低维 embeddings，以近似 $P(\\mathrm{metabolite}\\mid\\mathrm{microbe})$ 的 conditional probability/自然参数。co-occurrence score 高表示在模型与数据尺度下相对富集，不等于 Spearman rho，也不是“该菌合成该代谢物”的概率。\n\n### 4. MOFA 把每个视图分解成共享 latent factors\n\n对 view $m$，MOFA 近似\n\n$$\nY^{(m)} \\approx ZW^{(m)\\top}+\\epsilon^{(m)},\n$$\n\n其中 $Z$ 是 sample factors，$W^{(m)}$ 是 view-specific loadings。factor 能由一个或多个 views 驱动；variance explained、loadings 与 external covariates 要一起解释。\n\n<details>\n<summary><strong>深入：top-pair overlap 为什么可以为零</strong></summary>\n\nSpearman 按 marginal rank correlation 排序；MMvec 对 compositional co-occurrence 建模，并把每个 microbe 的 metabolite distribution 归一化。一个 metabolite 可以与很多 microbes 同向随疾病变化而产生高 Spearman，却未必在某个 microbe 条件下有特异 enrichment。零重叠首先说明 estimands 不同，不应被包装成“一个方法失败”。\n\n</details>\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装环境并定义出版级作图函数</strong></summary>\n\n\n::: {.cell}\n\n```{.bash .cell-code}\n# 原生 MMvec 1.0.5 需要旧版 TensorFlow，单独隔离\nCONDA_CHANNEL_PRIORITY=flexible mamba env create -f env/mmvec-native.yml\n\n# Spearman、CCA 与原生 mofapy2\nmamba env create -f env/multiomics.yml\n```\n:::\n\n\nMMvec 1.0.5 依赖 Python 3.7 / TensorFlow 1.15，因此不要把它与现代 MOFA2 环境混装。环境隔离既保留原论文工具，也避免旧依赖污染日常分析环境。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"ggplot2\", \"jsonlite\", \"patchwork\", \"ragg\", \"readr\", \"scales\",\n  \"svglite\", \"systemfonts\"\n))\n```\n:::\n\n\n整仓库使用者可改用 `source(\"R/theme_pub.R\")`；单篇复现直接运行下面定义：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(patchwork)\n\nset.seed(20260748)\nfont_pub <- \"DejaVu Sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(colour = \"#E6E6E6\", linewidth = 0.25),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(fill = \"#F2F2F2\", colour = \"#B3B3B3\"),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(), legend.position = \"top\"\n    )\n}\nsave_pub <- function(plot, file_base, width = 89, height = 70, units = \"mm\", dpi = 600) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(paste0(file_base, \".pdf\"), plot, width = width, height = height,\n                  units = units, device = grDevices::cairo_pdf, family = font_pub, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".svg\"), plot, width = width, height = height,\n                  units = units, device = svglite::svglite, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".png\"), plot, width = width, height = height,\n                  units = units, dpi = dpi, device = ragg::agg_png, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".tiff\"), plot, width = width, height = height,\n                  units = units, dpi = dpi, device = ragg::agg_tiff,\n                  compression = \"lzw\", bg = \"white\")\n  invisible(plot)\n}\n```\n:::\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取三件套与配对 metabolite matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(path, show_col_types = FALSE, progress = FALSE,\n                       name_repair = \"minimal\", na = character())\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\ndata_dir <- \"data/small/paired-ibd-multiomics\"\notutab_raw <- read_keyed_tsv(file.path(data_dir, \"otutab.tsv\"))\ntaxonomy <- read_keyed_tsv(file.path(data_dir, \"taxonomy.tsv\"))\nmetadata <- read_keyed_tsv(file.path(data_dir, \"metadata.tsv\"))\nmetabolites_raw <- read_keyed_tsv(file.path(data_dir, \"metabolites.tsv\"))\nmetabolite_annotation <- read_keyed_tsv(\n  file.path(data_dir, \"metabolite-annotation.tsv\")\n)\notutab <- as.matrix(data.frame(lapply(otutab_raw, as.numeric), check.names = FALSE))\nmetabolites <- as.matrix(data.frame(\n  lapply(metabolites_raw, as.numeric), check.names = FALSE\n))\nrownames(otutab) <- rownames(otutab_raw)\nrownames(metabolites) <- rownames(metabolites_raw)\nstopifnot(\n  nrow(otutab) == 250L, ncol(otutab) == 220L,\n  nrow(metabolites) == 277L, ncol(metabolites) == 220L,\n  identical(colnames(otutab), rownames(metadata)),\n  identical(colnames(metabolites), rownames(metadata)),\n  all(otutab >= 0), all(metabolites >= 0)\n)\nhead(otutab[, 1:5])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        PRISM.7122 PRISM.7147 PRISM.7150 PRISM.7153 PRISM.7184\nMB_G001     453719   10530766   11892271    7512181    1046534\nMB_G002     869654    6592783    3427735     922276    3202362\nMB_G003   10991530    8375177    6081649      38477     513707\nMB_G004      23786    8482569     411525    2994933      25506\nMB_G005      20363    4186641    1152397      24974    1631929\nMB_G006      42243    1231904   12103817        959     536343\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(taxonomy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Kingdom       Phylum       Class           Order          Family\nMB_G001 Bacteria Bacteroidota Bacteroidia   Bacteroidales  Bacteroidaceae\nMB_G002 Bacteria Firmicutes_A  Clostridia  Lachnospirales Lachnospiraceae\nMB_G003 Bacteria Bacteroidota Bacteroidia   Bacteroidales  Bacteroidaceae\nMB_G004 Bacteria Firmicutes_A  Clostridia  Lachnospirales Lachnospiraceae\nMB_G005 Bacteria Firmicutes_A  Clostridia Oscillospirales Ruminococcaceae\nMB_G006 Bacteria Bacteroidota Bacteroidia   Bacteroidales   Rikenellaceae\n                   Genus Species\nMB_G001      Bacteroides      NA\nMB_G002        Blautia_A      NA\nMB_G003      Phocaeicola      NA\nMB_G004     Agathobacter      NA\nMB_G005 Faecalibacterium      NA\nMB_G006        Alistipes      NA\n                                                                                                    Lineage\nMB_G001        d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides\nMB_G002         d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Blautia_A\nMB_G003        d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola\nMB_G004      d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter\nMB_G005 d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Faecalibacterium\nMB_G006           d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Rikenellaceae;g__Alistipes\n             DisplayName\nMB_G001      Bacteroides\nMB_G002        Blautia_A\nMB_G003      Phocaeicola\nMB_G004     Agathobacter\nMB_G005 Faecalibacterium\nMB_G006        Alistipes\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Dataset    Subject StudyGroup Age Age.Units\nPRISM.7122 FRANZOSA_IBD_2019 PRISM.7122         CD  38     Years\nPRISM.7147 FRANZOSA_IBD_2019 PRISM.7147         CD  50     Years\nPRISM.7150 FRANZOSA_IBD_2019 PRISM.7150         CD  41     Years\nPRISM.7153 FRANZOSA_IBD_2019 PRISM.7153         CD  51     Years\nPRISM.7184 FRANZOSA_IBD_2019 PRISM.7184         CD  68     Years\nPRISM.7238 FRANZOSA_IBD_2019 PRISM.7238         CD  67     Years\n                                 DOI\nPRISM.7122 10.1038/s41564-018-0306-4\nPRISM.7147 10.1038/s41564-018-0306-4\nPRISM.7150 10.1038/s41564-018-0306-4\nPRISM.7153 10.1038/s41564-018-0306-4\nPRISM.7184 10.1038/s41564-018-0306-4\nPRISM.7238 10.1038/s41564-018-0306-4\n                                                                         PublicationName\nPRISM.7122 Gut microbiome structure and metabolic activity in inflammatory bowel disease\nPRISM.7147 Gut microbiome structure and metabolic activity in inflammatory bowel disease\nPRISM.7150 Gut microbiome structure and metabolic activity in inflammatory bowel disease\nPRISM.7153 Gut microbiome structure and metabolic activity in inflammatory bowel disease\nPRISM.7184 Gut microbiome structure and metabolic activity in inflammatory bowel disease\nPRISM.7238 Gut microbiome structure and metabolic activity in inflammatory bowel disease\n           FecalCalprotectin antibiotic immunosuppressant mesalamine steroids\nPRISM.7122               207         No               Yes         No       No\nPRISM.7147                NA         No                No        Yes       No\nPRISM.7150               218         No               Yes         No       No\nPRISM.7153                NA         No                No        Yes       No\nPRISM.7184                20         No                No         No       No\nPRISM.7238                 3        Yes               Yes         No      Yes\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metabolites[, 1:5])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        PRISM.7122 PRISM.7147 PRISM.7150 PRISM.7153 PRISM.7184\nMT_M001  1512.2600    512.290  3716.9300    21.9432     0.0000\nMT_M002    51.2708     30.878     0.0000   771.3020   505.4620\nMT_M003   603.6030    345.589    32.4742   185.2380   801.6310\nMT_M004     0.0000      0.000     0.0000     0.0000     0.0000\nMT_M005   235.8610    109.167   227.9400    77.5904    94.4461\nMT_M006     0.0000      0.000     0.0000  1035.2100     0.0000\n```\n\n\n:::\n:::\n\n\n### 2. outcome-blind 固定 analysis matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmicrobe_features <- names(sort(rowSums(otutab), decreasing = TRUE))[1:100]\nmetabolite_variance <- apply(log1p(t(metabolites)), 2, var)\nmetabolite_features <- names(sort(metabolite_variance, decreasing = TRUE))[1:120]\nanalysis_microbes <- otutab[microbe_features, , drop = FALSE]\nanalysis_metabolites <- metabolites[metabolite_features, , drop = FALSE]\nstopifnot(\n  dim(analysis_microbes)[1] == 100L,\n  dim(analysis_metabolites)[1] == 120L,\n  identical(colnames(analysis_microbes), colnames(analysis_metabolites))\n)\n```\n:::\n\n\n### 3. 原生 MMvec：固定 train/holdout split 后直接拟合\n\n先在 diagnosis 各层内固定抽取 70% training samples，共得到 153 个训练样本和 67 个 holdout samples。下面是官方 `mmvec.multimodal.MMvec` 的核心调用；完整脚本还负责读取三件套、outcome-blind feature selection、每轮诊断记录、最佳权重恢复与 conditional probability 导出。\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport tensorflow as tf\nfrom mmvec.multimodal import MMvec\nfrom scipy.sparse import coo_matrix\n\nnp.random.seed(20260726)\n# train_microbes/test_microbes: samples × microbial features\n# train_metabolites/test_metabolites: exactly matched samples × metabolites\ngraph = tf.Graph()\nwith graph.as_default():\n    tf.set_random_seed(20260726)\n    with tf.Session() as session:\n        model = MMvec(\n            latent_dim=4, batch_size=32, learning_rate=1e-5,\n            u_scale=1.0, v_scale=1.0, beta_1=0.9, beta_2=0.95,\n            clipnorm=10.0, device_name=\"/cpu:0\",\n            save_path=\"results/48-mmvec-mofa/mmvec-native-tensorboard\"\n        )\n        model(\n            session,\n            coo_matrix(train_microbes.values), train_metabolites.values,\n            coo_matrix(test_microbes.values), test_metabolites.values\n        )\n        for epoch in range(1, 101):\n            for _ in range(max(1, model.nnz // 32)):\n                session.run(model.train)\n            train_objective, holdout_mae = session.run(\n                [model.log_loss, model.cv]\n            )\n```\n:::\n\n\n### 4. MOFA：两视图、五个起始 factors、automatic pruning\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom mofapy2.run.entry_point import entry_point\n\nentry = entry_point()\nentry.set_data_options(\n    scale_groups=False, scale_views=False,\n    center_groups=True, use_float32=False\n)\nentry.set_data_matrix(\n    [[microbe_z], [metabolite_z]],\n    likelihoods=[\"gaussian\", \"gaussian\"],\n    views_names=[\"Microbiome\", \"Metabolome\"],\n    groups_names=[\"AllSamples\"], samples_names=[sample_ids],\n    features_names=[microbe_ids, metabolite_ids]\n)\nentry.set_model_options(\n    factors=5, spikeslab_weights=True,\n    ard_weights=True, ard_factors=False\n)\nentry.set_train_options(\n    iter=1000, convergence_mode=\"medium\", seed=20260726,\n    dropR2=0.001, gpu_mode=False, verbose=False,\n    outfile=\"results/48-mmvec-mofa/mofa-model.hdf5\"\n)\nentry.build()\nentry.run()\n```\n:::\n\n\n完整固定运行分两步：先跑原生 MMvec，再在现代环境中跑 Spearman、CCA 与原生 `mofapy2`。\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nPYTHONNOUSERSITE=1 OMP_NUM_THREADS=1 TF_CPP_MIN_LOG_LEVEL=2 \\\nconda run -n mmvec-native \\\n  python scripts/run_article48_native_mmvec.py --epochs 100\n\nconda run -n multiomics-native \\\n  python scripts/run_article48_mmvec_mofa.py\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_dir <- \"results/48-mmvec-mofa\"\ncca_scores <- readr::read_tsv(\n  file.path(result_dir, \"cca-scores.tsv\"), show_col_types = FALSE\n)\nmmvec_loss <- readr::read_tsv(\n  file.path(result_dir, \"mmvec-loss.tsv\"), show_col_types = FALSE\n)\nmmvec_pairs <- readr::read_tsv(\n  file.path(result_dir, \"mmvec-top-pairs.tsv\"), show_col_types = FALSE\n)\nmofa_variance <- readr::read_tsv(\n  file.path(result_dir, \"mofa-variance-explained.tsv\"), show_col_types = FALSE\n)\nmofa_scores <- readr::read_tsv(\n  file.path(result_dir, \"mofa-factor-scores.tsv\"), show_col_types = FALSE\n)\nmofa_tests <- readr::read_tsv(\n  file.path(result_dir, \"mofa-factor-group-tests.tsv\"), show_col_types = FALSE\n)\nintegration_summary <- jsonlite::read_json(\n  file.path(result_dir, \"summary.json\"), simplifyVector = TRUE\n)\nstopifnot(\n  integration_summary$spearman_tested_pairs == 12000L,\n  integration_summary$spearman_fdr_hits == 4166L,\n  integration_summary$mmvec_train_samples == 153L,\n  integration_summary$mmvec_holdout_samples == 67L,\n  integration_summary$mmvec_epochs_run == 100L,\n  integration_summary$mmvec_best_epoch_one_based == 100L,\n  integration_summary$mofa_factors_retained == 4L,\n  integration_summary$spearman_mmvec_top50_pair_overlap == 0L\n)\nintegration_summary[c(\n  \"cca_canonical_correlations\", \"mmvec_best_validation_mae\",\n  \"mofa_total_variance_explained_by_view\", \"mofa_group_associated_factors_fdr\"\n)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$cca_canonical_correlations\n[1] 0.9997625 0.9993638 0.9990189\n\n$mmvec_best_validation_mae\n[1] 1844.294\n\n$mofa_total_variance_explained_by_view\n$mofa_total_variance_explained_by_view$Metabolome\n[1] 0.3259248\n\n$mofa_total_variance_explained_by_view$Microbiome\n[1] 0.3482947\n\n\n$mofa_group_associated_factors_fdr\n[1] 3\n```\n\n\n:::\n:::\n\n\n## MMvec 与 MOFA 的结果怎样交叉验证？ {#sec-audit}\n\n1. **CCA 的 0.999 不是胜利。**100 + 120 个 features 对 220 个 samples，training canonical correlation 几乎为 1 正是高维 flexibility；必须 sparse/regularized CCA 并做 held-out projection。\n2. **MMvec 的 holdout 最优点仍在边界。**原生默认方案跑 100 个 epochs，最低 holdout MAE 1844.29 出现在 epoch 100。它不能被写成“已 early stop”；正式分析应预先设定更长上限与 patience，再检查最佳点是否离开边界。\n3. **指标名称按实现核对。**MMvec 1.0.5 的 TensorBoard tag 虽叫 `cv_rmse`，源码实际计算的是 mean absolute error；因此图和结果表统一写 holdout MAE。每个 microbe 的 conditional probabilities 行和最大误差为 $6.9\\times10^{-15}$，而 co-occurrence natural parameter 本身不要求和为 1。\n4. **top list 不应强求重叠。**Spearman 与 MMvec top-50 overlap 为 0；它们回答不同 estimand，不能以“多数投票”制造确定性。\n5. **MOFA factor 需要 external annotation。**5 个初始 factors 被 pruning 为 4 个；3 个与 diagnosis 关联，但 diagnosis 也可能代表 medication、inflammation 或 batch。\n6. **重复训练检查稳定性。**正式项目应跨 seeds 比较 MMvec embeddings/top pairs、MOFA factor matching 与 variance explained，并在独立 cohort 验证预先锁定的 signatures。\n\n::: {.callout-warning title=\"解释边界\"}\nMMvec high score、MOFA shared factor 和 Spearman correlation 都不是 metabolite production evidence。至少需要 microbial genes/pathways、strain resolution、培养/共培养、同位素示踪或 intervention 才能升级机制措辞。\n:::\n\n## 出版级美化 {#sec-beautify}\n\n### 图 1：几乎完美的 CCA 是 audit signal\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncca_long <- do.call(rbind, lapply(1:3, function(component) {\n  data.frame(\n    StudyGroup = cca_scores$StudyGroup,\n    Component = paste0(\"CC\", component),\n    Microbiome = cca_scores[[paste0(\"MicrobiomeCC\", component)]],\n    Metabolome = cca_scores[[paste0(\"MetabolomeCC\", component)]]\n  )\n}))\ncca_cor <- aggregate(cbind(Microbiome, Metabolome) ~ Component,\n                     data = cca_long, FUN = mean)\ncca_labels <- setNames(\n  sprintf(\"r = %.4f\", integration_summary$cca_canonical_correlations),\n  paste0(\"CC\", 1:3)\n)\ngroup_colors <- c(\n  Control = unname(pal_pub[\"blue\"]),\n  CD = unname(pal_pub[\"vermillion\"]),\n  UC = unname(pal_pub[\"orange\"])\n)\np48_1 <- ggplot(cca_long, aes(Microbiome, Metabolome, colour = StudyGroup)) +\n  geom_abline(slope = 1, intercept = 0, linetype = 2, colour = \"#777777\", linewidth = 0.4) +\n  geom_point(size = 1.2, alpha = 0.65) +\n  facet_wrap(~ Component, scales = \"free\") +\n  geom_text(\n    data = data.frame(Component = paste0(\"CC\", 1:3), x = -Inf, y = Inf,\n                      label = unname(cca_labels)),\n    aes(x = x, y = y, label = label), inherit.aes = FALSE,\n    hjust = -0.05, vjust = 1.3, family = font_pub, size = 3\n  ) +\n  scale_color_manual(values = group_colors) +\n  labs(x = \"Microbiome canonical score\", y = \"Metabolome canonical score\",\n       colour = \"Study group\", title = \"Naive CCA: an overfitting warning\",\n       subtitle = \"In-sample correlations require held-out validation\") + theme_pub()\nsave_pub(p48_1, \"figures/48-mmvec-mofa/48-1-cca-overfit-audit\", 180, 78)\np48_1\n```\n\n::: {.cell-output-display}\n![Naive CCA produces near-perfect in-sample canonical correlations in a high-dimensional setting.](48-mmvec-mofa_files/figure-html/fig-cca-overfit-audit-1.png){#fig-cca-overfit-audit}\n:::\n:::\n\n\n### 图 2：MMvec training/holdout trace\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloss_long <- rbind(\n  data.frame(Epoch = mmvec_loss$Epoch,\n             Metric = \"Training objective\", Value = mmvec_loss$TrainLoss),\n  data.frame(Epoch = mmvec_loss$Epoch,\n             Metric = \"Holdout MAE\", Value = mmvec_loss$ValidationMAE)\n)\nloss_long$Metric <- factor(\n  loss_long$Metric, levels = c(\"Training objective\", \"Holdout MAE\")\n)\nbest_epoch <- integration_summary$mmvec_best_epoch_one_based\nbest_labels <- data.frame(\n  Epoch = best_epoch,\n  Value = Inf,\n  Metric = factor(\"Holdout MAE\",\n                  levels = levels(loss_long$Metric)),\n  Label = paste0(\"Best: \", best_epoch)\n)\np48_2 <- ggplot(loss_long, aes(Epoch, Value)) +\n  geom_line(linewidth = 0.7, colour = pal_pub[\"blue\"]) +\n  geom_vline(xintercept = best_epoch, linetype = 2, colour = \"#555555\") +\n  geom_text(data = best_labels, aes(Epoch, Value, label = Label),\n            inherit.aes = FALSE, hjust = 1.04, vjust = 1.25,\n            family = font_pub, size = 2.7) +\n  facet_wrap(~ Metric, ncol = 1, scales = \"free_y\") +\n  labs(x = \"Epoch\", y = \"Metric value\",\n       title = \"Native MMvec optimization\",\n       subtitle = \"Best holdout value occurs at the epoch limit\") +\n  theme_pub(9)\nsave_pub(p48_2, \"figures/48-mmvec-mofa/48-2-mmvec-loss\", 89, 88)\np48_2\n```\n\n::: {.cell-output-display}\n![Native MMvec training objective and holdout MAE shown on separate scales.](48-mmvec-mofa_files/figure-html/fig-mmvec-loss-1.png){#fig-mmvec-loss}\n:::\n:::\n\n\n### 图 3：MMvec conditional co-occurrence ranking\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_mmvec <- head(mmvec_pairs, 15)\ntop_mmvec$Pair <- paste0(top_mmvec$MicrobeName, \"  |  \", top_mmvec$MetaboliteName)\ntop_mmvec$Pair <- factor(top_mmvec$Pair, levels = rev(top_mmvec$Pair))\np48_3 <- ggplot(top_mmvec, aes(score, Pair)) +\n  geom_segment(aes(x = 0, xend = score, yend = Pair), colour = pal_pub[\"sky\"], linewidth = 0.7) +\n  geom_point(colour = pal_pub[\"blue\"], size = 2.8) +\n  labs(x = \"MMvec conditional co-occurrence score\", y = NULL,\n       title = \"Top MMvec pairs\",\n       subtitle = \"Exact overlap with Spearman top 50: 0; estimands differ\") +\n  theme_pub(9)\nsave_pub(p48_3, \"figures/48-mmvec-mofa/48-3-mmvec-top-pairs\", 180, 105)\np48_3\n```\n\n::: {.cell-output-display}\n![Highest MMvec conditional co-occurrence scores.](48-mmvec-mofa_files/figure-html/fig-mmvec-top-pairs-1.png){#fig-mmvec-top-pairs}\n:::\n:::\n\n\n### 图 4：MOFA variance explained 与 diagnosis-linked factors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmofa_variance$Percent <- 100 * mofa_variance$VarianceExplained\np_variance <- ggplot(mofa_variance, aes(Factor, View, fill = Percent)) +\n  geom_tile(colour = \"white\", linewidth = 0.8) +\n  geom_text(aes(label = sprintf(\"%.1f%%\", Percent)), family = font_pub, size = 3) +\n  scale_fill_gradient(low = \"#F7FBFF\", high = pal_pub[\"blue\"]) +\n  labs(x = NULL, y = NULL, fill = \"Variance (%)\", title = \"Variance explained\") +\n  theme_pub(9) + theme(legend.position = \"right\")\n\nmofa_long <- reshape(\n  as.data.frame(mofa_scores),\n  varying = paste0(\"Factor\", 1:4), v.names = \"Score\",\n  timevar = \"Factor\", times = paste0(\"Factor\", 1:4), direction = \"long\"\n)\nmofa_long$Factor <- factor(mofa_long$Factor, levels = paste0(\"Factor\", 1:4))\nq_labels <- setNames(sprintf(\"BH q = %.2g\", mofa_tests$QValue), mofa_tests$Factor)\np_scores <- ggplot(mofa_long, aes(StudyGroup, Score, fill = StudyGroup)) +\n  geom_boxplot(width = 0.62, outlier.shape = NA, alpha = 0.80) +\n  geom_jitter(width = 0.14, size = 0.55, alpha = 0.35) +\n  facet_wrap(~ Factor, scales = \"free_y\", labeller = as_labeller(function(x) {\n    paste0(x, \"\\n\", q_labels[x])\n  })) +\n  scale_fill_manual(values = group_colors) +\n  labs(x = NULL, y = \"Factor score\", fill = \"Study group\",\n       title = \"External association audit\") + theme_pub(9) +\n  theme(axis.text.x = element_text(angle = 35, hjust = 1))\np48_4 <- p_variance / p_scores + plot_layout(heights = c(0.65, 1.35))\nsave_pub(p48_4, \"figures/48-mmvec-mofa/48-4-mofa-summary\", 180, 135)\np48_4\n```\n\n::: {.cell-output-display}\n![MOFA view-wise variance explained and sample factor scores.](48-mmvec-mofa_files/figure-html/fig-mofa-summary-1.png){#fig-mofa-summary}\n:::\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最常追问的六件事\"}\n\n1. 不核对两张表的 sample IDs/order，导致错误配对。\n2. 用 raw counts 做 Euclidean/CCA，忽略 library size 与 composition。\n3. 把 in-sample CCA correlation 当外部 performance。\n4. 只展示 MMvec 最终 objective，不给 holdout trace、seed、split、最佳 epoch 与 probability check。\n5. 把 MOFA factor 与 diagnosis 的 post-hoc association 写成 factor 的定义或因果机制。\n6. 只展示 top pairs/loadings，不报告完整 feature filter、tested family 与稳定性。\n\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> Microbial counts and metabolite intensities from 220 paired samples were aligned by exact sample identifier. The 100 most abundant microbial features and 120 metabolites with the largest log1p variance were selected without using diagnosis labels. Pairwise associations were estimated from CLR-transformed microbial abundances and log1p-transformed metabolite intensities using Spearman correlation, with Benjamini–Hochberg adjustment across 12,000 tests. Naive three-component CCA was retained only as an in-sample overfitting audit. MMvec 1.0.5 was fitted through its native TensorFlow implementation using a diagnosis-stratified 153/67 training/holdout split, four latent dimensions, batch size 32, learning rate $10^{-5}$, 100 epochs and seed 20260726. The epoch with the lowest holdout mean absolute error was restored before exporting conditional log scores and row-normalized probabilities. MOFA2 was fitted through mofapy2 0.7.4 to standardized CLR/log1p views, initialized with five factors and automatic factor pruning, and trained for up to 1,000 iterations using seed 20260726. View-specific variance explained, loadings and sample scores were exported; factor–diagnosis associations were tested using Kruskal–Wallis tests with BH correction. Conditional co-occurrence scores and latent factors were not interpreted as causal or biosynthetic evidence.\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n1. 替换三件套与 metabolite matrix/annotation；两个 views 必须是同一批 biological samples，而不是各自的 group averages。\n2. 根据 detection/prevalence 和 measurement QC outcome-blind 地定 feature universe；不要从全模型结果倒推筛选阈值。\n3. MMvec 的 split、latent dimension、learning rate、epoch 上限与 stopping rule 应通过预先定义的 validation scheme 调整；保存完整 trace。若最佳 epoch 落在上限边界，应增加预算后重新审计，而不是宣称收敛。\n4. MOFA 加入新 view 时分别说明 distribution/normalization，并检查每个 factor 是否被单一技术 batch 主导。\n5. 若目标是 prediction，把 sample split 放在所有 filter/scale/tuning 之前；本篇 factor association 不是 prediction validation。\n\n## 参考 {#sec-references}\n\n- Morton JT, et al. Learning representations of microbe–metabolite interactions. *Nature Methods*. 2019. <https://doi.org/10.1038/s41592-019-0616-3>\n- Argelaguet R, et al. MOFA+: a statistical framework for comprehensive integration of multi-modal single-cell data. *Genome Biology*. 2020. <https://doi.org/10.1186/s13059-020-02015-1>\n- Franzosa EA, et al. Gut microbiome structure and metabolic activity in inflammatory bowel disease. *Nature Microbiology*. 2019. <https://doi.org/10.1038/s41564-018-0306-4>\n- MMvec native implementation, version 1.0.5. <https://github.com/biocore/mmvec>\n- MOFA2 native Python implementation (`mofapy2`), version 0.7.4. <https://github.com/bioFAM/mofapy2>\n- Borenstein Lab. CuratedMetagenomicDataMetabolome. Fixed source commit: `89a519d8c832008fbc6e650453e83e2f04858d02`. <https://github.com/borenstein-lab/CuratedMetagenomicDataMetabolome>\n",
    "supporting": [
      "48-mmvec-mofa_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}
