{
  "hash": "315058c9bfb1a5362252d172be04db12",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"纵向：线性混合模型/轨迹/volatility\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**在重复测量设计中，用线性混合模型估计 Shannon 多样性的组别×时间效应，用 Bray–Curtis 轨迹和相邻时间点 volatility 描述个体内群落变化。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`；metadata 还需包含个体 ID、组别和有序时间点。  \n> **预计资源：**真实示例为 130 个 HITChip 分类单元、222 个样本、38 位参与者和 6 个时间点；普通笔记本约 2–5 分钟，内存低于 1 GB。\n\n## 纵向分析的独立单位是受试者，不是时间点 {#sec-target}\n\n纵向微生物组论文常把同一位参与者的多个样本连成线，并叠加组平均轨迹；若研究整体群落变化，还会画 PCoA 箭头或报告相邻时间点距离。它们共同回答：\n\n> 群落指标是否随时间改变？两组的改变模式是否不同？一次改变发生在个体内，还是主要来自个体间差异？\n\n本例使用 O'Keefe 等人的两周饮食互换研究：非裔美国人与南非农村参与者在基线饮食与互换饮食阶段被重复采样。原研究结合微生物、代谢物和黏膜标志物评估饮食改变；公开的 `dietswap` 对象提供 222 个 HITChip 16S 系统发育芯片丰度谱。[原始论文](https://doi.org/10.1038/ncomms7342)、[Dryad 数据记录](https://doi.org/10.5061/dryad.1mn1n)和[Bioconductor 数据包](https://bioconductor.org/packages/3.19/bioc/html/microbiome.html)给出了可引用来源。\n\nHITChip 不是扩增子测序；它的丰度预处理不能照搬到 ASV 表，但“特征×样本 → 样本内指标 → 重复测量模型”的下游逻辑相同。这里不转载论文原图，而是从公开表格重算四张图。\n\n::: {.callout-important title=\"纵向连线不等于纵向检验\"}\n把同一个体的点连起来只是一种展示。推断必须在模型中声明同一个体内的相关性；把 222 个样本当作 222 个独立观察，会低估标准误并制造过度显著。\n:::\n\n## 为什么普通线性模型不够 {#sec-theory}\n\n对第 (i) 位参与者在时间 (t) 的 Shannon 多样性，可写成：\n\n\\[\ny_{it}=\\beta_0+\\beta_1\\mathrm{Cohort}_i+\\beta_2\\mathrm{Time}_t+\n\\beta_3(\\mathrm{Cohort}_i\\times\\mathrm{Time}_t)+b_i+\\epsilon_{it},\n\\]\n\n其中 (b_i\\) 是个体随机截距，吸收稳定的个体间差异。`Cohort × Time` 交互项检验的是“两组随时间的改变是否不同”，不是某一组单独是否显著。\n\n先记住四点：\n\n1. **时间先按因子建模。** 只有六个预设时间点时，因子模型不强迫轨迹为直线，也便于定位差异发生在哪个阶段。\n2. **个体是随机效应或置换区组。** 重复测量的独立单位是参与者，不是粪便样本。\n3. **AR(1) 是候选结构，不是默认真理。** 相邻时间点残差可能更相似，但样本少、缺失不规则时，额外参数未必改善模型。\n4. **volatility 是个体内距离。** 本例定义为同一参与者相邻观测之间的 Bray–Curtis 距离；值越大表示该时间窗群落改变越大。\n\n<details>\n<summary><strong>深入：随机截距、随机斜率和 AR(1) 分别解决什么</strong></summary>\n\n- 随机截距允许每位参与者有不同基线；\n- 随机斜率允许每位参与者有不同时间趋势，但需要足够个体和时间点；\n- AR(1) 描述同一个体残差随时间间隔衰减的相关性。\n\n三者不是互相替代。复杂模型应由设计和诊断支持，不能只因 AIC 略降就无限加参数。若时间间隔不等，连续时间相关结构 `corCAR1` 往往比离散 `corAR1` 更合适；若结局是计数或比例，则需匹配分布的广义混合模型。\n\n</details>\n\n::: {.callout-note title=\"缺失时间点可以保留，但需说明缺失机制\"}\n混合模型不要求每个人都有全部六个时间点。本例 222 个样本来自 38 人，理论满格为 228 个观测。模型在“给定已纳入协变量后缺失近似随机”的假设下使用可用观测；若失访与症状恶化有关，应做缺失机制与敏感性分析。\n:::\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、获取真实数据和定义作图函数</strong></summary>\n\n首次运行安装依赖：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"nlme\", \"emmeans\", \"vegan\", \"ggplot2\", \"patchwork\",\n  \"scales\", \"digest\", \"svglite\", \"ragg\"\n))\nif (!requireNamespace(\"BiocManager\", quietly = TRUE)) {\n  install.packages(\"BiocManager\")\n}\nBiocManager::install(c(\"phyloseq\", \"microbiome\"))\n```\n:::\n\n\n下面把固定版本源码包中的 `dietswap` 对象导出为标准三件套。SHA-256 可防止下载内容悄然变化。\n\n\n::: {.cell}\n\n```{.r .cell-code}\narchive <- \"data/raw/microbiome_1.26.0.tar.gz\"\nurl <- paste0(\n  \"https://bioconductor.org/packages/3.19/bioc/src/contrib/\",\n  \"microbiome_1.26.0.tar.gz\"\n)\nexpected <- paste0(\n  \"67cc6d117ce9dfbbc472fba828e1bb0d\",\n  \"48c621fb574f4f8d3424f6cc9a77fdab\"\n)\ndir.create(\"data/raw\", recursive = TRUE, showWarnings = FALSE)\ndir.create(\"data/small/longitudinal-dietswap\", recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(archive)) download.file(url, archive, mode = \"wb\")\nstopifnot(identical(\n  digest::digest(archive, algo = \"sha256\", file = TRUE), expected\n))\n\ntmp <- tempfile(\"dietswap-\")\ndir.create(tmp)\nutils::untar(archive, files = \"microbiome/data/dietswap.rda\", exdir = tmp)\ne <- new.env(parent = emptyenv())\nload(file.path(tmp, \"microbiome\", \"data\", \"dietswap.rda\"), envir = e)\nps <- e$dietswap\n\noriginal_names <- phyloseq::taxa_names(ps)\nfeature_ids <- sprintf(\"HT_%03d\", seq_along(original_names))\notutab <- as(phyloseq::otu_table(ps), \"matrix\")\nrownames(otutab) <- feature_ids\ntax0 <- as.data.frame(as(phyloseq::tax_table(ps), \"matrix\"))\ntaxonomy <- data.frame(\n  Kingdom = \"Bacteria\", Phylum = tax0$Phylum, Class = \"\", Order = \"\",\n  Family = tax0$Family, Genus = tax0$Genus, Species = \"\",\n  DisplayName = original_names, row.names = feature_ids,\n  check.names = FALSE\n)\nmeta0 <- as.data.frame(phyloseq::sample_data(ps))\nmetadata <- data.frame(\n  SubjectID = meta0$subject,\n  Sex = tools::toTitleCase(as.character(meta0$sex)),\n  Cohort = ifelse(meta0$nationality == \"AAM\", \"African American\", \"Rural African\"),\n  OriginalCohortCode = meta0$nationality,\n  PhaseCode = meta0$group,\n  Timepoint = as.integer(meta0$timepoint),\n  TimeWithinPhase = as.integer(meta0$timepoint.within.group),\n  BMIGroup = tools::toTitleCase(as.character(meta0$bmi_group)),\n  row.names = meta0$sample,\n  check.names = FALSE\n)\nwrite_piece <- function(x, id, path) {\n  out <- data.frame(setNames(list(rownames(x)), id), x, check.names = FALSE)\n  write.table(out, path, sep = \"\\t\", quote = FALSE, row.names = FALSE, na = \"\")\n}\nbase <- \"data/small/longitudinal-dietswap\"\nwrite_piece(otutab, \"FeatureID\", file.path(base, \"otutab.tsv\"))\nwrite_piece(taxonomy, \"FeatureID\", file.path(base, \"taxonomy.tsv\"))\nwrite_piece(metadata, \"SampleID\", file.path(base, \"metadata.tsv\"))\nunlink(tmp, recursive = TRUE)\n```\n:::\n\n\n出版级作图函数直接定义如下：\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.libPaths(c(\".r-lib\", .libPaths()))\nlibrary(nlme)\nlibrary(emmeans)\nlibrary(vegan)\nlibrary(ggplot2)\nlibrary(patchwork)\n\nset.seed(20260751)\nfont_pub <- \"DejaVu Sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(colour = \"#E6E6E6\", linewidth = 0.25),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\", size = ggplot2::rel(1.15)),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      legend.position = \"top\",\n      legend.key = ggplot2::element_blank()\n    )\n}\nsave_pub <- function(plot, file_base, width = 180, height = 125,\n                     units = \"mm\", dpi = 600) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(paste0(file_base, \".pdf\"), plot, width = width,\n                  height = height, units = units,\n                  device = grDevices::cairo_pdf, family = font_pub, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".svg\"), plot, width = width,\n                  height = height, units = units, device = svglite::svglite,\n                  bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".png\"), plot, width = width,\n                  height = height, units = units, dpi = dpi,\n                  device = ragg::agg_png, bg = \"white\")\n  ggplot2::ggsave(paste0(file_base, \".tiff\"), plot, width = width,\n                  height = height, units = units, dpi = dpi,\n                  device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\")\n  invisible(plot)\n}\n```\n:::\n\n\n整套项目运行时可改用内容相同的 `R/theme_pub.R`；复制单篇时保留上面的定义即可。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取三件套并核对重复测量结构\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase <- \"data/small/longitudinal-dietswap\"\notutab <- as.matrix(read.delim(\n  file.path(base, \"otutab.tsv\"), row.names = 1, check.names = FALSE\n))\ntaxonomy <- read.delim(\n  file.path(base, \"taxonomy.tsv\"), row.names = 1, check.names = FALSE\n)\nmetadata <- read.delim(\n  file.path(base, \"metadata.tsv\"), row.names = 1, check.names = FALSE\n)\nstorage.mode(otutab) <- \"numeric\"\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(otutab >= 0), all(colSums(otutab) > 0),\n  !anyDuplicated(paste(metadata$SubjectID, metadata$Timepoint))\n)\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 130 222\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(taxonomy[, c(\"Phylum\", \"Family\", \"Genus\", \"DisplayName\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Phylum          Family                        Genus\nHT_001  Actinobacteria  Actinobacteria             Actinomycetaceae\nHT_002      Firmicutes         Bacilli                   Aerococcus\nHT_003  Proteobacteria  Proteobacteria                    Aeromonas\nHT_004 Verrucomicrobia Verrucomicrobia                  Akkermansia\nHT_005  Proteobacteria  Proteobacteria Alcaligenes faecalis et rel.\nHT_006   Bacteroidetes   Bacteroidetes           Allistipes et rel.\n                        DisplayName\nHT_001             Actinomycetaceae\nHT_002                   Aerococcus\nHT_003                    Aeromonas\nHT_004                  Akkermansia\nHT_005 Alcaligenes faecalis et rel.\nHT_006           Allistipes et rel.\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SubjectID    Sex           Cohort OriginalCohortCode PhaseCode\nSample-1       byn   Male African American                AAM        DI\nSample-2       nms   Male    Rural African                AFR        HE\nSample-3       olt   Male    Rural African                AFR        HE\nSample-4       pku Female    Rural African                AFR        HE\nSample-5       qjy Female    Rural African                AFR        HE\nSample-6       riv Female    Rural African                AFR        HE\n         Timepoint TimeWithinPhase   BMIGroup\nSample-1         4               1      Obese\nSample-2         2               1       Lean\nSample-3         2               1 Overweight\nSample-4         2               1      Obese\nSample-5         2               1 Overweight\nSample-6         2               1      Obese\n```\n\n\n:::\n\n```{.r .cell-code}\nwith(metadata, table(Cohort, Timepoint))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Timepoint\nCohort              1  2  3  4  5  6\n  African American 21 21 21 20 20 20\n  Rural African    17 16 17 17 15 17\n```\n\n\n:::\n:::\n\n\n先把每个样本转为相对丰度并计算 Shannon。组名在进入图片前统一成英文。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelative <- sweep(otutab, 2, colSums(otutab), \"/\")\nmetadata$Shannon <- -colSums(ifelse(\n  relative > 0, relative * log(relative), 0\n))[rownames(metadata)]\nmetadata$Cohort <- factor(\n  metadata$Cohort,\n  levels = c(\"African American\", \"Rural African\")\n)\nmetadata$TimeFactor <- factor(metadata$Timepoint, levels = 1:6)\nmetadata$TimeLabel <- factor(\n  paste0(\"T\", metadata$Timepoint), levels = paste0(\"T\", 1:6)\n)\n```\n:::\n\n\n### 2. 拟合随机截距主模型\n\n模型比较必须用最大似然（ML）；固定效应估计与区间再用限制最大似然（REML）。不要用 REML 比较固定效应不同的模型。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ri_ml <- nlme::lme(\n  Shannon ~ Cohort * TimeFactor,\n  random = ~ 1 | SubjectID,\n  data = metadata,\n  method = \"ML\",\n  na.action = na.omit,\n  control = nlme::lmeControl(opt = \"optim\")\n)\nfit_ar1_ml <- update(\n  fit_ri_ml,\n  correlation = nlme::corAR1(form = ~ Timepoint | SubjectID)\n)\nfit_ri <- update(fit_ri_ml, method = \"REML\")\nfit_ar1 <- update(fit_ar1_ml, method = \"REML\")\n\nmodel_comparison <- anova(fit_ri_ml, fit_ar1_ml)\nmodel_comparison\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Model df      AIC      BIC    logLik   Test  L.Ratio p-value\nfit_ri_ml      1 14 326.2578 373.8953 -149.1289                        \nfit_ar1_ml     2 15 326.2104 377.2506 -148.1052 1 vs 2 2.047397  0.1525\n```\n\n\n:::\n\n```{.r .cell-code}\nunname(coef(fit_ar1$modelStruct$corStruct, unconstrained = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1383233\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_ri)$tTable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                       Value Std.Error  DF     t-value\n(Intercept)                      2.678359216 0.1118318 174 23.94988581\nCohortRural African             -0.649725213 0.1671986  36 -3.88594819\nTimeFactor2                      0.195833569 0.1371004 174  1.42839574\nTimeFactor3                      0.069342379 0.1371004 174  0.50577824\nTimeFactor4                     -0.002103664 0.1390145 174 -0.01513269\nTimeFactor5                     -0.010935644 0.1390444 174 -0.07864857\nTimeFactor6                     -0.036257436 0.1390444 174 -0.26076153\nCohortRural African:TimeFactor2 -0.040433313 0.2069586 174 -0.19536909\nCohortRural African:TimeFactor3  0.210851518 0.2049774 174  1.02865752\nCohortRural African:TimeFactor4  0.528823766 0.2062626 174  2.56383772\nCohortRural African:TimeFactor5  0.400888671 0.2104606 174  1.90481586\nCohortRural African:TimeFactor6  0.604145863 0.2062827 174  2.92872721\n                                     p-value\n(Intercept)                     5.708640e-57\nCohortRural African             4.199716e-04\nTimeFactor2                     1.549705e-01\nTimeFactor3                     6.136525e-01\nTimeFactor4                     9.879437e-01\nTimeFactor5                     9.374025e-01\nTimeFactor6                     7.945848e-01\nCohortRural African:TimeFactor2 8.453320e-01\nCohortRural African:TimeFactor3 3.050684e-01\nCohortRural African:TimeFactor4 1.119758e-02\nCohortRural African:TimeFactor5 5.845363e-02\nCohortRural African:TimeFactor6 3.859421e-03\n```\n\n\n:::\n:::\n\n\n随机截距模型中，`Rural African × T4` 交互估计为 0.529（P = 0.011），表示两组从 T1 到 T4 的 Shannon 改变量相差约 0.53。T6 交互也为正，但这些时间点检验没有做跨全部结局与分类单元的多重校正，不能挑一个 P 值写成全局结论。\n\n### 3. 得到模型边际均值轨迹\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_means <- as.data.frame(emmeans::emmeans(\n  fit_ri, ~ Cohort * TimeFactor\n))\nmodel_means$Timepoint <- as.integer(as.character(model_means$TimeFactor))\n\ncohort_colours <- c(\n  \"African American\" = pal_pub[[\"blue\"]],\n  \"Rural African\" = pal_pub[[\"orange\"]]\n)\np_alpha <- ggplot(metadata, aes(Timepoint, Shannon, colour = Cohort)) +\n  geom_line(aes(group = SubjectID), linewidth = 0.35, alpha = 0.17) +\n  geom_point(size = 0.9, alpha = 0.25) +\n  geom_ribbon(\n    data = model_means,\n    aes(x = Timepoint, ymin = lower.CL, ymax = upper.CL, fill = Cohort),\n    inherit.aes = FALSE, alpha = 0.16, colour = NA\n  ) +\n  geom_line(\n    data = model_means,\n    aes(Timepoint, emmean, colour = Cohort, group = Cohort),\n    linewidth = 1.05\n  ) +\n  geom_point(\n    data = model_means, aes(Timepoint, emmean, colour = Cohort), size = 2.1\n  ) +\n  scale_x_continuous(breaks = 1:6, labels = paste0(\"T\", 1:6)) +\n  scale_colour_manual(values = cohort_colours) +\n  scale_fill_manual(values = cohort_colours) +\n  labs(\n    title = \"Within-subject diversity trajectories\",\n    subtitle = \"Thin lines: participants; thick lines and bands: mixed-model means and 95% CI\",\n    x = \"Study timepoint\", y = \"Shannon diversity\",\n    colour = \"Cohort\", fill = \"Cohort\"\n  ) +\n  theme_pub(10)\np_alpha\n```\n\n::: {.cell-output-display}\n![](51-longitudinal-analysis_files/figure-html/unnamed-chunk-7-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_alpha, \"figures/51-longitudinal-analysis/51-1-alpha-trajectories\")\n```\n:::\n\n\n### 4. 在 Bray–Curtis 空间画个体轨迹\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbray <- vegan::vegdist(t(relative), method = \"bray\")\npcoa <- stats::cmdscale(bray, k = 5, eig = TRUE, add = TRUE)\npcoa_scores <- data.frame(\n  SampleID = rownames(pcoa$points),\n  Axis1 = pcoa$points[, 1], Axis2 = pcoa$points[, 2]\n)\npcoa_scores <- cbind(\n  pcoa_scores,\n  metadata[pcoa_scores$SampleID,\n           c(\"SubjectID\", \"Cohort\", \"Timepoint\", \"TimeLabel\"), drop = FALSE]\n)\npositive_eigenvalues <- pcoa$eig[pcoa$eig > 0]\naxis_percent <- 100 * pcoa$eig[1:2] / sum(positive_eigenvalues)\ncentroids <- aggregate(\n  cbind(Axis1, Axis2) ~ Cohort + Timepoint, pcoa_scores, mean\n)\n\np_pcoa <- ggplot(pcoa_scores, aes(Axis1, Axis2, colour = Cohort)) +\n  geom_path(\n    aes(group = SubjectID), linewidth = 0.3, alpha = 0.13,\n    arrow = grid::arrow(length = grid::unit(1.2, \"mm\"), type = \"closed\")\n  ) +\n  geom_point(alpha = 0.18, size = 0.8) +\n  geom_path(\n    data = centroids, aes(group = Cohort), linewidth = 1.2,\n    arrow = grid::arrow(length = grid::unit(2.2, \"mm\"), type = \"closed\")\n  ) +\n  geom_point(\n    data = centroids, aes(fill = Cohort), shape = 21, size = 3, colour = \"white\"\n  ) +\n  geom_text(\n    data = centroids[centroids$Timepoint %in% c(1, 4, 6), ],\n    aes(label = paste0(\"T\", Timepoint)), colour = \"#202020\",\n    nudge_y = 0.008, size = 2.8, show.legend = FALSE\n  ) +\n  scale_colour_manual(values = cohort_colours) +\n  scale_fill_manual(values = cohort_colours) +\n  labs(\n    title = \"Bray-Curtis trajectories retain subject history\",\n    subtitle = \"Faint arrows show participants; labelled paths show cohort centroids\",\n    x = sprintf(\"PCoA 1 (%.1f%%)\", axis_percent[1]),\n    y = sprintf(\"PCoA 2 (%.1f%%)\", axis_percent[2]),\n    colour = \"Cohort\", fill = \"Cohort\"\n  ) +\n  coord_equal() + theme_pub(10)\np_pcoa\n```\n\n::: {.cell-output-display}\n![](51-longitudinal-analysis_files/figure-html/unnamed-chunk-8-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_pcoa, \"figures/51-longitudinal-analysis/51-2-pcoa-trajectories\",\n         height = 135)\n```\n:::\n\n\nPCoA 轨迹适合展示方向，却不能把二维箭头长度当成完整 Bray–Curtis 改变量。定量比较应回到原始距离矩阵。\n\n### 5. 计算相邻时间点 volatility\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbray_matrix <- as.matrix(bray)\nvolatility <- do.call(rbind, lapply(split(metadata, metadata$SubjectID), function(x) {\n  x <- x[order(x$Timepoint), , drop = FALSE]\n  if (nrow(x) < 2) return(NULL)\n  do.call(rbind, lapply(seq_len(nrow(x) - 1), function(j) {\n    if (x$Timepoint[j + 1] - x$Timepoint[j] != 1) return(NULL)\n    from <- rownames(x)[j]\n    to <- rownames(x)[j + 1]\n    data.frame(\n      SubjectID = x$SubjectID[j], Cohort = x$Cohort[j],\n      Window = paste0(\"T\", x$Timepoint[j], \"-T\", x$Timepoint[j + 1]),\n      Volatility = unname(bray_matrix[from, to])\n    )\n  }))\n}))\nvolatility$Cohort <- factor(volatility$Cohort, levels = levels(metadata$Cohort))\nvolatility$Window <- factor(\n  volatility$Window, levels = paste0(\"T\", 1:5, \"-T\", 2:6)\n)\nfit_volatility <- nlme::lme(\n  Volatility ~ Cohort * Window,\n  random = ~ 1 | SubjectID,\n  data = volatility,\n  method = \"REML\",\n  control = nlme::lmeControl(opt = \"optim\")\n)\nhead(volatility)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      SubjectID           Cohort Window Volatility\nazh.1       azh African American  T1-T2  0.3418451\nazh.2       azh African American  T2-T3  0.5418188\nazh.3       azh African American  T3-T4  0.4484846\nazh.4       azh African American  T4-T5  0.2380189\nazh.5       azh African American  T5-T6  0.3603050\nazl.1       azl    Rural African  T1-T2  0.1364981\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_volatility)$tTable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                      Value  Std.Error  DF    t-value\n(Intercept)                      0.35873735 0.03926180 134  9.1370577\nCohortRural African              0.02881064 0.05967643  36  0.4827809\nWindowT2-T3                      0.08377707 0.05243575 134  1.5977089\nWindowT3-T4                      0.10657140 0.05314471 134  2.0053059\nWindowT4-T5                     -0.11383573 0.05391689 134 -2.1113185\nWindowT5-T6                     -0.04982433 0.05314471 134 -0.9375218\nCohortRural African:WindowT2-T3 -0.09809526 0.07973856 134 -1.2302111\nCohortRural African:WindowT3-T4 -0.14241519 0.07960155 134 -1.7891008\nCohortRural African:WindowT4-T5 -0.05131649 0.08166176 134 -0.6284029\nCohortRural African:WindowT5-T6 -0.05540311 0.08115400 134 -0.6826910\n                                     p-value\n(Intercept)                     8.884837e-16\nCohortRural African             6.321743e-01\nWindowT2-T3                     1.124633e-01\nWindowT3-T4                     4.694454e-02\nWindowT4-T5                     3.660194e-02\nWindowT5-T6                     3.501769e-01\nCohortRural African:WindowT2-T3 2.207734e-01\nCohortRural African:WindowT3-T4 7.585757e-02\nCohortRural African:WindowT4-T5 5.308097e-01\nCohortRural African:WindowT5-T6 4.959807e-01\n```\n\n\n:::\n\n```{.r .cell-code}\np_volatility <- ggplot(volatility, aes(Window, Volatility, fill = Cohort)) +\n  geom_boxplot(\n    position = position_dodge(width = 0.72), width = 0.62,\n    outlier.shape = NA, alpha = 0.72\n  ) +\n  geom_point(\n    aes(colour = Cohort),\n    position = position_jitterdodge(jitter.width = 0.12, dodge.width = 0.72),\n    size = 0.8, alpha = 0.45\n  ) +\n  scale_colour_manual(values = cohort_colours) +\n  scale_fill_manual(values = cohort_colours) +\n  labs(\n    title = \"Volatility is a within-person distance\",\n    subtitle = \"Bray-Curtis distance between consecutive observed timepoints\",\n    x = \"Consecutive time window\", y = \"Bray-Curtis volatility\",\n    colour = \"Cohort\", fill = \"Cohort\"\n  ) +\n  theme_pub(10) +\n  theme(axis.text.x = element_text(angle = 25, hjust = 1))\np_volatility\n```\n\n::: {.cell-output-display}\n![](51-longitudinal-analysis_files/figure-html/unnamed-chunk-9-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_volatility, \"figures/51-longitudinal-analysis/51-3-volatility\")\n```\n:::\n\n\n这里得到 180 对完整相邻观测。若跳过缺失时间点，不能把 T2 到 T4 当作“T2–T3”或“T3–T4”的 volatility；应保留实际时间差，或改用每单位时间距离。\n\n## 时间相关、缺失和个体异质性 {#sec-audit}\n\n### 相关结构是否改变结论\n\n随机截距与随机截距+AR(1) 的 ML AIC 分别约为 326.26 和 326.21；似然比检验 P = 0.153，AR(1) 参数约 0.139。额外相关参数没有得到强支持，而 T4 交互在两种模型中方向和量级接近。因此主结果保留更简约的随机截距模型，并把 AR(1) 放入敏感性分析。\n\n下面把全部组别×时间交互的区间并排，并对 T4−T1 改变量按**参与者**自助抽样。若按样本行抽样，会破坏重复测量结构。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_fixed <- function(model, label) {\n  x <- summary(model)$tTable\n  critical <- qt(0.975, df = x[, \"DF\"])\n  data.frame(\n    Model = label, Term = rownames(x), Estimate = x[, \"Value\"],\n    Lower = x[, \"Value\"] - critical * x[, \"Std.Error\"],\n    Upper = x[, \"Value\"] + critical * x[, \"Std.Error\"],\n    PValue = x[, \"p-value\"], row.names = NULL\n  )\n}\nfixed_effects <- rbind(\n  extract_fixed(fit_ri, \"Random intercept\"),\n  extract_fixed(fit_ar1, \"Random intercept + AR(1)\")\n)\ninteractions <- fixed_effects[grepl(\"CohortRural African:TimeFactor\", fixed_effects$Term), ]\ninteractions$Timepoint <- sub(\n  \"CohortRural African:TimeFactor\", \"T\", interactions$Term, fixed = TRUE\n)\n\npaired_change <- do.call(rbind, lapply(split(metadata, metadata$SubjectID), function(x) {\n  if (!all(c(1, 4) %in% x$Timepoint)) return(NULL)\n  data.frame(\n    SubjectID = x$SubjectID[1], Cohort = x$Cohort[1],\n    DeltaT4T1 = x$Shannon[x$Timepoint == 4][1] - x$Shannon[x$Timepoint == 1][1]\n  )\n}))\nset.seed(20260751)\nbootstrap_draws <- do.call(rbind, lapply(levels(metadata$Cohort), function(g) {\n  v <- paired_change$DeltaT4T1[paired_change$Cohort == g]\n  data.frame(\n    Cohort = g,\n    MeanChange = replicate(5000, mean(sample(v, length(v), replace = TRUE)))\n  )\n}))\n\np_audit_a <- ggplot(interactions, aes(Estimate, Timepoint, colour = Model)) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#777777\") +\n  geom_errorbarh(\n    aes(xmin = Lower, xmax = Upper),\n    position = position_dodge(width = 0.45), height = 0\n  ) +\n  geom_point(position = position_dodge(width = 0.45), size = 1.8) +\n  scale_colour_manual(values = c(\n    \"Random intercept\" = pal_pub[[\"blue\"]],\n    \"Random intercept + AR(1)\" = pal_pub[[\"vermillion\"]]\n  )) +\n  labs(\n    title = \"A. Correlation-structure audit\",\n    x = \"Cohort-by-time interaction estimate (95% CI)\",\n    y = \"Timepoint vs T1\", colour = \"Model\"\n  ) + theme_pub(9)\n\np_audit_b <- ggplot(bootstrap_draws, aes(MeanChange, fill = Cohort)) +\n  geom_density(alpha = 0.45, colour = NA) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#555555\") +\n  scale_fill_manual(values = cohort_colours) +\n  labs(\n    title = \"B. Participant-level bootstrap\",\n    subtitle = \"Mean Shannon change, T4 minus T1\",\n    x = \"Bootstrapped mean change\", y = \"Density\", fill = \"Cohort\"\n  ) + theme_pub(9)\n\np_audit <- p_audit_a + p_audit_b + patchwork::plot_layout(widths = c(1.25, 1))\np_audit\n```\n\n::: {.cell-output-display}\n![](51-longitudinal-analysis_files/figure-html/unnamed-chunk-10-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(p_audit, \"figures/51-longitudinal-analysis/51-4-model-audit\",\n         height = 115)\n```\n:::\n\n\n### 今天还应补哪些验证\n\n- **先画每个人的采样日历。** 若“时间点”并非相同实际天数，优先使用真实天数和连续时间相关结构。\n- **检查残差与异方差。** 两组或不同阶段方差明显不同时，可用 `weights = varIdent(...)`；不要只盯固定效应 P 值。\n- **预先定义主终点与主时间窗。** 同时测试许多 alpha 指标、距离、菌和时间点时，要控制多重比较。\n- **差异丰度需使用纵向方法。** 对每个菌单独套普通检验会同时忽略重复测量、成分性和零膨胀；应选能声明 subject/block 的方法并做稳健性比较。\n- **饮食阶段与时间完全绑定时要克制。** 时间趋势、适应效应和干预效应可能无法仅靠模型公式分开。\n\n::: {.callout-caution title=\"常见坑：轨迹最容易制造的四种假象\"}\n1. 同一个人的样本未连对，或 sample ID 被误当成 subject ID；  \n2. 先在每个时间点分别做组间检验，再把 P 值变化解释成组别×时间交互；  \n3. PCoA 只画二维投影，却把图上箭头长度当成原始距离；  \n4. 看到纵向先后顺序，就把观察到的改变写成饮食导致的机制。纵向设计加强时间信息，但仍需随机化、依从性、共干预和缺失机制支持因果解释。\n:::\n\n## 出版级美化 {#sec-publication}\n\n四张图承担不同信息，不要堆进一张拥挤的“全能图”：\n\n- 主图优先放混合模型边际均值和 95% CI，个体线用低透明度作为数据层；\n- PCoA 只标关键时间点，个体轨迹淡化、组质心加粗；\n- volatility 明确定义距离和时间窗，避免只写“stability”；\n- 审计图用相同横轴和零参考线，直接比较模型结构与重抽样结果。\n\n`save_pub()` 已同时导出带可编辑文字的 PDF/SVG，以及 600 ppi 的 PNG/TIFF。图中组名、轴、图例和注释均为英文，可直接进入英文稿件。\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> Longitudinal alpha-diversity was analysed using linear mixed-effects models with participant-specific random intercepts. Cohort, categorical study timepoint, and their interaction were included as fixed effects. Models were fitted by restricted maximum likelihood for effect estimation; maximum-likelihood fits were used to compare a random-intercept model with an AR(1) residual correlation model. Estimated marginal means and 95% confidence intervals were reported. Community trajectories were visualised by principal coordinates analysis of Bray–Curtis dissimilarities calculated from sample-wise relative abundances. Within-participant volatility was defined as the Bray–Curtis dissimilarity between consecutive observed timepoints and was analysed using a mixed-effects model with participant as a random intercept. Random procedures used fixed seeds, and participant-level bootstrap resampling was used as a sensitivity analysis.\n\n把 `cohort`、时间定义、随机效应、相关结构、距离、缺失处理、软件版本和 bootstrap 次数替换为自己的实际设置。若主模型用了随机斜率、非线性样条或广义分布，也必须写明。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n三张表仍保持：\n\n- `otutab.tsv`：行为特征、列为样本；\n- `taxonomy.tsv`：行顺序与 `otutab` 完全一致；\n- `metadata.tsv`：行为样本，至少含 `SubjectID`、`Cohort`、`Timepoint`。\n\n替换路径后，重点修改三处：\n\n1. 把 `Cohort` 换成处理/病例状态列，并设定有科学意义的参考水平；\n2. 把 `Timepoint` 换成预先定义的离散访视，或使用实际天数建连续/非线性模型；\n3. 根据真实采样间隔决定 `corAR1`、`corCAR1` 或不加残差相关结构。\n\n若同一受试者还有左右部位、技术重复或中心批次，应把层级结构完整写入模型。不要把多个层级压成一个“复合 ID”后就停止思考。\n\n## 参考 {#sec-references}\n\n- O'Keefe SJD, et al. Fat, fibre and cancer risk in African Americans and rural Africans. *Nature Communications*. 2015;6:6342. [doi:10.1038/ncomms7342](https://doi.org/10.1038/ncomms7342)\n- O'Keefe et al. Diet swap study data. Dryad. [doi:10.5061/dryad.1mn1n](https://doi.org/10.5061/dryad.1mn1n)\n- Lloyd-Price J, et al. Multi-omics of the gut microbial ecosystem in inflammatory bowel diseases. *Nature*. 2019;569:655–662. [doi:10.1038/s41586-019-1237-9](https://doi.org/10.1038/s41586-019-1237-9)\n- Pinheiro JC, Bates DM. *Mixed-Effects Models in S and S-PLUS*. Springer; 2000.\n- Oksanen J, et al. *vegan: Community Ecology Package*. R package.\n",
    "supporting": [
      "51-longitudinal-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}
