{
  "hash": "4a2ff73ce05d401c7aa3d47286851444",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 20 篇 · Alpha 组间检验 + 复现顶刊箱线图\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**比较三个湿地组的 coverage-standardized Alpha diversity，同时报告总体检验、效应量、置信区间和多重比较，而不是只在箱线图上添加星号。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`。  \n> **预计资源：**真实示例含 90 个样本、13,628 个 OTU；完整计算与 5,000 次 bootstrap 通常少于 2 分钟，峰值内存低于 1 GB。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n微生物组论文最常见的 Alpha 结果图，是按病例组、处理组或地点分组的箱线图。它通常被用来回答：\n\n> 各组样本内的群落多样性是否不同？差异方向和不确定性有多大？\n\n一张可投稿的图至少应同时保留：\n\n- 每个独立样本，而不是只画均值或箱体；\n- Alpha 指标的明确定义和标准化口径；\n- 总体检验及其多重比较范围；\n- 成对效应方向、效应量和置信区间；\n- 与研究设计一致的独立、配对或重复测量模型。\n\n本例使用 [`microeco` 2.0.0](https://doi.org/10.1093/femsec/fiaa255) 分发的中国湿地真实 16S 数据。原始研究覆盖内陆、沿海与青藏高原湿地，并讨论了环境梯度与细菌群落的关系。[数据论文（An et al., 2019）](https://doi.org/10.1016/j.geoderma.2018.09.035)提供研究背景。这里从标准三件套重新计算 90% sample coverage 下的 Hill (q=0,1,2)，重绘“原始点 + violin + boxplot”主图，并用效应量 forest plot 承载成对推断。\n\n::: {.callout-important title=\"先给结论\"}\n三个 coverage-standardized Hill 指标的 Kruskal–Wallis 检验均未通过 Holm 校正；九个计划成对比较也没有一个通过 Holm 校正。未经标准化的 raw (q=0) 有一个未校正的名义信号（P = 0.035），但在 10,000 reads 和 90% coverage 下分别变为 P = 0.511 与 P = 0.216。这个例子说明，星号可能首先反映测量口径，而不是稳健的组间生物学差异。\n:::\n\n## 理论：检验之前先锁定设计、指标和检验族 {#sec-theory}\n\n最短的决策顺序是：\n\n1. **确认实验单位是否独立。** 同一受试者、地点、窝、家庭或时间序列中的观测不能当作独立样本。\n2. **预先确定主要 Alpha 指标。** 本例使用相同量纲的 Hill (q=0,1,2)，主口径固定为 90% sample coverage。\n3. **定义一个检验族。** 三个总体检验一起做 Holm 校正；三个指标 × 三个 pair 的九个计划比较构成另一个完整检验族。\n4. **同时报告效应量与区间。** P 值不说明差异有多大；Cliff's delta 表示两组随机抽样时谁更可能取得较高值。\n\n### 独立、配对和重复测量不是三个按钮\n\n| 数据结构 | metadata 最低要求 | 典型分析 |\n|---|---|---|\n| 独立两组 | `Group`，每个实验单位只出现一次 | Wilcoxon–Mann–Whitney 或 Welch t test |\n| 独立三组及以上 | `Group`，每个实验单位只出现一次 | Kruskal–Wallis 或 Welch one-way test |\n| 配对两条件 | `SubjectID`/`PairID` + `Condition` | paired Wilcoxon 或 paired t test |\n| 重复测量 | `SubjectID` + `Time` + `Condition` | mixed-effects model 或适当的纵向模型 |\n| 区组/聚类 | `Block`、`SiteID`、`Family`、`Cage`、`Center` 等 | 在模型或重采样中保留聚类结构 |\n\n当前 metadata 只有 `Group`、`Type` 和 `Saline`，没有 subject、pair、time 或声明的 block 标识，因此可执行的演示分支是三组独立样本分析。**列不存在并不能证明生物学独立**；真实项目仍要回查采样表和实验记录。\n\n<details>\n<summary><strong>深入：Kruskal–Wallis 检验的不是“中位数”三个字</strong></summary>\n\nKruskal–Wallis 先对所有观测联合排序，再比较各组秩和。其原假设涉及组间分布，而不是无条件地只比较中位数。只有各组分布形状和尺度近似、差异可理解为位置平移时，才可把结果简化解释为位置或中位数差异。\n\n因此本例同时做三件事：\n\n- 画出全部样本、violin 轮廓和 boxplot；\n- 保存各组 skewness、IQR 与 Tukey outlier 诊断；\n- 用 Cliff's delta 描述随机抽取一个 A 组样本和一个 B 组样本时的序优势。\n\nCliff's delta 定义为：\n\n\\[\n\\delta=P(X_A>X_B)-P(X_A<X_B), \\qquad -1\\leq\\delta\\leq 1.\n\\]\n\n当 \\(\\delta>0\\) 时，A 组样本倾向于高于 B 组；\\(\\delta=0\\) 表示没有总体序优势。`ProbabilitySuperiority = (delta + 1) / 2` 将相同信息转换为更直观的概率尺度，并把 ties 各分一半。\n\n</details>\n\n<details>\n<summary><strong>深入：为什么不先跑 Shapiro–Wilk 再挑检验</strong></summary>\n\n用同一批数据先检验正态性，再根据 P 值决定 t test 或秩检验，会把一个数据驱动的模型选择步骤隐藏进最终 P 值。样本量小时，正态性检验可能没有能力发现偏离；样本量大时，又可能对不重要的轻微偏离非常敏感。\n\n更透明的做法是：\n\n1. 根据 estimand 和设计预先指定主分析；\n2. 用分布图和残差诊断解释模型是否合适；\n3. 用有清楚 estimand 的替代模型做 sensitivity analysis；\n4. 不根据哪一个方法更显著来选择最终结果。\n\n本例预先把秩分布比较设为主分析，并把不等方差 Welch mean comparison 设为敏感性分析。两条路线都没有显著结果。\n\n</details>\n\n::: {.callout-warning title=\"示例数据的 Group 与 Saline 完全混杂\"}\n`IW` 全部是 non-saline soil，而 `CW` 与 `TW` 全部是 saline soil。因此，即使发现 Group 差异，也不能把它单独归因于地理类别或盐碱状态。本章演示的是组间统计与作图合同，不提供地理或盐碱因果结论。\n:::\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、下载真实数据和定义作图函数</strong></summary>\n\n首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"digest\", \"dplyr\", \"ggplot2\", \"iNEXT\", \"jsonlite\",\n  \"ragg\", \"readr\", \"scales\", \"svglite\", \"systemfonts\", \"vegan\"\n))\n```\n:::\n\n\n数据固定使用 `microeco` 2.0.0 源码包中的真实 16S 示例表。下面代码下载版本锁定的压缩包、核对 SHA-256，并导出标准三件套：\n\n\n::: {.cell}\n\n```{.r .cell-code}\narchive <- \"data/raw/microeco_2.0.0.tar.gz\"\nsource_url <- paste0(\n  \"https://cran.r-project.org/src/contrib/Archive/\",\n  \"microeco/microeco_2.0.0.tar.gz\"\n)\nexpected_sha256 <- paste0(\n  \"454a3b71ceeea86bdd54f475a12b5bac\",\n  \"9c3b124f663b8dc6e560827fca89ebfd\"\n)\n\ndir.create(\"data/raw\", recursive = TRUE, showWarnings = FALSE)\ndir.create(\"data/small\", recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(archive)) {\n  download.file(source_url, archive, mode = \"wb\")\n}\nobserved_sha256 <- digest::digest(\n  file = archive,\n  algo = \"sha256\",\n  serialize = FALSE\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\nrequired <- c(\n  \"microeco/data/otu_table_16S.RData\",\n  \"microeco/data/taxonomy_table_16S.RData\",\n  \"microeco/data/sample_info_16S.RData\"\n)\nextract_dir <- tempfile(\"microeco-data-\")\ndir.create(extract_dir)\nutils::untar(archive, files = required, exdir = extract_dir)\n\ndata_env <- new.env(parent = emptyenv())\nfor (relative_path in required) {\n  load(file.path(extract_dir, relative_path), envir = data_env)\n}\n\nwrite_keyed_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name),\n    x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out,\n    path,\n    sep = \"\\t\",\n    quote = FALSE,\n    row.names = FALSE,\n    na = \"\"\n  )\n}\n\nwrite_keyed_tsv(data_env$otu_table_16S, \"FeatureID\", \"data/small/otutab.tsv\")\nwrite_keyed_tsv(\n  data_env$taxonomy_table_16S,\n  \"FeatureID\",\n  \"data/small/taxonomy.tsv\"\n)\nwrite_keyed_tsv(\n  data_env$sample_info_16S,\n  \"SampleID\",\n  \"data/small/metadata.tsv\"\n)\nunlink(extract_dir, recursive = TRUE)\n```\n:::\n\n\n本页需要的包与出版级函数全部内联：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(digest)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(iNEXT)\nlibrary(readr)\nlibrary(scales)\nlibrary(vegan)\n\nset.seed(20260721)\n\nfont_pub <- \"DejaVu Sans\"\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\",\n        linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\",\n        linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\",\n        size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(\n        colour = \"#666666\",\n        hjust = 0\n      ),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\",\n        colour = \"#B3B3B3\",\n        linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 89,\n  height = 70,\n  units = \"mm\",\n  dpi = 600,\n  write_svg = TRUE,\n  write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf,\n    family = base_family,\n    bg = \"white\"\n  )\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"),\n      plot,\n      width = width,\n      height = height,\n      units = units,\n      device = svglite::svglite,\n      bg = \"white\"\n    )\n  }\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    device = ragg::agg_png,\n    bg = \"white\"\n  )\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"),\n      plot,\n      width = width,\n      height = height,\n      units = units,\n      dpi = dpi,\n      device = ragg::agg_tiff,\n      compression = \"lzw\",\n      bg = \"white\"\n    )\n  }\n  invisible(plot)\n}\n```\n:::\n\n\n整仓库运行时可使用内容相同的 `R/theme_pub.R`；只复制本页时，上面的代码块已经包含全部作图与导出函数。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取三件套并按 ID 对齐\n\n`otutab` 必须是 feature × sample 的非负整数表。Alpha richness 对 singleton 很敏感，因此这里不在计算前做 prevalence 或 abundance 过滤。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\ninput_paths <- c(\n  otutab = \"data/small/otutab.tsv\",\n  taxonomy = \"data/small/taxonomy.tsv\",\n  metadata = \"data/small/metadata.tsv\"\n)\nexpected_sha256 <- c(\n  otutab = \"76fa79c38da889f35978dc86da4641a270961746709ff38049ee5f67e3c6f7a3\",\n  taxonomy = \"725280bb9a0cd9bda7b540022e92af945ceed52527f8b2d220b055b4489f6901\",\n  metadata = \"df24771dccf27607ddf922c6bca2cafa876d946fbe2e09d14b601accce66ba64\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  digest::digest,\n  character(1),\n  algo = \"sha256\",\n  serialize = FALSE,\n  file = TRUE\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\notutab <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\n\notutab <- data.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\nfeature_ids <- rownames(otutab)\nsample_ids <- colnames(otutab)\n\nstopifnot(\n  setequal(feature_ids, rownames(taxonomy)),\n  setequal(sample_ids, rownames(metadata)),\n  all(is.finite(otutab)),\n  all(otutab >= 0),\n  all(abs(otutab - round(otutab)) < .Machine$double.eps^0.5),\n  all(colSums(otutab) > 0)\n)\ntaxonomy <- taxonomy[feature_ids, , drop = FALSE]\nmetadata <- metadata[sample_ids, , drop = FALSE]\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1619670\n```\n\n\n:::\n\n```{.r .cell-code}\notutab[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxonomy[1:5, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\n                         Class               Order               Family Genus\nOTU_4272            c__Bacilli       o__Bacillales                  f__   g__\nOTU_236                    c__                 o__                  f__   g__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae   g__\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__   g__\nOTU_32                     c__                 o__                  f__   g__\n         Species\nOTU_4272     s__\nOTU_236      s__\nOTU_399      s__\nOTU_1556     s__\nOTU_32       s__\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n:::\n\n\n### 2. 先让 metadata 决定分析分支\n\n下面的审计不会把缺失列自动解释成“独立”；它只说明当前表能支持哪条计算路线。独立性仍需由采样设计确认。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubject_candidates <- c(\"SubjectID\", \"Subject\", \"ParticipantID\")\npair_candidates <- c(\"PairID\", \"Pair\", \"MatchedSet\")\ntime_candidates <- c(\"Time\", \"Timepoint\", \"Visit\")\nblock_candidates <- c(\"Block\", \"Batch\", \"SiteID\", \"Center\")\n\npresent_subject <- intersect(subject_candidates, colnames(metadata))\npresent_pair <- intersect(pair_candidates, colnames(metadata))\npresent_time <- intersect(time_candidates, colnames(metadata))\npresent_block <- intersect(block_candidates, colnames(metadata))\n\ndesign_audit <- data.frame(\n  Branch = c(\n    \"Independent groups\",\n    \"Paired two-condition\",\n    \"Repeated measures\",\n    \"Blocked or clustered\"\n  ),\n  RequiredMetadata = c(\n    \"Group with independent experimental units\",\n    \"SubjectID or PairID plus two conditions\",\n    \"SubjectID plus Time and Condition\",\n    \"Block, SiteID, Center, Family, Cage, or Batch\"\n  ),\n  Available = c(\n    \"Group\" %in% colnames(metadata),\n    length(c(present_subject, present_pair)) > 0,\n    length(present_subject) > 0 && length(present_time) > 0,\n    length(present_block) > 0\n  )\n)\n\nselected_branch <- \"Independent three-group\"\nstopifnot(\n  all(c(\"Group\", \"Type\", \"Saline\") %in% colnames(metadata)),\n  length(present_subject) == 0L,\n  length(present_pair) == 0L,\n  length(present_time) == 0L,\n  identical(sort(unique(metadata$Group)), c(\"CW\", \"IW\", \"TW\")),\n  identical(as.integer(table(metadata$Group)[c(\"CW\", \"IW\", \"TW\")]),\n            c(30L, 30L, 30L))\n)\n\ndesign_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Branch                              RequiredMetadata Available\n1   Independent groups     Group with independent experimental units      TRUE\n2 Paired two-condition       SubjectID or PairID plus two conditions     FALSE\n3    Repeated measures             SubjectID plus Time and Condition     FALSE\n4 Blocked or clustered Block, SiteID, Center, Family, Cage, or Batch     FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nselected_branch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Independent three-group\"\n```\n\n\n:::\n\n```{.r .cell-code}\nwith(metadata, table(Group, Saline))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Saline\nGroup Non-saline soil Saline soil\n   CW               0          30\n   IW              30           0\n   TW               0          30\n```\n\n\n:::\n:::\n\n\n`Group × Saline` 表显示完全混杂。后面的 P 值描述三个标签下的样本分布，不识别单独的地理或盐碱效应。\n\n### 3. 从计数表独立计算三种测量口径\n\n主分析使用 90% sample coverage；raw 与 10,000 reads 只用于 sensitivity analysis。三种结果都在本页从计数表计算，不把外部 Alpha 结果表作为隐性输入。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunity <- t(otutab)\nlibrary_size <- rowSums(community)\nobserved <- vegan::specnumber(community)\nshannon <- vegan::diversity(community, index = \"shannon\")\ninverse_simpson <- vegan::diversity(\n  community,\n  index = \"invsimpson\"\n)\n\ngroup_labels <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan Plateau\"\n)\ngroup_levels <- unname(group_labels[c(\"IW\", \"CW\", \"TW\")])\ngroup_palette <- c(\n  \"Inland wetland\" = pal_pub[[\"blue\"]],\n  \"Coastal wetland\" = pal_pub[[\"vermillion\"]],\n  \"Tibetan Plateau\" = pal_pub[[\"green\"]]\n)\ngroup_shapes <- c(\n  \"Inland wetland\" = 21,\n  \"Coastal wetland\" = 22,\n  \"Tibetan Plateau\" = 24\n)\n\nalpha_raw <- rbind(\n  data.frame(\n    SampleID = sample_ids,\n    Order = 0L,\n    HillD = as.numeric(observed)\n  ),\n  data.frame(\n    SampleID = sample_ids,\n    Order = 1L,\n    HillD = as.numeric(exp(shannon))\n  ),\n  data.frame(\n    SampleID = sample_ids,\n    Order = 2L,\n    HillD = as.numeric(inverse_simpson)\n  )\n)\nalpha_raw$Group <- metadata[alpha_raw$SampleID, \"Group\"]\nalpha_raw$GroupLabel <- factor(\n  unname(group_labels[alpha_raw$Group]),\n  levels = group_levels\n)\nalpha_raw$Standardization <- \"Raw counts\"\n\nabundance_list <- setNames(\n  lapply(seq_len(nrow(community)), function(i) {\n    as.numeric(community[i, community[i, ] > 0])\n  }),\n  sample_ids\n)\n\nsize_target <- 10000L\nset.seed(20260721)\nsize_estimate <- iNEXT::estimateD(\n  abundance_list,\n  q = c(0, 1, 2),\n  datatype = \"abundance\",\n  base = \"size\",\n  level = size_target,\n  nboot = 0\n)\nalpha_size <- data.frame(\n  SampleID = size_estimate$Assemblage,\n  Group = metadata[size_estimate$Assemblage, \"Group\"],\n  GroupLabel = unname(\n    group_labels[metadata[size_estimate$Assemblage, \"Group\"]]\n  ),\n  ImpliedReads = size_estimate$m,\n  Method = size_estimate$Method,\n  Order = as.integer(size_estimate$Order.q),\n  SampleCoverage = size_estimate$SC,\n  HillD = size_estimate$qD,\n  Standardization = \"10,000 reads\",\n  stringsAsFactors = FALSE\n)\nalpha_size$GroupLabel <- factor(\n  alpha_size$GroupLabel,\n  levels = group_levels\n)\n\ncoverage_target <- 0.90\nset.seed(20260721)\ncoverage_estimate <- iNEXT::estimateD(\n  abundance_list,\n  q = c(0, 1, 2),\n  datatype = \"abundance\",\n  base = \"coverage\",\n  level = coverage_target,\n  nboot = 0\n)\nalpha_coverage <- data.frame(\n  SampleID = coverage_estimate$Assemblage,\n  Group = metadata[coverage_estimate$Assemblage, \"Group\"],\n  GroupLabel = unname(\n    group_labels[metadata[coverage_estimate$Assemblage, \"Group\"]]\n  ),\n  ObservedReads = as.numeric(\n    library_size[coverage_estimate$Assemblage]\n  ),\n  ImpliedReads = coverage_estimate$m,\n  EffortRatio = coverage_estimate$m / as.numeric(\n    library_size[coverage_estimate$Assemblage]\n  ),\n  Method = coverage_estimate$Method,\n  Order = as.integer(coverage_estimate$Order.q),\n  TargetCoverage = coverage_estimate$SC,\n  HillD = coverage_estimate$qD,\n  Standardization = \"90% coverage\",\n  stringsAsFactors = FALSE\n)\nalpha_coverage$GroupLabel <- factor(\n  alpha_coverage$GroupLabel,\n  levels = group_levels\n)\n\ncoverage_q0 <- alpha_coverage[\n  alpha_coverage$Order == 0L,\n  ,\n  drop = FALSE\n]\nstopifnot(\n  nrow(alpha_raw) == 270L,\n  nrow(alpha_size) == 270L,\n  nrow(alpha_coverage) == 270L,\n  length(unique(alpha_coverage$SampleID)) == 90L,\n  identical(sort(unique(alpha_coverage$Order)), 0:2),\n  sum(coverage_q0$Method == \"Rarefaction\") == 56L,\n  sum(coverage_q0$Method == \"Extrapolation\") == 34L,\n  max(coverage_q0$EffortRatio) <= 1.5\n)\n\nc(\n  samples = length(unique(alpha_coverage$SampleID)),\n  rarefaction_samples = sum(coverage_q0$Method == \"Rarefaction\"),\n  extrapolation_samples = sum(coverage_q0$Method == \"Extrapolation\"),\n  maximum_effort_ratio = max(coverage_q0$EffortRatio)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              samples   rarefaction_samples extrapolation_samples \n            90.000000             56.000000             34.000000 \n maximum_effort_ratio \n             1.452755 \n```\n\n\n:::\n:::\n\n\n### 4. 先描述分布，但不让诊断替我们选择 P 值\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_skewness <- function(x) {\n  n <- length(x)\n  s <- sd(x)\n  if (n < 3L || !is.finite(s) || s == 0) {\n    return(NA_real_)\n  }\n  n / ((n - 1) * (n - 2)) * sum(((x - mean(x)) / s)^3)\n}\n\ngroup_descriptive_summary <- alpha_coverage |>\n  group_by(Order, Group, GroupLabel) |>\n  summarise(\n    Samples = n(),\n    Mean = mean(HillD),\n    SD = sd(HillD),\n    Median = median(HillD),\n    Q25 = quantile(HillD, 0.25),\n    Q75 = quantile(HillD, 0.75),\n    Minimum = min(HillD),\n    Maximum = max(HillD),\n    .groups = \"drop\"\n  )\n\ndistribution_diagnostics <- alpha_coverage |>\n  group_by(Order, Group, GroupLabel) |>\n  summarise(\n    Samples = n(),\n    UniqueValues = n_distinct(HillD),\n    Skewness = sample_skewness(HillD),\n    IQR = IQR(HillD),\n    LowerOutliers = sum(\n      HillD < quantile(HillD, 0.25) - 1.5 * IQR(HillD)\n    ),\n    UpperOutliers = sum(\n      HillD > quantile(HillD, 0.75) + 1.5 * IQR(HillD)\n    ),\n    .groups = \"drop\"\n  )\n\ngroup_descriptive_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 11\n  Order Group GroupLabel  Samples  Mean    SD Median   Q25   Q75 Minimum Maximum\n  <int> <chr> <fct>         <int> <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl>   <dbl>\n1     0 CW    Coastal we…      30 2661.  531.  2634. 2188. 3072.  1711.    3799.\n2     0 IW    Inland wet…      30 2858.  488.  2893. 2608. 3123.  1796.    3944.\n3     0 TW    Tibetan Pl…      30 2585.  636.  2536. 2096. 3088.  1315.    3795.\n4     1 CW    Coastal we…      30  715.  278.   761.  629.  844.   125.    1243.\n5     1 IW    Inland wet…      30  797.  261.   866.  568.  992.   377.    1471.\n6     1 TW    Tibetan Pl…      30  771.  353.   738.  500.  958.   254.    1532.\n7     2 CW    Coastal we…      30  206.  112.   237.  117.  308.    19.9    364.\n8     2 IW    Inland wet…      30  213.  101.   208.  133.  274.    51.3    514.\n9     2 TW    Tibetan Pl…      30  213.  152.   166.  122.  238.    23.0    597.\n```\n\n\n:::\n\n```{.r .cell-code}\ndistribution_diagnostics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 9\n  Order Group GroupLabel      Samples UniqueValues Skewness   IQR LowerOutliers\n  <int> <chr> <fct>             <int>        <int>    <dbl> <dbl>         <int>\n1     0 CW    Coastal wetland      30           30   0.103   884.             0\n2     0 IW    Inland wetland       30           30   0.0988  515.             1\n3     0 TW    Tibetan Plateau      30           30   0.126   992.             0\n4     1 CW    Coastal wetland      30           30  -0.369   215.             4\n5     1 IW    Inland wetland       30           30   0.149   424.             0\n6     1 TW    Tibetan Plateau      30           30   0.596   458.             0\n7     2 CW    Coastal wetland      30           30  -0.349   191.             0\n8     2 IW    Inland wetland       30           30   0.677   142.             0\n9     2 TW    Tibetan Plateau      30           30   1.29    115.             0\n# ℹ 1 more variable: UpperOutliers <int>\n```\n\n\n:::\n:::\n\n\n`q=1` 与 `q=2` 在部分组有长尾和 Tukey outliers，所以正文把 Kruskal–Wallis 解释为秩分布比较，而不把它缩写成“中位数检验”。\n\n### 5. 三个总体检验构成一个主检验族\n\nepsilon-squared 使用 \\((H-k+1)/(n-k)\\)，负的小样本估计截为 0。它描述秩差异的总体量级，不替代原始分布图。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomnibus_rows <- lapply(0:2, function(order_q) {\n  x <- alpha_coverage[\n    alpha_coverage$Order == order_q,\n    ,\n    drop = FALSE\n  ]\n  fit <- kruskal.test(HillD ~ GroupLabel, data = x)\n  h <- unname(fit$statistic)\n  k <- nlevels(droplevels(x$GroupLabel))\n  n_total <- nrow(x)\n  data.frame(\n    Order = order_q,\n    Metric = paste0(\"Hill q=\", order_q),\n    H = h,\n    DF = unname(fit$parameter),\n    PValue = fit$p.value,\n    EpsilonSquared = max(0, (h - k + 1) / (n_total - k))\n  )\n})\nomnibus_tests <- bind_rows(omnibus_rows) |>\n  mutate(\n    PAdjustedHolm = p.adjust(PValue, method = \"holm\"),\n    RejectHolm05 = PAdjustedHolm < 0.05\n  )\n\nomnibus_tests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Order   Metric         H DF    PValue EpsilonSquared PAdjustedHolm\n1     0 Hill q=0 3.0613919  2 0.2163850     0.01219991     0.6491551\n2     1 Hill q=1 1.0663736  2 0.5867322     0.00000000     1.0000000\n3     2 Hill q=2 0.4232479  2 0.8092690     0.00000000     1.0000000\n  RejectHolm05\n1        FALSE\n2        FALSE\n3        FALSE\n```\n\n\n:::\n:::\n\n\n结果为：\n\n- (q=0)：(H=3.061)，raw P = 0.216，Holm P = 0.649，\\(\\epsilon^2=0.012\\)；\n- (q=1)：(H=1.066)，raw P = 0.587，Holm P = 1.000，\\(\\epsilon^2=0\\)；\n- (q=2)：(H=0.423)，raw P = 0.809，Holm P = 1.000，\\(\\epsilon^2=0\\)。\n\n这里的“没有拒绝原假设”不等于证明三组完全相同；它表示当前样本与分析精度不足以支持预先指定的组间差异声明。\n\n### 6. 九个计划成对比较统一做 Holm 校正\n\n每个 contrast 的方向固定为 `GroupA minus GroupB`。bootstrap 在两组内部各自重采样，保留原组样本数，不把所有样本混合后再抽。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncliffs_delta <- function(x, y) {\n  differences <- outer(x, y, \"-\")\n  (sum(differences > 0) - sum(differences < 0)) /\n    length(differences)\n}\n\nbootstrap_delta <- function(x, y, replicates, seed) {\n  set.seed(seed)\n  values <- vapply(\n    seq_len(replicates),\n    function(i) {\n      xb <- sample(x, length(x), replace = TRUE)\n      yb <- sample(y, length(y), replace = TRUE)\n      cliffs_delta(xb, yb)\n    },\n    numeric(1)\n  )\n  c(\n    lower = unname(quantile(values, 0.025, names = FALSE)),\n    upper = unname(quantile(values, 0.975, names = FALSE)),\n    valid = sum(is.finite(values))\n  )\n}\n\nbootstrap_replicates <- 5000L\npair_definitions <- combn(group_levels, 2L, simplify = FALSE)\npairwise_rows <- list()\nrow_id <- 0L\n\nfor (order_q in 0:2) {\n  order_data <- alpha_coverage[\n    alpha_coverage$Order == order_q,\n    ,\n    drop = FALSE\n  ]\n  for (pair in pair_definitions) {\n    row_id <- row_id + 1L\n    x <- order_data$HillD[\n      order_data$GroupLabel == pair[[1L]]\n    ]\n    y <- order_data$HillD[\n      order_data$GroupLabel == pair[[2L]]\n    ]\n    wilcox_fit <- suppressWarnings(\n      wilcox.test(x, y, exact = FALSE, correct = TRUE)\n    )\n    delta <- cliffs_delta(x, y)\n    delta_ci <- bootstrap_delta(\n      x,\n      y,\n      replicates = bootstrap_replicates,\n      seed = 20260721L + 100L * order_q + row_id\n    )\n\n    pairwise_rows[[row_id]] <- data.frame(\n      Order = order_q,\n      GroupA = pair[[1L]],\n      GroupB = pair[[2L]],\n      Contrast = paste(pair[[1L]], \"minus\", pair[[2L]]),\n      NGroupA = length(x),\n      NGroupB = length(y),\n      MedianGroupA = median(x),\n      MedianGroupB = median(y),\n      WilcoxonW = unname(wilcox_fit$statistic),\n      PValue = wilcox_fit$p.value,\n      CliffsDelta = delta,\n      ProbabilitySuperiority = (delta + 1) / 2,\n      DeltaLower95 = delta_ci[[\"lower\"]],\n      DeltaUpper95 = delta_ci[[\"upper\"]],\n      BootstrapReplicates = bootstrap_replicates,\n      BootstrapValid = as.integer(delta_ci[[\"valid\"]])\n    )\n  }\n}\n\npairwise_tests <- bind_rows(pairwise_rows) |>\n  mutate(\n    PAdjustedHolm = p.adjust(PValue, method = \"holm\"),\n    RejectHolm05 = PAdjustedHolm < 0.05\n  )\n\nstopifnot(\n  nrow(pairwise_tests) == 9L,\n  all(pairwise_tests$BootstrapValid == bootstrap_replicates),\n  all(abs(pairwise_tests$CliffsDelta) <= 1),\n  all(pairwise_tests$DeltaLower95 <= pairwise_tests$CliffsDelta),\n  all(pairwise_tests$CliffsDelta <= pairwise_tests$DeltaUpper95)\n)\n\npairwise_tests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Order          GroupA          GroupB                              Contrast\n1     0  Inland wetland Coastal wetland  Inland wetland minus Coastal wetland\n2     0  Inland wetland Tibetan Plateau  Inland wetland minus Tibetan Plateau\n3     0 Coastal wetland Tibetan Plateau Coastal wetland minus Tibetan Plateau\n4     1  Inland wetland Coastal wetland  Inland wetland minus Coastal wetland\n5     1  Inland wetland Tibetan Plateau  Inland wetland minus Tibetan Plateau\n6     1 Coastal wetland Tibetan Plateau Coastal wetland minus Tibetan Plateau\n7     2  Inland wetland Coastal wetland  Inland wetland minus Coastal wetland\n8     2  Inland wetland Tibetan Plateau  Inland wetland minus Tibetan Plateau\n9     2 Coastal wetland Tibetan Plateau Coastal wetland minus Tibetan Plateau\n  NGroupA NGroupB MedianGroupA MedianGroupB WilcoxonW     PValue CliffsDelta\n1      30      30    2893.2119    2634.4395       533 0.22257290  0.18444444\n2      30      30    2893.2119    2535.5539       566 0.08771038  0.25777778\n3      30      30    2634.4395    2535.5539       474 0.72826530  0.05333333\n4      30      30     866.4971     760.8580       521 0.29727169  0.15777778\n5      30      30     866.4971     738.4079       496 0.50114367  0.10222222\n6      30      30     760.8580     738.4079       437 0.85338174 -0.02888889\n7      30      30     207.6152     237.0341       442 0.91170898 -0.01777778\n8      30      30     207.6152     166.0920       497 0.49178296  0.10444444\n9      30      30     237.0341     166.0920       479 0.67349505  0.06444444\n  ProbabilitySuperiority DeltaLower95 DeltaUpper95 BootstrapReplicates\n1              0.5922222  -0.11555556    0.4666667                5000\n2              0.6288889  -0.03333333    0.5466667                5000\n3              0.5266667  -0.23777778    0.3422222                5000\n4              0.5788889  -0.14672222    0.4466667                5000\n5              0.5511111  -0.19777778    0.3977778                5000\n6              0.4855556  -0.32666667    0.2688889                5000\n7              0.4911111  -0.32222222    0.2822222                5000\n8              0.5522222  -0.19555556    0.3955556                5000\n9              0.5322222  -0.22672222    0.3688889                5000\n  BootstrapValid PAdjustedHolm RejectHolm05\n1           5000     1.0000000        FALSE\n2           5000     0.7893934        FALSE\n3           5000     1.0000000        FALSE\n4           5000     1.0000000        FALSE\n5           5000     1.0000000        FALSE\n6           5000     1.0000000        FALSE\n7           5000     1.0000000        FALSE\n8           5000     1.0000000        FALSE\n9           5000     1.0000000        FALSE\n```\n\n\n:::\n:::\n\n\n最大的观察效应出现在 (q=0) 的 Inland wetland vs Tibetan Plateau：Cliff's \\(\\delta=0.258\\)，95% bootstrap CI 为 -0.033 到 0.547，九项全局 Holm P = 0.789。区间跨过 0，因此数据同时容许接近无效应和中等正向优势；只看点估计会夸大确定性。\n\n### 7. 把 Welch 与标准化选择放入敏感性分析\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwelch_sensitivity <- bind_rows(lapply(0:2, function(order_q) {\n  x <- alpha_coverage[\n    alpha_coverage$Order == order_q,\n    ,\n    drop = FALSE\n  ]\n  fit <- oneway.test(\n    HillD ~ GroupLabel,\n    data = x,\n    var.equal = FALSE\n  )\n  data.frame(\n    Order = order_q,\n    Statistic = unname(fit$statistic),\n    DF1 = unname(fit$parameter[[1L]]),\n    DF2 = unname(fit$parameter[[2L]]),\n    PValue = fit$p.value\n  )\n})) |>\n  mutate(\n    PAdjustedHolm = p.adjust(PValue, method = \"holm\"),\n    RejectHolm05 = PAdjustedHolm < 0.05\n  )\n\nstandardized_hill <- bind_rows(\n  alpha_raw |>\n    select(SampleID, Group, GroupLabel, Order, HillD, Standardization),\n  alpha_size |>\n    select(SampleID, Group, GroupLabel, Order, HillD, Standardization),\n  alpha_coverage |>\n    select(SampleID, Group, GroupLabel, Order, HillD, Standardization)\n) |>\n  mutate(\n    Standardization = factor(\n      Standardization,\n      levels = c(\"Raw counts\", \"10,000 reads\", \"90% coverage\")\n    )\n  )\n\nstandardization_sensitivity <- standardized_hill |>\n  group_by(Standardization, Order) |>\n  group_modify(~ {\n    fit <- kruskal.test(HillD ~ GroupLabel, data = .x)\n    h <- unname(fit$statistic)\n    k <- nlevels(droplevels(.x$GroupLabel))\n    n_total <- nrow(.x)\n    data.frame(\n      H = h,\n      DF = unname(fit$parameter),\n      PValue = fit$p.value,\n      EpsilonSquared = max(0, (h - k + 1) / (n_total - k))\n    )\n  }) |>\n  ungroup() |>\n  arrange(Standardization, Order) |>\n  mutate(\n    PAdjustedHolm9 = p.adjust(PValue, method = \"holm\"),\n    RejectHolm9At05 = PAdjustedHolm9 < 0.05\n  )\n\nwelch_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Order Statistic DF1      DF2    PValue PAdjustedHolm RejectHolm05\n1     0 2.0306809   2 57.37476 0.1405728     0.4217184        FALSE\n2     1 0.6902654   2 57.20476 0.5055704     1.0000000        FALSE\n3     2 0.0353756   2 56.63581 0.9652641     1.0000000        FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nstandardization_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 8\n  Standardization Order     H    DF PValue EpsilonSquared PAdjustedHolm9\n  <fct>           <int> <dbl> <int>  <dbl>          <dbl>          <dbl>\n1 Raw counts          0 6.73      2 0.0346         0.0543          0.311\n2 Raw counts          1 1.60      2 0.450          0               1    \n3 Raw counts          2 0.380     2 0.827          0               1    \n4 10,000 reads        0 1.34      2 0.511          0               1    \n5 10,000 reads        1 0.976     2 0.614          0               1    \n6 10,000 reads        2 0.424     2 0.809          0               1    \n7 90% coverage        0 3.06      2 0.216          0.0122          1    \n8 90% coverage        1 1.07      2 0.587          0               1    \n9 90% coverage        2 0.423     2 0.809          0               1    \n# ℹ 1 more variable: RejectHolm9At05 <lgl>\n```\n\n\n:::\n:::\n\n\nWelch sensitivity 的三个 Holm P 分别为 0.422、1.000 和 1.000，与主分析方向一致。标准化敏感性中只有 raw (q=0) 的未校正 P 低于 0.05；把九项诊断作为同一族做 Holm 校正后，它也变为 0.311。\n\n## 出版级美化 {#sec-publication}\n\n### 1. 先画设计选择图\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndesign_plot_data <- data.frame(\n  Branch = factor(\n    c(\n      \"Independent groups\",\n      \"Paired two-condition\",\n      \"Repeated measures\",\n      \"Blocked or clustered\"\n    ),\n    levels = rev(c(\n      \"Independent groups\",\n      \"Paired two-condition\",\n      \"Repeated measures\",\n      \"Blocked or clustered\"\n    ))\n  ),\n  Detail = c(\n    \"Group: IW / CW / TW; n = 30 each\",\n    \"Needs SubjectID or PairID\",\n    \"Needs SubjectID and Time\",\n    \"Needs a declared clustering column\"\n  ),\n  Status = c(\n    \"Selected\",\n    \"Metadata absent\",\n    \"Metadata absent\",\n    \"Metadata absent\"\n  )\n)\n\ndesign_plot <- ggplot(\n  design_plot_data,\n  aes(y = Branch)\n) +\n  geom_segment(\n    aes(x = 0.08, xend = 0.92, yend = Branch),\n    colour = \"#D0D0D0\",\n    linewidth = 1.2\n  ) +\n  geom_point(\n    aes(x = 0.08, fill = Status),\n    shape = 21,\n    size = 4.2,\n    stroke = 0.45,\n    colour = \"#1A1A1A\"\n  ) +\n  geom_text(\n    aes(x = 0.15, label = Detail),\n    hjust = 0,\n    size = 3.2,\n    colour = \"#1A1A1A\"\n  ) +\n  geom_text(\n    aes(x = 0.92, label = Status),\n    hjust = 1,\n    size = 3.0,\n    fontface = \"bold\"\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"Selected\" = pal_pub[[\"green\"]],\n      \"Metadata absent\" = \"#B8B8B8\"\n    ),\n    guide = \"none\"\n  ) +\n  scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) +\n  labs(\n    title = \"Choose the test from the sampling design\",\n    subtitle = \"Selected branch: independent three-group comparison\",\n    x = NULL,\n    y = NULL,\n    caption = paste(\n      \"No subject, pair, time, or declared block identifier is present\",\n      \"in the demonstration metadata.\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  theme(\n    panel.grid = element_blank(),\n    panel.border = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks = element_blank(),\n    axis.text.y = element_text(face = \"bold\", size = 8.5),\n    plot.margin = margin(8, 12, 8, 8)\n  )\n\ndesign_plot\n```\n\n::: {.cell-output-display}\n![](20-alpha-group-tests_files/figure-html/unnamed-chunk-9-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  design_plot,\n  \"figures/20-design-selection-map\",\n  width = 183,\n  height = 84\n)\n```\n:::\n\n\n### 2. 主图保留每个样本，不用星号代替结果\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_p <- function(p) {\n  ifelse(\n    is.na(p),\n    \"NA\",\n    ifelse(p < 0.001, \"<0.001\", sprintf(\"%.3f\", p))\n  )\n}\n\norder_descriptions <- c(\n  \"0\" = \"q = 0 · rare features\",\n  \"1\" = \"q = 1 · balanced\",\n  \"2\" = \"q = 2 · dominant features\"\n)\npanel_lookup <- setNames(\n  paste0(\n    order_descriptions[as.character(omnibus_tests$Order)],\n    \"\\nKruskal-Wallis Holm P \",\n    format_p(omnibus_tests$PAdjustedHolm)\n  ),\n  omnibus_tests$Order\n)\n\ndistribution_plot_data <- alpha_coverage |>\n  mutate(\n    Panel = factor(\n      unname(panel_lookup[as.character(Order)]),\n      levels = unname(panel_lookup[as.character(0:2)])\n    )\n  )\n\ndistribution_plot <- ggplot(\n  distribution_plot_data,\n  aes(x = GroupLabel, y = HillD, fill = GroupLabel)\n) +\n  geom_violin(\n    width = 0.88,\n    alpha = 0.16,\n    colour = NA,\n    trim = FALSE\n  ) +\n  geom_boxplot(\n    width = 0.48,\n    outlier.shape = NA,\n    alpha = 0.60,\n    colour = \"#1A1A1A\",\n    linewidth = 0.4\n  ) +\n  geom_point(\n    aes(shape = GroupLabel),\n    position = position_jitter(\n      width = 0.11,\n      height = 0,\n      seed = 20260721\n    ),\n    colour = \"#1A1A1A\",\n    stroke = 0.28,\n    size = 1.45,\n    alpha = 0.68\n  ) +\n  facet_wrap(~Panel, scales = \"free_y\", nrow = 1L) +\n  scale_fill_manual(values = group_palette, guide = \"none\") +\n  scale_shape_manual(values = group_shapes, guide = \"none\") +\n  scale_y_log10(labels = label_comma()) +\n  labs(\n    title = \"Alpha diversity by wetland group\",\n    subtitle = paste(\n      \"Hill diversity standardized to 90% sample coverage;\",\n      \"points are independent samples\"\n    ),\n    x = NULL,\n    y = \"Effective features (log scale)\",\n    caption = paste(\n      \"Boxes show medians and IQRs. Kruskal-Wallis tests rank\",\n      \"distributions, not medians alone.\"\n    )\n  ) +\n  theme_pub(base_size = 8.6) +\n  theme(\n    axis.text.x = element_text(angle = 24, hjust = 1, size = 7.5),\n    strip.text = element_text(size = 7.5),\n    legend.position = \"none\"\n  )\n\ndistribution_plot\n```\n\n::: {.cell-output-display}\n![](20-alpha-group-tests_files/figure-html/unnamed-chunk-10-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  distribution_plot,\n  \"figures/20-alpha-group-distributions\",\n  width = 183,\n  height = 108\n)\n```\n:::\n\n\n### 3. 用敏感性图暴露标准化依赖\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsensitivity_plot_data <- standardization_sensitivity |>\n  mutate(\n    OrderLabel = factor(\n      paste0(\"q = \", Order),\n      levels = paste0(\"q = \", 0:2)\n    ),\n    MinusLog10P = -log10(PValue),\n    PLabel = paste0(\"P=\", format_p(PValue))\n  )\n\nsensitivity_plot <- ggplot(\n  sensitivity_plot_data,\n  aes(\n    x = Standardization,\n    y = MinusLog10P,\n    group = OrderLabel,\n    colour = OrderLabel\n  )\n) +\n  geom_hline(\n    yintercept = -log10(0.05),\n    linetype = 2,\n    colour = \"#666666\",\n    linewidth = 0.45\n  ) +\n  geom_line(linewidth = 0.7, alpha = 0.75) +\n  geom_point(\n    aes(size = EpsilonSquared),\n    shape = 21,\n    fill = \"white\",\n    stroke = 0.75\n  ) +\n  geom_text(\n    aes(label = PLabel),\n    nudge_y = 0.10,\n    size = 2.55,\n    show.legend = FALSE\n  ) +\n  scale_colour_manual(\n    values = c(\n      \"q = 0\" = pal_pub[[\"blue\"]],\n      \"q = 1\" = pal_pub[[\"orange\"]],\n      \"q = 2\" = pal_pub[[\"purple\"]]\n    )\n  ) +\n  scale_size_continuous(\n    range = c(2.2, 6.2),\n    limits = c(0, max(sensitivity_plot_data$EpsilonSquared)),\n    name = expression(epsilon^2)\n  ) +\n  scale_y_continuous(\n    expand = expansion(mult = c(0.05, 0.22)),\n    breaks = c(0, -log10(0.05), 2),\n    labels = c(\"1\", \"0.05\", \"0.01\")\n  ) +\n  labs(\n    title = paste(\n      \"The nominal raw-richness signal is not robust\",\n      \"to standardization\"\n    ),\n    subtitle = paste(\n      \"Kruskal-Wallis diagnostics across prespecified\",\n      \"measurement scales\"\n    ),\n    x = NULL,\n    y = \"Unadjusted P value (reverse log scale)\",\n    colour = \"Hill order\",\n    caption = paste(\n      \"Point size is epsilon-squared. All nine sensitivity P values\",\n      \"are non-significant after global Holm adjustment.\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  theme(\n    legend.position = \"top\",\n    axis.text.x = element_text(face = \"bold\")\n  )\n\nsensitivity_plot\n```\n\n::: {.cell-output-display}\n![](20-alpha-group-tests_files/figure-html/unnamed-chunk-11-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  sensitivity_plot,\n  \"figures/20-standardization-sensitivity\",\n  width = 183,\n  height = 92\n)\n```\n:::\n\n\n### 4. 成对结果用效应量 forest plot，而不是括号森林\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_plot_data <- pairwise_tests |>\n  mutate(\n    OrderPanel = factor(\n      paste0(\"q = \", Order),\n      levels = paste0(\"q = \", 0:2)\n    ),\n    ContrastLabel = factor(\n      Contrast,\n      levels = rev(unique(Contrast))\n    ),\n    PLabel = paste0(\"Holm P=\", format_p(PAdjustedHolm))\n  )\n\nforest_plot <- ggplot(\n  forest_plot_data,\n  aes(x = CliffsDelta, y = ContrastLabel)\n) +\n  geom_vline(\n    xintercept = 0,\n    linetype = 2,\n    colour = \"#666666\",\n    linewidth = 0.45\n  ) +\n  geom_errorbar(\n    aes(xmin = DeltaLower95, xmax = DeltaUpper95),\n    orientation = \"y\",\n    width = 0.16,\n    linewidth = 0.6,\n    colour = \"#3A3A3A\"\n  ) +\n  geom_point(\n    shape = 21,\n    size = 2.6,\n    stroke = 0.45,\n    fill = pal_pub[[\"blue\"]],\n    colour = \"#1A1A1A\"\n  ) +\n  geom_text(\n    aes(label = PLabel),\n    nudge_y = 0.23,\n    size = 2.45,\n    colour = \"#333333\"\n  ) +\n  facet_wrap(~OrderPanel, nrow = 1L) +\n  scale_x_continuous(\n    limits = c(-1, 1),\n    breaks = seq(-1, 1, by = 0.5)\n  ) +\n  labs(\n    title = \"Pairwise dominance effects remain uncertain\",\n    subtitle = paste(\n      \"Cliff's delta with stratified bootstrap\",\n      \"95% percentile intervals\"\n    ),\n    x = \"Cliff's delta (Group A minus Group B)\",\n    y = NULL,\n    caption = paste(\n      paste(\n        \"Positive values mean that a random Group A sample tends\",\n        \"to have higher diversity than Group B.\"\n      ),\n      \"Holm adjustment covers all nine planned contrasts.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 8.5) +\n  theme(\n    panel.grid.major.y = element_blank(),\n    strip.text = element_text(size = 8),\n    axis.text.y = element_text(size = 7.3)\n  )\n\nforest_plot\n```\n\n::: {.cell-output-display}\n![](20-alpha-group-tests_files/figure-html/unnamed-chunk-12-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  forest_plot,\n  \"figures/20-pairwise-effect-forest\",\n  width = 183,\n  height = 106\n)\n```\n:::\n\n\n四张图均生成 PDF、SVG、600 ppi PNG 与 LZW-compressed TIFF。PDF/SVG 用于排版，PNG 适合网页与公众号，TIFF 用于要求高分辨率位图的期刊系统。\n\n### 5. 对完整分析做机器回验\n\n验证器会重新读取三件套并核对输入 checksum、设计分支、coverage 计算、三个总体检验、九个成对比较、5,000 次 bootstrap、Holm 检验族、四种文件格式、物理尺寸、字体、SVG text nodes、600 ppi 和 TIFF LZW compression：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nRscript --vanilla scripts/validate_alpha_group_tests.R \\\n  --project-root . \\\n  --input-dir data/small \\\n  --output-dir results/20-alpha-group-tests \\\n  --figure-dir figures\n```\n:::\n\n\n项目审计结果存在时，下面代码要求全部 188 项通过；只复制分析代码时，不需要该审计目录也能完成前面的计算和出图。\n\n\n::: {.cell}\n\n```{.r .cell-code}\naudit_summary_path <- paste0(\n  \"results/20-alpha-group-tests/\",\n  \"alpha-group-tests-summary.json\"\n)\nif (file.exists(audit_summary_path)) {\n  audit_summary <- jsonlite::read_json(\n    audit_summary_path,\n    simplifyVector = TRUE\n  )\n  stopifnot(\n    audit_summary$checks_total == 188L,\n    audit_summary$checks_passed == 188L,\n    audit_summary$checks_failed == 0L,\n    audit_summary$analysis$omnibus_tests == 3L,\n    audit_summary$analysis$pairwise_tests == 9L,\n    audit_summary$analysis$bootstrap_replicates == 5000L,\n    audit_summary$graphics$primary_figures == 4L,\n    audit_summary$graphics$format_files == 16L\n  )\n  unlist(audit_summary[c(\n    \"checks_total\",\n    \"checks_passed\",\n    \"checks_failed\"\n  )])\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n checks_total checks_passed checks_failed \n          188           188             0 \n```\n\n\n:::\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最常追问的十件事\"}\n\n1. **把同一受试者或地点的重复样本当独立样本。** 这会人为放大有效样本量并使标准误过小。\n2. **没有先定义主要 Alpha 指标。** 同时试 Observed、Chao1、ACE、Shannon、Simpson、Pielou 和多个 Hill orders，却只报告显著的一项，属于选择性报告。\n3. **用 raw richness 做主比较。** richness 与 library size 高度相关时，组间测序量差异会进入结果。\n4. **先做 Shapiro–Wilk，再挑更显著的检验。** 主分析应由 estimand 与设计预先确定，诊断和敏感性分析不能反向选择结论。\n5. **把 Kruskal–Wallis 写成无条件的中位数检验。** 分布形状或尺度不同会改变秩分布；必须看原始点和分布诊断。\n6. **总体显著后只画若干星号。** 应明确所有计划 contrasts、效应方向、效应量、置信区间及 P 值校正范围。\n7. **每个 q 单独做一次三 pair 校正。** 若三个 q 都是同一研究问题的一部分，应说明为什么检验族是 3、9 或其他预先定义的范围。\n8. **用未校正 P = 0.049 当作稳健证据。** 本例 raw (q=0) 正好展示了标准化和多重比较如何改变结论。\n9. **把“未显著”写成“完全相同”。** 宽 CI 可能同时容许无效应和有意义效应；应报告精度边界。\n10. **忽略混杂。** Group 与 Saline 完全重叠时，即使 P 很小也不能区分两者的独立作用。\n\n:::\n\n::: {.callout-warning title=\"箱线图不展示配对关系\"}\n若同一 SubjectID 在两个条件下被重复采样，普通 jitter + boxplot 会隐藏配对。应增加连接同一 subject 的细线或画 within-subject change，并使用 paired test；三个以上时间点通常需要纵向模型，而不是把每个时间点拆成多个独立 Wilcoxon。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n下面英文与本例实际代码和结果一致：\n\n> Alpha diversity was recalculated from the unfiltered sample-by-feature count table and expressed as Hill numbers of orders q = 0, 1, and 2. The primary analysis used diversity standardized to 90% sample coverage with iNEXT 3.0.2; 56 samples were interpolated and 34 were extrapolated, with a maximum extrapolation effort of 1.453 times the observed library size. The metadata contained no subject, pair, time, or declared blocking identifier, and the 90 samples were analysed as three independent groups of 30 samples each, conditional on the original sampling design. Prespecified between-group comparisons were performed using Kruskal–Wallis rank-sum tests for each Hill order. Family-wise error across the three omnibus tests was controlled using Holm's procedure. The corresponding H statistics were 3.061, 1.066, and 0.423 for q = 0, 1, and 2, respectively, with Holm-adjusted P values of 0.649, 1.000, and 1.000. All nine prespecified pairwise Wilcoxon–Mann–Whitney comparisons were additionally adjusted as one family using Holm's procedure. Pairwise effects were reported as Cliff's delta with 95% percentile confidence intervals obtained from 5,000 within-group bootstrap resamples. No omnibus or pairwise comparison met the adjusted 0.05 threshold. Welch one-way tests and raw-count/10,000-read standardizations were evaluated as sensitivity analyses and did not replace the prespecified primary analysis.\n\n正式稿还要把 `Group` 的生物学定义、实验单位、排除标准、缺失值处理和混杂变量写清楚。若 metadata 有 repeated measures，上面“analysed as three independent groups”必须替换成真实的 mixed-model 或 paired design。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. 替换三件套路径和分组列\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"your_project/otutab.tsv\",\n  taxonomy = \"your_project/taxonomy.tsv\",\n  metadata = \"your_project/metadata.tsv\"\n)\ngroup_col <- \"Treatment\"\n\notutab <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\n\nstopifnot(\n  setequal(rownames(otutab), rownames(taxonomy)),\n  setequal(colnames(otutab), rownames(metadata)),\n  group_col %in% colnames(metadata)\n)\nmetadata <- metadata[colnames(otutab), , drop = FALSE]\nmetadata$AnalysisGroup <- factor(metadata[[group_col]])\n```\n:::\n\n\n最低输入要求：\n\n- `otutab`：feature × sample 原始非负整数 reads；\n- `taxonomy`：feature ID 与 `otutab` 一致；本分析不聚合 taxonomy，但保留标准接口和结果解释依据；\n- `metadata`：sample × variables，至少包含分组列；\n- 图中的中文分组先 recode 成英文；\n- 任何 subject、pair、time、site、batch、family、cage 或 center 列都要保留，不能为了简化表格而删除。\n\n### 2. 独立样本分支\n\n两个独立组可运行一个预先指定的 rank-sum comparison；三个以上独立组先做 omnibus，再输出所有计划 contrasts。不要根据总体 P 是否低于 0.05 才决定隐藏或显示预先计划的 pairwise estimates。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(nlevels(metadata$AnalysisGroup) >= 2L)\n\nalpha_primary <- alpha_coverage |>\n  mutate(\n    AnalysisGroup = metadata[SampleID, \"AnalysisGroup\"]\n  )\n\nif (nlevels(metadata$AnalysisGroup) == 2L) {\n  fit <- wilcox.test(\n    HillD ~ AnalysisGroup,\n    data = filter(alpha_primary, Order == 1L),\n    exact = FALSE,\n    conf.int = TRUE\n  )\n} else {\n  fit <- kruskal.test(\n    HillD ~ AnalysisGroup,\n    data = filter(alpha_primary, Order == 1L)\n  )\n}\nfit\n```\n:::\n\n\n若主要 estimand 是 mean difference，并且 residual diagnostics 支持连续模型，可预先选择 Welch test 或带协变量的 linear model；“non-parametric”并不自动等于更正确。\n\n### 3. 配对两条件分支\n\n先保留完整 pair，再显式按 `SubjectID` 对齐。不能只把 `paired = TRUE` 加到两列未排序的数据上。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\n\nsubject_col <- \"SubjectID\"\ncondition_col <- \"Condition\"\nstopifnot(\n  subject_col %in% colnames(metadata),\n  condition_col %in% colnames(metadata),\n  nlevels(factor(metadata[[condition_col]])) == 2L\n)\n\npaired_data <- alpha_primary |>\n  filter(Order == 1L) |>\n  mutate(\n    SubjectID = metadata[SampleID, subject_col],\n    Condition = metadata[SampleID, condition_col]\n  ) |>\n  select(SubjectID, Condition, HillD) |>\n  pivot_wider(names_from = Condition, values_from = HillD) |>\n  filter(if_all(-SubjectID, ~ !is.na(.x)))\n\nstopifnot(!anyDuplicated(paired_data$SubjectID))\n\npaired_fit <- wilcox.test(\n  paired_data[[2L]],\n  paired_data[[3L]],\n  paired = TRUE,\n  exact = FALSE,\n  conf.int = TRUE\n)\npaired_fit\n```\n:::\n\n\n图中应按 `SubjectID` 连接两次观测，并报告 within-subject change 的效应量与区间。\n\n### 4. 三个以上时间点或重复测量分支\n\n重复测量通常需要 mixed-effects model。下面是连续响应经 `log1p` 转换后的起点；随机截距、随机斜率、时间函数和残差结构要由真实采样设计决定。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"lme4\", \"lmerTest\", \"emmeans\"))\n\nlongitudinal_data <- alpha_primary |>\n  filter(Order == 1L) |>\n  mutate(\n    SubjectID = metadata[SampleID, \"SubjectID\"],\n    Condition = factor(metadata[SampleID, \"Condition\"]),\n    Time = as.numeric(metadata[SampleID, \"Time\"])\n  )\n\nstopifnot(\n  !anyNA(longitudinal_data$SubjectID),\n  !anyNA(longitudinal_data$Time)\n)\n\nmixed_fit <- lmerTest::lmer(\n  log1p(HillD) ~ Condition * Time + (1 + Time | SubjectID),\n  data = longitudinal_data,\n  REML = FALSE\n)\nsummary(mixed_fit)\n\nplanned_contrasts <- emmeans::emmeans(\n  mixed_fit,\n  ~ Condition | Time,\n  at = list(Time = c(0, 4, 8))\n)\npairs(planned_contrasts, adjust = \"holm\")\n```\n:::\n\n\n如果随机斜率导致 singular fit，不要悄悄删除它；先检查每个 subject 的时间点数、时间变化和设计可辨识性，再报告简化理由。\n\n### 5. 在看结果前写下检验族\n\n至少固定以下内容：\n\n1. primary Alpha metric 或 Hill orders；\n2. primary standardization；\n3. experimental unit 与配对/聚类结构；\n4. primary contrasts；\n5. omnibus 与 pairwise 各自的 multiplicity family；\n6. effect size、CI 方法和 bootstrap replicates；\n7. sensitivity analyses；\n8. 缺失值、异常值和排除规则。\n\n这样最终图上的每一个 P 值和区间都有预先定义的统计位置，而不是看到箱线图之后临时加上的装饰。\n\n## 参考 {#sec-references}\n\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n- Hill MO. Diversity and evenness: a unifying notation and its consequences. *Ecology*. 1973;54(2):427–432. [doi:10.2307/1934352](https://doi.org/10.2307/1934352)\n- Chao A, Jost L. Coverage-based rarefaction and extrapolation: standardizing samples by completeness rather than size. *Ecology*. 2012;93(12):2533–2547. [doi:10.1890/11-1952.1](https://doi.org/10.1890/11-1952.1)\n- Hsieh TC, Ma KH, Chao A. iNEXT: an R package for rarefaction and extrapolation of species diversity. *Methods in Ecology and Evolution*. 2016;7(12):1451–1456. [doi:10.1111/2041-210X.12613](https://doi.org/10.1111/2041-210X.12613)\n- Kruskal WH, Wallis WA. Use of ranks in one-criterion variance analysis. *Journal of the American Statistical Association*. 1952;47(260):583–621. [doi:10.1080/01621459.1952.10483441](https://doi.org/10.1080/01621459.1952.10483441)\n- Wilcoxon F. Individual comparisons by ranking methods. *Biometrics Bulletin*. 1945;1(6):80–83. [doi:10.2307/3001968](https://doi.org/10.2307/3001968)\n- Holm S. A simple sequentially rejective multiple test procedure. *Scandinavian Journal of Statistics*. 1979;6(2):65–70. [JSTOR 4615733](https://www.jstor.org/stable/4615733)\n- Cliff N. Dominance statistics: ordinal analyses to answer ordinal questions. *Psychological Bulletin*. 1993;114(3):494–509. [doi:10.1037/0033-2909.114.3.494](https://doi.org/10.1037/0033-2909.114.3.494)\n- Efron B. Bootstrap methods: another look at the jackknife. *Annals of Statistics*. 1979;7(1):1–26. [doi:10.1214/aos/1176344552](https://doi.org/10.1214/aos/1176344552)\n- Welch BL. On the comparison of several mean values: an alternative approach. *Biometrika*. 1951;38(3–4):330–336. [doi:10.1093/biomet/38.3-4.330](https://doi.org/10.1093/biomet/38.3-4.330)\n- Laird NM, Ware JH. Random-effects models for longitudinal data. *Biometrics*. 1982;38(4):963–974. [doi:10.2307/2529876](https://doi.org/10.2307/2529876)\n",
    "supporting": [
      "20-alpha-group-tests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}