{
  "hash": "3358ec12610ebb63efa91b5f9f405b29",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 25 篇 · 方差解构：envfit/Mantel/VPA 变异分解\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**把环境变量与群落差异之间的关系拆成三类证据：二维排序上的梯度拟合、距离矩阵关联，以及环境组和场景组的独立/共享调整后变异比例。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`、`environment.tsv`。  \n> **预计资源：**示例含 13,628 个 OTU、90 个样本和 11 个环境变量；999 次固定置换、4 个 prevalence 分支及四张 600 ppi 图通常需要 3–6 分钟，峰值内存低于 1 GB。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n环境或宿主因素很多时，论文通常会把三类图放在同一条证据链中：\n\n1. PCoA/NMDS 上叠加环境箭头，显示变量沿哪一方向变化；\n2. Mantel 点图或热图，比较群落距离与环境、气候、地理距离；\n3. variation partitioning analysis（VPA，变异分解），区分两个预测变量集合的独立、共享和未解释部分。\n\n[Falony et al. (2016)](https://doi.org/10.1126/science.aad3503)在 1,106 人的发现队列和 1,135 人的复现队列中系统筛查了临床与问卷协变量；其 Figure 3 一类的累计效应量图强调：微生物组差异通常由许多相关因素共同贡献，单个小 P 值不等于解释了大量群落变异。\n\n这里不复制该人群研究的数值或原图，而是使用 `microeco` 2.0.0 公开分发的中国湿地土壤 16S 数据重新绘图。原始数据研究为 [An et al. (2019)](https://doi.org/10.1016/j.geoderma.2018.09.035)，包含 90 个可与环境表匹配的样本；`microeco` 的数据与软件说明见 [Liu et al. (2021)](https://doi.org/10.1093/femsec/fiaa255)。\n\n::: {.callout-important title=\"先给结论\"}\n在预先固定的 5% prevalence filter 后保留 11,113 个 OTU。11 个连续变量的 `envfit` 检验中，10 个经 BH 校正后达到 0.05；最强的两个二维关联为 Temperature（(r^2=0.801)）和 Latitude（(r^2=0.801)）。这里的 (r^2) 只描述变量与当前两条 PCoA 轴的拟合，不是完整群落表的解释率。\n\n三组预设 Mantel 检验均为正关联：edaphic、climate 和 geographic distance 的 Spearman (r) 分别为 0.332、0.395 和 0.587，三者 Holm-adjusted (P=0.003)。Mantel (r) 是两个距离矩阵的相关，不是 explained variance，也不能确认独立环境驱动。\n\nHellinger VPA 的 combined adjusted (R^2=0.282)：纯土壤变量占 9.7%，纯 wetland group 占 11.4%，共享部分占 7.1%，未解释部分占 71.8%；两个纯组分的 Holm-adjusted (P=0.002)。`Group` 与 `Saline` 在这批数据中完全混杂，因此这些比例是统计关联分解，不能被写成盐度或地域的因果贡献。\n:::\n\n## 理论：三种方法回答三个不同问题 {#sec-theory}\n\n### envfit：变量与“当前排序图”是否对齐\n\n`vegan::envfit()`把连续变量投影到已经完成的排序空间。箭头方向表示变量增加方向；箭头长度与当前展示轴上的相关强度有关。对连续变量，`envfit` 输出的 (r^2) 是变量与所提供排序坐标之间的 squared correlation。\n\n本例把 11 个连续变量同时拟合到 Bray–Curtis PCoA 的前两轴，并把 11 个置换 P 值作为一个检验族做 Benjamini–Hochberg（BH）校正。图上只标出校正后显著变量中 (r^2) 最高的 7 个，完整 11 个结果仍保留在表中。\n\n::: {.callout-warning title=\"箭头长不等于解释率高\"}\n若重要信息落在第三轴以后，变量在二维图上的箭头可能很短。反过来，二维箭头很长也不代表它独立解释了完整群落表中的同等比例，更不证明因果。要回答多维 explained fraction，应使用 RDA/db-RDA、PERMANOVA 或 VPA，并报告相应的 (R^2)。\n:::\n\n### Mantel：两个距离结构是否同向变化\n\nMantel 检验把两个距离矩阵的下三角元素相关起来，并通过样本标签置换建立零分布。本例预先定义三组环境距离：\n\n| 距离块 | 变量 | 距离定义 |\n|---|---|---|\n| Edaphic | pH、TOC、NH4、NO3、Conductivity | 各列 Z-score 后的 Euclidean distance |\n| Climate | Temperature、Precipitation | 各列 Z-score 后的 Euclidean distance |\n| Geographic | Latitude、Longitude | Haversine great-circle distance（km） |\n\n主检验用 Spearman 相关，三个 P 值做 Holm 校正。距离中的变量先标准化，否则 Conductivity 这类数值跨度大的列会主导 Euclidean distance。\n\n<details>\n<summary><strong>深入：为什么 partial Mantel 只放敏感性分析</strong></summary>\n\npartial Mantel 尝试在控制第三个距离矩阵后关联另外两个距离矩阵，但“控制距离”不等于在原始变量尺度上完成可靠的混杂调整。空间自相关下，它还可能出现错误率失控；[Guillot & Rousset (2013)](https://doi.org/10.1111/2041-210X.12018)对此给出系统批评。\n\n`vegan` 文档还特别提醒，partial Mantel 的非 Pearson 相关实现可能有问题。因此本页只额外给出 Pearson partial Mantel 作为敏感性结果，不把它放进主检验族，也不据此声称“排除了地理影响”。需要正式控制空间结构时，应在样本级模型中显式加入空间坐标、空间基函数或研究设计中的 site/block。\n\n</details>\n\n### VPA：两个预测集合的独立和共享 adjusted R²\n\nVPA 把 Hellinger-transformed community matrix 的变异拆成：\n\n\\[\n1=[a]+[b]+[c]+[d]\n\\]\n\n- ([a])：edaphic set 在控制 wetland group 后的纯组分；\n- ([b])：wetland group 在控制 edaphic set 后的纯组分；\n- ([c])：两组预测变量共享的算术重叠；\n- ([d])：未解释部分。\n\n这里使用 adjusted (R^2)，因为原始 (R^2) 会随着预测变量数量增加而上升。只有 ([a]) 和 ([b]) 能通过 partial RDA 直接检验；共享组分 ([c]) 不能唯一归属给某一组变量，也不能直接做置换检验。共享组分在其他数据中可能为负值，那是调整后估计与共线性共同作用的结果，不应强制截断成 0。\n\n::: {.callout-note title=\"先看共线性，再定义变量集合\"}\n11 个变量中有 4 对 (|r|\\ge 0.80)，其中 TOC 与 TN 的 Pearson (r=0.988)。因此 TN 不进入主 edaphic set，避免几乎重复计入同一梯度；它仍保留在 `envfit` 描述性检验中。变量集合应由问题和测量含义预先定义，不能根据哪个组合 P 最小再反选。\n:::\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、下载真实数据和定义作图函数</strong></summary>\n\n首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"digest\", \"ggplot2\", \"jsonlite\", \"permute\", \"ragg\",\n  \"readr\", \"scales\", \"svglite\", \"systemfonts\", \"vegan\"\n))\n```\n:::\n\n\n下载固定版本数据、核对 SHA-256，并导出标准三件套和环境表：\n\n\n::: {.cell}\n\n```{.r .cell-code}\narchive <- \"data/raw/microeco_2.0.0.tar.gz\"\nsource_url <- paste0(\n  \"https://cran.r-project.org/src/contrib/Archive/\",\n  \"microeco/microeco_2.0.0.tar.gz\"\n)\nexpected_archive_sha256 <- paste0(\n  \"454a3b71ceeea86bdd54f475a12b5bac\",\n  \"9c3b124f663b8dc6e560827fca89ebfd\"\n)\n\ndir.create(\"data/raw\", recursive = TRUE, showWarnings = FALSE)\ndir.create(\"data/small\", recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(archive)) {\n  download.file(source_url, archive, mode = \"wb\")\n}\nstopifnot(identical(\n  digest::digest(file = archive, algo = \"sha256\", serialize = FALSE),\n  expected_archive_sha256\n))\n\nrequired <- c(\n  \"microeco/data/otu_table_16S.RData\",\n  \"microeco/data/taxonomy_table_16S.RData\",\n  \"microeco/data/sample_info_16S.RData\",\n  \"microeco/data/env_data_16S.RData\"\n)\nextract_dir <- tempfile(\"microeco-data-\")\ndir.create(extract_dir)\nutils::untar(archive, files = required, exdir = extract_dir)\n\ndata_env <- new.env(parent = emptyenv())\nfor (relative_path in required) {\n  load(file.path(extract_dir, relative_path), envir = data_env)\n}\n\nwrite_keyed_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name), x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out, path, sep = \"\\t\", quote = FALSE,\n    row.names = FALSE, na = \"\"\n  )\n}\n\nwrite_keyed_tsv(data_env$otu_table_16S, \"FeatureID\", \"data/small/otutab.tsv\")\nwrite_keyed_tsv(\n  data_env$taxonomy_table_16S,\n  \"FeatureID\",\n  \"data/small/taxonomy.tsv\"\n)\nwrite_keyed_tsv(\n  data_env$sample_info_16S,\n  \"SampleID\",\n  \"data/small/metadata.tsv\"\n)\nwrite_keyed_tsv(\n  data_env$env_data_16S,\n  \"SampleID\",\n  \"data/small/environment.tsv\"\n)\nunlink(extract_dir, recursive = TRUE)\n```\n:::\n\n\n出版级函数直接内联；图内统一使用英文和 `DejaVu Sans`：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(vegan)\n\nset.seed(20260725)\nfont_pub <- \"DejaVu Sans\"\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\", linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\", size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot,\n    width = width, height = height, units = units,\n    device = grDevices::cairo_pdf, family = base_family, bg = \"white\"\n  )\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"), plot,\n      width = width, height = height, units = units,\n      device = svglite::svglite, bg = \"white\"\n    )\n  }\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot,\n    width = width, height = height, units = units, dpi = dpi,\n    device = ragg::agg_png, bg = \"white\"\n  )\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"), plot,\n      width = width, height = height, units = units, dpi = dpi,\n      device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\"\n    )\n  }\n  invisible(plot)\n}\n```\n:::\n\n\n若在完整仓库中运行，也可把上面的函数块替换为 `source(\"R/theme_pub.R\")`；正文复现不依赖该文件。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取四张表并锁定样本顺序\n\n三件套仍是群落数据入口；`environment.tsv`是本分析额外需要的样本级环境表。环境表可包含更多样本，进入模型前按三件套共同样本显式取交集和排序。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character(),\n    col_types = readr::cols(.default = readr::col_character())\n  )\n  ids <- as.character(x[[1]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\ninput_paths <- c(\n  otutab = \"data/small/otutab.tsv\",\n  taxonomy = \"data/small/taxonomy.tsv\",\n  metadata = \"data/small/metadata.tsv\",\n  environment = \"data/small/environment.tsv\"\n)\nexpected_sha256 <- c(\n  otutab = \"76fa79c38da889f35978dc86da4641a270961746709ff38049ee5f67e3c6f7a3\",\n  taxonomy = \"725280bb9a0cd9bda7b540022e92af945ceed52527f8b2d220b055b4489f6901\",\n  metadata = \"df24771dccf27607ddf922c6bca2cafa876d946fbe2e09d14b601accce66ba64\",\n  environment = \"45814f6724e8abd901b8063ba227c42716777cd0749ac130e9cae99f0477f7a8\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  digest::digest,\n  character(1),\n  algo = \"sha256\",\n  serialize = FALSE,\n  file = TRUE\n)\nstopifnot(identical(unname(observed_sha256), unname(expected_sha256)))\n\notu_frame <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\nenvironment_frame <- read_keyed_tsv(input_paths[[\"environment\"]])\n\ncounts_character <- as.matrix(otu_frame)\ncounts <- matrix(\n  as.numeric(counts_character),\n  nrow = nrow(counts_character),\n  ncol = ncol(counts_character),\n  dimnames = dimnames(counts_character)\n)\nenvironment_character <- as.matrix(environment_frame)\nenvironment_all <- matrix(\n  as.numeric(environment_character),\n  nrow = nrow(environment_character),\n  ncol = ncol(environment_character),\n  dimnames = dimnames(environment_character)\n)\n\nsample_ids <- colnames(counts)\nfeature_ids <- rownames(counts)\nenvironment_variables <- c(\n  \"Latitude\", \"Longitude\", \"Altitude\", \"Temperature\", \"Precipitation\",\n  \"TOC\", \"NH4\", \"NO3\", \"pH\", \"Conductivity\", \"TN\"\n)\nstopifnot(\n  setequal(feature_ids, rownames(taxonomy)),\n  setequal(sample_ids, rownames(metadata)),\n  all(sample_ids %in% rownames(environment_all)),\n  all(environment_variables %in% colnames(environment_all)),\n  all(is.finite(counts)),\n  all(counts >= 0),\n  all(abs(counts - round(counts)) < .Machine$double.eps^0.5)\n)\n\ntaxonomy <- taxonomy[feature_ids, , drop = FALSE]\nmetadata <- metadata[sample_ids, , drop = FALSE]\nenvironment <- as.data.frame(\n  environment_all[sample_ids, environment_variables, drop = FALSE],\n  check.names = FALSE\n)\n\ngroup_labels <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan Plateau\"\n)\nmetadata$GroupCode <- metadata$Group\nmetadata$Group <- factor(\n  unname(group_labels[metadata$GroupCode]),\n  levels = unname(group_labels)\n)\nmetadata$Saline <- factor(metadata$Saline)\nmetadata$Type <- factor(metadata$Type)\n\ndim(counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1619670\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(counts[, 1:5])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\nOTU_706   0  1  0  1   0\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(taxonomy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\nOTU_706  k__Bacteria                     p__Actinobacteria\n                         Class               Order               Family\nOTU_4272            c__Bacilli       o__Bacillales                  f__\nOTU_236                    c__                 o__                  f__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__\nOTU_32                     c__                 o__                  f__\nOTU_706      c__Actinobacteria       o__Frankiales   f__Nakamurellaceae\n                  Genus Species\nOTU_4272            g__     s__\nOTU_236             g__     s__\nOTU_399             g__     s__\nOTU_1556            g__     s__\nOTU_32              g__     s__\nOTU_706  g__Nakamurella     s__\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Group Type          Saline GroupCode\nS1 Inland wetland   NE Non-saline soil        IW\nS2 Inland wetland   NE Non-saline soil        IW\nS3 Inland wetland   NE Non-saline soil        IW\nS4 Inland wetland   NE Non-saline soil        IW\nS5 Inland wetland   NE Non-saline soil        IW\nS6 Inland wetland   NE Non-saline soil        IW\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(environment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Latitude Longitude Altitude Temperature Precipitation   TOC      NH4  NO3\nS1 52.96482  122.5635      432        -4.2           445 10.02 18.95966 1.93\nS2 52.94877  122.6109      445        -4.3           449  6.94 21.05730 1.46\nS3 52.94932  122.6099      430        -4.3           449  8.38 14.31937 2.38\nS4 52.94900  122.6104      430        -4.3           449  8.17 20.89645 1.38\nS5 52.95292  122.6057      429        -4.3           449  8.41  9.65465 0.77\nS6 52.95300  122.6123      429        -4.3           449  8.13 15.94577 1.31\n     pH Conductivity   TN\nS1 5.10        108.7 0.28\nS2 6.53         31.2 0.22\nS3 5.13         68.2 0.26\nS4 5.81         64.4 0.25\nS5 5.50         33.5 0.24\nS6 5.37         33.3 0.26\n```\n\n\n:::\n:::\n\n\n样本顺序必须在 counts、metadata、environment 和所有距离矩阵中保持一致。这里得到 13,628 × 90 的 count matrix，总计 1,619,670 reads；环境源表有 200 个样本，其中 90 个与三件套匹配。\n\n### 2. 先审计设计与环境变量相关性\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndesign_cross <- with(metadata, table(Group, Saline))\ndesign_cross\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Saline\nGroup             Non-saline soil Saline soil\n  Inland wetland               30           0\n  Coastal wetland               0          30\n  Tibetan Plateau               0          30\n```\n\n\n:::\n\n```{.r .cell-code}\ngroup_determines_saline <- all(rowSums(design_cross > 0) == 1L)\nrepeat_columns <- intersect(\n  c(\"SubjectID\", \"PairID\", \"Block\", \"SiteID\", \"Time\", \"Batch\"),\n  colnames(metadata)\n)\nstopifnot(group_determines_saline, length(repeat_columns) == 0L)\n\ncorrelation_matrix <- stats::cor(environment, method = \"pearson\")\ncorrelation_index <- expand.grid(\n  Variable1 = rownames(correlation_matrix),\n  Variable2 = colnames(correlation_matrix),\n  stringsAsFactors = FALSE\n)\ncorrelation_index$PearsonR <- as.vector(correlation_matrix)\ncorrelation_index$AbsR <- abs(correlation_index$PearsonR)\nvariable_order <- setNames(seq_along(environment_variables), environment_variables)\ncorrelation_index$UniquePair <-\n  variable_order[correlation_index$Variable1] <\n  variable_order[correlation_index$Variable2]\nhigh_correlation_pairs <- subset(\n  correlation_index,\n  UniquePair & AbsR >= 0.80,\n  select = c(Variable1, Variable2, PearsonR, AbsR)\n)\nhigh_correlation_pairs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Variable1     Variable2   PearsonR      AbsR\n24    Longitude      Altitude -0.8637498 0.8637498\n34     Latitude   Temperature -0.8454553 0.8454553\n48  Temperature Precipitation  0.8540615 0.8540615\n116         TOC            TN  0.9880195 0.9880195\n```\n\n\n:::\n:::\n\n\n::: {.callout-caution title=\"没有 block 列，不等于已经证明样本独立\"}\n公开 metadata 没有 subject、pair、block、site、time 或 batch 标识，因此示例只能按独立样本做自由置换。这是可用信息下的分析边界，不是对原始采样独立性的额外证明。自己的数据只要有重复测量、区组、家庭、笼位或地点层级，就必须据此限制置换。\n:::\n\n### 3. 固定 feature filter、两种群落表示和置换矩阵\n\n`envfit` 与 Mantel 使用 relative-abundance Bray–Curtis；VPA 使用 Hellinger-transformed count matrix。两条分支不能混称为同一种标准化。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_seed <- 20260725L\npermutation_count <- 999L\nmin_prevalence <- 0.05\nminimum_samples <- ceiling(min_prevalence * ncol(counts))\n\nprimary_keep <- rowSums(counts > 0) >= minimum_samples\nprimary_counts <- counts[primary_keep, , drop = FALSE]\ncommunity_counts <- t(primary_counts)\ncommunity_relative <- sweep(\n  community_counts,\n  1,\n  rowSums(community_counts),\n  \"/\"\n)\ncommunity_hellinger <- vegan::decostand(\n  community_counts,\n  method = \"hellinger\"\n)\nbray_distance <- vegan::vegdist(community_relative, method = \"bray\")\n\npermutation_control <- permute::how(\n  within = permute::Within(type = \"free\"),\n  nperm = permutation_count\n)\nset.seed(primary_seed)\npermutation_matrix <- permute::shuffleSet(\n  n = length(sample_ids),\n  nset = permutation_count,\n  control = permutation_control\n)\n\nstopifnot(\n  sum(primary_keep) == 11113L,\n  minimum_samples == 5L,\n  max(abs(rowSums(community_relative) - 1)) < 1e-12,\n  all(is.finite(community_hellinger)),\n  nrow(unique(as.data.frame(permutation_matrix))) == 999L\n)\ndata.frame(\n  Samples = nrow(community_counts),\n  FeaturesBefore = nrow(counts),\n  FeaturesAfter = nrow(primary_counts),\n  MinimumSamples = minimum_samples,\n  Permutations = nrow(permutation_matrix),\n  MinimumP = 1 / (permutation_count + 1)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Samples FeaturesBefore FeaturesAfter MinimumSamples Permutations MinimumP\n1      90          13628         11113              5          999    0.001\n```\n\n\n:::\n:::\n\n\n### 4. PCoA 后运行 envfit，并校正 11 个检验\n\n先完成 unconstrained ordination，再把环境变量作为外部向量拟合；`envfit` 不会反过来改变 PCoA 坐标。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcoa <- vegan::wcmdscale(\n  bray_distance,\n  k = 2,\n  eig = TRUE,\n  add = \"lingoes\",\n  x.ret = TRUE\n)\npcoa_scores <- data.frame(\n  SampleID = rownames(pcoa$points),\n  PCoA1 = pcoa$points[, 1],\n  PCoA2 = pcoa$points[, 2],\n  Group = metadata[rownames(pcoa$points), \"Group\"],\n  stringsAsFactors = FALSE\n)\npositive_eigenvalues <- pcoa$eig[pcoa$eig > 0]\npcoa_axis_percent <- 100 * pcoa$eig[1:2] / sum(positive_eigenvalues)\n\nenvironment_z <- as.data.frame(scale(environment))\nset.seed(primary_seed)\nenvfit_result <- vegan::envfit(\n  pcoa$points,\n  environment_z,\n  permutations = permutation_matrix,\n  w = rep(1, nrow(pcoa$points)),\n  na.rm = FALSE\n)\nenvfit_scaled_scores <- vegan::scores(envfit_result, display = \"vectors\")\nenvfit_results <- data.frame(\n  Variable = rownames(envfit_result$vectors$arrows),\n  Axis1Direction = envfit_result$vectors$arrows[, 1],\n  Axis2Direction = envfit_result$vectors$arrows[, 2],\n  PlotAxis1 = envfit_scaled_scores[, 1],\n  PlotAxis2 = envfit_scaled_scores[, 2],\n  TwoAxisR2 = as.numeric(envfit_result$vectors$r),\n  PValue = as.numeric(envfit_result$vectors$pvals),\n  stringsAsFactors = FALSE\n)\nenvfit_results$PAdjustedBH <- stats::p.adjust(\n  envfit_results$PValue,\n  method = \"BH\"\n)\nenvfit_results$RejectBH05 <- envfit_results$PAdjustedBH < 0.05\nenvfit_results <- envfit_results[\n  order(envfit_results$PAdjustedBH, -envfit_results$TwoAxisR2),\n  ,\n  drop = FALSE\n]\nrownames(envfit_results) <- NULL\n\nenvfit_results[, c(\n  \"Variable\", \"TwoAxisR2\", \"PValue\", \"PAdjustedBH\", \"RejectBH05\"\n)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Variable  TwoAxisR2 PValue PAdjustedBH RejectBH05\n1    Temperature 0.80081147  0.001 0.001571429       TRUE\n2       Latitude 0.80065933  0.001 0.001571429       TRUE\n3       Altitude 0.75850835  0.001 0.001571429       TRUE\n4      Longitude 0.75815444  0.001 0.001571429       TRUE\n5   Conductivity 0.55309350  0.001 0.001571429       TRUE\n6  Precipitation 0.49254244  0.001 0.001571429       TRUE\n7             pH 0.35345342  0.001 0.001571429       TRUE\n8             TN 0.18690456  0.002 0.002444444       TRUE\n9            TOC 0.17006029  0.002 0.002444444       TRUE\n10           NO3 0.07919999  0.028 0.030800000       TRUE\n11           NH4 0.05546100  0.073 0.073000000      FALSE\n```\n\n\n:::\n:::\n\n\n本数据的 Bray–Curtis 距离没有负 eigenvalues，因此虽然显式请求了 `add = \"lingoes\"`，实际加常数为 0。代码保留该选项，避免换数据后静默忽略非欧氏距离问题；坐标轴百分比按正 eigenvalues 计算。\n\n### 5. 把环境变量预注册成三个 Mantel 距离块\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedaphic_names <- c(\"pH\", \"TOC\", \"NH4\", \"NO3\", \"Conductivity\")\nclimate_names <- c(\"Temperature\", \"Precipitation\")\nedaphic_z <- as.data.frame(scale(environment[, edaphic_names, drop = FALSE]))\nclimate_z <- as.data.frame(scale(environment[, climate_names, drop = FALSE]))\n\nhaversine_dist <- function(latitude, longitude, ids = names(latitude)) {\n  rad <- pi / 180\n  lat <- latitude * rad\n  lon <- longitude * rad\n  n <- length(lat)\n  out <- matrix(0, n, n)\n  for (i in seq_len(n - 1L)) {\n    j <- (i + 1L):n\n    dlat <- lat[j] - lat[i]\n    dlon <- lon[j] - lon[i]\n    a <- sin(dlat / 2)^2 +\n      cos(lat[i]) * cos(lat[j]) * sin(dlon / 2)^2\n    out[i, j] <- 6371.0088 * 2 * atan2(\n      sqrt(a),\n      sqrt(pmax(0, 1 - a))\n    )\n    out[j, i] <- out[i, j]\n  }\n  dimnames(out) <- list(ids, ids)\n  stats::as.dist(out)\n}\n\nenvironment_distances <- list(\n  Edaphic = stats::dist(edaphic_z, method = \"euclidean\"),\n  Climate = stats::dist(climate_z, method = \"euclidean\"),\n  Geographic = haversine_dist(\n    environment$Latitude,\n    environment$Longitude,\n    sample_ids\n  )\n)\n\nmantel_results <- do.call(\n  rbind,\n  lapply(seq_along(environment_distances), function(i) {\n    set.seed(primary_seed)\n    fit <- vegan::mantel(\n      bray_distance,\n      environment_distances[[i]],\n      method = \"spearman\",\n      permutations = permutation_matrix,\n      na.rm = FALSE\n    )\n    data.frame(\n      DistanceBlock = names(environment_distances)[i],\n      Statistic = as.numeric(fit$statistic),\n      PValue = as.numeric(fit$signif),\n      Permutations = permutation_count,\n      stringsAsFactors = FALSE\n    )\n  })\n)\nmantel_results$PAdjustedHolm <- stats::p.adjust(\n  mantel_results$PValue,\n  method = \"holm\"\n)\nmantel_results$RejectHolm05 <- mantel_results$PAdjustedHolm < 0.05\nmantel_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  DistanceBlock Statistic PValue Permutations PAdjustedHolm RejectHolm05\n1       Edaphic 0.3318957  0.001          999         0.003         TRUE\n2       Climate 0.3950914  0.001          999         0.003         TRUE\n3    Geographic 0.5869835  0.001          999         0.003         TRUE\n```\n\n\n:::\n:::\n\n\n不要把 `0.587` 写成“地理解释了 58.7% 群落变异”。它表示样本对的 geographic distance 与 Bray–Curtis distance 有较强的单调正相关；样本对彼此不独立，所以 P 值来自样本标签置换，而不是普通相关检验。\n\n### 6. partial Mantel 只作为带警告的敏感性结果\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(primary_seed)\npartial_mantel <- vegan::mantel.partial(\n  bray_distance,\n  environment_distances$Edaphic,\n  environment_distances$Geographic,\n  method = \"pearson\",\n  permutations = permutation_matrix,\n  na.rm = FALSE\n)\npartial_mantel_sensitivity <- data.frame(\n  Analysis = \"Edaphic distance | geographic distance\",\n  Method = \"Pearson partial Mantel\",\n  Statistic = as.numeric(partial_mantel$statistic),\n  PValue = as.numeric(partial_mantel$signif),\n  Permutations = permutation_count,\n  PrimaryInference = FALSE,\n  stringsAsFactors = FALSE\n)\npartial_mantel_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                Analysis                 Method Statistic\n1 Edaphic distance | geographic distance Pearson partial Mantel 0.1884762\n  PValue Permutations PrimaryInference\n1  0.001          999            FALSE\n```\n\n\n:::\n:::\n\n\n结果为 (r=0.188)、(P=0.001)，但这不会升级为“控制地理后土壤仍有独立因果作用”。它只说明在这一特定距离残差化定义下仍见正相关，正式结论仍依赖样本级设计和模型。\n\n### 7. 用 Hellinger RDA 做两集合 VPA\n\n主 edaphic set 含五个变量；`Group` 是三水平因子。TN 因与 TOC 几乎重复而不进入该集合，Saline 因与 Group 完全混杂而不与 Group 同时解释为独立预测变量。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_df <- data.frame(Group = metadata$Group, row.names = sample_ids)\nvariation_partition_object <- vegan::varpart(\n  community_hellinger,\n  edaphic_z,\n  group_df\n)\nindividual_fractions <- variation_partition_object$part$indfract\nvariation_partition <- data.frame(\n  FractionCode = c(\"[a]\", \"[b]\", \"[c]\", \"[d]\"),\n  Fraction = c(\n    \"Pure edaphic | wetland group\",\n    \"Pure wetland group | edaphic\",\n    \"Shared edaphic + wetland group\",\n    \"Unexplained\"\n  ),\n  AdjustedR2 = as.numeric(individual_fractions$Adj.R.squared),\n  Testable = as.logical(individual_fractions$Testable),\n  stringsAsFactors = FALSE\n)\n\nmodel_data <- cbind(edaphic_z, Group = metadata$Group, Saline = metadata$Saline)\ncombined_rda <- vegan::rda(\n  community_hellinger ~ pH + TOC + NH4 + NO3 + Conductivity + Group,\n  data = model_data\n)\npure_edaphic_rda <- vegan::rda(\n  community_hellinger ~ pH + TOC + NH4 + NO3 + Conductivity +\n    Condition(Group),\n  data = model_data\n)\npure_group_rda <- vegan::rda(\n  community_hellinger ~ Group +\n    Condition(pH + TOC + NH4 + NO3 + Conductivity),\n  data = model_data\n)\n\ncombined_r2 <- vegan::RsquareAdj(combined_rda)\nset.seed(primary_seed)\npure_edaphic_test <- anova(\n  pure_edaphic_rda,\n  permutations = permutation_matrix\n)\nset.seed(primary_seed)\npure_group_test <- anova(\n  pure_group_rda,\n  permutations = permutation_matrix\n)\nvariation_fraction_tests <- data.frame(\n  Fraction = variation_partition$Fraction[1:2],\n  AdjustedR2 = c(\n    vegan::RsquareAdj(pure_edaphic_rda)$adj.r.squared,\n    vegan::RsquareAdj(pure_group_rda)$adj.r.squared\n  ),\n  FValue = c(pure_edaphic_test$F[1], pure_group_test$F[1]),\n  PValue = c(\n    pure_edaphic_test$`Pr(>F)`[1],\n    pure_group_test$`Pr(>F)`[1]\n  ),\n  stringsAsFactors = FALSE\n)\nvariation_fraction_tests$PAdjustedHolm <- stats::p.adjust(\n  variation_fraction_tests$PValue,\n  method = \"holm\"\n)\nvariation_fraction_tests$RejectHolm05 <-\n  variation_fraction_tests$PAdjustedHolm < 0.05\n\nvariation_partition\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  FractionCode                       Fraction AdjustedR2 Testable\n1          [a]   Pure edaphic | wetland group 0.09673210     TRUE\n2          [b]   Pure wetland group | edaphic 0.11404959     TRUE\n3          [c] Shared edaphic + wetland group 0.07096358    FALSE\n4          [d]                    Unexplained 0.71825474    FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(\n  CombinedRawR2 = combined_r2$r.squared,\n  CombinedAdjustedR2 = combined_r2$adj.r.squared\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  CombinedRawR2 CombinedAdjustedR2\n1     0.3382372          0.2817453\n```\n\n\n:::\n\n```{.r .cell-code}\nvariation_fraction_tests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      Fraction AdjustedR2   FValue PValue PAdjustedHolm\n1 Pure edaphic | wetland group  0.0967321 3.343373  0.001         0.002\n2 Pure wetland group | edaphic  0.1140496 7.669058  0.001         0.002\n  RejectHolm05\n1         TRUE\n2         TRUE\n```\n\n\n:::\n:::\n\n\n### 8. 检查 VIF、conditioning 和 prevalence 敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_vif <- vegan::vif.cca(combined_rda)\nvif_audit <- data.frame(\n  Term = names(combined_vif),\n  VIF = as.numeric(combined_vif),\n  Status = ifelse(combined_vif < 5, \"PASS\", \"REVIEW\"),\n  stringsAsFactors = FALSE\n)\n\nedaphic_unconditioned_rda <- vegan::rda(\n  community_hellinger ~ pH + TOC + NH4 + NO3 + Conductivity,\n  data = model_data\n)\nedaphic_condition_saline_rda <- vegan::rda(\n  community_hellinger ~ pH + TOC + NH4 + NO3 + Conductivity +\n    Condition(Saline),\n  data = model_data\n)\nconditioning_sensitivity <- data.frame(\n  Conditioning = c(\"None\", \"Binary salinity\", \"Three-level wetland group\"),\n  AdjustedR2 = c(\n    vegan::RsquareAdj(edaphic_unconditioned_rda)$adj.r.squared,\n    vegan::RsquareAdj(edaphic_condition_saline_rda)$adj.r.squared,\n    vegan::RsquareAdj(pure_edaphic_rda)$adj.r.squared\n  ),\n  Primary = c(FALSE, FALSE, TRUE),\n  stringsAsFactors = FALSE\n)\n\nprevalence_thresholds <- c(0, 0.05, 0.10, 0.20)\nprevalence_sensitivity <- do.call(\n  rbind,\n  lapply(prevalence_thresholds, function(threshold) {\n    keep <- if (threshold == 0) {\n      rep(TRUE, nrow(counts))\n    } else {\n      rowSums(counts > 0) >= ceiling(threshold * ncol(counts))\n    }\n    branch_counts <- t(counts[keep, , drop = FALSE])\n    branch_relative <- sweep(\n      branch_counts,\n      1,\n      rowSums(branch_counts),\n      \"/\"\n    )\n    branch_hellinger <- vegan::decostand(\n      branch_counts,\n      method = \"hellinger\"\n    )\n    branch_vpa <- vegan::varpart(branch_hellinger, edaphic_z, group_df)\n    fractions <- as.numeric(branch_vpa$part$indfract$Adj.R.squared)\n    set.seed(primary_seed)\n    branch_mantel <- vegan::mantel(\n      vegan::vegdist(branch_relative, method = \"bray\"),\n      environment_distances$Edaphic,\n      method = \"spearman\",\n      permutations = permutation_matrix\n    )\n    data.frame(\n      PrevalenceThreshold = threshold,\n      MinimumSamples = ifelse(\n        threshold == 0,\n        1L,\n        ceiling(threshold * ncol(counts))\n      ),\n      Features = sum(keep),\n      PureEdaphicAdjustedR2 = fractions[1],\n      PureGroupAdjustedR2 = fractions[2],\n      SharedAdjustedR2 = fractions[3],\n      UnexplainedAdjustedR2 = fractions[4],\n      EdaphicMantelRho = as.numeric(branch_mantel$statistic),\n      EdaphicMantelP = as.numeric(branch_mantel$signif),\n      Primary = threshold == min_prevalence,\n      stringsAsFactors = FALSE\n    )\n  })\n)\n\nvif_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                     Term      VIF Status\npH                                     pH 1.873580   PASS\nTOC                                   TOC 1.852951   PASS\nNH4                                   NH4 1.259056   PASS\nNO3                                   NO3 1.263890   PASS\nConductivity                 Conductivity 1.662513   PASS\nGroupCoastal wetland GroupCoastal wetland 2.143884   PASS\nGroupTibetan Plateau GroupTibetan Plateau 1.813708   PASS\n```\n\n\n:::\n\n```{.r .cell-code}\nconditioning_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Conditioning AdjustedR2 Primary\n1                      None  0.1676957   FALSE\n2           Binary salinity  0.1352140   FALSE\n3 Three-level wetland group  0.0967321    TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nprevalence_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PrevalenceThreshold MinimumSamples Features PureEdaphicAdjustedR2\n1                0.00              1    13628            0.09554094\n2                0.05              5    11113            0.09673210\n3                0.10              9     9043            0.09865475\n4                0.20             18     5700            0.10303684\n  PureGroupAdjustedR2 SharedAdjustedR2 UnexplainedAdjustedR2 EdaphicMantelRho\n1           0.1126496       0.07035764             0.7214518        0.3290579\n2           0.1140496       0.07096358             0.7182547        0.3318957\n3           0.1164374       0.07245623             0.7124516        0.3361705\n4           0.1231388       0.07732894             0.6964955        0.3404246\n  EdaphicMantelP Primary\n1          0.001   FALSE\n2          0.001    TRUE\n3          0.001   FALSE\n4          0.001   FALSE\n```\n\n\n:::\n:::\n\n\ncombined model 的最大 VIF 为 2.14，没有达到预设的 review threshold 5。prevalence 从 0% 调到 20% 时，pure edaphic adjusted (R^2) 为 0.096–0.103，edaphic Mantel (r) 为 0.329–0.340；方向和量级稳定，但主分支仍应按预先声明的 5% 阈值报告，而不是挑最漂亮的一行。\n\n## 出版级美化 {#sec-publication}\n\n### 1. 相关性热图先暴露环境变量的冗余\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrelation_index$Diagonal <-\n  correlation_index$Variable1 == correlation_index$Variable2\ncorrelation_index$HighCollinearity <-\n  correlation_index$UniquePair & correlation_index$AbsR >= 0.80\ncorrelation_plot_data <- correlation_index[\n  variable_order[correlation_index$Variable1] <=\n    variable_order[correlation_index$Variable2],\n  ,\n  drop = FALSE\n]\ncorrelation_plot_data$Variable1 <- factor(\n  correlation_plot_data$Variable1,\n  levels = rev(environment_variables)\n)\ncorrelation_plot_data$Variable2 <- factor(\n  correlation_plot_data$Variable2,\n  levels = environment_variables\n)\ncorrelation_plot_data$Label <- ifelse(\n  correlation_plot_data$Diagonal,\n  \"1.00\",\n  ifelse(\n    correlation_plot_data$AbsR >= 0.50,\n    sprintf(\"%.2f\", correlation_plot_data$PearsonR),\n    \"\"\n  )\n)\n\ncorrelation_plot <- ggplot2::ggplot(\n  correlation_plot_data,\n  ggplot2::aes(Variable2, Variable1, fill = PearsonR)\n) +\n  ggplot2::geom_tile(colour = \"white\", linewidth = 0.35) +\n  ggplot2::geom_tile(\n    data = subset(correlation_plot_data, HighCollinearity),\n    fill = NA,\n    colour = \"#111111\",\n    linewidth = 0.85\n  ) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = Label),\n    size = 2.5,\n    colour = \"#111111\",\n    family = font_pub\n  ) +\n  ggplot2::scale_fill_gradient2(\n    low = \"#0072B2\",\n    mid = \"white\",\n    high = \"#D55E00\",\n    midpoint = 0,\n    limits = c(-1, 1),\n    name = \"Pearson r\"\n  ) +\n  ggplot2::coord_equal() +\n  ggplot2::labs(\n    title = \"Environmental covariates are not independent\",\n    subtitle = \"Black outlines mark |r| >= 0.80; labels are shown for |r| >= 0.50\",\n    x = NULL,\n    y = NULL,\n    caption = paste(\n      \"All 11 variables enter the descriptive envfit family.\",\n      \"TN is excluded from the primary edaphic set because it is nearly redundant with TOC.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 8.4) +\n  ggplot2::theme(\n    panel.grid = ggplot2::element_blank(),\n    axis.text.x = ggplot2::element_text(angle = 42, hjust = 1, size = 7.4),\n    axis.text.y = ggplot2::element_text(size = 7.4),\n    legend.position = \"right\"\n  )\n\nsave_pub(\n  correlation_plot,\n  \"figures/25-environment-correlation\",\n  width = 183,\n  height = 126\n)\ncorrelation_plot\n```\n\n::: {.cell-output-display}\n![环境变量 Pearson 相关性。黑框表示 |r| ≥ 0.80；TN 与 TOC 近乎冗余，因此 TN 不进入主 VPA edaphic set。](25-environment-variance_files/figure-html/fig-environment-correlation-1.png){#fig-environment-correlation}\n:::\n:::\n\n\n图内只标出 (|r|\\ge 0.50) 的系数，避免数字墙；完整矩阵仍由 `correlation_matrix` 保存。高相关不自动说明删谁，应结合测量含义、研究假设和模型用途决定。\n\n### 2. envfit 图只展示强箭头，完整检验留在表中\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_palette <- c(\n  \"Inland wetland\" = \"#0072B2\",\n  \"Coastal wetland\" = \"#D55E00\",\n  \"Tibetan Plateau\" = \"#009E73\"\n)\ngroup_shapes <- c(\n  \"Inland wetland\" = 16,\n  \"Coastal wetland\" = 17,\n  \"Tibetan Plateau\" = 15\n)\nenvfit_plot_arrows <- subset(envfit_results, RejectBH05)\nenvfit_plot_arrows <- head(\n  envfit_plot_arrows[order(-envfit_plot_arrows$TwoAxisR2), ],\n  7\n)\narrow_multiplier <- min(\n  diff(range(pcoa_scores$PCoA1)) * 0.40 /\n    max(abs(envfit_plot_arrows$PlotAxis1)),\n  diff(range(pcoa_scores$PCoA2)) * 0.40 /\n    max(abs(envfit_plot_arrows$PlotAxis2))\n)\nenvfit_plot_arrows$ArrowX <-\n  envfit_plot_arrows$PlotAxis1 * arrow_multiplier\nenvfit_plot_arrows$ArrowY <-\n  envfit_plot_arrows$PlotAxis2 * arrow_multiplier\n\nenvfit_label_offsets <- data.frame(\n  Variable = c(\n    \"Temperature\", \"Latitude\", \"Altitude\", \"Longitude\",\n    \"Conductivity\", \"Precipitation\", \"pH\"\n  ),\n  OffsetX = c(0.025, -0.015, -0.025, 0.005, -0.060, -0.035, 0.020),\n  OffsetY = c(0.030, -0.045, 0.035, -0.030, 0.035, -0.055, 0.040),\n  Hjust = c(0, 1, 0.5, 0.5, 1, 0.5, 0),\n  stringsAsFactors = FALSE\n)\noffset_index <- match(envfit_plot_arrows$Variable, envfit_label_offsets$Variable)\nenvfit_plot_arrows$LabelX <-\n  envfit_plot_arrows$ArrowX + envfit_label_offsets$OffsetX[offset_index]\nenvfit_plot_arrows$LabelY <-\n  envfit_plot_arrows$ArrowY + envfit_label_offsets$OffsetY[offset_index]\nenvfit_plot_arrows$LabelHjust <- envfit_label_offsets$Hjust[offset_index]\n\nenvfit_plot <- ggplot2::ggplot(\n  pcoa_scores,\n  ggplot2::aes(PCoA1, PCoA2, colour = Group, shape = Group)\n) +\n  ggplot2::stat_ellipse(\n    type = \"t\",\n    level = 0.95,\n    linewidth = 0.55,\n    show.legend = FALSE\n  ) +\n  ggplot2::geom_point(size = 2.4, alpha = 0.83) +\n  ggplot2::geom_segment(\n    data = envfit_plot_arrows,\n    ggplot2::aes(x = 0, y = 0, xend = ArrowX, yend = ArrowY),\n    inherit.aes = FALSE,\n    colour = \"#222222\",\n    linewidth = 0.55,\n    arrow = grid::arrow(length = grid::unit(2.1, \"mm\"), type = \"closed\")\n  ) +\n  ggplot2::geom_segment(\n    data = envfit_plot_arrows,\n    ggplot2::aes(x = ArrowX, y = ArrowY, xend = LabelX, yend = LabelY),\n    inherit.aes = FALSE,\n    colour = \"#777777\",\n    linewidth = 0.35\n  ) +\n  ggplot2::geom_text(\n    data = envfit_plot_arrows,\n    ggplot2::aes(\n      x = LabelX,\n      y = LabelY,\n      label = Variable,\n      hjust = LabelHjust\n    ),\n    inherit.aes = FALSE,\n    colour = \"#111111\",\n    family = font_pub,\n    fontface = \"bold\",\n    size = 2.8\n  ) +\n  ggplot2::scale_colour_manual(values = group_palette, name = \"Wetland group\") +\n  ggplot2::scale_shape_manual(values = group_shapes, name = \"Wetland group\") +\n  ggplot2::coord_equal(clip = \"off\") +\n  ggplot2::labs(\n    title = \"envfit overlays external gradients on an unconstrained PCoA\",\n    subtitle = paste(\n      \"Top 7 of\",\n      sum(envfit_results$RejectBH05),\n      \"BH-significant variables; all 11 tests remain in the audit table\"\n    ),\n    x = sprintf(\"PCoA1 (%.1f%% positive inertia)\", pcoa_axis_percent[1]),\n    y = sprintf(\"PCoA2 (%.1f%% positive inertia)\", pcoa_axis_percent[2]),\n    caption = paste(\n      \"Arrow direction and length describe association with this two-axis display.\",\n      \"They are not causal effects or full-community explained fractions.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  ggplot2::theme(\n    legend.position = \"top\",\n    legend.title = ggplot2::element_text(face = \"bold\"),\n    panel.grid.minor = ggplot2::element_blank()\n  ) +\n  ggplot2::guides(\n    colour = ggplot2::guide_legend(nrow = 1, byrow = TRUE),\n    shape = ggplot2::guide_legend(nrow = 1, byrow = TRUE)\n  )\n\nsave_pub(\n  envfit_plot,\n  \"figures/25-envfit-pcoa\",\n  width = 183,\n  height = 122\n)\nenvfit_plot\n```\n\n::: {.cell-output-display}\n![Bray–Curtis PCoA 与 envfit。仅标出 10 个 BH 显著变量中二维 r² 最高的 7 个；箭头不是因果效应或完整群落解释率。](25-environment-variance_files/figure-html/fig-envfit-pcoa-1.png){#fig-envfit-pcoa}\n:::\n:::\n\n\n颜色和形状同时编码分组，即使黑白打印也能区分；椭圆只帮助阅读样本分布，不进入任何显著性检验。\n\n### 3. Mantel 图同时画效应方向和 multiplicity-adjusted P\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_p <- function(p) {\n  ifelse(p <= 0.001, \"<=0.001\", sprintf(\"%.3f\", p))\n}\nmantel_plot_data <- data.frame(\n  Label = c(\n    \"Geographic distance\",\n    \"Climate distance\",\n    \"Edaphic distance\",\n    \"Edaphic | geographic\"\n  ),\n  Statistic = c(\n    mantel_results$Statistic[mantel_results$DistanceBlock == \"Geographic\"],\n    mantel_results$Statistic[mantel_results$DistanceBlock == \"Climate\"],\n    mantel_results$Statistic[mantel_results$DistanceBlock == \"Edaphic\"],\n    partial_mantel_sensitivity$Statistic\n  ),\n  PValue = c(\n    mantel_results$PAdjustedHolm[mantel_results$DistanceBlock == \"Geographic\"],\n    mantel_results$PAdjustedHolm[mantel_results$DistanceBlock == \"Climate\"],\n    mantel_results$PAdjustedHolm[mantel_results$DistanceBlock == \"Edaphic\"],\n    partial_mantel_sensitivity$PValue\n  ),\n  Family = c(rep(\"Primary Mantel family\", 3), \"Partial Mantel sensitivity\"),\n  stringsAsFactors = FALSE\n)\nmantel_plot_data$Label <- factor(\n  mantel_plot_data$Label,\n  levels = rev(mantel_plot_data$Label)\n)\nmantel_plot_data$Annotation <- sprintf(\n  \"r = %.3f; P %s\",\n  mantel_plot_data$Statistic,\n  format_p(mantel_plot_data$PValue)\n)\n\nmantel_plot <- ggplot2::ggplot(\n  mantel_plot_data,\n  ggplot2::aes(Statistic, Label, colour = Family, shape = Family)\n) +\n  ggplot2::geom_segment(\n    ggplot2::aes(x = 0, xend = Statistic, yend = Label),\n    linewidth = 0.8,\n    alpha = 0.65,\n    show.legend = FALSE\n  ) +\n  ggplot2::geom_point(size = 3.2) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = Annotation),\n    hjust = -0.08,\n    colour = \"#111111\",\n    family = font_pub,\n    size = 3.1,\n    show.legend = FALSE\n  ) +\n  ggplot2::geom_vline(xintercept = 0, colour = \"#555555\", linewidth = 0.4) +\n  ggplot2::scale_colour_manual(\n    values = c(\n      \"Primary Mantel family\" = \"#0072B2\",\n      \"Partial Mantel sensitivity\" = \"#D55E00\"\n    ),\n    name = NULL\n  ) +\n  ggplot2::scale_shape_manual(\n    values = c(\n      \"Primary Mantel family\" = 16,\n      \"Partial Mantel sensitivity\" = 17\n    ),\n    name = NULL\n  ) +\n  ggplot2::coord_cartesian(xlim = c(0, 0.72), clip = \"off\") +\n  ggplot2::labs(\n    title = \"Mantel statistics compare two distance structures\",\n    subtitle = \"Primary Spearman tests use Holm correction across three prespecified blocks\",\n    x = \"Matrix correlation\",\n    y = NULL,\n    caption = paste(\n      \"The partial Mantel row uses Pearson correlation and is a sensitivity analysis only.\",\n      \"Distance correlation does not identify an independent environmental cause.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  ggplot2::theme(\n    panel.grid.major.y = ggplot2::element_blank(),\n    legend.position = \"top\",\n    plot.margin = ggplot2::margin(5.5, 38, 5.5, 5.5)\n  )\n\nsave_pub(\n  mantel_plot,\n  \"figures/25-mantel-distance-blocks\",\n  width = 183,\n  height = 96\n)\nmantel_plot\n```\n\n::: {.cell-output-display}\n![三个预设 Mantel 距离块及一个 partial Mantel 敏感性结果。蓝色主检验标注 Holm-adjusted P；橙色 partial Mantel 标注原始 P 且不进入主结论。](25-environment-variance_files/figure-html/fig-mantel-distance-blocks-1.png){#fig-mantel-distance-blocks}\n:::\n:::\n\n\n### 4. VPA 用带符号的条形图，不伪造重叠圆面积\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariation_plot_data <- variation_partition\nvariation_plot_data$Fraction <- factor(\n  variation_plot_data$Fraction,\n  levels = rev(variation_plot_data$Fraction)\n)\nvariation_palette <- c(\n  \"Pure edaphic | wetland group\" = \"#0072B2\",\n  \"Pure wetland group | edaphic\" = \"#D55E00\",\n  \"Shared edaphic + wetland group\" = \"#CC79A7\",\n  \"Unexplained\" = \"#9CA3AF\"\n)\n\nvariation_plot <- ggplot2::ggplot(\n  variation_plot_data,\n  ggplot2::aes(AdjustedR2, Fraction, fill = Fraction)\n) +\n  ggplot2::geom_col(width = 0.64, colour = \"#333333\", linewidth = 0.35) +\n  ggplot2::geom_vline(xintercept = 0, colour = \"#333333\", linewidth = 0.4) +\n  ggplot2::geom_text(\n    ggplot2::aes(\n      label = scales::percent(AdjustedR2, accuracy = 0.1),\n      hjust = ifelse(AdjustedR2 >= 0, -0.08, 1.08)\n    ),\n    family = font_pub,\n    size = 3.2\n  ) +\n  ggplot2::scale_fill_manual(values = variation_palette, guide = \"none\") +\n  ggplot2::scale_x_continuous(\n    labels = scales::label_percent(accuracy = 1),\n    expand = ggplot2::expansion(mult = c(0.02, 0.13))\n  ) +\n  ggplot2::labs(\n    title = \"Adjusted variation partition separates unique and shared fractions\",\n    subtitle = sprintf(\n      \"Combined adjusted R2 = %.3f; both pure fractions Holm P <= 0.002\",\n      combined_r2$adj.r.squared\n    ),\n    x = \"Adjusted fraction of Hellinger community variation\",\n    y = NULL,\n    caption = paste(\n      \"Shared variation is not directly testable or attributable to one predictor set.\",\n      \"Wetland group is a broad context variable and is completely confounded with salinity here.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  ggplot2::theme(\n    panel.grid.major.y = ggplot2::element_blank(),\n    plot.margin = ggplot2::margin(5.5, 18, 5.5, 5.5)\n  )\n\nsave_pub(\n  variation_plot,\n  \"figures/25-variation-partition\",\n  width = 183,\n  height = 100\n)\nvariation_plot\n```\n\n::: {.cell-output-display}\n![Hellinger community matrix 的 adjusted variation partition。只有两个 pure fractions 可直接检验；shared fraction 是算术重叠，不能归因给某一组变量。](25-environment-variance_files/figure-html/fig-variation-partition-1.png){#fig-variation-partition}\n:::\n:::\n\n\n四张图均导出 PDF、SVG、600 ppi PNG 和 LZW-compressed TIFF。条形图保留零线和带符号数值，因此换成自己的数据后即使出现负 adjusted fraction，也不会被面积图或强制截断掩盖。\n\n<details>\n<summary><strong>展开：对完整结果和四格式导出做机器回验</strong></summary>\n\n仓库中的审计脚本会重新读取四张表、重建同一 999-row permutation matrix，并核对统计量、字体、物理尺寸、像素、SVG 文字和 TIFF 压缩：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nRscript --vanilla scripts/validate_environment_variance.R \\\n  --project-root . \\\n  --input-dir data/small \\\n  --output-dir results/25-environment-variance \\\n  --figure-dir figures\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naudit_path <-\n  \"results/25-environment-variance/environment-variance-summary.json\"\n\nif (file.exists(audit_path)) {\n  audit_summary <- jsonlite::read_json(audit_path)\n  stopifnot(\n    audit_summary$checks_total == 221L,\n    audit_summary$checks_passed == 221L,\n    audit_summary$checks_failed == 0L,\n    audit_summary$dataset$samples == 90L,\n    audit_summary$standardization$retained_features == 11113L,\n    audit_summary$graphics$primary_figures == 4L,\n    audit_summary$graphics$format_files == 16L\n  )\n  audit_summary[c(\n    \"dataset\", \"standardization\", \"permutations\", \"mantel\",\n    \"variation_partition\", \"graphics\", \"checks_total\", \"checks_failed\"\n  )]\n} else {\n  data.frame(\n    Audit = \"Optional repository-level verification\",\n    Status = \"NOT RUN\",\n    NextStep = \"Run the Rscript command shown immediately above\"\n  )\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$dataset\n$dataset$source\n[1] \"microeco 2.0.0 packaged wetland 16S tables\"\n\n$dataset$features\n[1] 13628\n\n$dataset$samples\n[1] 90\n\n$dataset$reads\n[1] 1619670\n\n$dataset$environment_source_samples\n[1] 200\n\n$dataset$matched_samples\n[1] 90\n\n$dataset$environment_variables\n[1] 11\n\n$dataset$groups\n[1] 3\n\n\n$standardization\n$standardization$primary_prevalence\n[1] 0.05\n\n$standardization$minimum_samples\n[1] 5\n\n$standardization$retained_features\n[1] 11113\n\n$standardization$envfit_mantel\n[1] \"Relative-abundance Bray-Curtis\"\n\n$standardization$variation_partition\n[1] \"Hellinger-transformed community matrix\"\n\n\n$permutations\n$permutations$seed\n[1] 20260725\n\n$permutations$mode\n[1] \"Free sample-label permutations\"\n\n$permutations$count\n[1] 999\n\n$permutations$minimum_p\n[1] 0.001\n\n$permutations$unique_rows\n[1] 999\n\n$permutations$identity_rows\n[1] 0\n\n$permutations$matrix_sha256\n[1] \"e69df77a49350b4f40997d316bb62a7eb69749f03882ff8c74ed41966e891499\"\n\n\n$mantel\n$mantel$family_size\n[1] 3\n\n$mantel$rejections_holm\n[1] 3\n\n$mantel$edaphic_rho\n[1] 0.3318957\n\n$mantel$climate_rho\n[1] 0.3950914\n\n$mantel$geographic_rho\n[1] 0.5869835\n\n$mantel$partial_edaphic_given_geographic_pearson\n[1] 0.1884762\n\n$mantel$partial_mantel_primary\n[1] FALSE\n\n\n$variation_partition\n$variation_partition$combined_raw_r2\n[1] 0.3382372\n\n$variation_partition$combined_adjusted_r2\n[1] 0.2817453\n\n$variation_partition$pure_edaphic_adjusted_r2\n[1] 0.0967321\n\n$variation_partition$pure_group_adjusted_r2\n[1] 0.1140496\n\n$variation_partition$shared_adjusted_r2\n[1] 0.07096358\n\n$variation_partition$unexplained_adjusted_r2\n[1] 0.7182547\n\n$variation_partition$testable_fractions\n[1] 2\n\n$variation_partition$pure_fraction_rejections_holm\n[1] 2\n\n$variation_partition$maximum_vif\n[1] 2.143884\n\n\n$graphics\n$graphics$font_family\n[1] \"DejaVu Sans\"\n\n$graphics$primary_figures\n[1] 4\n\n$graphics$vector_files\n[1] 8\n\n$graphics$raster_files\n[1] 8\n\n$graphics$format_files\n[1] 16\n\n$graphics$raster_ppi\n[1] 600\n\n$graphics$svg_files_with_text\n[1] 4\n\n$graphics$svg_chinese_characters\n[1] 0\n\n$graphics$pdf_files_with_embedded_font\n[1] 4\n\n$graphics$lzw_tiff_files\n[1] 4\n\n$graphics$dimension_checks_passed\n[1] 16\n\n\n$checks_total\n[1] 221\n\n$checks_failed\n[1] 0\n```\n\n\n:::\n:::\n\n\n</details>\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"1. 把 envfit r²、Mantel r 和 VPA adjusted R² 混成一列\"}\n三者分母和问题不同：`envfit` 是变量与给定排序轴的 squared correlation，Mantel 是两个距离矩阵的相关，VPA 才是 Hellinger community matrix 的 adjusted variation fraction。不能比较数值大小后说“哪个方法解释得最多”。\n:::\n\n::: {.callout-caution title=\"2. 一口气测几十个变量，却只报告原始 P\"}\n本例把 11 个 `envfit` P 值用 BH 校正，把 3 个预设 Mantel blocks 和 2 个可检验 VPA pure fractions 分别用 Holm 校正。不同科学问题可构成不同检验族，但分组规则必须在看结果前说明。\n:::\n\n::: {.callout-caution title=\"3. 用同一批高度相关变量填满 VPA\"}\nTOC 与 TN 的 (r=0.988)。同时纳入会让系数和独立组分难以辨认，还可能推高 VIF。先按测量含义定义集合，再用相关矩阵与 VIF 审计；不要用逐步筛选制造“独立解释率”。\n:::\n\n::: {.callout-caution title=\"4. 把 shared fraction 当作协同机制\"}\n共享组分只是两个预测集合对同一群落变异的重叠，可能来自真实共驱动、代理变量、空间结构或混杂。它不可直接检验，也不能自动命名为“interaction”。\n:::\n\n::: {.callout-caution title=\"5. 用 partial Mantel 宣称已经控制空间\"}\npartial Mantel 不是一般性的空间因果调整。把它限定为敏感性分析，并优先在样本级 RDA/db-RDA、mixed model 或 spatial eigenfunction model 中显式表达空间结构。\n:::\n\n::: {.callout-caution title=\"6. 忽略置换单位\"}\n自由置换只适用于可交换的独立样本。配对、纵向、区组、家庭、地点或笼位数据必须建立相应 restriction；置换次数再多也不能修复错误的 exchangeability。\n:::\n\n::: {.callout-caution title=\"7. 看到 Group 显著就解释成 Saline\"}\n本数据中 Inland wetland 全为 non-saline，另两组全为 saline。Group 与 Saline 完全混杂，无法从这些样本中分开估计；VPA 的 pure group fraction 只能称为 wetland-group context association。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> Features present in at least 5% of samples (≥5 of 90 samples) were retained, yielding 11,113 OTUs. For ordination fitting and Mantel analyses, counts were converted to within-sample relative abundances and Bray–Curtis dissimilarities were calculated. A two-axis principal coordinates analysis was fitted with the Lingoes option; the observed distance matrix required an additive constant of zero. Eleven standardized continuous covariates were fitted to the displayed ordination using `envfit`, with Benjamini–Hochberg correction across the 11 permutation tests. Three prespecified environmental distance blocks—edaphic, climatic, and geographic—were tested against Bray–Curtis dissimilarity using one-sided Spearman Mantel tests and Holm correction across the three tests. Geographic distances were Haversine great-circle distances, whereas edaphic and climatic distances were Euclidean distances calculated after variable-wise Z-standardization. Community counts were Hellinger transformed for variation partitioning. Adjusted variation was partitioned between five edaphic variables (pH, total organic carbon, ammonium, nitrate, and conductivity) and a three-level wetland-group factor; total nitrogen was excluded from this set because of near redundancy with total organic carbon (Pearson r = 0.988). The two pure fractions were tested by partial RDA and Holm corrected; the shared fraction was not tested directly. All tests used the same 999-row free-permutation matrix generated with seed 20260725. Because no repeat, block, site, time, or batch identifier was available in the public metadata, inference assumes exchangeable samples. Partial Mantel analysis was reported as a non-primary sensitivity analysis. All analyses were performed in R 4.4.1 with vegan 2.6-6.1.\n\n结果段可以紧接：\n\n> Ten of 11 covariates were associated with the displayed two-axis PCoA after BH correction. Edaphic, climatic, and geographic distances were positively associated with Bray–Curtis dissimilarity (Spearman r = 0.332, 0.395, and 0.587, respectively; Holm-adjusted P = 0.003 for each). The combined edaphic and wetland-group model accounted for an adjusted 28.2% of Hellinger-transformed community variation. Pure edaphic, pure wetland-group, shared, and unexplained fractions were 9.7%, 11.4%, 7.1%, and 71.8%, respectively; both pure fractions had Holm-adjusted P = 0.002. Wetland group was completely confounded with salinity, so the group fraction was interpreted as contextual association rather than a salinity effect.\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. 只替换四个路径和分组列名\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"your_project/otutab.tsv\",\n  taxonomy = \"your_project/taxonomy.tsv\",\n  metadata = \"your_project/metadata.tsv\",\n  environment = \"your_project/environment.tsv\"\n)\n\ngroup_column <- \"Treatment\"\nmetadata$Group <- factor(metadata[[group_column]])\n```\n:::\n\n\n- `otutab.tsv`：行为 feature、列为 sample、值为非负整数 counts；\n- `taxonomy.tsv`：行名与 `otutab` feature IDs 一致；\n- `metadata.tsv`：行名与 `otutab` sample IDs 一致；\n- `environment.tsv`：行为 sample、列为可解释的数值环境变量，可包含额外样本但不能有重复 ID。\n\n### 2. 预先写下三个分析合同\n\n在运行前固定：\n\n1. feature filter 和群落表示；\n2. 哪些环境变量组成哪个 block，以及删去冗余变量的规则；\n3. `envfit`、Mantel 与 VPA 各自的检验族和 P 值校正方法。\n\n若变量单位不同，Euclidean environmental distance 前必须 Z-score。若变量含大量缺失，不要让每个检验偷偷使用不同样本子集；先定义共同 complete cases，输出保留/剔除样本表。\n\n### 3. 按研究设计生成合法置换\n\n独立样本可以沿用自由置换。完全区组示例：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctrl <- permute::how(nperm = 999)\npermute::setBlocks(ctrl) <- metadata$Block\nset.seed(20260725)\npermutation_matrix <- permute::shuffleSet(\n  nrow(metadata),\n  nset = 999,\n  control = ctrl\n)\n```\n:::\n\n\n纵向、split-plot 或多层采样还要设置 `Plots()` / `Within()` 结构，不能只把所有样本放进同一个 block。先画清随机化和采样层级，再写 `how()`。\n\n### 4. 两个以上预测集合时先考虑可解释性\n\n`varpart()`最多可接收四个解释表，但集合越多，组分数量和不可检验共享部分增长越快。优先选择有明确科学含义的少量 blocks，例如 soil chemistry、climate、space；每个 block 内先处理冗余，再报告 adjusted fractions 和可检验边界。\n\n### 5. 结果至少保留六张审计表\n\n- 环境变量缺失、单位、均值、标准差和取值范围；\n- 变量相关矩阵与高相关 pairs；\n- 完整 `envfit` 11/全部变量结果，而非只留图上的箭头；\n- Mantel block 定义、statistic、raw P、adjusted P 和置换数；\n- VPA 四组分、testable 标记、pure-fraction tests 和 VIF；\n- filter、conditioning 与 permutation sensitivity branches。\n\n## 参考 {#sec-references}\n\n1. Falony G, Joossens M, Vieira-Silva S, et al. Population-level analysis of gut microbiome variation. *Science*. 2016;352:560–564. [doi:10.1126/science.aad3503](https://doi.org/10.1126/science.aad3503).\n2. An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035).\n3. Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97:fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255).\n4. Legendre P, Gallagher ED. Ecologically meaningful transformations for ordination of species data. *Oecologia*. 2001;129:271–280. [doi:10.1007/s004420100716](https://doi.org/10.1007/s004420100716).\n5. Peres-Neto PR, Legendre P, Dray S, Borcard D. Variation partitioning of species data matrices: estimation and comparison of fractions. *Ecology*. 2006;87:2614–2625. [doi:10.1890/0012-9658(2006)87%5B2614:VPOSDM%5D2.0.CO;2](https://doi.org/10.1890/0012-9658(2006)87%5B2614:VPOSDM%5D2.0.CO;2).\n6. Guillot G, Rousset F. Dismantling the Mantel tests. *Methods in Ecology and Evolution*. 2013;4:336–344. [doi:10.1111/2041-210X.12018](https://doi.org/10.1111/2041-210X.12018).\n7. Oksanen J, Simpson GL, Blanchet FG, et al. `vegan` reference: [`envfit`](https://vegandevs.github.io/vegan/reference/envfit.html), [`mantel`](https://vegandevs.github.io/vegan/reference/mantel.html), [`varpart`](https://vegandevs.github.io/vegan/reference/varpart.html), and [`decostand`](https://vegandevs.github.io/vegan/reference/decostand.html).\n",
    "supporting": [
      "25-environment-variance_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}