{
  "hash": "628256748f8711c04c47e59a68014681",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 27 篇 · 多分类级组成（门→纲→目→科→属逐级）\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**从同一张 feature count table 同时生成 Phylum、Class、Order、Family、Genus 五级组成结果，并让 rank、lineage、缺失父级、Top-N 与分母都可审计。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`。  \n> **预计资源：**示例含 13,628 个 OTU、90 个样本和 1,619,670 reads；五级聚合、完整 lineage 审计与四张 600 ppi 图通常需 1–3 分钟，峰值内存低于 1 GB。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n微生物组论文常把门、纲、目、科、属的组成并排展示：上层级交代群落骨架，下层级追踪更具体的分类单元。真正困难的不是把 `Phylum` 换成 `Genus`，而是保证每个面板仍使用同一批样本、同一分母和可追踪的分类路径，同时避免把跨层级同名 taxon 合并。\n\n本页使用 `microeco` 2.0.0 随包分发的中国湿地土壤 16S 数据。原研究 [An et al. (2019)](https://doi.org/10.1016/j.geoderma.2018.09.035)比较 inland、coastal 与 Tibetan wetland 的细菌群落；[Liu et al. (2021)](https://doi.org/10.1093/femsec/fiaa255)给出了三件套数据入口和逐分类级丰度计算框架。层级图的表达思路参考 [Metacoder](https://doi.org/10.1371/journal.pcbi.1005404)，但这里从公开 count、taxonomy 和 metadata 重新计算并绘制四张原创图。\n\n::: {.callout-important title=\"先给结论\"}\n以全部 reads 为分母、先逐样本闭合再等权平均，能够命名到 Phylum、Class、Order、Family、Genus 的 reads 比例依次为 **99.65%、96.80%、85.57%、67.96%、36.89%**。最大分辨率损失发生在 Family→Genus，一步减少 **31.07 个百分点**。\n\n属水平可命名比例在 inland、coastal、Tibetan wetland 分别为 **28.99%、38.38%、43.31%**。因此删除 `Unknown genus` 后重新归一化，会给三组施加不同放大倍数；本页主结果始终保留全部 reads 分母。\n\n共有 **754** 条完整 Phylum→Genus lineage，合计覆盖 34.38% reads；丰度最高的 12 条完整 lineage 仅覆盖 10.19%。另外有 324 个 features（2.52% reads）出现“Family 未知、Genus 已知”，这些断裂路径被原样保留，不根据 genus 反推或补写 family。\n:::\n\n## 理论：多分类级不是把五张表直接拼起来 {#sec-theory}\n\n### 1. 每个 rank 都有自己的 100%，跨 rank 不能相加\n\n对样本 (j)，把 feature counts 聚合到 rank (r) 后：\n\n\\[\np_{krj}=\\frac{x_{krj}}{\\sum_k x_{krj}}, \\qquad\n\\sum_k p_{krj}=1.\n\\]\n\n同一条 read 会同时贡献给它的 phylum、class、order、family 和 genus。五个 rank 各自闭合到 100%，并不意味着把五级比例相加后得到新的“总丰度”；那会把同一证据重复计算五次。\n\n### 2. 联合键至少是 `Rank + Lineage`，不能只用显示名\n\n裸名称并不天然唯一。本数据有 13 个名称出现在多个 rank，例如 `Acidobacteria` 同时可见于 Phylum 和 Class。Family 层还有 `Family XII` 与 `FamilyI` 分别对应多个父系路径。联合表应保存：\n\n```text\nRankQualifiedTaxon = \"P · Acidobacteria\"\nLineageKey = \"Acidobacteria > ... > Candidatus Solibacter\"\n```\n\n前者防止跨 rank 合并，后者防止同一 rank 内的多父系同名标签被错误压成一个 lineage。\n\n### 3. 缺失父级是证据边界，不是待自动补齐的空格\n\n本数据在 Phylum→Class、Class→Order、Order→Family 三个 transition 中没有“父级未知、子级已知”的记录；Family→Genus 却有 324 个 features、17 个 genus 落在这种断裂路径中。它们可能来自参考库的 rank 结构或分类器输出，不能仅凭 genus 名称反推 family。\n\n`Incertae Sedis` 也不等于空注释：它表示来源数据库提供了一个未定位置的命名标签。本页保留原标签、单独审计，但不把它写成已完全解析的标准分类单元。\n\n### 4. 同一个 Top 10，在不同 rank 覆盖率完全不同\n\n按 90 个样本的等权均值选择全局 Top 10，Phylum、Class、Order、Family、Genus 的平均覆盖率分别为 94.80%、59.00%、34.77%、23.67%、9.52%。Top-N 是排版决定，不是跨 rank 等价的生物学过滤器。\n\n<details>\n<summary><strong>深入：完整 lineage 与“该 rank 有名称”为什么不是一回事</strong></summary>\n\n“Genus 有名称”只检查 genus 单元格是否非空；“完整 Phylum→Genus lineage”要求五级连续可追踪。本例 genus named fraction 为 36.89%，完整 genus lineage 只有 34.38%，差出的 2.52% 正是 family 缺失但 genus 已知的断裂路径。层级图若要求连线，应使用完整 lineage；rank 独立汇总则可以保留这些 genus，但必须显式标注缺失父级。\n\n</details>\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、下载真实数据和定义作图函数</strong></summary>\n\n首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"digest\", \"ggplot2\", \"jsonlite\", \"ragg\", \"readr\",\n  \"scales\", \"svglite\", \"systemfonts\"\n))\n```\n:::\n\n\n下载 `microeco` 2.0.0 源码包、核对 SHA-256，并导出三件套：\n\n\n::: {.cell}\n\n```{.r .cell-code}\narchive <- \"data/raw/microeco_2.0.0.tar.gz\"\nsource_url <- paste0(\n  \"https://cran.r-project.org/src/contrib/Archive/\",\n  \"microeco/microeco_2.0.0.tar.gz\"\n)\nexpected_archive_sha256 <- paste0(\n  \"454a3b71ceeea86bdd54f475a12b5bac\",\n  \"9c3b124f663b8dc6e560827fca89ebfd\"\n)\n\ndir.create(\"data/raw\", recursive = TRUE, showWarnings = FALSE)\ndir.create(\"data/small\", recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(archive)) {\n  download.file(source_url, archive, mode = \"wb\")\n}\nstopifnot(identical(\n  digest::digest(file = archive, algo = \"sha256\", serialize = FALSE),\n  expected_archive_sha256\n))\n\nrequired <- c(\n  \"microeco/data/otu_table_16S.RData\",\n  \"microeco/data/taxonomy_table_16S.RData\",\n  \"microeco/data/sample_info_16S.RData\"\n)\nextract_dir <- tempfile(\"microeco-data-\")\ndir.create(extract_dir)\nutils::untar(archive, files = required, exdir = extract_dir)\n\ndata_env <- new.env(parent = emptyenv())\nfor (relative_path in required) {\n  load(file.path(extract_dir, relative_path), envir = data_env)\n}\n\nwrite_keyed_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name), x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out, path, sep = \"\\t\", quote = FALSE,\n    row.names = FALSE, na = \"\"\n  )\n}\n\nwrite_keyed_tsv(data_env$otu_table_16S, \"FeatureID\", \"data/small/otutab.tsv\")\nwrite_keyed_tsv(\n  data_env$taxonomy_table_16S,\n  \"FeatureID\",\n  \"data/small/taxonomy.tsv\"\n)\nwrite_keyed_tsv(\n  data_env$sample_info_16S,\n  \"SampleID\",\n  \"data/small/metadata.tsv\"\n)\nunlink(extract_dir, recursive = TRUE)\n```\n:::\n\n\n出版级函数直接内联；图内统一使用英文和 `DejaVu Sans`：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nset.seed(20260727)\nfont_pub <- \"DejaVu Sans\"\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\", linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\", size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot,\n    width = width, height = height, units = units,\n    device = grDevices::cairo_pdf, family = base_family, bg = \"white\"\n  )\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"), plot,\n      width = width, height = height, units = units,\n      device = svglite::svglite, bg = \"white\"\n    )\n  }\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot,\n    width = width, height = height, units = units, dpi = dpi,\n    device = ragg::agg_png, bg = \"white\"\n  )\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"), plot,\n      width = width, height = height, units = units, dpi = dpi,\n      device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\"\n    )\n  }\n  invisible(plot)\n}\n\nclean_taxon <- function(x, rank_name) {\n  x <- trimws(as.character(x))\n  x <- sub(\"^[A-Za-z]__\", \"\", x)\n  missing <- is.na(x) | x == \"\" | tolower(x) %in% c(\n    \"unassigned\", \"unclassified\", \"unknown\", \"na\", \"nan\"\n  )\n  x[missing] <- paste(\"Unknown\", tolower(rank_name))\n  x\n}\n\nwrap_label <- function(x, width = 16L) {\n  vapply(\n    x,\n    function(value) paste(strwrap(value, width = width), collapse = \"\\n\"),\n    character(1)\n  )\n}\n```\n:::\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取三件套并锁定方向、ID 和哈希\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character(),\n    col_types = readr::cols(.default = readr::col_character())\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\ninput_paths <- c(\n  otutab = \"data/small/otutab.tsv\",\n  taxonomy = \"data/small/taxonomy.tsv\",\n  metadata = \"data/small/metadata.tsv\"\n)\nexpected_sha256 <- c(\n  otutab = \"76fa79c38da889f35978dc86da4641a270961746709ff38049ee5f67e3c6f7a3\",\n  taxonomy = \"725280bb9a0cd9bda7b540022e92af945ceed52527f8b2d220b055b4489f6901\",\n  metadata = \"df24771dccf27607ddf922c6bca2cafa876d946fbe2e09d14b601accce66ba64\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  function(path) digest::digest(\n    file = path, algo = \"sha256\", serialize = FALSE\n  ),\n  character(1)\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\notutab <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\n\ncounts <- as.matrix(otutab)\nstorage.mode(counts) <- \"numeric\"\nstopifnot(\n  identical(rownames(counts), rownames(taxonomy)),\n  setequal(colnames(counts), rownames(metadata)),\n  all(counts >= 0),\n  all(counts == round(counts)),\n  all(rowSums(counts) > 0),\n  all(colSums(counts) > 0)\n)\nmetadata <- metadata[colnames(counts), , drop = FALSE]\n\ngroup_display <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan wetland\"\n)\ngroup_codes <- c(\"IW\", \"CW\", \"TW\")\nmetadata$SampleID <- rownames(metadata)\nmetadata$GroupDisplay <- unname(group_display[metadata$Group])\n\nsample_depths <- colSums(counts)\nrelative_feature <- sweep(counts, 2L, sample_depths, \"/\")\nstopifnot(max(abs(colSums(relative_feature) - 1)) <= 1e-12)\n\ndata.frame(\n  Features = nrow(counts),\n  Samples = ncol(counts),\n  Reads = sum(counts),\n  MinimumDepth = min(sample_depths),\n  MaximumDepth = max(sample_depths)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Features Samples   Reads MinimumDepth MaximumDepth\n1    13628      90 1619670        10364        37374\n```\n\n\n:::\n:::\n\n\n先查看三张表，而不是只接受一个看不见内部结构的对象：\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab[1:5, 1:5, drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxonomy[1:6, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\nOTU_706  k__Bacteria                     p__Actinobacteria\n                         Class               Order               Family\nOTU_4272            c__Bacilli       o__Bacillales                  f__\nOTU_236                    c__                 o__                  f__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__\nOTU_32                     c__                 o__                  f__\nOTU_706      c__Actinobacteria       o__Frankiales   f__Nakamurellaceae\n                  Genus Species\nOTU_4272            g__     s__\nOTU_236             g__     s__\nOTU_399             g__     s__\nOTU_1556            g__     s__\nOTU_32              g__     s__\nOTU_706  g__Nakamurella     s__\n```\n\n\n:::\n\n```{.r .cell-code}\nmetadata[1:6, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Group Type          Saline SampleID   GroupDisplay\nS1    IW   NE Non-saline soil       S1 Inland wetland\nS2    IW   NE Non-saline soil       S2 Inland wetland\nS3    IW   NE Non-saline soil       S3 Inland wetland\nS4    IW   NE Non-saline soil       S4 Inland wetland\nS5    IW   NE Non-saline soil       S5 Inland wetland\nS6    IW   NE Non-saline soil       S6 Inland wetland\n```\n\n\n:::\n:::\n\n\n### 2. 逐 rank 聚合，并保留 rank-qualified label\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_names <- c(\"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\")\nrank_prefix <- c(\n  Phylum = \"P\", Class = \"C\", Order = \"O\", Family = \"F\", Genus = \"G\"\n)\nunknown_labels <- setNames(paste(\"Unknown\", tolower(rank_names)), rank_names)\n\ntaxonomy_clean <- as.data.frame(\n  setNames(\n    lapply(\n      rank_names,\n      function(rank_name) clean_taxon(taxonomy[[rank_name]], rank_name)\n    ),\n    rank_names\n  ),\n  check.names = FALSE,\n  stringsAsFactors = FALSE\n)\nrownames(taxonomy_clean) <- rownames(taxonomy)\n\nrank_relative <- list()\nrank_counts <- list()\nresolution_rows <- list()\nfor (rank_name in rank_names) {\n  labels <- taxonomy_clean[[rank_name]]\n  rank_counts[[rank_name]] <- rowsum(counts, labels, reorder = TRUE)\n  rank_relative[[rank_name]] <- sweep(\n    rank_counts[[rank_name]], 2L, sample_depths, \"/\"\n  )\n  stopifnot(\n    max(abs(colSums(rank_relative[[rank_name]]) - 1)) <= 1e-12,\n    !anyDuplicated(rownames(rank_relative[[rank_name]]))\n  )\n\n  rel_rank <- rank_relative[[rank_name]]\n  unknown_label <- unknown_labels[[rank_name]]\n  known_taxa <- setdiff(rownames(rel_rank), unknown_label)\n  known_order <- known_taxa[order(\n    rowMeans(rel_rank[known_taxa, , drop = FALSE]),\n    decreasing = TRUE\n  )]\n  top10 <- head(known_order, 10L)\n  known_sample <- 1 - rel_rank[unknown_label, ]\n  resolution_rows[[rank_name]] <- data.frame(\n    Rank = rank_name,\n    Labels = nrow(rel_rank),\n    KnownLabels = length(known_taxa),\n    KnownMean = mean(known_sample),\n    KnownMinimum = min(known_sample),\n    KnownMaximum = max(known_sample),\n    UnknownMean = mean(rel_rank[unknown_label, ]),\n    Top10CoverageMean = mean(colSums(rel_rank[top10, , drop = FALSE])),\n    IncertaeSedisFeatures = sum(grepl(\n      \"Incertae Sedis\", labels, fixed = TRUE\n    )),\n    stringsAsFactors = FALSE\n  )\n}\nrank_resolution <- do.call(rbind, resolution_rows)\nrank_resolution$ResolutionLossPP <- c(\n  NA_real_,\n  100 * head(rank_resolution$KnownMean, -1L) -\n    100 * tail(rank_resolution$KnownMean, -1L)\n)\nrank_resolution\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Rank Labels KnownLabels KnownMean KnownMinimum KnownMaximum\nPhylum Phylum     56          55 0.9965362    0.9746454    0.9993507\nClass   Class    128         127 0.9679785    0.9173091    0.9924631\nOrder   Order    217         216 0.8557273    0.6178719    0.9737159\nFamily Family    394         393 0.6796275    0.3875696    0.9294762\nGenus   Genus    772         771 0.3689439    0.1556430    0.7847552\n       UnknownMean Top10CoverageMean IncertaeSedisFeatures ResolutionLossPP\nPhylum 0.003463782        0.94803047                     0               NA\nClass  0.032021456        0.59004532                    28         2.855767\nOrder  0.144272720        0.34765278                   100        11.225126\nFamily 0.320372461        0.23671066                   172        17.609974\nGenus  0.631056113        0.09521805                     0        31.068365\n```\n\n\n:::\n:::\n\n\n门到属的标签数依次为 56、128、217、394、772；标签越来越多，并不代表可解释 reads 越来越多。属水平正好相反：大量 reads 停在更高 rank。\n\n### 3. 逐组审计注释分辨率，不删除 Unknown\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_resolution_rows <- list()\nfor (rank_name in rank_names) {\n  rel_rank <- rank_relative[[rank_name]]\n  known_sample <- 1 - rel_rank[unknown_labels[[rank_name]], ]\n\n  group_resolution_rows[[length(group_resolution_rows) + 1L]] <- data.frame(\n    GroupCode = \"ALL\",\n    Group = \"All samples\",\n    Rank = rank_name,\n    KnownMean = mean(known_sample),\n    KnownMinimum = min(known_sample),\n    KnownMaximum = max(known_sample),\n    stringsAsFactors = FALSE\n  )\n  for (group_code in group_codes) {\n    ids <- metadata$SampleID[metadata$Group == group_code]\n    values <- known_sample[ids]\n    group_resolution_rows[[length(group_resolution_rows) + 1L]] <- data.frame(\n      GroupCode = group_code,\n      Group = unname(group_display[group_code]),\n      Rank = rank_name,\n      KnownMean = mean(values),\n      KnownMinimum = min(values),\n      KnownMaximum = max(values),\n      stringsAsFactors = FALSE\n    )\n  }\n}\ngroup_rank_resolution <- do.call(rbind, group_resolution_rows)\n\nsubset(group_rank_resolution, Rank == \"Genus\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   GroupCode           Group  Rank KnownMean KnownMinimum KnownMaximum\n17       ALL     All samples Genus 0.3689439    0.1556430    0.7847552\n18        IW  Inland wetland Genus 0.2899131    0.1556430    0.4689417\n19        CW Coastal wetland Genus 0.3838468    0.2367641    0.7847552\n20        TW Tibetan wetland Genus 0.4330718    0.2877018    0.6707779\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning title=\"不要把 known-only 比例冒充 all-read relative abundance\"}\nInland wetland 的 `Unknown genus` 平均为 71.01%，Tibetan wetland 为 56.69%。若各样本删除 Unknown 后重新闭合，两个组的已知 genus 会被不同程度放大；这既改变数值，也改变组间视觉距离。\n:::\n\n### 4. 建 lineage key，审计断裂路径与同名冲突\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_equal_mean <- rowMeans(relative_feature)\nknown_matrix <- vapply(\n  rank_names,\n  function(rank_name) {\n    taxonomy_clean[[rank_name]] != unknown_labels[[rank_name]]\n  },\n  logical(nrow(taxonomy_clean))\n)\ncolnames(known_matrix) <- rank_names\n\ncomplete_depth <- apply(known_matrix, 1L, function(x) {\n  first_unknown <- which(!x)[1L]\n  if (is.na(first_unknown)) length(x) else first_unknown - 1L\n})\nlineage_key <- apply(\n  taxonomy_clean[, rank_names, drop = FALSE],\n  1L,\n  paste,\n  collapse = \" > \"\n)\n\nlineage_gap_rows <- list()\nfor (i in 2:length(rank_names)) {\n  parent_rank <- rank_names[[i - 1L]]\n  child_rank <- rank_names[[i]]\n  parent_unknown <- taxonomy_clean[[parent_rank]] == unknown_labels[[parent_rank]]\n  child_unknown <- taxonomy_clean[[child_rank]] == unknown_labels[[child_rank]]\n  gap <- parent_unknown & !child_unknown\n  lineage_gap_rows[[length(lineage_gap_rows) + 1L]] <- data.frame(\n    Transition = paste(parent_rank, \"to\", child_rank),\n    ChildKnownParentUnknownFeatures = sum(gap),\n    ChildKnownParentUnknownTaxa = length(unique(\n      taxonomy_clean[[child_rank]][gap]\n    )),\n    EqualSampleMean = sum(feature_equal_mean[gap]),\n    stringsAsFactors = FALSE\n  )\n}\nlineage_gap_audit <- do.call(rbind, lineage_gap_rows)\nlineage_gap_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Transition ChildKnownParentUnknownFeatures ChildKnownParentUnknownTaxa\n1 Phylum to Class                               0                           0\n2  Class to Order                               0                           0\n3 Order to Family                               0                           0\n4 Family to Genus                             324                          17\n  EqualSampleMean\n1      0.00000000\n2      0.00000000\n3      0.00000000\n4      0.02518277\n```\n\n\n:::\n:::\n\n\n再检查同一 rank 内，一个裸名称是否对应多个父系：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncollision_rows <- list()\nfor (i in 2:length(rank_names)) {\n  rank_name <- rank_names[[i]]\n  labels <- taxonomy_clean[[rank_name]]\n  known_labels <- setdiff(unique(labels), unknown_labels[[rank_name]])\n  for (taxon in known_labels) {\n    mask <- labels == taxon\n    parent_paths <- apply(\n      taxonomy_clean[\n        mask,\n        rank_names[seq_len(i - 1L)],\n        drop = FALSE\n      ],\n      1L,\n      paste,\n      collapse = \" > \"\n    )\n    parent_paths <- sort(unique(parent_paths))\n    if (length(parent_paths) > 1L) {\n      collision_rows[[length(collision_rows) + 1L]] <- data.frame(\n        Rank = rank_name,\n        Taxon = taxon,\n        ParentLineages = length(parent_paths),\n        ParentPaths = paste(parent_paths, collapse = \" | \"),\n        EqualSampleMean = sum(feature_equal_mean[mask]),\n        stringsAsFactors = FALSE\n      )\n    }\n  }\n}\nlabel_collision_audit <- do.call(rbind, collision_rows)\nlabel_collision_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Rank      Taxon ParentLineages\n1 Family    FamilyI              3\n2 Family Family XII              2\n                                                                                                                                 ParentPaths\n1 Cyanobacteria > Cyanobacteria > SubsectionI | Cyanobacteria > Cyanobacteria > SubsectionIII | Cyanobacteria > Cyanobacteria > SubsectionIV\n2                                                                Firmicutes > Bacilli > Bacillales | Firmicutes > Clostridia > Clostridiales\n  EqualSampleMean\n1     0.001376438\n2     0.004929644\n```\n\n\n:::\n:::\n\n\n`Family XII` 和 `FamilyI` 必须由 parent path 区分。若只按 family 显示名聚合，它们可以作为 rank composition 的一个标签；若要画 lineage 或追踪父子关系，则必须使用完整路径键。\n\n### 5. 固定每级 Top 5，并保留 Top-N coverage 敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_top_rows <- list()\nrank_group_rows <- list()\ntop_taxa_by_rank <- list()\nfor (rank_name in rank_names) {\n  rel_rank <- rank_relative[[rank_name]]\n  unknown_label <- unknown_labels[[rank_name]]\n  known_taxa <- setdiff(rownames(rel_rank), unknown_label)\n  known_means <- rowMeans(rel_rank[known_taxa, , drop = FALSE])\n  top5 <- names(sort(known_means, decreasing = TRUE))[1:5]\n  top_taxa_by_rank[[rank_name]] <- top5\n\n  rank_top_rows[[rank_name]] <- data.frame(\n    Rank = rank_name,\n    TopRank = seq_along(top5),\n    Taxon = top5,\n    RankQualifiedTaxon = paste0(rank_prefix[[rank_name]], \" · \", top5),\n    OverallMean = unname(known_means[top5]),\n    stringsAsFactors = FALSE\n  )\n\n  for (group_code in group_codes) {\n    ids <- metadata$SampleID[metadata$Group == group_code]\n    for (taxon in c(top5, unknown_label)) {\n      values <- rel_rank[taxon, ids]\n      rank_group_rows[[length(rank_group_rows) + 1L]] <- data.frame(\n        Rank = rank_name,\n        GroupCode = group_code,\n        Group = unname(group_display[group_code]),\n        Taxon = taxon,\n        RankQualifiedTaxon = paste0(rank_prefix[[rank_name]], \" · \", taxon),\n        MeanRelativeAbundance = mean(values),\n        MeanPercent = 100 * mean(values),\n        Prevalence = mean(values > 0),\n        stringsAsFactors = FALSE\n      )\n    }\n  }\n}\nrank_top_taxa <- do.call(rbind, rank_top_rows)\nrank_taxon_group_summary <- do.call(rbind, rank_group_rows)\nrank_top_taxa\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Rank TopRank                        Taxon\nPhylum.1 Phylum       1               Proteobacteria\nPhylum.2 Phylum       2                  Chloroflexi\nPhylum.3 Phylum       3                Bacteroidetes\nPhylum.4 Phylum       4                Acidobacteria\nPhylum.5 Phylum       5               Actinobacteria\nClass.1   Class       1                Acidobacteria\nClass.2   Class       2          Alphaproteobacteria\nClass.3   Class       3           Betaproteobacteria\nClass.4   Class       4                 Anaerolineae\nClass.5   Class       5          Gammaproteobacteria\nOrder.1   Order       1               Anaerolineales\nOrder.2   Order       2             Acidimicrobiales\nOrder.3   Order       3              Xanthomonadales\nOrder.4   Order       4           Sphingobacteriales\nOrder.5   Order       5                  Rhizobiales\nFamily.1 Family       1              Anaerolineaceae\nFamily.2 Family       2            Flavobacteriaceae\nFamily.3 Family       3               Comamonadaceae\nFamily.4 Family       4            Planctomycetaceae\nFamily.5 Family       5            Gemmatimonadaceae\nGenus.1   Genus       1                 Sphingomonas\nGenus.2   Genus       2 Clostridium sensu stricto 13\nGenus.3   Genus       3                 Thiobacillus\nGenus.4   Genus       4                     Bacillus\nGenus.5   Genus       5        Candidatus Solibacter\n                       RankQualifiedTaxon OverallMean\nPhylum.1               P · Proteobacteria 0.307133967\nPhylum.2                  P · Chloroflexi 0.138240898\nPhylum.3                P · Bacteroidetes 0.116492475\nPhylum.4                P · Acidobacteria 0.113375701\nPhylum.5               P · Actinobacteria 0.100095632\nClass.1                 C · Acidobacteria 0.089633197\nClass.2           C · Alphaproteobacteria 0.087102869\nClass.3            C · Betaproteobacteria 0.078018054\nClass.4                  C · Anaerolineae 0.069398355\nClass.5           C · Gammaproteobacteria 0.067400343\nOrder.1                O · Anaerolineales 0.069398355\nOrder.2              O · Acidimicrobiales 0.036600910\nOrder.3               O · Xanthomonadales 0.034599230\nOrder.4            O · Sphingobacteriales 0.032748272\nOrder.5                   O · Rhizobiales 0.030755374\nFamily.1              F · Anaerolineaceae 0.069398355\nFamily.2            F · Flavobacteriaceae 0.028304264\nFamily.3               F · Comamonadaceae 0.021210247\nFamily.4            F · Planctomycetaceae 0.020549638\nFamily.5            F · Gemmatimonadaceae 0.017383823\nGenus.1                  G · Sphingomonas 0.012858135\nGenus.2  G · Clostridium sensu stricto 13 0.012673358\nGenus.3                  G · Thiobacillus 0.010813747\nGenus.4                      G · Bacillus 0.010772492\nGenus.5         G · Candidatus Solibacter 0.009378094\n```\n\n\n:::\n:::\n\n\nTop-N sensitivity 将 `Top 5/10/20/50` 与该 rank 的全部已知标签放在同一分母下比较：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_n_rows <- list()\nfor (rank_name in rank_names) {\n  rel_rank <- rank_relative[[rank_name]]\n  unknown_label <- unknown_labels[[rank_name]]\n  known_taxa <- setdiff(rownames(rel_rank), unknown_label)\n  known_means <- rowMeans(rel_rank[known_taxa, , drop = FALSE])\n  known_order <- names(sort(known_means, decreasing = TRUE))\n  branches <- list(\n    `Top 5` = head(known_order, 5L),\n    `Top 10` = head(known_order, 10L),\n    `Top 20` = head(known_order, 20L),\n    `Top 50` = head(known_order, 50L),\n    `All known` = known_order\n  )\n  for (label in names(branches)) {\n    selected <- branches[[label]]\n    coverage <- colSums(rel_rank[selected, , drop = FALSE])\n    top_n_rows[[length(top_n_rows) + 1L]] <- data.frame(\n      Rank = rank_name,\n      NLabel = label,\n      SelectedN = length(selected),\n      MeanCoverage = mean(coverage),\n      MinimumCoverage = min(coverage),\n      MaximumCoverage = max(coverage),\n      UnknownMean = mean(rel_rank[unknown_label, ]),\n      stringsAsFactors = FALSE\n    )\n  }\n}\nrank_topn_sensitivity <- do.call(rbind, top_n_rows)\nsubset(rank_topn_sensitivity, NLabel == \"Top 10\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Rank NLabel SelectedN MeanCoverage MinimumCoverage MaximumCoverage\n2  Phylum Top 10        10   0.94803047      0.86515573       0.9891697\n7   Class Top 10        10   0.59004532      0.40544229       0.7098990\n12  Order Top 10        10   0.34765278      0.12144807       0.5932802\n17 Family Top 10        10   0.23671066      0.09883876       0.5526710\n22  Genus Top 10        10   0.09521805      0.02201933       0.3296409\n   UnknownMean\n2  0.003463782\n7  0.032021456\n12 0.144272720\n17 0.320372461\n22 0.631056113\n```\n\n\n:::\n:::\n\n\n### 6. 把 pooled reads 和 known-only 留在敏感性分支\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregation_rows <- list()\ndenominator_rows <- list()\nfor (rank_name in rank_names) {\n  rel_rank <- rank_relative[[rank_name]]\n  counts_rank <- rank_counts[[rank_name]]\n  unknown_label <- unknown_labels[[rank_name]]\n  top5 <- top_taxa_by_rank[[rank_name]]\n\n  for (group_code in group_codes) {\n    ids <- metadata$SampleID[metadata$Group == group_code]\n    equal_vector <- rowMeans(rel_rank[, ids, drop = FALSE])\n    pooled_vector <- rowSums(counts_rank[, ids, drop = FALSE]) /\n      sum(counts_rank[, ids, drop = FALSE])\n    aggregation_rows[[length(aggregation_rows) + 1L]] <- data.frame(\n      Rank = rank_name,\n      GroupCode = group_code,\n      Group = unname(group_display[group_code]),\n      TotalVariation = 0.5 * sum(abs(equal_vector - pooled_vector)),\n      MaximumTaxonDifferencePP = 100 * max(abs(\n        equal_vector - pooled_vector\n      )),\n      stringsAsFactors = FALSE\n    )\n\n    known_total <- 1 - rel_rank[unknown_label, ids]\n    for (taxon in top5) {\n      all_read_mean <- mean(rel_rank[taxon, ids])\n      known_only_mean <- mean(rel_rank[taxon, ids] / known_total)\n      denominator_rows[[length(denominator_rows) + 1L]] <- data.frame(\n        Rank = rank_name,\n        GroupCode = group_code,\n        Group = unname(group_display[group_code]),\n        Taxon = taxon,\n        AllReadMean = all_read_mean,\n        KnownOnlyMean = known_only_mean,\n        InflationPP = 100 * (known_only_mean - all_read_mean),\n        stringsAsFactors = FALSE\n      )\n    }\n  }\n}\naggregation_sensitivity <- do.call(rbind, aggregation_rows)\ndenominator_sensitivity <- do.call(rbind, denominator_rows)\n\ndenominator_sensitivity[\n  which.max(denominator_sensitivity$InflationPP),\n  ,\n  drop = FALSE\n]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Rank GroupCode          Group                 Taxon AllReadMean\n65 Genus        IW Inland wetland Candidatus Solibacter  0.02383324\n   KnownOnlyMean InflationPP\n65    0.09656292    7.272969\n```\n\n\n:::\n:::\n\n\n已知属在 inland wetland 的分母最小，`Candidatus Solibacter` 从 all-read 2.38% 变成 known-only 9.66%，增加 7.27 个百分点。这不是生物学变化，而是分母改变。\n\n### 7. 选择完整优势 lineage，而不是孤立 genus 名\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomplete_mask <- complete_depth == length(rank_names)\ncomplete_rel <- rowsum(\n  relative_feature[complete_mask, , drop = FALSE],\n  lineage_key[complete_mask],\n  reorder = TRUE\n)\ncomplete_means <- rowMeans(complete_rel)\ncomplete_order <- names(sort(complete_means, decreasing = TRUE))\ntop12_lineages <- head(complete_order, 12L)\n\nlineage_rows <- list()\nladder_rows <- list()\nfor (lineage_rank in seq_along(top12_lineages)) {\n  key <- top12_lineages[[lineage_rank]]\n  path_index <- match(key, lineage_key)\n  path <- unlist(\n    taxonomy_clean[path_index, rank_names, drop = FALSE],\n    use.names = TRUE\n  )\n  leaf_values <- complete_rel[key, ]\n\n  for (group_code in group_codes) {\n    ids <- metadata$SampleID[metadata$Group == group_code]\n    lineage_rows[[length(lineage_rows) + 1L]] <- data.frame(\n      LineageRank = lineage_rank,\n      LineageKey = key,\n      GroupCode = group_code,\n      Group = unname(group_display[group_code]),\n      MeanRelativeAbundance = mean(leaf_values[ids]),\n      Prevalence = mean(leaf_values[ids] > 0),\n      stringsAsFactors = FALSE\n    )\n  }\n\n  for (rank_i in seq_along(rank_names)) {\n    rank_name <- rank_names[[rank_i]]\n    prefix_match <- rep(TRUE, nrow(taxonomy_clean))\n    for (prefix_i in seq_len(rank_i)) {\n      prefix_rank <- rank_names[[prefix_i]]\n      prefix_match <- prefix_match &\n        taxonomy_clean[[prefix_rank]] == path[[prefix_rank]]\n    }\n    node_mean <- sum(feature_equal_mean[prefix_match])\n    ladder_rows[[length(ladder_rows) + 1L]] <- data.frame(\n      LineageRank = lineage_rank,\n      LineageKey = key,\n      LeafGenus = path[[\"Genus\"]],\n      Rank = rank_name,\n      Taxon = path[[rank_name]],\n      NodePercent = 100 * node_mean,\n      LeafPercent = 100 * mean(leaf_values),\n      stringsAsFactors = FALSE\n    )\n  }\n}\ndominant_complete_lineages <- do.call(rbind, lineage_rows)\nlineage_ladder <- do.call(rbind, ladder_rows)\n\ndata.frame(\n  CompleteLineages = nrow(complete_rel),\n  CompleteLineageCoverage = sum(complete_means),\n  Top12Coverage = sum(complete_means[top12_lineages])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  CompleteLineages CompleteLineageCoverage Top12Coverage\n1              754               0.3437611     0.1018763\n```\n\n\n:::\n:::\n\n\n### 8. 保存完整表与敏感性审计\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_dir <- \"results/27-multirank-composition\"\ndir.create(result_dir, recursive = TRUE, showWarnings = FALSE)\n\ntaxonomy_lineage_map <- data.frame(\n  FeatureID = rownames(taxonomy_clean),\n  taxonomy_clean,\n  LineageKey = lineage_key,\n  CompleteDepth = complete_depth,\n  EqualSampleMean = feature_equal_mean,\n  check.names = FALSE\n)\n\nreadr::write_tsv(\n  taxonomy_lineage_map,\n  file.path(result_dir, \"article-taxonomy-lineage-map.tsv\")\n)\nreadr::write_tsv(\n  rank_resolution,\n  file.path(result_dir, \"article-rank-resolution.tsv\")\n)\nreadr::write_tsv(\n  group_rank_resolution,\n  file.path(result_dir, \"article-group-rank-resolution.tsv\")\n)\nreadr::write_tsv(\n  lineage_gap_audit,\n  file.path(result_dir, \"article-lineage-gap-audit.tsv\")\n)\nreadr::write_tsv(\n  label_collision_audit,\n  file.path(result_dir, \"article-label-collision-audit.tsv\")\n)\nreadr::write_tsv(\n  rank_top_taxa,\n  file.path(result_dir, \"article-rank-top-taxa.tsv\")\n)\nreadr::write_tsv(\n  rank_taxon_group_summary,\n  file.path(result_dir, \"article-rank-taxon-group-summary.tsv\")\n)\nreadr::write_tsv(\n  rank_topn_sensitivity,\n  file.path(result_dir, \"article-rank-topn-sensitivity.tsv\")\n)\nreadr::write_tsv(\n  lineage_ladder,\n  file.path(result_dir, \"article-lineage-ladder.tsv\")\n)\nreadr::write_tsv(\n  aggregation_sensitivity,\n  file.path(result_dir, \"article-aggregation-sensitivity.tsv\")\n)\nreadr::write_tsv(\n  denominator_sensitivity,\n  file.path(result_dir, \"article-denominator-sensitivity.tsv\")\n)\n```\n:::\n\n\n## 出版级美化：四张图各回答一个层级问题 {#sec-publication}\n\n### 1. 注释分辨率阶梯：先看每一级还有多少 reads 可命名\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_colours <- c(\n  `All samples` = \"#1F2937\",\n  `Inland wetland` = \"#E69F00\",\n  `Coastal wetland` = \"#0072B2\",\n  `Tibetan wetland` = \"#009E73\"\n)\ncascade_data <- group_rank_resolution\ncascade_data$Rank <- factor(cascade_data$Rank, levels = rank_names)\ncascade_data$Group <- factor(\n  cascade_data$Group,\n  levels = c(\"All samples\", unname(group_display[group_codes]))\n)\n\ncascade_plot <- ggplot2::ggplot(\n  cascade_data,\n  ggplot2::aes(\n    x = Rank,\n    y = KnownMean,\n    colour = Group,\n    linetype = Group,\n    group = Group\n  )\n) +\n  ggplot2::geom_line(linewidth = 0.8) +\n  ggplot2::geom_point(size = 2.2) +\n  ggplot2::scale_colour_manual(values = group_colours, drop = FALSE) +\n  ggplot2::scale_linetype_manual(\n    values = c(\n      `All samples` = \"22\",\n      `Inland wetland` = \"solid\",\n      `Coastal wetland` = \"solid\",\n      `Tibetan wetland` = \"solid\"\n    ),\n    drop = FALSE\n  ) +\n  ggplot2::scale_y_continuous(\n    limits = c(0, 1.02),\n    breaks = seq(0, 1, by = 0.2),\n    labels = scales::label_percent(accuracy = 1),\n    expand = ggplot2::expansion(mult = c(0, 0.01))\n  ) +\n  ggplot2::labs(\n    title = \"Taxonomic resolution falls as the requested rank becomes finer\",\n    subtitle = \"Known fraction uses all reads and equal sample weight within each wetland group\",\n    x = NULL,\n    y = \"Reads assigned at rank\",\n    colour = NULL,\n    linetype = NULL,\n    caption = paste(\n      \"Genus-level resolution: inland 29.0%, coastal 38.4%, Tibetan 43.3%;\\n\",\n      \"differences in annotation completeness remain visible.\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  ggplot2::theme(\n    legend.position = \"top\",\n    panel.grid.major.x = ggplot2::element_blank()\n  )\n\nsave_pub(\n  cascade_plot,\n  \"figures/27-rank-resolution-cascade\",\n  width = 150,\n  height = 96\n)\ncascade_plot\n```\n\n::: {.cell-output-display}\n![Phylum→Genus 注释分辨率阶梯。](27-multirank-composition_files/figure-html/fig-rank-resolution-cascade-1.png){#fig-rank-resolution-cascade}\n:::\n:::\n\n\n这张图先回答“这个 rank 在每组还能解析多少 reads”。它不是测序质量评分，更不是组间显著性检验；但如果各组注释率差异明显，后续 known-only 图必须格外谨慎。\n\n### 2. 多层级气泡图：Top 5 名单跨组固定\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbubble_data <- rank_taxon_group_summary\nbubble_data$Rank <- factor(bubble_data$Rank, levels = rank_names)\nbubble_data$Group <- factor(\n  bubble_data$Group,\n  levels = unname(group_display[group_codes])\n)\nbubble_levels <- unlist(lapply(rank_names, function(rank_name) {\n  c(\n    paste0(rank_prefix[[rank_name]], \" · \", top_taxa_by_rank[[rank_name]]),\n    paste0(rank_prefix[[rank_name]], \" · \", unknown_labels[[rank_name]])\n  )\n}), use.names = FALSE)\nbubble_data$RankQualifiedTaxon <- factor(\n  bubble_data$RankQualifiedTaxon,\n  levels = rev(bubble_levels)\n)\n\nbubble_plot <- ggplot2::ggplot(\n  bubble_data,\n  ggplot2::aes(\n    x = Group,\n    y = RankQualifiedTaxon,\n    size = MeanPercent,\n    colour = Prevalence\n  )\n) +\n  ggplot2::geom_point(alpha = 0.9) +\n  ggplot2::facet_wrap(~Rank, ncol = 2, scales = \"free_y\") +\n  ggplot2::scale_size_area(max_size = 11, breaks = c(1, 5, 20, 60)) +\n  ggplot2::scale_colour_gradientn(\n    colours = c(\"#D9EAF7\", \"#56B4E9\", \"#0072B2\", \"#003B5C\"),\n    limits = c(0, 1),\n    labels = scales::label_percent(accuracy = 1)\n  ) +\n  ggplot2::scale_x_discrete(\n    labels = c(\n      `Inland wetland` = \"IW\",\n      `Coastal wetland` = \"CW\",\n      `Tibetan wetland` = \"TW\"\n    )\n  ) +\n  ggplot2::labs(\n    title = \"The same Top-5 rule yields different views at each rank\",\n    subtitle = \"Global Top 5 named taxa plus rank-specific Unknown; one fixed list is reused across groups\",\n    x = \"Wetland group (IW / CW / TW)\",\n    y = NULL,\n    size = \"Mean abundance (%)\",\n    colour = \"Prevalence\",\n    caption = paste(\n      \"IW, inland; CW, coastal; TW, Tibetan wetland. P/C/O/F/G prefixes prevent\",\n      \"equal-looking names at different ranks from being merged.\"\n    )\n  ) +\n  theme_pub(base_size = 7.7) +\n  ggplot2::theme(\n    legend.position = \"bottom\",\n    axis.text.x = ggplot2::element_text(angle = 0, hjust = 0.5),\n    panel.grid.major.y = ggplot2::element_line(\n      colour = \"#ECECEC\", linewidth = 0.25\n    ),\n    panel.spacing.x = grid::unit(1.2, \"mm\"),\n    strip.text = ggplot2::element_text(size = 8)\n  )\n\nsave_pub(\n  bubble_plot,\n  \"figures/27-multirank-bubble\",\n  width = 183,\n  height = 198\n)\nbubble_plot\n```\n\n::: {.cell-output-display}\n![五个分类级的全局 Top 5 与 Unknown。](27-multirank-composition_files/figure-html/fig-multirank-bubble-1.png){#fig-multirank-bubble}\n:::\n:::\n\n\n点面积表示以全部 reads 为分母的组均值，颜色表示该聚合 taxon 在组内样本中的非零比例。二者回答不同问题：高 prevalence 不保证高平均丰度，高平均丰度也可能由少数样本驱动。\n\n### 3. Lineage ladder：每一行是一条可追踪路径\n\n\n::: {.cell}\n\n```{.r .cell-code}\nladder_data <- lineage_ladder\nladder_data$Rank <- factor(ladder_data$Rank, levels = rank_names)\nleaf_order <- unique(ladder_data$LeafGenus[order(ladder_data$LineageRank)])\nladder_data$LeafGenus <- factor(\n  ladder_data$LeafGenus,\n  levels = rev(leaf_order)\n)\nladder_data$CellLabel <- wrap_label(ladder_data$Taxon, width = 15L)\nladder_dark <- ladder_data$NodePercent >= 9\n\nladder_plot <- ggplot2::ggplot(\n  ladder_data,\n  ggplot2::aes(x = Rank, y = LeafGenus, fill = NodePercent)\n) +\n  ggplot2::geom_tile(colour = \"white\", linewidth = 0.45) +\n  ggplot2::geom_text(\n    data = ladder_data[!ladder_dark, , drop = FALSE],\n    ggplot2::aes(label = CellLabel),\n    colour = \"#17202A\",\n    family = font_pub,\n    size = 2.05,\n    lineheight = 0.88\n  ) +\n  ggplot2::geom_text(\n    data = ladder_data[ladder_dark, , drop = FALSE],\n    ggplot2::aes(label = CellLabel),\n    colour = \"white\",\n    family = font_pub,\n    size = 2.05,\n    lineheight = 0.88\n  ) +\n  ggplot2::scale_fill_gradientn(\n    colours = c(\"#F7FBFF\", \"#C6DBEF\", \"#6BAED6\", \"#2171B5\", \"#08306B\"),\n    trans = \"sqrt\",\n    labels = scales::label_number(accuracy = 0.1, suffix = \"%\")\n  ) +\n  ggplot2::scale_y_discrete(\n    labels = function(x) wrap_label(x, width = 21L)\n  ) +\n  ggplot2::labs(\n    title = \"A genus is a complete path, not an isolated display name\",\n    subtitle = \"Top 12 complete genus lineages cover 10.19% of all reads; tile colour is prefix-node abundance\",\n    x = NULL,\n    y = \"Leaf genus\",\n    fill = \"Node abundance\",\n    caption = paste(\n      \"Each row traces one Phylum-to-Genus path. Prefix-node percentages repeat\",\n      \"context and must not be added across columns.\"\n    )\n  ) +\n  theme_pub(base_size = 8) +\n  ggplot2::theme(\n    panel.grid = ggplot2::element_blank(),\n    legend.position = \"right\",\n    axis.text.x = ggplot2::element_text(face = \"bold\"),\n    axis.ticks = ggplot2::element_blank()\n  )\n\nsave_pub(\n  ladder_plot,\n  \"figures/27-lineage-ladder\",\n  width = 183,\n  height = 168\n)\nladder_plot\n```\n\n::: {.cell-output-display}\n![丰度最高的 12 条完整 Phylum→Genus lineage。](27-multirank-composition_files/figure-html/fig-lineage-ladder-1.png){#fig-lineage-ladder}\n:::\n:::\n\n\n每个格子的颜色是“共享该路径前缀的所有 features”的总体丰度，因此越靠左的父节点通常更深。颜色用于提供上级背景，不能沿同一行相加。`Marinicella` 路径中的 `Order Incertae Sedis` 和 `Family Incertae Sedis` 被保留，清楚标示它的未定位置边界。\n\n### 4. Top-N coverage：把排版损失画出来\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_colours <- c(\n  Phylum = \"#0072B2\",\n  Class = \"#E69F00\",\n  Order = \"#009E73\",\n  Family = \"#CC79A7\",\n  Genus = \"#D55E00\"\n)\ntopn_plot_data <- rank_topn_sensitivity\ntopn_plot_data$Rank <- factor(topn_plot_data$Rank, levels = rank_names)\ntopn_plot_data$NLabel <- factor(\n  topn_plot_data$NLabel,\n  levels = c(\"Top 5\", \"Top 10\", \"Top 20\", \"Top 50\", \"All known\")\n)\ntop10_labels <- topn_plot_data[\n  topn_plot_data$NLabel == \"Top 10\",\n  ,\n  drop = FALSE\n]\ntop10_labels$Label <- scales::percent(\n  top10_labels$MeanCoverage,\n  accuracy = 0.1\n)\n\ntopn_plot <- ggplot2::ggplot(\n  topn_plot_data,\n  ggplot2::aes(x = NLabel, y = MeanCoverage, colour = Rank, group = Rank)\n) +\n  ggplot2::geom_line(linewidth = 0.8) +\n  ggplot2::geom_point(size = 2.1) +\n  ggplot2::geom_text(\n    data = top10_labels,\n    ggplot2::aes(label = Label),\n    nudge_x = 0.14,\n    hjust = 0,\n    size = 2.4,\n    show.legend = FALSE,\n    family = font_pub\n  ) +\n  ggplot2::scale_colour_manual(values = rank_colours, drop = FALSE) +\n  ggplot2::scale_y_continuous(\n    limits = c(0, 1.03),\n    breaks = seq(0, 1, by = 0.2),\n    labels = scales::label_percent(accuracy = 1),\n    expand = ggplot2::expansion(mult = c(0, 0.01))\n  ) +\n  ggplot2::labs(\n    title = \"Top 10 does not mean the same coverage at every rank\",\n    subtitle = \"Coverage is measured against all reads after per-sample closure\",\n    x = \"Display branch\",\n    y = \"Mean covered abundance\",\n    colour = \"Rank\",\n    caption = paste(\n      \"Top-10 coverage falls from 94.8% at phylum to 9.5% at genus;\\n\",\n      \"All known retains the rank-specific unclassified fraction.\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  ggplot2::theme(\n    legend.position = \"top\",\n    panel.grid.major.x = ggplot2::element_blank()\n  )\n\nsave_pub(\n  topn_plot,\n  \"figures/27-topn-coverage\",\n  width = 160,\n  height = 102\n)\ntopn_plot\n```\n\n::: {.cell-output-display}\n![不同 rank 的 Top-N 覆盖率。](27-multirank-composition_files/figure-html/fig-topn-coverage-1.png){#fig-topn-coverage}\n:::\n:::\n\n\n这张图把 Top-N 的视觉损失量化。属水平即使显示 Top 50 已知 genus，也只覆盖 21.56% 的全部 reads；完整已知 genus 合计也只有 36.89%。因此属图必须同时报告 Unknown，并把完整结果表留给复查。\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     Validation Passed Total\n1 Repository QA    209   209\n```\n\n\n:::\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"坑 1：按裸 taxon 名合并五级结果\"}\n`Acidobacteria` 在 Phylum 和 Class 中都出现。先增加 `Rank` 与 `RankQualifiedTaxon`，再做 join、排序或配色；lineage 图还要增加完整 parent path。\n:::\n\n::: {.callout-caution title=\"坑 2：用已知子级反推空父级\"}\nFamily 为空、Genus 已知并不授权你补写 family。保留 `Unknown family > named genus` 路径，并在需要完整连线的图中把它排除或单列。\n:::\n\n::: {.callout-caution title=\"坑 3：把五个 rank 的百分比相加\"}\n每个 rank 都重复描述同一批 reads，并各自闭合到 100%。跨 rank 相加是重复计数；lineage ladder 中的父子节点颜色也不能相加。\n:::\n\n::: {.callout-caution title=\"坑 4：每组单独选择 Top-N\"}\n若 inland、coastal、Tibetan 分别挑自己的 Top 5，相同位置就代表不同 taxon。先用全体样本的等权均值选定一份全局名单，再复用于所有组。\n:::\n\n::: {.callout-caution title=\"坑 5：删除 Unknown 后仍写 all-read abundance\"}\nknown-only 是条件比例。本数据最大放大为 7.27 个百分点，且三组放大量不同。若必须展示，标题、轴和 Methods 都要明确写 `among classified reads`。\n:::\n\n::: {.callout-caution title=\"坑 6：把层级图当成差异丰度检验\"}\n注释率曲线、气泡大小、lineage ladder 和 Top-N coverage 都是描述性证据。显著性、协变量和重复测量应由预先选择的差异丰度模型处理。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> Taxonomic composition was calculated independently at the phylum, class, order, family, and genus ranks from the unrarefied feature-count table. Counts were converted to within-sample relative abundances before group summaries, and biological samples received equal weight. Empty assignments were retained as rank-specific Unknown categories, whereas named Incertae Sedis assignments were preserved as unresolved database labels. Taxa were identified by rank-qualified labels, and hierarchical displays used complete lineage keys without imputing missing parent ranks. The five most abundant named taxa at each rank were selected globally across all 90 samples and reused across groups; Top-5, Top-10, Top-20, Top-50, pooled-read, and classified-read-only results were retained as sensitivity analyses. All displayed proportions used total reads as the primary denominator, and the figures were interpreted descriptively rather than as differential-abundance tests.\n\n替换样本数、Top-N、分组变量和实际 sensitivity 分支即可；若使用 known-only 图，必须把 `total reads` 改成 `classified reads`，不能让代码与 Methods 使用不同分母。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. 只替换三件套路径和分组列\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"your_data/otutab.tsv\",\n  taxonomy = \"your_data/taxonomy.tsv\",\n  metadata = \"your_data/metadata.tsv\"\n)\ngroup_column <- \"Treatment\"\n```\n:::\n\n\n`otutab` 必须是 feature × sample；`taxonomy` 行名必须与 feature 完全一致；`metadata` 行名必须覆盖全部样本。先核对集合，再按 count table 顺序重排 taxonomy 与 metadata。\n\n### 2. 先写下五级合同\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrank_names <- c(\"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\")\ntop_n <- 5L\nprimary_denominator <- \"all reads\"\nprimary_group_weight <- \"equal biological samples\"\nmissing_parent_rule <- \"retain; never backfill from child\"\n```\n:::\n\n\n论文图如果只需要 Phylum、Family、Genus，也应在运行前固定这三个 rank，而不是看完结果后挑最漂亮的层级。\n\n### 3. taxonomy 只有一列字符串时，先拆成七列\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxonomy_raw <- readr::read_tsv(\n  \"your_data/taxonomy-single-column.tsv\",\n  show_col_types = FALSE\n)\nrank_names_7 <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"\n)\nparts <- strsplit(taxonomy_raw$Taxon, \";\", fixed = TRUE)\ntaxonomy_matrix <- t(vapply(parts, function(x) {\n  x <- trimws(x)\n  length(x) <- length(rank_names_7)\n  x\n}, character(length(rank_names_7))))\ntaxonomy <- as.data.frame(taxonomy_matrix, stringsAsFactors = FALSE)\nnames(taxonomy) <- rank_names_7\nrownames(taxonomy) <- taxonomy_raw$FeatureID\n```\n:::\n\n\n不要把缺失的 Species 自动复制成 Genus，也不要用 genus 名补写 family。缺失值应由 `clean_taxon()` 转成 rank-specific Unknown。\n\n### 4. 有技术重复时先恢复生物学样本单位\n\n如果多个测序库来自同一生物学样本，应先按预声明规则合并原始 counts，再做逐样本 closure。不能把技术库当作独立样本等权平均，否则一个受试者会获得更多权重。\n\n### 5. 最少保留这些审计输出\n\n- 清洗后的 feature × 五级 taxonomy lineage map；\n- 每个 rank 的完整 sample-level relative-abundance 表；\n- rank resolution 与组内 Unknown 比例；\n- parent–child gap 和同名冲突表；\n- 全部完整 lineage abundance 表，而不只保存 Top 12；\n- Top-N、pooled-read 与 known-only 敏感性表；\n- 图形尺寸、字体、格式和 600 ppi 导出审计。\n\n## 参考 {#sec-references}\n\n1. An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035).\n2. Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255).\n3. Foster ZSL, Sharpton TJ, Grünwald NJ. Metacoder: An R package for visualization and manipulation of community taxonomic diversity data. *PLOS Computational Biology*. 2017;13(2):e1005404. [doi:10.1371/journal.pcbi.1005404](https://doi.org/10.1371/journal.pcbi.1005404).\n4. Gloor GB, Macklaim JM, Pawlowsky-Glahn V, Egozcue JJ. Microbiome datasets are compositional: and this is not optional. *Frontiers in Microbiology*. 2017;8:2224. [doi:10.3389/fmicb.2017.02224](https://doi.org/10.3389/fmicb.2017.02224).\n5. Wickham H, et al. [ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics](https://ggplot2.tidyverse.org/).\n",
    "supporting": [
      "27-multirank-composition_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}