{
  "hash": "79b664255a41cc076da2b4b39cd55af0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"导出到 R：构建 phyloseq 对象、数据结构详解\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**把 QIIME 2 导出的真实 ASV 计数、七级 taxonomy、sample metadata、代表序列和 rooted tree 组装成一个五组件 `phyloseq` 对象；在构建前核对方向与 ID，在保存后核对 RDS 往返一致性。  \n> **输入文件：**`data/small/phyloseq-import/otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`、`representative-sequences.fasta.gz` 和 `rooted-insertion-tree.nwk.gz`。  \n> **预计资源：**读取 203,818-tip 完整树并裁剪、构建对象和回验通常需要 20–90 秒；建议预留 1–2 GB 内存。  \n> **执行策略：**正文从可校验的输入文件重新构建对象，`execute: eval: true`；发布前另用独立校验脚本完成 82 项检查，并输出 PDF、PNG、350 dpi LZW TIFF、审计表和运行日志。\n\n## 把 QIIME 2 结果正确装进 phyloseq {#sec-target}\n\n`phyloseq` 对象通常不直接成为论文结果图，却是群落组成、alpha diversity、beta diversity、差异丰度和系统发育分析共同的数据入口。McMurdie 与 Holmes 在 `phyloseq` 方法论文中用对象与分析组件的关系说明这种设计。面对真实输入时，先检查以下四件事：\n\n1. 五类输入如何通过方向与 ID gate 进入一个对象；\n2. feature ID 和 sample ID 是否完整对齐；\n3. 每个技术库的 reads 与 observed ASVs 是否在转换后保留；\n4. taxonomy 覆盖率应同时按 ASV 数和 reads 加权报告。\n\n![五组件 phyloseq 对象合同。完整 SEPP tree 先与 366 个 ASV 对齐并显式裁剪，再与计数、taxonomy、metadata 和代表序列共同组装。](../figures/17-phyloseq-object-contract.png){#fig-phyloseq-contract}\n\n![构建前的 ID 对账。taxonomy、代表序列、树尖端、metadata 和对象中的 ID 均达到 100% 匹配；完整树中的 203,452 个 reference-only tips 是预期范围，不是样本 feature。](../figures/17-id-reconciliation-audit.png){#fig-id-reconciliation}\n\n![对象保留了四个技术库的 read depth 与 observed ASVs。Filename set 只是文件来源标签，不能解释成处理组。](../figures/17-library-feature-audit.png){#fig-library-audit}\n\n![逐分类层级覆盖。Genus 覆盖 318/366 个 ASV、4,217/5,213 条 reads；Species 没有可报告注释。](../figures/17-taxonomy-coverage-audit.png){#fig-taxonomy-coverage}\n\n::: {.callout-important title=\"先记住一句话\"}\n**成功执行 `phyloseq()` 只证明构造器返回了对象，不证明输入方向、ID 交集、计数总量和树尖端都正确。先验收每个组件，再构建对象；构建后再从对象反向核对。**\n:::\n\n本次冻结输入和对象结果如下：\n\n```text\nSource\n  nf-core/test-datasets commit:       f282ad2bafb3ca90190ec87290066ee1985df655\n  Denoising:                          QIIME 2 / q2-dada2 2026.4.0\n  Taxonomy:                           SILVA 138.2 V4 classifier, confidence 0.70\n  Tree:                               rooted SEPP insertion tree\n\nInput contract\n  Count table:                        366 features x 4 libraries\n  Taxonomy:                           366 features x 7 ranks\n  Metadata:                           4 libraries x 5 variables\n  Representative sequences:          366\n  Total reads:                        5,213\n  Complete tree:                      203,818 tips\n  Query / reference-only tips:        366 / 203,452\n\nphyloseq object\n  Components:                         5\n  Component names:                    otu_table, tax_table, sam_data,\n                                      phy_tree, refseq\n  Orientation:                        taxa_are_rows = TRUE\n  Object tree:                        366 rooted ASV tips\n  Features / samples / reads:         366 / 4 / 5,213\n  Genus assignment:                   318 / 4,217 features / reads\n  Species assignment:                 0 / 0 features / reads\n  RDS round trip:                     PASS\n  Required checks:                    82 / 82 PASS\n```\n\n四个 library labels 来自 nf-core 测试文件名。`S103`、`S115`、`base` 和 `suffix_a` 描述文件集合，不是处理、病例状态或生物学重复，因此这里只验证数据结构，不做组间推断。\n\n## phyloseq 如何保持特征、分类和样本一致 {#sec-theory}\n\n### 1. 导出是数据合同转换，不是一次复制粘贴\n\nQIIME 2 Artifact（`.qza`）把数据、semantic type、格式和 provenance 打包在一起；R 中的矩阵、data frame、`phylo` 和 `DNAStringSet` 则是分析对象。`qiime tools export` 会把 Artifact 的数据部分写成标准文件，但导出文件不再携带完整 Artifact provenance。\n\n因此应同时保存两类证据：\n\n| 资产 | 负责回答的问题 |\n|---|---|\n| 原始 `.qza` + `qiime tools peek` / provenance | 数据从哪里来、用什么参数产生 |\n| 导出的 TSV / FASTA / Newick + SHA-256 | R 实际读取了哪一份字节 |\n| R 对象审计 | 转换是否保留 feature、sample、reads 和树尖端 |\n| `sessionInfo()` / lockfile | R 与包版本是什么 |\n\n一个可靠的 R 入口不能只写“从 QIIME 2 导入”，还要明确导出的是哪种 semantic type、怎样转换方向，以及如何证明 ID 没有被截断或自动丢弃。\n\n### 2. 三件套决定主体，序列和树扩展能力\n\n最小的群落对象由三件套组成：\n\n```text\notutab:    features x samples\ntaxonomy:  features x taxonomic ranks\nmetadata:  samples x variables\n```\n\n它们分别进入：\n\n```text\notu_table   <- counts\ntax_table   <- taxonomy\nsample_data <- metadata\n```\n\n若再加入代表序列与系统发育树，对象可扩展为五组件：\n\n```text\nrefseq   <- ASV sequences\nphy_tree <- rooted ASV tree\n```\n\n三组件对象足以进行许多非系统发育分析；Faith's PD、weighted UniFrac 和 unweighted UniFrac 等指标还需要 ID 对齐、含枝长的 rooted tree。保留 `refseq` 也便于追踪具体 ASV、重新注释和导出序列。\n\n### 3. 对象必须是多个 ID 集合的受审计交集\n\n设计数表 feature 集合为 (F_c)，taxonomy 为 (F_t)，代表序列为 (F_s)，树尖端为 (F_p)。进入五组件对象的 ASV 集合应为：\n\n\\[\nF = F_c \\cap F_t \\cap F_s \\cap F_p\n\\]\n\nsample 集合则是计数表列名与 metadata 行名的交集：\n\n\\[\nS = S_c \\cap S_m\n\\]\n\n真正重要的不是交集能算出来，而是集合差是否符合预期。若 taxonomy 少 20 个 ASV，构造器可能只保留共同部分；对象仍能生成，但 feature 数和 reads 已改变。正式分析应在构造器之前显式计算：\n\n```r\nsetdiff(count_feature_ids, taxonomy_feature_ids)\nsetdiff(count_sample_ids, metadata_sample_ids)\n```\n\n只有预先定义为允许的差异才能保留。例如完整 SEPP insertion tree 中有 203,452 个 reference-only tips，这些参考尖端不是 feature table 中的 ASV，可以在审计后裁剪；taxonomy 缺失一个 count feature 则不是同一类情况。\n\n### 4. `taxa_are_rows` 是方向合同，不是装饰参数\n\n本页计数矩阵是 `features × samples`，因此必须写：\n\n```r\nphyloseq::otu_table(otu_matrix, taxa_are_rows = TRUE)\n```\n\n若输入是 `samples × features`，应先根据 feature ID 与 taxonomy ID 的匹配关系判断方向，再转置矩阵。不要因为“行数比列数多”就猜测方向；小型研究、聚合表或过滤后的数据完全可能打破这种经验。\n\n方向错误有时仍会生成对象，随后产生荒谬的 `ntaxa()`、`nsamples()` 或 library size。至少要反查：\n\n```text\nnumber of taxa\nnumber of samples\nsample-wise read totals\ntaxa_are_rows flag\n```\n\n### 5. 完整 reference-placement tree 要先解释、再裁剪\n\n本例的完整 SEPP tree 有 203,818 个 tips：366 个 query ASV 加 203,452 个 reference tips。完整树保留 reference placement 的坐标和来源证据，但 feature table 只有 366 个 ASV。\n\n对象构建前显式执行：\n\n```r\nquery_tree <- ape::keep.tip(full_tree, feature_ids)\n```\n\n并核对裁剪后仍然：\n\n- 有 366 个且仅有 366 个目标 tips；\n- rooted；\n- branch lengths 无缺失、无负值；\n- tip labels 与 `otutab` feature IDs 完全集合相等。\n\n显式裁剪比依赖构造器内部求交集更容易审计，也避免把 20 万个 reference-only tips 长期塞进每个下游对象。完整 tree 文件仍应作为来源资产归档。\n\n### 6. 导入时保留原始整数计数\n\n相对丰度、稀释、CLR 和其他变换服务于不同问题，不应覆盖唯一的原始计数入口。对象中的 `otu_table` 先保留非负整数 counts：\n\n```text\nraw count object\n  ├─ composition display      -> relative abundance copy\n  ├─ count model              -> raw-count copy + model offsets\n  ├─ phylogenetic diversity   -> filtered/rarefied copy\n  └─ Aitchison analysis       -> zero-aware log-ratio copy\n```\n\n这样每条分析分支都能追溯到同一个 count ledger。若直接把相对丰度写回主体对象，后续 DESeq2、library size 审计和 reads 加权 taxonomy coverage 都会失去原始含义。\n\n### 7. taxonomy 的空值是测量边界\n\ntaxonomy table 有七列不等于每条 ASV 都有七级注释。本例中：\n\n| Rank | Assigned ASVs | Assigned reads | Read-weighted coverage |\n|---|---:|---:|---:|\n| Domain | 366 | 5,213 | 100.0% |\n| Phylum | 354 | 5,153 | 98.8% |\n| Family | 333 | 5,011 | 96.1% |\n| Genus | 318 | 4,217 | 80.9% |\n| Species | 0 | 0 | 0.0% |\n\n空字符串、`NA`、`Unassigned` 和前缀后没有名称的值，都不能当作已注释。Species 覆盖为 0 时，不能把 Genus 名称复制到 Species 列，也不能以 ASV 序列唯一为由声称物种水平分辨率。\n\n### 8. RDS 是经过验证的派生物，不是不可追溯的起点\n\n`saveRDS()` 适合保存完整 S4 对象，避免每次交互都重新读取并对齐五类文件。但 RDS 应在三件套、序列、树和环境通过检查后生成，并与以下信息一起归档：\n\n- 输入路径与 SHA-256；\n- R、Bioconductor 与 `phyloseq` 版本；\n- feature/sample/read counts；\n- 组件名称与方向；\n- 构建脚本和验证日志。\n\n只收到一个来历不明的 `ps.rds` 时，很难证明计数是否已变换、taxonomy 用了哪个数据库、树是否裁剪正确或 metadata 是否被重排。\n\n<details>\n<summary><strong>深入：为什么对象构建前后要检查两次</strong></summary>\n\n构建前检查的是输入合同：\n\n```text\nIDs unique\nsets reconcile\ncounts integer and non-negative\norientation explicit\ntree rooted and branch lengths valid\n```\n\n构建后检查的是转换结果：\n\n```text\nclass and component names\nntaxa / nsamples / total reads\nsample_sums\ntree tips and refseq names\nRDS reload parity\n```\n\n两类检查捕捉的问题不同。前者能指出哪个源文件错了；后者能发现构造器求交集、排序或序列化带来的变化。只做后者时，常只能看到“少了多少”，却不知道丢失发生在哪个组件。\n\n</details>\n\n## 准备工作 {#sec-preparation}\n\n<details open>\n<summary><strong>展开：安装依赖、固定版本并定义作图函数</strong></summary>\n\n本页实测环境为 R 4.4.1、Bioconductor 3.19、`phyloseq` 1.48.0、`ape` 5.8、`Biostrings` 2.72.1、`readr` 2.1.5 和 `ggplot2` 3.5.2。首次安装可执行：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"ape\", \"digest\", \"dplyr\", \"ggplot2\", \"jsonlite\", \"readr\",\n  \"scales\", \"tibble\", \"tidyr\"\n))\n\nif (!requireNamespace(\"BiocManager\", quietly = TRUE)) {\n  install.packages(\"BiocManager\")\n}\nBiocManager::install(\n  c(\"phyloseq\", \"Biostrings\"),\n  version = \"3.19\",\n  ask = FALSE,\n  update = FALSE\n)\n```\n:::\n\n\n新环境若采用更新的 R/Bioconductor 组合，应把实际版本写入锁文件并重跑全部检查，不要强行把不兼容的 Bioconductor release 安装到当前 R。\n\n下面的作图函数直接内联，可用于本页和自己的重绘：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260721)\n\nrequired_packages <- c(\n  \"ape\", \"Biostrings\", \"digest\", \"dplyr\", \"ggplot2\",\n  \"phyloseq\", \"readr\", \"scales\", \"tibble\", \"tidyr\"\n)\nmissing_packages <- required_packages[\n  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)\n]\nstopifnot(length(missing_packages) == 0L)\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 11) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.title = ggplot2::element_text(color = \"black\"),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(face = \"bold\"),\n      plot.subtitle = ggplot2::element_text(color = \"#4D4D4D\"),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", color = \"#B3B3B3\"\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(plot, stem, width = 125, height = 95, dpi = 350) {\n  dir.create(dirname(stem), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(stem, \".pdf\"), plot,\n    width = width, height = height, units = \"mm\",\n    device = grDevices::cairo_pdf, bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(stem, \".png\"), plot,\n    width = width, height = height, units = \"mm\",\n    dpi = dpi, bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(stem, \".tiff\"), plot,\n    width = width, height = height, units = \"mm\",\n    dpi = dpi, compression = \"lzw\", bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 从 QIIME 2 导出标准文件\n\n若手中仍是 Artifact，可在 QIIME 2 环境中导出。输出目录应分别创建，避免同名文件互相覆盖：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nmkdir -p export/table export/taxonomy export/sequences export/tree\n\nqiime tools export \\\n  --input-path table.qza \\\n  --output-path export/table\n\nbiom convert \\\n  --input-fp export/table/feature-table.biom \\\n  --output-fp export/table/feature-table.tsv \\\n  --to-tsv\n\nqiime tools export \\\n  --input-path taxonomy.qza \\\n  --output-path export/taxonomy\n\nqiime tools export \\\n  --input-path representative-sequences.qza \\\n  --output-path export/sequences\n\nqiime tools export \\\n  --input-path rooted-tree.qza \\\n  --output-path export/tree\n```\n:::\n\n\nBIOM 转出的第一行可能是注释，feature ID 列名也可能是 `#OTU ID`。应把它规范成首列 `FeatureID`、行是 features、后续列是 samples 的 `otutab.tsv`。QIIME 2 taxonomy 常是 `Feature ID / Taxon / Confidence` 三列；下文“换成你自己的数据”给出把 `Taxon` 拆成七列的完整代码。\n\n本页使用已经规范化并固定哈希的真实文件，来源记录见 `source-summary.json`。它们不是从某个先前保存的 R 对象读取。\n\n### 2. 校验输入文件字节\n\n先固定路径与 SHA-256。只要文件内容改变，代码立即停止：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_dir <- \"data/small/phyloseq-import\"\n\ninput_paths <- c(\n  otutab = file.path(input_dir, \"otutab.tsv\"),\n  taxonomy = file.path(input_dir, \"taxonomy.tsv\"),\n  metadata = file.path(input_dir, \"metadata.tsv\"),\n  representative_sequences = file.path(\n    input_dir, \"representative-sequences.fasta.gz\"\n  ),\n  rooted_insertion_tree = file.path(\n    input_dir, \"rooted-insertion-tree.nwk.gz\"\n  )\n)\n\nexpected_sha256 <- c(\n  otutab = \"6c43bb8f929f935b60e42ed32737632d3be18ddd491f5298ba3a6abd6e3f18a9\",\n  taxonomy = \"8ef235ea19923307eef4d8e1905c2f34b78cf25cf1a83f08aa00353f2c5c0d38\",\n  metadata = \"6628dd51051c53884e82c540ceaff8cc34f69900a78d372239a2ed41ff5b7263\",\n  representative_sequences = \"a19e083cfb0ab757d557569bdf76aa3de78576ae35033a7e69a647976a370bc2\",\n  rooted_insertion_tree = \"7e541e2ed9e3f81d9b6c6bf98999335e7f684a37ac5dd5f2b56e61b2f4c4c47c\"\n)\n\nobserved_sha256 <- vapply(\n  input_paths,\n  digest::digest,\n  character(1),\n  algo = \"sha256\",\n  serialize = FALSE,\n  file = TRUE\n)\n\nhash_audit <- tibble::tibble(\n  asset = names(input_paths),\n  observed_sha256 = unname(observed_sha256),\n  expected_sha256 = unname(expected_sha256),\n  status = ifelse(observed_sha256 == expected_sha256, \"PASS\", \"FAIL\")\n)\nstopifnot(all(hash_audit$status == \"PASS\"))\nhash_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  asset                    observed_sha256                expected_sha256 status\n  <chr>                    <chr>                          <chr>           <chr> \n1 otutab                   6c43bb8f929f935b60e42ed327376… 6c43bb8f929f93… PASS  \n2 taxonomy                 8ef235ea19923307eef4d8e1905c2… 8ef235ea199233… PASS  \n3 metadata                 6628dd51051c53884e82c540ceaff… 6628dd51051c53… PASS  \n4 representative_sequences a19e083cfb0ab757d557569bdf76a… a19e083cfb0ab7… PASS  \n5 rooted_insertion_tree    7e541e2ed9e3f81d9b6c6bf989993… 7e541e2ed9e3f8… PASS  \n```\n\n\n:::\n:::\n\n\n### 3. 读取三件套并确认方向\n\n首列作为 key，而不是普通分析变量：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(length(ids) > 0L, !anyDuplicated(ids), !anyNA(ids), nzchar(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\notutab <- read_keyed_tsv(\"data/small/phyloseq-import/otutab.tsv\")\ntaxonomy <- read_keyed_tsv(\"data/small/phyloseq-import/taxonomy.tsv\")\nmetadata <- read_keyed_tsv(\"data/small/phyloseq-import/metadata.tsv\")\n\notu_matrix <- as.matrix(otutab)\nstorage.mode(otu_matrix) <- \"numeric\"\ntax_matrix <- as.matrix(taxonomy)\nstorage.mode(tax_matrix) <- \"character\"\n\nfeature_ids <- rownames(otu_matrix)\nsample_ids <- colnames(otu_matrix)\n\nstopifnot(\n  dim(otu_matrix)[[1L]] == 366L,\n  dim(otu_matrix)[[2L]] == 4L,\n  sum(otu_matrix) == 5213,\n  all(is.finite(otu_matrix)),\n  all(otu_matrix >= 0),\n  all(otu_matrix == round(otu_matrix)),\n  setequal(feature_ids, rownames(tax_matrix)),\n  setequal(sample_ids, rownames(metadata))\n)\n\nlist(\n  otutab_dimension = dim(otu_matrix),\n  taxonomy_dimension = dim(tax_matrix),\n  metadata_dimension = dim(metadata),\n  total_reads = sum(otu_matrix)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$otutab_dimension\n[1] 366   4\n\n$taxonomy_dimension\n[1] 366   7\n\n$metadata_dimension\n[1] 4 5\n\n$total_reads\n[1] 5213\n```\n\n\n:::\n:::\n\n\n看清三张表的结构：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nutils::head(\n  data.frame(FeatureID = rownames(otutab), otutab, check.names = FALSE),\n  5\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                        FeatureID   1  1a   2\nb39be459cc96689db8cd6b00a0d86e8e b39be459cc96689db8cd6b00a0d86e8e 164   0 332\ndf915ccb4ee135b84e0b244e8af12b92 df915ccb4ee135b84e0b244e8af12b92   0 150   0\n5da32e051bdda695c26f4cc556c3aede 5da32e051bdda695c26f4cc556c3aede  65   0 133\n3ebe761bfb1238c87195d431f41bf976 3ebe761bfb1238c87195d431f41bf976  90  17  57\nb7d6cf3f7467ca45087ca083796a0af0 b7d6cf3f7467ca45087ca083796a0af0  57   0  94\n                                  2a\nb39be459cc96689db8cd6b00a0d86e8e   0\ndf915ccb4ee135b84e0b244e8af12b92 140\n5da32e051bdda695c26f4cc556c3aede   0\n3ebe761bfb1238c87195d431f41bf976   0\nb7d6cf3f7467ca45087ca083796a0af0   0\n```\n\n\n:::\n\n```{.r .cell-code}\nutils::head(\n  data.frame(FeatureID = rownames(taxonomy), taxonomy, check.names = FALSE),\n  5\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                        FeatureID   Domain\nb39be459cc96689db8cd6b00a0d86e8e b39be459cc96689db8cd6b00a0d86e8e Bacteria\ndf915ccb4ee135b84e0b244e8af12b92 df915ccb4ee135b84e0b244e8af12b92  Archaea\n5da32e051bdda695c26f4cc556c3aede 5da32e051bdda695c26f4cc556c3aede  Archaea\n3ebe761bfb1238c87195d431f41bf976 3ebe761bfb1238c87195d431f41bf976 Bacteria\nb7d6cf3f7467ca45087ca083796a0af0 b7d6cf3f7467ca45087ca083796a0af0 Bacteria\n                                         Phylum               Class\nb39be459cc96689db8cd6b00a0d86e8e Pseudomonadota Gammaproteobacteria\ndf915ccb4ee135b84e0b244e8af12b92  Nanoarchaeota        Nanoarchaeia\n5da32e051bdda695c26f4cc556c3aede Thermoproteota     Nitrososphaeria\n3ebe761bfb1238c87195d431f41bf976 Pseudomonadota Gammaproteobacteria\nb7d6cf3f7467ca45087ca083796a0af0 Pseudomonadota Gammaproteobacteria\n                                            Order            Family\nb39be459cc96689db8cd6b00a0d86e8e  Burkholderiales   Gallionellaceae\ndf915ccb4ee135b84e0b244e8af12b92  Woesearchaeales    Incertae_Sedis\n5da32e051bdda695c26f4cc556c3aede Nitrosopumilales Nitrosopumilaceae\n3ebe761bfb1238c87195d431f41bf976  Pseudomonadales     Moraxellaceae\nb7d6cf3f7467ca45087ca083796a0af0  Burkholderiales    Comamonadaceae\n                                          Genus    Species\nb39be459cc96689db8cd6b00a0d86e8e     Unassigned Unassigned\ndf915ccb4ee135b84e0b244e8af12b92 Incertae_Sedis Unassigned\n5da32e051bdda695c26f4cc556c3aede Nitrosarchaeum Unassigned\n3ebe761bfb1238c87195d431f41bf976  Acinetobacter Unassigned\nb7d6cf3f7467ca45087ca083796a0af0    Polaromonas Unassigned\n```\n\n\n:::\n\n```{.r .cell-code}\nutils::head(\n  data.frame(SampleID = rownames(metadata), metadata, check.names = FALSE),\n  4\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   SampleID LibraryLabel FilenameSet FilenameVariant AmpliconRegion ReadLayout\n1         1    Library_1        S103            base         16S_V4  PairedEnd\n1a       1a   Library_1a        S103        suffix_a         16S_V4  PairedEnd\n2         2    Library_2        S115            base         16S_V4  PairedEnd\n2a       2a   Library_2a        S115        suffix_a         16S_V4  PairedEnd\n```\n\n\n:::\n:::\n\n\n样本 reads 与 observed ASVs 是最直接的方向回验：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_audit <- tibble::tibble(\n  SampleID = sample_ids,\n  Library = metadata[sample_ids, \"LibraryLabel\"],\n  Reads = as.numeric(colSums(otu_matrix)),\n  ObservedASVs = as.numeric(colSums(otu_matrix > 0))\n)\n\nstopifnot(\n  identical(sample_audit$Reads, c(1144, 1251, 1503, 1315)),\n  identical(sample_audit$ObservedASVs, c(82, 133, 106, 138))\n)\nsample_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  SampleID Library    Reads ObservedASVs\n  <chr>    <chr>      <dbl>        <dbl>\n1 1        Library_1   1144           82\n2 1a       Library_1a  1251          133\n3 2        Library_2   1503          106\n4 2a       Library_2a  1315          138\n```\n\n\n:::\n:::\n\n\n### 4. 读取代表序列与完整 rooted tree\n\n先核对 FASTA header，再把完整树明确裁剪到计数表 ASV：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsequences <- Biostrings::readDNAStringSet(\n  \"data/small/phyloseq-import/representative-sequences.fasta.gz\"\n)\nfull_tree <- ape::read.tree(\n  gzfile(\"data/small/phyloseq-import/rooted-insertion-tree.nwk.gz\")\n)\n\nfull_query_tips <- intersect(full_tree$tip.label, feature_ids)\nreference_only_tips <- setdiff(full_tree$tip.label, feature_ids)\n\nstopifnot(\n  length(sequences) == 366L,\n  setequal(names(sequences), feature_ids),\n  ape::Ntip(full_tree) == 203818L,\n  length(full_query_tips) == 366L,\n  length(reference_only_tips) == 203452L,\n  ape::is.rooted(full_tree),\n  !anyNA(full_tree$edge.length),\n  all(full_tree$edge.length >= 0)\n)\n\nquery_tree <- ape::keep.tip(full_tree, feature_ids)\n\nstopifnot(\n  ape::Ntip(query_tree) == 366L,\n  setequal(query_tree$tip.label, feature_ids),\n  ape::is.rooted(query_tree),\n  !anyNA(query_tree$edge.length),\n  all(query_tree$edge.length >= 0)\n)\n\ntibble::tibble(\n  Tree = c(\"Complete SEPP insertion tree\", \"ASV-pruned object tree\"),\n  Tips = c(ape::Ntip(full_tree), ape::Ntip(query_tree)),\n  QueryTips = c(length(full_query_tips), ape::Ntip(query_tree)),\n  ReferenceOnlyTips = c(length(reference_only_tips), 0L),\n  Rooted = c(ape::is.rooted(full_tree), ape::is.rooted(query_tree))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  Tree                           Tips QueryTips ReferenceOnlyTips Rooted\n  <chr>                         <int>     <int>             <int> <lgl> \n1 Complete SEPP insertion tree 203818       366            203452 TRUE  \n2 ASV-pruned object tree          366       366                 0 TRUE  \n```\n\n\n:::\n:::\n\n\n### 5. 在构造器之前完成 ID gate\n\n对账表应明确区分 feature IDs 与 sample IDs：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_gate <- tibble::tribble(\n  ~Component, ~Domain, ~Expected, ~Matched, ~Missing, ~Unexpected,\n  \"Taxonomy\", \"Feature IDs\", length(feature_ids),\n    length(intersect(feature_ids, rownames(taxonomy))),\n    length(setdiff(feature_ids, rownames(taxonomy))),\n    length(setdiff(rownames(taxonomy), feature_ids)),\n  \"Representative sequences\", \"Feature IDs\", length(feature_ids),\n    length(intersect(feature_ids, names(sequences))),\n    length(setdiff(feature_ids, names(sequences))),\n    length(setdiff(names(sequences), feature_ids)),\n  \"Pruned tree\", \"Feature IDs\", length(feature_ids),\n    length(intersect(feature_ids, query_tree$tip.label)),\n    length(setdiff(feature_ids, query_tree$tip.label)),\n    length(setdiff(query_tree$tip.label, feature_ids)),\n  \"Metadata\", \"Sample IDs\", length(sample_ids),\n    length(intersect(sample_ids, rownames(metadata))),\n    length(setdiff(sample_ids, rownames(metadata))),\n    length(setdiff(rownames(metadata), sample_ids))\n)\n\nstopifnot(\n  all(id_gate$Matched == id_gate$Expected),\n  all(id_gate$Missing == 0L),\n  all(id_gate$Unexpected == 0L)\n)\nid_gate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  Component                Domain      Expected Matched Missing Unexpected\n  <chr>                    <chr>          <int>   <int>   <int>      <int>\n1 Taxonomy                 Feature IDs      366     366       0          0\n2 Representative sequences Feature IDs      366     366       0          0\n3 Pruned tree              Feature IDs      366     366       0          0\n4 Metadata                 Sample IDs         4       4       0          0\n```\n\n\n:::\n:::\n\n\n### 6. 构建五组件 `phyloseq` 对象\n\n先按计数表顺序重排其他组件，再构建对象：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxonomy <- taxonomy[feature_ids, , drop = FALSE]\nmetadata <- metadata[sample_ids, , drop = FALSE]\nsequences <- sequences[feature_ids]\n\nps <- phyloseq::phyloseq(\n  phyloseq::otu_table(otu_matrix, taxa_are_rows = TRUE),\n  phyloseq::tax_table(as.matrix(taxonomy)),\n  phyloseq::sample_data(metadata),\n  phyloseq::phy_tree(query_tree),\n  sequences\n)\n\ncomponent_names <- methods::slotNames(ps)[\n  !vapply(\n    methods::slotNames(ps),\n    function(slot_name) is.null(methods::slot(ps, slot_name)),\n    logical(1)\n  )\n]\n\nstopifnot(\n  inherits(ps, \"phyloseq\"),\n  setequal(\n    component_names,\n    c(\"otu_table\", \"tax_table\", \"sam_data\", \"phy_tree\", \"refseq\")\n  ),\n  phyloseq::taxa_are_rows(ps),\n  phyloseq::ntaxa(ps) == 366L,\n  phyloseq::nsamples(ps) == 4L,\n  sum(phyloseq::sample_sums(ps)) == 5213,\n  setequal(phyloseq::taxa_names(ps), feature_ids),\n  setequal(phyloseq::sample_names(ps), sample_ids),\n  setequal(phyloseq::phy_tree(ps)$tip.label, feature_ids),\n  setequal(names(phyloseq::refseq(ps)), feature_ids)\n)\n\nobject_summary <- tibble::tibble(\n  Metric = c(\n    \"Class\", \"Components\", \"Features\", \"Samples\", \"Reads\",\n    \"Tree tips\", \"Reference sequences\", \"Taxa are rows\"\n  ),\n  Value = c(\n    class(ps)[[1L]],\n    length(component_names),\n    phyloseq::ntaxa(ps),\n    phyloseq::nsamples(ps),\n    sum(phyloseq::sample_sums(ps)),\n    ape::Ntip(phyloseq::phy_tree(ps)),\n    length(phyloseq::refseq(ps)),\n    phyloseq::taxa_are_rows(ps)\n  )\n)\nobject_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  Metric              Value   \n  <chr>               <chr>   \n1 Class               phyloseq\n2 Components          5       \n3 Features            366     \n4 Samples             4       \n5 Reads               5213    \n6 Tree tips           366     \n7 Reference sequences 366     \n8 Taxa are rows       TRUE    \n```\n\n\n:::\n:::\n\n\n`phyloseq` 的内部 slot 名为 `sam_data`，面向读者的 accessor 是 `sample_data()`。分析代码应优先使用 accessor，而不是直接操作 S4 slot。\n\n### 7. 反向核对 taxonomy、样本计数和组件\n\n构建后再次从对象取值：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobject_taxonomy <- as(\n  phyloseq::tax_table(ps),\n  \"matrix\"\n)\ntaxa_reads <- phyloseq::taxa_sums(ps)\n\ntaxonomy_coverage <- do.call(\n  rbind,\n  lapply(colnames(object_taxonomy), function(rank_name) {\n    values <- object_taxonomy[, rank_name]\n    assigned <- !is.na(values) & nzchar(values) & values != \"Unassigned\"\n    data.frame(\n      Rank = rank_name,\n      AssignedASVs = sum(assigned),\n      TotalASVs = length(assigned),\n      AssignedReads = sum(taxa_reads[assigned]),\n      TotalReads = sum(taxa_reads),\n      stringsAsFactors = FALSE\n    )\n  })\n)\n\ngenus_row <- taxonomy_coverage[taxonomy_coverage$Rank == \"Genus\", ]\nspecies_row <- taxonomy_coverage[taxonomy_coverage$Rank == \"Species\", ]\nstopifnot(\n  genus_row$AssignedASVs == 318L,\n  genus_row$AssignedReads == 4217,\n  species_row$AssignedASVs == 0L,\n  species_row$AssignedReads == 0\n)\n\ntaxonomy_coverage\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Rank AssignedASVs TotalASVs AssignedReads TotalReads\n1  Domain          366       366          5213       5213\n2  Phylum          354       366          5153       5213\n3   Class          353       366          5144       5213\n4   Order          336       366          5024       5213\n5  Family          333       366          5011       5213\n6   Genus          318       366          4217       5213\n7 Species            0       366             0       5213\n```\n\n\n:::\n\n```{.r .cell-code}\nphyloseq::sample_sums(ps)[sample_ids]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   1   1a    2   2a \n1144 1251 1503 1315 \n```\n\n\n:::\n\n```{.r .cell-code}\nphyloseq::rank_names(ps)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Domain\"  \"Phylum\"  \"Class\"   \"Order\"   \"Family\"  \"Genus\"   \"Species\"\n```\n\n\n:::\n\n```{.r .cell-code}\nphyloseq::sample_variables(ps)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"LibraryLabel\"    \"FilenameSet\"     \"FilenameVariant\" \"AmpliconRegion\" \n[5] \"ReadLayout\"     \n```\n\n\n:::\n:::\n\n\n### 8. 保存并回读 RDS\n\n保存之前已完成输入与对象检查。回读后比较 class、组件、维度、reads 和 ID：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrds_path <- \"results/17-phyloseq-import/atacama-v4-phyloseq.rds\"\ndir.create(dirname(rds_path), recursive = TRUE, showWarnings = FALSE)\nsaveRDS(ps, rds_path, version = 3, compress = \"xz\")\nps_reloaded <- readRDS(rds_path)\n\nstopifnot(\n  inherits(ps_reloaded, \"phyloseq\"),\n  phyloseq::ntaxa(ps_reloaded) == phyloseq::ntaxa(ps),\n  phyloseq::nsamples(ps_reloaded) == phyloseq::nsamples(ps),\n  identical(\n    as.numeric(phyloseq::sample_sums(ps_reloaded)[sample_ids]),\n    as.numeric(phyloseq::sample_sums(ps)[sample_ids])\n  ),\n  setequal(phyloseq::taxa_names(ps_reloaded), phyloseq::taxa_names(ps)),\n  setequal(phyloseq::sample_names(ps_reloaded), phyloseq::sample_names(ps))\n)\n\ntibble::tibble(\n  Metric = c(\"Class\", \"Features\", \"Samples\", \"Reads\", \"Taxa IDs\", \"Sample IDs\"),\n  Before = c(\n    class(ps)[[1L]], phyloseq::ntaxa(ps), phyloseq::nsamples(ps),\n    sum(phyloseq::sample_sums(ps)), length(phyloseq::taxa_names(ps)),\n    length(phyloseq::sample_names(ps))\n  ),\n  After = c(\n    class(ps_reloaded)[[1L]], phyloseq::ntaxa(ps_reloaded),\n    phyloseq::nsamples(ps_reloaded), sum(phyloseq::sample_sums(ps_reloaded)),\n    length(phyloseq::taxa_names(ps_reloaded)),\n    length(phyloseq::sample_names(ps_reloaded))\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  Metric     Before   After   \n  <chr>      <chr>    <chr>   \n1 Class      phyloseq phyloseq\n2 Features   366      366     \n3 Samples    4        4       \n4 Reads      5213     5213    \n5 Taxa IDs   366      366     \n6 Sample IDs 4        4       \n```\n\n\n:::\n:::\n\n\n发布前的独立校验命令为：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nRscript --vanilla scripts/validate_phyloseq_import.R \\\n  --project-root . \\\n  --input-dir data/small/phyloseq-import \\\n  --output-dir results/17-phyloseq-import \\\n  --figure-dir figures\n\n# Expected terminal line:\n# Article 17 validation complete: 82 / 82 PASS\n```\n:::\n\n\n该脚本还固定 R 与包版本、七份输入哈希、序列长度、完整树与裁剪树、五个对象组件、逐样本 reads、逐 rank taxonomy 覆盖和 RDS 往返结果。机器可读总表在 `results/17-phyloseq-import/validation-checks.tsv`。\n\n## 出版级美化 {#sec-visualization}\n\n### 1. 先画数据合同，再画生态结果\n\n对象入口最值得展示的不是一个 `str(ps)` 截图，而是能回答以下问题的审计图：\n\n- 哪些输入进入对象；\n- ID 是否完整匹配；\n- 样本 reads 与 observed ASVs 是否保留；\n- taxonomy 覆盖下降发生在哪个层级。\n\n例如从对象计算 taxonomy 覆盖后可重绘为 feature- 与 read-weighted 两种比例：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoverage_long <- taxonomy_coverage |>\n  dplyr::mutate(\n    FeatureCoverage = 100 * AssignedASVs / TotalASVs,\n    ReadCoverage = 100 * AssignedReads / TotalReads\n  ) |>\n  tidyr::pivot_longer(\n    c(FeatureCoverage, ReadCoverage),\n    names_to = \"Weighting\",\n    values_to = \"Coverage\"\n  ) |>\n  dplyr::mutate(\n    Weighting = dplyr::recode(\n      Weighting,\n      FeatureCoverage = \"ASV weighted\",\n      ReadCoverage = \"Read weighted\"\n    )\n  )\n\np_coverage <- ggplot2::ggplot(\n  coverage_long,\n  ggplot2::aes(x = Rank, y = Coverage, color = Weighting, group = Weighting)\n) +\n  ggplot2::geom_line(linewidth = 0.8) +\n  ggplot2::geom_point(size = 2.6) +\n  scale_color_pub(values = c(\"#0072B2\", \"#D55E00\")) +\n  ggplot2::scale_y_continuous(\n    limits = c(0, 100),\n    breaks = seq(0, 100, 20),\n    labels = function(x) paste0(x, \"%\")\n  ) +\n  ggplot2::labs(\n    x = \"Taxonomic rank\",\n    y = \"Assigned coverage\",\n    color = NULL,\n    title = \"Taxonomic resolution declines toward lower ranks\"\n  ) +\n  theme_pub()\n\nsave_pub(\n  p_coverage,\n  \"figures/17-taxonomy-coverage-redraw\",\n  width = 125,\n  height = 90\n)\n```\n:::\n\n\n图内的 title、axis、legend、sample labels 和 annotation 使用英文；中文解释留在正文。这样可直接进入英文论文，也能减少跨平台字体差异。\n\n### 2. 图形导出与主张保持一致\n\n本页四张正式图均输出：\n\n```text\nPDF                         vector\nPNG                         350 dpi\nTIFF                        350 dpi, LZW compression\n```\n\n尺寸应按期刊单栏或双栏物理宽度设置，不要先导出一张超大像素图再在排版软件中任意拉伸。`save_pub()` 的 `width` 与 `height` 单位为 mm，方便直接按期刊规格调整。\n\n::: {.callout-tip title=\"审计图也要有明确的统计单位\"}\ntaxonomy coverage 同时给 ASV-weighted 和 read-weighted 结果。前者回答“多少 feature 有名字”，后者回答“这些 feature 覆盖多少观测 reads”。两者差异本身可能提示未注释 feature 主要位于低丰度还是高丰度部分。\n:::\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人和合作者最容易追问的 12 个问题\"}\n1. **从来历不明的 `ps.rds` 开始**：无法回查原始 counts、taxonomy release、metadata 对齐和 tree 处理。保留标准输入、哈希和构建脚本。  \n2. **把 BIOM 方向读反**：必须用 taxonomy feature IDs 和 metadata sample IDs 判断方向，并核对 `taxa_are_rows`。  \n3. **让构造器静默求交集**：先算 `setdiff()`，报告每个组件缺失与额外 ID，再构建对象。  \n4. **把完整 SEPP reference tips 当样本 ASV**：完整树可归档，但对象树要显式裁剪到 feature table；本例从 203,818 tips 裁到 366。  \n5. **只看 `ntaxa()`，不看 reads**：丢一个高丰度 ASV 可能只减少 1 个 feature，却改变大量 reads。feature 与 read retention 都要报告。  \n6. **导入时覆盖原始 counts**：relative abundance、rarefaction 与 CLR 分别在对象副本上完成，不要覆盖 count ledger。  \n7. **metadata 行名被自动改写**：`check.names = FALSE`，把首列显式设为 row names，并检查重复、空值和集合相等。  \n8. **taxonomy 一列字符串直接塞进 `tax_table`**：先拆成固定 rank 列、去前缀、保留真正未注释值，再验收列名。  \n9. **把空 Species 补成 Genus**：这制造了不存在的物种分辨率。本例 Species 为 0/366 ASV。  \n10. **树有 tip labels 却没有可靠 branch lengths/root**：系统发育指标还需要 rootedness、完整且非负的枝长。  \n11. **把技术文件名当分组**：本例四个 labels 不能支持任何处理效应、病例对照或重复测量推断。  \n12. **RDS 保存后不回读**：至少在全新 R session 中 `readRDS()`，比较 class、组件、features、samples、reads 和 ID。\n:::\n\n::: {.callout-warning title=\"对象中有变量，不等于研究设计支持该变量\"}\n`sample_data()` 只是存储 metadata。一个列名能被 `plot_ordination(..., color = ...)` 使用，并不证明该变量有足够重复、与 batch 可分离或适合置换检验。统计设计仍要独立验收。\n:::\n\n::: {.callout-warning title=\"不要把 phyloseq 自动修剪当作数据清洗策略\"}\n自动保留共同 taxa 可以让代码继续运行，却会掩盖拼写差异、截断的 FASTA header、taxonomy 缺行或 tree tip 命名错误。只有已经解释并记录的 reference-only tips 才能在明确规则下裁剪。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n下面模板可直接替换方括号内容：\n\n> QIIME 2 `FeatureTable[Frequency]`, `FeatureData[Taxonomy]`, representative-sequence, and rooted-phylogeny Artifacts were exported using QIIME 2 version [2026.4.0]. The BIOM feature table was converted to a tab-delimited feature-by-sample count matrix without normalization. Taxonomy strings were parsed into seven ranks, and sample identifiers were reconciled between the count matrix and metadata before object construction. Representative-sequence identifiers and query tips in the complete SEPP insertion tree were matched to feature-table identifiers; the complete [203,818]-tip insertion tree was then explicitly pruned to the [366] observed ASV tips using `ape` version [5.8]. A five-component `phyloseq` object was constructed in R version [4.4.1] using `phyloseq` version [1.48.0], comprising the raw-count `otu_table` (`taxa_are_rows = TRUE`), `tax_table`, `sample_data`, rooted `phy_tree`, and `refseq`. Input files were verified by SHA-256 checksums. Feature counts, sample counts, total reads, identifier sets, tree branch lengths, and per-sample library sizes were checked before and after construction and after RDS serialization. The final object contained [366] ASVs across [4] technical libraries and [5,213] reads. The library labels represented source filenames and were not treated as biological groups. Random procedures used a fixed seed of [20260721].\n\n若没有 tree 或 representative sequences，应删除对应组件和句子；不能把三组件对象写成完成了系统发育分析。若正文分析使用了过滤、稀释、相对丰度或 log-ratio 变换，还要在相应 Methods 段落另行说明，不能用“构建了 phyloseq 对象”代替预处理细节。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. 准备三件套和可选的两个组件\n\n| 文件 | 必需性 | 合同 |\n|---|---|---|\n| `otutab.tsv` | 必需 | 首列 feature ID；其余列是 sample；非负整数 counts |\n| `taxonomy.tsv` | 必需 | 首列同一 feature ID；其余列为固定 taxonomy ranks |\n| `metadata.tsv` | 必需 | 首列 sample ID；其余列为实验与协变量 |\n| representative FASTA | 推荐 | 每个 count feature 一条同名序列 |\n| rooted Newick tree | 系统发育分析必需 | 包含目标 feature tips；枝长完整且非负 |\n\n只需要替换路径：\n\n```r\notutab_path <- \"data/otutab.tsv\"\ntaxonomy_path <- \"data/taxonomy.tsv\"\nmetadata_path <- \"data/metadata.tsv\"\nsequence_path <- \"data/representative-sequences.fasta.gz\"\ntree_path <- \"data/rooted-tree.nwk.gz\"\n```\n\n然后保留本文的 `read_keyed_tsv()`、方向检查、集合对账、对象反查和 RDS 回验。不要删除检查里的 expected 值后直接运行；应把 366、4、5,213 等示例数字替换成自己在冻结输入后签字确认的数值。\n\n### 2. taxonomy 只有一个 `Taxon` 字符串时完整拆列\n\nQIIME 2 常导出 `Feature ID`、`Taxon`、`Confidence`。下面代码把分号分隔字符串转成七列，并保留 confidence 供敏感性检查：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxonomy_qiime <- readr::read_tsv(\n  \"export/taxonomy/taxonomy.tsv\",\n  show_col_types = FALSE,\n  name_repair = \"minimal\"\n) |>\n  dplyr::rename(\n    FeatureID = `Feature ID`,\n    TaxonomyString = Taxon\n  ) |>\n  tidyr::separate_wider_delim(\n    TaxonomyString,\n    delim = \";\",\n    names = c(\"Domain\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"),\n    too_few = \"align_start\",\n    too_many = \"merge\"\n  ) |>\n  dplyr::mutate(\n    dplyr::across(\n      c(Domain, Phylum, Class, Order, Family, Genus, Species),\n      function(x) {\n        x <- trimws(x)\n        x <- sub(\"^[dpkcofgs]__\", \"\", x)\n        x[x == \"\"] <- NA_character_\n        x\n      }\n    )\n  )\n\nreadr::write_tsv(\n  dplyr::select(\n    taxonomy_qiime,\n    FeatureID, Domain, Phylum, Class, Order, Family, Genus, Species\n  ),\n  \"data/taxonomy.tsv\",\n  na = \"\"\n)\nreadr::write_tsv(\n  dplyr::select(taxonomy_qiime, FeatureID, Confidence),\n  \"data/taxonomy-confidence.tsv\",\n  na = \"\"\n)\n```\n:::\n\n\n不同数据库可能使用 `D_0__`、`Kingdom` 或更多/更少 ranks。先根据数据库合同建立明确 crosswalk，再改列名；不要只按字符串位置猜。\n\n### 3. 用 ID 判断计数表是否需要转置\n\n\n::: {.cell}\n\n```{.r .cell-code}\notu_raw <- read_keyed_tsv(otutab_path)\ntax_raw <- read_keyed_tsv(taxonomy_path)\nmeta_raw <- read_keyed_tsv(metadata_path)\n\notu_candidate <- as.matrix(otu_raw)\n\nif (\n  setequal(rownames(otu_candidate), rownames(tax_raw)) &&\n  setequal(colnames(otu_candidate), rownames(meta_raw))\n) {\n  otu_matrix <- otu_candidate\n} else if (\n  setequal(colnames(otu_candidate), rownames(tax_raw)) &&\n  setequal(rownames(otu_candidate), rownames(meta_raw))\n) {\n  otu_matrix <- t(otu_candidate)\n} else {\n  stop(\"Count-table orientation cannot be reconciled with taxonomy and metadata IDs.\")\n}\n\nstorage.mode(otu_matrix) <- \"numeric\"\nstopifnot(\n  all(is.finite(otu_matrix)),\n  all(otu_matrix >= 0),\n  all(otu_matrix == round(otu_matrix))\n)\n```\n:::\n\n\n### 4. 没有 tree 或序列时构建三组件对象\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps_three <- phyloseq::phyloseq(\n  phyloseq::otu_table(otu_matrix, taxa_are_rows = TRUE),\n  phyloseq::tax_table(as.matrix(tax_raw[rownames(otu_matrix), , drop = FALSE])),\n  phyloseq::sample_data(meta_raw[colnames(otu_matrix), , drop = FALSE])\n)\n```\n:::\n\n\n此时 Bray–Curtis、Jaccard、Aitchison、组成展示和许多差异丰度方法仍可开展；Faith's PD 与 UniFrac 不可用。若后来补入 tree，必须重新做 feature-tip 对账和对象 reads retention，而不是直接把任意 Newick 文件塞进对象。\n\n### 5. 在正式下游分析前完成签字\n\n- counts 是未归一化的非负整数，方向由 ID 证明；\n- taxonomy feature IDs 与 count features 完全一致，未注释层级保持缺失；\n- metadata sample IDs 与 count columns 完全一致，变量含义和单位有数据字典；\n- representative FASTA headers 与 count features 完全一致；\n- tree 已 root，枝长完整、非负，进入对象的 tips 与 count features 完全一致；\n- `ntaxa()`、`nsamples()`、`sample_sums()`、`taxa_names()` 和 `sample_names()` 与输入账本一致；\n- RDS 在全新 session 回读后仍通过同一组检查；\n- 输入哈希、包版本、构建脚本和验证日志已经归档。\n\n完成这些检查后，再复制对象创建分支用于过滤、归一化和统计模型。原始 count 对象保留为只读基线。\n\n## 参考 {#sec-references}\n\n1. McMurdie PJ, Holmes S. phyloseq: an R package for reproducible interactive analysis and graphics of microbiome census data. *PLoS ONE*. 2013;8:e61217. [doi:10.1371/journal.pone.0061217](https://doi.org/10.1371/journal.pone.0061217)\n2. QIIME 2. Exporting data from QIIME 2 Artifacts. [https://docs.qiime2.org/2024.10/tutorials/exporting/](https://docs.qiime2.org/2024.10/tutorials/exporting/)\n3. Bioconductor. phyloseq package and vignettes. [https://bioconductor.org/packages/phyloseq/](https://bioconductor.org/packages/phyloseq/)\n4. Paradis E, Schliep K. ape 5.0: an environment for modern phylogenetics and evolutionary analyses in R. *Bioinformatics*. 2019;35:526–528. [doi:10.1093/bioinformatics/bty633](https://doi.org/10.1093/bioinformatics/bty633)\n5. Pagès H, Aboyoun P, Gentleman R, DebRoy S. Biostrings: efficient manipulation of biological strings. Bioconductor package. [https://bioconductor.org/packages/Biostrings/](https://bioconductor.org/packages/Biostrings/)\n6. Bolyen E, Rideout JR, Dillon MR, et al. Reproducible, interactive, scalable and extensible microbiome data science using QIIME 2. *Nature Biotechnology*. 2019;37:852–857. [doi:10.1038/s41587-019-0209-9](https://doi.org/10.1038/s41587-019-0209-9)\n7. nf-core/test-datasets, ampliseq V4 test data, commit `f282ad2bafb3ca90190ec87290066ee1985df655` (MIT). [https://github.com/nf-core/test-datasets/tree/f282ad2bafb3ca90190ec87290066ee1985df655/testdata](https://github.com/nf-core/test-datasets/tree/f282ad2bafb3ca90190ec87290066ee1985df655/testdata)\n",
    "supporting": [
      "17-phyloseq-import_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}