{
  "hash": "fba27eab1468080a4e66ba9d7879c999",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 05 篇 · 批次效应：来源、检测与校正策略\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**从实验设计、群落距离和 feature 三个层级识别 batch effect，区分“在模型中控制批次”和“直接改写丰度表”，并用可审计的敏感性分析检查生物结论是否稳定。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`；metadata 额外包含 `PlateNumber`、`Subject`、`Habitat`、`IsNegative` 和 DNA 定量。  \n> **预计资源：**1,951 个 ASV、569 个样本；普通笔记本约 2–5 分钟，内存低于 1 GB。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n批次效应（batch effect）不是“PCoA 上按批次上色看起来没分开”就可以排除。论文中至少应留下四类证据：\n\n1. 生物分组在各批次中的样本数，证明批次与研究变量可以区分；\n2. 批次、研究变量与个体对群落差异的解释率，而不只给显著性；\n3. feature 层面的批次影响和多重检验结果；\n4. 主分析、批次控制模型和删去单一批次后的敏感性结果。\n\n本篇使用 `decontam 1.24.0` 随包分发的真实 `MUClite.rds` 数据。对象包含 539 个口腔生物样本、30 个阴性对照、3 位受试者、7 个口腔部位和 6 块实验板。每位受试者分布在两块板上，每块板又覆盖全部 7 个部位，因此可以估计“同一受试者内部的板间差异”；但 plate 与 subject 仍是嵌套关系，不能把板间差异简单宣布为纯技术效应。\n\n::: {layout-ncol=2}\n![每块板均覆盖 7 个口腔部位，但 plate 嵌套在 subject 内。](../figures/05-batch-design-audit.png){#fig-batch-design}\n\n![Bray-Curtis 与 Aitchison 距离下，habitat、subject 和 plate 的群落解释率。](../figures/05-community-batch-effects.png){#fig-community-batch}\n:::\n\n::: {layout-ncol=2}\n![234 个高检出 ASV 的 habitat 与 plate 解释率；颜色表示 plate 项的 FDR 判定。](../figures/05-feature-batch-effects.png){#fig-feature-batch}\n\n![保留 habitat 与 subject 设计项后，诊断性移除 subject 内 plate 均值前后的残差 PCA。](../figures/05-adjustment-diagnostic.png){#fig-adjustment}\n:::\n\n::: {.callout-important title=\"先判断能不能分，再谈怎么校正\"}\n如果所有病例都在 Batch 1、所有对照都在 Batch 2，`Group` 与 `Batch` 完全共线。此时不存在能从这批数据中唯一分离“疾病效应”和“批次效应”的统计方法。ComBat、ConQuR、MMUPHin 或任何深度模型都不能凭空创造缺失的交叉设计；强行校正只是在不可识别的信号之间做未经验证的分配。\n:::\n\n## 理论：批次从哪里来，为什么不能见到就删 {#sec-theory}\n\n### 1. 从采样到统计模型，每一层都可能形成批次\n\n| 阶段 | 常见批次来源 | 建议保留的 metadata |\n|---|---|---|\n| Sampling | 日期、中心、操作者、季节、运输路线 | `CollectionDate`, `Site`, `Collector` |\n| Storage | 保存液、温度、冻融次数、保存时长 | `Preservative`, `FreezeThaw`, `StorageDays` |\n| Extraction | kit lot、提取板、机器人、实验人员 | `ExtractionBatch`, `KitLot`, `PlateRow/Column` |\n| PCR | primer lot、循环数、PCR plate | `PCRBatch`, `PrimerLot`, `PCRCycles` |\n| Sequencing | run、lane、flow cell、index set | `SequencingRun`, `Lane`, `IndexSet` |\n| Bioinformatics | 引物、截断长度、数据库、软件版本 | `PipelineVersion`, `ClassifierVersion` |\n\n同一天、同一块板或同一个研究中心产生的相似性，可能来自技术流程，也可能包含真实的空间、时间或人群差异。批次变量的定义不是“我不感兴趣的列”，而是需要结合采样流程、随机化记录和研究问题解释的变异来源。\n\n### 2. technical batch、biological block 与 confounder 不是同义词\n\n- **Technical batch：**本希望相同的样本因提取板、试剂批号或测序 run 不同而产生系统差异。\n- **Biological block：**subject、cage、plot、center 等会让样本相关，但这种相关本身可能具有生物意义。\n- **Confounder：**同时与暴露/分组和结局相关，导致目标效应无法直接解释。\n\n例如 cage 既可能是需要控制的笼位效应，也可能通过共食粪便真实改变肠道微生物。把 cage 影响从丰度表中“抹平”不等于获得更真实的数据；更稳妥的做法通常是在设计和模型中承认 cage 这一层级。\n\n### 3. 三种设计决定了可做的分析\n\n| Batch × biology 关系 | 例子 | 能否估计批次 | 首选策略 |\n|---|---|---|---|\n| Crossed / balanced | 每个批次都有病例与对照 | 可以 | 模型中加入 batch；必要时做经过验证的校正 |\n| Partially crossed | 部分批次缺少某一组 | 有限 | 限制比较范围、分层/混合模型、敏感性分析 |\n| Completely confounded | Batch 1 全病例，Batch 2 全对照 | 不可以 | 补测桥接样本、重新设计或弱化问题 |\n\n用设计矩阵表示时，完全混杂会导致矩阵不满秩：\n\n$$\n\\operatorname{rank}(\\mathbf{X}) < \\operatorname{ncol}(\\mathbf{X})\n$$\n\n这不是软件报错技巧问题，而是数据没有提供足够信息。\n\n### 4. 批次诊断必须同时看 effect size 与 dispersion\n\nPCoA/PCA 只展示前几个方向，批次也可能影响稀有 feature、零比例、方差或高阶分布。一个基本诊断组合是：\n\n- 设计交叉表与 library/QC 分布；\n- Bray-Curtis、Aitchison 等不同距离下的 PERMANOVA $R^2$；\n- 与 PERMANOVA 配套的 multivariate dispersion；\n- feature-wise 模型，并做 Benjamini-Hochberg FDR；\n- leave-one-batch-out 或 within-batch 敏感性分析。\n\n大样本中很小的批次效应也可能得到极小的 $P$ 值。反过来，批次数很少时，一个肉眼明显的差异也可能没有足够的批次级自由度。结论应首先看设计和效应量，再看显著性。\n\n### 5. “控制 batch”优先于“改写数据”\n\n从稳妥到激进，可按下列顺序决策：\n\n1. **实验阶段预防：**随机分板、平衡分组、桥接样本、阴性/阳性对照；\n2. **统计模型控制：**把 batch 作为固定效应、随机效应或 permutation block；\n3. **分层与 meta-analysis：**先在 batch/study 内估计，再合并效应；\n4. **生成校正后的 profile：**仅在设计可识别、方法与数据类型匹配且生物信号保留得到验证时使用；\n5. **补测或缩小问题：**完全混杂时增加 bridge samples，或只回答批次内可识别的问题。\n\n[Wang 与 Lê Cao](https://doi.org/10.1093/bib/bbz105)系统总结了微生物组 batch 的来源、设计条件和方法假设；[Gibbons 等](https://doi.org/10.1371/journal.pcbi.1006102)证明常规 omics 校正可能在微生物组 case-control 合并中制造或掩盖信号；[ConQuR](https://doi.org/10.1038/s41467-022-33071-9)与 [MMUPHin](https://doi.org/10.1186/s13059-022-02753-4)则针对零膨胀、过度离散和多队列结构提供了更专门的方法。\n\n<details>\n<summary><strong>深入：为什么本篇不把 ComBat 后的丰度表当默认答案</strong></summary>\n\n16S 计数具有稀疏、过度离散和成分性。对相对丰度逐 feature 做高斯位置/尺度校正，可能：\n\n- 产生负值或破坏每个样本总和；\n- 把真实但与 batch 相关的生物差异一并删除；\n- 改变零值、稀有 feature 与相关结构；\n- 在全数据上先校正再交叉验证，造成测试集信息泄漏；\n- 让排序图“混得更好”，但下游分类或差异结果更差。\n\n因此本篇的矩阵调整只作为**设计矩阵是否按预期工作**的诊断：先保留 habitat 与 subject 的模型项，再减去每位 subject 内的 plate 均值对比。它不是 ConQuR、MMUPHin 或 ComBat 的替代品，也不作为后续差异丰度的默认输入。正式推断仍优先在每个方法自己的模型中加入 batch。\n\n</details>\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、导出真实数据和定义作图函数</strong></summary>\n\n本篇使用 R 4.4.1、Bioconductor 3.19、`decontam 1.24.0` 与 `vegan 2.6-6.1`。首次运行安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"BiocManager\", \"vegan\", \"ggplot2\", \"scales\", \"digest\"\n))\nBiocManager::install(version = \"3.19\", ask = FALSE)\nBiocManager::install(\n  c(\"decontam\", \"phyloseq\"),\n  ask = FALSE,\n  update = FALSE\n)\n```\n:::\n\n\n`MUClite.rds` 随 `decontam` 分发。下面代码核对对象 SHA-256，并导出本篇使用的三件套：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(phyloseq)\n\nmuc_path <- system.file(\n  \"extdata\",\n  \"MUClite.rds\",\n  package = \"decontam\"\n)\nexpected_sha256 <- paste0(\n  \"801456d5780d5f51308d04c23f447710\",\n  \"2cc5fbe9543ffa62fad2240a99c43d62\"\n)\nstopifnot(\n  nzchar(muc_path),\n  identical(\n    digest::digest(\n      file = muc_path,\n      algo = \"sha256\",\n      serialize = FALSE\n    ),\n    expected_sha256\n  )\n)\n\nps <- readRDS(muc_path)\notutab <- as(phyloseq::otu_table(ps), \"matrix\")\nif (!phyloseq::taxa_are_rows(ps)) {\n  otutab <- t(otutab)\n}\ntaxonomy <- as(phyloseq::tax_table(ps), \"matrix\")\nmetadata <- as.data.frame(phyloseq::sample_data(ps))\nmetadata$IsNegative <- (\n  metadata$Sample_or_Control == \"Control Sample\"\n)\n\nwrite_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name),\n    x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out,\n    path,\n    sep = \"\\t\",\n    quote = FALSE,\n    row.names = FALSE,\n    na = \"\"\n  )\n}\n\ndir.create(\n  \"data/small/decontam\",\n  recursive = TRUE,\n  showWarnings = FALSE\n)\nwrite_tsv(\n  otutab,\n  \"FeatureID\",\n  \"data/small/decontam/otutab.tsv\"\n)\nwrite_tsv(\n  taxonomy,\n  \"FeatureID\",\n  \"data/small/decontam/taxonomy.tsv\"\n)\nwrite_tsv(\n  metadata,\n  \"SampleID\",\n  \"data/small/decontam/metadata.tsv\"\n)\n```\n:::\n\n\n出版级函数直接定义在文章内：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(decontam)\nlibrary(vegan)\nlibrary(ggplot2)\n\nstopifnot(\n  identical(\n    as.character(utils::packageVersion(\"decontam\")),\n    \"1.24.0\"\n  ),\n  identical(\n    as.character(utils::packageVersion(\"vegan\")),\n    \"2.6.6.1\"\n  )\n)\n\nset.seed(20260719)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(\n        color = \"black\",\n        linewidth = 0.3\n      ),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 120,\n  height = 95,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(\n    dirname(file_base),\n    recursive = TRUE,\n    showWarnings = FALSE\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n}\n```\n:::\n\n\n整仓库运行时可使用内容相同的 `R/theme_pub.R`；独立运行以上代码块即可获得全部函数。\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 从三件套读取并核对 batch metadata\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"data/small/decontam/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"data/small/decontam/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/decontam/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\nmetadata$IsNegative <- as.logical(metadata$IsNegative)\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(otutab >= 0),\n  all(otutab == floor(otutab)),\n  all(c(\n    \"PlateNumber\",\n    \"Subject\",\n    \"Habitat\",\n    \"quant_reading\",\n    \"IsNegative\"\n  ) %in% colnames(metadata)),\n  all(metadata$quant_reading > 0)\n)\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1951  569\n```\n\n\n:::\n\n```{.r .cell-code}\notutab[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     P1101C01701R00 P1101C01702R00 P1101C01703R00 P1101C08701R00 P1101C08702R00\nSeq1           3502          12040           9877           4035          12491\nSeq2           8391            152           2401           5706           1444\nSeq3              0              0              0              0              0\nSeq4            193           7924           4333            257           4384\nSeq5           2838              0              0           3161            294\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxonomy[1:5, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Kingdom         Phylum               Class           Order\nSeq1 Bacteria     Firmicutes             Bacilli Lactobacillales\nSeq2 Bacteria Proteobacteria Gammaproteobacteria  Pasteurellales\nSeq3 Bacteria        unknown             unknown         unknown\nSeq4 Bacteria Proteobacteria Gammaproteobacteria  Pasteurellales\nSeq5 Bacteria Proteobacteria  Betaproteobacteria    Neisseriales\n               Family         Genus\nSeq1 Streptococcaceae Streptococcus\nSeq2  Pasteurellaceae   Haemophilus\nSeq3          unknown       unknown\nSeq4  Pasteurellaceae   Haemophilus\nSeq5    Neisseriaceae     Neisseria\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   X.SampleID PlateNumber Subject     Habitat quant_reading\nP1101C01701R00 P1101C01701R00           3    1101      Tongue          2829\nP1101C01702R00 P1101C01702R00           3    1101 Cheek_Right          5808\nP1101C01703R00 P1101C01703R00           3    1101  Cheek_Left          5052\nP1101C08701R00 P1101C08701R00           3    1101      Tongue          1227\nP1101C08702R00 P1101C08702R00           3    1101 Cheek_Right          3872\nP1101C08703R00 P1101C08703R00           3    1101  Cheek_Left          5872\n               Sample_or_Control IsNegative\nP1101C01701R00       True Sample      FALSE\nP1101C01702R00       True Sample      FALSE\nP1101C01703R00       True Sample      FALSE\nP1101C08701R00       True Sample      FALSE\nP1101C08702R00       True Sample      FALSE\nP1101C08703R00       True Sample      FALSE\n```\n\n\n:::\n:::\n\n\n原始对象包含 1,951 个 ASV 和 569 个测序样本，其中 30 个为阴性对照。批次分析前不能忽略污染：若某一提取板的 reagent background 更高，污染本身就会表现为 batch effect。\n\n### 2. 在本篇内完成污染判定，再保留生物样本\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseqtab <- t(otutab)\ncontam_combined <- decontam::isContaminant(\n  seqtab,\n  method = \"combined\",\n  conc = metadata$quant_reading,\n  neg = metadata$IsNegative,\n  threshold = 0.10\n)\n\ncontaminant_ids <- rownames(contam_combined)[\n  contam_combined$contaminant\n]\nbiological_ids <- rownames(metadata)[\n  !metadata$IsNegative\n]\n\notutab_bio <- otutab[\n  setdiff(rownames(otutab), contaminant_ids),\n  biological_ids,\n  drop = FALSE\n]\ntaxonomy_bio <- taxonomy[\n  rownames(otutab_bio),\n  ,\n  drop = FALSE\n]\nmetadata_bio <- metadata[\n  biological_ids,\n  ,\n  drop = FALSE\n]\n\nstopifnot(\n  identical(\n    rownames(otutab_bio),\n    rownames(taxonomy_bio)\n  ),\n  identical(\n    colnames(otutab_bio),\n    rownames(metadata_bio)\n  )\n)\n\ndata.frame(\n  ContaminantsRemoved = length(contaminant_ids),\n  BiologicalSamples = ncol(otutab_bio),\n  RetainedASVs = nrow(otutab_bio)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ContaminantsRemoved BiologicalSamples RetainedASVs\n1                  56               539         1895\n```\n\n\n:::\n:::\n\n\n本例标记并移除 56 个候选污染 ASV，保留 1895 个 ASV 和 539 个生物样本。阴性对照不进入后续生物群落模型，但原始三件套与 classifier 结果始终保留。\n\n### 3. 先画设计矩阵，不从排序图开始\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhabitat_labels <- c(\n  \"Cheek_Left\" = \"Cheek left\",\n  \"Cheek_Right\" = \"Cheek right\",\n  \"Floor\" = \"Mouth floor\",\n  \"Lip_Lower\" = \"Lower lip\",\n  \"Lip_Upper\" = \"Upper lip\",\n  \"Roof\" = \"Mouth roof\",\n  \"Tongue\" = \"Tongue\"\n)\nhabitat_levels <- unname(habitat_labels)\n\nmetadata_bio$Habitat <- factor(\n  unname(habitat_labels[metadata_bio$Habitat]),\n  levels = habitat_levels\n)\nmetadata_bio$Subject <- factor(\n  paste(\"Subject\", metadata_bio$Subject)\n)\nmetadata_bio$Plate <- factor(\n  paste(\"Plate\", metadata_bio$PlateNumber),\n  levels = paste(\"Plate\", 1:6)\n)\n\nplate_subject_table <- with(\n  metadata_bio,\n  table(Plate, Subject)\n)\nplate_habitat_table <- with(\n  metadata_bio,\n  table(Plate, Habitat)\n)\n\nplate_subject_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Subject\nPlate     Subject 1101 Subject 1102 Subject 1104\n  Plate 1            0            0           91\n  Plate 2            0            0           90\n  Plate 3           89            0            0\n  Plate 4            0           90            0\n  Plate 5            0           89            0\n  Plate 6           90            0            0\n```\n\n\n:::\n\n```{.r .cell-code}\nplate_habitat_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Habitat\nPlate     Cheek left Cheek right Mouth floor Lower lip Upper lip Mouth roof\n  Plate 1         15          14           9        15        15          8\n  Plate 2         10          11          17        11        11         18\n  Plate 3         16          15          13         8         7         14\n  Plate 4         16          15           8        14        14          8\n  Plate 5         16          14          13         8         8         14\n  Plate 6         16          15           8        14        14          8\n         Habitat\nPlate     Tongue\n  Plate 1     15\n  Plate 2     12\n  Plate 3     16\n  Plate 4     15\n  Plate 5     16\n  Plate 6     15\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\n  all(rowSums(plate_subject_table > 0) == 1),\n  all(colSums(plate_subject_table > 0) == 2),\n  all(plate_habitat_table > 0)\n)\n\nplate_subject_map <- unique(\n  metadata_bio[c(\"Plate\", \"Subject\")]\n)\nplate_subject_map <- plate_subject_map[\n  order(plate_subject_map$Plate),\n  ,\n  drop = FALSE\n]\n\ndesign_counts <- as.data.frame(\n  plate_habitat_table,\n  responseName = \"Samples\"\n)\ndesign_counts$Subject <- plate_subject_map$Subject[\n  match(design_counts$Plate, plate_subject_map$Plate)\n]\ndesign_counts$PlateSubject <- factor(\n  paste(\n    design_counts$Plate,\n    design_counts$Subject,\n    sep = \" · \"\n  ),\n  levels = rev(\n    paste(\n      plate_subject_map$Plate,\n      plate_subject_map$Subject,\n      sep = \" · \"\n    )\n  )\n)\nhead(design_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Plate    Habitat Samples      Subject           PlateSubject\n1 Plate 1 Cheek left      15 Subject 1104 Plate 1 · Subject 1104\n2 Plate 2 Cheek left      10 Subject 1104 Plate 2 · Subject 1104\n3 Plate 3 Cheek left      16 Subject 1101 Plate 3 · Subject 1101\n4 Plate 4 Cheek left      16 Subject 1102 Plate 4 · Subject 1102\n5 Plate 5 Cheek left      16 Subject 1102 Plate 5 · Subject 1102\n6 Plate 6 Cheek left      16 Subject 1101 Plate 6 · Subject 1101\n```\n\n\n:::\n:::\n\n\n每块板都覆盖全部 7 个 habitat，单格 7–18 个样本；每位 subject 分布在两块板上。因而 habitat 与 plate 是交叉的，但 plate 嵌套在 subject 内。后续模型按 `Habitat + Subject + Plate` 的顺序估计：`Plate` 项表示控制 habitat 和 subject 后剩余的 subject 内板间差异。\n\n### 4. 同时检查 Bray-Curtis 与 Aitchison 距离\n\nBray-Curtis 使用污染过滤后的相对丰度。Aitchison 距离先保留至少 5% 生物样本中检出的 ASV，再加 0.5 pseudocount 做 centered log-ratio（CLR）：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelative_abundance <- sweep(\n  otutab_bio,\n  2,\n  colSums(otutab_bio),\n  \"/\"\n)\nbray_distance <- vegan::vegdist(\n  t(relative_abundance),\n  method = \"bray\"\n)\n\nfeature_prevalence <- rowMeans(otutab_bio > 0)\nclr_feature_ids <- names(feature_prevalence)[\n  feature_prevalence >= 0.05\n]\nclr_counts <- otutab_bio[\n  clr_feature_ids,\n  ,\n  drop = FALSE\n]\n\nclr_matrix <- t(\n  apply(\n    t(clr_counts) + 0.5,\n    1,\n    function(x) {\n      log(x) - mean(log(x))\n    }\n  )\n)\nrownames(clr_matrix) <- colnames(clr_counts)\ncolnames(clr_matrix) <- rownames(clr_counts)\n\nstopifnot(\n  nrow(clr_matrix) == nrow(metadata_bio),\n  max(abs(rowSums(clr_matrix))) < 1e-10\n)\n\naitchison_distance <- stats::dist(clr_matrix)\ndim(clr_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 539 234\n```\n\n\n:::\n:::\n\n\n这里进入 CLR 诊断的有 234 个 ASV。pseudocount 是零值处理假设，不是“恢复真实绝对丰度”；因此 Bray-Curtis 与 Aitchison 结果都报告，避免把单一变换当成唯一真相。\n\n### 5. PERMANOVA 报告 $R^2$，并限制置换范围\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_permanova <- function(distance_object) {\n  set.seed(20260719)\n  vegan::adonis2(\n    distance_object ~ Habitat + Subject + Plate,\n    data = metadata_bio,\n    permutations = 999,\n    by = \"terms\",\n    strata = metadata_bio$Subject\n  )\n}\n\nextract_permanova <- function(model, metric) {\n  term_names <- c(\"Habitat\", \"Subject\", \"Plate\")\n  data.frame(\n    Metric = metric,\n    Test = \"PERMANOVA\",\n    Term = term_names,\n    Df = model[term_names, \"Df\"],\n    R2 = model[term_names, \"R2\"],\n    F = model[term_names, \"F\"],\n    P = model[term_names, \"Pr(>F)\"],\n    row.names = NULL\n  )\n}\n\nbray_permanova <- run_permanova(bray_distance)\naitchison_permanova <- run_permanova(\n  aitchison_distance\n)\n\ncommunity_terms <- rbind(\n  extract_permanova(\n    bray_permanova,\n    \"Bray-Curtis\"\n  ),\n  extract_permanova(\n    aitchison_permanova,\n    \"Aitchison\"\n  )\n)\ncommunity_terms\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Metric      Test    Term Df          R2         F     P\n1 Bray-Curtis PERMANOVA Habitat  6 0.331658368 56.604034 0.001\n2 Bray-Curtis PERMANOVA Subject  2 0.145446194 74.469775 0.001\n3 Bray-Curtis PERMANOVA   Plate  3 0.008256147  2.818148 0.002\n4   Aitchison PERMANOVA Habitat  6 0.154092222 21.782307 0.001\n5   Aitchison PERMANOVA Subject  2 0.211732108 89.790652 0.001\n6   Aitchison PERMANOVA   Plate  3 0.012825795  3.626080 0.001\n```\n\n\n:::\n:::\n\n\nBray-Curtis 下，habitat、subject 和 plate 分别解释 33.2%、14.5% 和 0.83%。Aitchison 下对应为 15.4%、21.2% 和 1.28%。\n\nplate 项在两种距离下都达到置换显著，但解释率只有约 1%。这正说明“大样本 $P$ 值很小”不等于“batch 主导整个数据”。\n\n### 6. PERMANOVA 必须配 dispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_dispersion <- function(distance_object, metric) {\n  dispersion <- vegan::betadisper(\n    distance_object,\n    metadata_bio$Plate,\n    bias.adjust = TRUE\n  )\n  set.seed(20260719)\n  test <- vegan::permutest(\n    dispersion,\n    permutations = 999\n  )\n  data.frame(\n    Metric = metric,\n    Test = \"PERMDISP\",\n    Term = \"Plate dispersion\",\n    Df = unname(test$tab[1, \"Df\"]),\n    R2 = NA_real_,\n    F = unname(test$tab[1, \"F\"]),\n    P = unname(test$tab[1, \"Pr(>F)\"])\n  )\n}\n\ndispersion_results <- rbind(\n  run_dispersion(\n    bray_distance,\n    \"Bray-Curtis\"\n  ),\n  run_dispersion(\n    aitchison_distance,\n    \"Aitchison\"\n  )\n)\ndispersion_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Metric     Test             Term Df R2         F     P\n1 Bray-Curtis PERMDISP Plate dispersion  5 NA 0.3058414 0.903\n2   Aitchison PERMDISP Plate dispersion  5 NA 5.6389361 0.001\n```\n\n\n:::\n\n```{.r .cell-code}\ncommunity_diagnostics <- rbind(\n  community_terms,\n  dispersion_results\n)\n```\n:::\n\n\nBray-Curtis 的 plate dispersion $P=0.903$，Aitchison 的 $P=0.001$。因此 Aitchison 下的 plate PERMANOVA 既可能包含 centroid shift，也受到组内离散度差异影响，不能只解释为板间均值位移。\n\n### 7. feature-wise 模型：做 FDR，也报告解释率\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_feature_model <- function(y) {\n  fit <- stats::lm(\n    y ~ Habitat + Subject + Plate,\n    data = metadata_bio\n  )\n  tab <- stats::anova(fit)\n  total_ss <- sum(tab[, \"Sum Sq\"])\n  c(\n    HabitatP = tab[\"Habitat\", \"Pr(>F)\"],\n    HabitatR2 = tab[\"Habitat\", \"Sum Sq\"] / total_ss,\n    SubjectP = tab[\"Subject\", \"Pr(>F)\"],\n    SubjectR2 = tab[\"Subject\", \"Sum Sq\"] / total_ss,\n    PlateP = tab[\"Plate\", \"Pr(>F)\"],\n    PlateR2 = tab[\"Plate\", \"Sum Sq\"] / total_ss\n  )\n}\n\nfeature_model_matrix <- t(\n  apply(\n    clr_matrix,\n    2,\n    fit_feature_model\n  )\n)\nfeature_model_table <- as.data.frame(\n  feature_model_matrix\n)\nfeature_model_table <- feature_model_table[\n  colnames(clr_matrix),\n  ,\n  drop = FALSE\n]\nfeature_model_table$HabitatQ <- stats::p.adjust(\n  feature_model_table$HabitatP,\n  method = \"BH\"\n)\nfeature_model_table$PlateQ <- stats::p.adjust(\n  feature_model_table$PlateP,\n  method = \"BH\"\n)\n\nfeature_diagnostics <- data.frame(\n  FeatureID = colnames(clr_matrix),\n  taxonomy_bio[\n    colnames(clr_matrix),\n    ,\n    drop = FALSE\n  ],\n  Prevalence = feature_prevalence[\n    colnames(clr_matrix)\n  ],\n  TotalReads = rowSums(\n    otutab_bio[\n      colnames(clr_matrix),\n      ,\n      drop = FALSE\n    ]\n  ),\n  feature_model_table,\n  check.names = FALSE,\n  row.names = NULL\n)\n\nfeature_summary <- data.frame(\n  TestedASVs = nrow(feature_diagnostics),\n  HabitatFDR05 = sum(\n    feature_diagnostics$HabitatQ < 0.05\n  ),\n  PlateFDR05 = sum(\n    feature_diagnostics$PlateQ < 0.05\n  ),\n  MedianHabitatR2 = stats::median(\n    feature_diagnostics$HabitatR2\n  ),\n  MedianPlateR2 = stats::median(\n    feature_diagnostics$PlateR2\n  )\n)\nfeature_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  TestedASVs HabitatFDR05 PlateFDR05 MedianHabitatR2 MedianPlateR2\n1        234          227         89       0.1029612   0.009137755\n```\n\n\n:::\n:::\n\n\n在 234 个高检出 ASV 中，89 个的 plate 项达到 BH FDR < 0.05，227 个的 habitat 项达到 FDR < 0.05。median plate $R^2$ 为 0.91%，明显低于 median habitat $R^2$ 的 10.3%；但少数 feature 的 plate $R^2$ 很大，不能用群落总体的 1% 替代 feature 审计。\n\n本对象没有完整的纵向时间与采样事件字段，因此这里的 feature 模型是 batch diagnostic，不用于宣称总体人群中的口腔部位差异。真实重复测量研究应加入 time/visit，并按 subject 使用 mixed model 或其他相关结构。\n\n### 8. leave-one-plate-out：结论是否被某块板推动\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleave_one_plate_out <- do.call(\n  rbind,\n  lapply(\n    levels(metadata_bio$Plate),\n    function(dropped_plate) {\n      keep_samples <- (\n        metadata_bio$Plate != dropped_plate\n      )\n      metadata_subset <- droplevels(\n        metadata_bio[\n          keep_samples,\n          ,\n          drop = FALSE\n        ]\n      )\n      model <- vegan::adonis2(\n        stats::dist(\n          clr_matrix[\n            keep_samples,\n            ,\n            drop = FALSE\n          ]\n        ) ~ Habitat + Subject + Plate,\n        data = metadata_subset,\n        permutations = 0,\n        by = \"terms\"\n      )\n      data.frame(\n        DroppedPlate = dropped_plate,\n        Samples = sum(keep_samples),\n        HabitatR2 = model[\"Habitat\", \"R2\"],\n        SubjectR2 = model[\"Subject\", \"R2\"],\n        PlateR2 = model[\"Plate\", \"R2\"]\n      )\n    }\n  )\n)\nleave_one_plate_out\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  DroppedPlate Samples HabitatR2 SubjectR2     PlateR2\n1      Plate 1     448 0.1737826 0.1871002 0.010784273\n2      Plate 2     449 0.1755791 0.1976209 0.010664454\n3      Plate 3     450 0.1591675 0.2033370 0.011520525\n4      Plate 4     449 0.1535751 0.2282777 0.008605357\n5      Plate 5     450 0.1615562 0.2177663 0.008477921\n6      Plate 6     449 0.1545828 0.2051161 0.011658159\n```\n\n\n:::\n:::\n\n\n删去任一板后，Aitchison habitat $R^2$ 保持在 15.4%–17.6%，plate $R^2$ 保持在 0.85%–1.17%。这比只报告全数据的一次 $P$ 值更能说明结果不是由某一块板单独推动。\n\n### 9. 设计感知的 adjustment 只用于诊断\n\n因为每位 subject 恰好分布在两块板上，可以为每位 subject 构造一个板间对比：该 subject 的两块板分别记为 $-0.5$ 和 $+0.5$，其他 subject 记为 0。模型先保留 habitat 与 subject，再估计三个 subject 内 plate contrast：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_biology <- stats::model.matrix(\n  ~ Habitat + Subject,\n  data = metadata_bio\n)\n\nsubject_levels <- levels(metadata_bio$Subject)\nplate_contrasts <- sapply(\n  subject_levels,\n  function(subject_level) {\n    subject_plates <- sort(\n      unique(\n        as.character(\n          metadata_bio$Plate[\n            metadata_bio$Subject == subject_level\n          ]\n        )\n      )\n    )\n    stopifnot(length(subject_plates) == 2)\n    ifelse(\n      metadata_bio$Subject == subject_level &\n        metadata_bio$Plate == subject_plates[1],\n      -0.5,\n      ifelse(\n        metadata_bio$Subject == subject_level &\n          metadata_bio$Plate == subject_plates[2],\n        0.5,\n        0\n      )\n    )\n  }\n)\ncolnames(plate_contrasts) <- paste0(\n  \"Within_\",\n  gsub(\" \", \"_\", subject_levels)\n)\n\nx_full <- cbind(\n  x_biology,\n  plate_contrasts\n)\nstopifnot(qr(x_full)$rank == ncol(x_full))\n\nall_coefficients <- qr.coef(\n  qr(x_full),\n  clr_matrix\n)\nbatch_rows <- (\n  ncol(x_biology) + 1\n):ncol(x_full)\nbatch_coefficients <- all_coefficients[\n  batch_rows,\n  ,\n  drop = FALSE\n]\n\nclr_adjusted_diagnostic <- (\n  clr_matrix -\n    plate_contrasts %*% batch_coefficients\n)\n\nadjustment_coefficients <- data.frame(\n  FeatureID = colnames(clr_matrix),\n  t(batch_coefficients),\n  check.names = FALSE,\n  row.names = NULL\n)\nhead(adjustment_coefficients)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  FeatureID Within_Subject_1101 Within_Subject_1102 Within_Subject_1104\n1      Seq1         0.019369842         -0.18737604          0.09790848\n2      Seq2         0.149241680         -0.20890674         -0.24005929\n3      Seq4        -0.074662655         -0.52025310         -0.82230694\n4      Seq5        -0.288988968         -0.27631239          0.63444291\n5      Seq6         0.004305498          0.01647426          0.06487136\n6      Seq7         0.165869770          0.77274424          0.13103499\n```\n\n\n:::\n:::\n\n\n用相同公式重新计算 Aitchison PERMANOVA：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadjusted_aitchison <- stats::dist(\n  clr_adjusted_diagnostic\n)\nadjusted_permanova <- run_permanova(\n  adjusted_aitchison\n)\nadjusted_terms <- extract_permanova(\n  adjusted_permanova,\n  \"Aitchison after diagnostic adjustment\"\n)\n\nadjustment_diagnostic <- rbind(\n  transform(\n    community_terms[\n      community_terms$Metric == \"Aitchison\",\n      ,\n      drop = FALSE\n    ],\n    Stage = \"Before adjustment\"\n  ),\n  transform(\n    adjusted_terms,\n    Stage = \"After adjustment\"\n  )\n)\nadjustment_diagnostic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                 Metric      Test    Term Df         R2\n4                             Aitchison PERMANOVA Habitat  6 0.15409222\n5                             Aitchison PERMANOVA Subject  2 0.21173211\n6                             Aitchison PERMANOVA   Plate  3 0.01282579\n1 Aitchison after diagnostic adjustment PERMANOVA Habitat  6 0.15656874\n2 Aitchison after diagnostic adjustment PERMANOVA Subject  2 0.21432836\n3 Aitchison after diagnostic adjustment PERMANOVA   Plate  3 0.00000000\n         F     P             Stage\n4 21.78231 0.001 Before adjustment\n5 89.79065 0.001 Before adjustment\n6  3.62608 0.001 Before adjustment\n1 21.85963 0.001  After adjustment\n2 89.77152 0.001  After adjustment\n3  0.00000 1.000  After adjustment\n```\n\n\n:::\n:::\n\n\nplate $R^2$ 从 1.28% 变为 0.00%。后者为 0 是这一步在**同一数据上按定义减去 plate contrast** 的代数结果，不是外部验证，更不证明所有技术偏差已经消失。\n\n下面只为可视化检查，在保留/调整后的 CLR 中进一步回归掉 habitat 与 subject，并把两组 residual 投影到同一个 PCA 基底：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresidualize_biology <- function(x) {\n  stats::lm.fit(\n    x = x_biology,\n    y = x\n  )$residuals\n}\n\nresidual_before <- residualize_biology(\n  clr_matrix\n)\nresidual_after <- residualize_biology(\n  clr_adjusted_diagnostic\n)\n\npca_reference <- stats::prcomp(\n  residual_before,\n  center = TRUE,\n  scale. = FALSE\n)\nscores_before <- pca_reference$x[, 1:2]\nscores_after <- (\n  scale(\n    residual_after,\n    center = pca_reference$center,\n    scale = FALSE\n  ) %*%\n    pca_reference$rotation[, 1:2]\n)\n\npca_variance <- (\n  pca_reference$sdev^2 /\n    sum(pca_reference$sdev^2)\n)\n\nordination_scores <- rbind(\n  data.frame(\n    SampleID = rownames(metadata_bio),\n    Stage = \"Before adjustment\",\n    PC1 = scores_before[, 1],\n    PC2 = scores_before[, 2],\n    Plate = metadata_bio$Plate,\n    Subject = metadata_bio$Subject\n  ),\n  data.frame(\n    SampleID = rownames(metadata_bio),\n    Stage = \"After adjustment\",\n    PC1 = scores_after[, 1],\n    PC2 = scores_after[, 2],\n    Plate = metadata_bio$Plate,\n    Subject = metadata_bio$Subject\n  )\n)\nordination_scores$Stage <- factor(\n  ordination_scores$Stage,\n  levels = c(\n    \"Before adjustment\",\n    \"After adjustment\"\n  )\n)\n\nordination_centroids <- aggregate(\n  cbind(PC1, PC2) ~ Stage + Plate,\n  data = ordination_scores,\n  FUN = mean\n)\nhead(ordination_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     SampleID             Stage        PC1       PC2   Plate\nP1101C01701R00 P1101C01701R00 Before adjustment -6.4837762 -4.496292 Plate 3\nP1101C01702R00 P1101C01702R00 Before adjustment  7.1004751  8.279408 Plate 3\nP1101C01703R00 P1101C01703R00 Before adjustment  2.5507966  4.471334 Plate 3\nP1101C08701R00 P1101C08701R00 Before adjustment -7.0804482 -6.741230 Plate 3\nP1101C08702R00 P1101C08702R00 Before adjustment  0.1276878  4.982415 Plate 3\nP1101C08703R00 P1101C08703R00 Before adjustment  6.1188412  8.573459 Plate 3\n                    Subject\nP1101C01701R00 Subject 1101\nP1101C01702R00 Subject 1101\nP1101C01703R00 Subject 1101\nP1101C08701R00 Subject 1101\nP1101C08702R00 Subject 1101\nP1101C08703R00 Subject 1101\n```\n\n\n:::\n:::\n\n\n### 10. 导出完整审计轨迹\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_dir <- \"results/05-batch\"\ndir.create(\n  result_dir,\n  recursive = TRUE,\n  showWarnings = FALSE\n)\n\nwrite_result <- function(x, filename) {\n  utils::write.table(\n    x,\n    file.path(result_dir, filename),\n    sep = \"\\t\",\n    quote = FALSE,\n    row.names = FALSE,\n    na = \"\"\n  )\n}\n\nwrite_result(\n  design_counts,\n  \"batch-design-counts.tsv\"\n)\nwrite_result(\n  community_diagnostics,\n  \"community-batch-diagnostics.tsv\"\n)\nwrite_result(\n  feature_diagnostics,\n  \"feature-batch-diagnostics.tsv\"\n)\nwrite_result(\n  leave_one_plate_out,\n  \"leave-one-plate-out.tsv\"\n)\nwrite_result(\n  adjustment_diagnostic,\n  \"adjustment-diagnostic.tsv\"\n)\nwrite_result(\n  adjustment_coefficients,\n  \"plate-adjustment-coefficients.tsv\"\n)\nwrite_result(\n  ordination_scores,\n  \"ordination-scores.tsv\"\n)\n```\n:::\n\n\n这些文件分别回答“设计是否交叉”“群落层 batch 多大”“哪些 ASV 受影响”“删去哪一板是否改变结论”“诊断性 adjustment 做了什么”。不要只保存一张校正后 PCA；没有原始输入、模型矩阵和系数的校正结果不可审计。\n\n## 出版级美化 {#sec-polish}\n\n### 1. Batch × habitat 设计热图\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_batch_design <- ggplot(\n  design_counts,\n  aes(\n    Habitat,\n    PlateSubject,\n    fill = Samples\n  )\n) +\n  geom_tile(\n    color = \"white\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    aes(label = Samples),\n    color = \"black\",\n    size = 3.5,\n    fontface = \"bold\"\n  ) +\n  scale_fill_gradient(\n    low = \"#EAF4FA\",\n    high = \"#0072B2\",\n    limits = range(design_counts$Samples),\n    name = \"Samples\"\n  ) +\n  labs(\n    title = \"Every plate covers all seven oral habitats\",\n    subtitle = paste0(\n      \"Plate is nested within subject · \",\n      nrow(metadata_bio),\n      \" biological samples · 6 plates\"\n    ),\n    x = \"Oral habitat\",\n    y = \"Technical plate · biological subject\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 12\n    ),\n    plot.subtitle = element_text(\n      color = \"grey35\"\n    ),\n    axis.text.x = element_text(\n      angle = 32,\n      hjust = 1\n    ),\n    axis.title = element_text(face = \"bold\"),\n    legend.position = \"right\"\n  )\n\np_batch_design\n```\n\n::: {.cell-output-display}\n![](05-batch-effects_files/figure-html/unnamed-chunk-16-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_batch_design,\n  \"figures/05-batch-design-audit\",\n  width = 180,\n  height = 115\n)\n```\n:::\n\n\n### 2. 群落层解释率\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunity_plot_data <- community_terms\ncommunity_plot_data$Term <- factor(\n  community_plot_data$Term,\n  levels = c(\"Plate\", \"Subject\", \"Habitat\")\n)\n\np_community_batch <- ggplot(\n  community_plot_data,\n  aes(\n    R2,\n    Term,\n    fill = Metric\n  )\n) +\n  geom_col(\n    position = position_dodge(width = 0.72),\n    width = 0.64,\n    color = \"white\",\n    linewidth = 0.25\n  ) +\n  geom_text(\n    aes(\n      label = scales::percent(\n        R2,\n        accuracy = 0.1\n      )\n    ),\n    position = position_dodge(width = 0.72),\n    hjust = -0.12,\n    size = 3.5,\n    fontface = \"bold\"\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"Bray-Curtis\" = \"#0072B2\",\n      \"Aitchison\" = \"#D55E00\"\n    ),\n    name = \"Distance\"\n  ) +\n  scale_x_continuous(\n    labels = scales::percent_format(accuracy = 1),\n    limits = c(0, 0.37),\n    expand = expansion(mult = c(0, 0))\n  ) +\n  labs(\n    title = \"Plate is detectable but explains little community variation\",\n    subtitle = \"Sequential PERMANOVA · permutations blocked within subject\",\n    x = \"Variance explained (R²)\",\n    y = NULL\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 12\n    ),\n    plot.subtitle = element_text(\n      color = \"grey35\"\n    ),\n    axis.title.x = element_text(face = \"bold\"),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\")\n  )\n\np_community_batch\n```\n\n::: {.cell-output-display}\n![](05-batch-effects_files/figure-html/unnamed-chunk-17-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_community_batch,\n  \"figures/05-community-batch-effects\",\n  width = 180,\n  height = 115\n)\n```\n:::\n\n\n### 3. Feature 层 effect-size landscape\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_diagnostics$PlateStatus <- factor(\n  ifelse(\n    feature_diagnostics$PlateQ < 0.05,\n    \"Plate FDR < 0.05\",\n    \"Not plate-associated\"\n  ),\n  levels = c(\n    \"Not plate-associated\",\n    \"Plate FDR < 0.05\"\n  )\n)\n\nlabel_feature_ids <- head(\n  feature_diagnostics$FeatureID[\n    order(feature_diagnostics$PlateQ)\n  ],\n  3\n)\nfeature_labels <- feature_diagnostics[\n  feature_diagnostics$FeatureID %in%\n    label_feature_ids,\n  ,\n  drop = FALSE\n]\nfeature_labels$LabelHjust <- ifelse(\n  feature_labels$PlateR2 > 0.15,\n  1.08,\n  -0.08\n)\n\np_feature_batch <- ggplot(\n  feature_diagnostics,\n  aes(\n    PlateR2,\n    HabitatR2,\n    color = PlateStatus\n  )\n) +\n  geom_abline(\n    slope = 1,\n    intercept = 0,\n    linetype = 2,\n    linewidth = 0.5,\n    color = \"grey55\"\n  ) +\n  geom_point(\n    size = 2.2,\n    alpha = 0.72\n  ) +\n  geom_text(\n    data = feature_labels,\n    aes(\n      label = FeatureID,\n      hjust = LabelHjust\n    ),\n    nudge_y = 0.012,\n    color = \"black\",\n    size = 3.2,\n    check_overlap = TRUE,\n    show.legend = FALSE\n  ) +\n  scale_color_manual(\n    values = c(\n      \"Not plate-associated\" = \"#B8B8B8\",\n      \"Plate FDR < 0.05\" = \"#D55E00\"\n    ),\n    name = NULL\n  ) +\n  scale_x_continuous(\n    labels = scales::percent_format(accuracy = 1),\n    limits = c(0, 0.21),\n    expand = expansion(mult = c(0, 0.01))\n  ) +\n  scale_y_continuous(\n    labels = scales::percent_format(accuracy = 1),\n    limits = c(0, 0.45),\n    expand = expansion(mult = c(0, 0.01))\n  ) +\n  coord_fixed(ratio = 0.21 / 0.45) +\n  labs(\n    title = \"Batch effects concentrate in a subset of ASVs\",\n    subtitle = paste0(\n      feature_summary$PlateFDR05,\n      \" of \",\n      feature_summary$TestedASVs,\n      \" ASVs associated with plate after BH correction\"\n    ),\n    x = \"Plate variance explained\",\n    y = \"Habitat variance explained\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 12\n    ),\n    plot.subtitle = element_text(\n      color = \"grey35\"\n    ),\n    axis.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\"\n  )\n\np_feature_batch\n```\n\n::: {.cell-output-display}\n![](05-batch-effects_files/figure-html/unnamed-chunk-18-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_feature_batch,\n  \"figures/05-feature-batch-effects\",\n  width = 165,\n  height = 135\n)\n```\n:::\n\n\n### 4. Adjustment 前后诊断图\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplate_colors <- setNames(\n  pal_pub[1:6],\n  levels(metadata_bio$Plate)\n)\n\np_adjustment <- ggplot(\n  ordination_scores,\n  aes(\n    PC1,\n    PC2,\n    color = Plate\n  )\n) +\n  geom_point(\n    size = 1.25,\n    alpha = 0.45\n  ) +\n  stat_ellipse(\n    level = 0.68,\n    linewidth = 0.55,\n    alpha = 0.75\n  ) +\n  geom_point(\n    data = ordination_centroids,\n    shape = 4,\n    size = 3.2,\n    stroke = 1.1,\n    show.legend = FALSE\n  ) +\n  facet_wrap(\n    ~ Stage,\n    nrow = 1\n  ) +\n  scale_color_manual(\n    values = plate_colors\n  ) +\n  labs(\n    title = \"Design-aware residualization removes within-subject plate means\",\n    subtitle = \"Diagnostic only: habitat and subject were preserved in the design matrix\",\n    x = paste0(\n      \"Residual PC1 (\",\n      scales::percent(\n        pca_variance[1],\n        accuracy = 0.1\n      ),\n      \")\"\n    ),\n    y = paste0(\n      \"Residual PC2 (\",\n      scales::percent(\n        pca_variance[2],\n        accuracy = 0.1\n      ),\n      \")\"\n    ),\n    color = \"Plate\"\n  ) +\n  theme_pub(base_size = 10.5) +\n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 12\n    ),\n    plot.subtitle = element_text(\n      color = \"grey35\"\n    ),\n    strip.text = element_text(face = \"bold\"),\n    axis.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\")\n  )\n\np_adjustment\n```\n\n::: {.cell-output-display}\n![](05-batch-effects_files/figure-html/unnamed-chunk-19-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_adjustment,\n  \"figures/05-adjustment-diagnostic\",\n  width = 200,\n  height = 115\n)\n```\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"1. Group 与 batch 完全混杂，还想靠软件救回来\"}\n先画 `table(Batch, Group)` 并检查 `qr(model.matrix(~ Group + Batch))$rank`。不满秩时，应补测桥接样本、缩小到批次内比较或明确承认不可识别；不要把校正后分组消失当作“批次去得很干净”。\n:::\n\n::: {.callout-caution title=\"2. 把 subject、cage、site 全部当技术噪声删除\"}\n这些变量可能是真实生物层级。优先在 mixed model、stratified permutation 或分层 meta-analysis 中控制相关性，而不是直接从整个 feature table 中抹去它们。\n:::\n\n::: {.callout-caution title=\"3. 只看 PCA/PCoA 是否按 batch 聚类\"}\n前两个轴没有分离不能排除 feature、零比例、方差或高阶分布上的批次。至少补充设计表、PERMANOVA $R^2$、dispersion、feature-wise FDR 和 sensitivity analysis。\n:::\n\n::: {.callout-caution title=\"4. 只报 P 值，不报 batch R²\"}\n本例 plate 在两种距离下都显著，但仅解释约 1% 的群落差异。大样本容易让很小的偏差显著；审稿人需要知道它是否足以改变主要生物结论。\n:::\n\n::: {.callout-caution title=\"5. PERMANOVA 显著就断言 centroid shift\"}\nAitchison 下 plate dispersion 也显著。位置与离散度可能共同贡献 PERMANOVA，因此必须配套 `betadisper()` / `permutest()`，并检查不同距离是否给出一致故事。\n:::\n\n::: {.callout-caution title=\"6. 先校正全数据，再随机分训练集和测试集\"}\n校正模型已经看到测试集的 batch 与生物分布，会产生信息泄漏。预测任务应在每个训练折内估计预处理/校正参数，再应用到验证折；更严格的是按 batch 或 study 做外部验证。\n:::\n\n::: {.callout-caution title=\"7. 把通用 ComBat 直接套到相对丰度\"}\n微生物组具有零膨胀、过度离散和成分性。方法必须匹配输入尺度和研究目的；需要生成校正后的 count/profile 时，评估 ConQuR、MMUPHin 等专门方法，并核对其设计假设。\n:::\n\n::: {.callout-caution title=\"8. 认为 rarefaction、TSS 或 CLR 已经校正 batch\"}\n这些步骤改变测序深度或数据几何，不会自动消除 kit lot、plate、run 或 center 的系统差异。normalization 与 batch handling 是两个问题。\n:::\n\n::: {.callout-caution title=\"9. 只展示校正后图，不展示校正前图和系数\"}\n至少保存原始三件套、设计矩阵、方法版本、保留变量、校正参数、前后图和关键生物效应。否则无法判断是去除了技术差异，还是删掉了真实信号。\n:::\n\n::: {.callout-caution title=\"10. 忽略污染与 batch 的联动\"}\n某一提取板的 blank burden、kitome 或串样异常会表现为 batch effect。应先完成对照与污染审计，再判断剩余板间结构；低生物量项目尤其不能跳过这一步。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n可直接修改的英文模板：\n\n> **Batch design, diagnostics, and sensitivity analysis.** Samples were randomized across [extraction/PCR/sequencing] batches while balancing [primary biological variables], and [number] negative plus [number] positive controls were included per batch. Batch metadata included [variables]. The batch-by-exposure design was inspected before analysis, and model-matrix rank was verified. After contaminant filtering, community structure was evaluated using [distances/transformations]. PERMANOVA models included [biological covariates] followed by [batch terms], with permutations restricted within [subject/site/block]; multivariate dispersion was assessed separately. Feature-wise [model] included batch as [fixed/random] effect, and P values were adjusted by the Benjamini-Hochberg method. The primary inference used unadjusted counts with batch represented in each statistical model. A batch-adjusted profile generated by [method, version, covariates preserved] was used only for [visualization/prediction] and was audited before and after adjustment. Robustness was assessed by [leave-one-batch-out/within-batch/meta-analysis] sensitivity analyses.\n\n本例的可复现实写：\n\n> **Worked batch diagnostic.** The dataset comprised 539 biological oral samples from three subjects, seven oral habitats, and six technical plates after 56 candidate contaminant ASVs were removed with `decontam` 1.24.0. Each subject was represented on two plates, and every plate contained all seven habitats. Bray-Curtis distances were calculated from relative abundance; Aitchison distances were calculated from 234 ASVs detected in at least 5% of biological samples after adding a 0.5 pseudocount and applying the centered log-ratio transformation. Sequential PERMANOVA models included habitat, subject, and plate, with 999 permutations restricted within subject; plate dispersion was tested separately. Plate explained 0.83% of Bray-Curtis and 1.28% of Aitchison variation. Feature-wise CLR models identified 89 / 234 ASVs with a plate term at BH FDR < 0.05. Leave-one-plate-out analyses retained habitat Aitchison R² values between 15.4% and 17.6%. A design-matrix residualization preserving habitat and subject was used only as a visualization diagnostic, not as the input for biological inference.\n\nResults 中应同时给出：\n\n- 各组在 batch 中的样本数与缺失组合；\n- batch 与主要协变量能否在设计矩阵中区分；\n- 距离、变换、模型项顺序和 permutation block；\n- batch 的 $R^2$、$P$ 值与 dispersion；\n- feature-wise FDR 数量和 effect-size 分布；\n- 校正前后生物效应与批次效应；\n- leave-one-batch-out、within-batch 或外部验证结果。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. metadata 至少要有这些列\n\n| 列名 | 类型 | 用途 |\n|---|---|---|\n| `Group` | factor | 主要暴露/处理/病例状态 |\n| `Batch` | factor | 提取板、PCR plate 或 sequencing run |\n| `SubjectID` / `PlotID` | factor | 独立实验单位与重复测量 |\n| `Site` / `Center` | factor | 多中心或空间 block |\n| `CollectionDate` | date/factor | 时间和季节 |\n| `KitLot` | factor | 试剂批号 |\n| `IsNegative` | logical | 阴性对照 |\n| `LibrarySize` / `DNAConcentration` | numeric | QC 与低生物量诊断 |\n\n不要把多个来源都压成一个含义模糊的 `batch1/batch2`。提取板、PCR plate、测序 run 和研究中心可能需要分别建模。\n\n### 2. 先做可识别性检查\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"your_data/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"your_data/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"your_data/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata))\n)\n\ndesign_table <- with(\n  metadata,\n  table(Batch, Group)\n)\nprint(design_table)\n\nx <- model.matrix(\n  ~ Group + SubjectID + Batch,\n  data = metadata\n)\nif (qr(x)$rank < ncol(x)) {\n  stop(\n    paste(\n      \"Group and batch are not identifiable.\",\n      \"Add bridge samples or restrict the question.\"\n    )\n  )\n}\n```\n:::\n\n\n设计平衡不要求每格完全相等，但主要生物水平必须在足够多的 batch 中重复出现。批次只有 1–2 个水平时，也很难把它当作可推广的随机效应。\n\n### 3. 默认在统计模型中加入 batch\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelative_abundance <- sweep(\n  otutab,\n  2,\n  colSums(otutab),\n  \"/\"\n)\ndistance <- vegan::vegdist(\n  t(relative_abundance),\n  method = \"bray\"\n)\n\nset.seed(20260719)\npermanova <- vegan::adonis2(\n  distance ~ Group + Age + Sex + Batch,\n  data = metadata,\n  permutations = 999,\n  by = \"margin\",\n  strata = metadata$SubjectID\n)\npermanova\n\ndispersion <- vegan::betadisper(\n  distance,\n  metadata$Batch,\n  bias.adjust = TRUE\n)\nset.seed(20260719)\nvegan::permutest(\n  dispersion,\n  permutations = 999\n)\n```\n:::\n\n\n差异丰度、alpha diversity、纵向模型和预测模型都应在各自方法中处理 batch；不要因为生成过一次“校正表”就从所有下游模型中删除 batch。\n\n### 4. 什么时候考虑生成校正后的 profile\n\n| 场景 | 可考虑的方法 | 必须检查 |\n|---|---|---|\n| 多队列 case-control 且每队列都有 control | percentile normalization / meta-analysis | control 定义一致、每批 control 足够 |\n| 零膨胀 count profile，需要通用下游 | ConQuR / ConQuR-libsize | key covariates 保留、训练/验证隔离 |\n| 多队列 abundance 与 meta-analysis | MMUPHin | batch 与 covariates、零膨胀、cohort heterogeneity |\n| 重复测量/中心/笼位 | mixed model / stratified analysis | 实验单位、随机效应水平数 |\n| 完全混杂 | 不做 profile correction | bridge samples、补实验或缩小问题 |\n\n若使用 MMUPHin，最小调用形式如下；它是可选扩展，不是本篇主分析的复现必需项：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBiocManager::install(\n  \"MMUPHin\",\n  ask = FALSE,\n  update = FALSE\n)\n\nrelative_abundance <- sweep(\n  otutab,\n  2,\n  colSums(otutab),\n  \"/\"\n)\n\nmmuphin_fit <- MMUPHin::adjust_batch(\n  feature_abd = relative_abundance,\n  batch = \"Batch\",\n  covariates = c(\"Group\", \"Age\", \"Sex\"),\n  data = metadata\n)\nabundance_adjusted <- (\n  mmuphin_fit$feature_abd_adj\n)\n```\n:::\n\n\n任何校正方法都要在原始设计、校正前后 batch effect、主要生物效应、稀疏度、library size、预测泛化和 leave-one-batch-out 结果之间做联合验收。目标不是让图“混在一起”，而是减少不需要的技术变异，同时保留可验证的生物信号。\n\n## 参考 {#sec-references}\n\n1. Wang Y, Lê Cao KA. Managing batch effects in microbiome data. *Briefings in Bioinformatics*. 2020;21(6):1954–1970. [doi:10.1093/bib/bbz105](https://doi.org/10.1093/bib/bbz105)\n2. Gibbons SM, Duvallet C, Alm EJ. Correcting for batch effects in case-control microbiome studies. *PLOS Computational Biology*. 2018;14(4):e1006102. [doi:10.1371/journal.pcbi.1006102](https://doi.org/10.1371/journal.pcbi.1006102)\n3. Ling W, Lu J, Zhao N, et al. Batch effects removal for microbiome data via conditional quantile regression. *Nature Communications*. 2022;13:5418. [doi:10.1038/s41467-022-33071-9](https://doi.org/10.1038/s41467-022-33071-9)\n4. Ma S, Shungin D, Mallick H, et al. Population structure discovery in meta-analyzed microbial communities and inflammatory bowel disease using MMUPHin. *Genome Biology*. 2022;23:208. [doi:10.1186/s13059-022-02753-4](https://doi.org/10.1186/s13059-022-02753-4)\n5. Gloor GB, Macklaim JM, Pawlowsky-Glahn V, Egozcue JJ. Microbiome datasets are compositional: and this is not optional. *Frontiers in Microbiology*. 2017;8:2224. [doi:10.3389/fmicb.2017.02224](https://doi.org/10.3389/fmicb.2017.02224)\n6. Anderson MJ. A new method for non-parametric multivariate analysis of variance. *Austral Ecology*. 2001;26(1):32–46. [doi:10.1111/j.1442-9993.2001.01070.pp.x](https://doi.org/10.1111/j.1442-9993.2001.01070.pp.x)\n7. Anderson MJ. Distance-based tests for homogeneity of multivariate dispersions. *Biometrics*. 2006;62(1):245–253. [doi:10.1111/j.1541-0420.2005.00440.x](https://doi.org/10.1111/j.1541-0420.2005.00440.x)\n8. Davis NM, Proctor DM, Holmes SP, Relman DA, Callahan BJ. Simple statistical identification and removal of contaminant sequences in marker-gene and metagenomics data. *Microbiome*. 2018;6:226. [doi:10.1186/s40168-018-0605-2](https://doi.org/10.1186/s40168-018-0605-2)\n",
    "supporting": [
      "05-batch-effects_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}