{
  "hash": "e551a104e50a2873823960c1712aca57",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 21 篇 · Beta 距离度量：Bray/Jaccard/UniFrac/Aitchison/Robust Aitchison（DEICODE）\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**在同一批真实 16S 样本上计算 Bray–Curtis、binary Jaccard、unweighted/weighted UniFrac、Aitchison 与 Robust Aitchison，明确每个距离测量什么、需要怎样标准化，以及零值和系统发育树怎样改变结果。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`；UniFrac 额外需要 `rooted-tree.nwk.gz`。  \n> **预计资源：**示例数据含 26 个样本、18,988 个非空 OTU、28,216,678 reads；R 距离计算与 gemelli RPCA 通常少于 1 分钟，峰值内存约 2 GB。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n微生物组论文中的 PCoA、NMDS、PERMANOVA、CAP 和距离热图，第一步都不是“画坐标”，而是定义样本间距离。常见目标图把每个样本画成一个点，用颜色区分病例、处理或生态环境；然而点的位置首先由距离度量决定。\n\n本例使用 `phyloseq` 1.48.0 分发的真实 `GlobalPatterns` 16S 数据。原始研究在不同人体部位、淡水、海洋、沉积物、土壤和 mock community 中进行深度测序，并用系统发育距离展示全球尺度的群落差异。[Caporaso et al. (2011)](https://doi.org/10.1073/pnas.1000080107)提供数据背景；这里从公开 OTU 表和 rooted tree 重新计算六种距离，绘制原创的距离相关图与六分面 PCoA。\n\n::: {.callout-important title=\"先给结论\"}\n同一批 26 个样本在六种距离几何中并不占据同样的位置。Jaccard 与 unweighted UniFrac 的 325 个样本对距离秩相关为 0.953，但前者不使用系统发育分支，不能据此称为同一方法；经典 Aitchison 与 Robust Aitchison 的相关为 0.800，说明零值处理会改变样本对的远近次序。weighted UniFrac 的 PCoA 有 3 个小负特征值，负/正特征值绝对和之比为 0.00455，因此只在该分支用 Lingoes 校正作图。\n:::\n\n本页不根据哪个距离“最能把组分开”来挑主结果，也不进行组间显著性检验。距离应由研究问题预先决定；PERMANOVA 与 dispersion test 是后续推断步骤。\n\n## 理论：距离不是画图选项，而是测量定义 {#sec-theory}\n\n先用一张表锁定六种度量的解释边界：\n\n| 距离 | 主要信息 | 是否需要树 | 零值处理 | 本例标准化 |\n|---|---|---:|---|---|\n| Bray–Curtis | feature 丰度差异 | 否 | 零可直接存在 | 50,000 reads；另与原始相对丰度核对 |\n| binary Jaccard | feature 出现/缺失 | 否 | 零表示未检出 | 50,000 reads |\n| unweighted UniFrac | 出现/缺失所在的独有分支长度 | 是 | 零表示该 tip 未检出 | 50,000 reads |\n| weighted UniFrac | 分支上的相对丰度差异 | 是 | 零与丰度共同进入 | 50,000 reads |\n| Aitchison | CLR 后的 log-ratio 差异 | 否 | 必须声明 zero replacement | 未抽平；过滤后加 0.5 |\n| Robust Aitchison | 只在观测非零项上做 rclr，再用 RPCA 补全低秩结构 | 否 | 不给观测零机械加伪计数 | 未抽平；与 Aitchison 同一过滤集 |\n\n### Bray–Curtis 与 Jaccard：丰度和出现不是一回事\n\n两个样本 (i,j) 的 Bray–Curtis dissimilarity 可写为：\n\n\\[\nd_{BC}(i,j)=\\frac{\\sum_k |x_{ik}-x_{jk}|}\n{\\sum_k(x_{ik}+x_{jk})}.\n\\]\n\n它对共同高丰度 feature 更敏感。binary Jaccard 先把计数变为 0/1，再比较两样本 feature 集合的交集与并集：\n\n\\[\nd_J(i,j)=1-\\frac{|A_i\\cap A_j|}{|A_i\\cup A_j|}.\n\\]\n\n因此，一个 feature 从 1 read 变为 10,000 reads 不改变 binary Jaccard，却会改变 Bray–Curtis。presence/absence 还很容易受测序深度影响：低深度样本更可能漏检稀有 feature，所以本例把四个生态距离放在同一份 50,000 reads 稀释表上比较。\n\n### UniFrac：比较的是树上分支，而不是 taxonomy 字符串\n\nUnweighted UniFrac 根据只出现在某一群落中的系统发育分支长度计算距离；weighted UniFrac 再把分支上的丰度纳入权重。[Lozupone & Knight (2005)](https://doi.org/10.1128/AEM.71.12.8228-8235.2005)与[Lozupone et al. (2007)](https://doi.org/10.1128/AEM.01996-06)分别给出核心方法与定量/定性比较。\n\n这意味着 UniFrac 至少需要三个不可省略的门禁：\n\n1. 树已经定根（rooted）；\n2. 每条边有有限、非负的 branch length；\n3. 树 tips 与计数表 feature ID 精确对应。\n\n如果 tip 不匹配，不能静默取交集后继续。被删掉的是哪些 ASV、丢失多少 reads、是否偏向某些类群，都必须先形成审计表。\n\n### Aitchison：相对信息应在 log-ratio 几何中比较\n\n微生物计数受总测序量约束。对正值组成向量 (x_i)，centered log-ratio（CLR）为：\n\n\\[\n\\operatorname{clr}(x_{ik})=\n\\log x_{ik}-\\frac{1}{D}\\sum_{l=1}^{D}\\log x_{il},\n\\]\n\n两个样本 CLR 向量的欧氏距离就是 Aitchison distance。问题在于 (log(0)) 不存在。给所有零加 0.5、1 或其他 pseudocount 是一个分析假设，不是无害的格式修复。\n\n<details>\n<summary><strong>深入：Robust Aitchison 与旧 DEICODE 名称的关系</strong></summary>\n\n[Martino et al. (2019)](https://doi.org/10.1128/mSystems.00016-19)提出的 DEICODE 方法族，先对每个样本的观测非零项做 robust CLR（rclr），把零当作缺失位置，再用低秩 matrix completion / robust PCA（RPCA）估计样本与 feature 结构。它不是“换了一个固定伪计数的 CLR”。\n\n当前维护实现是 [`gemelli`](https://github.com/biocore/gemelli)。本例固定 `gemelli 0.0.13`、3 个 components、5 次 OptSpace iterations 和显式 ARPACK seed；输出再统一 PC 方向并写到 12 位小数。这里保留“DEICODE”作为读者熟悉的方法族名称，但实际运行使用维护中的 gemelli，而不是旧的 DEICODE 仓库。\n\n</details>\n\n### PCoA 的负特征值要先审计\n\nPCoA 尝试在欧氏坐标中保存输入距离。如果距离不是严格 Euclidean，分解可能出现负特征值。处理顺序应是：\n\n1. 保存全部原始 eigenvalues；\n2. 报告负特征值数量及其相对量级；\n3. 只有存在实质性负值时才明确使用 Lingoes 或 Cailliez correction；\n4. 在图注和 Methods 中写明校正，而不是静默改变距离。\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、导出真实数据、配置 gemelli 和定义作图函数</strong></summary>\n\nR 4.4 与 Bioconductor 3.19 环境首次安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"BiocManager\", \"ape\", \"digest\", \"dplyr\", \"ggplot2\", \"jsonlite\",\n  \"ragg\", \"readr\", \"scales\", \"svglite\", \"systemfonts\", \"tibble\",\n  \"tidyr\", \"vegan\"\n))\nBiocManager::install(version = \"3.19\", ask = FALSE)\nBiocManager::install(\"phyloseq\", version = \"3.19\", ask = FALSE)\n```\n:::\n\n\nRobust Aitchison 使用独立 Python 3.12 环境，避免与 QIIME 2 或 R 环境互相覆盖：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\npython3.12 -m venv .tools/gemelli-0.0.13\n.tools/gemelli-0.0.13/bin/python -m pip install --upgrade \"pip==26.0.1\"\n.tools/gemelli-0.0.13/bin/python -m pip install \\\n  \"gemelli==0.0.13\" \\\n  \"numpy==2.4.2\" \\\n  \"pandas==2.3.3\" \\\n  \"scipy==1.17.1\" \\\n  \"scikit-learn==1.7.1\" \\\n  \"scikit-bio==0.7.2\" \\\n  \"biom-format==2.1.17\" \\\n  \"h5py==3.15.1\" \\\n  \"matplotlib==3.10.8\" \\\n  \"seaborn==0.13.2\" \\\n  \"click==8.1.8\" \\\n  \"iow==1.0.8\" \\\n  \"tax2tree==1.1\" \\\n  \"nose==1.3.7\"\n.tools/gemelli-0.0.13/bin/python -m pip check\n```\n:::\n\n\n下面从 `phyloseq 1.48.0` 内置的 `GlobalPatterns` 真实对象导出三件套和 rooted tree。源对象含 19,216 个 OTU，其中 228 个在全部样本中计数为零；删除这些空行后保留 18,988 个 OTU，reads 总数不变。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ape)\nlibrary(digest)\nlibrary(phyloseq)\nlibrary(readr)\n\nstopifnot(as.character(packageVersion(\"phyloseq\")) == \"1.48.0\")\ndata(\"GlobalPatterns\", package = \"phyloseq\")\nps <- prune_taxa(taxa_sums(GlobalPatterns) > 0, GlobalPatterns)\n\notutab <- as(otu_table(ps), \"matrix\")\nif (!taxa_are_rows(ps)) otutab <- t(otutab)\ntaxonomy <- as(tax_table(ps), \"matrix\")\nmetadata <- data.frame(sample_data(ps), check.names = FALSE)\ntree <- phy_tree(ps)\n\nmetadata <- metadata[colnames(otutab), , drop = FALSE]\nhabitat_map <- c(\n  \"Feces\" = \"Human-associated\",\n  \"Skin\" = \"Human-associated\",\n  \"Tongue\" = \"Human-associated\",\n  \"Freshwater\" = \"Freshwater\",\n  \"Freshwater (creek)\" = \"Freshwater\",\n  \"Ocean\" = \"Marine/estuarine\",\n  \"Sediment (estuary)\" = \"Marine/estuarine\",\n  \"Soil\" = \"Soil\",\n  \"Mock\" = \"Mock\"\n)\n\nmetadata_out <- data.frame(\n  SampleID = rownames(metadata),\n  SampleType = as.character(metadata$SampleType),\n  HabitatClass = unname(habitat_map[as.character(metadata$SampleType)]),\n  Primer = as.character(metadata$Primer),\n  Final_Barcode = as.character(metadata$Final_Barcode),\n  Barcode_truncated_plus_T = as.character(metadata$Barcode_truncated_plus_T),\n  Barcode_full_length = as.character(metadata$Barcode_full_length),\n  Description = as.character(metadata$Description),\n  check.names = FALSE\n)\n\ndir.create(\"data/small/beta-distances\", recursive = TRUE, showWarnings = FALSE)\nwrite_tsv(\n  tibble::as_tibble(otutab, rownames = \"FeatureID\"),\n  \"data/small/beta-distances/otutab.tsv\"\n)\nwrite_tsv(\n  tibble::as_tibble(taxonomy, rownames = \"FeatureID\"),\n  \"data/small/beta-distances/taxonomy.tsv\",\n  na = \"\"\n)\nwrite_tsv(\n  metadata_out,\n  \"data/small/beta-distances/metadata.tsv\",\n  na = \"\"\n)\ntree_con <- gzfile(\n  \"data/small/beta-distances/rooted-tree.nwk.gz\",\n  open = \"wt\",\n  compression = 9\n)\nwriteLines(write.tree(tree), tree_con, useBytes = TRUE)\nclose(tree_con)\n```\n:::\n\n\n本页所需的包、随机种子和出版级函数全部内联：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ape)\nlibrary(digest)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(jsonlite)\nlibrary(phyloseq)\nlibrary(readr)\nlibrary(tidyr)\nlibrary(vegan)\n\nset.seed(20260722)\n\nfont_pub <- \"DejaVu Sans\"\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\", linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\", size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 89,\n  height = 70,\n  units = \"mm\",\n  dpi = 600,\n  write_svg = TRUE,\n  write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot,\n    width = width, height = height, units = units,\n    device = grDevices::cairo_pdf, family = base_family, bg = \"white\"\n  )\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"), plot,\n      width = width, height = height, units = units,\n      device = svglite::svglite, bg = \"white\"\n    )\n  }\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot,\n    width = width, height = height, units = units, dpi = dpi,\n    device = ragg::agg_png, bg = \"white\"\n  )\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"), plot,\n      width = width, height = height, units = units, dpi = dpi,\n      device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\"\n    )\n  }\n  invisible(plot)\n}\n```\n:::\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 从三件套读起，并单独读取根树\n\n`otutab` 的方向固定为 feature × sample。taxonomy 虽不直接进入距离公式，仍与计数表一起核对，避免分析数据和注释数据来自不同版本。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\ninput_paths <- c(\n  otutab = \"data/small/beta-distances/otutab.tsv\",\n  taxonomy = \"data/small/beta-distances/taxonomy.tsv\",\n  metadata = \"data/small/beta-distances/metadata.tsv\",\n  tree = \"data/small/beta-distances/rooted-tree.nwk.gz\"\n)\nexpected_sha256 <- c(\n  otutab = \"727073a3f26aff6730ad54b55c11e1d52bd5d3d34f99dbf75d125d2e84d9722d\",\n  taxonomy = \"1189e6e2a02474a665283f6b9962ec25716b6c7faf66011a6506e87a69ddf0ff\",\n  metadata = \"c708b3b89edbb26a4aab26b5e575cdefef1eae28b9b7f93cea5f8f2edfc94221\",\n  tree = \"535f512b3018da462a416b8f04ef36369bf1c1e383510494a790508361fc8c15\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  function(path) digest::digest(\n    path,\n    algo = \"sha256\",\n    serialize = FALSE,\n    file = TRUE\n  ),\n  character(1)\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\notutab <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\ntree <- ape::read.tree(gzfile(input_paths[[\"tree\"]]))\n\notutab <- data.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\nfeature_ids <- rownames(otutab)\nsample_ids <- colnames(otutab)\n\nstopifnot(\n  nrow(otutab) == 18988L,\n  ncol(otutab) == 26L,\n  sum(otutab) == 28216678,\n  setequal(feature_ids, rownames(taxonomy)),\n  setequal(sample_ids, rownames(metadata)),\n  all(is.finite(otutab)),\n  all(otutab >= 0),\n  all(abs(otutab - round(otutab)) < .Machine$double.eps^0.5),\n  all(rowSums(otutab) > 0),\n  all(colSums(otutab) > 0)\n)\ntaxonomy <- taxonomy[feature_ids, , drop = FALSE]\nmetadata <- metadata[sample_ids, , drop = FALSE]\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18988    26\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28216678\n```\n\n\n:::\n\n```{.r .cell-code}\notutab[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       CL3 CC1 SV1 M31Fcsw M11Fcsw\n549322   0   0   0       0       0\n522457   0   0   0       0       0\n951      0   0   0       0       0\n244423   0   0   0       0       0\n586076   0   0   0       0       0\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxonomy[1:5, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Kingdom        Phylum        Class        Order        Family      Genus\n549322 Archaea Crenarchaeota Thermoprotei                                      \n522457 Archaea Crenarchaeota Thermoprotei                                      \n951    Archaea Crenarchaeota Thermoprotei Sulfolobales Sulfolobaceae Sulfolobus\n244423 Archaea Crenarchaeota        Sd-NA                                      \n586076 Archaea Crenarchaeota        Sd-NA                                      \n                        Species\n549322                         \n522457                         \n951    Sulfolobusacidocaldarius\n244423                         \n586076                         \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        SampleType     HabitatClass  Primer Final_Barcode\nCL3           Soil             Soil ILBC_01        AACGCA\nCC1           Soil             Soil ILBC_02        AACTCG\nSV1           Soil             Soil ILBC_03        AACTGT\nM31Fcsw      Feces Human-associated ILBC_04        AAGAGA\nM11Fcsw      Feces Human-associated ILBC_05        AAGCTG\nM31Plmr       Skin Human-associated ILBC_07        AATCGT\n        Barcode_truncated_plus_T Barcode_full_length\nCL3                       TGCGTT         CTAGCGTGCGT\nCC1                       CGAGTT         CATCGACGAGT\nSV1                       ACAGTT         GTACGCACAGT\nM31Fcsw                   TCTCTT         TCGACATCTCT\nM11Fcsw                   CAGCTT         CGACTGCAGCT\nM31Plmr                   ACGATT         CGAGTCACGAT\n                                       Description\nCL3       Calhoun South Carolina Pine soil, pH 4.9\nCC1       Cedar Creek Minnesota, grassland, pH 6.1\nSV1     Sevilleta new Mexico, desert scrub, pH 8.3\nM31Fcsw    M3, Day 1, fecal swab, whole body study\nM11Fcsw    M1, Day 1, fecal swab, whole body study\nM31Plmr    M3, Day 1, right palm, whole body study\n```\n\n\n:::\n:::\n\n\n### 2. 在算 UniFrac 前锁死树合同\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntree_audit <- data.frame(\n  Metric = c(\n    \"Rooted\",\n    \"Tips\",\n    \"Unique tips\",\n    \"Internal nodes\",\n    \"Branch lengths present\",\n    \"Finite branch lengths\",\n    \"Negative branch lengths\",\n    \"Tip set matches otutab\"\n  ),\n  Value = c(\n    ape::is.rooted(tree),\n    length(tree$tip.label),\n    length(unique(tree$tip.label)),\n    tree$Nnode,\n    !is.null(tree$edge.length),\n    all(is.finite(tree$edge.length)),\n    sum(tree$edge.length < 0),\n    setequal(tree$tip.label, feature_ids)\n  )\n)\nstopifnot(\n  ape::is.rooted(tree),\n  length(tree$tip.label) == 18988L,\n  !anyDuplicated(tree$tip.label),\n  !is.null(tree$edge.length),\n  all(is.finite(tree$edge.length)),\n  all(tree$edge.length >= 0),\n  setequal(tree$tip.label, feature_ids)\n)\ntree_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Metric Value\n1                  Rooted     1\n2                    Tips 18988\n3             Unique tips 18988\n4          Internal nodes 18987\n5  Branch lengths present     1\n6   Finite branch lengths     1\n7 Negative branch lengths     0\n8  Tip set matches otutab     1\n```\n\n\n:::\n:::\n\n\n### 3. 为生态距离固定同一测序深度\n\n本例所有样本至少有 58,688 reads，因此固定 50,000 reads 可保留 26 个样本。随机抽样只执行一次并固定 seed；这张表只服务于距离比较，不作为 feature-level differential abundance 的通用输入。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunity <- t(otutab)\nlibrary_size <- rowSums(community)\n\nstopifnot(min(library_size) >= 50000)\nset.seed(20260722)\ncommunity_rarefied <- vegan::rrarefy(\n  community,\n  sample = 50000\n)\nstopifnot(\n  nrow(community_rarefied) == 26L,\n  all(rowSums(community_rarefied) == 50000L),\n  sum(community_rarefied) == 1300000\n)\n\nrarefaction_audit <- data.frame(\n  SampleID = rownames(community_rarefied),\n  HabitatClass = metadata[rownames(community_rarefied), \"HabitatClass\"],\n  OriginalReads = as.numeric(library_size[rownames(community_rarefied)]),\n  RarefiedReads = rowSums(community_rarefied),\n  FeaturesBefore = rowSums(community > 0),\n  FeaturesAfter = rowSums(community_rarefied > 0)\n)\nhead(rarefaction_audit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        SampleID     HabitatClass OriginalReads RarefiedReads FeaturesBefore\nCL3          CL3             Soil        864077         50000           6964\nCC1          CC1             Soil       1135457         50000           7679\nSV1          SV1             Soil        697509         50000           5729\nM31Fcsw  M31Fcsw Human-associated       1543451         50000           2667\nM11Fcsw  M11Fcsw Human-associated       2076476         50000           2574\nM31Plmr  M31Plmr Human-associated        718943         50000           3214\n        FeaturesAfter\nCL3              3256\nCC1              3644\nSV1              2708\nM31Fcsw           714\nM11Fcsw           547\nM31Plmr          1244\n```\n\n\n:::\n\n```{.r .cell-code}\nc(\n  samples = nrow(community_rarefied),\n  reads = sum(community_rarefied),\n  retained_features = sum(colSums(community_rarefied) > 0)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          samples             reads retained_features \n               26           1300000             12443 \n```\n\n\n:::\n:::\n\n\n### 4. 计算 Bray、Jaccard 和两种 UniFrac\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbray <- vegan::vegdist(community_rarefied, method = \"bray\")\njaccard <- vegan::vegdist(\n  community_rarefied,\n  method = \"jaccard\",\n  binary = TRUE\n)\n\nps_rarefied <- phyloseq::phyloseq(\n  phyloseq::otu_table(t(community_rarefied), taxa_are_rows = TRUE),\n  phyloseq::phy_tree(tree)\n)\nps_rarefied <- phyloseq::prune_taxa(\n  phyloseq::taxa_sums(ps_rarefied) > 0,\n  ps_rarefied\n)\n\nunweighted_unifrac <- phyloseq::UniFrac(\n  ps_rarefied,\n  weighted = FALSE,\n  normalized = TRUE,\n  parallel = FALSE,\n  fast = TRUE\n)\nweighted_unifrac <- phyloseq::UniFrac(\n  ps_rarefied,\n  weighted = TRUE,\n  normalized = TRUE,\n  parallel = FALSE,\n  fast = TRUE\n)\n\n# Bray sensitivity: rarefied counts versus unrarefied relative abundance\nbray_relative <- vegan::vegdist(\n  vegan::decostand(community, method = \"total\"),\n  method = \"bray\"\n)\nbray_sensitivity_rho <- cor(\n  as.vector(bray),\n  as.vector(bray_relative),\n  method = \"spearman\"\n)\nbray_sensitivity_rho\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9985223\n```\n\n\n:::\n:::\n\n\n本数据中两条 Bray 路线的距离秩相关为 0.999。这是一项数据集特异的敏感性结果，不是“Bray 永远不受标准化影响”的保证。\n\n### 5. 在未抽平计数上计算经典 Aitchison\n\n为与 gemelli 默认的稀有 feature 控制一致，两个 Aitchison 分支都保留 total count > 10 且 prevalence > 10% 的 feature。阈值是排除极少信息行的分析决策，必须在 Methods 中报告。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_total <- rowSums(otutab)\nfeature_prevalence <- rowMeans(otutab > 0)\nkeep_composition <- feature_total > 10 & feature_prevalence > 0.10\n\nfeature_filter_audit <- data.frame(\n  FeatureID = feature_ids,\n  TotalCount = feature_total,\n  Prevalence = feature_prevalence,\n  Retained = keep_composition\n)\nstopifnot(\n  sum(keep_composition) == 11063L,\n  sum(otutab[keep_composition, , drop = FALSE]) == 28148221\n)\n\naitchison_distance <- function(pseudocount) {\n  log_counts <- log(\n    t(otutab[keep_composition, , drop = FALSE]) + pseudocount\n  )\n  clr <- log_counts - rowMeans(log_counts)\n  dist(clr, method = \"euclidean\")\n}\n\naitchison_pc01 <- aitchison_distance(0.1)\naitchison_pc05 <- aitchison_distance(0.5)\naitchison_pc10 <- aitchison_distance(1.0)\n\nc(\n  retained_features = sum(keep_composition),\n  retained_reads = sum(otutab[keep_composition, , drop = FALSE])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nretained_features    retained_reads \n            11063          28148221 \n```\n\n\n:::\n:::\n\n\n### 6. 用维护中的 gemelli 计算 Robust Aitchison\n\n下面命令固定 3 个 components、5 次 iterations、同一 feature filter 和 seed。仓库附带的 runner 还固定 ARPACK 初始化、统一任意 PC 符号并把浮点输出规范到 12 位。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngemelli_python <- Sys.getenv(\n  \"GEMELLI_PYTHON\",\n  \".tools/gemelli-0.0.13/bin/python\"\n)\ngemelli_runner <- Sys.getenv(\n  \"GEMELLI_RUNNER\",\n  \"scripts/run_gemelli_rpca.py\"\n)\nstopifnot(file.exists(gemelli_python), file.exists(gemelli_runner))\n\ndir.create(\"results/21-beta-distances\", recursive = TRUE, showWarnings = FALSE)\ngemelli_log <- system2(\n  gemelli_python,\n  args = c(\n    shQuote(gemelli_runner),\n    \"--input\", shQuote(input_paths[[\"otutab\"]]),\n    \"--output-dir\", shQuote(\"results/21-beta-distances\"),\n    \"--n-components\", \"3\",\n    \"--min-sample-count\", \"500\",\n    \"--min-feature-count\", \"10\",\n    \"--min-feature-frequency\", \"10\",\n    \"--max-iterations\", \"5\"\n  ),\n  stdout = TRUE,\n  stderr = TRUE,\n  env = c(\n    \"PYTHONHASHSEED=20260722\",\n    \"OMP_NUM_THREADS=1\",\n    \"OPENBLAS_NUM_THREADS=1\",\n    \"MKL_NUM_THREADS=1\"\n  )\n)\ngemelli_status <- attr(gemelli_log, \"status\")\nif (is.null(gemelli_status)) gemelli_status <- 0L\nstopifnot(gemelli_status == 0L)\ngemelli_log\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"gemelli RPCA complete: 11063 features x 26 samples\"\n```\n\n\n:::\n:::\n\n\n<details>\n<summary><strong>展开：runner 的关键 Python 实现</strong></summary>\n\n把下面代码保存为 `scripts/run_gemelli_rpca.py`。它接受 feature × sample TSV，输出距离、样本坐标、feature loadings、eigenvalues 和可由 scikit-bio 读取的 ordination 文件。\n\n```python\n#!/usr/bin/env python3\nfrom __future__ import annotations\n\nimport argparse\nimport hashlib\nimport json\nimport os\nimport platform\nimport sys\nfrom pathlib import Path\n\nimport biom\nimport gemelli\nimport gemelli.optspace as gemelli_optspace\nimport numpy as np\nimport pandas as pd\nimport scipy\nimport skbio\nimport sklearn\nfrom gemelli.rpca import rpca, rpca_table_processing\nfrom scipy.sparse.linalg import svds as scipy_svds\n\nSEED = 20260722\nROUND_DIGITS = 12\n\ndef deterministic_svds(*args, **kwargs):\n    kwargs.setdefault(\"rng\", np.random.default_rng(SEED))\n    return scipy_svds(*args, **kwargs)\n\ndef canonicalize_results(ordination, distance):\n    samples = ordination.samples.copy().astype(float)\n    features = ordination.features.copy().astype(float)\n    for axis in samples.columns:\n        anchor = samples[axis].abs().idxmax()\n        if samples.loc[anchor, axis] < 0:\n            samples.loc[:, axis] *= -1\n            features.loc[:, axis] *= -1\n    result = skbio.OrdinationResults(\n        ordination.short_method_name,\n        ordination.long_method_name,\n        ordination.eigvals.astype(float).round(ROUND_DIGITS),\n        samples=samples.round(ROUND_DIGITS),\n        features=features.round(ROUND_DIGITS),\n        proportion_explained=(\n            ordination.proportion_explained.astype(float).round(ROUND_DIGITS)\n        ),\n    )\n    distance = skbio.DistanceMatrix(\n        np.round(np.asarray(distance.data), ROUND_DIGITS),\n        ids=distance.ids,\n    )\n    return result, distance\n\nparser = argparse.ArgumentParser()\nparser.add_argument(\"--input\", type=Path, required=True)\nparser.add_argument(\"--output-dir\", type=Path, required=True)\nparser.add_argument(\"--n-components\", type=int, default=3)\nparser.add_argument(\"--min-sample-count\", type=int, default=500)\nparser.add_argument(\"--min-feature-count\", type=int, default=10)\nparser.add_argument(\"--min-feature-frequency\", type=float, default=10.0)\nparser.add_argument(\"--max-iterations\", type=int, default=5)\nargs = parser.parse_args()\n\nargs.output_dir.mkdir(parents=True, exist_ok=True)\ncounts_df = pd.read_csv(args.input, sep=\"\\t\", index_col=0)\ncounts = counts_df.to_numpy(dtype=float)\nif (\n    counts_df.index.has_duplicates\n    or counts_df.columns.has_duplicates\n    or not np.isfinite(counts).all()\n    or (counts < 0).any()\n    or not np.equal(counts, np.floor(counts)).all()\n    or (counts.sum(axis=0) == 0).any()\n    or (counts.sum(axis=1) == 0).any()\n):\n    raise ValueError(\"Invalid feature table\")\n\ntable = biom.Table(\n    counts,\n    observation_ids=counts_df.index.astype(str).tolist(),\n    sample_ids=counts_df.columns.astype(str).tolist(),\n)\nprocessed = rpca_table_processing(\n    table,\n    min_sample_count=args.min_sample_count,\n    min_feature_count=args.min_feature_count,\n    min_feature_frequency=args.min_feature_frequency,\n)\n\nnp.random.seed(SEED)\ngemelli_optspace.svds = deterministic_svds\nordination, distance = rpca(\n    table,\n    n_components=args.n_components,\n    min_sample_count=args.min_sample_count,\n    min_feature_count=args.min_feature_count,\n    min_feature_frequency=args.min_feature_frequency,\n    max_iterations=args.max_iterations,\n)\nordination, distance = canonicalize_results(ordination, distance)\n\ndistance.write(args.output_dir / \"robust-aitchison-distance.tsv\")\nordination.write(args.output_dir / \"robust-aitchison-ordination.txt\")\nordination.samples.rename_axis(\"SampleID\").reset_index().to_csv(\n    args.output_dir / \"robust-aitchison-sample-scores.tsv\",\n    sep=\"\\t\", index=False, float_format=\"%.12g\"\n)\nordination.features.rename_axis(\"FeatureID\").reset_index().to_csv(\n    args.output_dir / \"robust-aitchison-feature-loadings.tsv\",\n    sep=\"\\t\", index=False, float_format=\"%.12g\"\n)\npd.DataFrame({\n    \"Axis\": ordination.eigvals.index,\n    \"Eigenvalue\": ordination.eigvals.to_numpy(),\n    \"ProportionExplained\": ordination.proportion_explained.to_numpy(),\n}).to_csv(\n    args.output_dir / \"robust-aitchison-eigenvalues.tsv\",\n    sep=\"\\t\", index=False, float_format=\"%.12g\"\n)\nprint(f\"gemelli RPCA complete: {processed.shape[0]} features x \"\n      f\"{processed.shape[1]} samples\")\n```\n\n</details>\n\n读取 Robust Aitchison 距离，并严格按三件套样本顺序排列：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrobust_frame <- readr::read_tsv(\n  \"results/21-beta-distances/robust-aitchison-distance.tsv\",\n  show_col_types = FALSE,\n  name_repair = \"minimal\"\n)\nrobust_ids <- as.character(robust_frame[[1L]])\nrobust_matrix <- data.matrix(robust_frame[-1L])\nrownames(robust_matrix) <- robust_ids\ncolnames(robust_matrix) <- colnames(robust_frame)[-1L]\nstopifnot(\n  setequal(sample_ids, rownames(robust_matrix)),\n  setequal(sample_ids, colnames(robust_matrix))\n)\nrobust_aitchison <- as.dist(\n  robust_matrix[sample_ids, sample_ids, drop = FALSE]\n)\n```\n:::\n\n\n### 7. 把六个距离放进同一审计框架\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalign_distance <- function(distance, ids = sample_ids) {\n  matrix <- as.matrix(distance)\n  as.dist(matrix[ids, ids, drop = FALSE])\n}\n\ndistances <- list(\n  \"Bray-Curtis\" = align_distance(bray),\n  \"Jaccard\" = align_distance(jaccard),\n  \"Unweighted UniFrac\" = align_distance(unweighted_unifrac),\n  \"Weighted UniFrac\" = align_distance(weighted_unifrac),\n  \"Aitchison\" = align_distance(aitchison_pc05),\n  \"Robust Aitchison\" = align_distance(robust_aitchison)\n)\n\nvalidate_distance <- function(distance) {\n  matrix <- as.matrix(distance)\n  stopifnot(\n    identical(dim(matrix), c(26L, 26L)),\n    identical(rownames(matrix), sample_ids),\n    identical(colnames(matrix), sample_ids),\n    all(is.finite(matrix)),\n    min(matrix) >= -1e-12,\n    max(abs(matrix - t(matrix))) <= 1e-10,\n    max(abs(diag(matrix))) <= 1e-10\n  )\n  TRUE\n}\nvapply(distances, validate_distance, logical(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Bray-Curtis            Jaccard Unweighted UniFrac   Weighted UniFrac \n              TRUE               TRUE               TRUE               TRUE \n         Aitchison   Robust Aitchison \n              TRUE               TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\npair_indices <- which(upper.tri(matrix(0, 26, 26)), arr.ind = TRUE)\ndistance_summary <- bind_rows(lapply(names(distances), function(metric) {\n  matrix <- as.matrix(distances[[metric]])\n  values <- matrix[pair_indices]\n  sample_a <- rownames(matrix)[pair_indices[, 1L]]\n  sample_b <- colnames(matrix)[pair_indices[, 2L]]\n  pair_type <- ifelse(\n    metadata[sample_a, \"HabitatClass\"] == metadata[sample_b, \"HabitatClass\"],\n    \"Within habitat\",\n    \"Between habitats\"\n  )\n  data.frame(\n    Metric = metric,\n    Minimum = min(values),\n    Median = median(values),\n    Maximum = max(values),\n    WithinMedian = median(values[pair_type == \"Within habitat\"]),\n    BetweenMedian = median(values[pair_type == \"Between habitats\"]),\n    BetweenWithinRatio =\n      median(values[pair_type == \"Between habitats\"]) /\n      median(values[pair_type == \"Within habitat\"])\n  )\n}))\ndistance_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Metric     Minimum      Median     Maximum WithinMedian\n1        Bray-Curtis  0.07050000   0.9877600   0.9991600    0.9271000\n2            Jaccard  0.48498498   0.9227027   0.9856204    0.8438426\n3 Unweighted UniFrac  0.38147173   0.7856390   0.9214850    0.7096534\n4   Weighted UniFrac  0.01842162   0.4436251   0.6211719    0.3673293\n5          Aitchison 71.83231859 211.7210015 329.0834406  165.2224446\n6   Robust Aitchison  0.12847247   1.9511190   4.6616892    1.4050986\n  BetweenMedian BetweenWithinRatio\n1     0.9896000           1.067415\n2     0.9278045           1.099499\n3     0.7917972           1.115752\n4     0.4501955           1.225591\n5   224.9282175           1.361366\n6     2.5915696           1.844404\n```\n\n\n:::\n:::\n\n\n这里的 within/between median 只是帮助理解距离尺度的描述量，不是显著性检验。尤其不能因为某个 ratio 最大，就在看到分组后把该距离改成主分析。\n\n### 8. 比较距离秩次，而不是比较数值单位\n\nAitchison 的数值可达数百，Robust Aitchison 约为 0–5，而 UniFrac 常在 0–1。直接比较“谁的平均距离更大”没有意义；下面用同一组 325 个样本对的 Spearman correlation 比较远近秩次。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetric_levels <- names(distances)\ndistance_vectors <- do.call(cbind, lapply(distances, as.vector))\ndistance_cor_matrix <- cor(distance_vectors, method = \"spearman\")\n\ndistance_correlation <- tidyr::expand_grid(\n  MetricX = rownames(distance_cor_matrix),\n  MetricY = colnames(distance_cor_matrix)\n)\ndistance_correlation$Spearman <- mapply(\n  function(x, y) distance_cor_matrix[x, y],\n  distance_correlation$MetricX,\n  distance_correlation$MetricY\n)\n\nround(distance_cor_matrix, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Bray-Curtis Jaccard Unweighted UniFrac Weighted UniFrac\nBray-Curtis              1.000   0.886              0.766            0.691\nJaccard                  0.886   1.000              0.953            0.707\nUnweighted UniFrac       0.766   0.953              1.000            0.695\nWeighted UniFrac         0.691   0.707              0.695            1.000\nAitchison                0.367   0.493              0.557            0.341\nRobust Aitchison         0.472   0.505              0.506            0.418\n                   Aitchison Robust Aitchison\nBray-Curtis            0.367            0.472\nJaccard                0.493            0.505\nUnweighted UniFrac     0.557            0.506\nWeighted UniFrac       0.341            0.418\nAitchison              1.000            0.800\nRobust Aitchison       0.800            1.000\n```\n\n\n:::\n:::\n\n\n在本数据中：\n\n- Jaccard 与 unweighted UniFrac：ρ = 0.953；\n- Aitchison 与 Robust Aitchison：ρ = 0.800；\n- Bray–Curtis 与 Aitchison：ρ = 0.367。\n\n高相关表示这批样本中许多 pair 的远近次序相似，不会消除定义差异。尤其是 Jaccard 无法回答“差异是否集中在深分化的系统发育分支”，Aitchison 也不等于 Bray–Curtis 的另一种缩放。\n\n### 9. 审计伪计数敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\npseudocount_distances <- list(\n  \"0.1\" = align_distance(aitchison_pc01),\n  \"0.5\" = align_distance(aitchison_pc05),\n  \"1.0\" = align_distance(aitchison_pc10)\n)\naitchison_pseudocount_sensitivity <- data.frame(\n  Pseudocount = as.numeric(names(pseudocount_distances)),\n  SpearmanToAitchisonPC05 = vapply(\n    pseudocount_distances,\n    function(x) cor(\n      as.vector(x),\n      as.vector(aitchison_pc05),\n      method = \"spearman\"\n    ),\n    numeric(1)\n  ),\n  SpearmanToRobustAitchison = vapply(\n    pseudocount_distances,\n    function(x) cor(\n      as.vector(x),\n      as.vector(robust_aitchison),\n      method = \"spearman\"\n    ),\n    numeric(1)\n  )\n)\naitchison_pseudocount_sensitivity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Pseudocount SpearmanToAitchisonPC05 SpearmanToRobustAitchison\n0.1         0.1               0.9957003                 0.7867978\n0.5         0.5               1.0000000                 0.8000115\n1.0         1.0               0.9986860                 0.8087152\n```\n\n\n:::\n:::\n\n\n0.1、0.5、1.0 三个 pseudocount 与默认 0.5 的距离秩相关均高于 0.995，但它们与 Robust Aitchison 的相关从 0.787 到 0.809。这说明本例对三个常见伪计数总体较稳定，却仍不能把 observed-only rclr/RPCA 当成固定伪计数 CLR。\n\n### 10. PCoA 前先保存负特征值审计\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcoa_score_rows <- list()\npcoa_audit_rows <- list()\n\nfor (metric in names(distances)) {\n  distance <- distances[[metric]]\n  raw_pcoa <- suppressWarnings(\n    cmdscale(\n      distance,\n      k = attr(distance, \"Size\") - 2L,\n      eig = TRUE,\n      add = FALSE\n    )\n  )\n  eigenvalues <- as.numeric(raw_pcoa$eig)\n  negative_count <- sum(eigenvalues < -1e-10)\n  negative_sum <- sum(abs(eigenvalues[eigenvalues < 0]))\n  positive_sum <- sum(eigenvalues[eigenvalues > 0])\n  correction <- if (negative_count > 0L) \"Lingoes\" else \"None\"\n\n  fit <- ape::pcoa(\n    distance,\n    correction = if (negative_count > 0L) \"lingoes\" else \"none\"\n  )\n  if (negative_count > 0L) {\n    coordinates <- fit$vectors.cor[, 1:2, drop = FALSE]\n    relative_eigen <- fit$values$Rel_corr_eig[1:2]\n  } else {\n    coordinates <- fit$vectors[, 1:2, drop = FALSE]\n    relative_eigen <- fit$values$Relative_eig[1:2]\n  }\n  coordinates <- coordinates[sample_ids, , drop = FALSE]\n\n  pcoa_score_rows[[metric]] <- data.frame(\n    Metric = metric,\n    SampleID = rownames(coordinates),\n    HabitatClass = metadata[rownames(coordinates), \"HabitatClass\"],\n    Axis1 = coordinates[, 1L],\n    Axis2 = coordinates[, 2L],\n    Axis1Explained = relative_eigen[[1L]],\n    Axis2Explained = relative_eigen[[2L]],\n    Correction = correction\n  )\n  pcoa_audit_rows[[metric]] <- data.frame(\n    Metric = metric,\n    PositiveEigenvalues = sum(eigenvalues > 1e-10),\n    NegativeEigenvalues = negative_count,\n    MinimumEigenvalue = min(eigenvalues),\n    NegativePositiveRatio = negative_sum / positive_sum,\n    Correction = correction,\n    Axis1Explained = relative_eigen[[1L]],\n    Axis2Explained = relative_eigen[[2L]]\n  )\n}\n\npcoa_scores <- bind_rows(pcoa_score_rows)\npcoa_eigen_audit <- bind_rows(pcoa_audit_rows)\nstopifnot(\n  nrow(pcoa_scores) == 156L,\n  pcoa_eigen_audit$NegativeEigenvalues[\n    pcoa_eigen_audit$Metric == \"Weighted UniFrac\"\n  ] == 3L,\n  all(\n    pcoa_eigen_audit$Correction[\n      pcoa_eigen_audit$Metric != \"Weighted UniFrac\"\n    ] == \"None\"\n  )\n)\npcoa_eigen_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Metric PositiveEigenvalues NegativeEigenvalues MinimumEigenvalue\n1        Bray-Curtis                  25                   0     -1.300283e-16\n2            Jaccard                  25                   0     -9.040552e-17\n3 Unweighted UniFrac                  25                   0     -4.783265e-17\n4   Weighted UniFrac                  22                   3     -8.607715e-03\n5          Aitchison                  25                   0     -3.703342e-13\n6   Robust Aitchison                   3                   0     -5.747998e-12\n  NegativePositiveRatio Correction Axis1Explained Axis2Explained\n1          1.149045e-17       None      0.1468052      0.1214270\n2          8.898069e-18       None      0.1385912      0.1052681\n3          6.380986e-18       None      0.1806779      0.1228718\n4          4.550580e-03    Lingoes      0.3062738      0.1330620\n5          6.059541e-19       None      0.2315903      0.1981294\n6          3.882489e-13       None      0.3947337      0.3765374\n```\n\n\n:::\n:::\n\n\nweighted UniFrac 的 3 个负特征值只占正特征值绝对和的 0.4551%。数值虽小，图与 Methods 仍明确标记 Lingoes correction。\n\n把主要中间结果保存为可审计 TSV：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"results/21-beta-distances\", recursive = TRUE, showWarnings = FALSE)\nreadr::write_tsv(\n  distance_summary,\n  \"results/21-beta-distances/distance-summary.tsv\"\n)\nreadr::write_tsv(\n  distance_correlation,\n  \"results/21-beta-distances/distance-correlation.tsv\"\n)\nreadr::write_tsv(\n  pcoa_eigen_audit,\n  \"results/21-beta-distances/pcoa-eigen-audit.tsv\"\n)\nreadr::write_tsv(\n  pcoa_scores,\n  \"results/21-beta-distances/pcoa-scores.tsv\"\n)\nreadr::write_tsv(\n  aitchison_pseudocount_sensitivity,\n  \"results/21-beta-distances/aitchison-pseudocount-sensitivity.tsv\"\n)\n```\n:::\n\n\n## 出版级美化 {#sec-figure}\n\n### 图 1：先展示“每个距离用了什么信息”\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchoice_grid <- tidyr::expand_grid(\n  Metric = metric_levels,\n  Signal = c(\"Abundance\", \"Occurrence\", \"Phylogeny\", \"Log-ratio\")\n)\nchoice_grid$Included <- with(\n  choice_grid,\n  (Metric == \"Bray-Curtis\" & Signal == \"Abundance\") |\n    (Metric == \"Jaccard\" & Signal == \"Occurrence\") |\n    (Metric == \"Unweighted UniFrac\" &\n      Signal %in% c(\"Occurrence\", \"Phylogeny\")) |\n    (Metric == \"Weighted UniFrac\" &\n      Signal %in% c(\"Abundance\", \"Phylogeny\")) |\n    (Metric %in% c(\"Aitchison\", \"Robust Aitchison\") &\n      Signal %in% c(\"Abundance\", \"Log-ratio\"))\n)\nchoice_grid$Label <- ifelse(choice_grid$Included, \"YES\", \"—\")\nchoice_grid$Metric <- factor(choice_grid$Metric, levels = rev(metric_levels))\nchoice_grid$Signal <- factor(\n  choice_grid$Signal,\n  levels = c(\"Abundance\", \"Occurrence\", \"Phylogeny\", \"Log-ratio\")\n)\n\nchoice_plot <- ggplot(\n  choice_grid,\n  aes(x = Signal, y = Metric, fill = Included)\n) +\n  geom_tile(colour = \"white\", linewidth = 1.1) +\n  geom_text(aes(label = Label), fontface = \"bold\", size = 3.2) +\n  scale_fill_manual(\n    values = c(`FALSE` = \"#ECEFF3\", `TRUE` = pal_pub[[\"sky\"]]),\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Distance metrics encode different biological contrasts\",\n    subtitle = \"Choose the signal before inspecting group separation\",\n    x = \"Information used by the metric\",\n    y = NULL,\n    caption = paste0(\n      \"Occurrence and UniFrac branches use 50,000 reads per sample.\\n\",\n      \"Aitchison branches use filtered unrarefied counts; classic CLR uses a declared pseudocount.\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text = element_text(face = \"bold\")\n  )\n\nsave_pub(\n  choice_plot,\n  \"figures/21-distance-choice-map\",\n  width = 183,\n  height = 92\n)\nchoice_plot\n```\n\n::: {.cell-output-display}\n![](21-beta-distances_files/figure-html/fig-distance-choice-1.png){#fig-distance-choice}\n:::\n:::\n\n\n图内只用英文，并把颜色作为辅助编码；“YES/—”文字使灰度打印和色觉差异下仍可读。\n\n### 图 2：距离相关热图\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrelation_plot_data <- distance_correlation\ncorrelation_plot_data$MetricX <- factor(\n  correlation_plot_data$MetricX,\n  levels = metric_levels\n)\ncorrelation_plot_data$MetricY <- factor(\n  correlation_plot_data$MetricY,\n  levels = rev(metric_levels)\n)\n\ncorrelation_plot <- ggplot(\n  correlation_plot_data,\n  aes(x = MetricX, y = MetricY, fill = Spearman)\n) +\n  geom_tile(colour = \"white\", linewidth = 0.7) +\n  geom_text(aes(label = sprintf(\"%.2f\", Spearman)), size = 2.8) +\n  scale_fill_gradientn(\n    colours = c(\"#F7F7F7\", \"#B8DCEB\", \"#0072B2\"),\n    limits = c(0, 1),\n    breaks = c(0, 0.5, 1)\n  ) +\n  labs(\n    title = \"Metric choice changes the rank order of sample pairs\",\n    subtitle = \"Spearman correlation across all 325 pairwise distances\",\n    x = NULL,\n    y = NULL,\n    fill = \"Spearman\\nrho\",\n    caption = \"High correlation in this dataset does not make two metric definitions interchangeable.\"\n  ) +\n  theme_pub(base_size = 8.5) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1),\n    legend.position = \"right\"\n  )\n\nsave_pub(\n  correlation_plot,\n  \"figures/21-distance-correlation\",\n  width = 183,\n  height = 112\n)\ncorrelation_plot\n```\n\n::: {.cell-output-display}\n![](21-beta-distances_files/figure-html/fig-distance-correlation-1.png){#fig-distance-correlation}\n:::\n:::\n\n\n### 图 3：同一样本的六种 PCoA 几何\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhabitat_levels <- c(\n  \"Human-associated\", \"Freshwater\", \"Marine/estuarine\", \"Soil\", \"Mock\"\n)\nhabitat_palette <- c(\n  \"Human-associated\" = pal_pub[[\"blue\"]],\n  \"Freshwater\" = pal_pub[[\"sky\"]],\n  \"Marine/estuarine\" = pal_pub[[\"green\"]],\n  \"Soil\" = pal_pub[[\"orange\"]],\n  \"Mock\" = pal_pub[[\"purple\"]]\n)\nhabitat_shapes <- c(\n  \"Human-associated\" = 21,\n  \"Freshwater\" = 22,\n  \"Marine/estuarine\" = 24,\n  \"Soil\" = 23,\n  \"Mock\" = 25\n)\n\npcoa_labels <- setNames(\n  vapply(metric_levels, function(metric) {\n    row <- pcoa_eigen_audit[pcoa_eigen_audit$Metric == metric, ]\n    correction_label <- ifelse(\n      row$Correction == \"Lingoes\",\n      \"\\nLingoes corrected\",\n      \"\"\n    )\n    sprintf(\n      \"%s\\nPCo 1 %.1f%% · PCo 2 %.1f%%%s\",\n      metric,\n      100 * row$Axis1Explained,\n      100 * row$Axis2Explained,\n      correction_label\n    )\n  }, character(1)),\n  metric_levels\n)\n\npcoa_plot_data <- pcoa_scores\npcoa_plot_data$Metric <- factor(pcoa_plot_data$Metric, levels = metric_levels)\npcoa_plot_data$HabitatClass <- factor(\n  pcoa_plot_data$HabitatClass,\n  levels = habitat_levels\n)\n\npcoa_plot <- ggplot(\n  pcoa_plot_data,\n  aes(\n    x = Axis1,\n    y = Axis2,\n    fill = HabitatClass,\n    shape = HabitatClass\n  )\n) +\n  geom_hline(yintercept = 0, colour = \"#D1D5DB\", linewidth = 0.3) +\n  geom_vline(xintercept = 0, colour = \"#D1D5DB\", linewidth = 0.3) +\n  geom_point(size = 2.2, stroke = 0.45, colour = \"#1F2937\", alpha = 0.92) +\n  facet_wrap(\n    ~Metric,\n    scales = \"free\",\n    ncol = 3,\n    labeller = as_labeller(pcoa_labels)\n  ) +\n  scale_fill_manual(values = habitat_palette, drop = FALSE) +\n  scale_shape_manual(values = habitat_shapes, drop = FALSE) +\n  labs(\n    title = \"The same samples occupy six different distance geometries\",\n    subtitle = \"GlobalPatterns 16S communities; each point is one sample\",\n    x = \"Principal coordinate 1\",\n    y = \"Principal coordinate 2\",\n    fill = \"Habitat\",\n    shape = \"Habitat\",\n    caption = \"Coordinates visualize distance structure; they are not tests of group separation.\"\n  ) +\n  theme_pub(base_size = 8.2) +\n  theme(\n    panel.grid = element_blank(),\n    legend.position = \"top\",\n    legend.title = element_text(face = \"bold\"),\n    strip.text = element_text(size = 7.1, lineheight = 0.95)\n  )\n\nsave_pub(\n  pcoa_plot,\n  \"figures/21-pcoa-metric-comparison\",\n  width = 183,\n  height = 132\n)\npcoa_plot\n```\n\n::: {.cell-output-display}\n![](21-beta-distances_files/figure-html/fig-pcoa-comparison-1.png){#fig-pcoa-comparison}\n:::\n:::\n\n\n颜色与形状同时编码 habitat，避免只依赖颜色。六个分面使用各自坐标尺度，因为不同距离的单位不同；分面间比较的是结构和相对位置，不是坐标绝对值。\n\n### 图 4：零值处理敏感性\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_a <- sample_ids[pair_indices[, 1L]]\nsample_b <- sample_ids[pair_indices[, 2L]]\npair_type <- ifelse(\n  metadata[sample_a, \"HabitatClass\"] == metadata[sample_b, \"HabitatClass\"],\n  \"Within habitat\",\n  \"Between habitats\"\n)\n\nzero_plot_data <- bind_rows(lapply(names(pseudocount_distances), function(pc) {\n  data.frame(\n    Pseudocount = pc,\n    ClassicAitchison = as.vector(pseudocount_distances[[pc]]),\n    RobustAitchison = as.vector(robust_aitchison),\n    PairType = pair_type\n  )\n}))\nzero_plot_data$Pseudocount <- factor(\n  zero_plot_data$Pseudocount,\n  levels = c(\"0.1\", \"0.5\", \"1.0\"),\n  labels = c(\"Pseudocount 0.1\", \"Pseudocount 0.5\", \"Pseudocount 1.0\")\n)\nzero_annotation <- data.frame(\n  Pseudocount = levels(zero_plot_data$Pseudocount),\n  Label = sprintf(\n    \"rho with robust = %.3f\",\n    aitchison_pseudocount_sensitivity$SpearmanToRobustAitchison\n  )\n)\nzero_annotation$Pseudocount <- factor(\n  zero_annotation$Pseudocount,\n  levels = levels(zero_plot_data$Pseudocount)\n)\n\nzero_plot <- ggplot(\n  zero_plot_data,\n  aes(\n    x = ClassicAitchison,\n    y = RobustAitchison,\n    colour = PairType\n  )\n) +\n  geom_point(size = 1.25, alpha = 0.62) +\n  geom_smooth(\n    aes(group = 1),\n    method = \"lm\",\n    formula = y ~ x,\n    se = FALSE,\n    linewidth = 0.55,\n    colour = \"#374151\",\n    show.legend = FALSE\n  ) +\n  geom_text(\n    data = zero_annotation,\n    aes(x = -Inf, y = Inf, label = Label),\n    inherit.aes = FALSE,\n    hjust = -0.05,\n    vjust = 1.35,\n    size = 2.7,\n    fontface = \"bold\"\n  ) +\n  facet_wrap(~Pseudocount, nrow = 1, scales = \"free_x\") +\n  scale_colour_manual(values = c(\n    \"Within habitat\" = pal_pub[[\"blue\"]],\n    \"Between habitats\" = pal_pub[[\"vermillion\"]]\n  )) +\n  labs(\n    title = \"Zero handling changes Aitchison geometry\",\n    subtitle = \"Classic pseudocount CLR versus observed-only Robust Aitchison\",\n    x = \"Classic Aitchison distance\",\n    y = \"Robust Aitchison distance\",\n    colour = \"Sample pair\",\n    caption = paste(\n      \"Both branches use the same 11,063 filtered features.\",\n      \"Robust Aitchison does not replace observed zeros with the displayed pseudocounts.\"\n    )\n  ) +\n  theme_pub(base_size = 8.5) +\n  theme(legend.position = \"top\")\n\nsave_pub(\n  zero_plot,\n  \"figures/21-aitchison-zero-sensitivity\",\n  width = 183,\n  height = 94\n)\nzero_plot\n```\n\n::: {.cell-output-display}\n![](21-beta-distances_files/figure-html/fig-zero-sensitivity-1.png){#fig-zero-sensitivity}\n:::\n:::\n\n\n四张图都同时导出 PDF、SVG、600 ppi PNG 和 LZW-TIFF。PDF/SVG 用于矢量排版，PNG 适合网页和公众号，TIFF 适合要求高分辨率位图的投稿系统。\n\n完整文件审计可一次运行：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nRscript --vanilla scripts/validate_beta_distances.R \\\n  --project-root . \\\n  --input-dir data/small/beta-distances \\\n  --output-dir results/21-beta-distances \\\n  --figure-dir figures \\\n  --gemelli-python .tools/gemelli-0.0.13/bin/python\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naudit_summary <- jsonlite::read_json(\n  \"results/21-beta-distances/beta-distances-summary.json\"\n)\nstopifnot(\n  audit_summary$checks_total == 239L,\n  audit_summary$checks_passed == 239L,\n  audit_summary$checks_failed == 0L,\n  audit_summary$graphics$primary_figures == 4L,\n  audit_summary$graphics$format_files == 16L\n)\n```\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最容易追问的八件事\"}\n\n1. **看到结果后挑距离。** 先运行六种方法，再选择分组最漂亮的一张，会产生未披露的 outcome-driven analysis。主距离应由研究问题预先指定，其他距离标为 sensitivity analysis。\n2. **presence/absence 不控制检测深度。** Jaccard 和 unweighted UniFrac 会把未检出当成缺失；测序深度不一致时，稀有 feature 漏检可直接制造距离。\n3. **树不合格仍算 UniFrac。** unrooted tree、缺 branch length、负 branch length 或 tip ID 不匹配，都应在计算前失败。\n4. **静默丢弃 tree/table 不相交的 feature。** 必须报告删除 feature 数、reads 和受影响样本；不能只保留交集后假装输入完整。\n5. **对相对丰度再做 CLR。** CLR 对整体缩放不敏感，但先转相对丰度再随意 zero replacement 会隐藏实际零处理。直接从过滤后的 counts 明报 pseudocount 更透明。\n6. **把 Robust Aitchison 写成“加 1 后 CLR”。** rclr/RPCA 只在观测项上中心化，并通过低秩模型处理缺失位置；算法和假设都不同。\n7. **忽略 PCoA 负特征值。** 至少保存数量、最小值与负/正比例；用了 Lingoes/Cailliez 必须在图注和 Methods 中写明。\n8. **把 PCoA 图当作检验。** 点云分开不等于组中心显著；PERMANOVA 还需与 dispersion test、实验单位和置换限制一起解释。\n\n:::\n\n::: {.callout-warning title=\"这个示例不能支持因果或广义生态结论\"}\n`GlobalPatterns` 只有 26 个样本，habitat 类别的样本数不平衡，且不同样本类型还伴随采样来源和实验背景差异。本页只比较距离定义与几何，不把 within/between 描述量解释为 habitat 的独立效应。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n下面英文模板与本页实际代码一致；换数据时修改方括号中的主距离、深度、分组变量和敏感性范围：\n\n> **Beta-diversity analysis.** Feature counts, seven-rank taxonomy, and sample metadata were imported as separate tab-delimited tables, and feature/sample identifiers were reconciled before analysis. For phylogenetic distances, a rooted tree with finite non-negative branch lengths was required to have an exact tip-set match to the count table. Bray–Curtis, binary Jaccard, unweighted UniFrac, and weighted UniFrac distances were calculated from a single rarefaction to 50,000 reads per sample with seed 20260722; all 26 samples were retained. Bray–Curtis distances from unrarefied relative abundances were additionally evaluated as a sensitivity analysis. For compositional distances, unrarefied features with total count >10 and prevalence >10% were retained (11,063 features). Classical Aitchison distances were calculated as Euclidean distances after centered log-ratio transformation with a pseudocount of 0.5, with 0.1 and 1.0 assessed for sensitivity. Robust Aitchison distances were estimated using observed-only robust CLR and rank-3 RPCA implemented in gemelli 0.0.13 (five OptSpace iterations; seed 20260722). Raw PCoA eigenvalues were audited for every distance; weighted UniFrac contained three small negative eigenvalues (absolute negative-to-positive eigenvalue ratio 0.00455) and was visualized after Lingoes correction. PCoA was used for visualization only; group inference was not based on ordination appearance.\n\n如果文章只预先指定一种主距离，可把其他五种压缩为 sensitivity analysis，并在主文/补充材料明确区分。不要把“所有距离都跑过”写成“结果稳健”，除非方向、效应量和推断结论确实一致。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n首先只改路径和计划用于着色的 metadata 列：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"your_project/otutab.tsv\",\n  taxonomy = \"your_project/taxonomy.tsv\",\n  metadata = \"your_project/metadata.tsv\",\n  tree = \"your_project/rooted-tree.nwk.gz\"\n)\ngroup_column <- \"Treatment\"\n```\n:::\n\n\n然后按研究问题选择主距离：\n\n- 关注优势类群丰度变化：优先考虑 Bray–Curtis；\n- 关注定殖/消失或稀有成员：考虑 Jaccard，但先控制检测深度；\n- 关注变化是否集中在系统发育分支：使用对应的 unweighted/weighted UniFrac，并先通过树门禁；\n- 关注组成型 log-ratio 差异：使用 Aitchison；零很多时同时评估 Robust Aitchison；\n- 研究方案没有预先指定时，可指定一个与生物学问题最匹配的 primary metric，并把其余方法写成有界的 sensitivity set。\n\n最低数据检查可以直接复用：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(\n  !anyDuplicated(rownames(otutab)),\n  !anyDuplicated(colnames(otutab)),\n  setequal(rownames(otutab), rownames(taxonomy)),\n  setequal(colnames(otutab), rownames(metadata)),\n  all(is.finite(otutab)),\n  all(otutab >= 0),\n  all(otutab == floor(otutab)),\n  all(colSums(otutab) > 0)\n)\n\nif (file.exists(input_paths[[\"tree\"]])) {\n  tree <- ape::read.tree(gzfile(input_paths[[\"tree\"]]))\n  stopifnot(\n    ape::is.rooted(tree),\n    !is.null(tree$edge.length),\n    all(is.finite(tree$edge.length)),\n    all(tree$edge.length >= 0),\n    setequal(tree$tip.label, rownames(otutab))\n  )\n}\n```\n:::\n\n\n抽平深度不能照抄 50,000。先检查自己的 `colSums(otutab)`、样本保留率和 presence/absence 稳定性；如果低深度样本很多，应回到研究问题与标准化策略，而不是为了保留全部样本把深度降到几乎没有检测能力。\n\n## 参考 {#sec-references}\n\n- Caporaso JG, Lauber CL, Walters WA, et al. Global patterns of 16S rRNA diversity at a depth of millions of sequences per sample. *Proceedings of the National Academy of Sciences*. 2011;108(Suppl 1):4516–4522. [doi:10.1073/pnas.1000080107](https://doi.org/10.1073/pnas.1000080107)\n- Bray JR, Curtis JT. An ordination of the upland forest communities of southern Wisconsin. *Ecological Monographs*. 1957;27(4):325–349. [doi:10.2307/1942268](https://doi.org/10.2307/1942268)\n- Jaccard P. Étude comparative de la distribution florale dans une portion des Alpes et du Jura. *Bulletin de la Société Vaudoise des Sciences Naturelles*. 1901;37:547–579. [doi:10.5169/seals-266450](https://doi.org/10.5169/seals-266450)\n- Lozupone C, Knight R. UniFrac: a new phylogenetic method for comparing microbial communities. *Applied and Environmental Microbiology*. 2005;71(12):8228–8235. [doi:10.1128/AEM.71.12.8228-8235.2005](https://doi.org/10.1128/AEM.71.12.8228-8235.2005)\n- Lozupone CA, Hamady M, Kelley ST, Knight R. Quantitative and qualitative beta diversity measures lead to different insights into factors that structure microbial communities. *Applied and Environmental Microbiology*. 2007;73(5):1576–1585. [doi:10.1128/AEM.01996-06](https://doi.org/10.1128/AEM.01996-06)\n- Aitchison J. The statistical analysis of compositional data. *Journal of the Royal Statistical Society Series B*. 1982;44(2):139–177. [doi:10.1111/j.2517-6161.1982.tb01195.x](https://doi.org/10.1111/j.2517-6161.1982.tb01195.x)\n- Martino C, Morton JT, Marotz CA, et al. A novel sparse compositional technique reveals microbial perturbations. *mSystems*. 2019;4(4):e00016-19. [doi:10.1128/mSystems.00016-19](https://doi.org/10.1128/mSystems.00016-19)\n- McMurdie PJ, Holmes S. phyloseq: an R package for reproducible interactive analysis and graphics of microbiome census data. *PLOS ONE*. 2013;8(4):e61217. [doi:10.1371/journal.pone.0061217](https://doi.org/10.1371/journal.pone.0061217)\n- Gower JC. Some distance properties of latent root and vector methods used in multivariate analysis. *Biometrika*. 1966;53(3–4):325–338. [doi:10.1093/biomet/53.3-4.325](https://doi.org/10.1093/biomet/53.3-4.325)\n- [`gemelli` maintained implementation and documentation](https://github.com/biocore/gemelli)\n",
    "supporting": [
      "21-beta-distances_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}