{
  "hash": "00255e2958861ba150f212bf49136661",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"实验设计：样本量、统计效力、分组与配对\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**在测序前定义独立实验单位、主要终点、分组/配对结构和统计效力；用真实 metadata 识别完全混杂，并用 pilot Shannon 差异完成可复算的样本量敏感性分析。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`。自己的研究还应在 metadata 中提供 `SubjectID`、`Block/Site/Cage`、`Batch` 和时间点等设计变量。  \n> **预计资源：**13,628 个 OTU、90 个样本；普通笔记本约 1–3 分钟，内存低于 500 MB。\n\n## 分析能否回答问题，首先由研究设计决定 {#sec-target}\n\n实验设计不会只出现在 Methods。严谨的微生物组论文通常需要一张研究流程图或设计概览，并在正文或补充材料中说明：\n\n- 每组有多少个**独立实验单位**；\n- 样本如何分层、随机化、配对或重复测量；\n- 主要终点和主要比较是什么；\n- 哪些批次、中心、笼位、家庭或个体因素需要控制；\n- 样本量依据的是何种效应量、方差、显著性水平和目标效力。\n\n本篇从真实中国湿地 16S 数据重绘两张设计审计图：\n\n::: {layout-ncol=2}\n![样本分组与盐碱状态的交叉表；空单元格揭示完全混杂。](../figures/03-design-confounding.png){#fig-design-confounding}\n\n![三种标准化效应量下，两独立组主要终点的样本量—效力敏感性曲线。](../figures/03-power-sensitivity.png){#fig-power-sensitivity}\n:::\n\n图 @fig-design-confounding 先回答“设计是否允许区分两个因素”；图 @fig-power-sensitivity 再回答“在给定假设下，大致需要多少独立样本”。顺序不能颠倒：样本再多，也不能从完全混杂的设计中分离两个效应。\n\n::: {.callout-important title=\"真正的 N 是独立实验单位数\"}\n同一只动物取 10 份粪便、同一位受试者测 10 个时间点，或同一笼内取 10 只共居动物，都不自动等于 $N=10$ 个独立重复。技术重复可以降低测量误差，纵向样本可以提高个体内变化的估计精度，但它们不能凭空增加独立受试者、笼位或样地的数量。\n:::\n\n## 从科学问题倒推设计 {#sec-theory}\n\n### 1. 先写清 estimand，再计算样本量\n\n**Estimand（目标估计量）**是研究真正要估计的量。例如：\n\n- 两个处理组在第 8 周 Shannon 指数的平均差；\n- 干预后整体群落 Bray–Curtis 距离中由处理解释的变异比例；\n- 某个预先指定菌属在病例与对照之间的对数丰度比；\n- 同一个体从基线到治疗后的变化量之组间差异。\n\n如果只写“比较两组菌群是否不同”，就无法唯一确定主要终点、统计检验、效应量或样本量。α 多样性、PERMANOVA、差异丰度和分类模型的效力函数不同，不能用一个通用的“每组至少 20 例”覆盖所有问题。\n\n### 2. 实验单位、观测单位和技术重复不是一回事\n\n- **实验单位（experimental unit）**：能够独立接受处理、暴露或被随机分组的最小单位。\n- **观测单位（observational unit）**：实际被测量的样本。\n- **技术重复（technical replicate）**：对同一生物材料重复提取、PCR 或测序。\n\n若处理施加在笼位，笼位通常是实验单位；若处理施加在动物，动物才可能是实验单位。共居动物共享环境和微生物来源，不能默认彼此独立。[Reish 等](https://doi.org/10.1128/aem.01033-24)审阅宿主—微生物组研究后指出，伪重复和实验单位描述不足仍很常见。\n\n### 3. 配对和重复测量要写进模型，而不是只连一条线\n\n配对设计通过比较同一个体内的变化，消除稳定的个体间差异。它通常比同样人数的完全独立设计更有效，但前提是：\n\n- 配对关系在 `SubjectID` 中明确记录；\n- 每个时间点的缺失机制被报告；\n- 模型包含个体随机截距或等价的配对结构；\n- 置换检验被限制在设计允许的交换范围内。\n\n一位受试者有两个时间点时，独立样本量仍是“受试者数/完整配对数”，不是样本管数。把 30 人 × 2 时间点写成 $N=60$ 个独立样本会造成伪重复。\n\n### 4. 平衡、随机化和阻断决定能否解释结果\n\n理想设计让主要比较在测序批次、提取批次、中心、笼位、板位和采样时间上尽量平衡。随机化用于降低已知和未知混杂；阻断（blocking）用于在不可避免的批次或空间结构内进行公平比较。\n\n最危险的情况是：\n\n> 所有病例在批次 A，所有对照在批次 B。\n\n此时“疾病效应”和“批次效应”不可辨识。统计校正不能从没有交叉信息的设计中估计两个独立效应。相同问题也会出现在地点与暴露、笼位与处理、中心与疾病完全重合时。\n\n### 5. 统计效力不是研究结束后的解释工具\n\n统计效力（power）是在真实效应达到预设大小时，研究拒绝零假设的概率。设计阶段至少要指定：\n\n1. 主要终点和统计模型；\n2. 有科学意义的最小效应；\n3. 方差或距离分布；\n4. 双侧显著性水平 $\\alpha$；\n5. 目标效力 $1-\\beta$；\n6. 组间比例、失访率和不可用样本率；\n7. 多重检验策略。\n\n研究结束后用观测到的 P 值计算“observed power”通常只是在重新表达 P 值，不能挽救阴性结果。更有信息的做法是报告效应量、置信区间，并说明研究能排除或无法排除多大的效应。\n\n<details>\n<summary><strong>深入：为什么 PERMANOVA 样本量不能直接照搬 t 检验</strong></summary>\n\n两独立组连续终点可用标准化均值差 $d$ 表示效应，并在给定分布假设下计算样本量。PERMANOVA 的效力则同时受到以下因素影响：\n\n- 组内群落距离分布和离散度；\n- 组间样本量及其不平衡；\n- 所选距离度量；\n- 群落组成与零值结构；\n- 协变量、分层和允许的置换方式；\n- 目标总体效应而非样本内偏高的 $R^2$。\n\n[Kelly 等](https://doi.org/10.1093/bioinformatics/btv183)提出基于 pilot 距离信息的 PERMANOVA 样本量估计，并强调样本 $R^2$ 对总体效应存在偏倚。[La Rosa 等](https://doi.org/10.1371/journal.pone.0052078)和[Ferdous 等](https://doi.org/10.1038/s41385-022-00548-1)也说明，微生物组效力计算必须与数据类型和检验对应。\n\n因此，本篇的曲线只针对一个明确的连续主要终点——固定测序深度下的 Shannon 指数——用于演示敏感性分析。若主要终点是 PERMANOVA、差异丰度或预测性能，应基于相应模型、pilot 数据和设计结构模拟，而不是把图中的 $n$ 直接套用。\n\n</details>\n\n::: {.callout-note title=\"真实数据中的设计警报\"}\n本例 90 个样本分为 inland wetland、coastal wetland 和 Tibetan Plateau 三组。30 个 non-saline 样本全部来自 inland wetland；60 个 saline 样本全部来自另外两组。因此 `Salinity` 与 `Group` 完全混杂，`Type` 也嵌套在 `Group` 内。盐碱状态的比较不能被解释为脱离地理/湿地类型的独立盐碱效应。\n:::\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、下载真实数据和定义作图函数</strong></summary>\n\n首次运行安装以下 CRAN 包：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"vegan\", \"ggplot2\", \"scales\", \"digest\", \"lme4\"\n))\n```\n:::\n\n\n数据固定使用 `microeco 2.0.0` 源码包中的真实湿地 16S 表。以下代码下载固定版本、核对 SHA-256，并导出扩增子通用三件套：\n\n\n::: {.cell}\n\n```{.r .cell-code}\narchive <- \"data/raw/microeco_2.0.0.tar.gz\"\nsource_url <- paste0(\n  \"https://cran.r-project.org/src/contrib/Archive/\",\n  \"microeco/microeco_2.0.0.tar.gz\"\n)\nexpected_sha256 <- paste0(\n  \"454a3b71ceeea86bdd54f475a12b5bac\",\n  \"9c3b124f663b8dc6e560827fca89ebfd\"\n)\n\ndir.create(\"data/raw\", recursive = TRUE, showWarnings = FALSE)\ndir.create(\"data/small\", recursive = TRUE, showWarnings = FALSE)\nif (!file.exists(archive)) {\n  download.file(source_url, archive, mode = \"wb\")\n}\nobserved_sha256 <- digest::digest(\n  file = archive,\n  algo = \"sha256\",\n  serialize = FALSE\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\nrequired <- c(\n  \"microeco/data/otu_table_16S.RData\",\n  \"microeco/data/taxonomy_table_16S.RData\",\n  \"microeco/data/sample_info_16S.RData\"\n)\nextract_dir <- tempfile(\"microeco-data-\")\ndir.create(extract_dir)\nutils::untar(archive, files = required, exdir = extract_dir)\n\ndata_env <- new.env(parent = emptyenv())\nfor (relative_path in required) {\n  load(file.path(extract_dir, relative_path), envir = data_env)\n}\n\nwrite_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name),\n    x,\n    check.names = FALSE\n  )\n  utils::write.table(\n    out,\n    path,\n    sep = \"\\t\",\n    quote = FALSE,\n    row.names = FALSE,\n    na = \"\"\n  )\n}\n\nwrite_tsv(data_env$otu_table_16S, \"FeatureID\", \"data/small/otutab.tsv\")\nwrite_tsv(\n  data_env$taxonomy_table_16S,\n  \"FeatureID\",\n  \"data/small/taxonomy.tsv\"\n)\nwrite_tsv(\n  data_env$sample_info_16S,\n  \"SampleID\",\n  \"data/small/metadata.tsv\"\n)\nunlink(extract_dir, recursive = TRUE)\n```\n:::\n\n\n出版级函数直接定义在文章内：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vegan)\nlibrary(ggplot2)\n\nset.seed(20260718)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(color = \"black\", linewidth = 0.3),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 120,\n  height = 95,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 从三件套读取并核对设计\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"data/small/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"data/small/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(otutab >= 0),\n  all(otutab == floor(otutab)),\n  all(colSums(otutab) > 0),\n  all(c(\"Group\", \"Type\", \"Saline\") %in% colnames(metadata))\n)\n\ndim(otutab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n```\n\n\n:::\n\n```{.r .cell-code}\notutab[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxonomy[1:5, , drop = FALSE]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\n                         Class               Order               Family Genus\nOTU_4272            c__Bacilli       o__Bacillales                  f__   g__\nOTU_236                    c__                 o__                  f__   g__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae   g__\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__   g__\nOTU_32                     c__                 o__                  f__   g__\n         Species\nOTU_4272     s__\nOTU_236      s__\nOTU_399      s__\nOTU_1556     s__\nOTU_32       s__\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n:::\n\n\n### 2. 画出交叉表，而不是只看每列频数\n\n单独运行 `table(metadata$Group)` 和 `table(metadata$Saline)` 都会得到看似合理的样本量；只有交叉表能暴露两个变量没有交叉。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_labels <- c(\n  IW = \"Inland wetland\",\n  CW = \"Coastal wetland\",\n  TW = \"Tibetan Plateau\"\n)\n\nmetadata$GroupLabel <- unname(group_labels[metadata$Group])\nmetadata$Salinity <- factor(\n  metadata$Saline,\n  levels = c(\"Non-saline soil\", \"Saline soil\")\n)\nstopifnot(!anyNA(metadata$GroupLabel), !anyNA(metadata$Salinity))\n\ndesign_counts <- as.data.frame(\n  with(metadata, table(GroupLabel, Salinity)),\n  responseName = \"Count\"\n)\ndesign_counts$Observed <- factor(\n  design_counts$Count > 0,\n  levels = c(FALSE, TRUE),\n  labels = c(\"Empty design cell\", \"Observed samples\")\n)\ndesign_counts$CellLabel <- ifelse(\n  design_counts$Count == 0,\n  \"Not\\nobserved\",\n  paste0(\"n = \", design_counts$Count)\n)\n\ndesign_matrix <- xtabs(Count ~ GroupLabel + Salinity, design_counts)\ntype_matrix <- with(metadata, table(Group, Type))\n\ndesign_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Salinity\nGroupLabel        Non-saline soil Saline soil\n  Coastal wetland               0          30\n  Inland wetland               30           0\n  Tibetan Plateau               0          30\n```\n\n\n:::\n\n```{.r .cell-code}\ntype_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Type\nGroup NC NE NW QTP SC YML\n   CW  9  0  0   0 18   3\n   IW  0 24  6   0  0   0\n   TW  0  0  0  30  0   0\n```\n\n\n:::\n\n```{.r .cell-code}\nperfect_group_salinity_confounding <- all(\n  rowSums(design_matrix > 0) == 1\n)\ntype_nested_within_group <- all(\n  colSums(type_matrix > 0) == 1\n)\n\nstopifnot(\n  perfect_group_salinity_confounding,\n  type_nested_within_group\n)\n```\n:::\n\n\n结果显示：\n\n- `Inland wetland` 的 30 个样本全部是 `Non-saline soil`；\n- `Coastal wetland` 和 `Tibetan Plateau` 各 30 个样本，全部是 `Saline soil`；\n- 六个 `Type` 水平分别只出现在一个 `Group` 中。\n\n因此，在这份数据里拟合 `outcome ~ Group + Salinity` 不能得到可识别的两个独立效应。软件可能删除共线项或返回秩亏模型，但这不是“完成了统计校正”。\n\n### 3. 用固定深度计算 pilot Shannon 指数\n\n为了让本例的随机抽样可复现，先把每个样本稀释到最小测序深度，再计算 Shannon 指数。这里的目的只是构造一个明确的连续主要终点进行样本量敏感性分析；稀释并不是所有 α 多样性推断的默认答案。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary_sizes <- colSums(otutab)\nrarefaction_depth <- min(library_sizes)\n\nset.seed(20260718)\notutab_rarefied <- t(\n  vegan::rrarefy(\n    t(otutab),\n    sample = rarefaction_depth\n  )\n)\n\nstopifnot(\n  all(colSums(otutab_rarefied) == rarefaction_depth),\n  identical(colnames(otutab_rarefied), rownames(metadata))\n)\n\nshannon <- vegan::diversity(\n  t(otutab_rarefied),\n  index = \"shannon\"\n)\n\nalpha_df <- data.frame(\n  SampleID = names(shannon),\n  Shannon = as.numeric(shannon),\n  Salinity = metadata[names(shannon), \"Salinity\"],\n  Group = metadata[names(shannon), \"GroupLabel\"],\n  stringsAsFactors = FALSE\n)\n\nalpha_summary <- do.call(\n  rbind,\n  lapply(split(alpha_df$Shannon, alpha_df$Salinity), function(x) {\n    data.frame(\n      N = length(x),\n      Mean = mean(x),\n      SD = stats::sd(x)\n    )\n  })\n)\n\nalpha_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 N     Mean        SD\nNon-saline soil 30 6.562007 0.3414035\nSaline soil     60 6.458448 0.5005029\n```\n\n\n:::\n:::\n\n\n稀释深度为每样本 10,364 reads。`Non-saline soil` 的 Shannon 均值为 6.562（$n=30$），`Saline soil` 为 6.458（$n=60$）。\n\n### 4. 估计标准化差异及其不确定性\n\n这里把效应方向定义为 `Non-saline soil − Saline soil`，用 pooled SD 标准化。bootstrap 在每组内部有放回抽样 2,000 次，并固定随机种子。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohen_d <- function(x, y) {\n  nx <- length(x)\n  ny <- length(y)\n  pooled_sd <- sqrt(\n    ((nx - 1) * stats::var(x) + (ny - 1) * stats::var(y)) /\n      (nx + ny - 2)\n  )\n  (mean(x) - mean(y)) / pooled_sd\n}\n\nshannon_non_saline <- subset(\n  alpha_df,\n  Salinity == \"Non-saline soil\"\n)$Shannon\nshannon_saline <- subset(\n  alpha_df,\n  Salinity == \"Saline soil\"\n)$Shannon\n\npilot_d <- cohen_d(\n  shannon_non_saline,\n  shannon_saline\n)\n\nset.seed(20260718)\nbootstrap_d <- replicate(2000, {\n  x_boot <- sample(\n    shannon_non_saline,\n    length(shannon_non_saline),\n    replace = TRUE\n  )\n  y_boot <- sample(\n    shannon_saline,\n    length(shannon_saline),\n    replace = TRUE\n  )\n  cohen_d(x_boot, y_boot)\n})\nbootstrap_d <- bootstrap_d[is.finite(bootstrap_d)]\npilot_ci <- unname(\n  stats::quantile(\n    bootstrap_d,\n    probs = c(0.025, 0.975)\n  )\n)\n\npilot_test <- stats::t.test(\n  shannon_non_saline,\n  shannon_saline,\n  var.equal = FALSE\n)\n\ndata.frame(\n  CohenD = pilot_d,\n  BootstrapLower = pilot_ci[1],\n  BootstrapUpper = pilot_ci[2],\n  WelchP = pilot_test$p.value\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     CohenD BootstrapLower BootstrapUpper    WelchP\n1 0.2279665     -0.1722814      0.5765388 0.2521634\n```\n\n\n:::\n:::\n\n\n本例得到 $d=0.228$，bootstrap 95% CI 为 -0.172 到 0.577，Welch 检验 $P=0.252$。区间跨过 0，效应估计很不精确；更重要的是，盐碱状态与湿地组完全混杂，所以这个 $d$ 不能解释为独立的盐碱效应。\n\n### 5. 做 prospective sensitivity analysis\n\n假设未来研究：\n\n- 以一个连续主要终点为主；\n- 两个独立组样本量相等；\n- 双侧 $\\alpha=0.05$；\n- 目标 power = 80%；\n- 标准化效应分别为 0.20、当前 pilot 点估计和 0.50。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot_effect <- abs(pilot_d)\neffect_scenarios <- data.frame(\n  Scenario = c(\n    \"Small effect\",\n    \"Pilot estimate\",\n    \"Moderate effect\"\n  ),\n  Effect = c(0.20, pilot_effect, 0.50),\n  stringsAsFactors = FALSE\n)\n\nn_grid <- seq(10, 450, by = 2)\n\npower_curve <- do.call(\n  rbind,\n  lapply(seq_len(nrow(effect_scenarios)), function(i) {\n    effect <- effect_scenarios$Effect[i]\n    data.frame(\n      NPerGroup = n_grid,\n      Power = vapply(\n        n_grid,\n        function(n) {\n          stats::power.t.test(\n            n = n,\n            delta = effect,\n            sd = 1,\n            sig.level = 0.05,\n            type = \"two.sample\",\n            alternative = \"two.sided\"\n          )$power\n        },\n        numeric(1)\n      ),\n      Scenario = effect_scenarios$Scenario[i],\n      Effect = effect\n    )\n  })\n)\n\nn80 <- effect_scenarios\nn80$NPerGroup <- vapply(\n  n80$Effect,\n  function(effect) {\n    ceiling(\n      stats::power.t.test(\n        delta = effect,\n        sd = 1,\n        sig.level = 0.05,\n        power = 0.80,\n        type = \"two.sample\",\n        alternative = \"two.sided\"\n      )$n\n    )\n  },\n  numeric(1)\n)\nn80$Power <- 0.80\n\ncurrent_smaller_group <- min(table(alpha_df$Salinity))\ncurrent_pilot_power <- stats::power.t.test(\n  n = current_smaller_group,\n  delta = pilot_effect,\n  sd = 1,\n  sig.level = 0.05,\n  type = \"two.sample\",\n  alternative = \"two.sided\"\n)$power\n\nn80\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Scenario    Effect NPerGroup Power\n1    Small effect 0.2000000       394   0.8\n2  Pilot estimate 0.2279665       304   0.8\n3 Moderate effect 0.5000000        64   0.8\n```\n\n\n:::\n:::\n\n\n若把 $d=0.228$ 当作未来研究的规划值，在这些理想化假设下达到 80% power 约需每组 304 个独立样本；当前较小组的 $n=30$ 对该效应只有约 13.8% 的理论效力。由于 pilot 效应不确定且存在混杂，正式方案应同时比较多个效应情景，并增加失访、提取失败和质控淘汰余量。\n\n## 出版级美化 {#sec-polish}\n\n### 1. 设计混杂热图\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndesign_counts$GroupLabel <- factor(\n  design_counts$GroupLabel,\n  levels = rev(c(\n    \"Inland wetland\",\n    \"Coastal wetland\",\n    \"Tibetan Plateau\"\n  ))\n)\n\ndesign_fill <- c(\n  \"Empty design cell\" = \"#F6D6D6\",\n  \"Observed samples\" = \"#2878A8\"\n)\n\np_design_confounding <- ggplot(\n  design_counts,\n  aes(Salinity, GroupLabel, fill = Observed)\n) +\n  geom_tile(\n    color = \"white\",\n    linewidth = 1.5,\n    width = 0.96,\n    height = 0.90\n  ) +\n  geom_text(\n    aes(\n      label = CellLabel,\n      color = Observed\n    ),\n    size = 4.0,\n    fontface = \"bold\",\n    lineheight = 0.9\n  ) +\n  scale_fill_manual(\n    values = design_fill,\n    name = \"Design cell\"\n  ) +\n  scale_color_manual(\n    values = c(\n      \"Empty design cell\" = \"#8B1A1A\",\n      \"Observed samples\" = \"white\"\n    ),\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Salinity is completely confounded with wetland group\",\n    subtitle = paste0(\n      \"Only 3 of 6 design cells are observed\\n\",\n      \"Geography and salinity cannot be separated\"\n    ),\n    x = \"Salinity category\",\n    y = \"Wetland group\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(\n      color = \"grey35\",\n      size = 9.2,\n      lineheight = 0.95\n    ),\n    axis.title = element_text(face = \"bold\"),\n    axis.text = element_text(face = \"bold\"),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\")\n  ) +\n  guides(fill = guide_legend(nrow = 1, byrow = TRUE))\n\np_design_confounding\n```\n\n::: {.cell-output-display}\n![](03-study-design_files/figure-html/unnamed-chunk-9-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_design_confounding,\n  \"figures/03-design-confounding\",\n  width = 172,\n  height = 112\n)\n```\n:::\n\n\n### 2. 样本量—效力敏感性曲线\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscenario_labels <- c(\n  \"Small effect\" = \"Small effect (d = 0.20)\",\n  \"Pilot estimate\" = sprintf(\n    \"Pilot estimate (d = %.2f)\",\n    pilot_effect\n  ),\n  \"Moderate effect\" = \"Moderate effect (d = 0.50)\"\n)\n\npower_curve$ScenarioLabel <- factor(\n  unname(scenario_labels[power_curve$Scenario]),\n  levels = unname(scenario_labels)\n)\nn80$ScenarioLabel <- factor(\n  unname(scenario_labels[n80$Scenario]),\n  levels = unname(scenario_labels)\n)\n\npower_colors <- stats::setNames(\n  c(\"#7A5195\", \"#0072B2\", \"#009E73\"),\n  unname(scenario_labels)\n)\n\np_power_sensitivity <- ggplot(\n  power_curve,\n  aes(NPerGroup, Power, color = ScenarioLabel)\n) +\n  geom_hline(\n    yintercept = 0.80,\n    linetype = \"dashed\",\n    color = \"grey35\",\n    linewidth = 0.6\n  ) +\n  geom_vline(\n    xintercept = current_smaller_group,\n    linetype = \"dotted\",\n    color = \"#D55E00\",\n    linewidth = 0.7\n  ) +\n  geom_line(linewidth = 1.15) +\n  geom_point(\n    data = n80,\n    aes(NPerGroup, Power, color = ScenarioLabel),\n    inherit.aes = FALSE,\n    size = 2.6\n  ) +\n  annotate(\n    \"text\",\n    x = 442,\n    y = 0.845,\n    label = \"80% target\",\n    hjust = 1,\n    vjust = 0,\n    size = 3.1,\n    color = \"grey25\"\n  ) +\n  annotate(\n    \"text\",\n    x = current_smaller_group + 5,\n    y = 0.24,\n    label = paste0(\n      \"Current smaller group\\nn = \",\n      current_smaller_group\n    ),\n    hjust = 0,\n    size = 3.0,\n    color = \"#B24716\"\n  ) +\n  scale_color_manual(\n    values = power_colors,\n    name = \"Planning scenario\"\n  ) +\n  scale_x_continuous(\n    breaks = sort(unique(c(\n      10,\n      current_smaller_group,\n      100,\n      200,\n      n80$NPerGroup,\n      450\n    ))),\n    limits = c(10, 450),\n    expand = expansion(mult = c(0.01, 0.01))\n  ) +\n  scale_y_continuous(\n    limits = c(0, 1),\n    breaks = seq(0, 1, by = 0.2),\n    labels = scales::percent_format(accuracy = 1),\n    expand = expansion(mult = c(0, 0.02))\n  ) +\n  labs(\n    title = \"Power depends on the effect worth detecting\",\n    subtitle = paste0(\n      \"Two equal independent groups · two-sided alpha = 0.05 · \",\n      \"continuous primary endpoint\"\n    ),\n    x = \"Independent samples per group\",\n    y = \"Theoretical power\"\n  ) +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(color = \"grey35\", size = 9.2),\n    axis.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\")\n  ) +\n  guides(color = guide_legend(nrow = 2, byrow = TRUE))\n\np_power_sensitivity\n```\n\n::: {.cell-output-display}\n![](03-study-design_files/figure-html/unnamed-chunk-10-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_power_sensitivity,\n  \"figures/03-power-sensitivity\",\n  width = 178,\n  height = 118\n)\n```\n:::\n\n\n两张图均导出为 PDF、PNG 和 300 dpi LZW-TIFF。图内所有文字均为英文；正文负责解释研究设计的生物学含义。\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最容易指出的十个设计问题\"}\n1. **把样本管数当独立样本数。** 同一个体、同一笼、同一地块或同一家庭内的观测往往相关。\n2. **所有病例与对照分属不同批次。** 完全混杂时，任何批次校正方法都不能恢复缺失的交叉设计。\n3. **先收集数据，再从多个终点挑显著者。** 应预先指定主要终点、主要比较和多重检验策略。\n4. **用固定经验数代替 power analysis。** “每组 20 个”没有说明效应、方差、模型、失访率或目标效力。\n5. **把 pilot 点估计当真实效应。** 小 pilot 的效应常被高估；应使用置信区间、保守情景或最小有意义效应。\n6. **报告事后 observed power。** 阴性结果应看效应量与置信区间，而不是从同一个 P 值反推效力。\n7. **配对采样却按独立样本检验。** 忽略 `SubjectID` 会低估标准误，也浪费配对带来的信息。\n8. **只在测序阶段随机化。** 采样、保存、提取、PCR、建库和测序都可能引入批次，需要全链路平衡。\n9. **多变量模型塞入过多协变量。** 小样本、稀疏分层和共线性会导致不可识别或极不稳定的估计。\n10. **只按 α 多样性估样本量，却把差异菌作为主要结论。** 每类主要终点都应有对应的效力或模拟依据。\n:::\n\n::: {.callout-warning title=\"样本量曲线不是本数据的因果结论\"}\n图 @fig-power-sensitivity 使用当前数据的 Shannon 标准化差异作为一个不确定的规划情景。它不证明盐碱状态影响 Shannon，也不意味着所有 16S 研究都需要每组 304 例。你的效应、方差、组间比例、配对相关、协变量和主要统计模型改变后，样本量会随之改变。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n下面模板把实验单位、主要终点、混杂检查和样本量假设写完整。方括号内容应在研究开始前按方案替换：\n\n> **Study design and sample-size planning.** The independent experimental unit was the [participant/animal/cage/site], and the prespecified primary comparison was [contrast] for [primary endpoint] at [time point]. Samples were randomized across extraction, PCR, library-preparation, and sequencing batches within [blocking factors]. Repeated observations from the same experimental unit were linked by a unique subject identifier and were analyzed using [paired/mixed-effects/restricted-permutation model]. Before analysis, contingency tables were used to identify empty design cells and complete confounding among treatment, site, batch, and other design variables. Sample size was planned for a two-sided type-I error rate of 0.05 and 80% power to detect a standardized effect of [d], with [n] independent units per group after allowing [x%] attrition.\n\n本例可这样描述，但必须保留其限制：\n\n> **Worked design audit.** The worked dataset comprised 90 soil samples (30 inland-wetland, 30 coastal-wetland, and 30 Tibetan-Plateau samples). Salinity was completely confounded with wetland group: all 30 non-saline samples belonged to the inland-wetland group, whereas all 60 saline samples belonged to the other two groups. Consequently, salinity and wetland-group effects were not separately identifiable. For an illustrative sensitivity analysis, Shannon diversity was calculated after rarefaction to 10,364 reads per sample. The standardized non-saline versus saline difference was $d=0.228$ (2,000-resample bootstrap 95% CI -0.172 to 0.577). Under an idealized equal-size two-sample design with two-sided $\\alpha=0.05$, detecting an effect of this magnitude with 80% power would require approximately 304 independent samples per group. This calculation was treated as a planning scenario rather than evidence for an independent salinity effect.\n\nResults 中建议同时报告：\n\n- 各组独立实验单位数和观测样本数；\n- 缺失、质控淘汰和完整配对数量；\n- 主要效应量及 95% CI；\n- 实际使用的阻断、随机效应和置换限制；\n- 与预注册/方案相比的任何偏离。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. metadata 至少要记录什么\n\n标准三件套路径只需替换为你的文件。metadata 每行对应一个样本，建议至少包含：\n\n| 列名 | 含义 | 示例 |\n|---|---|---|\n| `SampleID` | 与 OTU/ASV 表列名一致的唯一 ID | `S001_T0` |\n| `Group` | 主要暴露或处理组 | `Control`, `Treatment` |\n| `SubjectID` | 独立个体/地块/笼位 ID | `P001` |\n| `Time` | 时间点 | `Baseline`, `Week8` |\n| `Block` | 分层、中心、笼或样地 | `Center1` |\n| `ExtractionBatch` | DNA 提取批次 | `E01` |\n| `PCRPlate` | PCR/建库板 | `P02` |\n| `SequencingRun` | 测序批次 | `Run1` |\n| 协变量 | 预先指定的年龄、性别、药物、pH 等 | 数值或因子 |\n\n独立个体横断面研究没有重复测量时，`SubjectID` 仍应存在，并与每个独立单位一一对应。若处理施加在笼或样地，`SubjectID` 应改为真正接受处理的单位，而不是每只动物或每个土芯。\n\n### 2. 先运行三张设计表\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"your_data/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"your_data/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"your_data/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata))\n)\n\n# 主要分组是否跨批次平衡？\nxtabs(~ Group + ExtractionBatch, data = metadata)\nxtabs(~ Group + SequencingRun, data = metadata)\n\n# 每个独立单位有几个时间点？\nxtabs(~ SubjectID + Time, data = metadata)\n\n# 关键协变量是否在各组都有观测？\nxtabs(~ Group + Site, data = metadata)\n```\n:::\n\n\n看到 0 单元格时，不是所有情况都必须放弃研究；但要判断它代表随机缺失、稀疏分层，还是两个变量完全重合。完全重合的效应无法通过增加模型项分离。\n\n### 3. 配对或纵向终点\n\n两个完整时间点的连续终点可先计算个体内差值；多个时间点或不完整随访更适合混合模型：\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 两时间点的配对检验\nwide <- reshape(\n  alpha_df[, c(\"SubjectID\", \"Time\", \"Shannon\")],\n  idvar = \"SubjectID\",\n  timevar = \"Time\",\n  direction = \"wide\"\n)\nstats::t.test(\n  wide$Shannon.Followup,\n  wide$Shannon.Baseline,\n  paired = TRUE\n)\n\n# 多时间点混合模型：独立 N 是 SubjectID 数\nfit_alpha <- lme4::lmer(\n  Shannon ~ Group * Time + ExtractionBatch + (1 | SubjectID),\n  data = alpha_df\n)\nsummary(fit_alpha)\n```\n:::\n\n\n若整体群落差异使用 PERMANOVA，置换必须与配对/阻断结构一致：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260718)\nbray <- vegan::vegdist(\n  t(otutab / rep(colSums(otutab), each = nrow(otutab))),\n  method = \"bray\"\n)\n\nperm_design <- permute::how(\n  within = permute::Within(type = \"free\"),\n  blocks = metadata$SubjectID,\n  nperm = 999\n)\n\nvegan::adonis2(\n  bray ~ Group * Time + ExtractionBatch,\n  data = metadata,\n  permutations = perm_design,\n  by = \"margin\"\n)\n```\n:::\n\n\n允许怎样置换取决于随机化和采样结构。若时间有固定顺序、存在嵌套笼位/中心，或组别是个体间因素，不能机械套用“按 SubjectID 分块”；应先把可交换单位画清楚，再定义置换方案。\n\n### 4. 把样本量变成可审查的假设\n\n正式方案至少保存一张情景表：\n\n| 情景 | 效应量 | 每组 N | 失访/失败率 | 最终招募量 | 依据 |\n|---|---:|---:|---:|---:|---|\n| 保守 | 最小有意义效应 | 由模型计算 | 预估比例 | 向上取整 | 生物学阈值 |\n| 中间 | 外部研究/高质量 pilot | 由模型计算 | 预估比例 | 向上取整 | 文献或 pilot |\n| 乐观 | 较大效应 | 由模型计算 | 预估比例 | 向上取整 | 敏感性分析 |\n\n如果主要结论有多个层级，应明确一个主要终点作为样本量核心，再对 PERMANOVA、差异丰度、纵向交互或分类性能进行模拟敏感性分析。所有计算都应基于**独立实验单位数**，最后再把失访、提取失败、污染剔除和低深度样本按比例加回招募量。\n\n## 参考 {#sec-references}\n\n1. An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n2. Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n3. Kelly BJ, Gross R, Bittinger K, et al. Power and sample-size estimation for microbiome studies using pairwise distances and PERMANOVA. *Bioinformatics*. 2015;31(15):2461–2468. [doi:10.1093/bioinformatics/btv183](https://doi.org/10.1093/bioinformatics/btv183)\n4. La Rosa PS, Brooks JP, Deych E, et al. Hypothesis testing and power calculations for taxonomic-based human microbiome data. *PLOS ONE*. 2012;7(12):e52078. [doi:10.1371/journal.pone.0052078](https://doi.org/10.1371/journal.pone.0052078)\n5. Ferdous T, Jiang J, Anderson G, et al. The rise to power of the microbiome: power and sample size calculation for microbiome studies. *Mucosal Immunology*. 2022;15:1060–1070. [doi:10.1038/s41385-022-00548-1](https://doi.org/10.1038/s41385-022-00548-1)\n6. Reish HM, Dewey L, Kirschman LJ. A host of issues: pseudoreplication in host–microbiota studies. *Applied and Environmental Microbiology*. 2024;90(8). [doi:10.1128/aem.01033-24](https://doi.org/10.1128/aem.01033-24)\n7. Anderson MJ. A new method for non-parametric multivariate analysis of variance. *Austral Ecology*. 2001;26(1):32–46. [doi:10.1111/j.1442-9993.2001.01070.pp.x](https://doi.org/10.1111/j.1442-9993.2001.01070.pp.x)\n8. Knight R, Vrbanac A, Taylor BC, et al. Best practices for analysing microbiomes. *Nature Reviews Microbiology*. 2018;16:410–422. [doi:10.1038/s41579-018-0029-9](https://doi.org/10.1038/s41579-018-0029-9)\n",
    "supporting": [
      "03-study-design_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}