{
  "hash": "42ff82ff6efbfb449bace6a9457907db",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"非约束排序：PCoA/NMDS/CLR-PCA（复现顶刊）\"\nauthor: \"Peter\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/22-ordination-unconstrained.R\n  packages:\n  - ggplot2\n  - scales\n  - vegan\n---\n\n## 排序图展示的是距离结构，不是组间检验 {#sec-target}\n\n微生物组论文中常见的“每个点代表一个样本、颜色代表分组、椭圆概括组内分布”的散点图，回答的是：\n\n> 不同实验组的整体群落组成是否存在系统性差异？\n\n本例使用中国湿地土壤 16S 数据。原始研究覆盖中国内陆、沿海和青藏高原湿地，并指出 pH 与电导率是重要环境因子；`microeco` 将其中一组标准 OTU、分类和样本表作为公开示例数据分发。[原始数据论文（An et al., 2019）](https://doi.org/10.1016/j.geoderma.2018.09.035)与[`microeco` 软件论文（Liu et al., 2021）](https://doi.org/10.1093/femsec/fiaa255)提供了可引用的数据与软件出处。\n\n从公开表格重新计算的 PCoA 同时满足以下要求：\n\n- X/Y 轴为 `PCoA 1` 和 `PCoA 2`，括号内给出轴解释比例；\n- 点按 `Non-saline soil` 与 `Saline soil` 着色；\n- 图内同时报告 PERMANOVA 的 \\(R^2\\)、P 值和 dispersion test 的 P 值；\n- PDF 用于排版，PNG/TIFF 为 300 dpi。\n\n::: {.callout-important title=\"图和检验回答的不是同一件事\"}\nPCoA 展示距离矩阵的主要结构；PERMANOVA 检验组中心是否存在差异；`betadisper` 检查组内离散度是否不同。只有散点“看起来分开”不能替代统计检验，PERMANOVA 显著也必须结合离散度结果解释。\n:::\n\n## 下载并读取本次分析的数据 {#sec-setup}\n\n需要 R，以及 `ggplot2`、`scales`、`vegan`。本次使用中国湿地的 OTU count 表、分类表和样本信息表，以及本次分析使用的实测环境变量或系统发育信息。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"data/small/environment.tsv\",\n  \"data/small/metadata.tsv\",\n  \"data/small/otutab.tsv\",\n  \"data/small/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vegan)\nlibrary(ggplot2)\n\nset.seed(20260718)\n\npal_pub <- c(\n  \"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\",\n  \"#E69F00\", \"#56B4E9\", \"#F0E442\", \"#999999\"\n)\n\nscale_color_pub <- function(...) {\n  ggplot2::scale_color_manual(values = pal_pub, ...)\n}\n\nscale_fill_pub <- function(...) {\n  ggplot2::scale_fill_manual(values = pal_pub, ...)\n}\n\ntheme_pub <- function(base_size = 12) {\n  ggplot2::theme_bw(base_size = base_size, base_family = \"sans\") +\n    ggplot2::theme(\n      panel.grid = ggplot2::element_blank(),\n      axis.text = ggplot2::element_text(color = \"black\"),\n      axis.ticks = ggplot2::element_line(color = \"black\", linewidth = 0.3),\n      legend.key = ggplot2::element_blank(),\n      legend.background = ggplot2::element_rect(\n        fill = scales::alpha(\"white\", 0.7),\n        color = NA\n      )\n    )\n}\n\nsave_pub <- function(\n  plot,\n  file_base,\n  width = 120,\n  height = 95,\n  units = \"mm\",\n  dpi = 300\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    device = grDevices::cairo_pdf\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    bg = \"white\"\n  )\n  ggplot2::ggsave(\n    paste0(file_base, \".tiff\"),\n    plot,\n    width = width,\n    height = height,\n    units = units,\n    dpi = dpi,\n    compression = \"lzw\",\n    bg = \"white\"\n  )\n  invisible(plot)\n}\n```\n:::\n\n\n### 读取三件套并检查方向\n\nOTU 表必须是“特征 × 样本”，taxonomy 的行名与 OTU 特征一致，metadata 的行名与 OTU 样本一致。\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"data/small/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"data/small/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"data/small/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\notutab <- as.matrix(otutab)\nstorage.mode(otutab) <- \"numeric\"\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata)),\n  all(otutab >= 0),\n  all(colSums(otutab) > 0)\n)\n\ndim(otutab)\notutab[1:5, 1:5]\ntaxonomy[1:5, , drop = FALSE]\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13628    90\n         S1 S2 S3 S4  S5\nOTU_4272  1  0  1  1   0\nOTU_236   1  4  0  2  35\nOTU_399   9  2  2  4   4\nOTU_1556  5 18  7  3   2\nOTU_32   83  9 19  8 102\n             Kingdom                                Phylum\nOTU_4272 k__Bacteria                         p__Firmicutes\nOTU_236  k__Bacteria                        p__Chloroflexi\nOTU_399  k__Bacteria                     p__Proteobacteria\nOTU_1556 k__Bacteria                      p__Acidobacteria\nOTU_32    k__Archaea p__Miscellaneous Crenarchaeotic Group\n                         Class               Order               Family Genus\nOTU_4272            c__Bacilli       o__Bacillales                  f__   g__\nOTU_236                    c__                 o__                  f__   g__\nOTU_399  c__Betaproteobacteria o__Nitrosomonadales f__Nitrosomonadaceae   g__\nOTU_1556      c__Acidobacteria      o__Subgroup 17                  f__   g__\nOTU_32                     c__                 o__                  f__   g__\n         Species\nOTU_4272     s__\nOTU_236      s__\nOTU_399      s__\nOTU_1556     s__\nOTU_32       s__\n   Group Type          Saline\nS1    IW   NE Non-saline soil\nS2    IW   NE Non-saline soil\nS3    IW   NE Non-saline soil\nS4    IW   NE Non-saline soil\nS5    IW   NE Non-saline soil\nS6    IW   NE Non-saline soil\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/691722146e287afe063bd43e9ce4fa41977fe763/examples/22-ordination-unconstrained.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"vegan\", \"ggplot2\", \"scales\", \"digest\"))\n```\n:::\n\n\n</details>\n\n## 为什么先算距离，再做排序 {#sec-theory}\n\n先记住三条：\n\n1. **PCoA 的输入是样本间距离矩阵。** 选用 Bray–Curtis、Jaccard 还是 UniFrac，往往比最后选哪种二维排序更影响结论。\n2. **Bray–Curtis 关注丰度组成差异。** 对测序深度不同的计数表，先转换为样本内相对丰度，避免总 reads 数主导距离。\n3. **排序轴不是“菌群好坏轴”。** 它们只是尽量保存样本间距离的数学方向，不能按坐标正负赋予生物学价值。\n\n<details>\n<summary><strong>深入：PCoA、NMDS 与 CLR-PCA 怎么选</strong></summary>\n\n**PCoA（principal coordinates analysis，主坐标分析）**\n\nPCoA 可以接收任意距离矩阵。Bray–Curtis PCoA 是 16S 研究中最常见的整体群落结构展示。非欧氏距离有时会产生负特征值，可使用 Lingoes 或 Cailliez 校正；本例用 `cmdscale(add = TRUE)` 添加 Lingoes 常数。\n\n**NMDS（non-metric multidimensional scaling，非度量多维标度）**\n\nNMDS 优先保存距离的秩次，而非距离的绝对数值。它没有“轴解释方差”，必须报告 stress。经验上 stress < 0.1 通常很好，0.1–0.2 可用于谨慎解释，> 0.2 时二维表示可能失真。NMDS 依赖随机初值，因此必须固定随机种子。\n\n**CLR-PCA（centered log-ratio PCA，中心对数比 PCA）**\n\nCLR 将成分数据映射到欧氏空间，PCA 后的欧氏距离对应 Aitchison 距离。但零值不能直接取对数；简单伪计数会影响结果，尤其是稀疏表。本例把 CLR-PCA作为敏感性分析，并明确报告零替代值与 prevalence 筛选阈值。若它是主要结论，优先考虑 robust Aitchison / RPCA，并比较不同零处理方案。\n\n</details>\n\n::: {.callout-note title=\"本例为什么按盐碱状态画主图\"}\n按盐碱状态分组时，PERMANOVA 显著而组内离散度检验不显著，适合演示“位置差异 + 离散度核查”的完整证据链。若改按三类湿地地理组分析，本数据的组内离散度检验也会显著，此时不能把 PERMANOVA 结果简单解释为组中心差异。\n:::\n\n## 从距离矩阵得到PCoA、NMDS与CLR-PCA {#sec-code}\n\n### 低 prevalence 筛选与 Bray–Curtis 距离\n\n保留至少在 5% 样本中检出的特征。这个阈值用于降低极低频特征对计算和噪声的影响，正式研究应报告阈值并做敏感性分析。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin_prevalence <- 0.05\nmin_samples <- ceiling(min_prevalence * ncol(otutab))\nkeep_feature <- rowSums(otutab > 0) >= min_samples\n\ncomm <- t(otutab[keep_feature, , drop = FALSE])\ncomm_rel <- sweep(comm, 1, rowSums(comm), \"/\")\nmetadata <- metadata[rownames(comm_rel), , drop = FALSE]\n\nstopifnot(\n  all(abs(rowSums(comm_rel) - 1) < 1e-10),\n  identical(rownames(comm_rel), rownames(metadata))\n)\n\ndist_bray <- vegan::vegdist(comm_rel, method = \"bray\")\nc(\n  samples = nrow(comm_rel),\n  retained_features = ncol(comm_rel),\n  original_features = nrow(otutab)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          samples retained_features original_features \n               90             11113             13628 \n```\n\n\n:::\n:::\n\n\n### PCoA 坐标\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcoa_fit <- stats::cmdscale(\n  dist_bray,\n  k = 2,\n  eig = TRUE,\n  add = TRUE\n)\n\npositive_eigenvalues <- pcoa_fit$eig[pcoa_fit$eig > 0]\npcoa_variance <- 100 * pcoa_fit$eig[1:2] / sum(positive_eigenvalues)\n\npcoa_df <- as.data.frame(pcoa_fit$points)\ncolnames(pcoa_df) <- c(\"PCoA1\", \"PCoA2\")\npcoa_df$SampleID <- rownames(pcoa_df)\npcoa_df$Salinity <- factor(\n  metadata[pcoa_df$SampleID, \"Saline\"],\n  levels = c(\"Non-saline soil\", \"Saline soil\")\n)\n\nhead(pcoa_df)\nround(pcoa_variance, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        PCoA1      PCoA2 SampleID        Salinity\nS1 -0.2819267 0.07325613       S1 Non-saline soil\nS2 -0.3521144 0.17689159       S2 Non-saline soil\nS3 -0.3611914 0.21457312       S3 Non-saline soil\nS4 -0.3721882 0.25104083       S4 Non-saline soil\nS5 -0.3341215 0.22442004       S5 Non-saline soil\nS6 -0.3455585 0.24112151       S6 Non-saline soil\n[1] 14.25 11.66\n```\n\n\n:::\n:::\n\n\n### PERMANOVA 与组内离散度\n\n示例样本按独立样本进行 999 次自由置换。若研究包含配对、重复测量、区组或采样点层级，必须限制置换范围。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260718)\npermanova <- vegan::adonis2(\n  dist_bray ~ Salinity,\n  data = pcoa_df,\n  permutations = 999\n)\n\ndispersion_model <- vegan::betadisper(\n  dist_bray,\n  group = pcoa_df$Salinity,\n  type = \"median\",\n  bias.adjust = TRUE\n)\nset.seed(20260718)\ndispersion_test <- vegan::permutest(\n  dispersion_model,\n  permutations = 999\n)\n\npermanova\ndispersion_test\n\npermanova_r2 <- unname(permanova$R2[1])\npermanova_p <- unname(permanova$`Pr(>F)`[1])\ndispersion_p <- unname(dispersion_test$tab$`Pr(>F)`[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nvegan::adonis2(formula = dist_bray ~ Salinity, data = pcoa_df, permutations = 999)\n         Df SumOfSqs      R2      F Pr(>F)    \nSalinity  1   3.2599 0.11106 10.994  0.001 ***\nResidual 88  26.0925 0.88894                  \nTotal    89  29.3524 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n          Df  Sum Sq   Mean Sq      F N.Perm Pr(>F)\nGroups     1 0.00468 0.0046803 1.5095    999  0.216\nResiduals 88 0.27284 0.0031005                     \n```\n\n\n:::\n:::\n\n\n本例中，PERMANOVA 说明两类土壤的整体群落结构存在统计差异；离散度检验未发现显著差异，因此结果不太可能仅由某一组更分散造成。这里的 P 值仍需结合真实研究设计解释。\n\n### NMDS：用 stress 判断二维表示是否可靠\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260718)\nnmds_fit <- vegan::metaMDS(\n  dist_bray,\n  k = 2,\n  trymax = 200,\n  autotransform = FALSE,\n  trace = FALSE\n)\n\nnmds_df <- as.data.frame(\n  vegan::scores(nmds_fit, display = \"sites\")\n)\nnmds_df$SampleID <- rownames(nmds_df)\nnmds_df$Salinity <- pcoa_df[nmds_df$SampleID, \"Salinity\"]\n\np_nmds <- ggplot(nmds_df, aes(NMDS1, NMDS2, color = Salinity)) +\n  geom_point(size = 2.3, alpha = 0.85) +\n  stat_ellipse(type = \"t\", level = 0.95, linewidth = 0.7) +\n  scale_color_pub(name = \"Soil salinity\") +\n  labs(\n    title = sprintf(\"Bray-Curtis NMDS (stress = %.3f)\", nmds_fit$stress),\n    x = \"NMDS1\",\n    y = \"NMDS2\"\n  ) +\n  theme_pub()\n\np_nmds\n```\n\n::: {.cell-output-display}\n![](22-ordination-unconstrained_files/figure-html/reader-step-07-1.png)\n:::\n\n```{.r .cell-code}\nnmds_fit$stress\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1633241\n```\n\n\n:::\n:::\n\n\n### CLR-PCA：把零处理写进分析假设\n\n下面保留至少 20% 样本中出现的特征，并用 `0.5` read 作为零替代值。这是透明、易复现的敏感性分析，不应被描述为唯一正确的零处理方案。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclr_min_prevalence <- 0.20\nkeep_clr <- rowSums(otutab > 0) >=\n  ceiling(clr_min_prevalence * ncol(otutab))\nclr_counts <- t(otutab[keep_clr, , drop = FALSE])\n\nzero_replacement <- 0.5\nlog_replaced <- log(clr_counts + zero_replacement)\nclr_matrix <- log_replaced - rowMeans(log_replaced)\n\nclr_pca_fit <- stats::prcomp(\n  clr_matrix,\n  center = TRUE,\n  scale. = FALSE,\n  rank. = 2\n)\nclr_variance <- 100 * summary(clr_pca_fit)$importance[2, 1:2]\n\nclr_df <- as.data.frame(clr_pca_fit$x[, 1:2, drop = FALSE])\nclr_df$SampleID <- rownames(clr_df)\nclr_df$Salinity <- pcoa_df[clr_df$SampleID, \"Salinity\"]\n\np_clr <- ggplot(clr_df, aes(PC1, PC2, color = Salinity)) +\n  geom_point(size = 2.3, alpha = 0.85) +\n  stat_ellipse(type = \"t\", level = 0.95, linewidth = 0.7) +\n  scale_color_pub(name = \"Soil salinity\") +\n  labs(\n    title = \"CLR-PCA sensitivity analysis\",\n    x = sprintf(\"PC1 (%.1f%%)\", clr_variance[1]),\n    y = sprintf(\"PC2 (%.1f%%)\", clr_variance[2])\n  ) +\n  theme_pub()\n\np_clr\n```\n\n::: {.cell-output-display}\n![](22-ordination-unconstrained_files/figure-html/reader-step-08-1.png)\n:::\n:::\n\n\n如果 Bray–Curtis PCoA 与 CLR-PCA 给出不同故事，先检查稀疏度、零替代、prevalence 阈值和极高丰度特征，而不是选择“更好看”的一张。\n\n## 在排序图中保留距离、拟合与检验信息 {#sec-polish}\n\n主图把检验结果放在图内，避免图注与分析版本脱节。轴解释率来自当前 PCoA 模型，不能手工抄写。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_p <- function(p) {\n  if (is.na(p)) {\n    return(\"= NA\")\n  }\n  if (p < 0.001) {\n    return(\"< 0.001\")\n  }\n  sprintf(\"= %.3f\", p)\n}\n\nstat_label <- paste0(\n  \"PERMANOVA  R² = \", sprintf(\"%.3f\", permanova_r2),\n  \", P \", format_p(permanova_p),\n  \"\\nDispersion  P \", format_p(dispersion_p)\n)\n\np_pcoa <- ggplot(\n  pcoa_df,\n  aes(PCoA1, PCoA2, color = Salinity)\n) +\n  stat_ellipse(\n    type = \"t\",\n    level = 0.95,\n    linewidth = 0.75,\n    show.legend = FALSE\n  ) +\n  geom_point(size = 2.7, alpha = 0.88) +\n  scale_color_pub(name = \"Soil salinity\") +\n  labs(\n    subtitle = stat_label,\n    x = sprintf(\"PCoA 1 (%.1f%%)\", pcoa_variance[1]),\n    y = sprintf(\"PCoA 2 (%.1f%%)\", pcoa_variance[2])\n  ) +\n  coord_equal() +\n  theme_pub(base_size = 11) +\n  theme(\n    plot.subtitle = element_text(size = 9.5, lineheight = 1.05),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\", size = 9),\n    legend.text = element_text(size = 8.5)\n  ) +\n  guides(color = guide_legend(nrow = 1, byrow = TRUE))\n\np_pcoa\n```\n\n::: {.cell-output-display}\n![](22-ordination-unconstrained_files/figure-html/reader-step-09-1.png)\n:::\n\n```{.r .cell-code}\nsave_pub(\n  p_pcoa,\n  \"figures/22-pcoa-bray\",\n  width = 120,\n  height = 95\n)\n```\n:::\n\n\n导出后得到：\n\n- `figures/22-pcoa-bray.pdf`：矢量版，优先用于论文排版；\n- `figures/22-pcoa-bray.png`：300 dpi，适合网页与公众号；\n- `figures/22-pcoa-bray.tiff`：300 dpi、LZW 压缩，适合要求 TIFF 的期刊。\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最常追问的六件事\"}\n1. **只报告 PERMANOVA，不检查 dispersion。** 组内离散度显著时，PERMANOVA 可能同时反映位置与扩散范围的差异。\n2. **直接对原始 reads 算 Bray–Curtis。** 测序深度差异可能进入距离；本例先转换为相对丰度。\n3. **把椭圆当作显著性边界。** `stat_ellipse()` 是分布概括，不是组间检验，也不适合样本数过少的组。\n4. **忽略研究设计。** 配对、重复测量或同一采样点的样本不能自由置换；可在 `adonis2()` 中用 `strata = metadata$SubjectID` 限制置换。\n5. **把 NMDS 轴写成解释方差。** NMDS 没有轴解释率，只报告 stress；stress 过高时增加维数或重新审视距离。\n6. **伪计数不报告。** CLR 结果会随零替代方案变化；必须写明替代值、筛选阈值，并进行敏感性分析。\n:::\n\n::: {.callout-warning title=\"真实反例：换成地理分组会发生什么\"}\n将 `Salinity` 换为 `metadata$Group` 后，本示例数据的 PERMANOVA 与 dispersion test 都显著。此时可以说“组间群落分布存在差异”，但不能把差异全部归因于组中心移动。这个检查不应因主图看起来分得很开而省略。\n:::\n\n## 报告距离、排序和离散度检验的方法与限制 {#sec-methods}\n\n下面英文可直接替换分组名、筛选阈值和置换设计：\n\n> Community structure was evaluated using Bray–Curtis dissimilarities calculated from sample-wise relative-abundance profiles. Features detected in at least 5% of samples were retained, resulting in 11,113 features across 90 samples. Principal coordinates analysis (PCoA) was performed with a Lingoes additive correction. Differences between soil-salinity groups were tested by PERMANOVA with 999 permutations (\\(R^2\\) = 0.111, P = 0.001). Homogeneity of multivariate dispersion was assessed using distances to spatial medians with small-sample bias adjustment (P = 0.216). Permutations were unrestricted because the demonstration metadata contained no repeated-measures or blocking variable.\n\n若真实数据有 `SubjectID`、`SiteID` 或 `Batch`，最后一句必须改成实际的受限置换设计。\n\n## 将距离、排序和离散度检验用于自己的研究 {#sec-own-data}\n\n只需替换三个路径和分组列名：\n\n\n::: {.cell}\n\n```{.r .cell-code}\notutab <- read.delim(\n  \"your_project/otutab.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\ntaxonomy <- read.delim(\n  \"your_project/taxonomy.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\nmetadata <- read.delim(\n  \"your_project/metadata.tsv\",\n  row.names = 1,\n  check.names = FALSE\n)\n\ngroup_col <- \"Treatment\"\nmetadata$AnalysisGroup <- factor(metadata[[group_col]])\n\nstopifnot(\n  identical(rownames(otutab), rownames(taxonomy)),\n  identical(colnames(otutab), rownames(metadata))\n)\n```\n:::\n\n\n输入约定：\n\n- `otutab`：行是 ASV/OTU，列是样本，单元格是非负 reads 数；\n- `taxonomy`：行与 `otutab` 完全一致，列为 Kingdom 至 Species；\n- `metadata`：行是样本，至少包含分组列；\n- 若样本顺序不一致，先按样本 ID 显式重排，不能只取交集后假定顺序正确；\n- 若有配对或区组设计，保留对应列并在置换检验中使用；\n- 若使用 UniFrac，还需一棵 tip 名称与特征 ID 一致的系统发育树。\n\n## 参考 {#sec-references}\n\n- An J, Liu C, Wang Q, et al. Soil bacterial community structure in Chinese wetlands. *Geoderma*. 2019;337:290–299. [doi:10.1016/j.geoderma.2018.09.035](https://doi.org/10.1016/j.geoderma.2018.09.035)\n- Liu C, Cui Y, Li X, Yao M. microeco: an R package for data mining in microbial community ecology. *FEMS Microbiology Ecology*. 2021;97(2):fiaa255. [doi:10.1093/femsec/fiaa255](https://doi.org/10.1093/femsec/fiaa255)\n- Gower JC. Some distance properties of latent root and vector methods used in multivariate analysis. *Biometrika*. 1966;53:325–338.\n- Anderson MJ. A new method for non-parametric multivariate analysis of variance. *Austral Ecology*. 2001;26:32–46. [doi:10.1111/j.1442-9993.2001.01070.pp.x](https://doi.org/10.1111/j.1442-9993.2001.01070.pp.x)\n- Anderson MJ. Distance-based tests for homogeneity of multivariate dispersions. *Biometrics*. 2006;62:245–253. [doi:10.1111/j.1541-0420.2005.00440.x](https://doi.org/10.1111/j.1541-0420.2005.00440.x)\n- Oksanen J, Simpson GL, Blanchet FG, et al. `vegan`: Community Ecology Package. [CRAN package page](https://CRAN.R-project.org/package=vegan)\n",
    "supporting": [
      "22-ordination-unconstrained_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "ffe2de9c9c4ba2427d9dc1521b4968c7",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  }
}
