{
  "hash": "e2255f8800ca9398b89998c3d8104ce9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"第 29 篇 · 群落分型 DMM（肠型/CST）\"\nauthor: \"微生物组分析最佳实践 · 16S 系列\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: true\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\n---\n\n> **分析目标：**用 Dirichlet-multinomial mixture（DMM，Dirichlet–多项式混合模型）从原始属级计数估计概率性群落状态，同时审计成分数、初始化、标签交换、后验不确定性、特征过滤、测序深度与重复样本稳定性。  \n> **输入文件：**`otutab.tsv`、`taxonomy.tsv`、`metadata.tsv`。  \n> **预计资源：**示例含 278 个样本、130 个来源属级类别和 570,851 reads；42 个 fresh fits 各用一次性 R 进程、最多 8 个并发，通常需 3–6 分钟，峰值内存约 1–2 GB，四张图以 PDF/SVG/600 ppi PNG/LZW-TIFF 导出。\n\n## 这一步对应论文里的哪张图 {#sec-target}\n\n群落分型常见于论文中的三类图：模型证据随 component 数 `k` 的曲线、按“肠型”（enterotype）或阴道群落状态型（community state type, CST）着色的排序图，以及各状态优势类群的组成热图。Holmes 等人的原文可直接查看 [Figure 1：Laplace model evidence](https://doi.org/10.1371/journal.pone.0030126.g001)、[Figure 2：按四个 component 着色的 NMDS](https://doi.org/10.1371/journal.pone.0030126.g002) 和 [Table 4：BMI 与 component 的列联表](https://doi.org/10.1371/journal.pone.0030126.t004)。PLOS ONE 原文采用 CC BY 许可；这里不嵌入原图，而是沿用“模型选择—排序显示—component 解释”的信息结构，从公开计数重绘并增加不确定性与稳定性审计。真正需要回答的不是“软件能分成几类”，而是：**离散状态是否比连续梯度更有支持，样本属于某状态的把握有多大，换一种合理的数据处理后结论是否仍成立。**\n\n本页使用 `DirichletMultinomial` 1.46.0 随包分发的真实 Twins 属级 16S 计数。原队列来自 [Turnbaugh et al. (2009)](https://doi.org/10.1038/nature07540) 的双胞胎肠道微生物组研究；[Holmes et al. (2012)](https://doi.org/10.1371/journal.pone.0030126)用这组数据演示 DMM。包内表保留 278 个样本、570,851 reads、129 个命名 genus 加一个来源标签拼作 `Uknown` 的未分类项。这里保留原始标签和计数，只在图中把 `Uknown` 显示为 `Unclassified`。\n\n::: {.callout-important title=\"先给结论\"}\n主分析直接使用**未转相对丰度、未加伪计数、未抽平**的整数 counts，固定 seed `20260729`，比较 `k=1–7`。Laplace approximation 在 `k=4` 最小，得到 85、86、46、61 个样本的四个状态；但 AIC 在 `k=2` 最小，BIC 在 `k=1` 最小。四分型是一个需要继续审计的工作模型，不是三个准则共同确认的天然分类。\n\n四个 component 以 fitted Bacteroides 比例递减、再以 Prevotella 比例递减的确定性规则命名为 `DMM-A` 至 `DMM-D`，避免把原始 component number 当作固定身份。278 个样本中有 8 个最大后验概率低于 0.80，不能把它们画成毫无歧义的 hard class。\n\n八个一次性进程中的独立初始化都进入与主模型相同的 partition，profile-matched adjusted Rand index（ARI）均为 1；最低 Laplace 的 seed `20260735` 也得到同一 partition。初始化审计支持当前四分型的 optimizer stability，但不替代过滤、深度、抽平和实验单位敏感性。\n\n5% prevalence 过滤后，Laplace 仍选 `k=4`；只保留深度至少 1,000 reads、把这些样本稀释到 1,000 reads、或每位参与者只留一个样本时，Laplace 都改选 `k=2`。固定比较 `k=4` 时，这四条分支与主分类的 matched ARI 分别约为 0.904、0.928、0.906、0.680。\n\n字符串后缀可构造 154 个 `ParticipantKey`，其中 124 个有两份来源样本；85/124 对状态相同，agreement 为 68.5%，ARI 为 0.377。包内没有独立临床访视表，因此后缀只用于重复样本审计，不能解释成已经验证的时间顺序。BMI 只做描述性交叉表，不做疾病关联检验。\n:::\n\n这里不复制论文原图，而是从公开计数重新绘制四张原创图：模型选择、后验着色 PCoA、component profile 热图和稳定性账本。\n\n## 理论：DMM 给的是概率状态，不是血型式类别 {#sec-theory}\n\n### 1. 单个 Dirichlet–多项式同时描述组成和过度离散\n\n设样本 `j` 的属级计数向量为 `x[j]`，总 reads 为 `N[j]`。普通 multinomial 假定每个样本共享固定组成 `p`；Dirichlet–multinomial 先让样本组成从 Dirichlet distribution 波动，再生成计数：\n\n$$\np_j \\sim \\mathrm{Dirichlet}(\\alpha), \\qquad\nx_j \\mid p_j \\sim \\mathrm{Multinomial}(N_j,p_j).\n$$\n\n`alpha` 的相对大小描述 component 的期望组成，总浓度与样本间离散程度相关。DMM 再混合 `k` 个这样的分布：\n\n$$\nP(x_j)=\\sum_{c=1}^{k}\\pi_c\\,\nP_{\\mathrm{DM}}(x_j\\mid\\alpha_c).\n$$\n\n模型把每个样本的总 reads `N[j]` 纳入 likelihood，所以主输入应是非负整数 counts。相对丰度、CLR 或人为伪计数属于不同测量对象，不能悄悄传给这条 DMM 主分支。\n\n### 2. `k` 是模型选择问题，不是看图数云团\n\n`DirichletMultinomial::dmn()`给出 negative log evidence 的 Laplace approximation，以及 AIC 和 BIC。三者都以较小为优，但复杂度惩罚与近似方式不同。只展示支持目标 `k` 的一个准则，会隐藏模型选择不确定性。\n\n本例的 fresh fit 中，Laplace、AIC、BIC 分别偏向 4、2、1。二维 PCoA 只是高维距离的投影；即使颜色看似分开，也不能反过来决定 DMM component 数。\n\n### 3. Hard assignment 会丢掉边界信息\n\n对样本 `j`，模型返回每个 component 的 posterior probability：\n\n$$\nr_{jc}=P(z_j=c\\mid x_j).\n$$\n\n`which.max(r[j, ])` 只保留最高者。最大 posterior 接近 0.5 和接近 1 的样本被同样画成一个实心颜色，会制造虚假确定性。因此至少保留：所有 component posterior、最大 posterior、normalized entropy，以及预声明的低置信度标记。\n\n### 4. Mixture label 会交换\n\n同一个 partition 可以在一次拟合中叫 component 1，在另一次拟合中叫 component 3；这叫 label switching。直接比较数字标签会把等价解误判为不稳定。本页先按 component expected profile 做 Jensen–Shannon divergence matching，再计算 ARI。主模型内部则按 Bacteroides、Prevotella 和原始 component index 的固定顺序赋 `DMM-A`–`DMM-D`。\n\n这个规则只负责**稳定命名**。`DMM-A` 不等于“Bacteroides enterotype”，`DMM-D` 也不等于疾病亚型；component profile 是完整分布，不是由一个优势菌定义的诊断。\n\n### 5. Enterotype 与 CST 需要不同语境的外部证据\n\n[Arumugam et al. (2011)](https://doi.org/10.1038/nature09944)提出肠道 enterotype；[Ravel et al. (2011)](https://doi.org/10.1073/pnas.1002611107)描述阴道 CST。[Koren et al. (2013)](https://doi.org/10.1371/journal.pcbi.1002863)和 [Costea et al. (2018)](https://doi.org/10.1038/s41564-017-0072-8)都提醒：不同身体部位和队列可能呈离散模式，也可能是连续梯度；cluster 支持、稳定性、可迁移性和临床含义必须分别验证。\n\n因此“发现四个 state”最多说明当前数据与合同下的概率模型支持一个四 component 描述。要升级为可复用的 enterotype/CST，还需要外部队列、批次与测序区域敏感性、纵向转移、协变量调整和生物学验证。\n\n<details>\n<summary><strong>深入：为什么模型已经考虑 read depth，仍要做 depth sensitivity</strong></summary>\n\nDMM 条件在每个样本的总 reads 上建模，因此不需要为了主拟合先把所有样本抽到同一深度。但极浅文库仍提供更宽的抽样不确定性，稀有 feature 的可见性也随深度变化；feature filter 与 sample inclusion 还能改变 likelihood 的维度和样本集合。Depth sensitivity 检查的是结论对观测设计和信息量的依赖，不是宣称 rarefaction 比原始 count likelihood 更正确。\n\n</details>\n\n## 准备工作 {#sec-setup}\n\n<details>\n<summary><strong>展开：安装依赖、导出真实三件套和定义作图函数</strong></summary>\n\nR 4.4 与 Bioconductor 3.19 的锁定安装：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"BiocManager\", \"digest\", \"ggplot2\", \"jsonlite\", \"ragg\", \"readr\",\n  \"scales\", \"svglite\", \"systemfonts\", \"vegan\"\n))\nBiocManager::install(version = \"3.19\", ask = FALSE)\nBiocManager::install(\"DirichletMultinomial\", ask = FALSE)\n```\n:::\n\n\n从 `DirichletMultinomial` 1.46.0 的 `extdata` 导出标准三件套。`otutab` 保持 feature × sample；taxonomy 只在 `Genus` 填入来源标签，因为包内没有分发其余 rank：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(\n  identical(\n    as.character(packageVersion(\"DirichletMultinomial\")),\n    \"1.46.0\"\n  )\n)\n\ntwins_path <- system.file(\n  \"extdata\", \"Twins.csv\", package = \"DirichletMultinomial\"\n)\nphenotype_path <- system.file(\n  \"extdata\", \"TwinStudy.t\", package = \"DirichletMultinomial\"\n)\nstopifnot(\n  digest::digest(twins_path, algo = \"sha256\", file = TRUE) ==\n    \"b6a231acded317b49b7fd800bf8b4ce12a75340c5b88499b51e92d72528f93ba\",\n  digest::digest(phenotype_path, algo = \"sha256\", file = TRUE) ==\n    \"4286c3f9255f7f1ce7f5c5ac5e60d4e27284fe358ceb553108748c67ab4d8b05\"\n)\n\notutab <- as.matrix(read.csv(\n  twins_path, row.names = 1, check.names = FALSE\n))\nstorage.mode(otutab) <- \"integer\"\nbmi_code <- scan(phenotype_path, what = integer(), quiet = TRUE)\n\ntaxonomy <- data.frame(\n  Kingdom = NA_character_, Phylum = NA_character_,\n  Class = NA_character_, Order = NA_character_,\n  Family = NA_character_, Genus = rownames(otutab),\n  Species = NA_character_,\n  row.names = rownames(otutab),\n  check.names = FALSE\n)\n\nsample_ids <- colnames(otutab)\nparticipant_key <- sub(\"\\\\.2$\", \"\", sample_ids)\nmetadata <- data.frame(\n  BMIClass = c(\"Lean\", \"Obese\", \"Overweight\")[bmi_code + 1L],\n  BMIClassCode = bmi_code,\n  ParticipantKey = participant_key,\n  SourceSuffix = ifelse(\n    grepl(\"\\\\.2$\", sample_ids), \"Dot2 suffix\", \"No suffix\"\n  ),\n  SamplesPerParticipantKey = as.integer(\n    table(participant_key)[participant_key]\n  ),\n  row.names = sample_ids,\n  check.names = FALSE\n)\n\nwrite_keyed_tsv <- function(x, id_name, path) {\n  out <- data.frame(\n    setNames(list(rownames(x)), id_name), x,\n    check.names = FALSE\n  )\n  write.table(\n    out, path, sep = \"\\t\", quote = FALSE,\n    row.names = FALSE, na = \"\"\n  )\n}\n\ndir.create(\n  \"data/small/community-typing-dmm\",\n  recursive = TRUE,\n  showWarnings = FALSE\n)\nwrite_keyed_tsv(\n  otutab, \"FeatureID\",\n  \"data/small/community-typing-dmm/otutab.tsv\"\n)\nwrite_keyed_tsv(\n  taxonomy, \"FeatureID\",\n  \"data/small/community-typing-dmm/taxonomy.tsv\"\n)\nwrite_keyed_tsv(\n  metadata, \"SampleID\",\n  \"data/small/community-typing-dmm/metadata.tsv\"\n)\n```\n:::\n\n\n出版级函数直接内联。图内统一使用英文、DejaVu Sans 和色觉友好配色：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nset.seed(20260729)\nfont_pub <- \"DejaVu Sans\"\n\npal_pub <- c(\n  blue = \"#0072B2\",\n  orange = \"#E69F00\",\n  green = \"#009E73\",\n  vermillion = \"#D55E00\",\n  purple = \"#CC79A7\",\n  sky = \"#56B4E9\",\n  yellow = \"#F0E442\",\n  grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\", linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\", size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(\n        colour = \"#666666\", hjust = 0\n      ),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot,\n    width = width, height = height, units = units,\n    device = grDevices::cairo_pdf,\n    family = base_family, bg = \"white\"\n  )\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"), plot,\n      width = width, height = height, units = units,\n      device = svglite::svglite, bg = \"white\"\n    )\n  }\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot,\n    width = width, height = height, units = units, dpi = dpi,\n    device = ragg::agg_png, bg = \"white\"\n  )\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"), plot,\n      width = width, height = height, units = units, dpi = dpi,\n      device = ragg::agg_tiff,\n      compression = \"lzw\", bg = \"white\"\n    )\n  }\n  invisible(plot)\n}\n```\n:::\n\n\n</details>\n\n## 可复制代码 {#sec-code}\n\n### 1. 读取三件套并锁定 count contract\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character(),\n    col_types = readr::cols(.default = readr::col_character())\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\ninput_paths <- c(\n  otutab = \"data/small/community-typing-dmm/otutab.tsv\",\n  taxonomy = \"data/small/community-typing-dmm/taxonomy.tsv\",\n  metadata = \"data/small/community-typing-dmm/metadata.tsv\"\n)\nexpected_sha256 <- c(\n  otutab = \"28de822c434aedade101e66ac60a61df38124c9b59357095599fbd278f2ecb41\",\n  taxonomy = \"9eaa0bf788ad1db8c314a59e774c8935bdaa33a51135eaf606c11d5a497dff08\",\n  metadata = \"0368c9129c7d77f381688465141593a2c61a229368d2fc411c9017e1abe04409\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  function(path) digest::digest(\n    file = path, algo = \"sha256\", serialize = FALSE\n  ),\n  character(1)\n)\nstopifnot(identical(observed_sha256, expected_sha256))\nstopifnot(\n  identical(\n    as.character(packageVersion(\"DirichletMultinomial\")),\n    \"1.46.0\"\n  )\n)\n\notu_frame <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\n\ncounts <- as.matrix(otu_frame)\nstorage.mode(counts) <- \"integer\"\ntaxonomy <- taxonomy[rownames(counts), , drop = FALSE]\nmetadata <- metadata[colnames(counts), , drop = FALSE]\nmetadata$SampleID <- rownames(metadata)\nmetadata$BMIClassCode <- as.integer(metadata$BMIClassCode)\nmetadata$SamplesPerParticipantKey <- as.integer(\n  metadata$SamplesPerParticipantKey\n)\nsample_depths <- colSums(counts)\nsample_counts <- t(counts)\n\nstopifnot(\n  identical(rownames(counts), rownames(taxonomy)),\n  identical(colnames(counts), rownames(metadata)),\n  nrow(counts) == 130L,\n  ncol(counts) == 278L,\n  sum(counts) == 570851L,\n  all(is.finite(counts)),\n  all(counts >= 0L),\n  all(counts == round(counts)),\n  all(rowSums(counts) > 0L),\n  all(colSums(counts) > 0L),\n  identical(range(sample_depths), c(53, 10585)),\n  median(sample_depths) == 1597.5\n)\n\nlist(\n  otutab = data.frame(\n    FeatureID = rownames(counts)[1:5],\n    counts[1:5, 1:5, drop = FALSE],\n    check.names = FALSE\n  ),\n  taxonomy = data.frame(\n    FeatureID = rownames(taxonomy)[1:5],\n    taxonomy[1:5, c(\"Genus\", \"TaxonomyStatus\"), drop = FALSE],\n    check.names = FALSE\n  ),\n  metadata = data.frame(\n    SampleID = metadata$SampleID[1:5],\n    metadata[1:5, c(\n      \"BMIClass\", \"ParticipantKey\", \"SourceSuffix\",\n      \"SamplesPerParticipantKey\"\n    )],\n    check.names = FALSE\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$otutab\n                              FeatureID TS1.2 TS10.2 TS100.2 TS100 TS101.2\nAcetanaerobacterium Acetanaerobacterium     0      0       0     1       0\nAcetivibrio                 Acetivibrio     0      0       0     0       0\nAcetobacterium           Acetobacterium     0      0       0     0       0\nAcidaminococcus         Acidaminococcus     0      0       1     0       0\nActinobaculum             Actinobaculum     0      0       0     0       0\n\n$taxonomy\n                              FeatureID               Genus\nAcetanaerobacterium Acetanaerobacterium Acetanaerobacterium\nAcetivibrio                 Acetivibrio         Acetivibrio\nAcetobacterium           Acetobacterium      Acetobacterium\nAcidaminococcus         Acidaminococcus     Acidaminococcus\nActinobaculum             Actinobaculum       Actinobaculum\n                                                                                               TaxonomyStatus\nAcetanaerobacterium Source genus category; higher and lower ranks are not distributed with the packaged table\nAcetivibrio         Source genus category; higher and lower ranks are not distributed with the packaged table\nAcetobacterium      Source genus category; higher and lower ranks are not distributed with the packaged table\nAcidaminococcus     Source genus category; higher and lower ranks are not distributed with the packaged table\nActinobaculum       Source genus category; higher and lower ranks are not distributed with the packaged table\n\n$metadata\n        SampleID BMIClass ParticipantKey SourceSuffix SamplesPerParticipantKey\nTS1.2      TS1.2     Lean            TS1  Dot2 suffix                        2\nTS10.2    TS10.2    Obese           TS10  Dot2 suffix                        2\nTS100.2  TS100.2    Obese          TS100  Dot2 suffix                        2\nTS100      TS100    Obese          TS100    No suffix                        2\nTS101.2  TS101.2    Obese          TS101  Dot2 suffix                        1\n```\n\n\n:::\n:::\n\n\n`otutab` 的列总和是 library size；DMM 需要转置成 sample × feature 后拟合。taxonomy 的空 rank 是公开数据边界，不应补造。`ParticipantKey` 与 `SourceSuffix` 是从字符串确定性派生的审计字段，不替代临床访视记录。\n\n### 2. 预声明主模型和稳定命名规则\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_seed <- 20260729L\ncandidate_k <- 1:7\nminimum_state_size <- max(10L, ceiling(0.05 * nrow(sample_counts)))\nstopifnot(minimum_state_size == 14L)\nstate_labels <- paste0(\"DMM-\", LETTERS[1:4])\n\nfit_scores <- function(fit_object) {\n  values <- DirichletMultinomial::goodnessOfFit(fit_object)\n  c(\n    NLE = unname(values[[\"NLE\"]]),\n    LogDet = unname(values[[\"LogDet\"]]),\n    Laplace = unname(values[[\"Laplace\"]]),\n    BIC = unname(values[[\"BIC\"]]),\n    AIC = unname(values[[\"AIC\"]])\n  )\n}\n\nfit_profiles <- function(fit_object) {\n  x <- DirichletMultinomial::fitted(fit_object, scale = TRUE)\n  sweep(x, 2L, colSums(x), \"/\")\n}\n\nfit_posteriors <- function(fit_object, sample_ids) {\n  x <- DirichletMultinomial::mixture(fit_object)\n  x <- sweep(x, 1L, rowSums(x), \"/\")\n  rownames(x) <- sample_ids\n  x\n}\n\nchoose2 <- function(x) x * (x - 1) / 2\n\nadjusted_rand_index <- function(x, y) {\n  tab <- table(x, y)\n  n <- sum(tab)\n  sum_cells <- sum(choose2(tab))\n  sum_rows <- sum(choose2(rowSums(tab)))\n  sum_cols <- sum(choose2(colSums(tab)))\n  expected <- sum_rows * sum_cols / choose2(n)\n  maximum <- (sum_rows + sum_cols) / 2\n  (sum_cells - expected) / (maximum - expected)\n}\n\nall_permutations <- function(x) {\n  if (length(x) == 1L) return(matrix(x, nrow = 1L))\n  do.call(rbind, lapply(seq_along(x), function(i) {\n    cbind(x[[i]], all_permutations(x[-i]))\n  }))\n}\n\njs_divergence <- function(p, q) {\n  p <- p / sum(p)\n  q <- q / sum(q)\n  m <- (p + q) / 2\n  sum(ifelse(p > 0, p * log(p / m), 0)) / 2 +\n    sum(ifelse(q > 0, q * log(q / m), 0)) / 2\n}\n\nmatch_profiles <- function(primary_profiles, candidate_profiles) {\n  common <- intersect(\n    rownames(primary_profiles),\n    rownames(candidate_profiles)\n  )\n  primary <- primary_profiles[common, , drop = FALSE]\n  candidate <- candidate_profiles[common, , drop = FALSE]\n  primary <- sweep(primary, 2L, colSums(primary), \"/\")\n  candidate <- sweep(candidate, 2L, colSums(candidate), \"/\")\n  k <- ncol(primary)\n  cost <- outer(seq_len(k), seq_len(k), Vectorize(function(i, j) {\n    js_divergence(primary[, i], candidate[, j])\n  }))\n  permutations <- all_permutations(seq_len(k))\n  total <- apply(permutations, 1L, function(p) {\n    sum(cost[cbind(seq_len(k), p)])\n  })\n  best <- permutations[which.min(total), ]\n  list(\n    candidate_for_primary = as.integer(best),\n    divergence = cost[cbind(seq_len(k), best)],\n    common_features = length(common)\n  )\n}\n```\n:::\n\n\n标签规则预先固定为：Bacteroides fitted proportion 从高到低；若相同，再按 Prevotella 从高到低；仍相同则按原始 component index。不同 sensitivity fit 则用完整 profile 的最小 Jensen–Shannon divergence 一一匹配。\n\n### 3. 构造四条 sensitivity branch\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_prevalence <- rowMeans(counts > 0L)\nprevalence_features <- rownames(counts)[feature_prevalence >= 0.05]\ndepth_samples <- names(sample_depths)[sample_depths >= 1000L]\n\nset.seed(primary_seed)\nrarefied_counts <- vegan::rrarefy(\n  sample_counts[depth_samples, , drop = FALSE],\n  sample = 1000L\n)\nset.seed(primary_seed)\nstopifnot(identical(\n  rarefied_counts,\n  vegan::rrarefy(\n    sample_counts[depth_samples, , drop = FALSE],\n    sample = 1000L\n  )\n))\n\nparticipant_indices <- split(\n  seq_len(nrow(metadata)),\n  metadata$ParticipantKey\n)\none_per_participant <- vapply(participant_indices, function(idx) {\n  no_suffix <- idx[metadata$SourceSuffix[idx] == \"No suffix\"]\n  if (length(no_suffix) > 0L) no_suffix[[1L]] else idx[[1L]]\n}, integer(1))\none_per_samples <- metadata$SampleID[one_per_participant]\n\nbranch_counts <- list(\n  Primary = sample_counts,\n  `Prevalence >= 5%` = sample_counts[\n    , prevalence_features, drop = FALSE\n  ],\n  `Depth >= 1,000` = sample_counts[\n    depth_samples, , drop = FALSE\n  ],\n  `Rarefied to 1,000` = rarefied_counts,\n  `One per participant` = sample_counts[\n    one_per_samples, , drop = FALSE\n  ]\n)\nbranch_seeds <- c(\n  Primary = primary_seed,\n  `Prevalence >= 5%` = primary_seed + 100L,\n  `Depth >= 1,000` = primary_seed + 200L,\n  `Rarefied to 1,000` = primary_seed + 300L,\n  `One per participant` = primary_seed + 400L\n)\n\ndata.frame(\n  Branch = names(branch_counts),\n  Samples = vapply(branch_counts, nrow, integer(1)),\n  Features = vapply(branch_counts, ncol, integer(1)),\n  Seed = unname(branch_seeds[names(branch_counts)]),\n  check.names = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                 Branch Samples Features     Seed\nPrimary                         Primary     278      130 20260729\nPrevalence >= 5%       Prevalence >= 5%     278       67 20260829\nDepth >= 1,000           Depth >= 1,000     247      130 20260929\nRarefied to 1,000     Rarefied to 1,000     247      130 20261029\nOne per participant One per participant     154      130 20261129\n```\n\n\n:::\n:::\n\n\n`Rarefied to 1,000` 只包含原深度至少 1,000 的 247 个样本；它是 sensitivity branch，不替代主 count model。`One per participant` 优先保留无 `.2` 后缀的样本，若某 key 只有 `.2`，则保留该样本，共 154 个。\n\n### 4. 每个模型都用一次性 R 进程拟合\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncandidate_jobs <- expand.grid(\n  Branch = names(branch_counts),\n  K = candidate_k,\n  stringsAsFactors = FALSE\n)\ncandidate_jobs$Seed <- unname(branch_seeds[candidate_jobs$Branch])\n\ninitialization_jobs <- data.frame(\n  Branch = \"Initialization\",\n  K = 4L,\n  Seed = primary_seed + 1:7,\n  stringsAsFactors = FALSE\n)\nall_jobs <- rbind(candidate_jobs, initialization_jobs)\n\njob_payload <- lapply(seq_len(nrow(all_jobs)), function(i) {\n  job <- all_jobs[i, , drop = FALSE]\n  list(\n    counts = if (job$Branch == \"Initialization\") {\n      branch_counts[[\"Primary\"]]\n    } else {\n      branch_counts[[job$Branch]]\n    },\n    k = job$K,\n    seed = job$Seed\n  )\n})\n\nfit_one <- function(job) {\n  Sys.setenv(\n    OMP_NUM_THREADS = \"1\",\n    OPENBLAS_NUM_THREADS = \"1\",\n    MKL_NUM_THREADS = \"1\"\n  )\n  requireNamespace(\"DirichletMultinomial\", quietly = TRUE)\n  DirichletMultinomial::dmn(\n    job$counts,\n    k = job$k,\n    verbose = FALSE,\n    seed = job$seed\n  )\n}\n\navailable_cores <- parallel::detectCores(logical = FALSE)\nif (is.na(available_cores)) available_cores <- 1L\nworkers <- min(8L, max(1L, available_cores), length(job_payload))\n\njob_indices <- seq_along(job_payload)\njob_batches <- split(\n  job_indices,\n  ceiling(job_indices / workers)\n)\nall_fits <- vector(\"list\", length(job_payload))\n\nfor (batch_indices in job_batches) {\n  cl <- parallel::makePSOCKcluster(length(batch_indices))\n  invisible(parallel::clusterEvalQ(cl, {\n    Sys.setenv(\n      OMP_NUM_THREADS = \"1\",\n      OPENBLAS_NUM_THREADS = \"1\",\n      MKL_NUM_THREADS = \"1\"\n    )\n    requireNamespace(\"DirichletMultinomial\", quietly = TRUE)\n    NULL\n  }))\n  batch_fits <- tryCatch(\n    parallel::parLapply(\n      cl,\n      job_payload[batch_indices],\n      fit_one\n    ),\n    finally = parallel::stopCluster(cl)\n  )\n  all_fits[batch_indices] <- batch_fits\n}\n\ncandidate_fits <- all_fits[seq_len(nrow(candidate_jobs))]\ninitialization_extra_fits <- all_fits[\n  nrow(candidate_jobs) + seq_len(nrow(initialization_jobs))\n]\n\nget_candidate_fit <- function(branch, k) {\n  index <- which(\n    candidate_jobs$Branch == branch & candidate_jobs$K == k\n  )\n  stopifnot(length(index) == 1L)\n  candidate_fits[[index]]\n}\n```\n:::\n\n\n这里不复用 worker：每批最多并发 8 个 PSOCK worker，而每个 worker 只完成一个 fit 就退出。每个进程都显式限制为单线程并接收独立 seed。在本次环境中，复用 worker 时，同一个 `dmn(seed=...)` 曾因前序 fit 历史而进入不同解；一次性进程把进程状态也纳入确定性合同。并行只缩短墙钟时间，不改变每个 fit 的输入、seed 或选择规则。\n\n### 5. 同时查看 Laplace、AIC 和 BIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_selection <- do.call(rbind, lapply(\n  seq_len(nrow(candidate_jobs)),\n  function(i) {\n    score <- fit_scores(candidate_fits[[i]])\n    data.frame(\n      Branch = candidate_jobs$Branch[[i]],\n      K = candidate_jobs$K[[i]],\n      Seed = candidate_jobs$Seed[[i]],\n      NLE = score[[\"NLE\"]],\n      LogDet = score[[\"LogDet\"]],\n      Laplace = score[[\"Laplace\"]],\n      AIC = score[[\"AIC\"]],\n      BIC = score[[\"BIC\"]],\n      stringsAsFactors = FALSE\n    )\n  }\n))\n\nselected_for <- function(branch, criterion) {\n  x <- model_selection[model_selection$Branch == branch, , drop = FALSE]\n  x$K[[which.min(x[[criterion]])]]\n}\n\nprimary_selection <- model_selection[\n  model_selection$Branch == \"Primary\",\n  c(\"K\", \"Laplace\", \"AIC\", \"BIC\")\n]\nprimary_selection$LaplaceMinimum <-\n  primary_selection$Laplace == min(primary_selection$Laplace)\nprimary_selection$AICMinimum <-\n  primary_selection$AIC == min(primary_selection$AIC)\nprimary_selection$BICMinimum <-\n  primary_selection$BIC == min(primary_selection$BIC)\n\nknitr::kable(\n  primary_selection,\n  digits = 2,\n  caption = \"Fresh fixed-seed model-selection ledger\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Fresh fixed-seed model-selection ledger\n\n|   |  K|  Laplace|      AIC|      BIC|LaplaceMinimum |AICMinimum |BICMinimum |\n|:--|--:|--------:|--------:|--------:|:--------------|:----------|:----------|\n|1  |  1| 39227.38| 39292.11| 39527.91|FALSE          |FALSE      |TRUE       |\n|6  |  2| 38872.47| 39115.53| 39588.93|FALSE          |TRUE       |FALSE      |\n|11 |  3| 38854.27| 39290.14| 40001.15|FALSE          |FALSE      |FALSE      |\n|16 |  4| 38838.42| 39476.69| 40425.31|TRUE           |FALSE      |FALSE      |\n|21 |  5| 38989.30| 39808.21| 40994.44|FALSE          |FALSE      |FALSE      |\n|26 |  6| 39135.50| 40154.37| 41578.21|FALSE          |FALSE      |FALSE      |\n|31 |  7| 39336.16| 40549.51| 42210.96|FALSE          |FALSE      |FALSE      |\n\n\n:::\n:::\n\n\n最低值分别是 Laplace `k=4`、AIC `k=2`、BIC `k=1`。后续用 `k=4` 是执行预声明的 Laplace 规则，不是宣称 AIC/BIC 错误。\n\n### 6. Canonicalize component，并保留全部 posterior\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_fit <- get_candidate_fit(\"Primary\", 4L)\nprofiles_raw <- fit_profiles(primary_fit)\nposteriors_raw <- fit_posteriors(primary_fit, rownames(sample_counts))\n\ncanonical_order <- order(\n  -profiles_raw[\"Bacteroides\", ],\n  -profiles_raw[\"Prevotella\", ],\n  seq_len(ncol(profiles_raw))\n)\nprofiles <- profiles_raw[, canonical_order, drop = FALSE]\nposteriors <- posteriors_raw[, canonical_order, drop = FALSE]\ncolnames(profiles) <- state_labels\ncolnames(posteriors) <- state_labels\n\nhard_index <- max.col(posteriors, ties.method = \"first\")\nprimary_state <- factor(state_labels[hard_index], levels = state_labels)\nnames(primary_state) <- rownames(posteriors)\nmaximum_posterior <- apply(posteriors, 1L, max)\nnormalized_entropy <- -rowSums(\n  posteriors * log(pmax(posteriors, 1e-15))\n) / log(ncol(posteriors))\n\nmixture_weights <- DirichletMultinomial::mixturewt(primary_fit)[\n  canonical_order, , drop = FALSE\n]\ncomponent_sizes <- as.integer(table(primary_state))\ncomponent_summary <- data.frame(\n  State = state_labels,\n  Samples = component_sizes,\n  MixtureWeight = mixture_weights$pi,\n  Theta = mixture_weights$theta,\n  ExpectedBacteroides = profiles[\"Bacteroides\", ],\n  ExpectedPrevotella = profiles[\"Prevotella\", ],\n  SamplesBelowPointEight = vapply(state_labels, function(state) {\n    sum(primary_state == state & maximum_posterior < 0.8)\n  }, integer(1)),\n  stringsAsFactors = FALSE\n)\n\nstopifnot(\n  identical(component_sizes, c(85L, 86L, 46L, 61L)),\n  min(component_sizes) >= minimum_state_size,\n  max(abs(colSums(profiles) - 1)) <= 1e-12,\n  max(abs(rowSums(posteriors) - 1)) <= 1e-12,\n  sum(maximum_posterior < 0.8) == 8L,\n  sum(maximum_posterior < 0.9) == 17L\n)\n\nknitr::kable(\n  component_summary,\n  digits = 4,\n  caption = \"Canonical component summary\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Canonical component summary\n\n|      |State | Samples| MixtureWeight|   Theta| ExpectedBacteroides| ExpectedPrevotella| SamplesBelowPointEight|\n|:-----|:-----|-------:|-------------:|-------:|-------------------:|------------------:|----------------------:|\n|DMM-A |DMM-A |      85|        0.3028| 53.2956|              0.3881|             0.0014|                      4|\n|DMM-B |DMM-B |      86|        0.3108| 52.0369|              0.2262|             0.0022|                      3|\n|DMM-C |DMM-C |      46|        0.1666| 18.7260|              0.0834|             0.0040|                      1|\n|DMM-D |DMM-D |      61|        0.2198| 30.1958|              0.0679|             0.0518|                      0|\n\n\n:::\n:::\n\n\n所有 posterior 都应写出，而不是只保存 `State`：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_posteriors <- data.frame(\n  SampleID = rownames(posteriors),\n  DMM_A = posteriors[, \"DMM-A\"],\n  DMM_B = posteriors[, \"DMM-B\"],\n  DMM_C = posteriors[, \"DMM-C\"],\n  DMM_D = posteriors[, \"DMM-D\"],\n  State = as.character(primary_state),\n  MaximumPosterior = maximum_posterior,\n  NormalizedEntropy = normalized_entropy,\n  LowConfidencePointEight = maximum_posterior < 0.8,\n  ParticipantKey = metadata[rownames(posteriors), \"ParticipantKey\"],\n  SourceSuffix = metadata[rownames(posteriors), \"SourceSuffix\"],\n  BMIClass = metadata[rownames(posteriors), \"BMIClass\"],\n  LibrarySize = sample_depths[rownames(posteriors)],\n  stringsAsFactors = FALSE\n)\nhead(sample_posteriors, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        SampleID        DMM_A        DMM_B        DMM_C        DMM_D State\nTS1.2      TS1.2 8.550839e-06 9.999914e-01 2.116637e-11 3.306405e-08 DMM-B\nTS10.2    TS10.2 9.996732e-01 3.776581e-08 3.267914e-04 2.847178e-10 DMM-A\nTS100.2  TS100.2 7.953050e-13 7.215446e-09 8.825577e-01 1.174423e-01 DMM-C\nTS100      TS100 7.861430e-02 5.974167e-01 1.414069e-06 3.239675e-01 DMM-B\nTS101.2  TS101.2 2.605763e-19 1.111438e-13 9.999985e-01 1.472108e-06 DMM-C\nTS103.2  TS103.2 9.996260e-01 3.737075e-04 3.245000e-07 4.361750e-10 DMM-A\nTS103      TS103 5.178859e-02 2.477008e-04 9.479636e-01 7.190560e-08 DMM-C\nTS104      TS104 9.725888e-01 2.741105e-02 1.126729e-07 7.048000e-12 DMM-A\n        MaximumPosterior NormalizedEntropy LowConfidencePointEight\nTS1.2          0.9999914      7.858200e-05                   FALSE\nTS10.2         0.9996732      2.128204e-03                   FALSE\nTS100.2        0.8825577      2.609820e-01                   FALSE\nTS100          0.5974167      6.296298e-01                    TRUE\nTS101.2        0.9999985      1.532199e-05                   FALSE\nTS103.2        0.9996260      2.400741e-03                   FALSE\nTS103          0.9479636      1.486270e-01                   FALSE\nTS104          0.9725888      9.062008e-02                   FALSE\n        ParticipantKey SourceSuffix BMIClass LibrarySize\nTS1.2              TS1  Dot2 suffix     Lean         813\nTS10.2            TS10  Dot2 suffix    Obese         660\nTS100.2          TS100  Dot2 suffix    Obese        1117\nTS100            TS100    No suffix    Obese        1655\nTS101.2          TS101  Dot2 suffix    Obese         957\nTS103.2          TS103  Dot2 suffix    Obese        1493\nTS103            TS103    No suffix    Obese         625\nTS104            TS104    No suffix    Obese        1023\n```\n\n\n:::\n:::\n\n\n### 7. 区分 fresh fit 与包内 reference fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreference_environment <- new.env(parent = emptyenv())\ndata(\n  \"fit\",\n  package = \"DirichletMultinomial\",\n  envir = reference_environment\n)\nreference_fits <- reference_environment$fit\n\nreference_fit_comparison <- do.call(rbind, lapply(\n  c(\"Fresh fixed-seed fit\", \"Bundled reference\"),\n  function(source_name) {\n    fit_list <- if (source_name == \"Fresh fixed-seed fit\") {\n      lapply(candidate_k, function(k) get_candidate_fit(\"Primary\", k))\n    } else {\n      reference_fits[candidate_k]\n    }\n    do.call(rbind, lapply(candidate_k, function(k) {\n      score <- fit_scores(fit_list[[k]])\n      data.frame(\n        Source = source_name,\n        K = k,\n        Laplace = score[[\"Laplace\"]],\n        AIC = score[[\"AIC\"]],\n        BIC = score[[\"BIC\"]],\n        stringsAsFactors = FALSE\n      )\n    }))\n  }\n))\n\nreference_profiles_raw <- fit_profiles(reference_fits[[4L]])\nreference_match <- match_profiles(profiles, reference_profiles_raw)\nreference_posteriors <- fit_posteriors(\n  reference_fits[[4L]], rownames(sample_counts)\n)[, reference_match$candidate_for_primary, drop = FALSE]\nreference_state <- state_labels[\n  max.col(reference_posteriors, ties.method = \"first\")\n]\nreference_ari <- adjusted_rand_index(\n  as.character(primary_state), reference_state\n)\n\nstopifnot(\n  reference_fit_comparison$K[\n    reference_fit_comparison$Source == \"Bundled reference\"\n  ][which.min(reference_fit_comparison$Laplace[\n    reference_fit_comparison$Source == \"Bundled reference\"\n  ])] == 4L,\n  abs(reference_ari - 1) <= 1e-12\n)\n```\n:::\n\n\nFresh `k=4` Laplace 约为 38,838.42，包内 reference 约为 38,781.10。两者都选 `k=4`，profile-matched partition 的 ARI 为 1，但 Laplace 数值并不相同；包内对象不能冒充本次 fresh fit。\n\n### 8. 初始化、过滤、深度和单人单样本审计\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninitialization_fits <- c(\n  list(primary_fit),\n  initialization_extra_fits\n)\ninitialization_seeds <- primary_seed + 0:7\n\ninitialization_audit <- do.call(rbind, lapply(\n  seq_along(initialization_fits),\n  function(i) {\n    fit_object <- initialization_fits[[i]]\n    profile_match <- match_profiles(profiles, fit_profiles(fit_object))\n    candidate_posterior <- fit_posteriors(\n      fit_object, rownames(sample_counts)\n    )[, profile_match$candidate_for_primary, drop = FALSE]\n    candidate_state <- state_labels[\n      max.col(candidate_posterior, ties.method = \"first\")\n    ]\n    score <- fit_scores(fit_object)\n    data.frame(\n      Seed = initialization_seeds[[i]],\n      Laplace = score[[\"Laplace\"]],\n      ARIToPrimary = adjusted_rand_index(\n        as.character(primary_state), candidate_state\n      ),\n      StateSizes = paste(\n        as.integer(table(factor(candidate_state, levels = state_labels))),\n        collapse = \"/\"\n      ),\n      MeanMatchedJSD = mean(profile_match$divergence),\n      stringsAsFactors = FALSE\n    )\n  }\n))\n\nsensitivity_agreement <- do.call(rbind, lapply(\n  names(branch_counts),\n  function(branch) {\n    fit_object <- get_candidate_fit(branch, 4L)\n    profile_match <- match_profiles(profiles, fit_profiles(fit_object))\n    candidate_posterior <- fit_posteriors(\n      fit_object, rownames(branch_counts[[branch]])\n    )[, profile_match$candidate_for_primary, drop = FALSE]\n    candidate_state <- state_labels[\n      max.col(candidate_posterior, ties.method = \"first\")\n    ]\n    names(candidate_state) <- rownames(candidate_posterior)\n    overlap <- intersect(names(primary_state), names(candidate_state))\n    data.frame(\n      Branch = branch,\n      Samples = nrow(branch_counts[[branch]]),\n      Features = ncol(branch_counts[[branch]]),\n      SelectedKLaplace = selected_for(branch, \"Laplace\"),\n      FixedK4ARI = adjusted_rand_index(\n        as.character(primary_state[overlap]),\n        candidate_state[overlap]\n      ),\n      MeanMatchedJSD = mean(profile_match$divergence),\n      stringsAsFactors = FALSE\n    )\n  }\n))\n\nstopifnot(\n  sum(initialization_audit$ARIToPrimary == 1) == 8L,\n  length(initialization_audit$Seed[\n    initialization_audit$ARIToPrimary < 1\n  ]) == 0L,\n  initialization_audit$ARIToPrimary[\n    which.min(initialization_audit$Laplace)\n  ] == 1,\n  identical(\n    sensitivity_agreement$SelectedKLaplace,\n    c(4L, 4L, 2L, 2L, 2L)\n  )\n)\n\nknitr::kable(\n  initialization_audit,\n  digits = 4,\n  caption = \"Eight one-shot independent k=4 starts\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Eight one-shot independent k=4 starts\n\n|     Seed|  Laplace| ARIToPrimary|StateSizes  | MeanMatchedJSD|\n|--------:|--------:|------------:|:-----------|--------------:|\n| 20260729| 38838.42|            1|85/86/46/61 |              0|\n| 20260730| 38838.60|            1|85/86/46/61 |              0|\n| 20260731| 38838.59|            1|85/86/46/61 |              0|\n| 20260732| 38838.43|            1|85/86/46/61 |              0|\n| 20260733| 38838.60|            1|85/86/46/61 |              0|\n| 20260734| 38838.60|            1|85/86/46/61 |              0|\n| 20260735| 38838.28|            1|85/86/46/61 |              0|\n| 20260736| 38838.60|            1|85/86/46/61 |              0|\n\n\n:::\n\n```{.r .cell-code}\nknitr::kable(\n  sensitivity_agreement,\n  digits = 4,\n  caption = \"Preprocessing and sampling sensitivity\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Preprocessing and sampling sensitivity\n\n|Branch              | Samples| Features| SelectedKLaplace| FixedK4ARI| MeanMatchedJSD|\n|:-------------------|-------:|--------:|----------------:|----------:|--------------:|\n|Primary             |     278|      130|                4|     1.0000|         0.0000|\n|Prevalence >= 5%    |     278|       67|                4|     0.9035|         0.0002|\n|Depth >= 1,000      |     247|      130|                2|     0.9284|         0.0008|\n|Rarefied to 1,000   |     247|      130|                2|     0.9056|         0.0018|\n|One per participant |     154|      130|                2|     0.6795|         0.0052|\n\n\n:::\n:::\n\n\n`SelectedKLaplace` 检查模型阶数是否改变；`FixedK4ARI` 则在 component 数固定后检查 assignment 是否改变。两者不能互相替代。\n\n### 9. 重复样本与外部 metadata 只做描述\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparticipant_counts <- table(metadata$ParticipantKey)\npaired_keys <- names(participant_counts)[participant_counts == 2L]\n\nparticipant_repeat_audit <- do.call(rbind, lapply(\n  paired_keys,\n  function(key) {\n    ids <- metadata$SampleID[metadata$ParticipantKey == key]\n    no_suffix_id <- ids[metadata[ids, \"SourceSuffix\"] == \"No suffix\"]\n    dot2_id <- ids[metadata[ids, \"SourceSuffix\"] == \"Dot2 suffix\"]\n    data.frame(\n      ParticipantKey = key,\n      NoSuffixSample = no_suffix_id,\n      Dot2SuffixSample = dot2_id,\n      NoSuffixState = as.character(primary_state[no_suffix_id]),\n      Dot2SuffixState = as.character(primary_state[dot2_id]),\n      StateAgreement = primary_state[no_suffix_id] ==\n        primary_state[dot2_id],\n      stringsAsFactors = FALSE\n    )\n  }\n))\n\nrepeat_agreement <- mean(participant_repeat_audit$StateAgreement)\nrepeat_ari <- adjusted_rand_index(\n  participant_repeat_audit$NoSuffixState,\n  participant_repeat_audit$Dot2SuffixState\n)\n\nbmi_cross_tab <- as.data.frame(table(\n  State = factor(primary_state, levels = state_labels),\n  BMIClass = factor(\n    metadata[names(primary_state), \"BMIClass\"],\n    levels = c(\"Lean\", \"Obese\", \"Overweight\")\n  )\n), stringsAsFactors = FALSE)\nnames(bmi_cross_tab)[3L] <- \"Samples\"\nbmi_cross_tab$WithinStateFraction <- ave(\n  bmi_cross_tab$Samples,\n  bmi_cross_tab$State,\n  FUN = function(x) x / sum(x)\n)\n\nstopifnot(\n  length(participant_counts) == 154L,\n  length(paired_keys) == 124L,\n  sum(participant_repeat_audit$StateAgreement) == 85L,\n  abs(repeat_agreement - 0.685483870967742) <= 1e-12,\n  abs(repeat_ari - 0.37678348271377) <= 1e-12\n)\n\nknitr::kable(\n  bmi_cross_tab,\n  digits = 3,\n  caption = \"Descriptive BMIClass cross-tabulation; no hypothesis test\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Descriptive BMIClass cross-tabulation; no hypothesis test\n\n|State |BMIClass   | Samples| WithinStateFraction|\n|:-----|:----------|-------:|-------------------:|\n|DMM-A |Lean       |      15|               0.176|\n|DMM-B |Lean       |      37|               0.430|\n|DMM-C |Lean       |       5|               0.109|\n|DMM-D |Lean       |       4|               0.066|\n|DMM-A |Obese      |      64|               0.753|\n|DMM-B |Obese      |      41|               0.477|\n|DMM-C |Obese      |      38|               0.826|\n|DMM-D |Obese      |      50|               0.820|\n|DMM-A |Overweight |       6|               0.071|\n|DMM-B |Overweight |       8|               0.093|\n|DMM-C |Overweight |       3|               0.065|\n|DMM-D |Overweight |       7|               0.115|\n\n\n:::\n:::\n\n\n同一 key 的两份样本并非独立实验单位；家庭、连续 BMI、饮食、药物和正式 visit metadata 也没有完整分发。因此不运行普通卡方检验，也不把 BMI 交叉表写成疾病关联。\n\n### 10. 计算仅用于显示的 Bray–Curtis PCoA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelative_samples <- sweep(\n  sample_counts, 1L, rowSums(sample_counts), \"/\"\n)\nbray <- vegan::vegdist(relative_samples, method = \"bray\")\npcoa <- cmdscale(bray, k = 2L, eig = TRUE, add = TRUE)\npcoa_points <- pcoa$points\n\nif (cor(pcoa_points[, 1L], relative_samples[, \"Bacteroides\"]) < 0) {\n  pcoa_points[, 1L] <- -pcoa_points[, 1L]\n}\nif (cor(pcoa_points[, 2L], relative_samples[, \"Prevotella\"]) < 0) {\n  pcoa_points[, 2L] <- -pcoa_points[, 2L]\n}\npositive_eigenvalues <- pcoa$eig[pcoa$eig > 0]\naxis_percent <- 100 * pcoa$eig[1:2] / sum(positive_eigenvalues)\n\nordination_scores <- data.frame(\n  SampleID = rownames(pcoa_points),\n  PCoA1 = pcoa_points[, 1L],\n  PCoA2 = pcoa_points[, 2L],\n  State = factor(\n    primary_state[rownames(pcoa_points)],\n    levels = state_labels\n  ),\n  MaximumPosterior = maximum_posterior[rownames(pcoa_points)],\n  ConfidenceClass = ifelse(\n    maximum_posterior[rownames(pcoa_points)] >= 0.8,\n    \"Posterior >= 0.80\",\n    \"Posterior < 0.80\"\n  ),\n  stringsAsFactors = FALSE\n)\n```\n:::\n\n\nPCoA 使用相对丰度 Bray–Curtis，只承担可视化；DMM assignment 来自 raw-count posterior，不来自点到 PCoA centroid 的距离。\n\n## 审计与升级 {#sec-audit-upgrade}\n\n### 1. 先忠实还原原文分析合同\n\n[Holmes、Harris 与 Quince（2012）](https://doi.org/10.1371/journal.pone.0030126)从“sample × genus frequency matrix”出发，用 Dirichlet–multinomial mixture 显式处理离散计数、稀疏性、不同文库大小与 component 内过度离散。他们逐步增加 component 数，以 Laplace approximation to the negative log model evidence 选择模型；Twins 数据在四 component 处达到最低值。随后用 Bray–Curtis NMDS 显示样本与 Dirichlet component means，并强调样本不一定属于二维图中最近的 component mean。BMI 与 component 的关系则另列成表，不参与无监督拟合。\n\n本页忠实保留了四个关键点：输入仍是原始属级频数；`k` 由模型证据而不是肉眼看排序图决定；assignment 来自 DMM posterior 而不是最近质心；BMIClass 在拟合完成后才进入描述。`DirichletMultinomial` 随包的 `fit` 对象也单独保留为 reference，避免把历史对象误写成本次重新拟合。\n\n\n::: {.cell}\n\n```{.r .cell-code}\naudit_upgrade <- data.frame(\n  Dimension = c(\n    \"Likelihood input\", \"Component count\", \"Ordination\", \"Assignments\",\n    \"Initialization\", \"Component identity\", \"Uncertainty\", \"Phenotype\"\n  ),\n  OriginalAnalysis = c(\n    \"Raw sample-by-genus frequencies\",\n    \"Laplace negative log model evidence\",\n    \"Bray-Curtis NMDS with component means\",\n    \"Posterior DMM component\",\n    \"One reported fitted solution\",\n    \"Numeric component index\",\n    \"Probabilistic model, hard labels shown\",\n    \"BMI-by-component comparison\"\n  ),\n  ReanalysisAndUpgrade = c(\n    \"Same raw integer count contract\",\n    \"Laplace primary; AIC and BIC shown in parallel\",\n    \"Bray-Curtis PCoA used only as a display\",\n    \"All posterior probabilities retained\",\n    \"Eight one-shot independent fresh starts\",\n    \"Profile matching plus deterministic names\",\n    \"Maximum posterior and entropy audited\",\n    \"Descriptive only under incomplete covariates\"\n  ),\n  stringsAsFactors = FALSE\n)\n\nknitr::kable(\n  audit_upgrade,\n  caption = \"Original DMM analysis and prespecified upgrades\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Original DMM analysis and prespecified upgrades\n\n|Dimension          |OriginalAnalysis                       |ReanalysisAndUpgrade                           |\n|:------------------|:--------------------------------------|:----------------------------------------------|\n|Likelihood input   |Raw sample-by-genus frequencies        |Same raw integer count contract                |\n|Component count    |Laplace negative log model evidence    |Laplace primary; AIC and BIC shown in parallel |\n|Ordination         |Bray-Curtis NMDS with component means  |Bray-Curtis PCoA used only as a display        |\n|Assignments        |Posterior DMM component                |All posterior probabilities retained           |\n|Initialization     |One reported fitted solution           |Eight one-shot independent fresh starts        |\n|Component identity |Numeric component index                |Profile matching plus deterministic names      |\n|Uncertainty        |Probabilistic model, hard labels shown |Maximum posterior and entropy audited          |\n|Phenotype          |BMI-by-component comparison            |Descriptive only under incomplete covariates   |\n\n\n:::\n:::\n\n\n### 2. 哪些原结论在这次重跑中保留\n\n- 原文与包内 reference fit 都以 Laplace criterion 支持四个 component；固定 seed 的 fresh fit 也选择 `k=4`。\n- 原文指出 component 的均值和变异程度都不同；本页的完整 fitted profiles 与 component summaries 保留这两个层面，不用单个“优势菌”替代整个分布。\n- 原文 Figure 2 已提醒“最近二维质心”不等于 model assignment；本页进一步把 posterior confidence 编码到排序图中。\n- 原文没有把 BMI 写成一个独立、确定的肥胖菌群类型；本页也不把四个 state 改名为疾病亚型。\n\n### 3. 哪些地方需要按今天的标准升级\n\n第一，**不能只保存一个 optimizer 结果**。本次八个 one-shot starts 得到相同 partition，但不同 start 的 Laplace 值仍略有差异；实际研究仍应预声明 start 数，以最优目标值选最终 fit，并保存全部 seed、目标值和 assignment agreement。每个 fit 使用一次性进程，可避免前序模型状态成为未记录的隐藏输入。\n\n第二，**不能把 component number 当作可迁移标签**。跨 seed、过滤方案或队列比较前，要按完整 profile 匹配 component，再计算 ARI；命名规则也应在看表型关联前固定。\n\n第三，**不能只画 hard class**。最大 posterior 与 normalized entropy 揭示边界样本；论文主图至少应通过透明度、形状或单独面板呈现不确定性，补充表保留所有 posterior。\n\n第四，**模型阶数与 assignment 稳定性必须分开审计**。本例 prevalence filter 仍选四 component，但 depth、rarefaction 和 one-per-participant 分支改选两个；固定 `k=4` 的 ARI 又显示不同程度的 partition 漂移。只报告“最佳 `k` 没变”或“ARI 尚可”都不完整。\n\n第五，**外部关联必须尊重实验单位和协变量**。后缀推导的重复结构不足以替代 subject、family、visit、diet、medication 与连续 BMI；因此这里把 BMIClass 和重复样本作为描述性审计，不复刻未经完整设计控制的显著性叙事。\n\n::: {.callout-important title=\"升级后的最低报告集\"}\n主文同时给 model-selection curves、component profiles、posterior-aware ordination 与 stability ledger；补充材料交付每个 fit 的 criterion、component matching、所有样本 posterior、初始化 agreement、过滤/深度敏感性和重复样本转移表。只有外部队列中的 profile transportability、posterior calibration 与纵向稳定性也成立时，才适合把数据内的 `DMM-A`–`DMM-D` 提升为可复用的 enterotype/CST 名称。\n:::\n\n## 出版级美化 {#sec-publication}\n\n### 图 1：三个准则和两个 fit source 同图\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncriterion_plot_data <- do.call(rbind, lapply(\n  c(\"Laplace\", \"AIC\", \"BIC\"),\n  function(criterion) {\n    data.frame(\n      Source = reference_fit_comparison$Source,\n      K = reference_fit_comparison$K,\n      Criterion = criterion,\n      Score = reference_fit_comparison[[criterion]],\n      stringsAsFactors = FALSE\n    )\n  }\n))\ncriterion_plot_data$Minimum <- ave(\n  criterion_plot_data$Score,\n  interaction(\n    criterion_plot_data$Source,\n    criterion_plot_data$Criterion\n  ),\n  FUN = function(x) x == min(x)\n) == 1\ncriterion_plot_data$Criterion <- factor(\n  criterion_plot_data$Criterion,\n  levels = c(\"Laplace\", \"AIC\", \"BIC\")\n)\n\nmodel_selection_plot <- ggplot(\n  criterion_plot_data,\n  aes(x = K, y = Score, colour = Source, linetype = Source)\n) +\n  geom_line(linewidth = 0.75) +\n  geom_point(size = 2.0) +\n  geom_point(\n    data = criterion_plot_data[criterion_plot_data$Minimum, ],\n    shape = 21, fill = \"white\", stroke = 1.0, size = 3.4\n  ) +\n  facet_wrap(~Criterion, scales = \"free_y\", ncol = 1L) +\n  scale_x_continuous(breaks = candidate_k) +\n  scale_colour_manual(values = c(\n    \"Fresh fixed-seed fit\" = \"#0072B2\",\n    \"Bundled reference\" = \"#D55E00\"\n  )) +\n  scale_linetype_manual(values = c(\n    \"Fresh fixed-seed fit\" = \"solid\",\n    \"Bundled reference\" = \"22\"\n  )) +\n  scale_y_continuous(labels = scales::label_comma(accuracy = 1)) +\n  labs(\n    title = \"Model-selection criteria do not tell the same story\",\n    subtitle = paste(\n      \"Open circles mark criterion minima within each\",\n      \"independently fitted series\"\n    ),\n    x = \"Number of mixture components (k)\",\n    y = \"Criterion score (lower is better)\",\n    colour = \"Fit source\",\n    linetype = \"Fit source\",\n    caption = paste0(\n      \"Fresh Laplace selects k = 4; fresh AIC selects k = 2 and BIC selects k = 1.\\n\",\n      \"The bundled reference has a lower k = 4 Laplace value but the same Laplace minimum.\"\n    )\n  ) +\n  theme_pub(base_size = 8.8) +\n  theme(legend.position = \"bottom\")\n\nsave_pub(\n  model_selection_plot,\n  \"figures/29-model-selection\",\n  width = 170,\n  height = 158\n)\nmodel_selection_plot\n```\n\n::: {.cell-output-display}\n![](29-community-typing-dmm_files/figure-html/fig-dmm-model-selection-1.png){#fig-dmm-model-selection}\n:::\n:::\n\n\n开放圆圈让读者直接看到：Laplace 的两个来源都在 4 最小，但 AIC/BIC 支持更简单的模型。完整曲线比单独写“最佳 `k=4`”更诚实。\n\n### 图 2：posterior uncertainty 进入排序图\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_colours <- c(\n  \"DMM-A\" = \"#0072B2\",\n  \"DMM-B\" = \"#E69F00\",\n  \"DMM-C\" = \"#009E73\",\n  \"DMM-D\" = \"#CC79A7\"\n)\nstate_centroids <- aggregate(\n  ordination_scores[, c(\"PCoA1\", \"PCoA2\")],\n  list(State = ordination_scores$State),\n  mean\n)\n\nposterior_ordination_plot <- ggplot(\n  ordination_scores,\n  aes(x = PCoA1, y = PCoA2, colour = State)\n) +\n  geom_point(\n    aes(alpha = MaximumPosterior, shape = ConfidenceClass),\n    size = 2.2,\n    stroke = 0.55\n  ) +\n  geom_point(\n    data = state_centroids,\n    shape = 4,\n    size = 4.2,\n    stroke = 1.1,\n    show.legend = FALSE\n  ) +\n  scale_colour_manual(values = state_colours, drop = FALSE) +\n  scale_alpha_continuous(\n    range = c(0.32, 0.9), limits = c(0, 1), guide = \"none\"\n  ) +\n  scale_shape_manual(values = c(\n    \"Posterior >= 0.80\" = 16,\n    \"Posterior < 0.80\" = 1\n  )) +\n  coord_equal() +\n  labs(\n    title = \"DMM states are posterior assignments, not PCoA quadrants\",\n    subtitle = paste(\n      \"Bray-Curtis PCoA is shown only as a two-dimensional\",\n      \"descriptive view\"\n    ),\n    x = sprintf(\n      \"PCoA 1 (%.1f%% of positive eigenvalue sum)\",\n      axis_percent[[1L]]\n    ),\n    y = sprintf(\n      \"PCoA 2 (%.1f%% of positive eigenvalue sum)\",\n      axis_percent[[2L]]\n    ),\n    colour = \"DMM state\",\n    shape = \"Assignment confidence\",\n    caption = paste0(\n      \"Crosses are state centroids. Open points have maximum posterior below 0.80.\\n\",\n      \"The DMM was fitted to raw counts; ordination did not define the states.\"\n    )\n  ) +\n  theme_pub(base_size = 8.8) +\n  guides(\n    colour = guide_legend(order = 1L, nrow = 1L),\n    shape = guide_legend(order = 2L, nrow = 1L)\n  ) +\n  theme(\n    legend.position = \"bottom\",\n    legend.box = \"vertical\"\n  )\n\nsave_pub(\n  posterior_ordination_plot,\n  \"figures/29-posterior-ordination\",\n  width = 170,\n  height = 125\n)\nposterior_ordination_plot\n```\n\n::: {.cell-output-display}\n![](29-community-typing-dmm_files/figure-html/fig-dmm-posterior-ordination-1.png){#fig-dmm-posterior-ordination}\n:::\n:::\n\n\n空心点标出最大 posterior `<0.80` 的 8 个样本；颜色、形状和透明度共同编码，灰度打印时仍能识别低置信度点。\n\n### 图 3：展示完整 component profile，而不是贴单菌标签\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_profile_features <- unique(unlist(lapply(state_labels, function(state) {\n  names(sort(profiles[, state], decreasing = TRUE))[1:5]\n})))\ntop_profile_features <- top_profile_features[\n  order(\n    apply(profiles[top_profile_features, , drop = FALSE], 1L, max),\n    decreasing = TRUE\n  )\n]\n\nprofile_plot_data <- data.frame(\n  FeatureID = rep(rownames(profiles), times = ncol(profiles)),\n  DisplayGenus = rep(ifelse(\n    taxonomy[rownames(profiles), \"Genus\"] == \"Uknown\",\n    \"Unclassified\",\n    taxonomy[rownames(profiles), \"Genus\"]\n  ), times = ncol(profiles)),\n  State = rep(state_labels, each = nrow(profiles)),\n  ExpectedProportion = as.vector(profiles),\n  stringsAsFactors = FALSE\n)\nprofile_plot_data <- profile_plot_data[\n  profile_plot_data$FeatureID %in% top_profile_features,\n]\nprofile_plot_data$DisplayGenus <- factor(\n  profile_plot_data$DisplayGenus,\n  levels = rev(ifelse(\n    taxonomy[top_profile_features, \"Genus\"] == \"Uknown\",\n    \"Unclassified\",\n    taxonomy[top_profile_features, \"Genus\"]\n  ))\n)\nprofile_plot_data$State <- factor(\n  profile_plot_data$State,\n  levels = state_labels\n)\n\ncomponent_profiles_plot <- ggplot(\n  profile_plot_data,\n  aes(x = State, y = DisplayGenus, fill = ExpectedProportion)\n) +\n  geom_tile(colour = \"white\", linewidth = 0.55) +\n  geom_text(\n    aes(\n      label = ifelse(\n        ExpectedProportion >= 0.005,\n        scales::percent(ExpectedProportion, accuracy = 0.1),\n        \"<0.5%\"\n      ),\n      colour = ExpectedProportion >= 0.25\n    ),\n    family = font_pub,\n    size = 2.45\n  ) +\n  scale_colour_manual(\n    values = c(`FALSE` = \"#17202A\", `TRUE` = \"white\"),\n    guide = \"none\"\n  ) +\n  scale_fill_gradientn(\n    colours = c(\n      \"#F7FBFF\", \"#C6DBEF\", \"#6BAED6\", \"#2171B5\", \"#08306B\"\n    ),\n    labels = scales::label_percent(accuracy = 1)\n  ) +\n  labs(\n    title = \"Component profiles are distributions, not single-taxon labels\",\n    subtitle = paste(\n      \"Union of the five highest expected-proportion genera\",\n      \"in each fitted state\"\n    ),\n    x = \"Canonical DMM state\",\n    y = \"Source genus category\",\n    fill = \"Expected proportion\",\n    caption = paste0(\n      \"The source label 'Uknown' is displayed as Unclassified without changing counts.\\n\",\n      \"State letters are deterministic profile labels, not biological diagnoses.\"\n    )\n  ) +\n  theme_pub(base_size = 8.8) +\n  theme(\n    legend.position = \"bottom\",\n    panel.grid = element_blank(),\n    axis.text.x = element_text(face = \"bold\")\n  )\n\nsave_pub(\n  component_profiles_plot,\n  \"figures/29-component-profiles\",\n  width = 165,\n  height = 122\n)\ncomponent_profiles_plot\n```\n\n::: {.cell-output-display}\n![](29-community-typing-dmm_files/figure-html/fig-dmm-component-profiles-1.png){#fig-dmm-component-profiles}\n:::\n:::\n\n\n四列都包含多个 genus 和大比例未分类 reads。优势项有助于描述 component，却不足以给状态贴功能、健康或病理标签。\n\n### 图 4：把稳定性证据做成一张账本\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstability_plot_data <- rbind(\n  data.frame(\n    Panel = \"Fresh-start ARI\",\n    Category = as.character(initialization_audit$Seed),\n    Value = initialization_audit$ARIToPrimary,\n    Label = sprintf(\"%.2f\", initialization_audit$ARIToPrimary)\n  ),\n  data.frame(\n    Panel = \"Sensitivity ARI\",\n    Category = sensitivity_agreement$Branch,\n    Value = sensitivity_agreement$FixedK4ARI,\n    Label = sprintf(\"%.2f\", sensitivity_agreement$FixedK4ARI)\n  ),\n  data.frame(\n    Panel = \"Selected k (Laplace)\",\n    Category = sensitivity_agreement$Branch,\n    Value = sensitivity_agreement$SelectedKLaplace,\n    Label = as.character(sensitivity_agreement$SelectedKLaplace)\n  ),\n  data.frame(\n    Panel = \"Repeated source pairs\",\n    Category = c(\"Same state\", \"Different state\"),\n    Value = c(\n      sum(participant_repeat_audit$StateAgreement),\n      sum(!participant_repeat_audit$StateAgreement)\n    ),\n    Label = as.character(c(\n      sum(participant_repeat_audit$StateAgreement),\n      sum(!participant_repeat_audit$StateAgreement)\n    ))\n  )\n)\nstability_plot_data$Panel <- factor(\n  stability_plot_data$Panel,\n  levels = c(\n    \"Fresh-start ARI\", \"Sensitivity ARI\",\n    \"Selected k (Laplace)\", \"Repeated source pairs\"\n  )\n)\nstability_plot_data$Category <- factor(\n  stability_plot_data$Category,\n  levels = c(\n    as.character(initialization_seeds),\n    names(branch_counts),\n    \"Same state\", \"Different state\"\n  )\n)\n\nstability_audit_plot <- ggplot(\n  stability_plot_data,\n  aes(x = Category, y = Value, fill = Panel)\n) +\n  geom_col(width = 0.68, show.legend = FALSE) +\n  geom_text(\n    aes(label = Label),\n    vjust = -0.3,\n    family = font_pub,\n    size = 2.6\n  ) +\n  facet_wrap(~Panel, scales = \"free\", ncol = 2L) +\n  scale_fill_manual(values = c(\n    \"Fresh-start ARI\" = \"#0072B2\",\n    \"Sensitivity ARI\" = \"#009E73\",\n    \"Selected k (Laplace)\" = \"#E69F00\",\n    \"Repeated source pairs\" = \"#CC79A7\"\n  )) +\n  scale_y_continuous(\n    expand = expansion(mult = c(0, 0.13))\n  ) +\n  labs(\n    title = \"A state label is credible only with a stability ledger\",\n    subtitle = paste(\n      \"Initialization, preprocessing, component count and repeated\",\n      \"samples answer different questions\"\n    ),\n    x = NULL,\n    y = \"Audit value\",\n    caption = paste0(\n      \"ARI comparisons use profile-matched k = 4 states on overlapping samples.\\n\",\n      \"Suffix-derived pairs are descriptive because clinical visit timing is not distributed.\"\n    )\n  ) +\n  theme_pub(base_size = 8.2) +\n  theme(\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor = element_blank(),\n    axis.text.x = element_text(angle = 28, hjust = 1),\n    strip.text = element_text(size = 8.5)\n  )\n\nsave_pub(\n  stability_audit_plot,\n  \"figures/29-stability-audit\",\n  width = 180,\n  height = 135\n)\nstability_audit_plot\n```\n\n::: {.cell-output-display}\n![](29-community-typing-dmm_files/figure-html/fig-dmm-stability-audit-1.png){#fig-dmm-stability-audit}\n:::\n:::\n\n\n这张图把四类问题分开：optimizer 是否落入局部解、预处理是否改变 assignment、最佳 `k` 是否改变、同一 participant key 的两份样本是否保持状态。不能用其中一个面板替代另外三个。\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     Validation Passed Total\n1 Repository QA    222   222\n```\n\n\n:::\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"坑 1：先转相对丰度或 CLR，再送进 DMM\"}\n这条实现的 likelihood 输入是 raw non-negative integer counts。相对丰度、CLR 和伪计数属于其他分析合同；不能因为所有方法都处理“群落组成”就交换输入。\n:::\n\n::: {.callout-caution title=\"坑 2：只报告一个最优 k\"}\n至少给 candidate range、选择准则和完整曲线。本例若只给 Laplace，会隐藏 AIC/BIC 分别支持 2/1 component 的事实。\n:::\n\n::: {.callout-caution title=\"坑 3：把 PCoA 上的颜色块当作建模证据\"}\nPCoA 只显示两个轴，点的颜色又来自已经拟合的 DMM。它是结果可视化，不是独立证明；不要用“看起来分开”替代 model evidence、posterior 和 stability。\n:::\n\n::: {.callout-caution title=\"坑 4：直接比较 component 1、2、3、4\"}\nMixture label 可以交换。跨 seed、过滤分支和外部队列比较前，先按 profile 一一匹配，再计算 ARI 或其他 agreement。\n:::\n\n::: {.callout-caution title=\"坑 5：只跑一次初始化\"}\n本例 8 个 one-shot starts 的 partition 一致，但这不是省略 multi-start 的理由。应保存每次 seed、Laplace、state size、profile distance 和 assignment agreement，并核对最低目标值对应的 partition；若复用 worker，还要确认前序 fit 不会影响同 seed 的结果。\n:::\n\n::: {.callout-caution title=\"坑 6：只保存 hard assignment\"}\n必须保留每个 component posterior、最大 posterior 和 entropy。低置信度样本应在图中以形状、透明度或单独标记显示，不能硬涂成确定类别。\n:::\n\n::: {.callout-caution title=\"坑 7：过滤或抽平后不重新选 k\"}\nFeature set、sample set 和 depth 改变都会改变 likelihood。既要重新比较 `k`，也要在共同样本上固定 `k` 检查 assignment；只做其一会混淆模型阶数变化与标签变化。\n:::\n\n::: {.callout-caution title=\"坑 8：把重复样本当成独立病例\"}\n同一 participant 的多份样本不增加同等数量的独立实验单位。外部关联要按 subject/family/visit 结构建模；没有正式 metadata 时，只做描述性 agreement。\n:::\n\n::: {.callout-caution title=\"坑 9：按优势菌给 state 贴疾病或功能标签\"}\nExpected profile 是相对 read composition。没有绝对负荷、功能实验、混杂调整、外部验证和纵向证据时，不能推出致病、保护、代谢功能或不可逆状态。\n:::\n\n::: {.callout-caution title=\"坑 10：把 enterotype/CST 当作跨队列通用字典\"}\n身体部位、扩增区域、数据库、队列构成、药物与饮食都可能移动 component。外部数据应重新估计或执行预注册的 label-transfer/validation，而不是按几个 genus 阈值硬套名称。\n:::\n\n## 这段 Methods 怎么写 {#sec-methods}\n\n> Community states were estimated from the unrarefied, non-negative integer genus-count matrix using Dirichlet-multinomial mixture models implemented in DirichletMultinomial 1.46.0. Candidate models with one to seven components were fitted with seed 20260729, and the primary component count was selected by the minimum Laplace approximation; AIC and BIC were retained as parallel diagnostics. A minimum assigned-component size of max(10, 5% of samples) was prespecified. For the selected four-component model, component labels were canonicalized by decreasing fitted Bacteroides proportion, followed by decreasing Prevotella proportion and raw component index. All component posterior probabilities, the maximum posterior probability, and normalized entropy were retained; assignments with maximum posterior probability below 0.80 were marked as low confidence. Initialization sensitivity was assessed across seeds 20260729–20260736 using one fresh, single-threaded R process per fit. Components across fits were matched by minimum Jensen–Shannon divergence between fitted profiles before adjusted Rand indices were calculated. Sensitivity analyses repeated model selection after 5% prevalence filtering, exclusion of libraries below 1,000 reads, deterministic rarefaction of eligible libraries to 1,000 reads, and selection of one sample per suffix-derived participant key. Bray–Curtis PCoA was used only for descriptive visualization and did not define state membership. BMI class and repeated-source-sample transitions were summarized descriptively without disease-association testing because family, visit, continuous BMI, medication, and dietary covariates were not fully available.\n\n替换版本、feature rank、candidate `k`、主准则、seed、最小 component size、低置信度阈值和 sensitivity contract。若最终采用多个 start 中目标值最小的模型，应明确写出 start 数和选择规则，而不是只给最终 seed。\n\n## 换成你自己的数据怎么做 {#sec-own-data}\n\n### 1. 只替换三件套路径和 metadata 列\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"your_data/otutab.tsv\",\n  taxonomy = \"your_data/taxonomy.tsv\",\n  metadata = \"your_data/metadata.tsv\"\n)\nsubject_column <- \"SubjectID\"\nvisit_column <- \"Visit\"\nexternal_group_column <- \"Phenotype\"\n```\n:::\n\n\n`otutab` 必须是 feature × sample 的 raw integer counts；taxonomy 行名与 feature 一致；metadata 行名覆盖全部样本。若输入已经是百分比或 CLR，回到未转换 count table。\n\n### 2. 在看结果前写下模型合同\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_feature_rank <- \"Genus\"\ncandidate_k <- 1:7\nprimary_selection_criterion <- \"Laplace\"\nprimary_seed <- 20260729L\ninitialization_seeds <- primary_seed + 0:19\nminimum_state_size <- max(10L, ceiling(0.05 * nrow(sample_counts)))\nlow_confidence_threshold <- 0.80\nprevalence_sensitivity <- 0.05\ndepth_sensitivity <- 1000L\n```\n:::\n\n\nCandidate range 应由样本量、预期最小 state 和研究问题决定。不要看到 `k=7` 仍在下降后临时扩大范围，却不重新定义小类门槛和验证计划。\n\n### 3. taxonomy 只有一列字符串时先拆成七列\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxonomy_raw <- readr::read_tsv(\n  \"your_data/taxonomy-single-column.tsv\",\n  show_col_types = FALSE\n)\nrank_names_7 <- c(\n  \"Kingdom\", \"Phylum\", \"Class\", \"Order\", \"Family\", \"Genus\", \"Species\"\n)\nparts <- strsplit(taxonomy_raw$Taxon, \";\", fixed = TRUE)\ntaxonomy_matrix <- t(vapply(parts, function(x) {\n  x <- trimws(x)\n  length(x) <- length(rank_names_7)\n  x\n}, character(length(rank_names_7))))\ntaxonomy <- as.data.frame(taxonomy_matrix, stringsAsFactors = FALSE)\nnames(taxonomy) <- rank_names_7\nrownames(taxonomy) <- taxonomy_raw$FeatureID\n```\n:::\n\n\n聚合到 genus 时按完整 lineage key 处理同名 taxa；多个空 genus 不应未经说明地并成一个人工高丰度 `Unknown`。\n\n### 4. 外部验证至少分三层\n\n1. **Internal stability**：多初始化、bootstrap/subsample、过滤和深度敏感性；\n2. **Temporal stability**：同一 subject 的状态保持、转移概率和 posterior 变化；\n3. **External transportability**：独立队列中重新拟合或预注册映射，报告 profile similarity、assignment confidence 与 calibration。\n\n疾病或环境关联应使用独立实验单位并调整预声明协变量。状态是自变量、因变量还是分层变量，要在看 association 结果前确定。\n\n### 5. 最少保留这些审计输出\n\n- 每个 `k`、每个 seed 的 Laplace/AIC/BIC 与运行状态；\n- 每个 component 的 mixture weight、theta、完整 expected profile 和 assigned size；\n- 每个样本的所有 posterior、最大 posterior、entropy 和 hard label；\n- label canonicalization 与跨 fit profile-matching ledger；\n- 初始化 pairwise ARI、潜在局部解及最佳目标值对应的 partition；\n- filtering、depth、rarefaction、one-per-subject 的重新选 `k` 和 fixed-`k` agreement；\n- subject/visit 重复结构与外部 metadata 的可检验边界；\n- 图形尺寸、字体、PDF/SVG/PNG/TIFF 格式审计。\n\n## 参考 {#sec-references}\n\n1. Holmes I, Harris K, Quince C. Dirichlet Multinomial Mixtures: Generative Models for Microbial Metagenomics. *PLOS ONE*. 2012;7(2):e30126. [doi:10.1371/journal.pone.0030126](https://doi.org/10.1371/journal.pone.0030126).\n2. Turnbaugh PJ, Hamady M, Yatsunenko T, et al. A core gut microbiome in obese and lean twins. *Nature*. 2009;457:480–484. [doi:10.1038/nature07540](https://doi.org/10.1038/nature07540).\n3. Arumugam M, Raes J, Pelletier E, et al. Enterotypes of the human gut microbiome. *Nature*. 2011;473:174–180. [doi:10.1038/nature09944](https://doi.org/10.1038/nature09944).\n4. Ravel J, Gajer P, Abdo Z, et al. Vaginal microbiome of reproductive-age women. *Proceedings of the National Academy of Sciences*. 2011;108(S1):4680–4687. [doi:10.1073/pnas.1002611107](https://doi.org/10.1073/pnas.1002611107).\n5. Koren O, Knights D, Gonzalez A, et al. A guide to enterotypes across the human body: meta-analysis of microbial community structures in human microbiome datasets. *PLOS Computational Biology*. 2013;9(1):e1002863. [doi:10.1371/journal.pcbi.1002863](https://doi.org/10.1371/journal.pcbi.1002863).\n6. Costea PI, Hildebrand F, Arumugam M, et al. Enterotypes in the landscape of gut microbial community composition. *Nature Microbiology*. 2018;3:8–16. [doi:10.1038/s41564-017-0072-8](https://doi.org/10.1038/s41564-017-0072-8).\n7. Morgan M. [DirichletMultinomial 1.46.0](https://bioconductor.org/packages/3.19/bioc/html/DirichletMultinomial.html). Bioconductor 3.19. [doi:10.18129/B9.bioc.DirichletMultinomial](https://doi.org/10.18129/B9.bioc.DirichletMultinomial).\n8. Oksanen J, et al. [vegan: Community Ecology Package](https://cran.r-project.org/package=vegan).\n9. Wickham H, et al. [ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics](https://ggplot2.tidyverse.org/).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}