{
  "hash": "66cb01a4c040584fdb1df7bb50ea986c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PERMANOVA + betadisper（必配）+ ANOSIM/MRPP\"\nauthor: \"Peter\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\n    number-sections: false\nexecute:\n  eval: true\n  freeze: auto\n  warning: false\n  message: false\nfig-dpi: 300\nfig-format: png\nreader-reproduction:\n  required: true\n  label-policy: all-executed\n  script: examples/23-permanova-dispersion.R\n  packages:\n  - digest\n  - ggplot2\n  - jsonlite\n  - permute\n  - ragg\n  - readr\n  - scales\n  - svglite\n  - vegan\n---\n\n## PERMANOVA 必须与离散度检验一起解释 {#sec-target}\n\nPERMANOVA 常对应论文中的 PCoA/NMDS 分组图和一张含 pseudo-F、(R^2)、P 值的统计表。真正需要回答的不是“彩色点是否看起来分开”，而是：\n\n1. 组间群落中心位置是否不同；\n2. 观察到的差异是否可能来自组内离散程度不同；\n3. 置换有没有保持配对、区组、whole plot 和技术重复结构；\n4. 结果对 feature filter、实验单位和置换方案是否稳健。\n\n本例使用 `phyloseq` 1.48.0 分发的真实 `soilrep` 数据，来源于长期增温 × 剪草草地实验。[Zhou et al. (2011)](https://doi.org/10.1038/ismej.2011.11)采用 6 个区组的 paired nested/split-plot 设计，并用多标签扩增测序研究方法重复性与处理响应。源对象保留 56 个 PCR/tag 文库，每个处理 14 个；这些文库对应 24 个生物学土壤样本，不能作为 56 个独立样本进入推断。\n\n原研究 Figure 2 的预处理保留“在任一处理至少 4 个 tagged libraries 中检出”的 feature。本页预先沿用该阈值作为主分析，先把同一土壤样本的 1–3 个技术文库相加，再计算 relative-abundance Bray–Curtis；论文图不直接复制，而是从公开数据重绘实验单位、中心/离散度、计划比较和 PERMDISP 四张英文图。\n\n::: {.callout-important title=\"先给结论\"}\n在研究锚定的 feature filter 和合法 split-plot 置换下，四水平 treatment omnibus PERMANOVA 的 total (R^2=0.0981)、block-adjusted partial (R^2=0.1847)、(P=0.0065)；区组本身解释 total (R^2=0.4689)。对应的 bias-adjusted spatial-median PERMDISP 为 (F=0.403)、(P=0.3714)，没有发现全局离散度差异。\n\n这个信号不能简化成“所有处理比较都显著”。Warming、Clipping 与交互项的 Holm-adjusted P 分别为 0.132、0.120 和 0.120；四个计划 simple effects 的 Holm-adjusted P 均为 0.125。更重要的是，保留全部 16,825 个 feature、仍使用同一合法置换时，omnibus P 变为 0.7642。因而结论应写成：**主预处理分支检测到条件性的整体位置差异，未见全局 dispersion 证据，但结果对 feature filter 敏感，不能宣称稳健而普遍的处理效应。**\n:::\n\n## 下载并读取本次分析的数据 {#sec-setup}\n\n需要 R，以及 `digest`、`ggplot2`、`jsonlite`、`permute`、`ragg`、`readr`、`scales`、`svglite`、`vegan`。本次使用用于分组比较的 count、taxonomy、metadata 三张表；样本表保留重复与区组信息。\n\n在一个新建的文件夹中运行以下代码，下载文件后按文中的顺序继续分析：\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 600)\ndata_url <- \"https://raw.githubusercontent.com/petemeng/microbiome-best-practices/3cb6a817e0c73ab7ecbec1cedc1ad80cbb9ecfaa/\"\ninput_files <- c(\n  \"data/small/permanova-dispersion/metadata.tsv\",\n  \"data/small/permanova-dispersion/otutab.tsv\",\n  \"data/small/permanova-dispersion/source-summary.json\",\n  \"data/small/permanova-dispersion/taxonomy.tsv\"\n)\nfor (path in input_files) {\n  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)\n  if (!file.exists(path)) download.file(paste0(data_url, path), path, mode = \"wb\", quiet = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(digest)\nlibrary(ggplot2)\nlibrary(jsonlite)\nlibrary(permute)\nlibrary(readr)\nlibrary(scales)\nlibrary(vegan)\n\nset.seed(20260723)\n\nfont_pub <- \"sans\"\npal_pub <- c(\n  blue = \"#0072B2\", orange = \"#E69F00\", green = \"#009E73\",\n  vermillion = \"#D55E00\", purple = \"#CC79A7\", sky = \"#56B4E9\",\n  yellow = \"#F0E442\", grey = \"#6B7280\"\n)\n\nscale_color_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_color_manual(..., values = values)\n}\n\nscale_fill_pub <- function(..., values = unname(pal_pub)) {\n  ggplot2::scale_fill_manual(..., values = values)\n}\n\ntheme_pub <- function(base_size = 10, base_family = font_pub) {\n  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +\n    ggplot2::theme(\n      panel.grid.minor = ggplot2::element_blank(),\n      panel.grid.major = ggplot2::element_line(\n        colour = \"#E6E6E6\", linewidth = 0.25\n      ),\n      axis.text = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.title = ggplot2::element_text(colour = \"#1A1A1A\"),\n      axis.ticks = ggplot2::element_line(\n        colour = \"#1A1A1A\", linewidth = 0.3\n      ),\n      plot.title.position = \"plot\",\n      plot.title = ggplot2::element_text(\n        face = \"bold\", size = ggplot2::rel(1.15)\n      ),\n      plot.subtitle = ggplot2::element_text(colour = \"#4D4D4D\"),\n      plot.caption = ggplot2::element_text(colour = \"#666666\", hjust = 0),\n      strip.background = ggplot2::element_rect(\n        fill = \"#F2F2F2\", colour = \"#B3B3B3\", linewidth = 0.3\n      ),\n      strip.text = ggplot2::element_text(face = \"bold\"),\n      legend.key = ggplot2::element_blank(),\n      legend.position = \"top\"\n    )\n}\n\nsave_pub <- function(\n  plot, file_base, width = 89, height = 70, units = \"mm\",\n  dpi = 600, write_svg = TRUE, write_tiff = TRUE,\n  base_family = font_pub\n) {\n  dir.create(dirname(file_base), recursive = TRUE, showWarnings = FALSE)\n  ggplot2::ggsave(\n    paste0(file_base, \".pdf\"), plot,\n    width = width, height = height, units = units,\n    device = grDevices::cairo_pdf, family = base_family, bg = \"white\"\n  )\n  if (isTRUE(write_svg)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".svg\"), plot,\n      width = width, height = height, units = units,\n      device = svglite::svglite, bg = \"white\"\n    )\n  }\n  ggplot2::ggsave(\n    paste0(file_base, \".png\"), plot,\n    width = width, height = height, units = units, dpi = dpi,\n    device = ragg::agg_png, bg = \"white\"\n  )\n  if (isTRUE(write_tiff)) {\n    ggplot2::ggsave(\n      paste0(file_base, \".tiff\"), plot,\n      width = width, height = height, units = units, dpi = dpi,\n      device = ragg::agg_tiff, compression = \"lzw\", bg = \"white\"\n    )\n  }\n  invisible(plot)\n}\n\nformat_p <- function(p) {\n  ifelse(is.na(p), \"NA\", ifelse(p < 0.001, \"<0.001\", sprintf(\"%.3f\", p)))\n}\n```\n:::\n\n\n### 读取三件套并锁定数据身份\n\n`otutab` 是 feature × technical library 的原始非负整数表。taxonomy 保留标准接口，但本数据源没有 rank annotations；metadata 明确给出技术文库所属的 biological sample、block、main plot 和处理。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_keyed_tsv <- function(path) {\n  x <- readr::read_tsv(\n    path,\n    show_col_types = FALSE,\n    progress = FALSE,\n    name_repair = \"minimal\",\n    na = character()\n  )\n  ids <- as.character(x[[1L]])\n  stopifnot(!anyDuplicated(ids))\n  out <- as.data.frame(x[-1L], check.names = FALSE)\n  rownames(out) <- ids\n  out\n}\n\ninput_paths <- c(\n  otutab = \"data/small/permanova-dispersion/otutab.tsv\",\n  taxonomy = \"data/small/permanova-dispersion/taxonomy.tsv\",\n  metadata = \"data/small/permanova-dispersion/metadata.tsv\",\n  source_summary = \"data/small/permanova-dispersion/source-summary.json\"\n)\nexpected_sha256 <- c(\n  otutab = \"de52dc7457f15f07776c216561803afd92782af7d6723ec93deb8dc0e932b900\",\n  taxonomy = \"599ed73e3d1f59bc2867782c58113100def184c3ebd2cab36286b2fc96dbaee0\",\n  metadata = \"5ebf2fd60582e1a0ef80fe20d251594bec3607df11d8bb74d0981236e03f982c\",\n  source_summary = \"0b7f7c5a6db0c3d9c09d9ae147ff926cb1ce8cbbed804290c074c088100e076d\"\n)\nobserved_sha256 <- vapply(\n  input_paths,\n  digest::digest,\n  character(1),\n  algo = \"sha256\",\n  serialize = FALSE,\n  file = TRUE\n)\nstopifnot(identical(observed_sha256, expected_sha256))\n\notutab_frame <- read_keyed_tsv(input_paths[[\"otutab\"]])\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\nsource_summary <- jsonlite::read_json(\n  input_paths[[\"source_summary\"]],\n  simplifyVector = TRUE\n)\n\notutab <- matrix(\n  suppressWarnings(as.numeric(as.matrix(otutab_frame))),\n  nrow = nrow(otutab_frame),\n  ncol = ncol(otutab_frame),\n  dimnames = dimnames(otutab_frame)\n)\nfeature_ids <- rownames(otutab)\nlibrary_ids <- colnames(otutab)\ntaxonomy <- taxonomy[feature_ids, , drop = FALSE]\nmetadata <- metadata[library_ids, , drop = FALSE]\n\nstopifnot(\n  nrow(otutab) == 16825L,\n  ncol(otutab) == 56L,\n  sum(otutab) == 98022,\n  setequal(feature_ids, rownames(taxonomy)),\n  setequal(library_ids, rownames(metadata)),\n  all(is.finite(otutab)),\n  all(otutab >= 0),\n  all(otutab == floor(otutab)),\n  identical(\n    source_summary$source_sha256,\n    \"47b25a0a033b794fca1db30ae6fdb68c55a44e6c4cd0d1be76788d1d77b51f36\"\n  )\n)\n\ndim(otutab)\nsum(otutab)\notutab[1:5, 1:5]\ntaxonomy[1:5, , drop = FALSE]\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16825    56\n[1] 98022\n           a_C026 a_C066 a_C070 a_C074 a_C075\nOTU_R0          0      0      0      0      1\nOTU_R1          3      0      7      3      2\nOTU_R10         0      0      0      0      0\nOTU_R100        0      1      2      1      0\nOTU_R10000      0      0      0      0      0\n           Kingdom Phylum Class Order Family Genus Species\nOTU_R0          NA     NA    NA    NA     NA    NA      NA\nOTU_R1          NA     NA    NA    NA     NA    NA      NA\nOTU_R10         NA     NA    NA    NA     NA    NA      NA\nOTU_R100        NA     NA    NA    NA     NA    NA      NA\nOTU_R10000      NA     NA    NA    NA     NA    NA      NA\n                                                              TaxonomyStatus\nOTU_R0     Not distributed with phyloseq::soilrep; not used in this analysis\nOTU_R1     Not distributed with phyloseq::soilrep; not used in this analysis\nOTU_R10    Not distributed with phyloseq::soilrep; not used in this analysis\nOTU_R100   Not distributed with phyloseq::soilrep; not used in this analysis\nOTU_R10000 Not distributed with phyloseq::soilrep; not used in this analysis\n       SourceTreatment SourceWarmed SourceClipped BiologicalSampleID   Block\na_C026              UC           no           yes                6CC Block 6\na_C066              UU           no            no                3UC Block 3\na_C070              WU          yes            no                5UW Block 5\na_C074              UU           no            no                2UC Block 2\na_C075              WC          yes           yes                5CW Block 5\na_C077              WU          yes            no                4UW Block 4\n                MainPlot Warming  Clipping           Treatment\na_C026 Block 6 / Ambient Ambient   Clipped   Ambient + Clipped\na_C066 Block 3 / Ambient Ambient Unclipped Ambient + Unclipped\na_C070  Block 5 / Warmed  Warmed Unclipped  Warmed + Unclipped\na_C074 Block 2 / Ambient Ambient Unclipped Ambient + Unclipped\na_C075  Block 5 / Warmed  Warmed   Clipped    Warmed + Clipped\na_C077  Block 4 / Warmed  Warmed Unclipped  Warmed + Unclipped\n       TechnicalLibraryIndex TechnicalLibraryCount\na_C026                     1                     2\na_C066                     1                     2\na_C070                     1                     2\na_C074                     1                     3\na_C075                     1                     3\na_C077                     1                     3\n```\n\n\n:::\n:::\n\n\n[下载完整 R 脚本](https://github.com/petemeng/microbiome-best-practices/blob/691722146e287afe063bd43e9ce4fa41977fe763/examples/23-permanova-dispersion.R)。脚本包含数据下载、计算和图形导出。\n\n<details class=\"wechat-omit\">\n<summary>首次使用时安装 R 包</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"BiocManager\", \"digest\", \"ggplot2\", \"jsonlite\", \"permute\",\n  \"ragg\", \"readr\", \"scales\", \"svglite\", \"systemfonts\", \"vegan\"\n))\nBiocManager::install(version = \"3.19\", ask = FALSE)\nBiocManager::install(\"phyloseq\", version = \"3.19\", ask = FALSE)\n```\n:::\n\n\n</details>\n\n## PERMANOVA 与 PERMDISP 回答不同问题 {#sec-theory}\n\n### 先区分组间中心差异与组内离散程度\n\nPERMANOVA 把距离矩阵中的平方和分解到模型项，比较组中心位置相关的 explained variation；常见输出是 pseudo-F、(R^2) 和 permutation P value。PERMDISP 则把每个样本到所属组 spatial median 或 centroid 的距离作为响应，检验各组 spread 是否不同。\n\n两者必须一起读：\n\n| PERMANOVA | PERMDISP | 可支持的表述 |\n|---|---|---|\n| 显著 | 不显著 | 与组中心位置差异一致，但仍需看设计、效应量和敏感性 |\n| 显著 | 显著 | location 与 dispersion 混在一起，不能只写“群落组成不同” |\n| 不显著 | 显著 | 没有中心差异证据，但 spread 不同本身可能有生物学意义 |\n| 不显著 | 不显著 | 当前精度下两类检验都未拒绝原假设，不等于各组完全相同 |\n\n[Warton et al. (2012)](https://doi.org/10.1111/j.2041-210X.2011.00127.x)系统说明了 distance-based multivariate tests 中 location 与 dispersion 的混淆风险。`betadisper(type = \"median\", bias.adjust = TRUE)`在本例中提供与主距离相配套的 spread 检验；二维 PCoA 只用于展示，推断仍使用完整距离空间。\n\n### 实验单位先于置换次数\n\n本数据有四层结构：\n\n```text\n6 Blocks\n└── 2 Main plots per block: Ambient / Warmed\n    └── 2 Subplots per main plot: Unclipped / Clipped\n        └── 1 biological soil sample\n            └── 1–3 PCR/tag technical libraries\n```\n\n因此每个区组有 8 种合法 treatment relabellings：whole-plot warming 可交换一次，两个 main plot 内的 clipping 可各交换一次，即 (2^3=8)。六个区组共有：\n\n\\[\n8^6=262{,}144\n\\]\n\n种合法 assignments（包含观察到的 identity）。主分析从其余 262,143 个 assignments 中以固定种子无放回抽取 9,999 个。置换 P 值按\n\n\\[\nP=\\frac{b+1}{m+1}\n\\]\n\n计算，因此 9,999 次置换的最小 P 为 0.0001。四个 planned simple effects 各有 6 对区组配对，穷举 63 个 non-identity swaps；连同观察顺序后，最小 P 为 (1/64=0.015625)。\n\n::: {.callout-warning title=\"只写 strata = Block 仍可能不够\"}\n`strata = Block`只能阻止样本跨区组交换，不能自动表达 whole plot 与 subplot 的不同交换规则。复杂 split-plot、crossover、family/cage 或纵向设计必须从随机化方案反推 exchangeability；若随机化记录不清楚，应先补设计合同，而不是增加置换次数。\n:::\n\n### total R²、partial R² 与 P 值不能互换\n\n本页同时报告两种比例：\n\n- **total (R^2)**：某项平方和占全部距离平方和的比例；\n- **partial (R^2)**：某项平方和占“该项 + residual”平方和的比例，即在先吸收 block 后的条件尺度。\n\nP 值还受到可交换单位数、置换空间和样本量影响。小 P 不代表效应大，大 (R^2) 也不保证估计精确。这里区组 total (R^2=0.469) 远大于 treatment total (R^2=0.098)，正说明设计结构不是可忽略的代码选项。\n\n<details>\n<summary><strong>深入：ANOSIM 和 MRPP 为什么只能做次要敏感性分析</strong></summary>\n\nANOSIM 比较 between-group 与 within-group 距离秩，统计量 (R>0) 才与“组内更近、组间更远”的常规分离方向一致。MRPP 的 chance-corrected agreement (A>0) 表示组内一致性高于随机期望。二者的统计量不等同于 PERMANOVA (R^2)，也不能替代 location/dispersion 分解。\n\n本例用同一受限置换矩阵得到 ANOSIM (R=-0.0948, P=0.0066) 和 MRPP (A=-0.0200, P=0.0122)。小 P 伴随负方向，表示观察到的组内相似性并没有沿常规“组内更近”的方向增强。把这两个 P 值列为“又有两种方法验证显著”会倒置统计量含义；本页只把它们保存为诊断性 sensitivity outputs。\n\n</details>\n\n## 同时检验群落中心与组内离散度 {#sec-code}\n\n### 把技术文库聚合回 24 个实验单位\n\n同一 `BiologicalSampleID` 下的技术文库共享同一处理标签，因而无法提供独立的 treatment replication。计数应先相加；对技术文库求平均 relative abundance 会让 1、2、3 个文库的土壤样本获得不同隐含权重。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreatment_levels <- c(\n  \"Ambient + Unclipped\", \"Ambient + Clipped\",\n  \"Warmed + Unclipped\", \"Warmed + Clipped\"\n)\nmetadata$Block <- factor(metadata$Block, levels = paste(\"Block\", 1:6))\nmetadata$Warming <- factor(metadata$Warming, levels = c(\"Ambient\", \"Warmed\"))\nmetadata$Clipping <- factor(metadata$Clipping, levels = c(\"Unclipped\", \"Clipped\"))\nmetadata$Treatment <- factor(metadata$Treatment, levels = treatment_levels)\n\nbiological_ids <- unique(as.character(metadata$BiologicalSampleID))\nbiological_meta <- do.call(rbind, lapply(biological_ids, function(id) {\n  rows <- metadata$BiologicalSampleID == id\n  fields <- c(\"Block\", \"MainPlot\", \"Warming\", \"Clipping\", \"Treatment\")\n  stopifnot(all(vapply(metadata[rows, fields, drop = FALSE], function(x) {\n    length(unique(as.character(x))) == 1L\n  }, logical(1))))\n  data.frame(\n    BiologicalSampleID = id,\n    Block = as.character(metadata$Block[rows][[1L]]),\n    MainPlot = as.character(metadata$MainPlot[rows][[1L]]),\n    Warming = as.character(metadata$Warming[rows][[1L]]),\n    Clipping = as.character(metadata$Clipping[rows][[1L]]),\n    Treatment = as.character(metadata$Treatment[rows][[1L]]),\n    TechnicalLibraries = sum(rows),\n    AggregateReads = sum(otutab[, rows, drop = FALSE]),\n    stringsAsFactors = FALSE\n  )\n}))\n\nbiological_meta$Block <- factor(\n  biological_meta$Block, levels = paste(\"Block\", 1:6)\n)\nbiological_meta$Warming <- factor(\n  biological_meta$Warming, levels = c(\"Ambient\", \"Warmed\")\n)\nbiological_meta$Clipping <- factor(\n  biological_meta$Clipping, levels = c(\"Unclipped\", \"Clipped\")\n)\nbiological_meta$Treatment <- factor(\n  biological_meta$Treatment, levels = treatment_levels\n)\nbiological_meta <- biological_meta[\n  order(biological_meta$Block, biological_meta$Warming, biological_meta$Clipping),\n  , drop = FALSE\n]\nrownames(biological_meta) <- biological_meta$BiologicalSampleID\nbiological_ids <- rownames(biological_meta)\n\naggregate_counts <- vapply(biological_ids, function(id) {\n  rowSums(otutab[, metadata$BiologicalSampleID == id, drop = FALSE])\n}, numeric(nrow(otutab)))\nrownames(aggregate_counts) <- feature_ids\ncolnames(aggregate_counts) <- biological_ids\n\nstopifnot(\n  ncol(aggregate_counts) == 24L,\n  sum(aggregate_counts) == sum(otutab),\n  all(with(biological_meta, table(Block, Warming, Clipping)) == 1L),\n  identical(as.integer(range(biological_meta$TechnicalLibraries)), c(1L, 3L))\n)\n\ndesign_audit <- data.frame(\n  BiologicalSampleID = biological_meta$BiologicalSampleID,\n  Block = as.character(biological_meta$Block),\n  MainPlot = biological_meta$MainPlot,\n  Warming = as.character(biological_meta$Warming),\n  Clipping = as.character(biological_meta$Clipping),\n  Treatment = as.character(biological_meta$Treatment),\n  TechnicalLibraries = biological_meta$TechnicalLibraries,\n  AggregateReads = biological_meta$AggregateReads,\n  stringsAsFactors = FALSE\n)\ndesign_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   BiologicalSampleID   Block          MainPlot Warming  Clipping\n1                 1UC Block 1 Block 1 / Ambient Ambient Unclipped\n2                 1CC Block 1 Block 1 / Ambient Ambient   Clipped\n3                 1UW Block 1  Block 1 / Warmed  Warmed Unclipped\n4                 1CW Block 1  Block 1 / Warmed  Warmed   Clipped\n5                 2UC Block 2 Block 2 / Ambient Ambient Unclipped\n6                 2CC Block 2 Block 2 / Ambient Ambient   Clipped\n7                 2UW Block 2  Block 2 / Warmed  Warmed Unclipped\n8                 2CW Block 2  Block 2 / Warmed  Warmed   Clipped\n9                 3UC Block 3 Block 3 / Ambient Ambient Unclipped\n10                3CC Block 3 Block 3 / Ambient Ambient   Clipped\n11                3UW Block 3  Block 3 / Warmed  Warmed Unclipped\n12                3CW Block 3  Block 3 / Warmed  Warmed   Clipped\n13                4UC Block 4 Block 4 / Ambient Ambient Unclipped\n14                4CC Block 4 Block 4 / Ambient Ambient   Clipped\n15                4UW Block 4  Block 4 / Warmed  Warmed Unclipped\n16                4CW Block 4  Block 4 / Warmed  Warmed   Clipped\n17                5UC Block 5 Block 5 / Ambient Ambient Unclipped\n18                5CC Block 5 Block 5 / Ambient Ambient   Clipped\n19                5UW Block 5  Block 5 / Warmed  Warmed Unclipped\n20                5CW Block 5  Block 5 / Warmed  Warmed   Clipped\n21                6UC Block 6 Block 6 / Ambient Ambient Unclipped\n22                6CC Block 6 Block 6 / Ambient Ambient   Clipped\n23                6UW Block 6  Block 6 / Warmed  Warmed Unclipped\n24                6CW Block 6  Block 6 / Warmed  Warmed   Clipped\n             Treatment TechnicalLibraries AggregateReads\n1  Ambient + Unclipped                  2           2270\n2    Ambient + Clipped                  3           5343\n3   Warmed + Unclipped                  1           2314\n4     Warmed + Clipped                  3           5729\n5  Ambient + Unclipped                  3           9863\n6    Ambient + Clipped                  2           2192\n7   Warmed + Unclipped                  3           3801\n8     Warmed + Clipped                  1           1564\n9  Ambient + Unclipped                  2           3154\n10   Ambient + Clipped                  3           8300\n11  Warmed + Unclipped                  2           3342\n12    Warmed + Clipped                  3           5280\n13 Ambient + Unclipped                  2           3061\n14   Ambient + Clipped                  2           2578\n15  Warmed + Unclipped                  3           5155\n16    Warmed + Clipped                  2           2817\n17 Ambient + Unclipped                  2           2971\n18   Ambient + Clipped                  2           2881\n19  Warmed + Unclipped                  2           3877\n20    Warmed + Clipped                  3           5746\n21 Ambient + Unclipped                  3           5188\n22   Ambient + Clipped                  2           2613\n23  Warmed + Unclipped                  3           6138\n24    Warmed + Clipped                  2           1845\n```\n\n\n:::\n:::\n\n\n### 预先固定 feature filter 和主距离\n\n主 filter 在**技术文库层**复现原研究规则；推断距离在**聚合后的生物学样本层**计算。两层不能交换顺序。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npresence_by_treatment <- vapply(treatment_levels, function(group) {\n  rowSums(otutab[, metadata$Treatment == group, drop = FALSE] > 0)\n}, numeric(nrow(otutab)))\ncolnames(presence_by_treatment) <- treatment_levels\nprimary_keep <- apply(presence_by_treatment >= 4L, 1L, any)\n\nprimary_counts <- aggregate_counts[primary_keep, , drop = FALSE]\nprimary_community <- t(primary_counts)\nprimary_relative <- sweep(\n  primary_community, 1L, rowSums(primary_community), \"/\"\n)\nprimary_distance <- vegan::vegdist(primary_relative, method = \"bray\")\ndistance_matrix <- as.matrix(primary_distance)\n\nstopifnot(\n  sum(primary_keep) == 1824L,\n  max(abs(rowSums(primary_relative) - 1)) < 1e-12,\n  max(abs(distance_matrix - t(distance_matrix))) < 1e-12,\n  max(abs(diag(distance_matrix))) < 1e-12,\n  identical(rownames(distance_matrix), biological_ids)\n)\n\ndata.frame(\n  Branch = c(\n    \"Primary: detected in >=4 tagged libraries in any treatment\",\n    \"Sensitivity: no prevalence filter\"\n  ),\n  InputFeatures = nrow(otutab),\n  RetainedFeatures = c(sum(primary_keep), nrow(otutab)),\n  UsedForPrimaryInference = c(TRUE, FALSE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                      Branch InputFeatures\n1 Primary: detected in >=4 tagged libraries in any treatment         16825\n2                          Sensitivity: no prevalence filter         16825\n  RetainedFeatures UsedForPrimaryInference\n1             1824                    TRUE\n2            16825                   FALSE\n```\n\n\n:::\n:::\n\n\n### 明确生成合法 split-plot 置换矩阵\n\n`make_splitplot_permutations()`为每个区组编码三个二元交换：whole plot 一次、两个 main plot 内各一次。`permute::how()`在这里作为独立的置换空间计数审计；真正传给 `adonis2()` 和 `permutest()`的是显式矩阵。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_splitplot_permutations <- function(meta, nset, seed) {\n  block_levels <- levels(meta$Block)\n  total_possible <- 8^length(block_levels)\n  stopifnot(nset <= total_possible - 1L)\n  set.seed(seed)\n  codes <- sample.int(total_possible - 1L, nset, replace = FALSE)\n  permutations <- matrix(\n    rep(seq_len(nrow(meta)), each = nset),\n    nrow = nset,\n    byrow = FALSE\n  )\n\n  for (row_i in seq_len(nset)) {\n    code <- codes[[row_i]]\n    for (block_i in seq_along(block_levels)) {\n      state <- code %% 8L\n      code <- code %/% 8L\n      destination <- which(meta$Block == block_levels[[block_i]])\n      ambient <- destination[meta$Warming[destination] == \"Ambient\"]\n      warmed <- destination[meta$Warming[destination] == \"Warmed\"]\n      ambient <- ambient[order(meta$Clipping[ambient])]\n      warmed <- warmed[order(meta$Clipping[warmed])]\n      if (bitwAnd(state, 2L) != 0L) ambient <- rev(ambient)\n      if (bitwAnd(state, 4L) != 0L) warmed <- rev(warmed)\n      source <- if (bitwAnd(state, 1L) != 0L) {\n        c(warmed, ambient)\n      } else {\n        c(ambient, warmed)\n      }\n      permutations[row_i, destination] <- source\n    }\n  }\n  list(matrix = permutations, codes = codes, possible = total_possible)\n}\n\nis_legal_splitplot <- function(permutation, meta) {\n  for (block_level in levels(meta$Block)) {\n    destination <- which(meta$Block == block_level)\n    source <- permutation[destination]\n    if (!all(meta$Block[source] == block_level)) return(FALSE)\n\n    destination_ambient <- destination[meta$Warming[destination] == \"Ambient\"]\n    destination_warmed <- destination[meta$Warming[destination] == \"Warmed\"]\n    source_plot_a <- unique(as.character(\n      meta$MainPlot[permutation[destination_ambient]]\n    ))\n    source_plot_w <- unique(as.character(\n      meta$MainPlot[permutation[destination_warmed]]\n    ))\n    if (length(source_plot_a) != 1L || length(source_plot_w) != 1L) {\n      return(FALSE)\n    }\n    if (identical(source_plot_a, source_plot_w)) return(FALSE)\n    if (!setequal(\n      meta$Clipping[permutation[destination_ambient]],\n      levels(meta$Clipping)\n    )) return(FALSE)\n    if (!setequal(\n      meta$Clipping[permutation[destination_warmed]],\n      levels(meta$Clipping)\n    )) return(FALSE)\n  }\n  TRUE\n}\n\nprimary_seed <- 20260723L\nprimary_nperm <- 9999L\nsplitplot <- make_splitplot_permutations(\n  biological_meta, primary_nperm, primary_seed\n)\npermutation_matrix <- splitplot$matrix\n\ncontrol_design <- permute::how(\n  blocks = biological_meta$Block,\n  plots = permute::Plots(\n    strata = factor(biological_meta$MainPlot),\n    type = \"free\"\n  ),\n  within = permute::Within(type = \"free\"),\n  nperm = primary_nperm\n)\npossible_from_permute <- permute::numPerms(\n  nrow(biological_meta), control = control_design\n)\nidentity_rows <- sum(apply(permutation_matrix, 1L, function(x) {\n  identical(as.integer(x), seq_len(nrow(biological_meta)))\n}))\nlegal_rows <- vapply(seq_len(nrow(permutation_matrix)), function(i) {\n  is_legal_splitplot(permutation_matrix[i, ], biological_meta)\n}, logical(1))\n\npermutation_contract <- data.frame(\n  Seed = primary_seed,\n  PossibleIncludingIdentity = splitplot$possible,\n  PossibleFromPermute = possible_from_permute,\n  PermutationsUsed = nrow(permutation_matrix),\n  UniqueRows = nrow(unique(permutation_matrix)),\n  IdentityRows = identity_rows,\n  LegalRows = sum(legal_rows),\n  MinimumP = 1 / (primary_nperm + 1),\n  MatrixSHA256 = digest(\n    permutation_matrix, algo = \"sha256\", serialize = TRUE\n  )\n)\nstopifnot(\n  splitplot$possible == 262144,\n  possible_from_permute == 262144,\n  nrow(unique(permutation_matrix)) == 9999L,\n  identity_rows == 0L,\n  all(legal_rows)\n)\npermutation_contract\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Seed PossibleIncludingIdentity PossibleFromPermute PermutationsUsed\n1 20260723                    262144              262144             9999\n  UniqueRows IdentityRows LegalRows MinimumP\n1       9999            0      9999    1e-04\n                                                      MatrixSHA256\n1 3b135bcf5075a2dc0c8bb0d331683be1bd5d98d53811f2d42fd65eda1cabf427\n```\n\n\n:::\n:::\n\n\n### 分别进行整体分组检验与多因素 PERMANOVA\n\n`Block`先进入模型以吸收区组差异；四水平 `Treatment` 是预先指定的 primary omnibus。factorial decomposition 用于描述 Warming、Clipping 与 interaction，并把三个 P 值作为一个 Holm family。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(primary_seed)\nomnibus_fit <- vegan::adonis2(\n  primary_distance ~ Block + Treatment,\n  data = biological_meta,\n  permutations = permutation_matrix,\n  by = \"terms\",\n  parallel = 1\n)\nomnibus_ss <- omnibus_fit[\"Treatment\", \"SumOfSqs\"]\nomnibus_residual_ss <- omnibus_fit[\"Residual\", \"SumOfSqs\"]\npermanova_omnibus <- data.frame(\n  Term = \"Treatment (4 levels)\",\n  Df = omnibus_fit[\"Treatment\", \"Df\"],\n  SumOfSquares = omnibus_ss,\n  ConditioningBlockR2 = omnibus_fit[\"Block\", \"R2\"],\n  R2Total = omnibus_fit[\"Treatment\", \"R2\"],\n  R2Partial = omnibus_ss / (omnibus_ss + omnibus_residual_ss),\n  PseudoF = omnibus_fit[\"Treatment\", \"F\"],\n  PValue = omnibus_fit[\"Treatment\", \"Pr(>F)\"],\n  Permutations = primary_nperm,\n  MinimumP = 1 / (primary_nperm + 1)\n)\n\nset.seed(primary_seed)\nfactorial_fit <- vegan::adonis2(\n  primary_distance ~ Block + Warming * Clipping,\n  data = biological_meta,\n  permutations = permutation_matrix,\n  by = \"terms\",\n  parallel = 1\n)\nfactorial_terms <- c(\"Warming\", \"Clipping\", \"Warming:Clipping\")\nfactorial_residual_ss <- factorial_fit[\"Residual\", \"SumOfSqs\"]\npermanova_factorial <- data.frame(\n  Term = factorial_terms,\n  Df = factorial_fit[factorial_terms, \"Df\"],\n  SumOfSquares = factorial_fit[factorial_terms, \"SumOfSqs\"],\n  R2Total = factorial_fit[factorial_terms, \"R2\"],\n  R2Partial = factorial_fit[factorial_terms, \"SumOfSqs\"] /\n    (factorial_fit[factorial_terms, \"SumOfSqs\"] + factorial_residual_ss),\n  PseudoF = factorial_fit[factorial_terms, \"F\"],\n  PValue = factorial_fit[factorial_terms, \"Pr(>F)\"],\n  Permutations = primary_nperm\n)\npermanova_factorial$PAdjustedHolm <- p.adjust(\n  permanova_factorial$PValue, method = \"holm\"\n)\npermanova_factorial$RejectHolm05 <-\n  permanova_factorial$PAdjustedHolm < 0.05\n\npermanova_omnibus\npermanova_factorial\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Term Df SumOfSquares ConditioningBlockR2    R2Total R2Partial\n1 Treatment (4 levels)  3    0.5176345           0.4689156 0.09808712 0.1846922\n   PseudoF PValue Permutations MinimumP\n1 1.132653 0.0065         9999    1e-04\n              Term Df SumOfSquares    R2Total  R2Partial  PseudoF PValue\n1          Warming  1    0.1798562 0.03408114 0.07296664 1.180648 0.1320\n2         Clipping  1    0.1677139 0.03178029 0.06837743 1.100941 0.0489\n3 Warming:Clipping  1    0.1700644 0.03222569 0.06926934 1.116370 0.0400\n  Permutations PAdjustedHolm RejectHolm05\n1         9999         0.132        FALSE\n2         9999         0.120        FALSE\n3         9999         0.120        FALSE\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"by = terms 的解释边界\"}\n`adonis2(..., by = \"terms\")`给出 sequential sums of squares。当前 2 × 2 balanced design 的 Warming、Clipping 与 interaction 平方和经换序核对一致；不平衡 observational metadata 中，项顺序可能改变结果，应预先确定模型、检查 marginal tests，并报告共线性和不可辨识项。\n:::\n\n### 四个计划 simple effects：穷举区组内配对交换\n\n每个 simple effect 都比较 12 个生物学样本、6 个 blocks。63 个 non-identity paired swaps 全部进入检验，四个 P 值再作为一个 Holm family。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_paired_permutations <- function(meta) {\n  block_levels <- levels(meta$Block)\n  permutations <- matrix(\n    rep(seq_len(nrow(meta)), each = 2^length(block_levels) - 1L),\n    nrow = 2^length(block_levels) - 1L,\n    byrow = FALSE\n  )\n  for (code in seq_len(2^length(block_levels) - 1L)) {\n    for (block_i in seq_along(block_levels)) {\n      if (bitwAnd(code, bitwShiftL(1L, block_i - 1L)) != 0L) {\n        destination <- which(meta$Block == block_levels[[block_i]])\n        permutations[code, destination] <- rev(destination)\n      }\n    }\n  }\n  permutations\n}\n\nplanned_contrasts <- list(\n  list(\n    label = \"Warming | Unclipped\",\n    group_a = \"Ambient + Unclipped\",\n    group_b = \"Warmed + Unclipped\"\n  ),\n  list(\n    label = \"Warming | Clipped\",\n    group_a = \"Ambient + Clipped\",\n    group_b = \"Warmed + Clipped\"\n  ),\n  list(\n    label = \"Clipping | Ambient\",\n    group_a = \"Ambient + Unclipped\",\n    group_b = \"Ambient + Clipped\"\n  ),\n  list(\n    label = \"Clipping | Warmed\",\n    group_a = \"Warmed + Unclipped\",\n    group_b = \"Warmed + Clipped\"\n  )\n)\n\npairwise_rows <- vector(\"list\", length(planned_contrasts))\nfor (contrast_i in seq_along(planned_contrasts)) {\n  contrast <- planned_contrasts[[contrast_i]]\n  keep_samples <- biological_meta$Treatment %in%\n    c(contrast$group_a, contrast$group_b)\n  pair_meta <- biological_meta[keep_samples, , drop = FALSE]\n  pair_meta$ContrastGroup <- factor(\n    as.character(pair_meta$Treatment),\n    levels = c(contrast$group_a, contrast$group_b)\n  )\n  pair_meta <- pair_meta[\n    order(pair_meta$Block, pair_meta$ContrastGroup),\n    , drop = FALSE\n  ]\n  pair_distance <- as.dist(\n    distance_matrix[rownames(pair_meta), rownames(pair_meta), drop = FALSE]\n  )\n  pair_permutations <- make_paired_permutations(pair_meta)\n  set.seed(primary_seed + contrast_i)\n  pair_fit <- vegan::adonis2(\n    pair_distance ~ Block + ContrastGroup,\n    data = pair_meta,\n    permutations = pair_permutations,\n    by = \"terms\",\n    parallel = 1\n  )\n  pair_ss <- pair_fit[\"ContrastGroup\", \"SumOfSqs\"]\n  pair_residual_ss <- pair_fit[\"Residual\", \"SumOfSqs\"]\n  pairwise_rows[[contrast_i]] <- data.frame(\n    Contrast = contrast$label,\n    GroupA = contrast$group_a,\n    GroupB = contrast$group_b,\n    Samples = nrow(pair_meta),\n    Blocks = nlevels(droplevels(pair_meta$Block)),\n    R2Total = pair_fit[\"ContrastGroup\", \"R2\"],\n    R2Partial = pair_ss / (pair_ss + pair_residual_ss),\n    PseudoF = pair_fit[\"ContrastGroup\", \"F\"],\n    PValue = pair_fit[\"ContrastGroup\", \"Pr(>F)\"],\n    Permutations = nrow(pair_permutations),\n    MinimumP = 1 / (nrow(pair_permutations) + 1)\n  )\n}\npairwise_permanova <- do.call(rbind, pairwise_rows)\npairwise_permanova$PAdjustedHolm <- p.adjust(\n  pairwise_permanova$PValue, method = \"holm\"\n)\npairwise_permanova$RejectHolm05 <-\n  pairwise_permanova$PAdjustedHolm < 0.05\npairwise_permanova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Contrast              GroupA             GroupB Samples Blocks\n1 Warming | Unclipped Ambient + Unclipped Warmed + Unclipped      12      6\n2   Warming | Clipped   Ambient + Clipped   Warmed + Clipped      12      6\n3  Clipping | Ambient Ambient + Unclipped  Ambient + Clipped      12      6\n4   Clipping | Warmed  Warmed + Unclipped   Warmed + Clipped      12      6\n     R2Total R2Partial  PseudoF  PValue Permutations MinimumP PAdjustedHolm\n1 0.06856475 0.1853007 1.137234 0.03125           63 0.015625         0.125\n2 0.06840673 0.1850233 1.135145 0.03125           63 0.015625         0.125\n3 0.06236555 0.1866763 1.147614 0.06250           63 0.015625         0.125\n4 0.07027971 0.1937671 1.201682 0.03125           63 0.015625         0.125\n  RejectHolm05\n1        FALSE\n2        FALSE\n3        FALSE\n4        FALSE\n```\n\n\n:::\n:::\n\n\n### 必配 PERMDISP，并保留 ANOSIM/MRPP 的方向\n\nPERMDISP 使用与 primary PERMANOVA 完全相同的 Bray–Curtis 和 9,999 行合法置换矩阵。`type = \"median\"`降低 centroid 对极端点的敏感性；`bias.adjust = TRUE`修正小组样本量下到中心距离的向下偏差。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion_model <- vegan::betadisper(\n  primary_distance,\n  group = biological_meta$Treatment,\n  type = \"median\",\n  bias.adjust = TRUE\n)\nset.seed(primary_seed)\ndispersion_test <- vegan::permutest(\n  dispersion_model,\n  permutations = permutation_matrix,\n  pairwise = FALSE,\n  parallel = 1\n)\ndispersion_global <- data.frame(\n  Grouping = \"Treatment (4 levels)\",\n  Center = \"Spatial median\",\n  BiasAdjustment = TRUE,\n  FValue = dispersion_test$tab[\"Groups\", \"F\"],\n  PValue = dispersion_test$tab[\"Groups\", \"Pr(>F)\"],\n  Permutations = dispersion_test$tab[\"Groups\", \"N.Perm\"],\n  MinimumP = 1 / (primary_nperm + 1)\n)\n\ndispersion_distances <- data.frame(\n  BiologicalSampleID = names(dispersion_model$distances),\n  Treatment = as.character(biological_meta[\n    names(dispersion_model$distances), \"Treatment\"\n  ]),\n  DistanceToSpatialMedian = as.numeric(dispersion_model$distances)\n)\n\nset.seed(primary_seed)\nanosim_fit <- vegan::anosim(\n  primary_distance,\n  grouping = biological_meta$Treatment,\n  permutations = permutation_matrix,\n  parallel = 1\n)\nset.seed(primary_seed)\nmrpp_fit <- vegan::mrpp(\n  primary_distance,\n  grouping = biological_meta$Treatment,\n  permutations = permutation_matrix,\n  weight.type = 1,\n  parallel = 1\n)\nalternative_tests <- data.frame(\n  Method = c(\"PERMANOVA\", \"ANOSIM\", \"MRPP\"),\n  Statistic = c(\"Pseudo-F\", \"R\", \"A\"),\n  StatisticValue = c(\n    permanova_omnibus$PseudoF,\n    unname(anosim_fit$statistic),\n    unname(mrpp_fit$A)\n  ),\n  PValue = c(\n    permanova_omnibus$PValue,\n    anosim_fit$signif,\n    mrpp_fit$Pvalue\n  ),\n  Role = c(\"Primary\", \"Directional sensitivity\", \"Directional sensitivity\")\n)\n\ndispersion_global\nalternative_tests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Grouping         Center BiasAdjustment    FValue PValue\n1 Treatment (4 levels) Spatial median           TRUE 0.4027608 0.3714\n  Permutations MinimumP\n1         9999    1e-04\n     Method Statistic StatisticValue PValue                    Role\n1 PERMANOVA  Pseudo-F     1.13265290 0.0065                 Primary\n2    ANOSIM         R    -0.09475309 0.0066 Directional sensitivity\n3      MRPP         A    -0.02004802 0.0122 Directional sensitivity\n```\n\n\n:::\n:::\n\n\n### 做两条有效和两条故意无效的敏感性分支\n\n第一条敏感性分支只改变 feature filter，仍可用于评估结论稳健性。后两条故意打破 exchangeability 或实验单位，用于量化“错误分析会把结果改成什么”，但不能作为平行证据。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_free_permutations <- function(n, nset, seed) {\n  set.seed(seed)\n  out <- t(replicate(nset, sample.int(n), simplify = \"matrix\"))\n  stopifnot(nrow(unique(out)) == nset)\n  out\n}\n\nrun_omnibus <- function(distance, meta, permutations, include_block = TRUE) {\n  if (include_block) {\n    fit <- vegan::adonis2(\n      distance ~ Block + Treatment,\n      data = meta, permutations = permutations,\n      by = \"terms\", parallel = 1\n    )\n  } else {\n    fit <- vegan::adonis2(\n      distance ~ Treatment,\n      data = meta, permutations = permutations,\n      by = \"terms\", parallel = 1\n    )\n  }\n  ss <- fit[\"Treatment\", \"SumOfSqs\"]\n  residual_ss <- fit[\"Residual\", \"SumOfSqs\"]\n  c(\n    R2Total = fit[\"Treatment\", \"R2\"],\n    R2Partial = ss / (ss + residual_ss),\n    PseudoF = fit[\"Treatment\", \"F\"],\n    PValue = fit[\"Treatment\", \"Pr(>F)\"]\n  )\n}\n\nunfiltered_relative <- sweep(\n  t(aggregate_counts), 1L, rowSums(t(aggregate_counts)), \"/\"\n)\nunfiltered_distance <- vegan::vegdist(\n  unfiltered_relative, method = \"bray\"\n)\nunfiltered_result <- run_omnibus(\n  unfiltered_distance, biological_meta, permutation_matrix, TRUE\n)\n\nfree_biological_permutations <- make_free_permutations(\n  nrow(biological_meta), primary_nperm, primary_seed + 1L\n)\nfree_biological_result <- run_omnibus(\n  primary_distance, biological_meta, free_biological_permutations, TRUE\n)\n\nlibrary_relative <- sweep(\n  t(otutab[primary_keep, , drop = FALSE]),\n  1L,\n  colSums(otutab[primary_keep, , drop = FALSE]),\n  \"/\"\n)\nlibrary_distance <- vegan::vegdist(library_relative, method = \"bray\")\nfree_library_permutations <- make_free_permutations(\n  nrow(metadata), primary_nperm, primary_seed + 2L\n)\ntechnical_result <- run_omnibus(\n  library_distance, metadata, free_library_permutations, FALSE\n)\n\nsensitivity_analysis <- data.frame(\n  Branch = c(\n    \"Paper filter + split-plot restriction\",\n    \"No prevalence filter + split-plot restriction\",\n    \"Paper filter + unrestricted biological units\",\n    \"Paper filter + unrestricted technical libraries\"\n  ),\n  Features = c(sum(primary_keep), nrow(otutab), sum(primary_keep), sum(primary_keep)),\n  Units = c(24L, 24L, 24L, 56L),\n  ValidForPrimaryInference = c(TRUE, TRUE, FALSE, FALSE),\n  R2Total = c(\n    permanova_omnibus$R2Total,\n    unfiltered_result[[\"R2Total\"]],\n    free_biological_result[[\"R2Total\"]],\n    technical_result[[\"R2Total\"]]\n  ),\n  R2Partial = c(\n    permanova_omnibus$R2Partial,\n    unfiltered_result[[\"R2Partial\"]],\n    free_biological_result[[\"R2Partial\"]],\n    technical_result[[\"R2Partial\"]]\n  ),\n  PseudoF = c(\n    permanova_omnibus$PseudoF,\n    unfiltered_result[[\"PseudoF\"]],\n    free_biological_result[[\"PseudoF\"]],\n    technical_result[[\"PseudoF\"]]\n  ),\n  PValue = c(\n    permanova_omnibus$PValue,\n    unfiltered_result[[\"PValue\"]],\n    free_biological_result[[\"PValue\"]],\n    technical_result[[\"PValue\"]]\n  )\n)\nsensitivity_analysis\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                           Branch Features Units\n1           Paper filter + split-plot restriction     1824    24\n2   No prevalence filter + split-plot restriction    16825    24\n3    Paper filter + unrestricted biological units     1824    24\n4 Paper filter + unrestricted technical libraries     1824    56\n  ValidForPrimaryInference    R2Total  R2Partial   PseudoF PValue\n1                     TRUE 0.09808712 0.18469216 1.1326529 0.0065\n2                     TRUE 0.10283030 0.16355756 0.9776977 0.7642\n3                    FALSE 0.09808712 0.18469216 1.1326529 0.2441\n4                    FALSE 0.05872515 0.05872515 1.0814085 0.2480\n```\n\n\n:::\n:::\n\n\n主 filter 与不做 prevalence filter 的 total (R^2) 接近，但受限置换 P 值从 0.0065 变为 0.7642。说明“排序图大致相似”不能替代推断稳健性；feature space 改变了在合法随机化分布中的相对位置。\n\n## 把设计、效应量和离散度放在一起解释 {#sec-publication}\n\n### 先把随机化单位画清楚\n\n每个格子是一个生物学土壤样本；格内数字显示它由多少 technical libraries 聚合而来。图内只使用英文，处理以颜色和文字同时编码。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreatment_palette <- c(\n  \"Ambient + Unclipped\" = pal_pub[[\"blue\"]],\n  \"Ambient + Clipped\" = pal_pub[[\"sky\"]],\n  \"Warmed + Unclipped\" = pal_pub[[\"vermillion\"]],\n  \"Warmed + Clipped\" = pal_pub[[\"orange\"]]\n)\nwarming_palette <- c(\n  \"Ambient\" = pal_pub[[\"blue\"]],\n  \"Warmed\" = pal_pub[[\"vermillion\"]]\n)\nclipping_shapes <- c(\"Unclipped\" = 21, \"Clipped\" = 24)\n\ndesign_plot_data <- design_audit\ndesign_plot_data$Block <- factor(\n  design_plot_data$Block, levels = rev(paste(\"Block\", 1:6))\n)\ndesign_plot_data$Treatment <- factor(\n  design_plot_data$Treatment, levels = treatment_levels\n)\ndesign_plot_data$Warming <- factor(\n  design_plot_data$Warming, levels = c(\"Ambient\", \"Warmed\")\n)\ndesign_plot_data$CellLabel <- paste0(\n  design_plot_data$TechnicalLibraries,\n  ifelse(design_plot_data$TechnicalLibraries == 1L, \" library\", \" libraries\"),\n  \"\\n1 analysis unit\"\n)\n\ndesign_plot <- ggplot(\n  design_plot_data, aes(Treatment, Block, fill = Warming)\n) +\n  geom_tile(\n    colour = \"white\", linewidth = 1.1, width = 0.96, height = 0.92\n  ) +\n  geom_text(\n    aes(label = CellLabel), colour = \"white\", size = 2.65,\n    lineheight = 0.9, family = font_pub\n  ) +\n  scale_fill_manual(values = warming_palette, drop = FALSE) +\n  scale_x_discrete(labels = c(\n    \"Ambient + Unclipped\" = \"Ambient\\nUnclipped\",\n    \"Ambient + Clipped\" = \"Ambient\\nClipped\",\n    \"Warmed + Unclipped\" = \"Warmed\\nUnclipped\",\n    \"Warmed + Clipped\" = \"Warmed\\nClipped\"\n  )) +\n  labs(\n    title = \"Technical libraries collapse to 24 biological units\",\n    subtitle = paste(\n      \"One row is one block; whole plots may swap within blocks,\",\n      \"and clipping may swap only within each main plot\"\n    ),\n    x = \"Field treatment\", y = NULL, fill = \"Whole-plot factor\",\n    caption = paste(\n      \"Labels show 1–3 PCR/tag libraries aggregated before inference.\",\n      \"The resulting split-plot space contains 8^6 = 262,144 assignments.\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text.x = element_text(size = 8.3, lineheight = 0.9),\n    axis.text.y = element_text(size = 8.3),\n    legend.position = \"top\"\n  )\n\nsave_pub(\n  design_plot, \"figures/23-exchangeability-design\",\n  width = 183, height = 104\n)\ndesign_plot\n```\n\n::: {.cell-output-display}\n![Split-plot 设计与实验单位。每格进入推断一次，技术文库先相加。](23-permanova-dispersion_files/figure-html/fig-design-1.png){#fig-design}\n:::\n:::\n\n\n### 同时展示群落中心差异与组内离散程度\n\n彩色叉号是四组 spatial medians，线段是每个样本到所属 median 的二维投影。PERMDISP 实际使用完整坐标空间的距离，不能从二维线段长度重算。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsite_vectors <- as.data.frame(\n  dispersion_model$vectors[, seq_len(2L), drop = FALSE]\n)\ncolnames(site_vectors) <- c(\"PCoA1\", \"PCoA2\")\nsite_vectors$BiologicalSampleID <- rownames(site_vectors)\nsite_vectors$Treatment <- as.character(biological_meta[\n  site_vectors$BiologicalSampleID, \"Treatment\"\n])\nsite_vectors$Clipping <- as.character(biological_meta[\n  site_vectors$BiologicalSampleID, \"Clipping\"\n])\n\ncenter_vectors <- as.data.frame(\n  dispersion_model$centroids[, seq_len(2L), drop = FALSE]\n)\ncolnames(center_vectors) <- c(\"Center1\", \"Center2\")\ncenter_vectors$Treatment <- rownames(center_vectors)\nsite_vectors$Center1 <- center_vectors$Center1[\n  match(site_vectors$Treatment, center_vectors$Treatment)\n]\nsite_vectors$Center2 <- center_vectors$Center2[\n  match(site_vectors$Treatment, center_vectors$Treatment)\n]\npositive_eigenvalues <- dispersion_model$eig[dispersion_model$eig > 0]\naxis_percent <- 100 * dispersion_model$eig[seq_len(2L)] /\n  sum(positive_eigenvalues)\n\npcoa_plot <- ggplot(site_vectors, aes(PCoA1, PCoA2)) +\n  geom_segment(\n    aes(xend = Center1, yend = Center2, colour = Treatment),\n    linewidth = 0.42, alpha = 0.55, show.legend = FALSE\n  ) +\n  geom_point(\n    aes(fill = Treatment, shape = Clipping),\n    colour = \"#1A1A1A\", size = 3.0, stroke = 0.55\n  ) +\n  geom_point(\n    data = center_vectors,\n    aes(Center1, Center2, colour = Treatment),\n    inherit.aes = FALSE, shape = 4, size = 4.2, stroke = 1.2,\n    show.legend = FALSE\n  ) +\n  scale_fill_manual(values = treatment_palette, drop = FALSE) +\n  scale_colour_manual(values = treatment_palette, drop = FALSE) +\n  scale_shape_manual(values = clipping_shapes, drop = FALSE) +\n  labs(\n    title = \"Location and spread must be read together\",\n    subtitle = sprintf(\n      \"Blocked PERMANOVA: R² = %.3f, P = %s; PERMDISP: P = %s\",\n      permanova_omnibus$R2Total,\n      format_p(permanova_omnibus$PValue),\n      format_p(dispersion_global$PValue)\n    ),\n    x = sprintf(\"PCoA 1 (%.1f%%)\", axis_percent[[1L]]),\n    y = sprintf(\"PCoA 2 (%.1f%%)\", axis_percent[[2L]]),\n    fill = \"Treatment\", shape = \"Clipping\",\n    caption = paste(\n      \"Crosses are treatment spatial medians; segments show the two-dimensional projection.\",\n      \"PERMDISP uses full-space distances to spatial medians.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  theme(legend.position = \"top\", legend.box = \"vertical\") +\n  guides(\n    fill = guide_legend(\n      nrow = 2, byrow = TRUE,\n      override.aes = list(shape = 21, size = 3.0, colour = \"#1A1A1A\")\n    ),\n    shape = guide_legend(nrow = 1)\n  )\n\nsave_pub(\n  pcoa_plot, \"figures/23-pcoa-centroid-dispersion\",\n  width = 183, height = 120\n)\npcoa_plot\n```\n\n::: {.cell-output-display}\n![Bray–Curtis PCoA、四组 spatial medians 与 PERMANOVA/PERMDISP 联合读图。](23-permanova-dispersion_files/figure-html/fig-pcoa-dispersion-1.png){#fig-pcoa-dispersion}\n:::\n:::\n\n\n### 计划比较用效应量和校正后 P 值，不用星号墙\n\n四个 partial (R^2) 约为 0.185–0.194，但离散的 exact permutation grid 和完整 Holm family 使校正后 P 均为 0.125。图同时显示 effect magnitude 与 multiplicity decision。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise_plot_data <- pairwise_permanova\npairwise_plot_data$Contrast <- factor(\n  pairwise_plot_data$Contrast,\n  levels = rev(vapply(planned_contrasts, `[[`, character(1), \"label\"))\n)\npairwise_plot_data$Decision <- ifelse(\n  pairwise_plot_data$RejectHolm05,\n  \"Holm-adjusted P < 0.05\",\n  \"Holm-adjusted P >= 0.05\"\n)\npairwise_plot_data$Label <- sprintf(\n  \"Partial R² = %.3f  |  Holm P %s\",\n  pairwise_plot_data$R2Partial,\n  format_p(pairwise_plot_data$PAdjustedHolm)\n)\npairwise_decision_palette <- c(\n  \"Holm-adjusted P < 0.05\" = pal_pub[[\"vermillion\"]],\n  \"Holm-adjusted P >= 0.05\" = pal_pub[[\"grey\"]]\n)\n\npairwise_plot <- ggplot(\n  pairwise_plot_data, aes(R2Partial, Contrast, colour = Decision)\n) +\n  geom_segment(\n    aes(x = 0, xend = R2Partial, yend = Contrast),\n    linewidth = 0.7, show.legend = FALSE\n  ) +\n  geom_point(size = 3.2) +\n  geom_text(\n    aes(label = Label), hjust = -0.08, colour = \"#333333\",\n    size = 2.65, family = font_pub\n  ) +\n  scale_colour_manual(values = pairwise_decision_palette) +\n  scale_x_continuous(\n    limits = c(0, max(pairwise_plot_data$R2Partial) * 1.75),\n    labels = scales::label_percent(accuracy = 1)\n  ) +\n  labs(\n    title = \"Planned simple effects use exact paired permutations\",\n    subtitle = \"Each contrast enumerates 63 non-identity swaps across six blocks\",\n    x = \"Partial variance explained\", y = NULL,\n    colour = \"Multiplicity decision\",\n    caption = paste(\n      \"The four prespecified P values form one Holm family.\",\n      \"With 64 assignments including the observed order, the minimum P is 0.015625.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  theme(panel.grid.major.y = element_blank(), legend.position = \"top\")\n\nsave_pub(\n  pairwise_plot, \"figures/23-pairwise-permanova\",\n  width = 183, height = 96\n)\npairwise_plot\n```\n\n::: {.cell-output-display}\n![四个预先指定 simple effects 的 partial R² 与 Holm-adjusted P。](23-permanova-dispersion_files/figure-html/fig-pairwise-1.png){#fig-pairwise}\n:::\n:::\n\n\n### 单独展示每个样本到 spatial median 的距离\n\n箱体用于概括分布，全部 24 个点仍保留；黑色叉号表示组均值。未显著的 PERMDISP 不应改写为“方差齐性已被证明”。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion_plot_data <- dispersion_distances\ndispersion_plot_data$Treatment <- factor(\n  dispersion_plot_data$Treatment, levels = treatment_levels\n)\n\ndispersion_plot <- ggplot(\n  dispersion_plot_data,\n  aes(Treatment, DistanceToSpatialMedian, fill = Treatment)\n) +\n  geom_boxplot(\n    width = 0.58, outlier.shape = NA, alpha = 0.35,\n    colour = \"#333333\", linewidth = 0.45\n  ) +\n  geom_point(\n    shape = 21, colour = \"#1A1A1A\", size = 2.4, stroke = 0.45,\n    position = position_jitter(width = 0.09, height = 0, seed = primary_seed)\n  ) +\n  stat_summary(\n    fun = mean, geom = \"point\", shape = 4, size = 3.4,\n    stroke = 1.0, colour = \"#1A1A1A\"\n  ) +\n  scale_fill_manual(values = treatment_palette, guide = \"none\") +\n  scale_x_discrete(labels = c(\n    \"Ambient + Unclipped\" = \"Ambient\\nUnclipped\",\n    \"Ambient + Clipped\" = \"Ambient\\nClipped\",\n    \"Warmed + Unclipped\" = \"Warmed\\nUnclipped\",\n    \"Warmed + Clipped\" = \"Warmed\\nClipped\"\n  )) +\n  labs(\n    title = \"PERMDISP tests spread, not group location\",\n    subtitle = sprintf(\n      \"Spatial median, bias-adjusted; F = %.3f, restricted P = %s\",\n      dispersion_global$FValue, format_p(dispersion_global$PValue)\n    ),\n    x = \"Treatment\", y = \"Distance to spatial median\",\n    caption = paste(\n      \"Points are 24 biological soil samples; crosses are group means of the distances.\",\n      \"A non-significant result is not proof that dispersions are identical.\",\n      sep = \"\\n\"\n    )\n  ) +\n  theme_pub(base_size = 9) +\n  theme(\n    panel.grid.major.x = element_blank(),\n    axis.text.x = element_text(size = 8.2, lineheight = 0.9)\n  )\n\nsave_pub(\n  dispersion_plot, \"figures/23-dispersion-by-treatment\",\n  width = 183, height = 104\n)\ndispersion_plot\n```\n\n::: {.cell-output-display}\n![四组到 spatial median 的完整距离分布与受限 PERMDISP。](23-permanova-dispersion_files/figure-html/fig-dispersion-1.png){#fig-dispersion}\n:::\n:::\n\n\n四张主图均生成 PDF、SVG、600 ppi PNG 与 LZW-compressed TIFF。PDF/SVG 是排版主文件，PNG 适合网页与公众号，TIFF 用于要求高分辨率位图的投稿系统。\n\n### 对完整分析做机器回验\n\n验证器会重新读取三件套，核对输入 checksum、实验单位聚合、1,824-feature 主 filter、262,144 个合法 assignments、9,999 行唯一置换、omnibus/factorial/pairwise/PERMDISP/ANOSIM/MRPP、四条敏感性分支、字体和四种图形格式：\n\n\n::: {.cell}\n\n```{.bash .cell-code}\nRscript --vanilla scripts/validate_permanova_dispersion.R \\\n  --project-root . \\\n  --input-dir data/small/permanova-dispersion \\\n  --output-dir results/23-permanova-dispersion \\\n  --figure-dir figures\n```\n:::\n\n\n审计结果存在时，下面代码要求 214 项全部通过；只使用前面的分析代码时不依赖该目录。\n\n\n::: {.cell}\n\n```{.r .cell-code}\naudit_summary_path <- paste0(\n  \"results/23-permanova-dispersion/\",\n  \"permanova-dispersion-summary.json\"\n)\nif (file.exists(audit_summary_path)) {\n  audit_summary <- jsonlite::read_json(\n    audit_summary_path, simplifyVector = TRUE\n  )\n  stopifnot(\n    audit_summary$checks_total == 214L,\n    audit_summary$checks_passed == 214L,\n    audit_summary$checks_failed == 0L,\n    audit_summary$dataset$features == 16825L,\n    audit_summary$dataset$technical_libraries == 56L,\n    audit_summary$dataset$biological_samples == 24L,\n    audit_summary$standardization$features_retained == 1824L,\n    audit_summary$permutations$possible == 262144L,\n    audit_summary$permutations$primary == 9999L,\n    audit_summary$analysis$factorial_rejections_holm == 0L,\n    audit_summary$analysis$pairwise_rejections_holm == 0L,\n    audit_summary$graphics$primary_figures == 4L,\n    audit_summary$graphics$format_files == 16L\n  )\n  unlist(audit_summary[c(\"checks_total\", \"checks_passed\", \"checks_failed\")])\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n checks_total checks_passed checks_failed \n          214           214             0 \n```\n\n\n:::\n:::\n\n\n## 常见坑 {#sec-pitfalls}\n\n::: {.callout-caution title=\"审稿人最常追问的十件事\"}\n\n1. **把 PCR、tag、测序 lane 或重复抽提当独立样本。** 技术重复共享同一 treatment label，不能增加 biological replication。\n2. **只限制在 block 内自由置换。** split-plot 还要求 whole plot 整体交换、subplot 只在自己的 main plot 内交换。\n3. **报告 999 或 9,999 次置换，却不报告可交换单位。** 如果只有 4 个 pair，理论 P 值网格不会因重复抽样变得无限精细。\n4. **PERMANOVA 显著就停止。** 必须同时报告 PERMDISP；显著 dispersion 会使 location 解释不唯一。\n5. **把 PERMDISP 不显著写成“方差相等”。** 未拒绝原假设不等于证明完全一致，尤其在每组只有 6 个生物学样本时。\n6. **只报 P 值，不报 (R^2)。** P 值依赖样本量和置换空间；total/partial (R^2) 说明效应在什么分母上有多大。\n7. **看到 factorial raw P < 0.05 就挑一项写结论。** 本例 Clipping 与 interaction 的 raw P 分别为 0.0489、0.0400，但同一三项 family 的 Holm P 都是 0.120。\n8. **总体显著后无限追加 pairwise PERMANOVA。** contrasts 与 multiplicity family 应在看结果前定义；本例四个计划比较没有一个通过 Holm。\n9. **把 ANOSIM/MRPP 的小 P 当作重复验证。** 本例 (R) 与 (A) 都为负，方向与“组内更相似”相反。\n10. **根据哪个 filter 显著来选择 feature space。** 主 filter 必须由测量与研究问题预先确定；完整表的受限 P = 0.7642 是必须保留的稳健性警告。\n\n:::\n\n::: {.callout-warning title=\"排序图不决定置换方案\"}\nPCoA 中点的颜色、椭圆和 hull 都不会告诉软件哪些标签可交换。exchangeability 只能来自随机化、采样和重复测量记录；缺少这份记录时，最漂亮的图也不能修复无效 P 值。\n:::\n\n## 报告置换设计与群落差异的方法与限制 {#sec-methods}\n\n下面英文与本例实际代码和结果一致：\n\n> PCR/tag technical libraries were summed within each biological soil sample before inference, yielding 24 biological units arranged as a 2 × 2 warming-by-clipping split-plot experiment in six blocks. Features were prespecified for the primary analysis when detected in at least four tagged libraries in any one treatment, retaining 1,824 of 16,825 OTUs. Bray–Curtis dissimilarities were calculated from sample-wise relative abundances. The primary four-level treatment effect was tested with PERMANOVA after fitting block first. A seed-fixed set of 9,999 unique non-identity permutations was sampled without replacement from the 262,144 assignments allowed by the block, whole-plot, and within-main-plot randomization. Treatment explained 9.81% of total distance variation (partial R² = 18.47%; pseudo-F = 1.133; P = 0.0065), whereas block accounted for 46.89% of total variation. Warming, clipping, and their interaction were decomposed descriptively and adjusted as one three-test family using Holm's procedure; no term remained significant. Four prespecified simple effects were tested using all 63 non-identity paired swaps across the six blocks and adjusted as one Holm family; no comparison met the adjusted 0.05 threshold. Multivariate dispersion was assessed on the same distance matrix using bias-adjusted distances to spatial medians and the same restricted permutation matrix (PERMDISP F = 0.403, P = 0.3714). ANOSIM and MRPP were retained only as directional sensitivity analyses. Repeating the valid restricted analysis without prevalence filtering changed the omnibus P value to 0.7642, so inference was treated as sensitive to feature filtering.\n\n正式稿还要补充：每层随机化发生在何时、每个 biological sample 的定义、技术重复为何合并、样本排除、primary distance/filter 的预注册依据，以及是否还有 batch、site、subject 或时间结构。\n\n## 将置换设计与群落差异用于自己的研究 {#sec-own-data}\n\n### 只替换路径和 metadata 列名\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninput_paths <- c(\n  otutab = \"your_project/otutab.tsv\",\n  taxonomy = \"your_project/taxonomy.tsv\",\n  metadata = \"your_project/metadata.tsv\"\n)\ngroup_col <- \"Treatment\"\nblock_col <- \"Block\"\nunit_col <- \"BiologicalSampleID\"\n\notutab <- data.matrix(read_keyed_tsv(input_paths[[\"otutab\"]]))\ntaxonomy <- read_keyed_tsv(input_paths[[\"taxonomy\"]])\nmetadata <- read_keyed_tsv(input_paths[[\"metadata\"]])\n\nstopifnot(\n  setequal(rownames(otutab), rownames(taxonomy)),\n  setequal(colnames(otutab), rownames(metadata)),\n  all(c(group_col, unit_col) %in% colnames(metadata))\n)\nmetadata <- metadata[colnames(otutab), , drop = FALSE]\nmetadata$AnalysisGroup <- factor(metadata[[group_col]])\n```\n:::\n\n\n最低输入要求：\n\n- `otutab`：feature × sample/library 的非负原始 counts；\n- `taxonomy`：feature ID 与 `otutab` 一致，本检验不要求按 taxonomy 聚合；\n- `metadata`：至少有 treatment 与真正实验单位列；\n- 配对、subject、time、site、block、main plot、cage、family、center、batch 等列必须保留；\n- 图内中文分组先 recode 成英文；\n- primary filter、standardization、distance、model terms、contrasts 和 multiplicity family 在看 P 值前写下。\n\n### 完全独立样本分支\n\n只有当每一列就是一个独立实验单位、没有配对或聚类时，才可自由置换：\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunity <- t(otutab)\nrelative <- sweep(community, 1L, rowSums(community), \"/\")\ndistance <- vegan::vegdist(relative, method = \"bray\")\n\nset.seed(20260723)\nfree_control <- permute::how(\n  within = permute::Within(type = \"free\"),\n  nperm = 9999\n)\nfree_matrix <- permute::shuffleSet(\n  n = nrow(metadata), nset = 9999, control = free_control\n)\n\nfit <- vegan::adonis2(\n  distance ~ AnalysisGroup,\n  data = metadata,\n  permutations = free_matrix,\n  by = \"terms\"\n)\ndisp <- vegan::betadisper(\n  distance, metadata$AnalysisGroup,\n  type = \"median\", bias.adjust = TRUE\n)\ndisp_test <- vegan::permutest(disp, permutations = free_matrix)\nfit\ndisp_test\n```\n:::\n\n\n### 简单 complete-block 或 paired 分支\n\n若每个 block/subject 下各 treatment 恰好一次，可把交换限制在 block 内：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(block_col %in% colnames(metadata))\nmetadata$AnalysisBlock <- factor(metadata[[block_col]])\n\nblocked_control <- permute::how(\n  blocks = metadata$AnalysisBlock,\n  within = permute::Within(type = \"free\"),\n  nperm = 9999\n)\npossible <- permute::numPerms(nrow(metadata), control = blocked_control)\nnset <- min(9999L, possible - 1L)\nblocked_matrix <- permute::shuffleSet(\n  nrow(metadata), nset = nset, control = blocked_control\n)\n\nfit <- vegan::adonis2(\n  distance ~ AnalysisBlock + AnalysisGroup,\n  data = metadata,\n  permutations = blocked_matrix,\n  by = \"terms\"\n)\nfit\n```\n:::\n\n\n这里仍要核对每个 block 内的 treatment balance。若 subject 有基线/末次、缺失 visit、carryover 或不等间隔时间，普通 block 内自由置换未必对应原始设计。\n\n### split-plot、纵向或多层聚类分支\n\n复杂设计先画出随机化树，再为每层写出：\n\n1. 哪个因子在哪一层随机；\n2. 哪些标签能整体交换；\n3. 哪些标签只能在 parent unit 内交换；\n4. 哪些重复观测完全不能彼此置换；\n5. 理论 permutation space 有多大；\n6. 每一行显式置换矩阵是否满足这些规则。\n\n`permute::how()`支持 blocks、plots、within，以及 `free`、`series`、`grid` 等结构；但软件参数不能替代真实随机化记录。若设计像本例一样包含 whole plot 和 subplot，建议保存显式 permutation matrix、identity/duplicate/legal-row audit 和 SHA-256，而不是只在 Methods 写“permutations were stratified”。\n\n### 为每个结论保留四件证据\n\n最终结果至少同时输出：\n\n- PERMANOVA pseudo-F、total/partial (R^2)、P 和实际置换数；\n- PERMDISP center definition、bias adjustment、F 和 P；\n- primary 与 sensitivity branches 的完整表，不只保留显著分支；\n- 每个 planned contrast 的样本数、配对/区组数、P 值分辨率、效应量和 multiplicity-adjusted P。\n\n这样图上的组间分离才有一条可审计的路径，从实验单位一直追溯到最终结论。\n\n## 参考 {#sec-references}\n\n- Zhou J, Wu L, Deng Y, et al. Reproducibility and quantitation of amplicon sequencing-based detection. *ISME Journal*. 2011;5:1303–1313. [doi:10.1038/ismej.2011.11](https://doi.org/10.1038/ismej.2011.11)\n- McMurdie PJ, Holmes S. phyloseq: an R package for reproducible interactive analysis and graphics of microbiome census data. *PLoS ONE*. 2013;8(4):e61217. [doi:10.1371/journal.pone.0061217](https://doi.org/10.1371/journal.pone.0061217)\n- Anderson MJ. A new method for non-parametric multivariate analysis of variance. *Austral Ecology*. 2001;26(1):32–46. [doi:10.1111/j.1442-9993.2001.01070.pp.x](https://doi.org/10.1111/j.1442-9993.2001.01070.pp.x)\n- Anderson MJ. Distance-based tests for homogeneity of multivariate dispersions. *Biometrics*. 2006;62(1):245–253. [doi:10.1111/j.1541-0420.2005.00440.x](https://doi.org/10.1111/j.1541-0420.2005.00440.x)\n- Warton DI, Wright ST, Wang Y. Distance-based multivariate analyses confound location and dispersion effects. *Methods in Ecology and Evolution*. 2012;3(1):89–101. [doi:10.1111/j.2041-210X.2011.00127.x](https://doi.org/10.1111/j.2041-210X.2011.00127.x)\n- Holm S. A simple sequentially rejective multiple test procedure. *Scandinavian Journal of Statistics*. 1979;6(2):65–70. [JSTOR 4615733](https://www.jstor.org/stable/4615733)\n- Oksanen J, Simpson GL, Blanchet FG, et al. vegan: Community Ecology Package. [`adonis2` documentation](https://vegandevs.github.io/vegan/reference/adonis.html) and [`betadisper` documentation](https://vegandevs.github.io/vegan/reference/betadisper.html).\n- Simpson GL. permute: Functions for Generating Restricted Permutations of Data. [`permutation design documentation`](https://vegandevs.github.io/permute/reference/how.html).\n",
    "supporting": [
      "23-permanova-dispersion_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  },
  "editorial_refresh": {
    "kind": "headings-and-links-only",
    "previous_source_hash": "c82cbfc1364ceb9ca0a9efcd805990ac",
    "fenced_code_and_output_unchanged": true,
    "full_R_code_verified": true,
    "native_stage_reused_from_verified_fresh_R_run": false
  }
}
